### PR TITLE
[core] Update placement group retry implementation

### LINKED ISSUE #18541: [release] many_ppo failing: "There was timeout in removing the placement group "
### What is the problem?

Weekly long running tests:

```
2021-09-12 04:13:06,836 INFO log_timer.py:27 -- NodeUpdater: ins_UBpk1QT7cF9Xpx681xfUQFYV: Got IP  [LogTimer=63ms]
Traceback (most recent call last):
  File "workloads/many_ppo.py", line 41, in <module>
    callbacks=[ProgressCallback()])
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 711, in run_experiments
    callbacks=callbacks).trials
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/tune.py", line 588, in run
    runner.step()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 646, in step
    self._run_and_catch(self.trial_executor.on_step_end)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/trial_runner.py", line 396, in _run_and_catch
    func(self.get_trials())
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/ray_trial_executor.py", line 988, in on_step_end
    self._pg_manager.cleanup()
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/tune/utils/placement_groups.py", line 296, in cleanup
    remove_placement_group(pg)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 122, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/util/placement_group.py", line 253, in remove_placement_group
    worker.core_worker.remove_placement_group(placement_group.id)
  File "python/ray/_raylet.pyx", line 1488, in ray._raylet.CoreWorker.remove_placement_group
  File "python/ray/_raylet.pyx", line 158, in ray._raylet.check_status
ray.exceptions.GetTimeoutError: There was timeout in removing the placement group of id eb068a103a8de03cd6ec0544849331b4. It is probably because GCS server is dead or there's a high load there.
(pid=44646, ip=172.31.89.10) 2021-09-12 04:14:16,933    WARNING trainer_template.py:186 -- `execution_plan` functions should accept `trainer`, `workers`, and `config` as args!
(pid=44646, ip=172.31.89.10) 2021-09-12 04:14:16,933    INFO trainable.py:111 -- Trainable.setup took 73.185 seconds. If your trainable is slow to initialize, consider setting reuse_actors=True to reduce actor creation overheads.
(pid=44646, ip=172.31.89.10) 2021-09-12 04:14:16,934    WARNING util.py:57 -- Install gputil for GPU system monitoring.
```

Failing after 1 hour (we see this sometimes in the nightly tests, too):

https://buildkite.com/ray-project/periodic-ci/builds/963#532e36d2-7d77-42a1-aa67-b6837f5a64f6
https://buildkite.com/ray-project/periodic-ci/builds/967#49b3cc43-6c31-4eed-9922-55744fe03ddb

cc @rkooo567 @ericl 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

Please check the ticket for more detail of this PR. 

Previously, we always post a retry task even there is one in the queue because the waiting is implemented based on defer submission. There are several problems here:
- retry accumulates in the pool
- the retried one doesn't schedule the failed one in some cases
- more complicated retry is not supported.

This PR fixed this issue:

* Use priority queue for pending placement group
* Don't use io context for retry
* Exponential backoff for retry

## Related issue number
Closes #18541

#18651 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
I'm working on unit testing.
e2e test is running.

File: src/ray/common/ray_config_def.h [hunk 1]
```diff
@@ -236,8 +236,10 @@ RAY_CONFIG(uint64_t, gcs_redis_heartbeat_interval_milliseconds, 100)
 RAY_CONFIG(uint32_t, gcs_lease_worker_retry_interval_ms, 200)
 /// Duration to wait between retries for creating actor in gcs server.
 RAY_CONFIG(uint32_t, gcs_create_actor_retry_interval_ms, 200)
-/// Duration to wait between retries for creating placement group in gcs server.
-RAY_CONFIG(uint32_t, gcs_create_placement_group_retry_interval_ms, 200)
+/// Exponential backoff params for gcs to retry creating a placement group
+RAY_CONFIG(uint32_t, gcs_create_placement_group_retry_min_interval_ms, 200)
+RAY_CONFIG(uint32_t, gcs_create_placement_group_retry_max_interval_ms, 1000)
```
Comment (ericl) [inline src/ray/common/ray_config_def.h:241]: Any reason not to make the max higher, like 5000? Otherwise seems we can simplify and combine these both into one 500ms interval.

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.h [hunk 2]
```diff
@@ -324,10 +332,9 @@ class GcsPlacementGroupManager : public rpc::PlacementGroupInfoHandler {
 
   /// The pending placement_groups which will not be scheduled until there's a resource
   /// change.
```
Comment (ericl) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.h:334]: Can you update the comment to describe the key semantics and how this reduces resource usage?

**Review by ericl — COMMENTED** [review]
Very nice!

File: src/ray/common/ray_config_def.h (hunk 1 above)
Comment (iycheng) [reply src/ray/common/ray_config_def.h:241]: 5000 looks good to me.

**Review by ericl — APPROVED** [review]

File: python/ray/tune/tests/test_trial_runner_pg.py [hunk 3]
```diff
@@ -120,25 +118,14 @@ def on_step_end(self, iteration, trials, **info):
                     scheduled,
                     min(scheduled, len(trials)),
                     msg=f"Num trials iter {iteration}")
-
-                # The following two tests were relaxed for reuse_actors=True
-                # so that up to `max_num_parallel` more placement groups can
-                # exist than we would expect. This is because caching
-                # relies on reconciliation for cleanup to avoid overscheduling
-                # of new placement groups.
-                num_parallel_reuse = int(reuse_actors) * max_num_parallel
```
Comment (rkooo567) [inline python/ray/tune/tests/test_trial_runner_pg.py:129]: Why do we change this?

File: python/ray/tune/utils/placement_groups.py [hunk 4]
```diff
@@ -298,14 +293,8 @@ def cleanup(self, force: bool = False):
             if force or (time.time() -
                          self._removal_delay) >= self._pgs_for_removal[pg]:
                 self._pgs_for_removal.pop(pg)
-
                 remove_placement_group(pg)
 
-                # Remove from unstaged cache
-                if pg in self._unstaged_pg_pgf:
```
Comment (rkooo567) [inline python/ray/tune/utils/placement_groups.py:305]: Same here. Is it related to this PR, or is it because you reverted for testing?

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 5]
```diff
@@ -241,31 +241,25 @@ void GcsPlacementGroupManager::OnPlacementGroupCreationFailed(
       // NOTE: If a node is dead, the placement group scheduler should try to recover the
       // group by rescheduling the bundles of the dead node. This should have higher
       // priority than trying to place other placement groups.
-      pending_placement_groups_.emplace_front(std::move(placement_group));
+      AddToPendingQueue(std::move(placement_group), 0);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:244]: 0 is confusing here. Can you write the argumenet name in the code like this? 

```suggestion
      AddToPendingQueue(std::move(placement_group), /*[argument_name]*/0);
```

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 6]
```diff
@@ -294,16 +290,25 @@ void GcsPlacementGroupManager::SchedulePendingPlacementGroups() {
 
   bool is_new_placement_group_scheduled = false;
   while (!pending_placement_groups_.empty() && !is_new_placement_group_scheduled) {
-    const auto placement_group = pending_placement_groups_.front();
-    pending_placement_groups_.pop_front();
+    auto iter = pending_placement_groups_.begin();
+    // Nothing to schedule
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:294]: Can you write a comment about why we only need to check the first entry?

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 7]
```diff
@@ -573,9 +570,36 @@ void GcsPlacementGroupManager::WaitPlacementGroup(
...
+  pending_placement_groups_.emplace(*rank, val);
+}
+
+void GcsPlacementGroupManager::RemoveFromPendingQueue(const PlacementGroupID &pg_id) {
+  auto it = std::find_if(pending_placement_groups_.begin(),
+                         pending_placement_groups_.end(), [&pg_id](const auto &val) {
+                           return val.second.second->GetPlacementGroupID() == pg_id;
+                         });
+  if (it != pending_placement_groups_.end()) {
+    pending_placement_groups_.erase(it);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:601]: Can you preserve this comment here? `    // The placement group was pending scheduling, remove it from the queue.
`

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 8]
```diff
@@ -573,9 +570,36 @@ void GcsPlacementGroupManager::WaitPlacementGroup(
...
+            RayConfig::instance().gcs_create_placement_group_retry_min_interval_ms(),
+        RayConfig::instance().gcs_create_placement_group_retry_multiplier(),
+        1000000 *
+            RayConfig::instance().gcs_create_placement_group_retry_max_interval_ms());
+  } else {
+    *rank += static_cast<int64_t>(exp_backer->Next());
+  }
+  auto val = std::make_pair<ExponentialBackOff, std::shared_ptr<GcsPlacementGroup>>(
+      *exp_backer, std::move(pg));
+  pending_placement_groups_.emplace(*rank, val);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:592]:
```suggestion
  pending_placement_groups_.emplace(*rank, std::make_pair<ExponentialBackOff, std::shared_ptr<GcsPlacementGroup>>(
      *exp_backer, std::move(pg)));
```

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 9]
```diff
@@ -294,16 +290,25 @@ void GcsPlacementGroupManager::SchedulePendingPlacementGroups() {
 
   bool is_new_placement_group_scheduled = false;
   while (!pending_placement_groups_.empty() && !is_new_placement_group_scheduled) {
-    const auto placement_group = pending_placement_groups_.front();
-    pending_placement_groups_.pop_front();
+    auto iter = pending_placement_groups_.begin();
+    // Nothing to schedule
+    if (iter->first > absl::GetCurrentTimeNanos()) {
+      break;
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:296]: I am a little confused about how this will be retried. Is it retried by the Tick in this case? (If so can we comment it?)

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 10]
```diff
@@ -593,7 +617,7 @@ void GcsPlacementGroupManager::OnNodeDead(const NodeID &node_id) {
       // creating until a node with the resources is added. we will solve it in next pr.
       if (iter->second->GetState() != rpc::PlacementGroupTableData::RESCHEDULING) {
         iter->second->UpdateState(rpc::PlacementGroupTableData::RESCHEDULING);
-        pending_placement_groups_.emplace_front(iter->second);
+        AddToPendingQueue(iter->second, 0);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:620]: Can you add a comment to the argument 0? 
```suggestion
        AddToPendingQueue(iter->second, /*[arg_name]*/0);
```

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc [hunk 11]
```diff
@@ -526,7 +532,8 @@ TEST_F(GcsPlacementGroupManagerTest, TestSchedulingCanceledWhenPgIsInfeasible) {
   mock_placement_group_scheduler_->placement_groups_.clear();
 
   // Mark it non-retryable.
-  gcs_placement_group_manager_->OnPlacementGroupCreationFailed(placement_group, false);
+  gcs_placement_group_manager_->OnPlacementGroupCreationFailed(placement_group,
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc:535]: Can you add a test that tests the exponential back off retry?

File: src/ray/gcs/test/gcs_test_util.h [hunk 12]
```diff
@@ -104,6 +104,7 @@ struct Mocker {
     PlacementGroupSpecBuilder builder;
 
     auto placement_group_id = PlacementGroupID::FromRandom();
+    RAY_LOG(INFO) << "PlacementGroupID: " << placement_group_id.Hex();
```
Comment (rkooo567) [inline src/ray/gcs/test/gcs_test_util.h:107]: Remove it!

File: src/ray/util/util.h [hunk 13]
```diff
@@ -312,4 +312,36 @@ class ThreadPrivate {
   mutable std::mutex mutex_;
 };
 
+class ExponentialBackOff {
```
Comment (rkooo567) [inline src/ray/util/util.h:315]: Can you add a docstring to the class?

File: src/ray/util/util.h [hunk 14]
```diff
@@ -312,4 +312,36 @@ class ThreadPrivate {
...
+ public:
+  ExponentialBackOff() = default;
+  ExponentialBackOff(const ExponentialBackOff &) = default;
+  ExponentialBackOff(ExponentialBackOff &&) = default;
+  ExponentialBackOff &operator=(const ExponentialBackOff &) = default;
+  ExponentialBackOff &operator=(ExponentialBackOff &&) = default;
+  ExponentialBackOff(double initial_value, double multiplier, double max_value = 0.0)
```
Comment (rkooo567) [inline src/ray/util/util.h:322]: Does max_value == 0.0 mean we will never try exponential backoff?

Comment (rkooo567) [reply src/ray/util/util.h:322]: Maybe also writing the docstring here?

File: python/ray/tune/tests/test_trial_runner_pg.py (hunk 3 above)
Comment (iycheng) [reply python/ray/tune/tests/test_trial_runner_pg.py:129]: it's included accidentially. when I'm testing the revert.

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc (hunk 9 above)
Comment (iycheng) [reply src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:298]: Yes, for this case, it'll be covered by Tick

**Comment by iycheng** [comment]
@rkooo567  test has been added.

**Review by rkooo567 — COMMENTED** [review]
Have a couple last comments! Also, can you try running the placement group stress test and compare the performance from the nightly?

**Review by rkooo567 — CHANGES_REQUESTED** [review]
change requested to avoid merging it accidently

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc [hunk 15]
```diff
@@ -0,0 +1,135 @@
...
+      1000000 * RayConfig::instance().gcs_create_placement_group_retry_min_interval_ms());
+  ASSERT_EQ(1, pending_queue.size());
+  auto rank = pending_queue.begin()->first;
+  ASSERT_LT(now + next, rank);
+  // ScheduleUnplacedBundles is not called here
+  gcs_placement_group_manager_->SchedulePendingPlacementGroups();
+  ASSERT_EQ(1, pending_queue.size());
+  ASSERT_EQ(rank, pending_queue.begin()->first);
+
+  absl::SleepFor(absl::Nanoseconds(rank - absl::GetCurrentTimeNanos()));
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:123]: I actually feel this is fine. Using the fake timer in the code just for testing makes the code complicated.
It's less than 1s here.

**Comment by iycheng** [comment]
new
```
  success = 1                                                                                                                                                                                                                                                             avg_pg_create_time_ms = 1.1399193753719132                                                                                                                                                                                                                              avg_pg_remove_time_ms = 4.032320572071604                                                                                                                                                                                                                               _runtime = 479.986270904541                                                                                                                                                                                                                                             _session_url = https://beta.anyscale.com/o/anyscale-internal/projects/prj_LFKjNprpiYt4AjAf1NdLDJwn/clusters/ses_yjTUA8gaZDSjF43Et5YJHfj5                                                                                                                                _commit_url = https://ray-wheels.s3.us-west-2.amazonaws.com/test_wheels/pg-schedule/01b13b601bca5f168fbb367341f330db191c9e83/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl                                                                                         _stable = True
```

**Comment by iycheng** [comment]
prod
```




success = 1
  | avg_pg_create_time_ms = 1.0101662852838733
  | avg_pg_remove_time_ms = 4.4615456231242465
  | _runtime = 461.87430810928345
  | _session_url = https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_K3pD2PKyVqkGDV4iD4XBdqrX
  | _commit_url = https://s3-us-west-2.amazonaws.com/ray-wheels/master/6dc1a6b72f687c8ed8bcb8e687d928afd442f5f5/ray-2.0.0.dev0-cp37-cp37m-manylinux2014_x86_64.whl
  | _stable = True
 ````

**Comment by iycheng** [comment]
@rkooo567  it's good for another look now

**Review by rkooo567 — APPROVED** [review]

File: BUILD.bazel [hunk 16]
```diff
@@ -1513,20 +1529,20 @@ cc_test(
...
-#     ],
-#     copts = COPTS,
-#     tags = ["team:core"],
-#     deps = [
-#         ":gcs_server_lib",
-#         ":ray_mock",
-#         "@com_google_googletest//:gtest_main",
-#     ],
-# )
+cc_test(
```
Comment (rkooo567) [inline BUILD.bazel:1532]: Is this relevant to this PR?

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.h [hunk 17]
```diff
@@ -284,6 +286,12 @@ class GcsPlacementGroupManager : public rpc::PlacementGroupInfoHandler {
   std::string DebugString() const;
 
  private:
+  /// Push a placement group to pending queue
+  void AddToPendingQueue(std::shared_ptr<GcsPlacementGroup> pg,
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_placement_group_manager.h:290]: Seems to be not updated?

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc (hunk 15 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:124]: Can you at least use wait for ...? Based on my experience having a absolute time sleep usually was the source of flakniess

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc [hunk 18]
```diff
@@ -0,0 +1,135 @@
...
+  gcs_placement_group_manager_->SchedulePendingPlacementGroups();
+  ASSERT_EQ(0, pending_queue.size());
+  pg->UpdateState(rpc::PlacementGroupTableData::PENDING);
+  now = absl::GetCurrentTimeNanos();
+  failure_callback(pg, true);
+  next = RayConfig::instance().gcs_create_placement_group_retry_multiplier() * next;
+  ASSERT_EQ(1, pending_queue.size());
+  ASSERT_LT(now + next, pending_queue.begin()->first);
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:132]: Just a ping if this is handled?

**Review by rkooo567 — COMMENTED** [review]
Last comments.

File: BUILD.bazel (hunk 16 above)
Comment (iycheng) [reply BUILD.bazel:1532]: No. But if you ask, I can move it to another PR.

Comment (rkooo567) [reply BUILD.bazel:1532]: I think this is fine, but why is it here? Was it intentional? (I wondered if it has bad merge with the master or sth initially)

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc (hunk 15 above)
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:124]: If 
```
  absl::SleepFor(absl::Nanoseconds(rank - absl::GetCurrentTimeNanos()));
```
will guarentee  `rank - absl::GetCurrentTimeNanos() + e (e >= 0)` suspension of the code, it's ok. `e` is the scheduling latency here.
I don't think wait for is a better choice here. 
How about this, let me run it for 100 times and if it's good, we are good here?

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc (hunk 18 above)
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:132]: Could you check 
`TEST_F(GcsPlacementGroupManagerMockTest, PendingQueuePriorityOrder)`
and 
`TEST(UtilTest, ExponentialBackOffTest)`

[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:132]: ah I found it! Thanks!

**Review by rkooo567 — APPROVED** [review]
LGTM. Feel free to merge if tests pass!

File: BUILD.bazel (hunk 16 above)
Comment (iycheng) [reply BUILD.bazel:1532]: Yes. I think it's actually bad behavior to mix things not related to this PR here. 

It's intentional... I feel shame about this... Let me remove this change and submit another PR for this.

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc (hunk 15 above)
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:124]: Let me justify what I mean here and let me know if it doesn't make sense and I can change it to use wait for.


Here if we `sleep s` seconds, usually it'll be `s + e`, where `e` equals the delay of os scheduling. 

So after executing this line, the time must be greater than rank. 

So in 125, it'll start to schedule the first one.

in L129, we'll have new rank  `r` where `r = t(the time when we push it back to queue) + (next) failed_delay`. `t > now` so `t + next = r > now + next` (L132).


Here the trick I'm using is that I use LT to compare the time, so if the theory stands, it's ok.

**Comment by iycheng** [comment]
@rkooo567 just updated it.  let me know if I missed anything

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc (hunk 15 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/gcs/gcs_server/test/gcs_placement_group_manager_mock_test.cc:124]: Gotcha. I think it makes sense, and it is less likely that there's unexpected flakiness because it has pretty straightforward dependencies (unlike Ray python tests which has so many unexpected scenarios). I am okay with keeping it

**Comment by rkooo567** [comment]
Screen Shot 2021-10-04 at 3 56 21 PM

Seems like this fails

**Comment by iycheng** [comment]
> Screen Shot 2021-10-04 at 3 56 21 PM
> 
> Seems like this fails

Checked this. Change LT to LE because of lock resolutions is us and within 1us it finished the code.

**Comment by iycheng** [comment]
windows test of `//python/ray/tests:test_client_reconnect` is flaky

File: src/ray/gcs/gcs_server/gcs_placement_group_manager.cc [hunk 19]
```diff
@@ -580,10 +580,36 @@ void GcsPlacementGroupManager::WaitPlacementGroup(
...
+void GcsPlacementGroupManager::AddToPendingQueue(
+    std::shared_ptr<GcsPlacementGroup> pg, std::optional<int64_t> rank,
+    std::optional<ExponentialBackOff> exp_backer) {
+  if (!rank) {
+    rank = absl::GetCurrentTimeNanos();
+  }
+
+  if (!exp_backer) {
+    exp_backer = ExponentialBackOff(
+        1000000 *
```
Comment (waleedkadous) [inline src/ray/gcs/gcs_server/gcs_placement_group_manager.cc:592]: What is 1000000? Why times 1000000 if it's ms?
