### PR TITLE
[core] Fix `JobID` check for detached actor tasks

### LINKED ISSUE #52090: Check failed: worker->GetAssignedJobId().IsNil() || worker->GetAssignedJobId() == task_spec.JobId()
### What happened + What you expected to happen

I submit a Job to RayCluster through API, which mainly processes data through Ray Data. At this point, Raylet crashes and Node restarts. This issue only appeared when I upgraded the Ray version to 2.38.0 or even higher, and below this version, this problem will not occur. I'm not sure what content was modified in version 2.38.0. And I can't provide a use case to reproduce it because it only appears when RayCluster submits a task

```
(raylet) [2025-03-21 00:01:19,595 C 338 338] (raylet) worker_pool.cc:1351:  Check failed: worker->GetAssignedJobId().IsNil() || worker->GetAssignedJobId() == task_spec.JobId() 
(raylet) *** StackTrace Information ***
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xbdf73a) [0x55dea26fa73a] ray::operator<<()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xbe1b21) [0x55dea26fcb21] ray::RayLog::~RayLog()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x3407f7) [0x55dea1e5b7f7] ray::raylet::WorkerPool::PopWorker()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x3a809c) [0x55dea1ec309c] ray::raylet::LocalTaskManager::DispatchScheduledTasksToWorkers()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x3a90c7) [0x55dea1ec40c7] ray::raylet::LocalTaskManager::QueueAndScheduleTask()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x48ee0c) [0x55dea1fa9e0c] ray::raylet::ClusterTaskManager::ScheduleOnNode()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x49200e) [0x55dea1fad00e] ray::raylet::ClusterTaskManager::ScheduleAndDispatchTasks()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x491c44) [0x55dea1facc44] ray::raylet::ClusterTaskManager::QueueAndScheduleTask()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x32536e) [0x55dea1e4036e] ray::raylet::NodeManager::HandleRequestWorkerLease()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x3170e7) [0x55dea1e320e7] ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x669e98) [0x55dea2184e98] EventTracker::RecordExecution()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x664e8e) [0x55dea217fe8e] std::_Function_handler<>::_M_invoke()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x665306) [0x55dea2180306] boost::asio::detail::completion_handler<>::do_complete()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc53f9b) [0x55dea276ef9b] boost::asio::detail::scheduler::do_run_one()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc56529) [0x55dea2771529] boost::asio::detail::scheduler::run()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc56a42) [0x55dea2771a42] boost::asio::io_context::run()
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x1e9155) [0x55dea1d04155] main
(raylet) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f3eb2fec083] __libc_start_main
(raylet) /home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x243277) [0x55dea1d5e277]
(raylet) 
``` 

### Versions / Dependencies

ray >=2.38.0
kuberay==1.3.1

### Reproduction script

Sorry, I am unable to provide a use case to reproduce this issue. Because it must submit a job through the API to appear.

### Issue Severity

None

### PR DESCRIPTION
**Pull request by edoakes**
## Why are these changes needed?

https://github.com/ray-project/ray/pull/47212 added [logic](https://github.com/ray-project/ray/pull/47212/files#diff-4c19d6ebd8575189e9439fa5646b567546dc54f64d576a959ce1bb43902d1a03R1178) to match task specs to workers based on the "root detached actor ID."

However, it introduced a bug where a task submitted by a detached actor or one of its descendent would bypass the `JobID` check. Tasks rooted in a detached actor inherit its job ID, so this meant a worker process from one job ID would be assigned a task from another job ID. This is *not* permitted and explicitly checked against in many parts of the code, including: `raylet/worker_pool.cc`, `raylet/worker.cc`, `core_worker/core_worker.cc`.

This PR modifies the logic to still check for a matching job ID in the case of root detached actor IDs.

I've added two sets of unit tests for `PopWorker` to guard against future breakages:

- `PopWorkerForRequestWithRootDetachedActor`: tests the matching logic for task specs with a root detached actor ID.
- `PopWorkerWithRootDetachedActorID`: tests the matching logic for workers with a root detached actor ID but requests without one.

## Related issue number

Closes https://github.com/ray-project/ray/issues/52090

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/worker_pool.cc [hunk 1]
```diff
@@ -1452,21 +1463,28 @@ std::shared_ptr<WorkerInterface> WorkerPool::FindAndPopIdleWorker(
     return false;
   };
   auto &state = GetStateForLanguage(pop_worker_request.language);
-  auto good_worker_it = std::find_if(idle_of_all_languages_.rbegin(),
+  auto worker_it = std::find_if(idle_of_all_languages_.rbegin(),
```
Comment (edoakes) [inline src/ray/raylet/worker_pool.cc:1466]: no behavior changes here; just reversed the early return logic

File: src/ray/raylet/worker_pool.cc [hunk 2]
```diff
@@ -1289,28 +1280,39 @@ WorkerUnfitForTaskReason WorkerPool::WorkerFitsForTask(
...
   }
 
-  if (!IdMatches(pop_worker_request.root_detached_actor_id,
-                 worker.GetRootDetachedActorId())) {
+  // For scheduling requests with a root detached actor ID, ensure that either the
+  // worker has _no_ detached actor ID or it matches the request.
+  // NOTE(edoakes): the job ID for a worker with no detached actor ID must still match,
+  // which is checked below. The pop_worker_request for a task rooted in a detached
+  // actor will have the job ID of the job that created the detached actor.
+  if (!pop_worker_request.root_detached_actor_id.IsNil() &&
```
Comment (israbbani) [inline src/ray/raylet/worker_pool.cc:1288]: Is this a behavior change? I think the invariant here is still if either the request or the worker has a root_detached_actor_id set, then it must match.

File: src/ray/raylet/worker_pool.cc [hunk 3]
```diff
@@ -1289,28 +1280,39 @@ WorkerUnfitForTaskReason WorkerPool::WorkerFitsForTask(
...
-  // Only compare job id for actors not rooted to a detached actor.
-  if (pop_worker_request.root_detached_actor_id.IsNil()) {
-    if (!IdMatches(pop_worker_request.job_id, worker.GetAssignedJobId())) {
-      return WorkerUnfitForTaskReason::ROOT_MISMATCH;
-    }
+
+  // Only consider workers that haven't been assigned to a job yet or have been assigned
+  // to the requested job.
+  const auto worker_job_id = worker.GetAssignedJobId();
+  if (!worker_job_id.IsNil() && pop_worker_request.job_id != worker_job_id) {
```
Comment (israbbani) [inline src/ray/raylet/worker_pool.cc:1297]: This is the behavior change, right? Previously, we would skip this check for requests that were from a detached actor and the job_id check would fail elsewhere.

**Review by israbbani — COMMENTED** [review]
I talked to @jjyao about this. I tried to write the invariants here are. Maybe they'll help with writing the PR description or tests:

1. This is only relevant for NORMAL_TASKs.
2. Actors inherit the job id of their ACTOR_CREATION_TASK.
3. Detached Actors are conceptually their own jobs.
4. If there is a detached actor on the task submission path, the PopWorkerRequest will contain the id of the closest ancestor that is a detached actor. 
  For example:
  detached_actor_1 -> task_A -> detached_actor_2 -> detached_actor_3 -> task_B -> task_C -> final_task
  The `root_detached_actor_id` for task_A is detached_actor_1
  The `root_detached_actor_id` for task_B is detached_actor_2
  The `root_detached_actor_id` for task_C is detached_actor_3
  The `root_detached_actor_id` for final_task is detached_actor_3
  
Overall, I think this fixes the bug. I appreciate the additional docs and style changes. Ping me when it's done and I'll review the tests.

File: src/ray/raylet/worker_pool.cc [hunk 4]
```diff
@@ -47,7 +47,6 @@ DEFINE_stats(worker_register_time_ms,
 
 namespace {
 
-// A helper function to get a worker from a list.
```
[the remark this answers is not in the document]
Comment (edoakes) [reply src/ray/raylet/worker_pool.cc:50]: agree

File: src/ray/raylet/worker_pool.cc [hunk 5]
```diff
@@ -70,27 +69,19 @@ std::shared_ptr<ray::raylet::WorkerInterface> GetWorker(
   return nullptr;
 }
 
-// A helper function to remove a worker from a list. Returns true if the worker
-// was found and removed.
+// Remove the worker from the set, returning true if it was present.
 bool RemoveWorker(
```
[the remark this answers is not in the document]
Comment (edoakes) [reply src/ray/raylet/worker_pool.cc:73]: haha :) I thought about removing it but ended up keeping it because I do think the `bool` return makes the callsites a bit more readable than the `> 0` check. probably wouldn't have added it myself

File: src/ray/raylet/worker_pool.cc (hunk 2 above)
Comment (edoakes) [reply src/ray/raylet/worker_pool.cc:1288]: This is not a behavior change. I just removed the `IdEquals` method to reduce confusion and wrote it in a way that (IMO) is more clear.

File: src/ray/raylet/worker_pool.cc (hunk 3 above)
Comment (edoakes) [reply src/ray/raylet/worker_pool.cc:1297]: that's correct

File: src/ray/raylet/worker_pool_test.cc [hunk 6]
```diff
@@ -926,6 +926,197 @@ TEST_F(WorkerPoolDriverRegisteredTest, PopWorkerMultiTenancy) {
...
+//   - Must be matched to workers that have a matching detached actor ID (or no detached
+//   actor ID).
+TEST_F(WorkerPoolDriverRegisteredTest, PopWorkerForRequestWithRootDetachedActor) {
+  auto job_1_id = JOB_ID;
+  auto job_2_id = JOB_ID_2;
+
+  // NOTE: in all test cases the request has job_1_detached_actor_1 as its root detached
+  // actor.
+  auto job_1_detached_actor_1_id = ActorID::Of(job_1_id, TaskID::FromRandom(job_1_id), 0);
+  auto task_spec_job_1_detached_actor_1 =
```
Comment (israbbani) [inline src/ray/raylet/worker_pool_test.cc:941]: nit: I'd follow the same pattern across different components of the same conceptual thing. E.g.

`job_1_detached_actor_1_id` is an ActorID but the name is prefixed with the job
`task_spec_job_1_detached_actor_1` is a TaskSpec, but the name is postfixed with the job and actor. 

I think picking one will make it easier to read e.g.: 

`detached_actor_1_id_job_1 `
`task_spec_detached_actor_1_job_1 `

File: src/ray/raylet/worker_pool_test.cc [hunk 7]
```diff
@@ -926,6 +926,197 @@ TEST_F(WorkerPoolDriverRegisteredTest, PopWorkerMultiTenancy) {
...
+            worker_job_1_no_detached_actor);
+  ASSERT_EQ(worker_pool_->GetIdleWorkerSize(), 0);
+
+  // Case 3 (match):
+  //   worker has matching root detached actor ID and job ID
+  auto worker_job_1_detached_actor_1 =
+      worker_pool_->CreateWorker(Process::CreateNewDummy(), Language::PYTHON, job_1_id);
+  RayTask job_1_detached_actor_1_task(task_spec_job_1_detached_actor_1);
+  worker_job_1_detached_actor_1->SetAssignedTask(job_1_detached_actor_1_task);
+  worker_job_1_detached_actor_1->AssignTaskId(TaskID::Nil());
```
Comment (israbbani) [inline src/ray/raylet/worker_pool_test.cc:972]: It doesn't look like there's a cleaner way to do this given the implementation of Worker 😢

File: src/ray/raylet/worker_pool_test.cc [hunk 8]
```diff
@@ -926,6 +926,197 @@ TEST_F(WorkerPoolDriverRegisteredTest, PopWorkerMultiTenancy) {
...
+  ASSERT_EQ(worker_pool_->GetIdleWorkerSize(), 1);
+  worker_job_2_no_detached_actor->MarkDead();
+  worker_pool_->TryKillingIdleWorkers();
+  ASSERT_EQ(worker_pool_->GetIdleWorkerSize(), 0);
+
+  // Case 5 (mismatch):
+  //   worker has mismatched detached actor ID and mismatched job ID
+  auto worker_job_2_detached_actor_3 =
+      worker_pool_->CreateWorker(Process::CreateNewDummy(), Language::PYTHON, job_2_id);
+  auto job_2_detached_actor_3_id = ActorID::Of(job_2_id, TaskID::FromRandom(job_2_id), 0);
```
Comment (israbbani) [inline src/ray/raylet/worker_pool_test.cc:996]: Did you mean `job_2_detached_actor_2_id`?

File: src/ray/raylet/worker_pool_test.cc [hunk 9]
```diff
@@ -926,6 +926,197 @@ TEST_F(WorkerPoolDriverRegisteredTest, PopWorkerMultiTenancy) {
   }
 }
 
+// Tests the worker assignment logic for task specs that have a root detached actor ID.
+// These tasks:
+//   - Must be matched to workers that have a matching job ID (or no job ID).
+//   - Must be matched to workers that have a matching detached actor ID (or no detached
+//   actor ID).
+TEST_F(WorkerPoolDriverRegisteredTest, PopWorkerForRequestWithRootDetachedActor) {
```
[the remark this answers is not in the document]
Comment (israbbani) [reply src/ray/raylet/worker_pool_test.cc:934]: I'm not sure if it will help. It took me a long time to read through all the cases in the test and if the test fails, it might be hard to pinpoint what caused it fail. 

Maybe separating it out into two tests, one where the workers can be assigned to the request and ones where workers cannot will help?

**Review by israbbani — APPROVED** [review]
LGTM. I left some nits. Thanks for writing the tests! 🚢

File: src/ray/raylet/worker_pool_test.cc (hunk 7 above)
Comment (edoakes) [reply src/ray/raylet/worker_pool_test.cc:972]: yeah it hurt a little bit. but mimics real usage at least

File: src/ray/raylet/worker_pool_test.cc (hunk 6 above)
Comment (edoakes) [reply src/ray/raylet/worker_pool_test.cc:941]: agreed; intended to do this but got sloppy, will fix

File: src/ray/raylet/worker_pool_test.cc (hunk 8 above)
Comment (edoakes) [reply src/ray/raylet/worker_pool_test.cc:996]: I named it `_3` because it was ambiguous before if `actor_2` was the same actor ID from job 1
