### PR TITLE
[Core] Allow failing new tasks immediately while the actor is restarting

### LINKED ISSUE #13594: [core] Fail submitted tasks immediately when an actor is temporarily unavailable
Currently, when an actor has `max_restarts` > 0 and crashed, the actor will enter RESTARTING state and then ALIVE. Imagine this scenario: an online service provides HTTP service and the proxy actor receives requests, forwards them to worker actors, and replies to clients with the execution results from worker actors.

```
                                                        -> Worker A (actor)
                                                       /
                                                      /
HTTP requests -------> Proxy (actor with HTTP server) ---> Worker B (actor)
                                                      \
                                                       \
                                                        -> ...
```

For each HTTP request, the proxy picks one worker (e.g. worker A) based on some algorithm, sends the request to it, and call `ray.get()` to wait for the result. If for some reason the picked worker crashed, Ray will restart the actor, and `ray.get()` will throw an error. The proxy may pick another worker (e.g. worker B) and re-send the request to it. This is OK.

But new requests keep coming. The proxy may pick worker A again. But because worker A is still in RESTARTING state, it's not ready to serve requests. This time, `ray.get()` will hang until worker A is back online (ALIVE state). The proxy won't be able to reschedule the request to another worker because it doesn't if worker A is alive or not. `ray.get()` hanging is probably just because the execution on worker requires quite a lot of time.

To solve this issue, in Ant internal repo, we added a new flag when creating an actor to control the strategy of submitting new tasks when the actor is in RESTARTING state. When the callee actor is in RESTARTING state, by default, newly submitted tasks will be queued in direct actor transport and only send them when the ALIVE state notification is received. But if the flag is turned on, newly submitted tasks will fail immediately with a RayActorError. This solution makes the fallback very quick when a worker is temporarily unavailable and improved P99 latency of the online service.

We hope we can contribute this back to community. @rkooo567 @stephanie-wang what do you think?

cc @raulchen @ffbin @jovany-wang @MissiontoMars

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

Currently, when an actor has `max_restarts` > 0 and has crashed, the actor will enter RESTARTING state and then ALIVE. Imagine this scenario: an online service provides HTTP service and the proxy actor receives requests, forwards them to worker actors, and replies to clients with the execution results from worker actors.

```
                                                        -> Worker A (actor)
                                                       /
                                                      /
HTTP requests -------> Proxy (actor with HTTP server) ---> Worker B (actor)
                                                      \
                                                       \
                                                        -> ...
```

For each HTTP request, the proxy picks one worker (e.g. worker A) based on some algorithm, sends the request to it, and calls `ray.get()` to wait for the result. If for some reason the picked worker crashed, Ray will restart the actor, and `ray.get()` will throw an error. The proxy may pick another worker (e.g. worker B) and re-send the request to it. This is OK.

But new requests keep coming. The proxy may pick worker A again. But because worker A is still in RESTARTING state, it's not ready to serve requests. `ray.get()` on subsequent requests sent to worker A will hang until worker A is back online (ALIVE state). The proxy won't be able to reschedule these requests to another worker because currently there's no way to know if worker A is alive or not before sending a request. We can't say worker A is not alive just based on whether `ray.get()` hangs either.

To solve this issue, we change the semantics of `max_task_retries`.

* When max_task_retries is 0 (which is the default value), if the callee actor is in the RESTARTING state, subsequently submitted tasks will fail immediately with a RayActorError. Users can catch the RayActorError and implement their own fallback strategies to improve service availability and mitigate service outages.
* When max_task_retries is not 0, subsequently submitted tasks will be queued on the caller side and we only send them to the callee when the callee actor is back to the ALIVE state.

TODO

- [x] Add test cases.
- [ ] Update docs.
- [x] API change review.

## Related issue number

Closes #13594

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kfstorm** [comment]
This is an Ant-internal feature and now we want to upstream it.

@stephanie-wang @edoakes Please raise if you have any questions about the design or implementation. Thanks!

@MissiontoMars Please review as well because the implementation in the submitter is different from our internal one.

**Comment by kfstorm** [comment]
## :bangbang: ACTION REQUIRED :bangbang:

We've updated our formatting configuration for C++ code. (see #22725)

This PR includes C++ code change. To prevent issues with merging your code, here's what you'll need to do:

1. Merge the latest changes from upstream/master branch into your branch.

```bash
git pull upstream master
git merge upstream/master
```

2. Resolve merge conflicts (if necessary).

After running these steps, you'll have the updated C++ formatting configuration.

3. Format changed files.

```bash
scripts/format.sh
```

4. Commit your changes.

```bash
git add --all
git commit -m "Format C++ code"
```

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc [hunk 1]
```diff
@@ -485,6 +501,18 @@ void CoreWorkerDirectActorTaskSubmitter::PushActorTask(ClientQueue &queue,
         reply_callback(status, reply);
       };
 
+  if (force_fail) {
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_task_submitter.cc:504]: Do we have to go through the PushActorTask logic here? Why not just do it in SendPendingTasks when we first assign force_fail? That seems like it would produce fewer code changes.

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Please update the PR description and add unit tests for the changes in direct actor transport.

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc (hunk 1 above)
Comment (kfstorm) [reply src/ray/core_worker/transport/direct_actor_task_submitter.cc]: Code updated. I moved the `if` to `SendPendingTasks`. Due to the fact that we need to reuse the reply callback for failure handling, I created a new private method `ReplyCallback` to hold the callback logic.

**Comment by kfstorm** [comment]
@stephanie-wang Python API, C++ UT, and Python UT added. Please help review again.

cc @pcmoritz for API changes.

Maybe we need to consider a better name for the new flag.

Documents will be added later.

**Comment by kfstorm** [comment]
@stephanie-wang @pcmoritz Any comments?

**Comment by stephanie-wang** [comment]
Sorry for the delay, @kfstorm. The C++ changes look good to me.

I noticed there are now Python API changes which will take a bit longer to review. We could also merge this now without the Python changes to get this merged faster.

File: python/ray/actor.py [hunk 2]
```diff
@@ -319,6 +322,7 @@ def __init__(
         runtime_env,
         concurrency_groups,
         scheduling_strategy: SchedulingStrategyT,
+        enable_task_fast_fail,
```
Comment (stephanie-wang) [inline python/ray/actor.py:325]: The naming is a bit unclear to me. Prefer something like "fail_tasks_during_restart"?

**Comment by stephanie-wang** [comment]
Actually on second thought, the semantics for this are a bit confusing when `max_task_retries > 0`. I wonder if we can simplify this API.

What if instead we remove the flag so that we always fail the task if the actor is dead? It will be treated as a normal error, so if max_task_retries is set, then the CoreWorker will try the task again up to the max retries.

**Comment by kfstorm** [comment]
> Actually on second thought, the semantics for this are a bit confusing when `max_task_retries > 0`. I wonder if we can simplify this API.
> 
> What if instead we remove the flag so that we always fail the task if the actor is dead? It will be treated as a normal error, so if max_task_retries is set, then the CoreWorker will try the task again up to the max retries.

I'm OK with this option. My only concern is compatibility since this is a behavior change.

BTW, if `max_task_retries` is set, do you want to retry tasks no matter what the actor state is, or only retry when the actor is back alive?

**Comment by kfstorm** [comment]
@stephanie-wang Any comments about the above question?

**Comment by stephanie-wang** [comment]
> I'm OK with this option. My only concern is compatibility since this is a behavior change.

Yes, let's get a review from @pcmoritz for the API change.


> BTW, if `max_task_retries` is set, do you want to retry tasks no matter what the actor state is, or only retry when the actor is back alive?

According to the above semantics, I think we can buffer the task on the sender when the actor is RESTARTING. If the number of retries is 0, we'll fail the task.

**Comment by kfstorm** [comment]
@stephanie-wang Let me clarify this.

We will NOT introduce a new flag `enable_task_fast_fail` (Python) / `enableTaskFastFail` (Java), instead, we change the behavior of the existing flag `max_task_retries`. When `max_task_retries` is 0 (which is the default value), if the callee actor is in the RESTARTING state, subsequently submitted tasks will fail immediately. When `max_task_retries` is not 0, subsequently submitted tasks will be queued on the caller side and we only send them to the callee when the caller actor is back to the ALIVE state.

Is the above statement correct?

**Comment by stephanie-wang** [comment]
> @stephanie-wang Let me clarify this.
> 
> We will NOT introduce a new flag `enable_task_fast_fail` (Python) / `enableTaskFastFail` (Java), instead, we change the behavior of the existing flag `max_task_retries`. When `max_task_retries` is 0 (which is the default value), if the callee actor is in the RESTARTING state, subsequently submitted tasks will fail immediately. When `max_task_retries` is not 0, subsequently submitted tasks will be queued on the caller side and we only send them to the callee when the callee actor is back to the ALIVE state.
> 
> Is the above statement correct?

Yes, this makes sense to me! Thanks for clarifying it.

**Review by pcmoritz — APPROVED** [review]
The new semantics looks good to me!

**Comment by pcmoritz** [comment]
Can we also add this to the fault tolerance documentation @stephanie-wang @kfstorm ?

**Comment by kfstorm** [comment]
> Can we also add this to the fault tolerance documentation @stephanie-wang @kfstorm ?

Will update doc.

**Comment by kfstorm** [comment]
Actually, I think the current description [here](https://docs.ray.io/en/latest/ray-core/actors/fault-tolerance.html) is pretty accurate and matches the new behavior in this PR. I don't think we need to be more specific. 

> By default, actor tasks execute with at-most-once semantics (max_task_retries=0 in the @ray.remote decorator). This means that if an actor task is submitted to an actor that is unreachable, Ray will report the error with RayActorError, a Python-level exception that is thrown when ray.get is called on the future returned by the task. 

@pcmoritz @stephanie-wang Any suggestions about updating the doc?

**Comment by kfstorm** [comment]
@stephanie-wang Please review the PR again. I also updated some test code in order to comply with the new behavior.

File: python/ray/tests/test_actor_advanced.py [hunk 3]
```diff
@@ -203,7 +203,7 @@ def test_actor_init_fails(ray_start_cluster_head):
     cluster = ray_start_cluster_head
     remote_node = cluster.add_node()
 
-    @ray.remote(max_restarts=1)
+    @ray.remote(max_restarts=1, max_task_retries=-1)
```
Comment (stephanie-wang) [inline python/ray/tests/test_actor_advanced.py:206]: Why do we need all the changes in the unit tests? It's a bit concerning because it seems to indicate there might be some compatibility issue with current user applications.

File: src/ray/core_worker/transport/direct_actor_task_submitter.h [hunk 4]
```diff
@@ -234,6 +244,11 @@ class CoreWorkerDirectActorTaskSubmitter
                      const TaskSpecification &task_spec,
                      bool skip_queue) EXCLUSIVE_LOCKS_REQUIRED(mu_);
 
+  void ReplyCallback(const Status &status,
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_task_submitter.h:247]:
```suggestion
  void HandlePushTaskReply(const Status &status,
```

**Review by stephanie-wang — COMMENTED** [review]
I have some questions about the unit test changes and the new semantics for 0 < max_task_retries < n.

File: python/ray/tests/test_actor_advanced.py (hunk 3 above)
Comment (kfstorm) [reply python/ray/tests/test_actor_advanced.py:206]: All the modified Python and Java test cases are due to the assumption that actor tasks sent after the actor is failed will be cached and sent later when the actor is back alive. This is exactly what we are trying to change in this PR.

However, I think I can revert the addition of `max_task_retries=-1` and instead add a loop to check if the actor is back alive before sending subsequent tasks. This can reduce the use of `max_task_retries` in test cases and should be more readable and maintainable. This method is used in a Java test case because right now `max_task_retries` cannot be configured in Java and it's always 0.

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc [hunk 5]
```diff
@@ -329,10 +333,32 @@ void CoreWorkerDirectActorTaskSubmitter::CheckTimeoutTasks() {
 void CoreWorkerDirectActorTaskSubmitter::SendPendingTasks(const ActorID &actor_id) {
   auto it = client_queues_.find(actor_id);
   RAY_CHECK(it != client_queues_.end());
-  if (!it->second.rpc_client) {
+  auto &client_queue = it->second;
+  auto &actor_submit_queue = client_queue.actor_submit_queue;
+  if (!client_queue.rpc_client) {
+    if (client_queue.state == rpc::ActorTableData::RESTARTING &&
+        client_queue.max_task_retries == 0) {
```
[the remark this answers is not in the document]
Comment (kfstorm) [reply src/ray/core_worker/transport/direct_actor_task_submitter.cc:340]: I assume `0 < max_task_retries < n` means that `max_task_retries` is set to a positive integer and the task has failed more than `max_task_retries` times. In this case, the task should be marked as failed and be removed from Task Manager on the `max_task_retries + 1`th failure via `FailOrRetryPendingTask`. There's no way this task will be resubmitted via `retry_task_callback_`. This task shouldn't go through the `SendPendingTasks` code path now.

On the other hand, if a task is enqueued to the actor submit queue, it means that the task has some retries left (or it's the first try), right?

File: python/ray/tests/test_actor_advanced.py (hunk 3 above)
Comment (stephanie-wang) [reply python/ray/tests/test_actor_advanced.py:206]: Got it, thanks! I think the tests are okay as is then, just wanted to make sure we don't have regressions here. I took a look at the [docs](https://docs.ray.io/en/latest/ray-core/actors/fault-tolerance.html) too, and I think this PR actually better matches what we currently state there, so seems fine to modify the tests to match that behavior.

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_actor_task_submitter.cc:340]: Got it, I misunderstood here and forgot tasks are retried through the TaskManager.

I think my confusion here is from the naming of max_task_retries. It makes it sound like we're actually going to retry the task here, but instead we only fail the task if it's equal to 0. For clarity, can we change this to use a bool like `fail_if_actor_unreachable`, similar to what you had before? Then we can set the bool based on whether max_task_retries == 0.

**Review by stephanie-wang — APPROVED** [review]
Thanks for bearing with us on this one! And glad to see this improvement.

I left one comment about improving code clarity, but otherwise feel free to merge.

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (kfstorm) [reply src/ray/core_worker/transport/direct_actor_task_submitter.cc:340]: Sounds reasonable. Will update the name.

**Comment by kfstorm** [comment]
LinkCheck fails on master as well.
