### PR TITLE
Fault tolerance race

### LINKED ISSUE #871: ComponentFailureTest.testPlasmaManagerFailed test hangs frequently in Travis in MacOS/Python3 build.
The following test fails nearly every time in Travis on the MacOS/Python 3.5 build.

```
python test/component_failures_test.py ComponentFailureTest.testPlasmaManagerFailed
```

Note that the line https://github.com/ray-project/ray/blob/617bc4d2394aec607755a1a33f16271c38298f3f/test/component_failures_test.py#L134 has a bug, it should just be `num_workers_per_scheduler`. After making that change, I can reproduce the problem locally by running the test in a loop.

Investigating the bug a bit more, it appears that **somehow a task is assigned to a local scheduler that has been removed**. This shouldn't happen because the monitor should iterate through all of the tasks in the task table and clean them up. However, there may be a race condition.

### PR DESCRIPTION
**Pull request by stephanie-wang**
This fixes three fault tolerance issues when a local scheduler dies:

1. Do not mark the local scheduler as dead in the db_client table during local scheduler cleanup. The global scheduler should be responsible for marking local schedulers as dead, to prevent races in task assignment.
2. Do not retry task assignments on the global scheduler if the local scheduler has been removed.
3. When submitting an actor task from one local scheduler to another, look up the most recent local scheduler to actor mapping before retrying a failed submission. This prevents us from infinitely retrying a dead local scheduler.

This fixes #871 (most likely caused by the second race).

### CODE REVIEW

File: src/local_scheduler/local_scheduler.cc [hunk 1]
```diff
@@ -147,6 +147,9 @@ void LocalSchedulerState_free(LocalSchedulerState *state) {
   /* Reset the SIGTERM handler to default behavior, so we try to clean up the
    * local scheduler at most once. If a SIGTERM is caught afterwards, there is
    * the possibility of orphan worker processes. */
+  /* TODO(swang): Add a null heartbeat that tells the global scheduler that we
+   * are dead. This avoids having to wait for the timeout before marking us as
+   * dead in the db_client table, in cases where we can do a clean exit. */
```
Comment (robertnishihara) [inline src/local_scheduler/local_scheduler.cc]: For the time being, this will add 10 seconds or so to each of our fault tolerance tests, right?

Comment (stephanie-wang) [reply src/local_scheduler/local_scheduler.cc]: Yes.

File: src/global_scheduler/global_scheduler.cc [hunk 2]
```diff
@@ -14,6 +14,45 @@
...
+  DBClientID local_scheduler_id = Task_local_scheduler(task);
+  auto it = state->local_schedulers.find(local_scheduler_id);
+  if (it == state->local_schedulers.end()) {
+    return;
+  }
+
+  // The local scheduler is still alive. The failure is most likely due to the
+  // task assignment getting published before the local scheduler subscribed to
+  // the channel. Retry the assignment.
+  auto retryInfo = RetryInfo{
```
Comment (robertnishihara) [inline src/global_scheduler/global_scheduler.cc]: These `RetryInfo` structs aren't being used anywhere else, so I'm a little concerned about reintroducing them.

I guess the `fail_callback` aspect is very useful, so maybe in a followup PR we should change the methods like `task_table_update` to explicitly take a `fail_callback` and to not take a retry struct.

File: src/common/state/redis.cc [hunk 3]
```diff
@@ -940,38 +940,20 @@ void redis_task_table_update_callback(redisAsyncContext *c,
...
-   * in which a global scheduler may publish a task to a local scheduler before
-   * the local scheduler has subscribed to the relevant channel, we shouldn't
-   * need this block any more. */
+  // If no subscribers received the message, call the failure callback. The
+  // caller should decide whether to retry the update. NOTE(swang): Retrying a
+  // task table update can race with the liveness monitor. Do not retry the
+  // update unless the caller is sure that the receiving subscriber is still
+  // alive in the db_client table.
   if (reply->type == REDIS_REPLY_ERROR &&
       strcmp(reply->str, "No subscribers received message.") == 0) {
```
Comment (robertnishihara) [inline src/common/state/redis.cc]: This code path is actually duplicated in `redis_task_table_add_task_callback`, so we probably should make the same changes there as well.

File: src/global_scheduler/global_scheduler.cc [hunk 4]
```diff
@@ -14,6 +14,45 @@
...
+ * publishes a task to a local scheduler before the local scheduler has
+ * subscribed to the channel. If we enforce that ordering, we can remove this
+ * retry method.
+ *
+ * @param id The task ID.
+ * @param user_context The global scheduler state.
+ * @param user_data The Task that failed to be assigned.
+ * @return Void.
+ */
+void assign_task_to_local_scheduler_retry(UniqueID id,
```
Comment (robertnishihara) [inline src/global_scheduler/global_scheduler.cc]: If we make some similar changes to the local scheduler then I think that will solve #807.

File: src/global_scheduler/global_scheduler.cc [hunk 5]
```diff
@@ -14,6 +14,45 @@
...
+  GlobalSchedulerState *state = (GlobalSchedulerState *) user_context;
+  Task *task = (Task *) user_data;
+  CHECK(Task_state(task) == TASK_STATUS_SCHEDULED);
+
+  // If the local scheduler has died since we requested the task assignment, do
+  // not retry again.
+  DBClientID local_scheduler_id = Task_local_scheduler(task);
+  auto it = state->local_schedulers.find(local_scheduler_id);
+  if (it == state->local_schedulers.end()) {
+    return;
```
Comment (robertnishihara) [inline src/global_scheduler/global_scheduler.cc]: Let's avoid adding extra return statements and put everything below in an if statement

```C++
if (it != state->local_schedulers.end()) {
}
```

File: src/global_scheduler/global_scheduler.cc [hunk 6]
```diff
@@ -14,6 +14,45 @@
...
+ * retry method.
+ *
+ * @param id The task ID.
+ * @param user_context The global scheduler state.
+ * @param user_data The Task that failed to be assigned.
+ * @return Void.
+ */
+void assign_task_to_local_scheduler_retry(UniqueID id,
+                                          void *user_context,
+                                          void *user_data) {
```
Comment (robertnishihara) [inline src/global_scheduler/global_scheduler.cc]: If we enter this function, we should probably log some sort of warning

File: src/global_scheduler/global_scheduler.cc [hunk 7]
```diff
@@ -14,6 +14,45 @@
...
+  GlobalSchedulerState *state = (GlobalSchedulerState *) user_context;
+  Task *task = (Task *) user_data;
+  CHECK(Task_state(task) == TASK_STATUS_SCHEDULED);
+
+  // If the local scheduler has died since we requested the task assignment, do
+  // not retry again.
+  DBClientID local_scheduler_id = Task_local_scheduler(task);
+  auto it = state->local_schedulers.find(local_scheduler_id);
+  if (it == state->local_schedulers.end()) {
```
Comment (robertnishihara) [inline src/global_scheduler/global_scheduler.cc]: In the case where the local scheduler has died, don't we need to do something? E.g., mark it as waiting again or call `handle_task_waiting` on it? Otherwise we could lose the task, right?

File: src/global_scheduler/global_scheduler.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/global_scheduler/global_scheduler.cc]: I had the same thought process. I suspect whatever the replacement is will still need something like the `fail_callback`, so I would prefer to just keep it here for now.

File: src/common/state/redis.cc (hunk 3 above)
Comment (stephanie-wang) [reply src/common/state/redis.cc]: Sure!

File: src/global_scheduler/global_scheduler.cc (hunk 5 above)
Comment (stephanie-wang) [reply src/global_scheduler/global_scheduler.cc]: Sorry for nitpicking, but why is that? I actually prefer the other way when reading code (put all short-circuit checks first, then do the actual function logic).

File: src/global_scheduler/global_scheduler.cc (hunk 7 above)
Comment (stephanie-wang) [reply src/global_scheduler/global_scheduler.cc]: Nope, the monitor will mark the task as lost eventually. It would be better not to write to the task table again, in case we interfere with someone trying to reconstruct the task.

File: src/global_scheduler/global_scheduler.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/global_scheduler/global_scheduler.cc]: With the last couple commits, the error messages will still get spewed while the actor is getting timed out, but will stop after the actor is marked as dead, instead of continuing forever. We can hide the error messages (possibly hiding actual errors later on), or we can retry the `task_table_add` after a timeout (possibly adding some unnecessary latency). Neither of these seems desirable.

Comment (robertnishihara) [reply src/global_scheduler/global_scheduler.cc]: So the behavior after this PR is that it logs excessively for 10 seconds and then it stops, right? That's a big improvement over logging excessively forever.

File: src/global_scheduler/global_scheduler.cc (hunk 5 above)
Comment (robertnishihara) [reply src/global_scheduler/global_scheduler.cc]: Ok that's fine, I remember someone saying that code is easier to understand when functions only have one return statement.

**Comment by robertnishihara** [comment]
Nice work here!

**Comment by pcmoritz** [comment]
Yeah!
