### PR TITLE
[Core] Fix worker process leaks after job finishes

### LINKED ISSUE #44897: [Ray core] Stopped job leaks worker
### What happened + What you expected to happen

No idle worker exists for the stopped job.

### Versions / Dependencies

2.10.0

### Reproduction script

No reliable script to reproduce this issue.

### Issue Severity

High

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?

This PR makes sure that when a job finishes, all worker processes (excluding those started by detached actors) belonging to it will **forcibly** exit. It fixes this by:

- TaskSpec has a new ancestor_detached_actor_id to indicate whether the task's root is driver or detached actor.
- Don't reuse workers for tasks whose ancestor is driver and tasks whose ancestor is detached actor so that we can safely kill workers when job finishes without impacting detached actors.
- Fixed some bugs where workers are not properly killed when job finishes (see comments for each bug)

This PR doesn't fix the worker leak when detached actors finish. Ideally if we treat detached actors are separate jobs, the same code can just work but this change has bigger impact and higher risk (e.g. are we going to overload the job table since each serve replica is a detached actor, will we run out of job id which is 4 bytes) so I didn't include it here in this PR.

## Related issue number
Closes #44897, #44931

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -4236,26 +4248,33 @@ void CoreWorker::HandleDeleteSpilledObjects(rpc::DeleteSpilledObjectsRequest req
...
   }
   bool will_exit = is_idle || force_exit;
   reply->set_success(will_exit);
   send_reply_callback(
       Status::OK(),
-      [this, will_exit]() {
+      [this, will_exit, force_exit]() {
         // If the worker is idle, we exit.
-        if (will_exit) {
+        if (force_exit) {
```
Comment (jjyao) [inline src/ray/core_worker/core_worker.cc:4272]: Bug: when `force_exit` is set, we still goes through the graceful exit code path which means if there is pending tasks or owning objects, the core worker will drain and exit which is not what we want when the job finishes.

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -4236,26 +4248,33 @@ void CoreWorker::HandleDeleteSpilledObjects(rpc::DeleteSpilledObjectsRequest req
 void CoreWorker::HandleExit(rpc::ExitRequest request,
                             rpc::ExitReply *reply,
                             rpc::SendReplyCallback send_reply_callback) {
-  bool own_objects = reference_counter_->OwnObjects();
-  int64_t pins_in_flight = local_raylet_client_->GetPinsInFlight();
+  const bool own_objects = reference_counter_->OwnObjects();
+  const size_t num_pending_tasks = task_manager_->NumPendingTasks();
```
Comment (jjyao) [inline src/ray/core_worker/core_worker.cc:4252]: Bug: we didn't consider pending tasks when we decide whether the core worker is idle or not however we consider it during drain and exit.

File: src/ray/raylet/worker_pool.cc [hunk 3]
```diff
@@ -192,17 +193,25 @@ void WorkerPool::PopWorkerCallbackAsync(const PopWorkerCallback &callback,
...
+                                           const PopWorkerCallback &callback,
                                            std::shared_ptr<WorkerInterface> worker,
                                            PopWorkerStatus status) {
   RAY_CHECK(callback);
-  auto used = callback(worker, status, /*runtime_env_setup_error_message*/ "");
+  auto used = false;
+  if (worker && finished_jobs_.contains(task_spec.JobId()) &&
+      task_spec.AncestorDetachedActorId().IsNil()) {
+    RAY_CHECK(status == PopWorkerStatus::OK);
+    callback(nullptr, PopWorkerStatus::JobFinished, "");
```
Comment (jjyao) [inline src/ray/raylet/worker_pool.cc:211]: Bug: when a job finishes, raylet will kill leased workers (one time) and idle workers (periodic). However there are workers don't belong to either of these two states: workers inside PopWorkerCallbackInternal that's sitting inside the event loop waiting to be added to the leased worker later. This fix makes sure this worker will go back to idle and will be killed by the periodic idle termination.

File: src/ray/raylet/node_manager.cc [hunk 4]
```diff
@@ -597,6 +597,25 @@ void NodeManager::HandleJobStarted(const JobID &job_id, const JobTableData &job_
 void NodeManager::HandleJobFinished(const JobID &job_id, const JobTableData &job_data) {
   RAY_LOG(DEBUG) << "HandleJobFinished " << job_id;
   RAY_CHECK(job_data.is_dead());
+  for (const auto &pair : leased_workers_) {
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:600]: Bug: we only tried to kill worker processes when its parent dies (this works in theory if you consider the task graph as a tree where the root is the driver so when root dies, eventually the entire task graph should die but in practice due to worker reuse, we will have cycles so driver death won't transitively kill all workers ) and this PR fixes it by killing workers when job finishes as well.

File: src/ray/raylet/worker_pool.cc [hunk 5]
```diff
@@ -338,20 +347,17 @@ WorkerPool::BuildProcessCommandArgs(const Language &language,
     worker_command_args.push_back("--worker-launch-time-ms=" +
                                   std::to_string(current_sys_time_ms()));
     worker_command_args.push_back("--node-id=" + node_id_.Hex());
+    worker_command_args.push_back("--runtime-env-hash=" +
```
Comment (jjyao) [inline src/ray/raylet/worker_pool.cc:350]: Bug: runtime-env-hash is actually worker cache key and includes more than just runtime env so we should always set it when starting a worker process not just when runtime env is not empty.

File: src/ray/protobuf/common.proto [hunk 6]
```diff
@@ -509,6 +509,9 @@ message TaskSpec {
   int64 generator_backpressure_num_objects = 38;
   // Boolean if task events enabled, i.e tasks events would be reported.
   bool enable_task_events = 39;
+  // If this task is originated from a detached actor,
+  // this field contains the detached actor id. Otherwise it's empty.
+  bytes ancestor_detached_actor_id = 40;
```
Comment (stephanie-wang) [inline src/ray/protobuf/common.proto:514]: Maybe root is more descriptive than ancestor?

File: src/ray/common/task/task_spec.h [hunk 7]
```diff
@@ -527,12 +529,17 @@ class WorkerCacheKey {
...
+  /// worker. \param is_ancestor_detached_actor Whether the worker will be running
+  ///         tasks or actors whose ancestor is a detached actor. This is set
+  ///         to prevent worker reuse between tasks whose ancestor is the driver process
+  ///         and tasks whose ancestor is a detached actor.
   WorkerCacheKey(const std::string serialized_runtime_env,
                  const absl::flat_hash_map<std::string, double> &required_resources,
                  bool is_actor,
-                 bool is_gpu);
+                 bool is_gpu,
+                 bool is_ancestor_detached_actor);
```
Comment (stephanie-wang) [inline src/ray/common/task/task_spec.h:542]: Since this is a bool, does that mean workers can still be reused across different detached actors?

Also, `is_descended_from_detached_actor` is a bit easier to understand.

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:4252]: Can we write a python test for this?

File: src/ray/raylet/local_task_manager.cc [hunk 8]
```diff
@@ -878,6 +883,7 @@ void LocalTaskManager::Dispatch(
   }
   worker->AssignTaskId(task_spec.TaskId());
   worker->SetAssignedTask(task);
+  worker->SetAncestorDetachedActorId(task_spec.AncestorDetachedActorId());
```
Comment (stephanie-wang) [inline src/ray/raylet/local_task_manager.cc:886]: Perhaps we can just do this in `SetAssignedTask`?

Comment (stephanie-wang) [reply src/ray/raylet/local_task_manager.cc:886]: Also is this only set while the worker is executing this task? I thought we would need to set it for the lifetime of the worker?

File: src/ray/raylet/node_manager.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc:600]: Add test?

**Review by stephanie-wang — COMMENTED** [review]
Hmm the number of bugs here is a bit scary :)

Can we add unit tests for these?

File: src/ray/raylet/local_task_manager.cc (hunk 8 above)
Comment (jjyao) [reply src/ray/raylet/local_task_manager.cc:886]: Once set it won't be unset for it's for the lifetime of the worker.

File: src/ray/common/task/task_spec.h (hunk 7 above)
Comment (jjyao) [reply src/ray/common/task/task_spec.h:542]: > does that mean workers can still be reused across different detached actors?

Yes, this PR doesn't address the worker leak for detached actors. In the follow-up PR that fixes worker leak for detached actors, we won't allow worker reuse across different detached actors anymore.

**Review by rkooo567 — COMMENTED** [review]
I think the fix makes sense. Need tests/comments to explain some code which we discussed offline

File: python/ray/_raylet.pyx [hunk 9]
```diff
@@ -4832,6 +4832,10 @@ cdef class CoreWorker:
         return (CCoreWorkerProcess.GetCoreWorker().GetWorkerContext()
                 .CurrentActorMaxConcurrency())
 
+    def get_current_root_detached_actor_id(self) -> ActorID:
```
Comment (rkooo567) [inline python/ray/_raylet.pyx:4835]: Comment test-only?

File: src/ray/raylet/worker_pool.cc [hunk 10]
```diff
@@ -972,21 +986,25 @@ void WorkerPool::InvokePopWorkerCallbackForProcess(
...
-    *task_id = it->second.task_id;
     const auto &callback = it->second.callback;
     RAY_CHECK(callback);
     // This method shouldn't be invoked when runtime env creation has failed because
     // when runtime env is failed to be created, they are all
     // invoking the callback immediately.
     RAY_CHECK(status != PopWorkerStatus::RuntimeEnvCreationFailed);
-    *worker_used = callback(worker, status, /*runtime_env_setup_error_message*/ "");
+    if (worker && finished_jobs_.contains(it->second.task_spec.JobId()) &&
+        it->second.task_spec.RootDetachedActorId().IsNil()) {
```
Comment (rkooo567) [inline src/ray/raylet/worker_pool.cc:1002]:
```suggestion
        // if the job is finished, kill workers
        // detached actor shouldn't be killed when job is killed
        it->second.task_spec.RootDetachedActorId().IsNil()) {
```

File: src/ray/raylet/worker.h [hunk 11]
```diff
@@ -205,6 +208,8 @@ class Worker : public WorkerInterface {
     lifetime_allocated_instances_ = allocated_instances;
   };
 
+  const ActorID &GetRootDetachedActorId() const { return root_detached_actor_id_; }
```
Comment (rkooo567) [inline src/ray/raylet/worker.h:211]: what does root detached actor mean?

File: src/ray/raylet/node_manager.cc [hunk 12]
```diff
@@ -616,6 +616,29 @@ void NodeManager::HandleJobStarted(const JobID &job_id, const JobTableData &job_
...
+      // Don't kill worker processes belonging to the detached actor
+      // since those are expected to outlive the job.
+      RAY_LOG(INFO) << "The leased worker " << worker->WorkerId()
+                    << " is killed because the job " << job_id << " finished.";
+      rpc::ExitRequest request;
+      request.set_force_exit(true);
+      worker->rpc_client()->Exit(
+          request, [this, worker](const ray::Status &status, const rpc::ExitReply &r) {
+            if (!status.ok()) {
+              RAY_LOG(WARNING) << "Failed to send exit request: " << status.ToString();
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:635]:
```suggestion
              RAY_LOG(WARNING) << "Failed to send exit request: " << status.ToString() << " Killing a worker using sigkill instead";
```

Also add pid to log

File: src/ray/raylet/local_task_manager.cc [hunk 13]
```diff
@@ -522,6 +522,11 @@ bool LocalTaskManager::PoppedWorkerHandler(
             task_id,
             rpc::RequestWorkerLeaseReply::SCHEDULING_CANCELLED_RUNTIME_ENV_SETUP_FAILED,
             /*scheduling_failure_message*/ runtime_env_setup_error_message);
+      } else if (status == PopWorkerStatus::JobFinished) {
+        // The task job finished.
+        // Just remove the task from dispatch queue.
+        RAY_LOG(DEBUG) << "Call back to a job finished task, task id = " << task_id;
+        erase_from_dispatch_queue_fn(work, scheduling_class);
```
Comment (rkooo567) [inline src/ray/raylet/local_task_manager.cc:529]: is this available in worker death reason btw?

File: src/ray/protobuf/common.proto [hunk 14]
```diff
@@ -509,6 +509,10 @@ message TaskSpec {
   int64 generator_backpressure_num_objects = 38;
   // Boolean if task events enabled, i.e tasks events would be reported.
   bool enable_task_events = 39;
+  // If this task is originated from a detached actor,
+  // this field contains the detached actor id.
+  // Otherwise it's empty and is originated from a driver.
+  bytes root_detached_actor_id = 40;
```
Comment (rkooo567) [inline src/ray/protobuf/common.proto:515]:
```suggestion
  bytes root_detached_actor_id = 40;
```
why don't we just call it `from_detached_actor: bool`?

**Review by rkooo567 — APPROVED** [review]

File: src/ray/raylet/worker.h (hunk 11 above)
Comment (jjyao) [reply src/ray/raylet/worker.h:211]: If a task or actor is created by a detached actor (directly or transitively) then its root is the detached actor otherwise it's the driver.

File: src/ray/raylet/local_task_manager.cc (hunk 13 above)
Comment (jjyao) [reply src/ray/raylet/local_task_manager.cc:529]: We have
```
if (force_exit) {
          ForceExit(rpc::WorkerExitType::INTENDED_SYSTEM_EXIT,
                    "Worker force exits because its job has finished");
```

File: src/ray/common/test/task_spec_test.cc [hunk 15]
```diff
@@ -146,6 +147,76 @@ TEST(TaskSpecTest, TestTaskSpecification) {
...
+                                              /*ray_namespace=*/"",
+                                              /*is_asyncio=*/false,
+                                              /*concurrency_groups=*/{},
+                                              /*extension_data=*/"",
+                                              /*execute_out_of_order=*/false,
+                                              /*root_detached_actor_id=*/actor_id);
+  ASSERT_EQ(actor_spec_builder.Build().RootDetachedActorId(), actor_id);
+}
+
+TEST(TaskSpecTest, TestWorkerCacheKey) {
```
Comment (stephanie-wang) [inline src/ray/common/test/task_spec_test.cc:204]: Can you add some comments to the tests to explain what they're testing for?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 16]
```diff
@@ -1130,6 +1130,19 @@ TEST_F(ClusterTaskManagerTest, NotOKPopWorkerTest) {
   ASSERT_TRUE(reply.canceled());
   ASSERT_EQ(reply.scheduling_failure_message(), runtime_env_error_msg);
 
+  callback_called = false;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1133]: Same here.

**Review by stephanie-wang — APPROVED** [review]

File: src/ray/protobuf/common.proto (hunk 14 above)
Comment (jjyao) [reply src/ray/protobuf/common.proto:515]: This way we can differentiate work processes belonging to different detached actors.
