### PR TITLE
[core] Make WaitForActorRefDeleted RPC Fault Tolerant

### LINKED ISSUE #53797: [Core] Transient network failure on RPC `WaitForActorRefDeleted` causes actor registration fail
### What happened + What you expected to happen

When running ray in our cluster, we observed a bug where transient network failure on RPC `WaitForActorRefDeleted` caused actor registration failed. Here is the concrete call site of the RPC that encountered transient error. [call_site.log](https://github.com/user-attachments/files/20721674/call_site.log)

Here is the output error message.

```
E                               class_name: test_actor_api.<locals>.Foo
E                               actor_id: 9ba41b4ddd98b0554ef05f0204000000
E                               namespace: 345c7114-a740-49cd-9c7f-af89bb3dea24
E                       The actor is dead because all references to the actor were removed including lineage ref count.
E                       The actor never ran - it was cancelled before it started running.
```

By analyzing the concrete call site, we noticed that the callback function of `WaitForActorRefDeleted` calls `DestroyActor` without checking return status. Maybe the root cause of this bug is that transient error caused GCS destroyed the actor without waiting for it, resulting in that the actor is cancelled before it started running.

https://github.com/ray-project/ray/blob/7337f2ad7315a587b5a86b86e244d7139b53bcc8/src/ray/gcs/gcs_server/gcs_actor_manager.cc#L1060-L1066

The expected behavior is that transient network failure can be handled and the job is executed properly.

### Versions / Dependencies

Ray 3.0.0.dev, Kuberay 1.3.0

### Reproduction script

Start a `RayCluster` using `Kuberay`. Then run the following script with ray job submit SDK.

```python
import ray


ray.init()
    
@ray.remote
class Foo:
    def __init__(self, val):
        self.x = val

    def get(self):
        return self.x

x = 1
f = Foo.remote(x)
assert ray.get(f.get.remote()) == x
```

Transient network failure can be reproduced with gRPC interceptor.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by Sparks0219**
## Why are these changes needed?

Making WaitForActorRefDeleted RPC Fault Tolerant. Added c++ unit tests to verify idempotency of HandleWaitForActorRefDeleted, and added a python integration test. 

## Related issue number

Closes #53797 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run pre-commit jobs to lint the changes in this PR. ([pre-commit setup](https://docs.ray.io/en/latest/ray-contribute/getting-involved.html#lint-and-formatting))
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

---

> [!NOTE]
> <sup>[Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) is generating a summary for commit e3234caee1b61e5ca99103275b4662abf742a079. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: src/ray/gcs/gcs_actor_manager.cc
Comment (dayshah) [inline src/ray/gcs/gcs_actor_manager.cc:952]: this looks a bit suspicious.

I think this will have some weird ordering implications based on whether we disconnect the client first or actually do wait for the actor ref deleted. I think if the status is disconnected, we know for sure the owner is dead now, so don't need to do this

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 1]
```diff
@@ -956,5 +958,150 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
...
+  rpc::WaitForActorRefDeletedRequest request;
+  request.set_actor_id(actor_id.Binary());
+  request.set_intended_worker_id(core_worker_->GetWorkerID().Binary());
+
+  std::atomic<int> callback_count(0);
+  rpc::WaitForActorRefDeletedReply reply1;
+  rpc::WaitForActorRefDeletedReply reply2;
+
+  // For requests containing the same ActorID, the send_reply_callback is overwritten
+  // and only the last callback is triggered.
```
Comment (dayshah) [inline src/ray/core_worker/tests/core_worker_test.cc]: should assert false in the first callback and assert true in the second callback

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 2]
```diff
@@ -956,5 +958,150 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
...
+  rpc::Address owner_address;
+  owner_address.set_worker_id(core_worker_->GetWorkerID().Binary());
+  reference_counter_->AddOwnedObject(
+      actor_creation_return_id, {}, owner_address, "test", 0, false, true);
+
+  rpc::WaitForActorRefDeletedRequest request;
+  request.set_actor_id(actor_id.Binary());
+  request.set_intended_worker_id(core_worker_->GetWorkerID().Binary());
+
+  std::atomic<int> callback_count(0);
```
Comment (dayshah) [inline src/ray/core_worker/tests/core_worker_test.cc]: this shouldn't need to be atomic? there's only one thread where everything is happening here

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 3]
```diff
@@ -956,5 +958,150 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
...
+    : public CoreWorkerTest,
+      public ::testing::WithParamInterface<bool> {};
+
+TEST_P(HandleWaitForActorRefDeletedRetriesTest, ActorHandleRemovedForRegisteredActor) {
+  // delete_actor_handle: determines whether the actor handle is removed from the
+  // reference counter. This is used to trigger the send_reply_callback which is stored in
+  // the reference counter via delete_actor_handle == true: the actor handle is removed
+  // from the reference counter and we expect the send_reply_callback to be triggered.
+  // delete_actor_handle == false: the actor handle is not removed from the reference
+  // counter and we expect the send_reply_callback to not be triggered.
```
Comment (dayshah) [inline src/ray/core_worker/tests/core_worker_test.cc:974]: does the parameterization for this test change what path the code goes down at all?

like more code executes when you delete, but when you don't delete the rest of the stack is still the same right?

Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc:974]: Yea with the parametrization the path doesn't change at all. Moved the reference being deleted to in between the HandleX calls so that way it'll trigger some extra conditionals since if the reference goes out of scope it has a check that'll immediately trigger the callback.

File: src/ray/core_worker/tests/core_worker_test.cc (hunk 2 above)
Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc]: oh brainfart, yup ur right

File: src/ray/core_worker/tests/core_worker_test.cc (hunk 1 above)
Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc]: Put an ASSERT_TRUE(false) in the first callback since I wanted to guarantee it wouldn't be called.

File: src/ray/gcs/gcs_actor_manager.cc
Comment (Sparks0219) [reply src/ray/gcs/gcs_actor_manager.cc:952]: Hmmm to clarify so there's a race between the gcs detecting the owner has died and cleaning up the actor, and the reply for WaitForActorRefDeleted arriving so we might end up calling DestroyActor twice? 
And by "don't need to do this" do you mean to replace the check at line 952 and instead check the status code to see if its not unavailable?

File: src/ray/gcs/gcs_actor_manager.cc [hunk 4]
```diff
@@ -935,13 +935,18 @@ void GcsActorManager::PollOwnerForActorRefDeleted(
...
           Status status, const rpc::WaitForActorRefDeletedReply &reply) {
         if (!status.ok()) {
           RAY_LOG(INFO) << "Worker " << owner_id
                         << " failed, destroying actor child, job id = "
                         << actor_id.JobId();
+          // Since WaitForActorRefDeleted is a retryable RPC, if it fails with a retryable
+          // grpc error we know that the owner is dead.
+          if (IsGrpcRetryableStatus(status)) {
+            return;
+          }
```
Comment (jjyao) [inline src/ray/gcs/gcs_actor_manager.cc]: why do we need early return here? This called is called either when the owner dies or the ref is removed, in either case we want to destroy the actor like what the existing code does

File: src/ray/gcs/gcs_actor_manager.cc [hunk 5]
```diff
@@ -935,13 +935,18 @@ void GcsActorManager::PollOwnerForActorRefDeleted(
...
+      std::move(wait_request),
       [this, owner_node_id, owner_id, actor_id](
           Status status, const rpc::WaitForActorRefDeletedReply &reply) {
         if (!status.ok()) {
           RAY_LOG(INFO) << "Worker " << owner_id
                         << " failed, destroying actor child, job id = "
                         << actor_id.JobId();
+          // Since WaitForActorRefDeleted is a retryable RPC, if it fails with a retryable
+          // grpc error we know that the owner is dead.
+          if (IsGrpcRetryableStatus(status)) {
```
Comment (dayshah) [inline src/ray/gcs/gcs_actor_manager.cc]: status is supposed to be Disconnected?
also only possible status will be disconnected after the other in flight pr, talked @Sparks0219 about this

Comment (dayshah) [reply src/ray/gcs/gcs_actor_manager.cc]: but ya probably don't need this bc actor will be removed from registered_actors

Comment (edoakes) [reply src/ray/gcs/gcs_actor_manager.cc]: `StatusSet`???

File: src/ray/gcs/gcs_actor_manager.cc (hunk 4 above)
Comment (Sparks0219) [reply src/ray/gcs/gcs_actor_manager.cc]: Agreed, removed it

File: src/ray/gcs/gcs_actor_manager.cc (hunk 5 above)
Comment (Sparks0219) [reply src/ray/gcs/gcs_actor_manager.cc]: Removed it

File: python/ray/tests/test_core_worker_fault_tolerance.py [hunk 6]
```diff
@@ -36,5 +36,33 @@ def cross_worker_access_task(objects):
     assert final_result == [0, 2, 4, 6, 8]
 
 
+@pytest.mark.parametrize("deterministic_failure", ["request"])
```
Comment (jjyao) [inline python/ray/tests/test_core_worker_fault_tolerance.py]: why not also `response`?

File: python/ray/tests/test_core_worker_fault_tolerance.py [hunk 7]
```diff
@@ -36,5 +36,33 @@ def cross_worker_access_task(objects):
...
+def test_wait_for_actor_ref_deleted_rpc_retry_and_idempotency(
+    monkeypatch, shutdown_only, deterministic_failure
+):
+    """Test that WaitForActorRefDeleted RPC retries work correctly.
+    Verify that the RPC is idempotent when network failures occur.
+    The GCS actor manager will trigger this RPC during actor initialization
+    to monitor when the actor handles have gone out of scope and the actor should be destroyed.
```
Comment (jjyao) [inline python/ray/tests/test_core_worker_fault_tolerance.py:48]:
```suggestion
    to monitor when the actor references are all removed and the actor is permanently dead.
```

File: python/ray/tests/test_core_worker_fault_tolerance.py [hunk 8]
```diff
@@ -36,5 +36,33 @@ def cross_worker_access_task(objects):
...
+    """
+
+    monkeypatch.setenv(
```
Comment (jjyao) [inline python/ray/tests/test_core_worker_fault_tolerance.py:51]: `deterministic_failure` is not used

File: python/ray/tests/test_core_worker_fault_tolerance.py [hunk 9]
```diff
@@ -36,5 +36,33 @@ def cross_worker_access_task(objects):
...
+    @ray.remote
+    class SimpleActor:
+        def ping(self):
+            return "pong"
+
+    actor = SimpleActor.options(name="test_actor").remote()
+
+    result = ray.get(actor.ping.remote())
+    assert result == "pong"
+
```
Comment (jjyao) [inline python/ray/tests/test_core_worker_fault_tolerance.py:68]: we should do

```
del actor
// check to make sure actor is marked as dead with cause equals REF_DELETED
```

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 10]
```diff
@@ -959,5 +961,158 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
   }
 }
 
+class HandleWaitForActorRefDeletedRetriesTest
+    : public CoreWorkerTest,
+      public ::testing::WithParamInterface<bool> {};
+
+TEST_P(HandleWaitForActorRefDeletedRetriesTest, ActorHandleRemovedForRegisteredActor) {
```
Comment (jjyao) [inline src/ray/core_worker/tests/core_worker_test.cc]:
```suggestion
TEST_P(HandleWaitForActorRefDeletedRetriesTest, ActorRefDeletedForRegisteredActor) {
```

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 11]
```diff
@@ -959,5 +961,158 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
...
+          Status s, std::function<void()> success, std::function<void()> failure) {
+        ASSERT_TRUE(s.ok());
+        callback_count++;
+      });
+
+  if (delete_actor_handle) {
+    std::vector<ObjectID> deleted;
+    // Triggers the send_reply_callback which is stored in the reference counter
+    reference_counter_->RemoveLocalReference(actor_creation_return_id, &deleted);
+    ASSERT_EQ(deleted.size(), 1u);
```
Comment (jjyao) [inline src/ray/core_worker/tests/core_worker_test.cc:1006]: ASSERT_EQ(callback_count, 1);

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 12]
```diff
@@ -959,5 +961,158 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
...
+INSTANTIATE_TEST_SUITE_P(ActorHandleRemovedForRegisteredActor,
+                         HandleWaitForActorRefDeletedRetriesTest,
+                         ::testing::Values(true, false));
+
+class HandleWaitForActorRefDeletedWhileRegisteringRetriesTest
+    : public CoreWorkerTest,
+      public ::testing::WithParamInterface<bool> {};
+
+TEST_P(HandleWaitForActorRefDeletedWhileRegisteringRetriesTest,
+       ActorHandleRemovedForRegisteringActor) {
```
Comment (jjyao) [inline src/ray/core_worker/tests/core_worker_test.cc]:
```suggestion
       ActorRefDeletedForRegisteringActor) {
```

Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc]: Done

File: src/ray/core_worker/tests/core_worker_test.cc (hunk 11 above)
Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc:1006]: Done

File: src/ray/core_worker/tests/core_worker_test.cc (hunk 10 above)
Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc]: Done

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 7 above)
Comment (Sparks0219) [reply python/ray/tests/test_core_worker_fault_tolerance.py:48]: That reads better, thanks!

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 8 above)
Comment (Sparks0219) [reply python/ray/tests/test_core_worker_fault_tolerance.py:51]: Oops that needs to be cleaned up, thanks for catching!

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 6 above)
Comment (Sparks0219) [reply python/ray/tests/test_core_worker_fault_tolerance.py]: I think it's a bit tricky to test response because there's another RPC that the owner uses to notify the GCS that the actor goes out of scope: AsyncReportActorOutOfScope so even if the response is lost the GCS will still deallocate the actor. 

Request is easy because if it's lost the callback immediately calls DestroyActor so we get an "actor creation cancelled" error

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 9 above)
Comment (Sparks0219) [reply python/ray/tests/test_core_worker_fault_tolerance.py:68]: AsyncReportActorOutOfScope will report this, note the prior comment

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 13]
```diff
@@ -959,5 +961,163 @@ TEST_F(CoreWorkerTest, HandlePubsubWorkerObjectLocationsChannelRetries) {
...
+
+  // Since the actor is in the registering state, we store the callbacks and trigger them
+  // when the the actor is done registering. However, each callback then sets the
+  // send_reply_callback in the reference counter which is overwritten each time.
+  core_worker_->HandleWaitForActorRefDeleted(
+      request,
+      &reply1,
+      [](Status s, std::function<void()> success, std::function<void()> failure) {
+        ASSERT_TRUE(false);
+      });
```
[the remark this answers is not in the document]
Comment (Sparks0219) [reply src/ray/core_worker/tests/core_worker_test.cc:1091]: Thanks AI

File: python/ray/tests/test_core_worker_fault_tolerance.py [hunk 14]
```diff
@@ -36,5 +36,32 @@ def cross_worker_access_task(objects):
...
+):
+    """Test that WaitForActorRefDeleted RPC retries work correctly.
+    Verify that the RPC is idempotent when network failures occur.
+    The GCS actor manager will trigger this RPC during actor initialization
+    to monitor when the actor handles have gone out of scope and the actor should be destroyed.
+    """
+
+    monkeypatch.setenv(
+        "RAY_testing_rpc_failure",
+        "CoreWorkerService.grpc_client.WaitForActorRefDeleted=1:100:0",
```
Comment (jjyao) [inline python/ray/tests/test_core_worker_fault_tolerance.py]: Why don't we also test response failure?

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 9 above)
Comment (jjyao) [reply python/ray/tests/test_core_worker_fault_tolerance.py:68]: I mean we should add some checks to make sure actor is marked as dead with cause equals REF_DELETED

File: src/ray/core_worker/reference_counter.cc [hunk 15]
```diff
@@ -821,7 +823,7 @@ bool ReferenceCounter::SetObjectRefDeletedCallback(
   if (it == object_id_refs_.end()) {
     return false;
   }
-  it->second.on_object_ref_delete = callback;
+  it->second.on_object_ref_delete.push_back(callback);
```
Comment (jjyao) [inline src/ray/core_worker/reference_counter.cc]:
```suggestion
  it->second.object_ref_deleted_callbacks.push_back(callback);
```

File: src/ray/core_worker/reference_counter.cc [hunk 16]
```diff
@@ -821,7 +823,7 @@ bool ReferenceCounter::SetObjectRefDeletedCallback(
   if (it == object_id_refs_.end()) {
     return false;
   }
```
Comment (jjyao) [inline src/ray/core_worker/reference_counter.cc:824]: The function should be renamed to `AddObjectRefDeletedCallback`

Comment (Sparks0219) [reply src/ray/core_worker/reference_counter.cc:824]: Ah good point, done thanks for catching!

File: src/ray/core_worker/reference_counter.cc (hunk 15 above)
Comment (Sparks0219) [reply src/ray/core_worker/reference_counter.cc]: Agreed, thanks!

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 14 above)
Comment (Sparks0219) [reply python/ray/tests/test_core_worker_fault_tolerance.py]: Also addressing the below comment about REF_DELETED, if AsyncReportActorOutOfScope triggers first (which it always does because WaitForRefRemoved does a retry) it causes an out of scope error instead of the REF_DELETED error. Hence on master when I tried to test response and REF_DELETED I would just see an out of scope error, and it seems to persist (doesn't get replaced with REF_DELETED).

File: python/ray/tests/test_core_worker_fault_tolerance.py (hunk 6 above)
Comment (dayshah) [reply python/ray/tests/test_core_worker_fault_tolerance.py]: can you put a comment there so the person after knows

**Comment by Sparks0219** [comment]
Added a test for response for test_wait_for_actor_ref_deleted_rpc_retry_and_idempotency that checks for REF_DELETED. However this test does pass on mainline with retries disabled since the WaitForActorRefDeleted treats successful response/bad status as the same (except for a differing log message. Keep it primarily just to show when REF_DELETED triggers.

File: src/ray/core_worker/reference_counter.cc [hunk 17]
```diff
@@ -814,14 +816,14 @@ void ReferenceCounter::UnsetObjectPrimaryCopy(ReferenceTable::iterator it) {
...
-bool ReferenceCounter::SetObjectRefDeletedCallback(
+bool ReferenceCounter::AddObjectRefDeletedCallback(
     const ObjectID &object_id, const std::function<void(const ObjectID &)> callback) {
   absl::MutexLock lock(&mutex_);
   auto it = object_id_refs_.find(object_id);
   if (it == object_id_refs_.end()) {
     return false;
   }
-  it->second.on_object_ref_delete = callback;
+  it->second.object_ref_deleted_callbacks.push_back(callback);
```
Comment (jjyao) [inline src/ray/core_worker/reference_counter.cc]:
```suggestion
  it->second.object_ref_deleted_callbacks.push_back(std::move(callback));
```

File: src/ray/core_worker/reference_counter.h [hunk 18]
```diff
@@ -348,7 +348,7 @@ class ReferenceCounter : public ReferenceCounterInterface,
   /// from the reference table (all refs including lineage ref count go to 0).
   /// Returns true if the object was in the reference table and the callback was added
   /// else false.
-  bool SetObjectRefDeletedCallback(const ObjectID &object_id,
+  bool AddObjectRefDeletedCallback(const ObjectID &object_id,
```
Comment (jjyao) [inline src/ray/core_worker/reference_counter.h]: Update docstring

File: src/ray/core_worker/reference_counter.h [hunk 19]
```diff
@@ -807,13 +807,15 @@ class ReferenceCounter : public ReferenceCounterInterface,
...
+    /// have lineage ref count and the callbacks in object_ref_deleted_callbacks
     /// will be called when lineage ref count is also 0.
     std::vector<std::function<void(const ObjectID &)>>
         on_object_out_of_scope_or_freed_callbacks;
-    /// Callback that will be called when the object ref is deleted
+    /// Callbacks that will be called when the object ref is deleted
     /// from the reference table (all refs including lineage ref count go to 0).
-    std::function<void(const ObjectID &)> on_object_ref_delete;
+    /// Need to store multiple due to message reordering where the callback of the retry
+    /// of the request could be overwritten by the callback of the initial request
```
Comment (jjyao) [inline src/ray/core_worker/reference_counter.h]: Move the comment to HandleRequest in core worker. In the reference counter context, there is no request

**Review by jjyao — COMMENTED** [review]
LGTM

File: src/ray/core_worker/reference_counter.h (hunk 19 above)
Comment (Sparks0219) [reply src/ray/core_worker/reference_counter.h]: Makes sense, done

File: src/ray/core_worker/reference_counter.h (hunk 18 above)
Comment (Sparks0219) [reply src/ray/core_worker/reference_counter.h]: Ah shoot, thanks for catching

File: src/ray/core_worker/reference_counter.cc (hunk 17 above)
Comment (Sparks0219) [reply src/ray/core_worker/reference_counter.cc]: Makes sense, done

**Review by jjyao — APPROVED** [review]

File: src/ray/core_worker/core_worker.cc [hunk 20]
```diff
@@ -3482,6 +3482,9 @@ void CoreWorker::HandleWaitForActorRefDeleted(
     send_reply_callback(Status::OK(), nullptr, nullptr);
   };
 
+  /// The callback for each request is stored in the reference counter due to retries
+  /// and message reordering where the callback of the retry of the request could be
+  /// overwritten by the callback of the initial request.
```
[the remark this answers is not in the document]
Comment (dayshah) [reply src/ray/core_worker/core_worker.cc:3487]: it got the problem wrong, the problem is actually just that the second move doesn't really move because function captures are const by default

File: src/ray/core_worker/reference_counter.cc [hunk 21]
```diff
@@ -771,8 +771,10 @@ void ReferenceCounter::EraseReference(ReferenceTable::iterator it) {
       num_objects_owned_by_us_--;
     }
   }
-  if (it->second.on_object_ref_delete) {
-    it->second.on_object_ref_delete(it->first);
+  if (it->second.object_ref_deleted_callbacks.size() > 0) {
```
Comment (dayshah) [inline src/ray/core_worker/reference_counter.cc]: why do you need this if, it's the same without it

File: src/ray/gcs/gcs_actor_manager.cc [hunk 22]
```diff
@@ -926,16 +926,16 @@ void GcsActorManager::PollOwnerForActorRefDeleted(
...
   it->second.children_actor_ids_.insert(actor_id);
 
   rpc::WaitForActorRefDeletedRequest wait_request;
   wait_request.set_intended_worker_id(owner_id.Binary());
   wait_request.set_actor_id(actor_id.Binary());
-  it->second.client_->WaitForActorRefDeleted(
-      wait_request,
+  auto client = worker_client_pool_.GetOrConnect(it->second.address_);
+  client->WaitForActorRefDeleted(
+      std::move(wait_request),
```
[the remark this answers is not in the document]
Comment (dayshah) [reply src/ray/gcs/gcs_actor_manager.cc:938]: omg cursor hates the moves

**Review by dayshah — COMMENTED** [review]
also update the Failure line in the .proto file, not sure if we've missed that for more rpc's...

just a nit

**Review by dayshah — APPROVED** [review]

File: src/ray/core_worker/reference_counter.cc (hunk 21 above)
Comment (Sparks0219) [reply src/ray/core_worker/reference_counter.cc]: oh bleh good catch thanks

File: src/ray/gcs/gcs_actor_manager.cc (hunk 22 above)
[the remark this answers is not in the document]
Comment (Sparks0219) [reply src/ray/gcs/gcs_actor_manager.cc:938]: yea and the client pool too, chill AI

**Comment by Sparks0219** [comment]
> also update the Failure line in the .proto file, not sure if we've missed that for more rpc's...

UHHH yea it's a little outdated lol, I went through the list on the doc and updated all the missing ones
