### PR TITLE
[Core] fix resource leak when cancel actor in phase of creating

### LINKED ISSUE #27743: [Core] It will case resource leak when cancel an actor in phase of creating
### What happened + What you expected to happen

It will case resource leak when cancel an actor in phase of creating.

### Versions / Dependencies

Ray master branch

### Reproduction script

``` python
def test_resource_leak_when_killing_actor(ray_start_cluster):
    cluster = ray_start_cluster
    cluster.add_node(num_cpus=2)
    ray.init(address=cluster.address)
    cluster.wait_for_nodes()

    @ray.remote(num_cpus=1)
    class Actor:
        def __init__(self, signal_1, signal_2):
            signal_1.send.remote()
            ray.get(signal_2.wait.remote())
            pass

    signal_1 = SignalActor.remote()
    signal_2 = SignalActor.remote()
    actor = Actor.remote(signal_1, signal_2)

    wait_for_condition(lambda: ray.available_resources()["CPU"] != 2)

    # Checking that the constructor of `Actor`` is invoked.
    ready_ids, _ = ray.wait([signal_1.wait.remote()], timeout=3.0)
    assert len(ready_ids) == 1

    # Kill the actor which is in the phase of creating.
    ray.kill(actor)

    # Ensure the pid
    wait_for_condition(lambda: ray.available_resources()["CPU"] == 2)
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by wumuzi520**
## Why are these changes needed?

It is quite easy to cause resource/process leak when cancel an actor which constructor is time-consuming.

## Related issue number

Closes #27743 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -801,6 +801,11 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id,
         created_actors_.erase(node_it);
       }
     } else {
+      if (!actor->GetAddress().worker_id().empty()) {
+        // The actor is in phase of creating, so we need to notify the core
+        // worker exit to avoid process and resource leak.
+        NotifyCoreWorkerToKillActor(actor, death_cause, force_kill);
```
Comment (scv119) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:807]: is this mainly due to race conditions? also after this fix, will there still be case the actor is leaked?

Comment (wumuzi520) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:807]: It,s not a race condition, if not fixed, tests in PR will definitely fail.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:807]: I think what we need is to think about what metadata & resources are related to each state. 

Dependency unready -> pending creation -> created -> restarting -> dead

Here, pending creation has technically two parts, scheduling and actor initialization, and actor initialization has more resources (processes started) to clean up. I assume we could have a similar issue when the state is restarting (but the mechanism we added here should handle this correctly). This PR adds code that implicitly distinguish actor initialization vs scheduling (by checking if the actor has an associated worker)

I think to make the code really safe, we need to have state <-> in memory metadata + resources associated with it from the code level (so we can simply clean up those associated resources when it is destroyed), but it might require big changes.

**Review by rkooo567 — COMMENTED** [review]
Can you also add a cpp unit test ?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 1 above)
Comment (wumuzi520) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:807]: Yes, I think this PR can not handle every scenarios. e.g.

The actor is marked as dead and flushed to external storage before the kill RPC send to the core worker, and then GCS restart, in this case, the worker process may leak too.

**Comment by wumuzi520** [comment]
> Can you also add a cpp unit test ?
> 
> 

Sure, I will do it.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:807]: Seems we need to holistically think about the entire state machine and the corresponding resource management (not in this PR).

**Comment by scv119** [comment]
Will not cherry pick this into 2.0

**Comment by wumuzi520** [comment]
> 

Okey!

We are outing for the past few days, and this issue has been delayed. There is indeed a little problem with this PR and I also need to add some c++ unit tests.

**Comment by wumuzi520** [comment]
> Will not cherry pick this into 2.0

Okey!

We are outing for the past few days, and this issue has been delayed. There is indeed a little problem with this PR and I also need to add some c++ unit tests.

**Comment by rkooo567** [comment]
Lmk if this is ready for the final review?

**Comment by wumuzi520** [comment]
> Lmk if this is ready for the final review?

I added some cpp unit tests, and I think it is ready for review again. :)

**Review by scv119 — APPROVED** [review]

**Comment by wumuzi520** [comment]
The failure of `mac-apple-ray-c-plus-plus-and-java` is unrelated.
BTW, I found that all tests in`mac-apple-ray-c-plus-plus-and-java` are passed, but the result is still failed.
 It is very likely that some cases have a segment error when exiting, I will find relevant colleagues to have a look.

**Comment by wumuzi520** [comment]
Hi, @rkooo567 do you have any suggestions for this PR? :)
