### PR TITLE
[dashboard] don't prepend "0" or "1" on non streaming logs

### LINKED ISSUE #46240: [Ray Dashboard] The format of the GPU profile file downloaded from the dashboard is incorrect
### What happened + What you expected to happen

Hi All. I ran GPU profiling on Ray using Nsight and the report was also generated. However, I am not able to view it on Nsight Systems on **WSL**. I got the following error:
/dvs/p4/build/sw/devtools/Agora/Rel/QuadD_Main/QuadD/Common/Analysis/Clients/ReportFile.cpp(339): Throw in function void QuadDAnalysis::ReportFile::verifyVersionTag() Dynamic exception type: boost::wrapexceptQuadDCommon::CorruptedDataException std::exception::what: CorruptedDataException [QuadDCommon::tag_message*] = Invalid version prefix: **1NVIDIA** Tegra Profiler Report [QuadDAnalysis::tag_report_file_name*] = “/Users/rajesh.dalai/Downloads/nsight_worker_process_854.nsys-rep”
Can anyone help with this? It seems that there is a problem with the format downloaded from the dashboard. Maybe some escapes are not processed properly. **Because there is a 1 in front of NVIDIA, and the subsequent lines have similar problems**

### Versions / Dependencies

Ray: 2.23.0
Nsight: 2024.4.1.61-244134315967v0

### Reproduction script

Follow the instructions in the Ray official documentation: https://docs.ray.io/en/latest/ray-observability/user-guides/profiling.html#run-nsight-on-ray

### Issue Severity

High: It blocks me from completing my task.

### LINKED ISSUE #46633: [Core] - log files for nsight profiler corrupted
### What happened + What you expected to happen

When using the nsight profiler - log files downloaded through Ray Dashboard are corrupted. Downloading direct from the node, however works.

Sniff test shows every 16-bit range of bits a random 0 or 1 is inserted. 

Full details in Ray Slack here: https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1720558963194049

### Versions / Dependencies

Latest I believe; community are all up to date so probably 2.30 forwards.

### Reproduction script

See Slack thread.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by rynewang**
Dashboard API `api/v0/logs/file` has a peculiar behavior: it prepends an `1` on each log file. This is normally not a big deal because the logs were read by humans anyway, but the same API is also used to download nsight profiles, and in near future structured loggings, where the prepended `1` can corrupt a machine readable file.

The `1` comes from #25481 for the need to indicate errors in a streaming HTTP request. Say the dashboard yielded 5 chunks of logs and found errors in the 6th. It can't set http status to 500 now because the header has already been transmitted. Hence we prepended a `1` when it's logs and `0` when it's exception. The char is consumed by the Dashboard UI Log Viewer (only 1 char) and the CLI (one char for each chunk), but not by `curl` or Chrome for obvious reasons.

The design itself is kinda OK, as long as the client parses and treats the leading char. However when you download, you have to give the pristine data.

In this PR, I added a new query param `format` = `"text" | "leading_1"`. The former gives just the data; the latter keeps the old behavior, prepends each chunk with a `1`.

UI Download buttons now use `text`. The `ray logs` CLI and the UI log viewer still uses `leading_1` to handle exceptions.

Fixes #46240. Fixes #46633.

### CODE REVIEW

**Comment by rynewang** [comment]
@alanwguo @rkooo567 please take a look

**Review by alanwguo — COMMENTED** [review]
This change makes sense to me and this has been the cause of some annoying UX, like when downloading the logs, an extra 1/0 is placed at the beginning.

However, this is a backwards-incompatible change and will break some downstream systems including some Anyscale logic. Can we put this change behind a flag? Probably a query_param could work?

**Comment by rynewang** [comment]
Will do

**Comment by rynewang** [comment]
@alanwguo added query param `format` = `"text" | "leading_1"`.

- UI download button uses `text` to get non-leading-1 data
- UI Log viewer uses leading_1 as old behavior to get the error
- CLI logs use `text`
- CLI streaming logs (`--follow`) use `leading_1`
- By default uses `leading_1` to not break any existing downstream

File: python/ray/dashboard/client/src/service/log.ts [hunk 1]
```diff
@@ -51,12 +56,14 @@ export const getStateApiDownloadLogUrl = ({
...
     `lines=${maxLines}`,
+    `format=${format}`,
   ];
 
   return `api/v0/logs/file?${variables.join("&")}`;
 };
 
 export const getStateApiLog = async (props: StateApiLogInput) => {
+  props.format = "leading_1";
   const url = getStateApiDownloadLogUrl(props);
```
Comment (alanwguo) [inline python/ray/dashboard/client/src/service/log.ts:67]:
```suggestion
  const url = getStateApiDownloadLogUrl({ ...props, format: "leading_1" });
```

To avoid mutating the passed in variable leading to hard to debug bugs later if some logic changes.

File: python/ray/dashboard/modules/state/state_head.py [hunk 2]
```diff
@@ -417,37 +430,59 @@ async def get_logs(self, req: aiohttp.web.Request):
...
+        output_format = req.query.get("format", "leading_1")
+        logger.info(f"Streaming logs with format {output_format} options: {options}")
+
+        async def formatter_text(response, async_gen: AsyncIterable[bytes]):
+            try:
+                async for logs in async_gen:
+                    await response.write(logs)
+            except asyncio.CancelledError:
+                # This happens when the client side closes the connection.
+                # Fofce close the connection and do no-op.
```
Comment (alanwguo) [inline python/ray/dashboard/modules/state/state_head.py:442]:
```suggestion
                # Force close the connection and do no-op.
```

**Review by alanwguo — APPROVED** [review]

**Comment by anyscalesam** [comment]
Discussed - this should fix the issue outright because we did root cause understand the additional bit pre-pends happen per chunk (which is why you see the throughout the log file).

This PR will fix that issue completely and make sure files are no longer corrupted.

**Comment by anyscalesam** [comment]
Tests are failing - @rynewang to you...
