### PR TITLE
Leave `ray.wait` calls open until the task or actor exits

### LINKED ISSUE #3715: ray.wait() doesn't return methods completed by dead actors as ready
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04
- **Ray installed from (source or binary)**: source
- **Ray version**: 0.6.1
- **Python version**: 3.6.6

### Describe the problem

1. launch an actor on another node
2. `x = actor.ping.remote()`
3. kill the node containing the actor
4. `ray.wait([x], timeout=0)`. `x` will never become ready, even if called much later

Expected behavior is that `x` will become ready and store an exception.
This is an issue when adding heartbeats for actors on multiple node using `ray.wait()`, such as for distributed SGD.

### Source code / logs
```python
import time

import ray 
from ray.test.cluster_utils import Cluster

cluster = Cluster(True, True, head_node_args={"num_cpus": 0})
node = cluster.add_node()

@ray.remote(num_cpus=1)
class Foo:
    def ping(self):
        pass

f = Foo.remote()

print("pinging")
ray.get(f.ping.remote())

x = f.ping.remote()

print("removing node")
cluster.remove_node(node)
print("done removing node")

for i in range(100):
    print(i, ray.wait([x], timeout=1))
    time.sleep(1)
```

CC @stephanie-wang

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

Previously, `ray.wait` calls would get canceled as soon as the call was able to return to the client, once the `timeout` or `num_returns` parameters was satisfied. This changes the behavior so that the raylet will continue to try and satisfy `ray.wait` calls even after control has been returned to the client. The call will be canceled when the object is local or when the task or actor that made the call exits, whichever occurs first.

This means that objects that the frontend requests through `ray.wait` that are not yet ready will be polled in the background until they become ready. This should reduce the number of calls that we have to make to `Pull` the object from remote object managers.

## Related issue number

Fixes #3715. Replaces #4153.

## Linter

- [x] I've run `scripts/format.sh` to lint the changes in this PR.

### CODE REVIEW

File: src/ray/raylet/task_dependency_manager.h [hunk 1]
```diff
@@ -188,13 +230,16 @@ class TaskDependencyManager {
   /// The storage system for the task lease table.
   gcs::TableInterface<TaskID, TaskLeaseData> &task_lease_table_;
   /// A mapping from task ID of each subscribed task to its list of object
-  /// dependencies.
+  /// dependencies, either task arguments or objects passed into `ray.get`.
   std::unordered_map<ray::TaskID, TaskDependencies> task_dependencies_;
+  /// A mapping from worker ID to each object that the worker called `ray.wait` on.
+  std::unordered_map<ray::WorkerID, WorkerDependencies> worker_dependencies_;
```
Comment (ericl) [inline src/ray/raylet/task_dependency_manager.h]: Instead of keeping both Task and Worker deps, how about keeping only Worker deps and doing the task->worker lookup? Non-actor tasks could clear their worker deps on exit.

File: src/ray/raylet/task_dependency_manager.h [hunk 2]
```diff
@@ -55,16 +58,39 @@ class TaskDependencyManager {
...
-  bool UnsubscribeDependencies(const TaskID &task_id);
+  bool UnsubscribeGetDependencies(const TaskID &task_id);
+
+  /// Unsubscribe from the object dependencies required by this worker through `ray.wait`.
+  /// If the objects were remote and are no longer required by any subscribed task, then
+  /// they will be canceled.
+  ///
+  /// \param worker_id The ID of the worker whose dependencies we should unsubscribe from.
+  /// \return The objects that the worker was waiting on.
+  void UnsubscribeWaitDependencies(const WorkerID &worker_id);
```
Comment (ericl) [inline src/ray/raylet/task_dependency_manager.h]: It would be nice to not have separate APIs for Get and Wait deps.

**Review by ericl — COMMENTED** [review]
Is this PR also changing the wait semantics to prefetch the object?

File: src/ray/raylet/task_dependency_manager.h (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/raylet/task_dependency_manager.h]: I don't think this will work out very cleanly because not all tasks have workers (e.g., unassigned tasks that are waiting for object dependencies). I tried something similar before where I only kept track of tasks instead of tasks and workers, but it turns out to be pretty complicated to keep track of the worker->task mapping. For actors, you actually have to track all tasks that still have an active `ray.wait`, even if the tasks already completed.

File: src/ray/raylet/task_dependency_manager.h (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/raylet/task_dependency_manager.h]: Yeah, I agree it's not great...but the semantics are quite different and I'm not really sure how/whether to unify them.

**Comment by stephanie-wang** [comment]
> Is this PR also changing the wait semantics to prefetch the object?

Yep.

**Review by ericl — APPROVED** [review]
Looks good! The new fetch behavior seems reasonable too... it will certainly speed up Tune and RLlib.

File: src/ray/raylet/node_manager.cc [hunk 3]
```diff
@@ -945,12 +943,15 @@ void NodeManager::ProcessDisconnectClientMessage(
       // Because in this case, its task is already cleaned up.
       RAY_LOG(DEBUG) << "Skip unblocking worker because it's already dead.";
     } else {
+      // Clean up any open ray.get calls that the worker made.
       while (!worker->GetBlockedTaskIds().empty()) {
         // NOTE(swang): HandleTaskUnblocked will modify the worker, so it is
         // not safe to pass in the iterator directly.
         const TaskID task_id = *worker->GetBlockedTaskIds().begin();
-        HandleTaskUnblocked(client, task_id);
+        HandleTaskUnblocked(client, task_id, /*ray_get=*/true);
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc]: `HandleJobTableUpdate` actually calls this code indirectly; it kills all workers that are executing tasks related to the job, and this code gets called once the node manager receives the worker disconnect event.
