### PR TITLE
[Java] Disable the multi-worker feature by default

### LINKED ISSUE #10492: Make the multi-worker feature for Java worker experimental
Right now, the multi-worker feature for Java worker is enabled by default, but the `ActorHandle::kill()` API doesn't work well if multi-worker is enabled because it will kill the whole process instead of one worker in the process.

To avoid complaints from Java users, we should disable the multi-worker feature by default, but we still enable it in unit test.

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

* Set the default value of num java workers per process to 1.
* Enable the multi-worker feature in Java CI.

## Related issue number

Closes #10492 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by raulchen — APPROVED** [review]

File: java/test.sh [hunk 1]
```diff
@@ -33,15 +33,18 @@ bazel build //java:gen_maven_deps
 echo "Build test jar."
 bazel build //java:all_tests_deploy.jar
 
+# Enable multi-worker feature in Java test
+TEST_ARGS=(-Dray.raylet.config.num_workers_per_process_java=10 -Dray.job.num-java-workers-per-process=10)
```
Comment (chaokunyang) [inline java/test.sh:37]: Why need to set those parameters at the same time?

**Comment by raulchen** [comment]
Can you check the Java CI failure? Looks related.

File: java/test.sh (hunk 1 above)
Comment (kfstorm) [reply java/test.sh:37]: Because we need to pass the tests both when multi-tenancy is enabled and disabled.
