### PR TITLE
[core] Remove "plasma promotion" for serialized ObjectRefs

### LINKED ISSUE #19024: [Release] many_tasks_serialized_ids is failing weekly release test
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

I think it hangs after 2 minutes with many errors and check failures.
```
(raylet) [2021-09-29 12:57:50,030 C 952 952] subscriber.cc:40:  Check failed: subscription_it->second.subscription_callback_map .emplace(key_id, std::make_pair(std::move(subscription_callback), std::move(subscription_failure_callback))) .second 
(raylet) *** StackTrace Information ***
(raylet)     ray::SpdLogMessage::Flush()
(raylet)     ray::RayLog::~RayLog()
(raylet)     ray::pubsub::SubscriberChannel<>::Subscribe()
(raylet)     ray::pubsub::Subscriber::Subscribe()
(raylet)     ray::raylet::LocalObjectManager::WaitForObjectFree()
(raylet)     ray::raylet::NodeManager::HandlePinObjectIDs()
(raylet)     std::_Function_handler<>::_M_invoke()
(raylet)     boost::asio::detail::completion_handler<>::do_complete()
(raylet)     boost::asio::detail::scheduler::do_run_one()
(raylet)     boost::asio::detail::scheduler::run()
(raylet)     boost::asio::io_context::run()
(raylet)     main
(raylet)     __libc_start_main
(raylet) 
```

### Reproduction script

https://buildkite.com/ray-project/periodic-ci/builds/1156#7454eac2-1e2c-4ea1-a9bd-13b64f2540b9

https://beta.anyscale.com/o/anyscale-internal/projects/prj_2xR6uT6t7jJuu1aCwWMsle/clusters/ses_ht3dcUEFniJSaS4tnNCc9Q1y?command-history-section=command_history

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Previously if an ObjectRef was serialized, we would "promote" the object to plasma. This allowed any ref holders to get the object by requesting it through the plasma store. However, this is no longer necessary because the owner can send objects directly to any ref holders (#13618).

It looks like plasma promotion + the new pubsub layer (#14762) is causing #19024. The root cause is that every time a worker serialized the ObjectRef, we would send another IPC to its local raylet asking it to pin the object (to make sure it's available for ref holders). The raylet would then subscribe to messages about the object from the object's owner. This could cause a duplicate subscription to the same key, which is not allowed in the new pubsub layer. I think this race condition has likely been an issue in the codebase for a while.

## Related issue number

Closes #19024.

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by stephanie-wang** [comment]
I confirmed that this fixes the test on my laptop.

**Review by scv119 — APPROVED** [review]

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -1025,6 +1025,7 @@ void CoreWorker::PutObjectIntoPlasma(const RayObject &object, const ObjectID &ob
 }
 
 void CoreWorker::PromoteObjectToPlasma(const ObjectID &object_id) {
+  // TODO(swang): Remove.
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc:1028]: ?

**Comment by ericl** [comment]
Makes sense. Just to be sure, the assumption is that large enough objects are put in plasma anyways?

File: python/ray/_raylet.pyx [hunk 2]
```diff
@@ -1726,7 +1726,6 @@ cdef class CoreWorker:
             CObjectID c_object_id = object_ref.native()
             CAddress c_owner_address = CAddress()
             c_string serialized_object_status
-        CCoreWorkerProcess.GetCoreWorker().PromoteObjectToPlasma(c_object_id)
```
Comment (ericl) [inline python/ray/_raylet.pyx:1729]: Aren't there other cases where we promote, like during arg passing?

**Comment by scv119** [comment]
> This could cause a duplicate subscription to the same key, which is not allowed in the new pubsub layer.
does it mean a better fix is to solve it at pubsub layer?

File: src/ray/core_worker/core_worker.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:1028]: Ah I meant to remove this codepath because it won't be used anymore, but just wanted to check if CI would pass first.

**Comment by stephanie-wang** [comment]
> Makes sense. Just to be sure, the assumption is that large enough objects are put in plasma anyways?

Yes, either they are already put in plasma, or the value is small enough that they will get returned directly by the owner. This has been the case for a while, so this codepath was not really doing anything.

> This could cause a duplicate subscription to the same key, which is not allowed in the new pubsub layer.
> does it mean a better fix is to solve it at pubsub layer?

Yeah I was thinking about this too, and I agree we should spend some time after this PR thinking about that. Definitely seems like there could be other cases where this could show up. But that seemed like a bigger change to me, and I'm not sure what the implications are. Maybe @rkooo567 can comment?

File: python/ray/_raylet.pyx (hunk 2 above)
Comment (stephanie-wang) [reply python/ray/_raylet.pyx:1729]: I think it's actually only used here. Arg passing also goes through this serialization codepath.

File: src/ray/core_worker/core_worker.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:1028]: If it's okay with you, I might leave this as a follow-up PR to unblock the release. Looks like this is codepath is used by Java too.
