### PR TITLE
[Core][actor out-of-order execution 3/n] Introducing out-of-order actor submit queue

### LINKED ISSUE #19822: [Core] support out of order execution for threaded/async actors
The following will timeout
```python
import ray
ray.init()

@ray.remote
class A:
    def echo(self, inp):
        print(inp)
        return inp

@ray.remote
def never_return():
    import time
    time.sleep(10000)

inp_ref_1 = never_return.remote()
inp_ref_2 = ray.put(2)

a = A.options(max_concurrency=2).remote()

out_ref_1 = a.echo.remote(inp_ref_1)
out_ref_2 = a.echo.remote(inp_ref_2)

assert ray.get(out_ref_2, timeout=5) == 2 # currently timeout!
```

I went all the way back to Ray 0.8.0 and it is the same behavior, so this is _not_ a regression. For concurrent actors and async actors, however, I think the snippet should work and we should allow later tasks to execute first when their dependencies ready. **This is a semantics change.**

Context: user bug report for Ray Serve https://discuss.ray.io/t/concurrent-queries-blocking-following-queries/3949/2

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

This is the third PR in the stack that supports out or order execution for threaded/async actors. Previous PR #20149 Next PR #20160
At a high level, threaded actor/async actor already don't guarantee execution order, and the current "sequential" order implementation has caused some confusion and inconvenience. Please refer to #19822 for detailed discussion.

In this PR, we implemented the out-of-order of queue that supports out of order execution. Conceptually it's very simple: it sends the requests as soon as the dependency is resolved.

TBD: add unit test to verify the behavior

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - TBD: [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.h [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+
+#include "absl/types/optional.h"
+#include "ray/common/id.h"
+#include "ray/core_worker/transport/actor_submit_queue.h"
+
+namespace ray {
+namespace core {
+
+/**
+ * OutofOrderActorSubmitQueue sends request as soon as the dependencies are resolved.
```
Comment (scv119) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.h:28]: TODO, we need a description of the guarantee and behaviors of this queue.

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc [hunk 2]
```diff
@@ -0,0 +1,85 @@
...
+    task_ids.push_back(spec.first.TaskId());
+  }
+  requests.clear();
+  return task_ids;
+}
+
+absl::optional<std::pair<TaskSpecification, bool>>
+OutofOrderActorSubmitQueue::PopNextTaskToSend() {
+  for (auto it = requests.begin(); it != requests.end(); it++) {
+    if (/*dependencies_resolved*/ it->second.second) {
```
Comment (ericl) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:60]: Maybe add a TODO to optimize this so it's not O(n^2) in the worst case (but seems unlikely to be an issue).

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.h [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+  std::vector<TaskID> ClearAllTasks() override;
+  absl::optional<std::pair<TaskSpecification, bool>> PopNextTaskToSend() override;
+  std::map<uint64_t, TaskSpecification> PopAllOutOfOrderCompletedTasks() override;
+  void OnClientConnected() override;
+  uint64_t GetSequenceNumber(const TaskSpecification &task_spec) const override;
+  void MarkTaskCompleted(uint64_t position, TaskSpecification task_spec) override;
+
+ private:
+  ActorID actor_id;
+  std::map<uint64_t, std::pair<TaskSpecification, bool>> requests;
```
Comment (ericl) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.h:47]: Consider absl::btree_map

**Review by ericl — APPROVED** [review]

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.h (hunk 1 above)
Comment (rkooo567) [reply src/ray/core_worker/transport/out_of_order_actor_submit_queue.h:28]: + Docstring for each API!

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.h [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+};
+}  // namespace core
+}  // namespace ray
```
Comment (rkooo567) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.h:50]: Newline

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+uint64_t OutofOrderActorSubmitQueue::GetSequenceNumber(
+    const TaskSpecification &task_spec) const {
+  return task_spec.ActorCounter();
+}
+
+void OutofOrderActorSubmitQueue::MarkTaskCompleted(uint64_t position,
+                                                   TaskSpecification task_spec) {}
+
+}  // namespace core
+}  // namespace ray
```
Comment (rkooo567) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:85]: Newline!

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc [hunk 6]
```diff
@@ -0,0 +1,85 @@
...
+// distributed under the License is distributed on an "AS IS" BASIS,
+// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+// See the License for the specific language governing permissions and
+// limitations under the License.
+
+#include "ray/core_worker/transport/out_of_order_actor_submit_queue.h"
+
+namespace ray {
+namespace core {
+OutofOrderActorSubmitQueue::OutofOrderActorSubmitQueue(ActorID actor_id)
```
Comment (rkooo567) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:19]:
```suggestion

OutofOrderActorSubmitQueue::OutofOrderActorSubmitQueue(ActorID actor_id)
```

Really minor lol

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc (hunk 2 above)
Comment (rkooo567) [reply src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:60]: I think we can easily do that by using 2 queues? (one for dep_resolved queue, and the other for non resolved queue)? Why don't we just do this here?

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc [hunk 7]
```diff
@@ -0,0 +1,85 @@
...
+std::map<uint64_t, TaskSpecification>
+OutofOrderActorSubmitQueue::PopAllOutOfOrderCompletedTasks() {
+  return {};
+}
+
+void OutofOrderActorSubmitQueue::OnClientConnected() {}
+
+uint64_t OutofOrderActorSubmitQueue::GetSequenceNumber(
+    const TaskSpecification &task_spec) const {
+  return task_spec.ActorCounter();
```
Comment (rkooo567) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:78]: Is it always -1? Why don't we assert here?

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc (hunk 2 above)
Comment (rkooo567) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:60]: Do we eagerly submit all resolved tasks? I wonder if we should at least guarantee FIFO order of dependency resolved order to avoid starvation (like some dep resolved tasks are never sent because they are just in the back of the map).

Comment (rkooo567) [reply src/ray/core_worker/transport/out_of_order_actor_submit_queue.cc:60]: should be easy to implement with the 2 queue approach

**Comment by scv119** [comment]
rlib:test_curiosity is broken on the base commit (#20375)
linux://python/ray/tests:test_output is broken on master
windows is broken on master.

this PR should be good to merge
