### PR TITLE
Fix idle worker leak issue if it received a SIGTERM when DrainAndShutdown.

### LINKED ISSUE #19639: [Bug] Worker would be leaked if it received a SIGTERM when DrainAndShutdown.
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

If a worker receives a SIGTERM signal when it's doing reference_counting->DrainAndShutdown stuffs, it would be leaked.

### Versions / Dependencies

master

## STEP1
`ray start --head`

## STEP2
Run this driver scripts:
```python
import ray
import numpy as np

ray.init(address='auto')

@ray.remote
def normal_task(large):
    import time
    time.sleep(60 * 60)
    return "normaltask"

large = ray.put(np.zeros(100 * 2**10, dtype=np.int8))
obj = normal_task.remote(large)
ray.get(obj)

```
## STEP3
Use `ps -ef | grep ray::` command to find the pid of the `normal_task` worker.
image
Then kill it with SIGTERM:
```
kill -15 88824
```
## STEP4
Wait the normal_task getting reconstructed, and then exit your driver process.

## FINALLY
The worker(pid=88824) is leaked. And next coming tasks wouldn't be scheduled to this worker.

REASON: It sends a disconnect message to raylet, but it doesn't exit because of DrainXxxx(). and raylet remove it from `registered_workers` in worker_pool. So `TryKillingIdleWorkers()` is not able to kill it.

### Anything else

In our production environment, the leaked worker executed a heavy task, and leaded the worker with a high memory usage(around 10G+). So in a short time, the memory usage wouldn't be down, and other actors were scheduled onto this pod, resulting in a critical OOM.

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jovany-wang**
This PR fixes the issue that worker might be leaked if task finished with some errors.
See #19639 for more details.

close #19639

### CODE REVIEW

File: src/ray/core_worker/reference_count.cc [hunk 1]
```diff
@@ -30,6 +30,24 @@ namespace {}  // namespace
...
+  if (it == local_ref_counts->end()) {
+    local_ref_counts->emplace(object_id, 0);
+  }
+
+  if (increase) {
+    ++(*local_ref_counts)[object_id];
+  } else {
+    if ((*local_ref_counts)[object_id] == 0) {
+      return;
+    }
```
Comment (ericl) [inline src/ray/core_worker/reference_count.cc:46]: This might create an entry with zero ref counts, is that intended?

File: src/ray/core_worker/reference_count.h [hunk 2]
```diff
@@ -820,6 +823,10 @@ class ReferenceCounter : public ReferenceCounterInterface,
   /// locally.
   absl::flat_hash_set<ObjectID> freed_objects_ GUARDED_BY(mutex_);
 
+  /// Index that all local reference counts to speed up the process of releasing
+  /// all local references when shutdown.
+  absl::flat_hash_map<ObjectID, int32_t> local_ref_counts_ GUARDED_BY(mutex_);
```
Comment (ericl) [inline src/ray/core_worker/reference_count.h:828]: Since shutdown is not performance critical, how about not indexing this and instead scanning the entire reference table for local references?

**Review by ericl — DISMISSED** [review]

**Comment by jovany-wang** [comment]
@rkooo567 cc

File: python/ray/tests/test_advanced_2.py [hunk 3]
```diff
@@ -745,6 +748,73 @@ def f():
...
+
+    driver_proc = run_string_as_driver_nonblocking(driver_script)
+
+    try:
+        driver_proc.wait(10)
+    except Exception as e:
+        print(e)
+
+    kvstore = ray.get_actor("kvstore", namespace="test")
+    normal_task_pid = ray.get(kvstore.get.remote("pid"))
```
Comment (kfstorm) [inline python/ray/tests/test_advanced_2.py:805]: Could you add more comments in the test case? I don't quite understand what scenario it tries to reproduce.

File: python/ray/tests/test_advanced_2.py [hunk 4]
```diff
@@ -745,6 +748,73 @@ def f():
...
+import ray
+import os
+import ray
+import numpy as np
+import time
+
+ray.init(address="{address}", namespace="test")
+
+@ray.remote
+class KvStore:
```
Comment (kfstorm) [inline python/ray/tests/test_advanced_2.py:769]: Could you simplify the driver script? I think the driver script is complicated and it makes me hard to get the key point of this test case.

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -832,6 +832,8 @@ void CoreWorker::Exit(
   RAY_CHECK_OK(
       local_raylet_client_->NotifyDirectCallTaskBlocked(/*release_resources*/ true));
 
+  RAY_LOG(DEBUG) << "Exit signal received, remove all local references.";
+  reference_counter_->ReleaseAllLocalReferences();
```
Comment (kfstorm) [inline src/ray/core_worker/core_worker.cc:836]: Could you add a comment here to explain the reason if this step? And please add it to the PR description as well.

File: python/ray/tests/test_advanced_2.py [hunk 6]
```diff
@@ -745,6 +748,73 @@ def f():
...
+
+    kvstore = ray.get_actor("kvstore", namespace="test")
+    normal_task_pid = ray.get(kvstore.get.remote("pid"))
+    normal_task_proc = psutil.Process(normal_task_pid)
+    print("killing normal task process, pid=", normal_task_pid)
+    normal_task_proc.send_signal(signal.SIGTERM)
+    time.sleep(3)
+
+    driver_proc.send_signal(signal.SIGTERM)
+    # Sleep to make sure raylet triggered cleanuping the idle workers.
```
Comment (kfstorm) [inline python/ray/tests/test_advanced_2.py:812]:
```suggestion
    # Sleep here to make sure raylet has triggered cleaning up the idle workers.
```

File: python/ray/tests/test_advanced_2.py [hunk 7]
```diff
@@ -745,6 +748,73 @@ def f():
...
+        driver_proc.wait(10)
+    except Exception as e:
+        print(e)
+
+    kvstore = ray.get_actor("kvstore", namespace="test")
+    normal_task_pid = ray.get(kvstore.get.remote("pid"))
+    normal_task_proc = psutil.Process(normal_task_pid)
+    print("killing normal task process, pid=", normal_task_pid)
+    normal_task_proc.send_signal(signal.SIGTERM)
+    time.sleep(3)
```
Comment (kfstorm) [inline python/ray/tests/test_advanced_2.py:809]: Is this sleep required?

Comment (jovany-wang) [reply python/ray/tests/test_advanced_2.py:809]: used wait_for_condition instead.

**Comment by jovany-wang** [comment]
@kfstorm Thanks for the helpful suggestions.
Test was simplified. Feel free to take another look.

File: python/ray/tests/test_advanced_2.py [hunk 8]
```diff
@@ -745,6 +749,65 @@ def f():
...
+import numpy as np
+import time
+from ray.experimental.internal_kv import _internal_kv_put
+
+ray.init(address="{address}", namespace="test")
+
+@ray.remote
+def normal_task(large):
+    # Record the pid of this normal task.
+    _internal_kv_put("NORMAL_TASK_PID", str(os.getpid()))
```
Comment (stephanie-wang) [inline python/ray/tests/test_advanced_2.py:775]: Can you use an actor instead of internal KV? We shouldn't use unstable APIs for testing.

File: python/ray/tests/test_advanced_2.py [hunk 9]
```diff
@@ -745,6 +749,65 @@ def f():
...
+    def normal_task_was_reconstructed():
+        curr_pid_bytes = _internal_kv_get("NORMAL_TASK_PID")
+        return curr_pid_bytes is not None \
+            and int(curr_pid_bytes) != normal_task_pid
+    wait_for_condition(lambda: normal_task_was_reconstructed(), 10)
+
+    driver_proc.send_signal(signal.SIGTERM)
+    # Sleep here to make sure raylet has triggered cleaning up
+    # the idle workers.
+    time.sleep(10)
```
Comment (stephanie-wang) [inline python/ray/tests/test_advanced_2.py:807]: Use wait_for_condition instead to avoid sleeping.

File: src/ray/core_worker/core_worker.cc [hunk 10]
```diff
@@ -832,6 +832,11 @@ void CoreWorker::Exit(
   RAY_CHECK_OK(
       local_raylet_client_->NotifyDirectCallTaskBlocked(/*release_resources*/ true));
 
+  RAY_LOG(DEBUG) << "Exit signal received, remove all local references.";
+  /// Since this core worker is exiting, it's necessary to release all local references,
+  /// otherwise this worker propobly be leaked.
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc:837]:
```suggestion
  /// otherwise the frontend code may not release its references and this worker will be leaked.
```

File: src/ray/core_worker/core_worker.cc [hunk 11]
```diff
@@ -832,6 +832,11 @@ void CoreWorker::Exit(
...
+  /// Details can be refered at the issue: https://github.com/ray-project/ray/issues/19639
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc:838]:
```suggestion
  /// See https://github.com/ray-project/ray/issues/19639.
```

File: src/ray/core_worker/reference_count.cc [hunk 12]
```diff
@@ -247,6 +247,19 @@ void ReferenceCounter::SetNestedRefInUseRecursive(ReferenceTable::iterator inner
   }
 }
 
+void ReferenceCounter::ReleaseAllLocalReferences() {
+  ReferenceTable all_local_refs;
+  {
+    absl::MutexLock lock(&mutex_);
+    /// A copy of object_id_refs_ to avoid iter invalidation
```
Comment (stephanie-wang) [inline src/ray/core_worker/reference_count.cc:254]: This seems like it could race with reference creation. Can you instead hold the lock for the whole method and add a RemoveLocalReferenceInternal that requires the lock to be held?

File: src/ray/core_worker/reference_count.cc [hunk 13]
```diff
@@ -247,6 +247,19 @@ void ReferenceCounter::SetNestedRefInUseRecursive(ReferenceTable::iterator inner
...
+    /// and mutex lock reentred.
+    all_local_refs = object_id_refs_;
+  }
+  for (auto &ref : all_local_refs) {
+    RemoveLocalReference(ref.first, nullptr);
```
Comment (stephanie-wang) [inline src/ray/core_worker/reference_count.cc:259]: I think we need to call this multiple times, if the worker has multiple instances of the object.

You can test this in Python by passing the same object as two of the task's arguments.

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Nice catch! It looks good, suggested some cleanups.

File: python/ray/tests/test_advanced_2.py (hunk 8 above)
Comment (jovany-wang) [reply python/ray/tests/test_advanced_2.py:775]: I don't think a KVStore actor is the good practice. It  will make readers miss the key point of the test code.

File: src/ray/core_worker/reference_count.cc (hunk 13 above)
Comment (jovany-wang) [reply src/ray/core_worker/reference_count.cc]: Good catch.

File: python/ray/tests/test_advanced_2.py (hunk 8 above)
Comment (jovany-wang) [reply python/ray/tests/test_advanced_2.py:775]: BTW, I found there're many places we use this internal KV for testing. :)

**Comment by jovany-wang** [comment]
@stephanie-wang Thanks for your nice comments. All were addressed or replied.

File: src/ray/core_worker/reference_count.h [hunk 14]
```diff
@@ -473,6 +473,9 @@ class ReferenceCounter : public ReferenceCounterInterface,
 
   bool IsObjectReconstructable(const ObjectID &object_id) const;
 
+  /// Relase all local references which registered on this local.
```
Comment (stephanie-wang) [inline src/ray/core_worker/reference_count.h:476]: Please also add a note that this should only be used on shutdown.

```suggestion
  /// Release all local references which registered on this local.
```

File: python/ray/tests/test_advanced_2.py (hunk 8 above)
Comment (stephanie-wang) [reply python/ray/tests/test_advanced_2.py:777]: Ah well, they shouldn't be using it either :) Could you still convert to using an actor here? It's standard to use actors like this in testing, and we should always prefer that over an unstable API.

**Review by stephanie-wang — APPROVED** [review]
Looks good, but please address the last two comments!

File: src/ray/core_worker/core_worker.cc [hunk 15]
```diff
@@ -832,6 +832,11 @@ void CoreWorker::Exit(
   RAY_CHECK_OK(
       local_raylet_client_->NotifyDirectCallTaskBlocked(/*release_resources*/ true));
 
+  RAY_LOG(DEBUG) << "Exit signal received, remove all local references.";
+  /// Since this core worker is exiting, it's necessary to release all local references,
+  /// otherwise the frontend code may not release its references and this worker will be
+  /// leaked. See https://github.com/ray-project/ray/issues/19639.
+  reference_counter_->ReleaseAllLocalReferences();
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:839]: Sorry I don't have much context here, but if we do this always does `reference_counter_->DrainAndShutdown(shutdown);` make sense?

Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:839]: Is this method guaranteed to be called only upon SIGTERM?

Comment (jovany-wang) [reply src/ray/core_worker/core_worker.cc:839]: > Is this method guaranteed to be called only upon SIGTERM?

It will be called in cases of SIGTERM, receiving task_canceled, or other things which invoke `CoreWorker::Exit`

> Sorry I don't have much context here, but if we do this always does reference_counter_-> DrainAndShutdown(shutdown); make sense?

I can't make sure whether `drain_references_callback` is able to be called since it's in another callback.
In current approach, when worker is exiting, it means the local references should be released always. (For task exits normally, the local refs were released in the frontend.)

Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:839]: It is called right? We don't shutdown until actual `shutdown` callback is invoked.

cc @stephanie-wang would this be safe for features like "not killing a worker when we own references"?

Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:839]: Maybe we should do this only for actor cases?

Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:839]: I believe this is correct. You can check out the test that @jovany-wang added for an example where this breaks even though no actors are used.

This will still keep the object in scope if there are other workers using the ref. It's just to make sure that we don't consider the owner's own refs anymore (which can't get released otherwise because we won't return to Python).

File: src/ray/core_worker/reference_count.cc [hunk 16]
```diff
@@ -247,12 +247,28 @@ void ReferenceCounter::SetNestedRefInUseRecursive(ReferenceTable::iterator inner
   }
 }
 
+void ReferenceCounter::ReleaseAllLocalReferences() {
+  absl::MutexLock lock(&mutex_);
+  for (auto &ref : object_id_refs_) {
+    /// Remove multiple times.
```
Comment (rkooo567) [inline src/ray/core_worker/reference_count.cc:253]: This comment is confusing. Can you just remove it or re-comment as "Remove it until owned ref goes to 0?"

File: src/ray/core_worker/core_worker.cc (hunk 15 above)
Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:839]: I see. To make sure I understood this code

```
    for (int i = ref.second.local_ref_count; i > 0; --i) {
      RemoveLocalReferenceInternal(ref.first, nullptr);
    }
```

Only removes the owner's ref count, so if it is used by other workers, it won't be stopped right? (And the purpose of DrainAndShutdown is for this case, so it won't regress)

File: src/ray/core_worker/reference_count.cc (hunk 16 above)
Comment (jovany-wang) [reply src/ray/core_worker/reference_count.cc]: deleted.

**Comment by jovany-wang** [comment]
@rkooo567 @ericl Approve?

**Review by rkooo567 — APPROVED** [review]

**Comment by jovany-wang** [comment]
Windows failure is unrelated.
