### PR TITLE
[core] Fix empty resource update to GCS resource manager. 

### LINKED ISSUE #39644: [core] Transient inconsistent node resource view at GCS
### What happened + What you expected to happen

Each raylet periodically updates GCS for its resources (`ResourcesData`), the resource update contains information such as available resources, total resources on the node. 

However, we also have other parts of the component in GCS that use the same data but with empty fields for other purposes (i.e. GC) here: https://github.com/ray-project/ray/blob/3f11cf4666b4042f9ef66c3ee51486e5ece3cb94/src/ray/gcs/gcs_server/gcs_server.cc#L851-L872

In this PR https://github.com/ray-project/ray/commit/4f5cadc3a5fb6495dc567c2bcdb714fcd8550b5c, we make GCS **unconditionally** override resources view without checking if the data is empty, this means:
- We were skipping empty resource update before 
- But we are not anymore now. 
- Thus GCS might see node's resources view being wrong until the next non-empty resource update comes. 

### Impacts
This will mean that Autoscaler might see the cluster available resources being corrupted sometimes, and leading to wrong scaling decisions.  

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

See https://github.com/ray-project/ray/issues/39644

GCS resource manager is currently mixing processing logic for RESOURCE_VIEW and COMMANDS messages from ray syncer. This PR sepearates the codepaths and make sure `ResroucesData` from the two messages are not affecting each other:
- COMMANDS: this is emitted by NodeManager (in raylet) when triggering global gc if object store is under pressure (and also informing potential resources deadlock). This might not contain any resources (e.g. total resources)
- RESOURCE_VIEW: this is emitted by LocalResourceManager (in raylet) for resources and usage update to GCS. 

## Related issue number

Closes https://github.com/ray-project/ray/issues/39644

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 1]
```diff
@@ -38,6 +38,12 @@ void GcsResourceManager::ConsumeSyncMessage(
   // delegate the work to the main thread for thread safety.
   // Ideally, all public api in GcsResourceManager need to be put into this
   // io context for thread safety.
+
```
Comment (rickyyx) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:41]: Or we could remove this: 

https://github.com/ray-project/ray/blob/3f11cf4666b4042f9ef66c3ee51486e5ece3cb94/src/ray/gcs/gcs_server/gcs_server.cc#L537-L538

Open to either.

**Review by jjyao — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:41]: Good point. Let Yi make a call

**Comment by rickyyx** [comment]
I am trying to add a quick test for this.

**Review by scv119 — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 1 above)
Comment (iycheng) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:41]: I'd prefer removing the register ones and put a RAY_CHECK here.

Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:41]: Sounds good to me!

**Review by rkooo567 — APPROVED** [review]
LGTM given https://github.com/ray-project/ray/pull/39648/files#r1325121300 is addressed

**Comment by rickyyx** [comment]
Added e2e integration tests, which failed consistently on 2.7 but pass here with PR.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 2]
```diff
@@ -38,11 +38,22 @@ void GcsResourceManager::ConsumeSyncMessage(
...
+  // We should only expect RESOURCE_VIEW messages from the syncer for GcsResourceManager.
+  // See GcsServer::InitRaySyncer for syncer registration.
+  RAY_CHECK(message->message_type() == syncer::MessageType::RESOURCE_VIEW);
+
   io_context_.dispatch(
       [this, message]() {
         rpc::ResourcesData resources;
         resources.ParseFromString(message->sync_message());
         resources.set_node_id(message->node_id());
+        if (resources.resources_total_size() == 0) {
```
Comment (rickyyx) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:51]: I am gracefully returning here.

Comment (scv119) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:51]: is this possible with cpu=0 case?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 3]
```diff
@@ -38,11 +38,22 @@ void GcsResourceManager::ConsumeSyncMessage(
   // delegate the work to the main thread for thread safety.
   // Ideally, all public api in GcsResourceManager need to be put into this
   // io context for thread safety.
+
+  // We should only expect RESOURCE_VIEW messages from the syncer for GcsResourceManager.
+  // See GcsServer::InitRaySyncer for syncer registration.
+  RAY_CHECK(message->message_type() == syncer::MessageType::RESOURCE_VIEW);
```
Comment (scv119) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:44]: RAY_CHECK is a bit aggressive. how about ignore the message if it's not RESOURCE_VIEW

**Review by fishbone — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 3 above)
Comment (iycheng) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:44]: I'm not sure, but it shouldn't happen unless there is bug in ray syncer.
We should at least print RAY_ERROR if you are not comfortable with this and need a fix asap.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 2 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:51]: we should still have other resources (e.g. memory).

Comment (iycheng) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:51]: I'm not sure. But I think we can a test with this? Like print the resource here. I think it sould come with CPU/GPU and memory, i mean the basic ones at least.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 3 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:44]: yah, i think this message type assertion should be rather safe (in cases when ray works). Otherwise, it will be a serious bug as Yi mentioned.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 2 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:51]: yah a node will usually come with node ip as resources: https://github.com/ray-project/ray/blob/701a6523c4121fa409f0ceab9b3e4f81f9445aeb/python/ray/_private/resource_spec.py#L160-L163

**Comment by rickyyx** [comment]
So we still need to handle (rather than reject) ray syncer COMMAND messages. These are the messages from NodeManager  sending potential resources deadlocks:

https://github.com/ray-project/ray/blob/c7b352eb6b149668ceb2cd8f78dd9715337cd9e2/src/ray/raylet/node_manager.cc#L2764-L2769


We could have had `RESOURCE_VIEW` carrying this bit of information from resource reports (i.e. here in [LocalResourceManager](https://github.com/ray-project/ray/blob/2522aa47783b4c045290a09d16d8140be97ca687/src/ray/raylet/scheduling/local_resource_manager.cc#L279-L281) ) . However, this message is stopped being sent when there's no available resources updates, which happens when resources deadlock happens. Therefore, it's not easy to piggyback the bit of info in RESOURCE_VIEW message. 


Thus, this PR still accepts both COMMANDS and RESOURCE_VIEW messages, and do the conditional updates depending on where the messages are from.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 4]
```diff
@@ -261,25 +269,30 @@ void GcsResourceManager::HandleGetAllResourceUsage(
...
+      }
+      (*iter->second.mutable_resources_available()) = resources.resources_available();
+      if (resources.resources_normal_task_changed()) {
+        (*iter->second.mutable_resources_normal_task()) =
+            resources.resources_normal_task();
+      }
+    } else {
+      // TODO(rickyx): We should change this to be part of RESOURCE_VIEW.
+      // This is being populated from NodeManager as part of COMMANDS
+      iter->second.set_cluster_full_of_actors_detected(
```
Comment (scv119) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:293]: should we go through this path if the request is from resource view as well?

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 5]
```diff
@@ -315,6 +315,80 @@ def verify():
...
+def foo():
+    ray.put(bytearray(1024*1024* 50))
+
+
+while True:
+    ray.get([foo.remote() for _ in range(50)])
+"""
+
+    try:
+        # This should trigger many COMMANDS messages from TryGlobalGC on GCS.
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:354]: actually don't we want many COMMANDS message from raylet?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 6]
```diff
@@ -124,7 +126,8 @@ void GcsResourceManager::HandleGetAllAvailableResources(
   ++counts_[CountType::GET_ALL_AVAILABLE_RESOURCES_REQUEST];
 }
 
-void GcsResourceManager::UpdateFromResourceReport(const rpc::ResourcesData &data) {
+void GcsResourceManager::UpdateFromResourceReport(const rpc::ResourcesData &data,
+                                                  bool from_resource_view) {
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:130]: (Probably too much for this PR) Ideally instead of having a `bool from_resource_view`, we should have two completely different code path for consuming two different types of messages.

File: python/ray/autoscaler/v2/tests/test_e2e.py (hunk 5 above)
Comment (rickyyx) [reply python/ray/autoscaler/v2/tests/test_e2e.py:354]: oh yes, we want those to be triggered - thus all the sys configs.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 6 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:130]: i think it's a good idea. Let me try.

File: python/ray/autoscaler/v2/tests/test_e2e.py (hunk 5 above)
Comment (jjyao) [reply python/ray/autoscaler/v2/tests/test_e2e.py:354]: Does that mean the comment is not accurate?

**Review by jjyao — APPROVED** [review]

File: python/ray/autoscaler/v2/tests/test_e2e.py (hunk 5 above)
Comment (rickyyx) [reply python/ray/autoscaler/v2/tests/test_e2e.py:354]: i guess i do wanna trigger many COMMANDS here? i might be missing something.

**Comment by rickyyx** [comment]
Core nightly release test: https://buildkite.com/ray-project/release-tests-pr/builds/53291
