### PR TITLE
[core] Pin arguments during task execution

### LINKED ISSUE #12663: [Object Spilling] Thrashing when there are large number of dependencies for many tasks
### What is the problem?

Discovered from the shuffling workload: https://gist.github.com/ericl/d419c6373928b4b7c8739738262da287

When there are many tasks with a large number of dependencies, tasks are not properly scheduled because they are waiting for dependencies to be local, but some of the dependencies are evicted (to make space) before every dependency becomes local. These dependencies are restored again, but after that, it is re-evicted. This leads all of the tasks to be in the waiting state and not executed forever (which causes the hanging). 

There might be many solutions, but one of them is to temporarily pin the restored objects until it is used by tasks. Indeed, this sort of thrashing behavior can happen even for non-object spilling scenarios (pull->evicted->pull->evicted), so this can help to optimize the object pulling in general. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Currently, there is a race condition where a task's arguments can get evicted after the task is dispatched but before the worker has gotten the arguments from the object store. This can lead to a deadlock if there are too many requests to pull other objects in the node's queue.

This fixes the race condition by having the raylet pin the dependencies while a task lease is granted.

## Related issue number

Closes #12663.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 1]
```diff
@@ -144,11 +146,27 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+      bool success = true;
+      const auto &deps = spec.GetDependencyIds();
+      if (!deps.empty()) {
+        success = pin_task_arguments_(deps, &args);
+        if (!success) {
+          RAY_LOG(WARNING) << "Error getting task arguments from plasma store";
+        }
+        for (size_t i = 0; i < deps.size(); i++) {
+          if (args[i] == nullptr) {
+            RAY_LOG(INFO) << "Task " << spec.TaskId() << " argument " << deps[i] << " was evicted before task could be dispatched";
```
Comment (rkooo567) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:159]: Can you comment when this can happen? It happens only when some of objects are evicted before the whole bundle is pulled?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 2]
```diff
@@ -144,11 +146,27 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
       auto &task = std::get<0>(work);
       auto &spec = task.GetTaskSpecification();
 
+      std::vector<std::unique_ptr<RayObject>> args;
+      bool success = true;
+      const auto &deps = spec.GetDependencyIds();
+      if (!deps.empty()) {
+        success = pin_task_arguments_(deps, &args);
```
Comment (rkooo567) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:153]: Can you comment args will have a reference to a plasma store?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 3]
```diff
@@ -252,8 +271,9 @@ TEST_F(ClusterTaskManagerTest, ResourceTakenWhileResolving) {
   };
 
   /* Blocked on dependencies */
-  dependency_manager_.task_ready_ = false;
-  auto task = CreateTask({{ray::kCPU_ResourceLabel, 5}}, 1);
+  auto task = CreateTask({{ray::kCPU_ResourceLabel, 5}}, 2);
```
Comment (rkooo567) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:274]: Unrelated to this line of code, but maybe we can add a simple test that all args are pinned correctly?

**Review by rkooo567 — COMMENTED** [review]
LGTM! Is the reason why we don't pin an object as soon as it is pulled because that's more complex or less robust?

File: src/ray/raylet/scheduling/cluster_task_manager.h [hunk 4]
```diff
@@ -248,6 +250,15 @@ class ClusterTaskManager : public ClusterTaskManagerInterface {
...
   std::unordered_map<WorkerID, std::shared_ptr<WorkerInterface>> &leased_workers_;
 
+  /// Callback to get references to task arguments. These will be pinned while
+  /// the task is running.
+  std::function<bool(const std::vector<ObjectID> &object_ids, std::vector<std::unique_ptr<RayObject>> *results)> pin_task_arguments_;
+
+  /// Arguments needed by currently granted lease requests. These should be
+  /// pinned before the lease is granted to ensure that the arguments are not
+  /// evicted before the task(s) start running.
+  std::unordered_map<TaskID, std::vector<std::unique_ptr<RayObject>>> pinned_task_arguments_;
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.h:260]: Could we add this to DebugString()?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 5]
```diff
@@ -783,15 +804,15 @@ TEST_F(ClusterTaskManagerTest, ArgumentEvicted) {
...
+  missing_objects_.insert(missing_arg);
   pool_.PushWorker(std::dynamic_pointer_cast<WorkerInterface>(worker));
   task_manager_.ScheduleAndDispatchTasks();
   ASSERT_EQ(dependency_manager_.subscribed_tasks, expected_subscribed_tasks);
   ASSERT_EQ(num_callbacks, 0);
   ASSERT_EQ(leased_workers_.size(), 0);
 
   /* Worker available and arguments available */
-  dependency_manager_.task_ready_ = true;
+  missing_objects_.erase(missing_arg);
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:815]: Can we add a test that the pinned object is unpinned when the lease is returned?

File: src/ray/raylet/node_manager.cc [hunk 6]
```diff
@@ -2346,33 +2375,14 @@ void NodeManager::HandlePinObjectIDs(const rpc::PinObjectIDsRequest &request,
     object_ids.push_back(ObjectID::FromBinary(object_id_binary));
   }
   if (object_pinning_enabled_) {
```
Comment (ericl) [inline src/ray/raylet/node_manager.cc:2377]: Should we remove this feature flag (separately)?

**Review by ericl — APPROVED** [review]
LGTM; simpler than I thought.

File: src/ray/raylet/node_manager.cc (hunk 6 above)
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc:2377]: Yeah, I think it's just used for LRU right now (and I guess if you wanted to turn off ref counting manually, but I don't think that should be recommended or exposed anymore...).
