### PR TITLE
[Core] Fix negative resource availability during resource broadcasting

### LINKED ISSUE #39138: [Core] GCS check failure: scorer.cc:52:  Check failed: available >= 0 Available resource -1 should be nonnegative.
### What happened + What you expected to happen

```
[2023-08-29 20:07:01,199 C 290 290] (gcs_server) scorer.cc:52:  Check failed: available >= 0 Available resource -1 should be nonnegative.
*** StackTrace Information ***
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0xa374ca) [0x5640866774ca] ray::operator<<()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0xa38fa2) [0x564086678fa2] ray::SpdLogMessage::Flush()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0xa392b7) [0x5640866792b7] ray::RayLog::~RayLog()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3d9e00) [0x564086019e00] ray::raylet_scheduling_policy::LeastResourceScorer::Calculate()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3da39c) [0x56408601a39c] ray::raylet_scheduling_policy::LeastResourceScorer::Score()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3e03ce) [0x5640860203ce] ray::raylet_scheduling_policy::BundleSchedulingPolicy::GetBestNode()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3e4b42) [0x564086024b42] ray::raylet_scheduling_policy::BundlePackSchedulingPolicy::Schedule()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3df4e1) [0x56408601f4e1] ray::raylet_scheduling_policy::CompositeBundleSchedulingPolicy::Schedule()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3ce840) [0x56408600e840] ray::ClusterResourceScheduler::Schedule()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x3442fd) [0x564085f842fd] ray::gcs::GcsPlacementGroupScheduler::ScheduleUnplacedBundles()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x353cc5) [0x564085f93cc5] ray::gcs::GcsPlacementGroupManager::SchedulePendingPlacementGroups()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x353dc0) [0x564085f93dc0] ray::gcs::GcsPlacementGroupManager::Tick()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x234a11) [0x564085e74a11] boost::asio::detail::wait_handler<>::do_complete()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0xb2a28b) [0x56408676a28b] boost::asio::detail::scheduler::do_run_one()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0xb2c379) [0x56408676c379] boost::asio::detail::scheduler::run()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0xb2c832) [0x56408676c832] boost::asio::io_context::run()
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x17ec39) [0x564085dbec39] main
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f287ad4b083] __libc_start_main
/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/gcs/gcs_server(+0x1cde67) [0x564085e0de67]
```

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

None

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?

This fixes the GCS check failure 
```
[2023-08-29 20:07:01,199 C 290 290] (gcs_server) scorer.cc:52:  Check failed: available >= 0 Available resource -1 should be nonnegative.
```

The issue is that we shouldn't broadcast negative resource availability since the remaining of the system assumes that it can not be negative. Negative resource availability should only be a concept known to the local node for nested tasks implementation.

## Related issue number
Closes #39138

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Is there a related issue opened?

File: src/ray/raylet/scheduling/local_resource_manager.cc [hunk 1]
```diff
@@ -298,9 +298,15 @@ std::optional<syncer::RaySyncMessage> LocalResourceManager::CreateSyncMessage(
   auto total = resources.total.GetResourceMap();
   resources_data.mutable_resources_total()->insert(total.begin(), total.end());
 
-  auto available = resources.available.GetResourceMap();
-  resources_data.mutable_resources_available()->insert(available.begin(),
-                                                       available.end());
+  for (const auto &[resource_name, available] : resources.available.GetResourceMap()) {
+    // Resource availability can be negative locally but treat it as 0
```
Comment (rkooo567) [inline src/ray/raylet/scheduling/local_resource_manager.cc:302]: It's the same behavior before syncer right? In terms of behavior, it will be the same as before

**Review by rkooo567 — APPROVED** [review]

File: src/ray/raylet/scheduling/local_resource_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/raylet/scheduling/local_resource_manager.cc:302]: Yes, same behavior before syncer.
