### PR TITLE
[core] Ref counting for actor handles

### LINKED ISSUE #3472: Actor handle GC is problematic.
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Ray installed from (source or binary)**: source
- **Ray version**: latest master
- **Python version**: all
- **Exact command to reproduce**: n/a

### Describe the problem

Currently, when the original actor handle is garbage collected by Python interpreter, a `__ray_terminate__` message will be sent to also terminate the actor, see https://github.com/ray-project/ray/blob/06f6431765b16da7cdb924cb4716a35acf0fba84/python/ray/actor.py#L662. 

This mechanism is problematic, because 
1) If there're forked handles, the actor shouldn't be terminated.
2) `__del__` is unreliable and not recommended to use, see https://stackoverflow.com/questions/1481488/what-is-the-del-method-how-to-call-it.

The first point is a critical problem and is hard to handle automatically. Even if we count the number of forked handles, and only terminate the actor when all handles are GC'ed. It's still problematic if users serialize a handle and deserialize it after a long time. Ray doesn't know when an actor is not needed any more. Only the user knows. 

Thus, I'm in favor of letting the users manually GC an actor with `actor.__ray_terminate__.remote()`, when they don't need the actor any more. To prevent the actor from wasting resource forever, there's already the mechanism that we'll clean up all workers when a driver exits.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Before, actors were kept alive as long as the creator's reference to the actor was active. This meant that if the creator exited, the actor might exit even though other handles to the actor were still active. 

This PR reuses the ref counting for normal `ObjectID`s to implement ref counting for actor handles by adding an `ObjectID` to the Python `ActorHandle` object. After this PR, an actor will be kept alive as the process that created it is still alive and there are any references to the actor's handle in scope.

Because distributed reference counting (#6945) is still feature-flagged off, this will only cover cases where an actor handle is passed by the original creator. If the actor handle is passed by a task/actor that did not originally create it, then the actor may exit early.

## Related issue number

Doesn't fix it yet, but one step closer to #6370
Closes #3472

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -779,24 +781,27 @@ Status CoreWorker::CreateActor(const RayFunction &function,
...
         std::max(RayConfig::instance().actor_creation_min_retries(),
                  actor_creation_options.max_reconstructions));
-    return direct_task_submitter_->SubmitTask(task_spec);
+    status = direct_task_submitter_->SubmitTask(task_spec);
   } else {
-    return local_raylet_client_->SubmitTask(task_spec);
+    status = local_raylet_client_->SubmitTask(task_spec);
   }
+
+  *actor_object_id = return_ids[0];
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc]: Is it true that this value will always be the same as `ObjectID::ForTaskReturn(TaskID::ForActorCreationTask(actor_id), 0)`? I didn't see any random bits in this.

If so, maybe we can generate the id on the fly instead of storing it.

Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc]: Oh hmm yeah I didn't see that function. That should work for C++.

We'll still have to store it in Python, though, since we're relying on the `ObjectID`'s python ref to track when the local ref goes out of scope and when the handle gets passed into a task.

**Comment by ericl** [comment]
Could you do the callback when the actor handle goes out of scope and treat
it as the id?

**Comment by stephanie-wang** [comment]
> Could you do the callback when the actor handle goes out of scope and treat it as the id?

Yes, but that won't cover the cases where the actor handle gets passed or nested inside other objects. If you have suggestions on how to do it, I can try it, but this seemed much simpler to me.

**Comment by ericl** [comment]
Right, I guess I was thinking you can synthesize the object id on the fly
in hooks for those cases too. Not sure how much code that adds.

**Comment by stephanie-wang** [comment]
Hmm let me try it and see. It might be good to separate out the logic about
actor handles more.

File: python/ray/actor.py [hunk 2]
```diff
@@ -807,12 +780,15 @@ def _serialization_helper(self, ray_forking):
 
         if hasattr(worker, "core_worker"):
             # Non-local mode
-            state = worker.core_worker.serialize_actor_handle(self)
+            state = worker.core_worker.serialize_actor_handle(
+                self._ray_actor_id)
+            state = (state, self._ray_actor_creation_return_id)
```
Comment (edoakes) [inline python/ray/actor.py]:
```suggestion
            state = (worker.core_worker.serialize_actor_handle(
                self._ray_actor_id), self._ray_actor_creation_return_id)
```

Comment (edoakes) [reply python/ray/actor.py]: So cool you can do multi-line suggestions now!

**Review by edoakes — COMMENTED** [review]
Looks great!

The changes to the `Exit()` logic look nice too - might be better to separate that into a different PR though. I think @kfstorm was going to add the same logic in https://github.com/ray-project/ray/pull/7346. Maybe you could separate the `Exit()` logic here into a separate PR and then both this and https://github.com/ray-project/ray/pull/7346 can rebase off of that?

LMK when you update with change that Eric suggested and I'll look again.

**Comment by stephanie-wang** [comment]
@edoakes I think the overlap with #7346 looks small enough that I'd rather just leave the changes in this PR and resolve the conflict later, if that's okay with you.

This PR is ready to review again.

**Review by edoakes — COMMENTED** [review]
Everything looks good except for the comment I left about overwriting the pending force kills.

Also, one thing to keep in mind is it might be nice to extend the changes here to add an API to check when an actor creation task has finished without submitting a new task. Are the currently changes compatible with that? Seems like we just need to be able to resolve the object ID associated with an actor handle in the same way that we do for serialized object IDs. This actually might have been easier with the previous iteration that stored the object ID :/

**Review by edoakes — APPROVED** [review]
LGTM! Should wait for @zhijunfu to have a look before merging.

**Comment by zhijunfu** [comment]
> LGTM! Should wait for @zhijunfu to have a look before merging.

Thanks, took a quick look ant it looks good to me.

**Comment by jovany-wang** [comment]
Note that this PR breaks the streaming CI.

@ffbin
