### PR TITLE
[Log] new spdlog tool for ray

### LINKED ISSUE #10493: Ray uses spdlog instead of glog
I have talked with @rkooo567 in slack link https://ray-distributed.slack.com/archives/C016MPZE1L1/p1598937145003600.
Reasons:

- glog lacks features such as log rotation or custom formatting. Log rotation is critical function of long running job becase the disk will become full due to a large number of log files being written without daily or custom rotation configuration.

- glog only supports writing files to different sinks for different severity.

Solution:
Replace glog with spdlog. This is homepage in github https://github.com/gabime/spdlog
Its simple description:
```
Very fast (see benchmarks below).
Headers only or compiled
Feature rich formatting, using the excellent fmt library.
Asynchronous mode (optional)
Custom formatting.
Multi/Single threaded loggers.
Various log targets:
Rotating log files.
Daily log files.
Console logging (colors supported).
syslog.
Windows debugger (OutputDebugString(..))
Easily extendable with custom log targets (just implement a single function in the sink interface).
Log filtering - log levels can be modified in runtime as well as in compile time.
Support for loading log levels from argv or from environment var.
Backtrace support - store debug messages in a ring buffer and display later on demand.
```

Spdlog repo and deps will be introduced in @Basasuya PR  https://github.com/ray-project/ray/pull/10419

### PR DESCRIPTION
**Pull request by ashione**
Motiviation:
* For long running job, it'd better to support log rotation
* For easily debug, we may change loglevel in runtime
* Support multiple sinks. Ray core worker can only focus on itself log message if user want to reuse ray log tool in cpp worker, so application logs will not mixed with ray core informations.
* More advanced functions: user-defined format pattern, async flush for high performace and trace session
## Why are these changes needed?
A new log tool for users.

## Related issue number

https://github.com/ray-project/ray/issues/10493

spdlog V.S. glog : https://docs.google.com/document/d/1pEXTLOhTFu5-va14Wj-tGoJD9tt_M_-JRMtxqd1JCyI
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ashione** [comment]
@rkooo567 @ericl

**Comment by ashione** [comment]
I test both glog and spdlog:
glog performance of Pertest in logging_test.cc
log file name pattern : LogPerfTest.20200923-142334.49592.log 
```
[       OK ] LogPerfTest.PerfTest (10494 ms)
[----------] 1 test from LogPerfTest (10494 ms total)
```

spdlog : log file name pattern  LogPerfTest_45421.log ( It can be modifed as same as glog)
```
Testing DEBUG log for 100000 rounds takes 0 ms.
Testing RAY_ERROR log for 100000 rounds takes 1210 ms.
Testing RAY_CHECK(true) for 100000 rounds takes 0 ms.
[       OK ] LogPerfTest.PerfTest (1239 ms)
[----------] 1 test from LogPerfTest (1239 ms total)
```

Only one difference is glog will produce log messages in both console(stdout) and log, but spdlog we define currently just flush them in log file.

**Comment by kfstorm** [comment]
Can you add some details about the motivation in the description?

**Comment by ashione** [comment]
> Can you add some details about the motivation in the description?

More details you may find in this issue https://github.com/ray-project/ray/issues/10493 and its related event PR https://github.com/ray-project/ray/pull/10419

**Comment by rkooo567** [comment]
So, does it mean spdlog is 10 times faster than glog in your workload?

**Comment by rkooo567** [comment]
Can you also push the testing code to this PR?

**Comment by ashione** [comment]
> Can you also push the benchmarking code to this PR?

It is LogPerfTest in src/ray/util/logging_test.cc.

**Comment by ashione** [comment]
> So, does it mean spdlog is 10 times faster than glog in your workload?
> 
> Also, why don't we do this `Only one difference is glog will produce log messages in both console(stdout) and log,` in this PR?

~ 5200ms when I remove stderr verbose of glog. (Just change `google::SetStderrLogging(GetMappedSeverity(RayLogLevel::ERROR));` to `google::SetStderrLogging(GetMappedSeverity(RayLogLevel::FATAL));`

**Comment by ashione** [comment]
@rkooo567 I have pushed benchmark target commit. You may execute 
`bazel test logging_spdlog_test` and `bazel test logging_test` to show their different performance.
In my MacBook Pro with 2.2 GHz Intel Core i7, 6 GB 1600 MHz DDR3
```
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from PrintLogTest
[ RUN      ] PrintLogTest.LogTestWithoutInit
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0924 13:57:48.694461 39597 2729898880 logging_test.cc:40] This is the INFO message
W0924 13:57:48.696022 39597 2729898880 logging_test.cc:42] This is the WARNING message
E0924 13:57:48.696040 39597 2729898880 logging_test.cc:44] This is the ERROR message
[       OK ] PrintLogTest.LogTestWithoutInit (2 ms)
[ RUN      ] PrintLogTest.LogTestWithInit
[       OK ] PrintLogTest.LogTestWithInit (1 ms)
[----------] 2 tests from PrintLogTest (3 ms total)

[----------] 1 test from LogPerfTest
[ RUN      ] LogPerfTest.PerfTest
Testing DEBUG log for 100000 rounds takes 0 ms.
Testing RAY_ERROR log for 100000 rounds takes 5701 ms.
Testing RAY_CHECK(true) for 100000 rounds takes 0 ms.
[       OK ] LogPerfTest.PerfTest (5721 ms)
[----------] 1 test from LogPerfTest (5721 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test cases ran. (5724 ms total)
[  PASSED  ] 3 tests.
``` 

And 

```
[==========] Running 3 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 2 tests from PrintLogTest
[ RUN      ] PrintLogTest.LogTestWithoutInit
[2020-09-24 13:58:07.811] [info] logging_test.cc:40: This is the INFO message
[2020-09-24 13:58:07.812] [warning] logging_test.cc:42: This is the WARNING message
[2020-09-24 13:58:07.812] [error] logging_test.cc:44: This is the ERROR message
[       OK ] PrintLogTest.LogTestWithoutInit (1 ms)
[ RUN      ] PrintLogTest.LogTestWithInit
[2020-09-24 13:58:07,812 D 40336 10382541] logging_test.cc:37: This is the DEBUG message
[2020-09-24 13:58:07,812 I 40336 10382541] logging_test.cc:40: This is the INFO message
[2020-09-24 13:58:07,812 W 40336 10382541] logging_test.cc:42: This is the WARNING message
[2020-09-24 13:58:07,812 E 40336 10382541] logging_test.cc:44: This is the ERROR message
[       OK ] PrintLogTest.LogTestWithInit (0 ms)
[----------] 2 tests from PrintLogTest (1 ms total)

[----------] 1 test from LogPerfTest
[ RUN      ] LogPerfTest.PerfTest
Testing DEBUG log for 100000 rounds takes 0 ms.
Testing RAY_ERROR log for 100000 rounds takes 1392 ms.
Testing RAY_CHECK(true) for 100000 rounds takes 0 ms.
[       OK ] LogPerfTest.PerfTest (1432 ms)
[----------] 1 test from LogPerfTest (1432 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 2 test cases ran. (1433 ms total)
[  PASSED  ] 3 tests.
```

**Comment by rkooo567** [comment]
@ashione Can you remove WIP when it is ready?

**Comment by ashione** [comment]
> @ashione Can you remove WIP when it is ready?

I remove `WIP` and create all same functions for spdlog.

**Comment by kfstorm** [comment]
@ashione Please avoid rebasing/modifying commit history in a pull request. It's hard to find out what's changed since the last review.

File: src/ray/util/logging.cc [hunk 1]
```diff
@@ -73,6 +81,59 @@ struct StdoutLogger : public google::base::Logger {
...
+      logger = spdlog::stderr_color_mt("stderr");
+      logger->set_pattern("[%Y-%m-%d %H:%M:%S,%e %L %P %t] %v");
+    }
+    return logger;
+  }
+
+  inline void Flush() {
+    auto logger = get_logger();
+    if (loglevel_ == static_cast<int>(spdlog::level::critical)) {
+      stream() << "\n" << ray::GetCallTrace();
```
Comment (kfstorm) [inline src/ray/util/logging.cc:115]: Why we need this line? I think GLOG will fetch the stack trace for us once `std::abort()` is invoked.

**Review by kfstorm — COMMENTED** [review]
Could you paste an example output of `RAY_CHECK`?

File: src/ray/util/logging.cc (hunk 1 above)
Comment (ashione) [reply src/ray/util/logging.cc:115]: > Could you paste an example output of `RAY_CHECK`?

Stacktraces will be exactly produced twice with InstallFailureSignalHandler, but nothing will be catched we do not call GetCallTrace manually without InstallFailureSignalHandler for glog.

**Comment by ashione** [comment]
> Could you paste an example output of `RAY_CHECK`?

Something like that 
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from PrintLogTest
[ RUN      ] PrintLogTest.RayCheckAbortTest
[2020-10-19 13:55:37,743 C 37433 2749808] logging_test.cc:140:  Check failed: 0 Check for aborting
    @        0x107aae9f8  ray::SpdLogMessage::Flush()
    @        0x107aadf99  ray::RayLog::~RayLog()
    @        0x107a62393  ray::PrintLogTest_RayCheckAbortTest_Test::TestBody()
    @        0x108404ff8  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x108404f4e  testing::Test::Run()
    @        0x108405f10  testing::TestInfo::Run()
    @        0x1084067c7  testing::TestCase::Run()
    @        0x108412e47  testing::internal::UnitTestImpl::RunAllTests()
    @        0x108412868  testing::internal::HandleExceptionsInMethodIfSupported<>()
    @        0x1084127ed  testing::UnitTest::Run()
    @        0x107a625a1  main
    @     0x7fff7488c015  start
```

File: BUILD.bazel [hunk 2]
```diff
@@ -1325,6 +1338,35 @@ cc_library(
...
+    ]),
+    copts = COPTS_SPDLOG,
+    strip_include_prefix = "src",
+    visibility = ["//visibility:public"],
+    deps = [
+        ":sha256",
+        "//src/ray/protobuf:event_cc_proto",
+        "@boost//:asio",
+        "@boost//:property_tree",
+        "@com_github_google_glog//:glog",
```
Comment (rkooo567) [inline BUILD.bazel:1362]: We still need this for signal handling and stacktrace print right?

**Review by rkooo567 — COMMENTED** [review]
Will review it very soon :) 

Btw, if glog anyway doesn't support Windows stacktrace support, should we try this library? https://github.com/bombela/backward-cpp

**Comment by rkooo567** [comment]
@ashione Also, can you bring up about this topic in tomorrow's sync up meeting?

File: BUILD.bazel (hunk 2 above)
Comment (ashione) [reply BUILD.bazel]: > We still need this for signal handling and stacktrace print right?

It's indeed now.

**Comment by ashione** [comment]
> @ashione Also, can you bring up about this topic in tomorrow's sync up meeting? (so that everyone will be on the same page about spdlog adoption)

That's OK.

**Comment by ashione** [comment]
> @ashione Please avoid rebasing/modifying commit history in a pull request. It's hard to find out what's changed since the last review.

I wanna to rebase the lastest master but find a lot of unrelated changed are added this PR. Is merge-command suggested for this case?

**Comment by rkooo567** [comment]
I always use the merge master command and never had any trouble (and it is okay to do this because the commit history doesn't matter anyway. All of commits are merged into one by Github when merged).

**Comment by kfstorm** [comment]
> > Could you paste an example output of `RAY_CHECK`?
> 
> Something like that
> 
> ```
> [==========] Running 1 test from 1 test case.
> [----------] Global test environment set-up.
> [----------] 1 test from PrintLogTest
> [ RUN      ] PrintLogTest.RayCheckAbortTest
> [2020-10-19 13:55:37,743 C 37433 2749808] logging_test.cc:140:  Check failed: 0 Check for aborting
>     @        0x107aae9f8  ray::SpdLogMessage::Flush()
>     @        0x107aadf99  ray::RayLog::~RayLog()
>     @        0x107a62393  ray::PrintLogTest_RayCheckAbortTest_Test::TestBody()
>     @        0x108404ff8  testing::internal::HandleExceptionsInMethodIfSupported<>()
>     @        0x108404f4e  testing::Test::Run()
>     @        0x108405f10  testing::TestInfo::Run()
>     @        0x1084067c7  testing::TestCase::Run()
>     @        0x108412e47  testing::internal::UnitTestImpl::RunAllTests()
>     @        0x108412868  testing::internal::HandleExceptionsInMethodIfSupported<>()
>     @        0x1084127ed  testing::UnitTest::Run()
>     @        0x107a625a1  main
>     @     0x7fff7488c015  start
> ```

I can't find `SIGABRT` in the log. Is it intended? What does the log look like if it's a `SIGSEGV`?

**Comment by ashione** [comment]
> > > Could you paste an example output of `RAY_CHECK`?
> > 
> > 
> > Something like that
> > ```
> > [==========] Running 1 test from 1 test case.
> > [----------] Global test environment set-up.
> > [----------] 1 test from PrintLogTest
> > [ RUN      ] PrintLogTest.RayCheckAbortTest
> > [2020-10-19 13:55:37,743 C 37433 2749808] logging_test.cc:140:  Check failed: 0 Check for aborting
> >     @        0x107aae9f8  ray::SpdLogMessage::Flush()
> >     @        0x107aadf99  ray::RayLog::~RayLog()
> >     @        0x107a62393  ray::PrintLogTest_RayCheckAbortTest_Test::TestBody()
> >     @        0x108404ff8  testing::internal::HandleExceptionsInMethodIfSupported<>()
> >     @        0x108404f4e  testing::Test::Run()
> >     @        0x108405f10  testing::TestInfo::Run()
> >     @        0x1084067c7  testing::TestCase::Run()
> >     @        0x108412e47  testing::internal::UnitTestImpl::RunAllTests()
> >     @        0x108412868  testing::internal::HandleExceptionsInMethodIfSupported<>()
> >     @        0x1084127ed  testing::UnitTest::Run()
> >     @        0x107a625a1  main
> >     @     0x7fff7488c015  start
> > ```
> 
> I can't find `SIGABRT` in the log. Is it intended? What does the log look like if it's a `SIGSEGV`?

It's shown by return value of command line.
```
[1]    40850 abort      sh -c "bazel-bin/logging_test --gtest_filter=*AbortTest"
```

**Comment by kfstorm** [comment]
FYI, I tested with an `std::abort()` and this is the log file:

```
tail -n 20 python-core-driver-01000000ffffffffffffffffffffffffffffffff_854.log
[2020-10-20 16:02:22,220 I 854 1015] actor_manager.cc:127: received notification on actor, state: DEPENDENCIES_UNREADY, actor_id: df5a1a8201000000, ip address: , port: 0, worker_id: NIL_ID, raylet_id: NIL_ID, num_restarts: 0
[2020-10-20 16:02:22,220 I 854 854] direct_task_transport.cc:47: Creating actor via GCS actor id = : df5a1a8201000000
[2020-10-20 16:02:22,220 E 854 1015] logging.cc:397: *** Aborted at 1603180942 (unix time) try "date -d @1603180942" if you are using GNU date ***
[2020-10-20 16:02:22,222 E 854 1015] logging.cc:397: PC: @                0x0 (unknown)
[2020-10-20 16:02:22,222 E 854 1015] logging.cc:397: *** SIGABRT (@0x70900000356) received by PID 854 (TID 0x7f6506ffd700) from PID 854; stack trace: ***
[2020-10-20 16:02:22,223 E 854 1015] logging.cc:397:     @     0x7f6526755620 (unknown)
[2020-10-20 16:02:22,224 E 854 1015] logging.cc:397:     @     0x7f6525ca5277 __GI_raise
[2020-10-20 16:02:22,225 E 854 1015] logging.cc:397:     @     0x7f6525ca6968 __GI_abort
[2020-10-20 16:02:22,226 E 854 1015] logging.cc:397:     @     0x7f65187a2c09 ray::CoreWorkerDirectActorTaskSubmitter::SendPendingTasks()
[2020-10-20 16:02:22,227 E 854 1015] logging.cc:397:     @     0x7f65187a84a5 _ZNSt17_Function_handlerIFvvEZN3ray34CoreWorkerDirectActorTaskSubmitter10SubmitTaskENS1_17TaskSpecificationEEUlvE_E9_M_invokeERKSt9_Any_data
[2020-10-20 16:02:22,228 E 854 1015] logging.cc:397:     @     0x7f65187afcb2 ray::LocalDependencyResolver::ResolveDependencies()
[2020-10-20 16:02:22,230 E 854 1015] logging.cc:397:     @     0x7f65187ae805 ray::CoreWorkerDirectActorTaskSubmitter::SubmitTask()
[2020-10-20 16:02:22,230 E 854 1015] logging.cc:397:     @     0x7f651873893c _ZN5boost4asio6detail18completion_handlerIZN3ray10CoreWorker15SubmitActorTaskERKNS3_7ActorIDERKNS3_11RayFunctionERKSt6vectorISt10unique_ptrINS3_7TaskArgESt14default_deleteISD_EESaISG_EERKNS3_11TaskOptionsEPSB_INS3_8ObjectIDESaISO_EEEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
[2020-10-20 16:02:22,232 E 854 1015] logging.cc:397:     @     0x7f6518baa6fd boost::asio::detail::scheduler::do_run_one()
[2020-10-20 16:02:22,233 E 854 1015] logging.cc:397:     @     0x7f6518bab1c1 boost::asio::detail::scheduler::run()
[2020-10-20 16:02:22,234 E 854 1015] logging.cc:397:     @     0x7f6518bacc92 boost::asio::io_context::run()
[2020-10-20 16:02:22,235 E 854 1015] logging.cc:397:     @     0x7f6518722c80 ray::CoreWorker::RunIOService()
[2020-10-20 16:02:22,236 E 854 1015] logging.cc:397:     @     0x7f65180abc60 (unknown)
[2020-10-20 16:02:22,237 E 854 1015] logging.cc:397:     @     0x7f652674de25 start_thread
[2020-10-20 16:02:22,238 E 854 1015] logging.cc:397:     @     0x7f6525d6cf1d __clone
```

The only difference from the glog solution is that there are many duplicated `[2020-10-20 16:02:22,235 E 854 1015] logging.cc:397:`.

**Review by kfstorm — APPROVED** [review]
LGTM.

**Comment by rkooo567** [comment]
@kfstorm please don’t merge it yet. I will review it tmrw

**Comment by kfstorm** [comment]
@rkooo567 Don't worry. I'm not going to merge this PR without your approval.

File: src/ray/util/logging.cc [hunk 3]
```diff
@@ -73,6 +81,62 @@ struct StdoutLogger : public google::base::Logger {
...
+  if (!base) base = strrchr(filepath, '\\');
+#endif
+  return base ? (base + 1) : filepath;
+}
+
+class SpdLogMessage final {
+ public:
+  explicit SpdLogMessage(const char *file, int line, int loglevel) : loglevel_(loglevel) {
+    stream() << ConstBasename(file) << ":" << line << ": ";
+  }
```
Comment (rkooo567) [inline src/ray/util/logging.cc:98]:
```suggestion
  }
  
```

File: src/ray/util/logging.cc [hunk 4]
```diff
@@ -73,6 +81,62 @@ struct StdoutLogger : public google::base::Logger {
...
+  inline std::shared_ptr<spdlog::logger> get_logger() {
+    auto logger = spdlog::get("ray_log_sink");
+    if (!logger) {
+      logger = spdlog::get("stderr");
+    }
+    // If no default logger we just emit all log informations to stderr.
```
Comment (rkooo567) [inline src/ray/util/logging.cc:104]: When's the time we don't have a default logger? Can you comment it?

File: src/ray/util/logging.cc [hunk 5]
```diff
@@ -73,6 +81,62 @@ struct StdoutLogger : public google::base::Logger {
...
+
+  inline void Flush() {
+    auto logger = get_logger();
+    // To avoid dump duplicated stacktrace with installed failure signal
+    // handler, we have to check whether glog failure signal handler is enabled.
+    if (!RayLog::IsFailureSignalHandlerEnabled() &&
+        loglevel_ == static_cast<int>(spdlog::level::critical)) {
+      stream() << "\n*** StackTrace Information ***\n" << ray::GetCallTrace();
+    }
+    logger->log(static_cast<spdlog::level::level_enum>(loglevel_), "{}", str_.str());
```
Comment (rkooo567) [inline src/ray/util/logging.cc:120]:
```suggestion
    logger->log(static_cast<spdlog::level::level_enum>(loglevel_), /*fmt*/ "{}", str_.str());
```?

Comment (rkooo567) [reply src/ray/util/logging.cc:120]: Not sure if it is the correct argument. Can you specify what this argument means?

File: src/ray/util/logging_test.cc [hunk 6]
```diff
@@ -15,6 +15,7 @@
 #include "ray/util/logging.h"
 
 #include <chrono>
+#include <csignal>
```
Comment (rkooo567) [inline src/ray/util/logging_test.cc:18]: Why is it added when we commented out all tests here?

File: src/ray/util/logging_test.cc [hunk 7]
```diff
@@ -122,6 +123,27 @@ TEST(PrintLogTest, CallstackTraceTest) {
...
+/// will terminated if abort signal raising.
+/*
+bool get_abort_signal = false;
+void signal_handler(int signum) {
+  RAY_LOG(WARNING) << "Interrupt signal (" << signum << ") received.";
+  get_abort_signal = signum == SIGABRT;
+  exit(0);
+}
+
+TEST(PrintLogTest, RayCheckAbortTest) {
```
Comment (rkooo567) [inline src/ray/util/logging_test.cc:137]: How did it work before?

File: src/ray/util/logging.cc [hunk 8]
```diff
@@ -245,24 +378,48 @@ void RayLog::UninstallSignalAction() {
...
+#if defined(RAY_USE_GLOG)
   google::ShutdownGoogleLogging();
+#elif defined(RAY_USE_SPDLOG)
+  spdlog::default_logger()->flush();
+  spdlog::drop_all();
+  spdlog::shutdown();
+#endif
+}
+
+void WriteFailureMessage(const char *data, int size) {
```
Comment (rkooo567) [inline src/ray/util/logging.cc:393]: Nice :)

File: src/ray/util/logging.cc [hunk 9]
```diff
@@ -196,15 +286,57 @@ void RayLog::StartRayLog(const std::string &app_name, RayLogLevel severity_thres
...
+    spdlog::set_level(static_cast<spdlog::level::level_enum>(severity_threshold_));
+    // Sink all log stuff to default file logger we defined here. We may need
+    // multiple sinks for different files or loglevel.
+    auto file_logger = spdlog::get("ray_log_sink");
+    if (!file_logger) {
+      file_logger =
+          spdlog::rotating_logger_mt("ray_log_sink",
+                                     dir_ends_with_slash + app_name_without_path + "_" +
+                                         std::to_string(pid) + ".log",
+                                     1 << 29, 10);
```
Comment (rkooo567) [inline src/ray/util/logging.cc:314]: Can we make this part configurable?

File: src/ray/util/logging_test.cc (hunk 7 above)
Comment (ashione) [reply src/ray/util/logging_test.cc:137]: I add it only for testing manually because process will abort and exit if signal catched.

File: src/ray/util/logging.cc (hunk 9 above)
Comment (ashione) [reply src/ray/util/logging.cc:314]: I'll extract theses parameters from env vars.

> Can we make this part configurable?

File: src/ray/util/logging.cc (hunk 3 above)
Comment (ashione) [reply src/ray/util/logging.cc:98]: auto-gen by clang-format

**Comment by ashione** [comment]
@rkooo567 Could you go over it again? I found failures are related to python travis tests.

**Comment by ashione** [comment]
@kfstorm @rkooo567 Any other comments about this PR? It's ready to be merged if nothing can be blocked.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
@ashione Can you merge the latest master? It seems like all serve tests are failing, but I think it was same for the master. But I'd like to make sure if that's the case.

**Comment by rkooo567** [comment]
Remove the tag (@author-action-required) once you merge the latest master (and passes all builds)

**Comment by ashione** [comment]
@rkooo567 I have no idea about why //python/ray/tune:test_experiment_analysis failed in TUNE_TESTING? Is it known-issue in master.

**Comment by rkooo567** [comment]
@ashione I think there were some failures on master. This must've been resolved now. Can you try merging the master one more time?

**Comment by ashione** [comment]
> @ashione I think there were some failures on master. This must've been resolved now. Can you try merging the master one more time?

It's done and looks all green.

**Comment by kfstorm** [comment]
Windows CI failure seems unrelated.

**Comment by rkooo567** [comment]
Windows tests seem to have weird test failures that I've never seen. Rerunning the job now...

**Comment by rkooo567** [comment]
@kfstorm The test failure indeed seems unrelated, but I've never seen this error in any CI builds. So let me re-run it just in case!

**Comment by kfstorm** [comment]
@rkooo567 Sure. Thank you.
