### PR TITLE
[GCS] Fix detached actor with empty name

### LINKED ISSUE #9282: It will failed when register two or more detached actors with empty name
### What is the problem?
It will failed when register two or more detached actors with empty name

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
TEST_F(GcsActorManagerTest, TestDetachedActorWithEmptyName) {
  auto job_id = JobID::FromInt(1);

  auto request1 =
      Mocker::GenCreateActorRequest(job_id, 0, /*is_detached=*/true, /*name=*/"");
  Status status = gcs_actor_manager_->RegisterActor(
      request1, [](std::shared_ptr<gcs::GcsActor> actor) {});
  ASSERT_TRUE(status.ok());
  ASSERT_TRUE(gcs_actor_manager_->GetActorIDByName("").IsNil());

  auto request2 =
      Mocker::GenCreateActorRequest(job_id, 0, /*is_detached=*/true, /*name=*/"");
  status = gcs_actor_manager_->RegisterActor(request2,
                                             [](std::shared_ptr<gcs::GcsActor> actor) {});
  ASSERT_TRUE(status.ok());
}
```

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by wumuzi520**
## Why are these changes needed?

It will return `Status::Invalid(xxx)` when register two or more detached actor with empty name, which is not expected.

We should not manage unnamed actors by `named_actors_`.

## Related issue number

Closes #9282

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
Let's just make core worker return Invalid Status when empty name is given (`GetNamedActor` & `CreateActor`). I think the current fix can cause unexpected behavior when the empty name is given.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -390,7 +390,7 @@ Status GcsActorManager::RegisterActor(
   }
 
   auto actor = std::make_shared<GcsActor>(request);
-  if (actor->IsDetached()) {
+  if (actor->IsDetached() && !actor->GetName().empty()) {
```
Comment (raulchen) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:393]: We need to handle named actors and detached actors separately. (This means that we also need to decouple these 2 concepts from the API.) I discussed this @edoakes and @ericl before.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:393]: For now, named actor is detached actor. We also removed `detached=True` flag. https://docs.ray.io/en/latest/advanced.html#detached-actors

When did you discuss with them last time? Maybe there's some miscommunication?

File: src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc [hunk 2]
```diff
@@ -410,6 +410,30 @@ TEST_F(GcsActorManagerTest, TestDetachedActorRestartWhenCreatorDead) {
...
+
+  // Gen `CreateActorRequest` with an empty name.
+  // (name,actor_id) => ("", actor_id_1)
+  auto request1 =
+      Mocker::GenCreateActorRequest(job_id, 0, /*is_detached=*/true, /*name=*/"");
+  Status status = gcs_actor_manager_->RegisterActor(
+      request1, [](std::shared_ptr<gcs::GcsActor> actor) {});
+  // Ensure successful registration.
+  ASSERT_TRUE(status.ok());
+  // Make sure actor who with empty name is not managered by named_actors_.
```
Comment (raulchen) [inline src/ray/gcs/gcs_server/test/gcs_actor_manager_test.cc:424]:
```suggestion
  // Make sure actor who empty name is not treated as a named actor.
```

**Review by raulchen — APPROVED** [review]
