### PR TITLE
[CI] [Minimal install] Check python version in minimal install

### LINKED ISSUE #33401: [core] Make sure minimal tests run in expected python versions
### What happened + What you expected to happen

We have seen cases where minimal test did not run in the targeted python version (propabbly due to conda not having the python version available yet), and tests were broken unexpectedly as conda released new support python version. https://github.com/ray-project/ray/pull/33400

We should prevent this from happening. 

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by cadedaniel**
This PR improves our CI by asserting the expected Python version in our minimal install tests. We use these tests to validate basic Ray functionality for each Python version we support (3.7-3.11). In the past, we saw an issue where the 3.11 tests actually used a different Python version because the conda env we consumed hadn't yet been built for 3.11. Now, the tests will fail if the actual Python version differs from the expected one.

See also https://github.com/ray-project/ray/issues/33401

### CODE REVIEW

File: ci/ci.sh [hunk 1]
```diff
@@ -743,10 +743,13 @@ build() {
 }
 
 run_minimal_test() {
+  EXPECTED_PYTHON_VERSION=$1
   BAZEL_EXPORT_OPTIONS="$(./ci/run/bazel_export_options)"
   # Ignoring shellcheck is necessary because if ${BAZEL_EXPORT_OPTIONS} is wrapped by the double quotation,
   # bazel test cannot recognize the option.
   # shellcheck disable=SC2086
+  bazel test --test_output=streamed --config=ci --test_env=RAY_MINIMAL=1 --test_env=EXPECTED_PYTHON_VERSION=$EXPECTED_PYTHON_VERSION ${BAZEL_EXPORT_OPTIONS} python/ray/tests/test_minimal_install
```
Comment (rickyyx) [inline ci/ci.sh:751]: I was thinking of an "easier" approach where we just asserted the python version in shell here like check the `python --version` output. 

What's the motif for running another pytest and assert in there?

**Review by rickyyx — APPROVED** [review]

File: ci/ci.sh (hunk 1 above)
Comment (cadedaniel) [reply ci/ci.sh:751]: I'm not sure how bazel works, so wanted to verify that bazel picks up right version. If someone confident in bazel behavior says we can trust it, I can delete the test.

Comment (rickyyx) [reply ci/ci.sh:751]: I don't have a strong opinion here - I' m ok with the current approach.

**Comment by jjyao** [comment]
Are you saying when we ask conda to install a particular version of python and that version doesn't exist, conda won't fail loudly but silently install another version?

**Comment by cadedaniel** [comment]
> Are you saying when we ask conda to install a particular version of python and that version doesn't exist, conda won't fail loudly but silently install another version?

@rickyyx 

> We have seen cases where minimal test did not run in the targeted python version (propabbly due to conda not having the python version available yet), and tests were broken unexpectedly as conda released new support python version

https://github.com/ray-project/ray/issues/33401

**Comment by rickyyx** [comment]
> Are you saying when we ask conda to install a particular version of python and that version doesn't exist, conda won't fail loudly but silently install another version?

Maybe not conda not fail explicitly - but our CI failed silently.

**Comment by jjyao** [comment]
> Maybe not conda not fail explicitly - but our CI failed silently.

Should we fix this directly? It seems to me that we still don't know the exact root cause yet?

**Comment by rickyyx** [comment]
> > Maybe not conda not fail explicitly - but our CI failed silently.
> 
> Should we fix this directly? It seems to me that we still don't know the exact root cause yet?

Yeah - i think the root cause was not really known, all we know now is that it wasn't running the expected python version somehow.

**Comment by cadedaniel** [comment]
`train_minimal_install` failed and it looks related. But must be some caching issue, since the codepath should work. I am rerunning the test.

**Comment by cadedaniel** [comment]
cc @jjyao ready for merge

**Comment by jjyao** [comment]
> Yeah - i think the root cause was not really known, all we know now is that it wasn't running the expected python version somehow.

I merged this but can we figure out the root cause as well (not a high priority)
