### PR TITLE
Fix memory leak in Redis by using auto memory management

### LINKED ISSUE #3884: [rllib] Memory usage constantly growing while training IMPALA
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 18.04.1 LTS
- **Ray installed from (source or binary)**: source, with few changes
- **Ray version**: 0.6.2
- **Python version**: Python 3.6.6 :: Anaconda, Inc.
- **Exact command to reproduce**: train IMPALA, described better below

### Describe the problem
Memory usage (resident memory/shared memory) in sampler and trainer is constantly growing during training IMPALA. Very quickly (in few minutes) it fills all the RAM.

Some important remarks in how do I use the rllib:
* I'm training SC2 via [pysc2](https://github.com/deepmind/pysc2) in my custom created env
* My neural net is fairly big, observations as well, and combining environment observations for inference is important for me - it improves performances a lot. Training is done on a small number of workers (currently on my machine 1) and many environments per worker (currently for test - 10).
* SC2 env communication is slow compared to Atari environments, and communication is done via ports - so I implemented making environments in separate remote processes and doing step / reset on them in parallel in the policy evaluator.

With the usage explained, `ray_PolicyEvaluator:sample()` and `ray_ImpalaAgent:train()` processes are just getting bigger and bigger (they take more and more resident/shared memory), as shown in this system manager screenshot:
image

Am I doing something wrong? Is it doing something I don't expect, like keeps old episodes or something, should I change some config?

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

We normally use `RedisModule_AutoMemory` to turn on Redis' built-in automatic memory management, but we forgot to enable it for `RAY.TABLE_APPEND`. Running this command repeatedly will cause Redis to evict all keys and use ever increasing memory.

This PR enables automatic memory management for this command and attempts to restructure the Redis module to make explicit which Redis commands have the feature enabled.

## Related issue number

I believe this should close #3884.

### CODE REVIEW

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 1]
```diff
@@ -675,16 +675,35 @@ std::string DebugString() {
...
+AUTO_MEMORY(ChainTableAdd_RedisCommand);
+AUTO_MEMORY(ChainTableAppend_RedisCommand);
+#endif
+};
 
 extern "C" {
+// Only use commands that have auto memory management.
+// TODO(swang): Ideally, we would make the commands that don't have auto memory
+// management inaccessible instead of just using separate namespaces.
+using namespace auto_memory_redis_commands;
```
Comment (pcmoritz) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: how about we get rid of this, just have the redis_commands namespace that hides the non-auto ones, and put the others into the global namespace? That would be a bit simpler and would make the auto ones more "canonical".

**Comment by pcmoritz** [comment]
This is great, good find :)

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 1 above)
Comment (pcmoritz) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: we could even call the redis_command namespace something else, like internal etc. to make clear it is "hidden"

**Comment by ericl** [comment]
Nice! We should (in a separate PR) somehow get this issue to show up in the stress tests, perhaps just by running one of the test workloads in a low-memory node.

**Review by ericl — APPROVED** [review]

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: Ah good idea, thanks! Now I'm not sure why I started with two separate namespaces :)

**Review by pcmoritz — APPROVED** [review]
