### PR TITLE
[Dashboard] Fix dashboard for daylight savings

### LINKED ISSUE #51310: [Dashboard] Job start and end time are not updated for daylight savings
### What happened + What you expected to happen

The displayed start and end time for jobs is not correct. Logs have correct time. Note our submission ID includes the local datetime as a sufix as well, so can see this doesn't match.

Image

Image

### Versions / Dependencies

Running Ray 2.40.0. Python 2.12.3.

### Reproduction script

1. Spin up ray cluster
2. Submit job
3. Look at the displayed start and end times

### Issue Severity

None

### PR DESCRIPTION
**Pull request by bhmiller**
Did not get traction with the [holistic fix](https://github.com/ray-project/ray/pull/51314) for daylight savings as there was pushback on usage of tzlocal in python. So, splitting out the fix on the UI side which is perhaps less controversial.

On the UI side, `timezone.ts` is showing GMT offsets not reflective of daylight savings time. Updating to dynamically pull the offset from `Intl.DateTimeFormat`. Note not doing any dynamic evaluation so for browser windows open during the switch, it will not update.

## Why are these changes needed?

See #51310

## Related issue number

Closes #51310

## Checks

- [X] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [X] I've run `scripts/format.sh` to lint the changes in this PR.
- [X] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

My tests are just running the typescript code through https://www.typescriptlang.org/play

### CODE REVIEW

File: python/ray/dashboard/client/src/common/timezone.ts [hunk 1]
```diff
@@ -1,794 +1,676 @@
...
   },
   {
-    utc: "GMT-06:00",
     value: "America/Chihuahua",
     group: "America",
     country: "Chihuahua",
   },
   {
-    utc: "GMT-06:00",
-    value: "America/Guadalajara",
```
Comment (bhmiller) [inline python/ray/dashboard/client/src/common/timezone.ts:82]: Did not exist in `Intl.DateTimeFormat`

File: python/ray/dashboard/client/src/common/timezone.ts [hunk 2]
```diff
@@ -1,794 +1,676 @@
...
   },
   {
-    utc: "GMT+07:00",
     value: "Asia/Bangkok",
     group: "Asia",
     country: "Bangkok",
   },
   {
-    utc: "GMT+07:00",
-    value: "Asia/Hanoi",
```
Comment (bhmiller) [inline python/ray/dashboard/client/src/common/timezone.ts:568]: Did not exist in `Intl.DateTimeFormat`

File: python/ray/dashboard/client/src/common/timezone.ts [hunk 3]
```diff
@@ -1,794 +1,691 @@
...
+      const offset = match[0];
+      if (!offset.includes(":")) {
+        return offset.replace(
+          /([+-])(\d{1,2})$/,
+          (_, sign, hours) => `${sign}${hours.padStart(2, "0")}:00`,
+        );
+      }
+      return offset.replace(
+        /([+-])(\d{1,2}):/,
+        (_, sign, hours) => `${sign}${hours.padStart(2, "0")}:`,
```
Comment (alanwguo) [inline python/ray/dashboard/client/src/common/timezone.ts:23]: I don't think we need the to re-format the string to look like longOffset. Let's just use the shortOffset format text in the UI.

**Comment by alanwguo** [comment]
Thanks for the fix!

File: python/ray/dashboard/client/src/common/timezone.ts (hunk 3 above)
Comment (bhmiller) [reply python/ray/dashboard/client/src/common/timezone.ts:23]: Will look into- need to trace through how it's used within `SearchComponent.tsx`

Comment (bhmiller) [reply python/ray/dashboard/client/src/common/timezone.ts]: Confirmed change to shortOffset is benign as it's only used for display. Time zone name is what drives the actual display using dayjs.

**Review by alanwguo — APPROVED** [review]

**Comment by alanwguo** [comment]
Thanks for the contribution, merging!
