### PR TITLE
Disable HTTP proxy for gRPC connections

### LINKED ISSUE #6662: Lost connection with local raylet. Error: IOError: 14: failed to connect to all addresses
I've migrated RLlib training code from Ray 0.7.2 to 0.8.0. While it runs on local_mode=True well, it fails in the very beginning when running with local_mode=False, giving the following (not-very-informative) stack trace:

> 2020-01-01 19:45:33,310	INFO resource_spec.py:216 -- Starting Ray with 34.23 GiB memory available for workers and up to 17.12 GiB for objects. You can adjust these settings with ray.init(memory=<bytes>, object_store_memory=<bytes>).
> 2020-01-01 19:45:33,607	WARNING services.py:1354 -- WARNING: The object store is using /tmp instead of /dev/shm because /dev/shm has only 17179865088 bytes available. This may slow down performance! You may be able to free up space by deleting files in /dev/shm or terminating any running plasma_store_server processes. If you are inside a Docker container, you may need to pass an argument with the flag '--shm-size' to 'docker run'.
> 2020-01-01 19:45:33,812	INFO trainer.py:371 -- Tip: set 'eager': true or the --eager flag to enable TensorFlow eager execution
> 2020-01-01 19:45:33,834	INFO trainer.py:512 -- Current log_level is WARN. For more information, set 'log_level': 'INFO' / 'DEBUG' or use the -v and -vv flags.
> Loading configuration... done.
> Loading configuration... done.
> 2020-01-01 19:45:38,914	WARNING util.py:45 -- Install gputil for GPU system monitoring.
> Loading configuration... done.
> F0101 19:45:39.223114  8665 direct_task_transport.cc:154] Lost connection with local raylet. Error: IOError: 14: failed to connect to all addresses
> *** Check failure stack trace: ***
>     @     0x7f1d2b42cecd  google::LogMessage::Fail()
>     @     0x7f1d2b42e33c  google::LogMessage::SendToLog()
>     @     0x7f1d2b42cba9  google::LogMessage::Flush()
>     @     0x7f1d2b42cdc1  google::LogMessage::~LogMessage()
>     @     0x7f1d2b201619  ray::RayLog::~RayLog()
>     @     0x7f1d2b1225f9  ray::CoreWorkerDirectTaskSubmitter::RetryLeaseRequest()
>     @     0x7f1d2b124d93  _ZNSt17_Function_handlerIFvRKN3ray6StatusERKNS0_3rpc16WorkerLeaseReplyEEZNS0_29CoreWorkerDirectTaskSubmitter24RequestNewWorkerIfNeededERKSt4pairIiSt6vectorINS0_8ObjectIDESaISC_EEEPKNS4_7AddressEEUlS3_S7_E_E9_M_invokeERKSt9_Any_dataS3_S7_
>     @     0x7f1d2b15c16f  ray::rpc::ClientCallImpl<>::OnReplyReceived()
>     @     0x7f1d2b0fef03  _ZN5boost4asio6detail18completion_handlerIZN3ray3rpc17ClientCallManager29PollEventsFromCompletionQueueEiEUlvE_E11do_completeEPvPNS1_19scheduler_operationERKNS_6system10error_codeEm
>     @     0x7f1d2b0fd8d5  boost::asio::detail::scheduler::run()
>     @     0x7f1d2b1019d3  ray::CoreWorker::RunIOService()
>     @     0x7f1d2ac849e0  (unknown)
>     @     0x7f1d2cee06db  start_thread
>     @     0x7f1d2d21988f  clone
> Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
> Quitting (on error).
> Error: tcpip::Socket::recvAndCheck @ recv: peer shutdown
> Quitting (on error).

Is anyone familiar with this type of exception? It seems to be a low level exception, and I can't figure out a way to debug it.

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Local gRPC connections will fail if the http_proxy or https_proxy env vars are set. Since we never supported HTTP proxying in previous versions of Ray, the simplest fix is to globally disable proxy support for all Ray gRPC connections.

In the future we can consider making this configurable, or disabling proxying for only local connections.

Closes https://github.com/ray-project/ray/issues/6662

### CODE REVIEW

File: src/ray/rpc/grpc_client.h [hunk 1]
```diff
@@ -38,8 +38,13 @@ class GrpcClient {
...
       : client_call_manager_(call_manager) {
-    std::shared_ptr<grpc::Channel> channel = grpc::CreateChannel(
-        address + ":" + std::to_string(port), grpc::InsecureChannelCredentials());
+    grpc::ChannelArguments argument;
+    // Disable http proxy since it disrupts local connections. TODO(ekl) we should make
+    // this configurable, or selectively set it for known local connections only.
+    argument.SetInt(GRPC_ARG_ENABLE_HTTP_PROXY, 0);
+    std::shared_ptr<grpc::Channel> channel =
+        grpc::CreateCustomChannel(address + ":" + std::to_string(port),
+                                  grpc::InsecureChannelCredentials(), argument);
```
Comment (raulchen) [inline src/ray/rpc/grpc_client.h]: Need do the same thing for the other constructor as well

**Review by raulchen — APPROVED** [review]

**Review by zhijunfu — APPROVED** [review]
