### PR TITLE
Fix Java CI crash caused by incorrect destruction order in core worker

### LINKED ISSUE #10693: [Java] A fatal error has been detected by the Java Runtime Environment
### What is the problem?
These is a jvm crash occurs casually in travis ci. 
```
---------------  S U M M A R Y ------------
Command Line: -Dray.raylet.config.num_workers_per_process_java=10 -Dray.job.num-java-workers-per-process=10 org.testng.TestNG -d /tmp/ray_java_test_output /home/travis/build/ray-project/ray/java/testng.xml
Host: Intel(R) Xeon(R) CPU, 2 cores, 7G, Ubuntu 16.04.6 LTS
Time: Tue Sep  8 23:09:18 2020 UTC elapsed time: 679 seconds (0d 0h 11m 19s)
---------------  T H R E A D  ---------------
Current thread is native thread
Stack: [0x00007f88c99fa000,0x00007f88ca1fa000],  sp=0x00007f88ca1f8b40,  free space=8186k
Native frames: (J=compiled Java code, A=aot compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libcore_worker_library_java.so+0x6c7697]  redisBufferWrite+0x117
C  [libcore_worker_library_java.so+0x6c381c]  redisAsyncWrite+0x1c
C  [libcore_worker_library_java.so+0x58548e]  ray::gcs::RedisAsyncContext::RedisAsyncHandleWrite()+0x2e
C  [libcore_worker_library_java.so+0x587a6d]  RedisAsioClient::handle_io(boost::system::error_code, bool)+0x19d
C  [libcore_worker_library_java.so+0x58730a]  boost::asio::detail::reactive_null_buffers_op<boost::_bi::bind_t<void, boost::_mfi::mf2<void, RedisAsioClient, boost::system::error_code, bool>, boost::_bi::list3<boost::_bi::value<RedisAsioClient*>, boost::arg<1> (*)(), boost::_bi::value<bool> > >, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long)+0x28a
C  [libcore_worker_library_java.so+0x843e09]  boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&)+0x349
C  [libcore_worker_library_java.so+0x844bc1]  boost::asio::detail::scheduler::run(boost::system::error_code&)+0xe1
C  [libcore_worker_library_java.so+0x84683b]  boost::asio::io_context::run()+0x3b
C  [libcore_worker_library_java.so+0x346330]  ray::CoreWorker::RunIOService()+0x50
siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0xfffffffffffffffe
```
Seems a bug related redis usage. See more on https://travis-ci.com/github/ray-project/ray/jobs/382539075#L1253

### Reproduction (REQUIRED)
Rerun travis java ci repeatedly should reproduce the issue.
- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

In the existing code, `gcs_client_->Disconnect()` is called right after `io_service_.stop` is called, but the IO thread hasn't been fully stopped yet.

https://github.com/ray-project/ray/blob/e72838c03d87c8eb10f7cb8df8804496b14121ab/src/ray/core_worker/core_worker.cc#L534-L540

In `ServiceBasedGcsClient::Disconnect()`, `gcs_pub_sub_` and `redis_gcs_client_` are released, which means the underlying `RedisAsyncContext` instances are destructed.

https://github.com/ray-project/ray/blob/e72838c03d87c8eb10f7cb8df8804496b14121ab/src/ray/gcs/gcs_client/service_based_gcs_client.cc#L90-L98

`redisAsyncFree` is called in `~RedisAsyncContext()`.

https://github.com/ray-project/ray/blob/e72838c03d87c8eb10f7cb8df8804496b14121ab/src/ray/gcs/redis_async_context.cc#L31-L36

In the implementation of `redisAsyncFree`, the cleanup function of the event lib is invoked (https://github.com/redis/hiredis/blob/5003906d633dd4b96a3a60d1f63188ffaca3140e/async.c#L344). But we do nothing in the hooked cleanup method.

https://github.com/ray-project/ray/blob/e72838c03d87c8eb10f7cb8df8804496b14121ab/src/ray/gcs/asio.cc#L111

That is to say, asio is not detected from the `redisAsyncContext` instance.

Before the IO thread stops, and if the `redisAsyncContext` instance is freed by `redisAsyncFree`, the IO thread may continue calling `RedisAsioClient::handle_io`. Furthermore, because `RedisAsioClient` instances are declared after `RedisContext`, the `RedisAsioClient` instances are destructed before `RedisAsyncContext` instances (included by `RedisContext`).

https://github.com/ray-project/ray/blob/e72838c03d87c8eb10f7cb8df8804496b14121ab/src/ray/gcs/redis_client.h#L96-L103

In short, the memory of `RedisAsioClient` is freed before `redisAsyncFree` is called, and the IO thread may continue trying to access `RedisAsioClient` via `RedisAsioClient::handle_io`, which leads to crash.

This PR applies a quick fix by moving the position of `gcs_client_->Disconnect()` to make sure the IO thread has been stopped before invoking it. The fix has been verified by #10674, which adds a while loop to run Java test indefinitely until it fails. [Travis CI log](https://travis-ci.com/github/ray-project/ray/builds/183654136) shows that the Java test ran successfully for 9 times before the job was killed by Travis due to timeout.

An once-for-all fix would be:

* To make sure asio is detached from a `redisAsyncContext` instance when the instance is about to be freed.
* Make sure the memory of `RedisAsioClient` is always valid while accessing it in the IO thread.

We've done it in Ant Financtial's internal repository, but it requires a lot of code changes. Especially that `RedisAsioClient::cleanup()` needs to be invoked in the IO thread, which seems impossible to me if we don't refactor upper-level classes like `RedisClient`.

## Related issue number

Closes #10693

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -532,12 +532,8 @@ void CoreWorker::Shutdown() {
 }
 
 void CoreWorker::Disconnect() {
-  io_service_.stop();
```
Comment (raulchen) [inline src/ray/core_worker/core_worker.cc:535]: If we don't stop the io_service here, it will be stopped in the destructor, right?

**Review by raulchen — APPROVED** [review]
Thanks for fixing this! this issue has been around for quite a while.

**Review by ffbin — APPROVED** [review]
