### PR TITLE
[gcs] Fix internal kv as the bottleneck when worker starts

### LINKED ISSUE #20602: [release] `many_actors` failed
I actually run it twice and both failed. 
https://buildkite.com/ray-project/periodic-ci/builds/1716#0873e354-d1c4-462f-87be-63307f0cb870

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

Before the commit (https://github.com/ray-project/ray/commit/e54d3117a40c20ca5441d38ffc72b908bc1b0609) all traffics go to redis which is a dedicated service.

After moving to gcs, internal kv are competing with gcs traffic which make it a bottleneck sometimes.

Before this PR, `many_actor` tests are failing, the reason is that when a lot of actors starts, gcs is really heavy loads, and then worker starts timeout because it failed to get internal kv requests executed in short time.
When worker failed, it'll starts a new worker even the original one is pending, and in the end there will be a lot workers.

There are several things here need to fix and this is the quick fix for this issues which also convert it back to the status when we are using redis.

In this PR: backpressure for kv is removed and gcs grpc server thread number increased to 8

## Related issue number

Closes #20602
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
k8s issue is fixed here https://github.com/ray-project/ray/commit/68ec652be78ee2f921eb5635d6ff074dfc8d44bc

**Review by rkooo567 — APPROVED** [review]
This looks good. Btw, just removing `InternalKVGcsService ` backpressure limit doesn't work?

**Comment by rkooo567** [comment]
Also please make sure to run nightly tests multiple times! (I remember we had issues increasing rpc threads caused regression?)

**Comment by ericl** [comment]
I'd like to understand why back pressure causes this failure in the first place. Is it the client doesn't retry, or handles failures incorrectly? It seems odd a cluster would get hung because of this.

**Comment by iycheng** [comment]
>  This looks good. Btw, just removing InternalKVGcsService backpressure limit doesn't work?

@rkooo567  it'll also work. I increase gcs thread here since just changing the thread number also works. I think since both works, so it should be better to have two? Open to any opinion here.

> I'd like to understand why back pressure causes this failure in the first place. Is it the client doesn't retry, or handles failures incorrectly? It seems odd a cluster would get hung because of this.

@ericl 
1.  We have backpressure for internal kv (100) and all worker hangs there first
2. This leads to some worker hangs. I'm not sure how things are working in grpc for backpressure, but it looks like it makes some workers hang for a long time. (from this part, grpc backpressure looks really suspicious, we should be careful about this. I think if it's working as expected, everything should be the same as -1, or even better since gcs is not overloaded).
3. raylet notice worker failure and starts new workers and this even add more pressure to gcs (raylet doesn't kill worker)
4. And gcs keeps receiving requests (here is the log for just one actor creation https://gist.github.com/iycheng/1d9d1a91ee2b422c414ff3c502700a88) since worker always failed. and this adds pressure to gcs.
5. in the end, everything hangs. it's like an error accumulates and eventually, it hangs forever.

**Comment by ericl** [comment]
I see. I think then we should test with a very low back pressure limit,
such as 1. The system should still run even if very slowly. Hangs seem like
a bug--- backpressure causing hangs would be counterproductive.

**Comment by iycheng** [comment]
There are a couple of things not documented well on backpressure (or maybe I just failed to find it):

1. how is query processed when backpressure hit: FIFO/LIFO or not defined
2. when backpressure hit and the new request comes, will the request reach to the server? If so, will the server's memory increase forever? If not, how is it handled on the client-side, will it retry and what's the retry policy.
3. what if the request got canceled or the client just died.

Before we have this, it's a little bit hard to interpret what's happening when backpressure hits.

**Comment by rkooo567** [comment]
+1 on refining/fixing/documenting backpressure behaviors. Maybe we should solve this before turning on grpc based pubsub

regarding backpressure + thread nums, my opinion is it’s better having minimal changes (only backpressure), but it is up to you. I am not quite confident I understand this grpc threads num history lol

File: src/ray/common/ray_config_def.h [hunk 1]
```diff
@@ -248,7 +248,7 @@ RAY_CONFIG(int32_t, maximum_profile_table_rows_count, 10 * 1000)
 RAY_CONFIG(uint32_t, object_store_get_max_ids_to_print_in_warning, 20)
 
 /// Number of threads used by rpc server in gcs server.
-RAY_CONFIG(uint32_t, gcs_server_rpc_server_thread_num, 1)
+RAY_CONFIG(uint32_t, gcs_server_rpc_server_thread_num, 8)
```
Comment (raulchen) [inline src/ray/common/ray_config_def.h:251]: `gcs_server_rpc_server_thread_num` is the number of threads that poll incoming requests from gRPC's completion queue. But since GCS is single-threaded, increasing this thread number won't help. IIRC, the object manager is the only place that need multiple RPC threads.

**Review by raulchen — DISMISSED** [review]

**Comment by rkooo567** [comment]
@raulchen I am on the same page as reducing it to 1, but this can still be helpful if our event loop processing is faster than completion queue dispatch right? Or you are saying it is fundamentally impossible that main event loop is faster than processing # of grpc requests?

**Comment by raulchen** [comment]
This is how gRPC back-pressure works:
1) Every time when we call this [CreateCall](https://github.com/ray-project/ray/blob/master/src/ray/rpc/server_call.h#L340), we tell gRPC that it can accept a new request of the specific type. And we can call this multiple times, so gRPC will accept at most this number requests of this type.
2) Every time when gRPC accepts a new request [here](https://github.com/ray-project/ray/blob/master/src/ray/rpc/grpc_server.cc#L162), it consumes one "slot" for this request type.  And we need to call `CreateCall` again to replenish the slots. 
3) So back-pressure is implemented by controlling when to call "CreatCall" again. Here is the original PR: https://github.com/ray-project/ray/pull/17427/files

**Comment by raulchen** [comment]
@rkooo567 It's very unlikely that the event loop can run faster than the RPC thread. The RPC thread simply polls a new request from the CQ and then post it to the event loop. While the event loop has more complicated logic about how to handle the request.

**Comment by rkooo567** [comment]
I think I agree with you. But I remember @iycheng mentioned increasing this threads solved some issues.

Not that I am thinking of it, it could be the side effect of increasing num_threads. We have backpressure limit 100 by default on all RPC calls per grpc thread IIRC, and maybe increasing num_threads have the same impact as increasing the backpressure limit (so, 8 grpc threads means the default backpressure limit became from 100 -> 800)

**Comment by raulchen** [comment]
When the back-pressure is hit, the server will stop accepting new requests. And the client cannot send new requests to the server, and it will hang there forever until the server starts accepting new requests again. 
@iycheng so, to answer your questions, the server memory won't increase (as the main motivation of back-pressure was to avoid OOM). And I guess the the order of the back-pressured requests should be undefined, because they haven't reached the server side yet. 
@lixin-wei please correct me if I am wrong.

**Comment by raulchen** [comment]
I think here the main problem is, when the GCS is super busy, many pending KV requests are delayed. So workers hang there due to the back-pressure.  
@iycheng I'm wondering which timeout you referred to. Is it the worker start-up timeout in the worker pool? I guess, if you increase that timeout, the process will eventually proceed and finish.

**Comment by rkooo567** [comment]
I can answer some of them as yi is sleeping now. We have by default 30s timeout until from worker start -> register RPC is received (so this includes worker startup time + python initialization + some cpp initialization). It took about 4 minutes for 10K actor scheduling.

We have some usage such as finding session name, finding Ray versions, and things like that I think. Maybe Yi can have more precise answer here.

**Comment by raulchen** [comment]
@rkooo567 thanks. 
To solve this issue, I think it makes sense to increase the back-pressure limit for KV, but better not simply disable it. 
But I still don't understand why increasing thread number could make any difference. @iycheng could you double check this?

**Comment by raulchen** [comment]
Also, please let me know which KV caused this issue. Another possible optimization is to delay this until the worker is registered to the Raylet.

**Comment by rkooo567** [comment]
> But I still don't understand why increasing thread number could make any difference

I have fairly high confidence increasing grpc threads number has the same impact as increasing backpressure limit. 1->8 threads should be equivalent to 100->800 limits https://github.com/ray-project/ray/blob/720bca8a1c9d221022b438882760e33f0e939443/src/ray/rpc/grpc_server.cc#L117

> Also, please let me know which KV caused this issue. Another possible optimization is to delay this until the worker is registered to the Raylet.

I think this is probably not enough. If it takes minutes to get reply from GCS, many components can be broken or being unstable. For example, ray.init was hanging when we observe this issue (because it uses internal KV in some part of initialization)

**Comment by mwtian** [comment]
> +1 on refining/fixing/documenting backpressure behaviors. Maybe we should solve this before turning on grpc based pubsub

GRPC pubsub on GCS does not limit max calls. GRPC pubsub uses long polling so max calls is ~ total # of workers. and anything lower will not work.

File: src/ray/common/ray_config_def.h (hunk 1 above)
Comment (iycheng) [reply src/ray/common/ray_config_def.h]: I think it also covers request deserialization which sometimes is the bottleneck when request is big.
I remember I'm told that in Ant the number is not 1 either (hopefully my memory is not wrong 😀).

**Comment by ericl** [comment]
> Previously with direct Redis usage, we didn't observe this behavior.

So it sounds to me this is a confluence of two things: (1) moving the KV operations from redis to the asio loop (previously, they did not contend with other asio operations), and (2) unpredictable queueing delay (random queueing order?) introduced by the backpressure flag.

Is this right? If so, it seems to address (1) we should move the KV service off the asio event loop (there's no need for it to serialize all operations, a simple lock can do), and for (2) disable backpressure for KV (short term fix).

So this PR LGTM as the short-term fix.

> back-pressure limit for KV, but better not simply disable it.

IIUC, any kind of limit can cause these requests to get arbitrarily delayed currently, so it might be dangerous. I think if we move KV ops off asio, there is no need for backpressure--- requests simply get processed directly by the RPC threads and if all threads are busy, requests are blocked.

**Review by ericl — APPROVED** [review]

**Comment by iycheng** [comment]
@raulchen I think here the ordering is important otherwise it'll prevent workers from starting up. The worker needs to send several requests to gcs to fetch kv info. It'll only be up until all requests are fetched.
Out of order execution for the requests will make things worse and also it will delay requests getting executed in the event loop as well. Btw how does cancelation work here? I don't think backpressure should work without the timeout for clients for this case.

I remember polling threads covers deserialization, which sometimes makes it a bottleneck especially when gcs keeps receiving big requests. 

But for this case, I agree with @rkooo567  it more looks like the buffer got increased.

I'll still keep it -1 since it's internal kv which is not that heavy and we'll move it to a separate pool later.

**Comment by raulchen** [comment]
@rkooo567 Got it. The back-pressure limit is actually counted per thread. So increasing the thread number will also increase the limit.

**Comment by raulchen** [comment]
@ericl I agree that we should move KV ops off the main loop. But without any back-pressure, problem can still happen in edge cases. That's say something wrong makes Redis latency longer, and workers keeps sending new KV requests. In this case, all the requests will be pending on the GCS side and cause memory usage bump. That being said, this is not a very big deal for now, as the KV requests are usually not very large.

**Comment by raulchen** [comment]
@iycheng I mean, he requests from the same GCS client are still correct. But the order of requests from different clients is not predictable, which I think doesn't matter.

**Comment by raulchen** [comment]
I think the key problem here is that the back-pressure limit is too strict for large clusters. Maybe we should use some adaptive approach to config the limit? cc @lixin-wei

**Comment by ericl** [comment]
I agree we need backpressure in the future (and it should be fine once we
have kv off the main loop).

I think what we're seeing is disabling backpressure is effectively
increasing the priority of kv requests, reducing their latency. That's
preventing the timeouts from happening.
