### PR TITLE
Limit number of concurrent workers started by hardware concurrency.

### LINKED ISSUE #2751: test/actor_test.py::ActorsWithGPUs::testActorMultipleGPUsFromMultipleTasks failing
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macosx
- **Ray installed from (source or binary)**: source
- **Ray version**: upstream/master , atumanov/raylet-scheduling-simple
- **Python version**: py2.7.12
- **Exact command to reproduce**:
`RAY_USE_XRAY=1 python -m pytest  -v  -s test/actor_test.py::ActorsWithGPUs`

### Describe the problem

test/actor_test.py::ActorsWithGPUs::testActorMultipleGPUsFromMultipleTasks may intermittently fail when run on either macosx or linux. The first problematic output captured from the failing test so far:
```
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
sh: fork: Resource temporarily unavailable
```

### PR DESCRIPTION
**Pull request by robertnishihara**
This fixes https://github.com/ray-project/ray/issues/2751.

This is related to some discussion in https://github.com/ray-project/ray/pull/2168.

### CODE REVIEW

**Comment by robertnishihara** [comment]
Just chatted with @pcmoritz and there is some concern about `std::thread::hardware_concurrency` being unreliable. One alternative would be to pass the concurrency in from the command line (and compute it in Python with `psutil.cpu_count()`).

File: src/ray/raylet/worker_pool.cc [hunk 1]
```diff
@@ -41,9 +44,11 @@ namespace raylet {
 /// A constructor that initializes a worker pool with
 /// (num_worker_processes * num_workers_per_process) workers for each language.
 WorkerPool::WorkerPool(
-    int num_worker_processes, int num_workers_per_process, int num_cpus,
+    int num_worker_processes, int num_workers_per_process,
+    int maximum_startup_concurrency,
     const std::unordered_map<Language, std::vector<std::string>> &worker_commands)
-    : num_workers_per_process_(num_workers_per_process), num_cpus_(num_cpus) {
+    : num_workers_per_process_(num_workers_per_process),
+      maximum_startup_concurrency_(maximum_startup_concurrency) {
```
Comment (raulchen) [inline src/ray/raylet/worker_pool.cc]: we should set `maximum_startup_concurrency_` to at least 1, in case user pass 0 or a negative number by accident.

File: java/runtime-native/src/main/java/org/ray/runner/RunManager.java [hunk 2]
```diff
@@ -623,9 +623,11 @@ private void startRaylet(String storeName, AddressInfo info, int numWorkers,
 
     String resourceArgument = ResourceUtil.getResourcesStringFromMap(staticResources);
 
+    int maximumStartupConcurrency = staticResources.get("CPU").intValue();
+
     // The second-last arugment is the worker command for Python, not needed for Java.
     String[] cmds = new String[]{filePath, rayletSocketName, storeName, ip, gcsIp,
-        gcsPort, "" + numWorkers, resourceArgument,
+        gcsPort, "" + numWorkers, "" + maximumStartupConcurrency, resourceArgument,
```
Comment (eric-jj) [inline java/runtime-native/src/main/java/org/ray/runner/RunManager.java]: String.valueOf(maximumStartupConcurrency);

File: java/runtime-native/src/main/java/org/ray/runner/RunManager.java [hunk 3]
```diff
@@ -623,9 +623,11 @@ private void startRaylet(String storeName, AddressInfo info, int numWorkers,
 
     String resourceArgument = ResourceUtil.getResourcesStringFromMap(staticResources);
 
+    int maximumStartupConcurrency = staticResources.get("CPU").intValue();
```
Comment (raulchen) [inline java/runtime-native/src/main/java/org/ray/runner/RunManager.java]: Similar to `psutil.cpu_count()` in Python, Java has `Runtime.getRuntime().availableProcessors()`

File: java/runtime-native/src/main/java/org/ray/runner/RunManager.java (hunk 2 above)
Comment (robertnishihara) [reply java/runtime-native/src/main/java/org/ray/runner/RunManager.java]: Thanks! I'll also change it for `"" + numWorkers` then.

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (robertnishihara) [reply src/ray/raylet/worker_pool.cc]: Hm, I think 0 should be allowed as a way to specify that no workers should be created.

File: java/runtime-native/src/main/java/org/ray/runner/RunManager.java (hunk 3 above)
Comment (robertnishihara) [reply java/runtime-native/src/main/java/org/ray/runner/RunManager.java]: I added that in to match the Python side.

File: java/runtime-native/src/main/java/org/ray/runner/RunManager.java (hunk 2 above)
Comment (robertnishihara) [reply java/runtime-native/src/main/java/org/ray/runner/RunManager.java]: Fixed.

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (raulchen) [reply src/ray/raylet/worker_pool.cc]: If `maximum_startup_concurrency_` is 0, no workers will ever be created. I think that's useless? 

Did you mean the number of initial workers to create when starting? that is another parameter, `num_worker_processes`.

Comment (robertnishihara) [reply src/ray/raylet/worker_pool.cc]: So, it's not necessarily useless, because you can still submit tasks and get objects. It just means that that node won't execute any tasks.

However, I think the appropriate way to specify that no tasks should be execute on a node is to set the resources to be 0 instead of setting the `maximum_startup_concurrency_` to 0. E.g., if we have 1 CPU resource and `maximum_startup_concurrency_` then that could lead to hanging.

Maybe we should simply do `RAY_CHECK(maximum_startup_concurrency_ > 0)`.

Comment (raulchen) [reply src/ray/raylet/worker_pool.cc]: 1) I'm afraid I still don't understand what the benefit is to add a no-op node to the cluster. One thing I can think of is that it allows users to add their laptops to a cluster and run drivers from the laptops without logging onto a prod machine. But this problem should be solved by job submission API. Am I missing something?

2) I'm not sure if `RAY_CHECK` is too strong here. An alternative way is setting the value to 1 and printing a warning. But either way is fine.

Comment (atumanov) [reply src/ray/raylet/worker_pool.cc]: We should keep the ability to create a ray cluster node that's guaranteed to accept no work. I commonly use this for testing local vs. remote task execution throughput and object store throughput.

Comment (raulchen) [reply src/ray/raylet/worker_pool.cc]: @atumanov thanks, that's a good point.

Comment (robertnishihara) [reply src/ray/raylet/worker_pool.cc]: @atumanov @raulchen I think the "correct" way to specify that no tasks should run at a node is to specify 0 resources as opposed to limiting the worker startup concurrency.

Especially since a 0-resource node can still execute tasks that require 0 resources, so we may need to start workers even on nodes with 0 resources.

@raulchen about the `RAY_CHECK`, changing the value sounds like it could potentially hide errors or cause confusion. If `0` is not a valid input, then I'd prefer to fail immediately (of course it should not be possible to trigger the fatal code path from the Python/Java side).

**Comment by robertnishihara** [comment]
@raulchen I'm happy with the current state of the PR, so please let me know if there are additional changes that should be made.

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (atumanov) [reply src/ray/raylet/worker_pool.cc]: @robertnishihara , yeah that's right. I think of ray nodes in terms of their multi-dimensional resource capacity. I think that the only units of compute that may require zero resources are actor tasks, in which case the actor creation task must've required resources, which would not have been placed on the zero-cpu node. It's a good sanity check and probably a good time to ensure that we don't have (don't support?) cases where the sum of actor creation resreq and actor task resreq is ever zero. That just wouldn't make sense to me.

FWIW, thus far, whenever I wanted a "no-op" ray node (one that accepts no work), I  specify `--num-cpus 0 --num-workers 0`.

**Review by atumanov — COMMENTED** [review]
when the number of workers is specified on the command line or through the `ray.init` API, the maximum startup cap won't be honored due to the semantics of `num_workers`. We treat the explicit specification of num_workers as the request from the user to start all of them on raylet startup (`force_start` boolean flag). The suggestion is to (a) deprecate num_workers or (b) break this guarantee.

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (raulchen) [reply src/ray/raylet/worker_pool.cc]: Agreed that specifying 0 resource is the proper way for no-op nodes.

@robertnishihara regarding the `RAY_CHECK`, your reasoning makes sense to me. Previously I was concerned that users might accidentally specify 0 cpu and have no idea what went wrong (new users may not know where to find the log file). Now since we ensure the argument is at least 1 in Python & Java. This won't happen.

**Review by raulchen — APPROVED** [review]
I think this PR looks good.

**Comment by robertnishihara** [comment]
Thanks @raulchen, want to go ahead and merge it? Test failures seem unrelated to me.

**Comment by raulchen** [comment]
@robertnishihara I was checking the test failure as well. It should be unrelated, but I just re-ran the failed one to make sure. I'll merge this a bit later when it finishes.

**Comment by atumanov** [comment]
OK, I don't think I made myself clear. This PR does NOT fix #2751 when `num_workers` is specified. See my comment above for details. We may agree to merge this in its current form with the proviso that `num_workers` will be deprecated in the near future (#2759). But could we at least leave a comment to that effect in `WorkerPool::StartWorkerProcess` (where the `force_start` boolean flag overrides the effect of `maximum_startup_concurrency_ ` ) ?
https://github.com/ray-project/ray/pull/2753/files#diff-64c50c0cc29e8f9f96ebf5df2b668f1cR108

**Comment by robertnishihara** [comment]
@atumanov sounds good, I'll push a change.

**Comment by robertnishihara** [comment]
@atumanov should be fixed now.

**Review by atumanov — APPROVED** [review]
LGTM. The correctness is pending #2762 or #2759

**Comment by raulchen** [comment]
The re-triggered CI job has succeeded. And latest 2 commits only touches comments. It should be safe for merge now.
