### PR TITLE
[Core] Fix negative ALIVE actors metric

### LINKED ISSUE #46232: [Core] `NodeId` and `NodeIp` tags don't match the expected instance
### What happened + What you expected to happen

The `NodeId`, `NodeIp`, `instance`, and `InstanceId` tags on the `ray_actors` metric all seem to be set to the head node's ID and IP. There's no way to tell what actors ran on what nodes using metrics.

### Versions / Dependencies

Ray on the latest `master`.

### Reproduction script

See any running service.

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?

Currently GCS emits the total number of ALIVE actors and each core worker emits `-1` if its actor is ALIVE but not idle. The sum is total number of idle actors (we call it state ALIVE while it really means IDLE). Since GCS and core worker emits metrics at different time, the sum might be negative.

image

This PR fixes this by letting gcs and core worker emits different actor states:

- GCS will emit DEPENDENCIES_UNREADY, PENDING_CREATION, ALIVE, RESTARTING and DEAD
- If the actor is ALIVE, core worker will emit IDLE, RUNNING_TASK, RUNNING_IN_RAY_GET, RUNNING_IN_RAY_WAIT. Those can be seen as sub-states of ALIVE.

Metrics dashboard is updated accordingly.

With this change, state ALIVE actually means alive instead of the old (wrong) idle semantic and we have a new state IDLE to indicate whether the actor is idle or not.

## Related issue number
Closes #46232

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/core_worker.h [hunk 1]
```diff
@@ -140,14 +140,17 @@ class TaskCounter {
...
       } else if (running_in_get_counter_.Total() > 0) {
         in_get = 1.0;
       } else if (num_tasks_running_ > 0) {
         running = 1.0;
+      } else {
+        alive = 1.0;
       }
-      ray::stats::STATS_actors.Record(-(running + in_get + in_wait),
+      ray::stats::STATS_actors.Record(alive,
                                       {{"State", "ALIVE"},
```
Comment (rickyyx) [inline src/ray/core_worker/core_worker.h:154]: Should this actually be "IDLE" ?

**Review by rickyyx — APPROVED** [review]
Is this easy to test and validate the fix works?

File: src/ray/core_worker/core_worker.h (hunk 1 above)
Comment (jjyao) [reply src/ray/core_worker/core_worker.h:154]: It should but it's a backward incompatible change I think.

**Comment by alexr-anyscale** [comment]
Not a huge priority for the customer but just checking for any update on this one

**Comment by alexr-anyscale** [comment]
@jjyao any update on this one? I see it was blocked by some pre-merge tests.

File: src/ray/stats/metric_defs.cc [hunk 2]
```diff
@@ -59,7 +59,8 @@ DEFINE_stats(
 DEFINE_stats(actors,
              "Current number of actors currently in a particular state.",
```
Comment (rickyyx) [inline src/ray/stats/metric_defs.cc:60]: In the long run, I wonder if it makes more sense to separate this metric cleanly rather than relying on the executor as a label. It seems tricky for users to know what the implications of source is.

**Review by rickyyx — APPROVED** [review]
Do we need to call it out somewhere in a doc or change log such that this definition now changes?

File: src/ray/stats/metric_defs.cc (hunk 2 above)
Comment (jjyao) [reply src/ray/stats/metric_defs.cc:60]: I feel if we document it correctly it should be fine? Although currently `source` is not documented at all.

File: dashboard/modules/metrics/dashboards/default_dashboard_panels.py [hunk 3]
```diff
@@ -71,7 +71,19 @@ def max_plus_pending(max_resource, pending_resource):
         unit="actors",
         targets=[
             Target(
-                expr="sum(ray_actors{{{global_filters}}}) by (State)",
+                expr='sum(ray_actors{{Source="gcs",{global_filters}}}) by (State)',
+                legend="{{State}}",
+            )
+        ],
+    ),
+    Panel(
```
Comment (alanwguo) [inline dashboard/modules/metrics/dashboards/default_dashboard_panels.py:79]: can we just replace the Scheduler Actor State graph completely? Or is it still useful?

Comment (jjyao) [reply dashboard/modules/metrics/dashboards/default_dashboard_panels.py:79]: yes, I think it's still useful.

**Review by alanwguo — APPROVED** [review]
