### PR TITLE
[Placement Group] Fix infeasible placement group not scheduled after node is added

### LINKED ISSUE #20968: [Bug] Infeasible placement group is not scheduled after the cluster is auto-scaled
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core, Ray Clusters

### What happened + What you expected to happen

1. When creating a single placement group (STRICT_PACK) for a node on EC2, it never becomes ready, even though the node comes up (seen in ray monitor). When looking at the placement_group_table, it says INFEASIBLE. Once the node is up, it is possible to remove and re-add the placement group, and it then becomes ready. This only happens with one node/placement_group. With two or more nodes, it works. However, placement_group_table says 'scheduling_attempt': 3 once they are up, so something seems a bit fishy.

3. I haven't been able to get that much out of logs. It just keeps saying:
`2021-12-08 02:08:11,690 WARNING resource_demand_scheduler.py:731 -- The autoscaler could not find a node type to satisfy the request: [{'bundle_group_f603e2de7cd8965a3e9e30f6357dbb7b': 0.001}]. If this request is related to placement groups the resource request will resolve itself, otherwise please specify a node type with the necessary resource https://docs.ray.io/en/master/cluster/autoscaling.html#multiple-node-type-autoscaling.` even though the instance is up.

### Versions / Dependencies

ray 1.9.0 and 1.8.0 have given the same results
python both 3.8.10 and 3.7.7 have given the same results

### Reproduction script
```
from ray.util.placement_group import placement_group, placement_group_table, remove_placement_group
import ray

ray.init('auto')

bundle = {"CPU": 4, "GPU": 1}
pg = placement_group(
    [bundle],
    name=f'worker_1',
    strategy="STRICT_PACK"
)
```

### Anything else

This happens every time we try so far. Did a minimal yaml for reproduction:
```
cluster_name: ray-test
max_workers: 2

docker:
    image: "rayproject/ray:1.9.0"
    container_name: "ray_docker"
    pull_before_run: True

provider:
    type: aws
    region: eu-central-1
    availability_zone: eu-central-1a,eu-central-1b
    use_internal_ips: True
    cache_stopped_nodes: False # If not present, the default is True.


auth:
    ssh_user: ubuntu
    ssh_private_key: ~/.ssh/<key>

available_node_types:
    gpu_ondemand:
        node_config:
            InstanceType: g4dn.xlarge
            ImageId: ami-0bdfa178b5c1fb9e6 # Deep Learning AMI (Ubuntu 18.04)
            KeyName: <key-name>
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 150
            SubnetIds:
                - <subnet1>
                - <subnet2>
            IamInstanceProfile:
                Arn: <ARN>
        # Autoscaler will auto fill the CPU/GPU resources below.
        resources:
            CPU: 4
            GPU: 1
        max_workers: 15
    cpu_ondemand:
        node_config:
            InstanceType: m5.large
            SubnetIds:
                - <subnet1>
                - <subnet2>
            ImageId: ami-0bdfa178b5c1fb9e6 # Deep Learning AMI (Ubuntu 18.04)
            KeyName: <key-name>
            BlockDeviceMappings:
                - DeviceName: /dev/sda1
                  Ebs:
                      VolumeSize: 150
        max_workers: 0
        resources:
            CPU: 2

head_node_type: cpu_ondemand
worker_default_node_type: gpu_ondemand
```

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

It looks like existing infeasible placement group in placement group manager didn't work properly. Idk how we added this feature when we cannot pass this simple test case.

But this is what has happend;

(1) PG is not scheduleable because it is infeasible
(2) New node is added
(3) After a new node is added, placement group manager tries rescheduling all infeasible pgs.
(4) Here, when we add a new node, we didn't report resources (this seems to be very weird. We are reporting resource using a separate RPC here). So when (3) happens, pg was still unschedulable. 

This PR fixes the issue by adding the resource information when the new node is added. 

Note that in the long term, we'd like to have a separate resource path from (4). This won't be addressed in this PR. 

## Related issue number

Closes https://github.com/ray-project/ray/issues/20968

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/raylet.cc [hunk 1]
```diff
@@ -79,6 +79,9 @@ Raylet::Raylet(instrumented_io_context &main_service, const std::string &socket_
   self_node_info_.set_node_manager_port(node_manager_.GetServerPort());
   self_node_info_.set_node_manager_hostname(boost::asio::ip::host_name());
   self_node_info_.set_metrics_export_port(metrics_export_port);
+  const auto &resource_map = node_manager_config.resource_config.GetResourceMap();
+  self_node_info_.mutable_resources_total()->insert(resource_map.begin(),
```
Comment (rkooo567) [inline src/ray/raylet/raylet.cc:83]: Previously, since we didn't report node resource information, when a new node is reported to GCS, and pg manager tries to reschedule infeasible pgs, it always failed. 

The resource is currently reported "again" by line 122, which is pretty weird. I believe it is the legacy code path we should clean. cc @iycheng (We should remove the Resource Table from GCS)

Comment (iycheng) [reply src/ray/raylet/raylet.cc:83]: I agree. The resource table seems like something can be reconstructed by just pulling data.

File: python/ray/tests/test_placement_group_3.py [hunk 2]
```diff
@@ -687,5 +687,28 @@ def test_fractional_resources_handle_correct(ray_start_cluster):
...
+    ray.init("auto")
+
+    bundle = {"CPU": 4, "GPU": 1}
+    pg = placement_group([bundle], name="worker_1", strategy="STRICT_PACK")
+
+    # Placement group is infeasible.
+    try:
+        pg.wait(timeout=3)
+    except Exception:
+        pass
```
Comment (iycheng) [inline python/ray/tests/test_placement_group_3.py:703]: `pytest.raises` to make sure the Exception is thrown.

**Review by fishbone — APPROVED** [review]

**Comment by rkooo567** [comment]
The failed test seems unrelated
