### PR TITLE
[core][autoscaler] Fix number of dispatching tasks inconsistent with resources usage on single node

### LINKED ISSUE #38004: [core][autoscaler] Inconsistent report of node's resources and load
### What happened + What you expected to happen

With node resource usage and load being updated independently, Ray cluster might expose incorrect resources state, which leads to false scaling.  E.g a task might no longer be pending but it is still showing up as part of requests. 

### Versions / Dependencies

master

### Reproduction script

```
import time
import ray
@ray.remote(num_cpus=<num_cpus_on_node>)
def foo():
  for x in range(5):
    print("A loop...")
    time.sleep(0.1)
  return True

while True:
    assert(ray.get(foo.remote()))

```

### Issue Severity

None

### LINKED ISSUE #38181: [CI] `linux://python/ray/autoscaler/v2:test_e2e` is failing/flaky on master.
- e19e4c07932fdd95539e18faac4e35f5df42cbc2 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5309#0189d107-fdf5-46e9-8cf3-ef499012ea42)
- e8f21da98a02dc34740f619db476a0e25d39a20a FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5306#0189d0e3-3c1a-4792-82d4-3f5cc66d95dd)
- 7216cd897ec17f0167718277d48c159ca93a5b29 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5304#0189d0af-f628-4348-996c-f1565f96b625)
- d290a3f9a83cbbf9e9a871354f5cd8db59d64ebe FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5303#0189cf29-06ed-47d4-a40f-3c9e89086758)
- 21fb277c5bc22c4e6f655abed4bc81d1db09391e FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5302#0189cf24-ce73-483f-b113-cd07103a2722)
- baad82c18887dee328a3b6b9bf7c070dcd278591 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5296#0189c2ed-2166-4dda-aa9a-f33d9e5c87e4)
- afb77089b587b5de2b5a54de0c5e488ca836e43a FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5294#0189c2ec-ef09-409f-a5f5-2022e9d2e707)
- 43958f0520223ce90c208e0b883a1abc55e7a2c1 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5293#0189c2c9-c3c3-4881-838e-9498c58885b5)
- 5d7431f981e4da808dd8b56292535a36c664bc00 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5289#0189c23c-e2ec-43eb-9bcc-015ca996854b)
- 4415c56b4eb6ffa73ac375cd06e71688355b8b4c FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5283#0189c20c-dc0b-4db1-a6d0-ea1807f6a108)
- 57f53c7f91f92fde7fc31debadd4de659951468b FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5278#0189c16b-6c85-4617-99b0-f4e59f3ae05b)
- e55258c114245db9cd541d4d73aa6217358c11f2 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5276#0189c135-721b-4bcf-99ac-23bca7119607)
- d09e7c504b84700b4d8eebe33e7885acc530ad79 FAILED [Buildkite :python: (Small & Client)](https://buildkite.com/ray-project/oss-ci-build-branch/builds/5275#0189c129-9fcf-4e8e-a869-f8373724a1f2)

....
Generated from flaky test tracker. Please do not edit the signature in this section.
DataCaseName-linux://python/ray/autoscaler/v2:test_e2e-END
....

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
Right now, if a task is being dispatched, it will:
1. Allocate resources instance 
2. Waiting for worker asynchronously 
3. Being dispached to worker. 

So when a task is in phase 2, it already has resources allocated from the node but it will still show up as load demand right now. 

This PR: 
1. Account the right number of tasks to dispatch (by excluding those with allocations) 

This is not ideal since it leads to issues like https://github.com/ray-project/ray/issues/38004

## Related issue number
Closes https://github.com/ray-project/ray/issues/38004
Closes https://github.com/ray-project/ray/issues/38181

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/scheduling/local_resource_manager.cc [hunk 1]
```diff
@@ -473,6 +466,24 @@ std::optional<syncer::RaySyncMessage> LocalResourceManager::CreateSyncMessage(
   resources_data.set_idle_duration_ms(
       absl::ToInt64Milliseconds(now - GetResourceIdleTime().value_or(now)));
 
+  return true;
+}
+
+std::optional<syncer::RaySyncMessage> LocalResourceManager::CreateSyncMessage(
```
Comment (rickyyx) [inline src/ray/raylet/scheduling/local_resource_manager.cc:472]: moved.

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 2]
```diff
@@ -69,6 +69,11 @@ void SchedulerResourceReporter::FillResourceUsage(
   absl::flat_hash_set<SchedulingClass> visited;
   auto fill_resource_usage_helper = [&](const auto &range, bool is_infeasible) mutable {
     for (auto [scheduling_class, count] : range) {
+      if (count == 0) {
```
Comment (rickyyx) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:72]: cc @iycheng  - this is okay right? I was curious why we didn't skip those scheduling class with count == 0?

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 3]
```diff
@@ -130,8 +134,21 @@ void SchedulerResourceReporter::FillResourceUsage(
...
   fill_resource_usage_helper(
       tasks_to_schedule_ | boost::adaptors::transformed(transform_func), false);
-  fill_resource_usage_helper(
-      tasks_to_dispatch_ | boost::adaptors::transformed(transform_func), false);
+
+  auto tasks_to_dispatch_range =
+      tasks_to_dispatch_ | boost::adaptors::transformed([](const auto &pair) {
+        auto cnt = pair.second.size();
+        // We should only report dispatching tasks that do not have resources allocated.
+        for (const auto &task : pair.second) {
```
Comment (rickyyx) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:142]: The O(n) loop is probably ok since the codepath is triggered outside of the critical path of tasks running. 

Will do core benchamrk to validate.

File: src/ray/protobuf/node_manager.proto [hunk 4]
```diff
@@ -331,7 +321,17 @@ message GetObjectsInfoReply {
...
+message GetResourceLoadRequest {
+  // The last seen version, -1 indicating no resources update has been seen.
+  // If the current version on the server end is not newer than this, the server
+  // will skip populating the resources view of the node, but only adding
+  // the newest load information.
+  // NOTE(rickyx): We could also do lightweight load reporting, but since we
+  // are only updating load info less frequentlys, 1 sec by default by
+  // gcs_pull_resource_loads_period_milliseconds, it's ok to send the entire load
+  // info, which is usally small.
+  int64 last_seen_version = 1;
```
Comment (rickyyx) [inline src/ray/protobuf/node_manager.proto:333]: This is needed so that we could skip populating resources when getting the load (similar to lightweight resources broadcasting). 

However, since this is GCS polling raylets, it needs to tell the raylet which is the most recent version of resources so the raylet could decide if data needs to be populated.

**Comment by rickyyx** [comment]
> ## Attention: External code changed
> This PR changes code that is used or cited in external sources, e.g. blog posts.
> 
> Before merging this PR, please make sure that the code in the external sources is still working, and consider updating them to reflect the changes.
> 
> The affected files and the external sources are:
> 
> * `doc/external/pytorch_tutorials_hyperparameter_tuning_tutorial.py`: https://pytorch.org/tutorials/beginner/hyperparameter_tuning_tutorial.html

This is not right?

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc (hunk 2 above)
Comment (rickyyx) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:72]: ah, actually, backlog are passed with count set to 0 explicitly.

Comment (rickyyx) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:72]: So my change is not correct.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 5]
```diff
@@ -1193,7 +1193,7 @@ TEST_F(ClusterTaskManagerTest, HeartbeatTest) {
         // infeasible, ready, CPU, GPU, size
         {1, 0, 10, 1, 2},
         {1, 0, 9, 5, 2},
-        {0, 1, 1, 0, 1}};
+        {0, 0, 1, 0, 1}};
```
Comment (rickyyx) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1196]: This is such that we are no longer treating task that has resources allocated in the "num_ready"  demand.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 6]
```diff
@@ -1319,15 +1319,15 @@ TEST_F(ClusterTaskManagerTest, BacklogReportTest) {
   ASSERT_EQ(pool_.workers.size(), 0);
   ASSERT_EQ(node_info_calls_, 0);
 
-  {  // No tasks can run because the worker pool is empty.
+  {  // 1 task has resources allocated, while remaining 9 is stuck.
```
Comment (rickyyx) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1322]: this is also similar,
before:
- if a task has resources allocated, but no worker, it will be reported as demand. 
- however, this will lead to scaling up in autoscaler as autoscaler thought there's no enough resources, but there's actually just delay in starting the worker. 

now: 
- once a task has resource allocated, it will not show up as demand, which makes a node's resource usage consistent with the load demand.

**Review by rickyyx — COMMENTED** [review]
There seems to be an eaisier fix.

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 7]
```diff
@@ -1,13 +1,83 @@
...
+def foo():
+  return True
+while True:
+    assert(ray.get(foo.remote()))
+"""
+    run_string_as_driver_nonblocking(driver_script)
+
+    def jobs_run():
+        jobs = list_jobs()
+        assert len(jobs) > 1
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:59]: Add a comment saying it's `> 1` not `== 1`

**Review by jjyao — APPROVED** [review]

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc (hunk 3 above)
Comment (rkooo567) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:137]: what's the frequency? I think it is hard to validate it via benchmark because it will affect the CPU usage or the latency to reply some RPCs (and probably e2e latency is not as affected)

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc (hunk 6 above)
Comment (rkooo567) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:1322]: so this test was originally written in a way one of tasks are assigned to worker already?

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 8]
```diff
@@ -1,13 +1,83 @@
...
+
+        return True
+
+    wait_for_condition(jobs_run)
+
+    try:
```
Comment (rkooo567) [inline python/ray/autoscaler/v2/tests/test_e2e.py:65]: try should be in the beg of the test? (when the AutoscalerCluster is initialized) otherwise it can leak?

**Review by rkooo567 — APPROVED** [review]
LGTM in general. Some questions before merging the PR...

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc (hunk 6 above)
Comment (rickyyx) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:1322]: originally the code and the test are both double-counting a dispatching task with resources allocated as pending, which is the root-cause of the inconsistency. 

in the original code, only when worker is ready, a dispatch task will then be removed from the demand, but it should be removed from the demand when resources could be allocated. (And it will be added back as demand when worker popping fails)

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc (hunk 3 above)
Comment (rickyyx) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:137]: right now, 1 every sec.

Comment (rkooo567) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:137]: That seems okay then!
