### PR TITLE
[gcs] Fix actor killing hang due to race condition

### LINKED ISSUE #17369: [Core] Actor hangs after other actors are killed
This very simple script is hanging for me. This is on nightly wheels.

```
import ray
ray.init(num_cpus=2)

class BaseWorker:
    """A class to execute arbitrary functions. Does not hold any state."""

    def execute(self, func):
        """Executes the input function and returns the output.
        Args:
            func(Callable): A function that does not take any arguments.
        """
        return func()

remote_cls = ray.remote(num_cpus=1)(BaseWorker)
workers = [remote_cls.remote() for _ in range(2)]

for worker in workers:
	ray.kill(worker)

remote_cls = ray.remote(num_cpus=1)(BaseWorker)
workers = [remote_cls.remote() for _ in range(2)]

func  = lambda: 1
ray.get([w.execute.remote(func) for w in workers]) # This hangs!
```

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

Creating and killing an actor immediately will have a race condition.

- Lease
- Canceling
- Lease reply
It will leave the worker leak. This PR fixed it.

And there is another race condition:
- Task creating
- Canceling
- Task creating reply received

This will leave the worker leaked too. 

## Related issue number
Closes #17369

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 1]
```diff
@@ -361,12 +362,20 @@ void GcsActorScheduler::CreateActorOnWorker(std::shared_ptr<GcsActor> actor,
               RetryCreatingActorOnWorker(actor, worker);
             }
           }
+        } else {
+          RAY_LOG(DEBUG) << "Actor " << actor->GetActorID()
+                         << " has been removed from creating map. Actor status "
+                         << actor->GetState();
+          auto actor_id = status.ok() ? actor->GetActorID() : ActorID::Nil();
+          KillActorOnWorker(worker->GetAddress(), actor_id);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:370]: Was this another race condition?

**Review by rkooo567 — APPROVED** [review]
@iycheng can you re-run the originally failing tests 3X times and lmk if that all passes?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 2]
```diff
@@ -586,12 +587,12 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id) {
       }
     }
   }
-
   // The actor is already dead, most likely due to process or node failure.
   if (actor->GetState() == rpc::ActorTableData::DEAD) {
+    RAY_LOG(DEBUG) << "Actor " << actor->GetActorID() << "has been dead,"
+                   << "skip sending killing request";
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:593]:
```suggestion
                   << "skip sending killing request.";
```

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 3]
```diff
@@ -343,6 +343,7 @@ void GcsActorScheduler::CreateActorOnWorker(std::shared_ptr<GcsActor> actor,
         if (iter != node_to_workers_when_creating_.end()) {
           auto worker_iter = iter->second.find(actor->GetWorkerID());
           if (worker_iter != iter->second.end()) {
+            RAY_LOG(DEBUG) << "Worker " << worker_iter->first << " is in creating map. ";
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:346]:
```suggestion
            RAY_LOG(DEBUG) << "Worker " << worker_iter->first << " is in creating map.";
```

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 4]
```diff
@@ -394,6 +403,26 @@ std::shared_ptr<WorkerLeaseInterface> GcsActorScheduler::GetOrConnectLeaseClient
...
+bool GcsActorScheduler::KillActorOnWorker(const rpc::Address &worker_address,
+                                          ActorID actor_id) {
+  if (worker_address.raylet_id().empty()) {
+    RAY_LOG(DEBUG) << "Invalid worker address, skip the killing of actor " << actor_id;
+    return false;
+  }
+
+  auto cli = core_worker_clients_.GetOrConnect(worker_address);
+  rpc::KillActorRequest request;
+  // Set it to be Nil() since it hasn't been setup yet
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:415]:
```suggestion
  // Set it to be Nil() since it hasn't been setup yet.
```

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 5]
```diff
@@ -450,6 +479,12 @@ void RayletBasedActorScheduler::HandleWorkerLeaseReply(
           << actor->GetActorID()
           << " has been already cancelled. The response will be ignored. Job id = "
           << actor->GetActorID().JobId();
+      if (actor->GetState() == rpc::ActorTableData::DEAD) {
+        // If the actor has been killed, we need to kill the worker too
+        // otherwise, the worker will be leaked.
+        RAY_LOG(DEBUG) << "Actor " << actor->GetActorID() << " is dead, kill the worker";
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:485]:
```suggestion
        RAY_LOG(DEBUG) << "Actor " << actor->GetActorID() << " is dead, kill the worker.";
```

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 6]
```diff
@@ -477,6 +512,11 @@ void RayletBasedActorScheduler::HandleWorkerLeaseReply(
     } else {
       RetryLeasingWorkerFromNode(actor, node);
     }
+  } else if (actor->GetState() == rpc::ActorTableData::DEAD) {
+    // If the actor has been killed, we need to kill the worker too
+    // otherwise, the worker will be leaked.
+    RAY_LOG(DEBUG) << "Actor " << actor->GetActorID() << " is dead, kill the worker";
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:518]:
```suggestion
    RAY_LOG(DEBUG) << "Actor " << actor->GetActorID() << " is dead, kill the worker.";
```

**Review by ffbin — APPROVED** [review]
LGTM, just some small comments.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 1 above)
Comment (iycheng) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:370]: Yes

**Comment by iycheng** [comment]
@rkooo567 I verified it.

**Comment by rkooo567** [comment]
Retry one rllib test. Btw, is it possible to add an unit test on `gcs_actor_manager_test`? I prefer to add that in this PR, but doing in the follow up is also fine for me.

**Comment by iycheng** [comment]
> Retry one rllib test. Btw, is it possible to add an unit test on `gcs_actor_manager_test`? I prefer to add that in this PR, but doing in the follow up is also fine for me.

Let me investigate it next week. Feel a little bit tired on this PR. :( I've put it in my schedule.

**Comment by rkooo567** [comment]
@iycheng sgtm!

**Comment by rkooo567** [comment]
Can you add it to the sprint task?

**Comment by iycheng** [comment]
> Can you add it to the sprint task?

I did add that.
