### PR TITLE
[Core][actor out-of-order execution 2/n] create abstraction for the queuing logic on the client/actor submission.

### LINKED ISSUE #19822: [Core] support out of order execution for threaded/async actors
The following will timeout
```python
import ray
ray.init()

@ray.remote
class A:
    def echo(self, inp):
        print(inp)
        return inp

@ray.remote
def never_return():
    import time
    time.sleep(10000)

inp_ref_1 = never_return.remote()
inp_ref_2 = ray.put(2)

a = A.options(max_concurrency=2).remote()

out_ref_1 = a.echo.remote(inp_ref_1)
out_ref_2 = a.echo.remote(inp_ref_2)

assert ray.get(out_ref_2, timeout=5) == 2 # currently timeout!
```

I went all the way back to Ray 0.8.0 and it is the same behavior, so this is _not_ a regression. For concurrent actors and async actors, however, I think the snippet should work and we should allow later tasks to execute first when their dependencies ready. **This is a semantics change.**

Context: user bug report for Ray Serve https://discuss.ray.io/t/concurrent-queries-blocking-following-queries/3949/2

### PR DESCRIPTION
**Pull request by scv119**
This second PR in the stack that supports out or order execution for threaded/async actors. Previous PR #20148 Next PR #20150
At a high level, threaded actor/async actor already don't guarantee execution order, and the current "sequential" order implementation has caused some confusion and inconvenience. Please refer to #19822 for detailed discussion.

This PR we further separate out the logic for ordering actor requests on the client side. In the next PR, we will implement a different type of queue that supports out of order execution.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by simon-mo — APPROVED** [review]
Stamp (refactoring)

File: src/ray/core_worker/transport/actor_submit_queue.h [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+#include "absl/types/optional.h"
+#include "ray/common/id.h"
+#include "ray/common/task/task_spec.h"
+
+namespace ray {
+namespace core {
+
+/**
+ * IActorSubmitQueue is responsible for queuing per actor requests on the client.
```
Comment (rkooo567) [inline src/ray/core_worker/transport/actor_submit_queue.h:28]: Add docstring?

File: src/ray/core_worker/transport/actor_submit_queue.h [hunk 2]
```diff
@@ -0,0 +1,47 @@
...
+  virtual void MarkDependencyResolved(uint64_t sequence_no) = 0;
+  virtual std::vector<TaskID> ClearAllTasks() = 0;
+  virtual absl::optional<std::pair<TaskSpecification, bool>> PopNextTaskToSend() = 0;
+  virtual std::map<uint64_t, TaskSpecification> PopAllOutOfOrderCompletedTasks() = 0;
+  virtual void OnClientConnected() = 0;
+  virtual uint64_t GetSequenceNumber(const TaskSpecification &task_spec) const = 0;
+  virtual void MarkTaskCompleted(uint64_t sequence_no, TaskSpecification task_spec) = 0;
+};
+}  // namespace core
+}  // namespace ray
```
Comment (rkooo567) [inline src/ray/core_worker/transport/actor_submit_queue.h:47]: Newline!

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc [hunk 3]
```diff
@@ -251,19 +243,16 @@ void CoreWorkerDirectActorTaskSubmitter::DisconnectActor(
...
-      auto &requests = queue->second.requests;
-      auto head = requests.begin();
 
       auto status = Status::IOError("cancelling all pending tasks of dead actor");
-      while (head != requests.end()) {
-        const auto &task_spec = head->second.first;
-        task_finisher_.MarkTaskCanceled(task_spec.TaskId());
+      auto task_ids = queue->second.actor_submit_queue->ClearAllTasks();
+
+      for (auto &task_id : task_ids) {
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_actor_task_submitter.cc:250]:
```suggestion
      for (const auto &task_id : task_ids) {
```

**Review by rkooo567 — COMMENTED** [review]
I think we should add 
- Cpp unit tests
- Docstring
?
~~Also at the same time, I wonder if we should not separate this logic out (The class seems to be very shallow), but it is up to you... I don't know the full picture now~~

Actually never mind. So, the comment above is definitely due to the fact that I don't have a full picture lol

File: src/ray/core_worker/transport/actor_submit_queue.h [hunk 4]
```diff
@@ -0,0 +1,47 @@
...
+#include "ray/common/task/task_spec.h"
+
+namespace ray {
+namespace core {
+
+/**
+ * IActorSubmitQueue is responsible for queuing per actor requests on the client.
+ * TODO(scv119): add more details.
+ */
+class IActorSubmitQueue {
```
Comment (jovany-wang) [inline src/ray/core_worker/transport/actor_submit_queue.h:31]: Existing interface classes are named `Interface` as the suffix. Is there any reason for using such rule?

File: src/ray/core_worker/transport/direct_actor_task_submitter.cc [hunk 5]
```diff
@@ -77,9 +77,7 @@ Status CoreWorkerDirectActorTaskSubmitter::SubmitTask(TaskSpecification task_spe
       // backpressure. The receiving actor will execute the tasks according to
       // this sequence number.
       send_pos = task_spec.ActorCounter();
-      auto inserted =
-          queue->second.requests.emplace(send_pos, std::make_pair(task_spec, false));
-      RAY_CHECK(inserted.second);
+      RAY_CHECK(queue->second.actor_submit_queue->Emplace(send_pos, task_spec));
```
Comment (jovany-wang) [inline src/ray/core_worker/transport/direct_actor_task_submitter.cc:80]: Nice refinement.

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.h [hunk 6]
```diff
@@ -0,0 +1,50 @@
...
+
+namespace ray {
+namespace core {
+
+/**
+ * OutofOrderActorSubmitQueue sends request as soon as the dependencies are resolved.
+ */
+class OutofOrderActorSubmitQueue : public IActorSubmitQueue {
+ public:
+  OutofOrderActorSubmitQueue(ActorID actor_id);
```
Comment (jovany-wang) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.h:32]:
```suggestion
  explicit OutofOrderActorSubmitQueue(ActorID actor_id);
```

File: src/ray/core_worker/transport/out_of_order_actor_submit_queue.h [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+
+#include "absl/types/optional.h"
+#include "ray/common/id.h"
+#include "ray/core_worker/transport/actor_submit_queue.h"
+
+namespace ray {
+namespace core {
+
+/**
+ * OutofOrderActorSubmitQueue sends request as soon as the dependencies are resolved.
```
Comment (jovany-wang) [inline src/ray/core_worker/transport/out_of_order_actor_submit_queue.h:28]: Sorry that I didn't see any usage of this class :)

**Comment by jovany-wang** [comment]
Not sure if this is ready for review.

**Comment by scv119** [comment]
both test_job_manager and test_autoscaler_drain_node_api is broken on master.
