### PR TITLE
[event] event framework integration in raylet, gcs server and core worker

### LINKED ISSUE #16249: [Dashboard][event] Basic event points.
- Some event points to expose exception, crash message, and `RAY_CHECK` failed.
- Event point will generate event logs.
- The event points will be located in C++、Java and Python.

### PR DESCRIPTION
**Pull request by SongGuyang**
## Why are these changes needed?
- Integrate event framework to make sure we can output event logs by event API in core processes.
- Add event of ray fatal check failed.

### CODE REVIEW

**Comment by rkooo567** [comment]
This is awesome! Chen and I will review this shortly!

**Review by scv119 — DISMISSED** [review]
Thanks for contributing the event framework!

File: src/ray/util/event.h [hunk 1]
```diff
@@ -202,4 +202,8 @@ class RayEvent {
   std::ostringstream osstream_;
 };
 
+void RayEventInit(rpc::Event_SourceType source_type,
```
[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/util/event.h:205]: Maybe to be a static function of `RayEventContext`? `Event` class is one-off.

File: src/ray/util/logging.cc [hunk 2]
```diff
@@ -335,11 +341,22 @@ std::string RayLog::GetLogFormatPattern() { return log_format_pattern_; }
...
+}
+
 RayLog::RayLog(const char *file_name, int line_number, RayLogLevel severity)
-    : logging_provider_(nullptr), is_enabled_(severity >= severity_threshold_) {
+    : logging_provider_(nullptr),
+      is_enabled_(severity >= severity_threshold_),
+      severity_(severity),
+      is_exposed_(severity == RayLogLevel::FATAL) {
+  if (is_exposed_) {
+    expose_osstream_ = new std::ostringstream();
```
[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/util/logging.cc:354]: Yep, my fault.

File: src/ray/util/logging.h [hunk 3]
```diff
@@ -182,18 +184,30 @@ class RayLogBase {
   // By default, this class is a null log because it return false here.
   virtual bool IsEnabled() const { return false; };
 
+  // This function to judge whether current log is fatal or not.
+  virtual bool IsExposed() const { return false; };
```
[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/util/logging.h:188]: I forgot to modify this comment. I'm considering using expose or fatal. If named expose, we can also produce other type logs, such as error log, signal handling log. But we also could name fatal to be an general type. Do you mean rename to `IsFatal` and `FatalLogCallback` better?

File: src/ray/core_worker/core_worker.cc [hunk 4]
```diff
@@ -181,6 +182,12 @@ CoreWorkerProcess::CoreWorkerProcess(const CoreWorkerOptions &options)
   // for java worker or in constructor of CoreWorker for python worker.
   stats::Init(global_tags, options_.metrics_agent_port);
 
+  // Initialize event framework.
+  if (RayConfig::instance().event_log_reporter_enabled() && !options_.log_dir.empty()) {
+    RayEventInit(ray::rpc::Event_SourceType::Event_SourceType_CORE_WORKER,
```
[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/core_worker/core_worker.cc:187]: Good point. But core worker is multi-threaded. We should add this custom field in the constructor of CoreWorker, not CoreWorkerProcess. Maybe we should add this field after finish the multi-thread issue?

File: src/ray/common/ray_config_def.h [hunk 5]
```diff
@@ -469,4 +469,7 @@ RAY_CONFIG(uint64_t, resource_broadcast_batch_size, 512);
 RAY_CONFIG(bool, worker_resource_limits_enabled, false)
 
 /// ServerCall instance number of each RPC service handler
-RAY_CONFIG(int64_t, gcs_max_active_rpcs_per_handler, 100)
\ No newline at end of file
+RAY_CONFIG(int64_t, gcs_max_active_rpcs_per_handler, 100)
+
+/// Whether to use log reporter in event framework
+RAY_CONFIG(bool, event_log_reporter_enabled, true)
```
Comment (rkooo567) [inline src/ray/common/ray_config_def.h:475]: New line

File: src/ray/raylet/main.cc [hunk 6]
```diff
@@ -253,6 +256,14 @@ int main(int argc, char *argv[]) {
             redis_password, node_manager_config, object_manager_config, gcs_client,
             metrics_export_port));
 
+        // Initialize event framework.
+        if (RayConfig::instance().event_log_reporter_enabled() && !log_dir.empty()) {
+          auto custom_fields = std::unordered_map<std::string, std::string>();
+          custom_fields.emplace("node_id", raylet->GetNodeId().Hex());
+          ray::RayEventInit(ray::rpc::Event_SourceType::Event_SourceType_RAYLET,
+                            custom_fields, log_dir);
```
Comment (rkooo567) [inline src/ray/raylet/main.cc:264]:
```suggestion
                           {{"node_id", raylet->GetNodeID().Hex()}}, log_dir);
```
?

File: src/ray/util/event.cc [hunk 7]
```diff
@@ -213,4 +220,14 @@ void RayEvent::SendMessage(const std::string &message) {
   EventManager::Instance().Publish(event, custom_fields_);
 }
 
+void RayEventInit(rpc::Event_SourceType source_type,
+                  const std::unordered_map<std::string, std::string> &custom_fields,
+                  const std::string &log_dir) {
+  RayEventContext::Instance().SetEventContext(source_type, custom_fields);
+  auto event_dir = boost::filesystem::path(log_dir) / boost::filesystem::path("event");
```
Comment (rkooo567) [inline src/ray/util/event.cc:227]: This is great :)

File: src/ray/util/event.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/util/event.h:205]: Hmm this seems to be a little weird to be a method of RayEventContext? Why don't we just have a global static function? event:: RayEventInit()

File: src/ray/common/ray_config_def.h (hunk 5 above)
Comment (rkooo567) [inline src/ray/common/ray_config_def.h:475]: Can we turn this off by default until we solve the thread safety issue? I am a little worried the logging.cc change can cause memory corruption in some scenarios (since logging module is shared by all threads)

File: src/ray/util/logging.cc [hunk 8]
```diff
@@ -335,11 +341,22 @@ std::string RayLog::GetLogFormatPattern() { return log_format_pattern_; }
 
 std::string RayLog::GetLoggerName() { return logger_name_; }
 
+void RayLog::SetExposeLogCallback(const ExposeLogCallback &expose_log_callback) {
+  expose_log_callback_ = expose_log_callback;
```
Comment (rkooo567) [inline src/ray/util/logging.cc:345]: Make it accept a vector of callbacks instead?

File: src/ray/util/logging.cc [hunk 9]
```diff
@@ -335,11 +341,22 @@ std::string RayLog::GetLogFormatPattern() { return log_format_pattern_; }
...
+      severity_(severity),
+      is_exposed_(severity == RayLogLevel::FATAL) {
+  if (is_exposed_) {
+    expose_osstream_ = std::make_shared<std::ostringstream>();
+    *expose_osstream_ << file_name << ":" << line_number << ":";
+  }
   if (is_enabled_) {
-    logging_provider_ =
-        new LoggingProvider(file_name, line_number, GetMappedSeverity(severity));
+    logging_provider_ = new LoggingProvider(
```
Comment (rkooo567) [inline src/ray/util/logging.cc:358]: Is there any reason why we do raw malloc instead of using smart pointer for this btw?

File: src/ray/util/event.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/util/event.h:205]: @rkooo567 It's a global function now, but no "event" namespace overall.

[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/util/event.h:205]: Logging module has no special namespace as well.

File: src/ray/common/ray_config_def.h (hunk 5 above)
Comment (SongGuyang) [reply src/ray/common/ray_config_def.h:475]: Make sense.

File: src/ray/util/logging.cc (hunk 8 above)
Comment (SongGuyang) [reply src/ray/util/logging.cc:345]: Make sense.

File: src/ray/util/logging.cc (hunk 9 above)
Comment (SongGuyang) [reply src/ray/util/logging.cc:358]: Maybe because we want to delete this provider to flush log in an special time? I don't really know.

**Comment by rkooo567** [comment]
Can you merge the lastest master? It seems like some of tests are broken!

**Comment by SongGuyang** [comment]
@rkooo567 buildkite CI tests has passed.

File: src/ray/util/event_test.cc [hunk 10]
```diff
@@ -349,6 +359,34 @@ TEST(EVENT_TEST, WITH_FIELD) {
...
+  ASSERT_DEATH({ RAY_CHECK(1 < 0) << "incorrect test case"; }, "");
+
+  std::vector<std::string> vc;
+  ReadEventFromFile(vc, log_dir + "/event/event_RAYLET.log");
+  json out_custom_fields;
+  rpc::Event ele_1 = GetEventFromString(vc.back(), &out_custom_fields);
+
+  CheckEventDetail(ele_1, "job 1", "node 1", "task 1", "RAYLET", "FATAL",
+                   EL_RAY_FATAL_CHECK_FAILED, "NULL");
+  EXPECT_TRUE(StringContains(ele_1.message(), "Check failed: 1 < 0 incorrect test case"));
```
Comment (scv119) [inline src/ray/util/event_test.cc:383]: pro tips: gtest has this builtin:
```
EXPECT_THAT(haystack, HasSubstr(needle));
```

**Comment by scv119** [comment]
The PR looks great delta the thread safety concern. Is the plan to address it in follow up PRs?

**Comment by SongGuyang** [comment]
@scv119 Sure, plan to support thread safety in next PR. Another issue is that exposing crash stack except RAY_CHECK. But there is a troublesome problem. We use absl and set an callback function `WriteFailureMessage` to catch crash stack. But the stack message will be output line by line. `WriteFailureMessage` will be called back multiple times. It will bring multiple events. Actually, I have solved this issue in Ant internal repo. But we used glog signal handler in our internal version,  not absl. And I have made a patch in glog source code to make sure the `WriteFailureMessage` function only called back once. But If we use absl, I don't ensure how to resolve this issue.

**Comment by rkooo567** [comment]
@SongGuyang if we can use event framework in python, I think we can just report the failure from log_monitor. That might make things easier (log monitor already publishes the stacktrace to the driver now)

File: src/ray/util/logging.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/util/logging.h:190]: This hasn't seemed to be addressed

**Review by rkooo567 — COMMENTED** [review]
> @scv119 Sure, plan to support thread safety in next PR. Another issue is that exposing crash stack except RAY_CHECK. But there is a troublesome problem. We use absl and set an callback function WriteFailureMessage to catch crash stack. But the stack message will be output line by line. WriteFailureMessage will be called back multiple times. It will bring multiple events. Actually, I have solved this issue in Ant internal repo. But we used glog signal handler in our internal version, not absl. And I have made a patch in glog source code to make sure the WriteFailureMessage function only called back once. But If we use absl, I don't ensure how to resolve this issue.

If this is the issue, I think we shouldn't add this feature until we find a right solution (multiple events per line of stacktrace sounds bad). Why don't we not write to event for now in this case? I think we can consider writing directly from the log monitor for OSS

**Comment by SongGuyang** [comment]
@rkooo567 But logmonitor can not get the structural data？Such as raylet id.

**Comment by rkooo567** [comment]
@SongGuyang I think it is not difficult to make it get those things (maybe we can just change the raylet log name to `raylet-[node_id].out`). Or there can be many ways to achieve that

**Comment by scv119** [comment]
rely on @rkooo567 to final accept/merge this.

**Comment by rkooo567** [comment]
Let's remove the stacktrace report for now, then I will approve. I think having event per line is worse than not having it since stacktrace is already reported to the driver.

**Comment by rkooo567** [comment]
I will start adding events using the framework once the thread safety PR is ready

**Comment by SongGuyang** [comment]
@rkooo567 Maybe there is a mistake. The stacktrace should be caught in two scenes. The first is `RAY_CHECK` which I had integrated in current PR. This one is not relied absl signal handler and don't have the problem of multiple line events. And the second is crash scene which is not raised by `RAY_CHECK`. It should be caught by absl signal handler. The second scene is not integrated in current PR now. I just threw this problem before implementation.

File: src/ray/util/logging.h (hunk 3 above)
[the remark this answers is not in the document]
Comment (SongGuyang) [reply src/ray/util/logging.h]: Addressed.

**Review by rkooo567 — APPROVED** [review]
Can you confirm this is disabled now? I think we shouldn't add the stacktrace stuff before having thread safety (let's enable it after that). Otherwise, it LGTM

**Comment by SongGuyang** [comment]
This config `event_log_reporter_enabled` is false by default.  https://github.com/ray-project/ray/pull/17671/files#diff-66e8718c71d8ec5383a5cc83b0ade4d1aa8bad17d7ced811928bb666b4b63165R467

**Review by raulchen — APPROVED** [review]
