### PR TITLE
[Python Worker] add feature flag to support forking from workers

### LINKED ISSUE #22909: [Bug] Crash after enabling GCS pubsub
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### Issue Severity

High

### What happened + What you expected to happen

A crash happens for a user workload, where bisection points to 5893a9eddb2b40fad11ef0da281a42258a1aa7d6.

Crash stack trace:
```
(Actor pid=84979, ip=10.97.18.74) *** SIGSEGV received at time=1646716655 on cpu 90 ***
(Actor pid=84979, ip=10.97.18.74) PC: @     0x7f1b250b9eb9  (unknown)  (unknown)
(Actor pid=84979, ip=10.97.18.74)     @     0x7f1bca46a210  1717161808  (unknown)
(Actor pid=84979, ip=10.97.18.74)     @ ... and at least 1000 more frames
(Actor pid=84979, ip=10.97.18.74) [2022-03-08 05:17:35,730 E 85732 85753] logging.cc:321: *** SIGSEGV received at time=1646716655 on cpu 90 ***
(Actor pid=84979, ip=10.97.18.74) [2022-03-08 05:17:35,730 E 85732 85753] logging.cc:321: PC: @     0x7f1b250b9eb9  (unknown)  (unknown)
(Actor pid=84979, ip=10.97.18.74) [2022-03-08 05:17:35,730 E 85732 85753] logging.cc:321:     @     0x7f1bca46a210  1717161808  (unknown)
(Actor pid=84979, ip=10.97.18.74) [2022-03-08 05:17:35,730 E 85732 85753] logging.cc:321:     @ ... and at least 1000 more frames
(Actor pid=84979, ip=10.97.18.74) Fatal Python error: Segmentation fault
(Actor pid=84979, ip=10.97.18.74) 
(Actor pid=84979, ip=10.97.18.74) Current thread 0x00007eebb8662700 (most recent call first):
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 319 in reduce_storage
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/reduction.py", line 51 in dumps
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/connection.py", line 211 in send
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 300 in serve_client
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 413 in accept_connection
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 212 in handle_request
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 910 in run
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 973 in _bootstrap_inner
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 930 in _bootstrap
(Actor pid=84979, ip=10.97.18.74) 
(Actor pid=84979, ip=10.97.18.74) Thread 0x00007eebb7e61700 (most recent call first):
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/socket.py", line 293 in accept
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/connection.py", line 614 in accept
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/connection.py", line 468 in accept
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 189 in accepter
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 910 in run
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 973 in _bootstrap_inner
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 930 in _bootstrap
(Actor pid=84979, ip=10.97.18.74) 
(Actor pid=84979, ip=10.97.18.74) Thread 0x00007f1bca2a64c0 (most recent call first):
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 316 in wait
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/threading.py", line 574 in wait
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 176 in serve_forever
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 591 in _run_server
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/process.py", line 108 in run
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/process.py", line 315 in _bootstrap
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/popen_fork.py", line 71 in _launch
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/popen_fork.py", line 19 in __init__
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/context.py", line 277 in _Popen
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/process.py", line 121 in start
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/multiprocessing/managers.py", line 554 in start
(Actor pid=84979, ip=10.97.18.74)   File "/root/code/openai/torch_multi.py", line 31 in start
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/util/tracing/tracing_helper.py", line 462 in _resume_span
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/_private/function_manager.py", line 704 in actor_method_executor
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/worker.py", line 450 in main_loop
(Actor pid=84979, ip=10.97.18.74)   File "/root/.pyenv/versions/3.9.9/lib/python3.9/site-packages/ray/workers/default_worker.py", line 225 in <module>
```

### Versions / Dependencies

Commit 5893a9eddb2b40fad11ef0da281a42258a1aa7d6

### Reproduction script

```
import torch
import ray
import multiprocessing
import multiprocessing.managers
import socket
import sys
import time
​
​
class Server:
    def get(self):
        return torch.rand(2048, 512)
​
​
class Manager(multiprocessing.managers.BaseManager):
    pass
​
​
Manager.register(
    "Server",
    Server,
    exposed=("get",),
)
​
​
class Actor:
    def start(self):
        torch.zeros((), device="cuda")
        torch.multiprocessing.set_sharing_strategy("file_system")
        manager = Manager(ctx=multiprocessing.get_context("fork"))
        manager.start()
        self.server = manager.Server()
​
    def run(self):
        print(socket.gethostname())
        for _ in range(10):
            x = self.server.get()
            time.sleep(0.1)
​
​
def main():
    ray.init(address="pleasedontsigsegv:6379")
    RemoteActor = ray.remote(Actor)
​
    nodes = ray.nodes()
    print(f"found {len(nodes)} nodes")
​
    actors = [
        RemoteActor.options(resources={"node:" + node["NodeManagerAddress"]: 0.1}).remote()
        for node in nodes
        for _ in range(8)
    ]
    ray.get([a.start.remote() for a in actors])
    ray.get([a.run.remote() for a in actors])
​
    print("completed successfully")
​
​
if __name__ == "__main__":
    main()
```

### Anything else

cc @rkooo567 

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by mwtian**
## Why are these changes needed?
1. Make sure Python dependencies can be imported on demand, without the background importer thread. Use cases are:
   -  If the pubsub notification for a new export is lost, importing can still be done.
   -  Allow not running the background importer thread, without affecting Ray's functionalities.

2. Add a feature flag to support forking from Python workers, by
   -  Enable fork support in gRPC.
   -  Disable importer thread and only leave the main thread in the Python worker. The importer thread will not run after forking anyway.

Closes #22909

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/worker_pool.cc [hunk 1]
```diff
@@ -386,6 +386,14 @@ std::tuple<Process, StartupToken> WorkerPool::StartWorkerProcess(
         absl::Base64Escape(RayConfig::instance().object_spilling_config()));
   }
 
+  if (language == Language::PYTHON) {
+    worker_command_args.push_back("--startup-token=" +
+                                  std::to_string(worker_startup_token_counter_));
+  } else if (language == Language::CPP) {
+    worker_command_args.push_back("--startup_token=" +
+                                  std::to_string(worker_startup_token_counter_));
+  }
```
Comment (iycheng) [inline src/ray/raylet/worker_pool.cc:395]: Any reason why move this code?

File: src/ray/common/ray_config_def.h [hunk 2]
```diff
@@ -318,6 +318,15 @@ RAY_CONFIG(uint32_t, task_retry_delay_ms, 0)
 /// Duration to wait between retrying to kill a task.
 RAY_CONFIG(uint32_t, cancellation_retry_ms, 2000)
 
+/// Whether to start a background thread to import Python dependencies eagerly.
+/// When set to false, Python dependencies will still be imported, only when
+/// they are needed.
+RAY_CONFIG(bool, start_python_importer_thread, true)
```
Comment (iycheng) [inline src/ray/common/ray_config_def.h:324]: Any concern about not using the new code by default?

File: src/ray/common/ray_config_def.h [hunk 3]
```diff
@@ -318,6 +318,15 @@ RAY_CONFIG(uint32_t, task_retry_delay_ms, 0)
...
+
+/// Determines if forking in Ray actors / tasks are supported.
+/// Note that this only enables forking in workers, but not drivers.
+RAY_CONFIG(bool, support_fork, false)
```
Comment (iycheng) [inline src/ray/common/ray_config_def.h:328]: The same, why not turn on this support by default?

**Comment by iycheng** [comment]
Overall, it looks good. This PR seems trying to fix the issue in the application layer. Do you think it's still sufficient if we fix it in pubsub layer? Or do you think it's worth fixing it there? My original feeling is that maybe we need to make pubsub robust anyway.

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (mwtian) [reply src/ray/raylet/worker_pool.cc:395]: I want to keep modifications to `worker_command_args` and `env` together, instead of mixed.

File: src/ray/common/ray_config_def.h (hunk 2 above)
Comment (mwtian) [reply src/ray/common/ray_config_def.h:324]: I don't have a significant concern right now. The additional latency from importing lazily shouldn't be a big issue. We can enable this by default in a separate PR.

File: src/ray/common/ray_config_def.h (hunk 3 above)
Comment (mwtian) [reply src/ray/common/ray_config_def.h:328]: This flag sets GRPC flags that do not apply to all OS, and may reduce performance. So it should only be enabled when needed.

**Comment by mwtian** [comment]
> Overall, it looks good. This PR seems trying to fix the issue in the application layer. Do you think it's still sufficient if we fix it in pubsub layer? Or do you think it's worth fixing it there? My original feeling is that maybe we need to make pubsub robust anyway.

Yes, we will improve the robustness of pubsub soon. But the change for importer is needed to reduce the number of Python threads, and allow forking to work. Tolerating lost export notification is just a side effect.

**Review by fishbone — APPROVED** [review]

File: src/ray/common/ray_config_def.h (hunk 3 above)
Comment (hauntsaninja) [reply src/ray/common/ray_config_def.h:328]: Note that `GRPC_ENABLE_FORK_SUPPORT` can cause hangs, so definitely don't set this true by default :-)

Let me know in #openai-anyscale if you need more details
