### PR TITLE
[Core] PushManager for reliable broadcast

### LINKED ISSUE #9432: High raylet memory usage during object broadcast
I am unable, on a manual local cluster, to sync a large shared memory numpy arrays after they gets to a certain size. I am unsure if this id due to my config, so I created the below script which recreates my issue.

In the code below, this can toggle between a non-issue and issue. Is that expected with the change in array size in this manner?
```
# THIS WORKS FINE, no problem, used very little memory on host
#feature_values = np.random.random((int(5e4),500)).astype(np.float32)
#feature_values = np.random.random((int(5e5),500)).astype(np.float32)
# This attempts to use well over 100gb in the RAYLET process
feature_values = np.random.random((int(5e6),500)).astype(np.float32)
```

Essentially, once my shared memory numpy array gets past a certain size, the raylet process, while shipping to nodes, appears to grow to well over 100gb in memory, prob over 200, until a crash. If a node begins to help in shipping after it gets the object it too then creates a massive raylet process which faces the same issues.

(Note pic was taken during the run, not at end, the RAYLET ram usage went to 100% and began to fill swap entirely as well)
cluster_raylet_memory_issue

_Other issues I notice but are consistent and don't affect the memory issue. mentioned in case they point to other issues:_
- Number of workers in new version of ray, 0.8.6, seems to be some very large value for some reason, this is probably unrelated but wanted to mention
- I notice in dashboard some workers flash on and off, they seem to work fine, but the dashboard keeps adding and removing or never showing some workers.

Recreation script, with terminal output from crash:
https://gist.github.com/DMTSource/b50aeffde22b51bb82019d9b3e84f921

ray version: 0.8.6 (also tried on snapshot for 0.9.0.dev0 as requested, i've experience this issue across 0.8.4 and 0.8.5 if I recall...)
pd version: 1.0.1
np version: 1.18.1
python version 3.7.4
ubuntu 14.04

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Previous versions of Ray did not limit the number of outstanding object pushes that can be in flight at once. This can result in OOM if a node is broadcasting an object to a large number of other nodes. In addition, the larger number of in-flight RPC events leads to event loop starvation / heartbeat timeouts.

This PR addresses the issues by adding admission control and tuning the broadcast constants. Specifically,
- We limit the number of outstanding object push bytes to 2GB per raylet by default. This is implemented in the `PushManager` class.
- The chunk size of pushes is raised from 1MB to 5MB, which reduces the number of messages by 5x.

The fix can be verified by running the following script on a m4.16xl machine:
https://gist.github.com/ericl/a72f0c11508b9b599a82fcc0afff9c80

It finishes in about 1 minute with this patch applied; without this patch you will observe "heartbeat timeout" after a couple minutes. Memory usage is steady with the patch (<10GB for all raylets); without the patch raylet memory spikes to tens of GB.

### Future work
- It is still sometimes possible to see heartbeat timeouts even after this patch, which should probably be fixed as a separate issue (https://github.com/ray-project/ray/issues/11624). I sometimes observed timeouts with a 10GB window, and so lowered it to 2GB (I didn't see any meaningful perf difference between a 1GB and 10GB send window when testing on a single node).
- We should add the repro script to release tests.
- Solve the duplicate push issue (needs debugging).
- Performance evaluation of constants for tuning.

## Related issue number

Closes https://github.com/ray-project/ray/issues/9432
## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by ericl** [comment]
cc @danyangz @stephanie-wang @rkooo567

**Comment by ericl** [comment]
Have a follow-up PR to remove the repeated push logic: https://github.com/ray-project/ray/pull/11874/files

File: src/ray/common/ray_config_def.h [hunk 1]
```diff
@@ -187,13 +187,19 @@ RAY_CONFIG(int, object_manager_push_timeout_ms, 10000)
 
 /// The period of time that an object manager will wait before pushing the
 /// same object again to a specific object manager.
-RAY_CONFIG(int, object_manager_repeated_push_delay_ms, 60000)
+/// NOTE(ekl): this has been raised to avoid spurious repeated pushes.
+RAY_CONFIG(int, object_manager_repeated_push_delay_ms, 10 * 60 * 1000)
```
Comment (ericl) [inline src/ray/common/ray_config_def.h:191]: Will be removed entirely in a follow-up https://github.com/ray-project/ray/pull/11874/files

File: src/ray/object_manager/object_manager.cc [hunk 2]
```diff
@@ -400,6 +404,51 @@ void ObjectManager::HandleReceiveFinished(const ObjectID &object_id,
...
+                   << " max, remaining chunks: " << NumChunksRemaining();
+
+    // It is the last chunk and we don't need to track it any more.
+    if (++next_chunk_id_[push_id] >= max_chunks) {
+      next_chunk_id_.erase(push_id);
+      push_info_.erase(it++);
+      RAY_LOG(DEBUG) << "Push for " << push_id
+                     << " completed, remaining: " << NumPushesInFlight();
+    }
+    // Note that we don't advance the iterator until done with the push.
```
Comment (rkooo567) [inline src/ray/object_manager/object_manager.cc:448]: Doesn't this mean there can be starvation? Is `flat_hash_map` keeping the insertion order?

File: src/ray/object_manager/object_manager.cc [hunk 3]
```diff
@@ -478,28 +527,24 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &client_id) {
...
-                                  metadata_size, chunk_index, rpc_client);
-        if (!st.ok()) {
-          RAY_LOG(WARNING) << "Send object " << object_id << " chunk failed due to "
-                           << st.message() << ", chunk index " << chunk_index;
-        }
-      });
-    }
+    push_manager_->StartPush(push_id, num_chunks, [=](int64_t chunk_id) {
+      SendObjectChunk(push_id, object_id, owner_address, client_id, data_size,
+                      metadata_size, chunk_id, rpc_client,
```
Comment (rkooo567) [inline src/ray/object_manager/object_manager.cc:532]: I am not 100% sure if this is the case, but isn't capturing `rpc_client` will duplicate the connection? Why don't we call the `GetRpcClient` here?

File: src/ray/object_manager/object_manager.cc [hunk 4]
```diff
@@ -478,28 +527,24 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &client_id) {
...
+                      [=](const Status &status) { push_manager_->OnChunkComplete(); });
```
Comment (rkooo567) [inline src/ray/object_manager/object_manager.cc:533]: Don't we need any logic when `status != Status::OK()`?

**Review by rkooo567 — APPROVED** [review]
In general LGTM! I have only a few minor comments.

> I didn't see any meaningful perf difference between a 1GB and 10GB send window when testing on a single node

Isn't performance difference noticeable only when we benchmark in multi nodes? (Or did you mean single node with a cluster_utils)?

**Comment by rkooo567** [comment]
Btw, don't we need to do a similar thing to the side where it pulls objects? For example, if one node sends pull requests to many nodes, although the push is throttled, we can have a similar issue?

File: src/ray/object_manager/object_manager.cc (hunk 2 above)
Comment (ericl) [reply src/ray/object_manager/object_manager.cc:448]: Good point. Let me switch this to randomized round robin.

File: src/ray/object_manager/object_manager.cc [hunk 5]
```diff
@@ -70,6 +70,10 @@ ObjectManager::ObjectManager(asio::io_service &main_service, const NodeID &self_
   RAY_CHECK(config_.rpc_service_threads_number > 0);
   main_service_ = &main_service;
 
+  push_manager_.reset(new PushManager(std::max(
```
Comment (stephanie-wang) [inline src/ray/object_manager/object_manager.cc:73]: Can you add a /*var_name=*/ -style comment here?

File: src/ray/object_manager/object_manager.h [hunk 6]
```diff
@@ -97,6 +99,72 @@ class ObjectManagerInterface {
   virtual ~ObjectManagerInterface(){};
 };
 
+class PushManager {
+ public:
+  /// Manages rate limiting of outbound object pushes.
+
+  /// Create a push manager.
```
Comment (stephanie-wang) [inline src/ray/object_manager/object_manager.h:106]: Can you add a description of the argument? I.e., is it max chunks per raylet-raylet connection or max chunks across all receivers?

File: src/ray/object_manager/object_manager.h [hunk 7]
```diff
@@ -97,6 +99,72 @@ class ObjectManagerInterface {
...
+  PushManager(int64_t max_chunks_in_flight)
+      : max_chunks_in_flight_(max_chunks_in_flight) {
+    RAY_CHECK(max_chunks_in_flight_ > 0) << max_chunks_in_flight_;
+  };
+
+  /// Start pushing an object subject to max bytes in flight limit.
```
Comment (stephanie-wang) [inline src/ray/object_manager/object_manager.h:112]:
```suggestion
  /// Start pushing an object subject to max chunks in flight limit.
```

File: src/ray/object_manager/object_manager.h [hunk 8]
```diff
@@ -97,6 +99,72 @@ class ObjectManagerInterface {
...
+  void ScheduleRemainingPushes();
+
+  /// Pair of (num_chunks, chunk_send_fn).
+  typedef std::pair<int64_t, std::function<void(int64_t)>> PushInfo;
+
+  /// Max number of chunks in flight allowed.
+  const int64_t max_chunks_in_flight_;
+
+  /// Running count of chunks remaining.
+  int64_t chunks_remaining_ = 0;
```
Comment (stephanie-wang) [inline src/ray/object_manager/object_manager.h:156]: Could you clarify this description? At first I thought this was the number of chunks that could still be sent (max - in-flight).

**Review by stephanie-wang — DISMISSED** [review]
Nice! My main comment is about the callback structure for PushManager. I think it would be cleaner if we moved all of the push logic inside that class.

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Oops, see above review.

File: src/ray/object_manager/object_manager.cc [hunk 9]
```diff
@@ -478,28 +527,24 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &client_id) {
...
-        auto st = SendObjectChunk(push_id, object_id, owner_address, client_id, data_size,
-                                  metadata_size, chunk_index, rpc_client);
-        if (!st.ok()) {
-          RAY_LOG(WARNING) << "Send object " << object_id << " chunk failed due to "
-                           << st.message() << ", chunk index " << chunk_index;
-        }
-      });
-    }
+    push_manager_->StartPush(push_id, num_chunks, [=](int64_t chunk_id) {
+      SendObjectChunk(push_id, object_id, owner_address, client_id, data_size,
```
[the remark this answers is not in the document]
Comment (ericl) [reply src/ray/object_manager/object_manager.cc:531]: I wanted to isolate the dependency here so PushManager doesn't depend on object manager internals. This separation makes it easier to unit test.

File: src/ray/object_manager/object_manager.cc (hunk 3 above)
Comment (ericl) [reply src/ray/object_manager/object_manager.cc:532]: It's a shared_ptr so it's not copied.

File: src/ray/object_manager/object_manager.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (ericl) [reply src/ray/object_manager/object_manager.cc:531]: The follow-up PR is changing PushManager to be handling the callbacks for individual chunks. How about we wait on that one for cleaning this up?

For now, I think this design gives the best isolation between the components making it much easier to test PushManager.

File: src/ray/object_manager/object_manager.cc (hunk 4 above)
Comment (ericl) [reply src/ray/object_manager/object_manager.cc:533]: I have a TODO comment to handle, not needed for now.

File: src/ray/object_manager/object_manager.h [hunk 10]
```diff
@@ -97,6 +99,72 @@ class ObjectManagerInterface {
...
+
+  /// Running count of chunks in flight, used to limit progress of in_flight_pushes_.
+  int64_t chunks_in_flight_ = 0;
+
+  /// Tracks all pushes with chunk transfers in flight.
+  absl::flat_hash_map<UniqueID, PushInfo> push_info_;
+
+  /// Tracks progress of in flight pushes.
+  absl::flat_hash_map<UniqueID, int64_t> next_chunk_id_;
```
[the remark this answers is not in the document]
Comment (ericl) [reply src/ray/object_manager/object_manager.h:165]: Let's defer this to the next PR which adds more structure here.

File: src/ray/object_manager/object_manager.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/object_manager/object_manager.cc:531]: Sounds good. I guess we will need to mock out the RPC client in the next PR, but I think it's worthwhile to do so that the PushManager is self-contained.

**Review by ericl — COMMENTED** [review]
@rkooo567 @stephanie-wang comments addressed

**Review by stephanie-wang — APPROVED** [review]

**Comment by ericl** [comment]
> Btw, don't we need to do a similar thing to the side where it pulls objects? For example, if one node sends pull requests to many nodes, although the push is throttled, we can have a similar issue?

Yeah, it can happen still (@stephanie-wang can probably comment on this more).
