### PR TITLE
Fix ERROR logging not being printed to standard error

### LINKED ISSUE #9616: Ray error logs should be printed to stdout
### What is the problem?

c++ errors should be printed to the driver's stdout but aren't. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

Put a `RAY_LOG(ERROR) << "dfasdf";` in `CoreWorker::ExecuteTask` and in `NodeManager::HandleWorkerLeaseRequest`. Neither will will be printed. 

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

ERROR output was no longer printed to standard error.

## Related issue number

#9230

Closes #9616

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Review by wuisawesome — APPROVED** [review]

**Comment by mehrdadn** [comment]
CI on fork: https://github.com/mehrdadn/ray/actions/runs/178257004

File: src/ray/util/logging.cc [hunk 1]
```diff
@@ -205,9 +205,9 @@ void RayLog::StartRayLog(const std::string &app_name, RayLogLevel severity_thres
                                       std::ios_base::app | std::ios_base::binary);
   }
   for (int lvl = 0; lvl < NUM_SEVERITIES; ++lvl) {
-    google::SetStderrLogging(lvl);
     google::base::SetLogger(lvl, &stream_logger_singleton);
   }
+  google::SetStderrLogging(GetMappedSeverity(RayLogLevel::ERROR));
```
Comment (ericl) [inline src/ray/util/logging.cc:210]: Can we add a unit test that this doesn't break? Not sure how to trigger the error level log, maybe try putting an object that is too big or something?
