### PR TITLE
Remove Jenkins backend tests and add new long running stress test.

### LINKED ISSUE #4283: Jenkins test_0.py failing frequently.
Example failure below. We should figure out what is going wrong, remove this test, and if necessary replace it with a different test (that doesn't use `multi_node_docker_test.py`).

```
+ python3 /home/jenkins/workspace/Ray-PRB/ci/jenkins_tests/multi_node_docker_test.py --docker-image=a8d86a6b1152dbf326a631e6d11fcfa8b8e66c31e0a0e26872a7d3e166de9ed2 --num-nodes=5 --num-redis-shards=10 --test-script=/ray/ci/jenkins_tests/multi_node_tests/test_0.py
Starting head node with command:['docker', 'run', '-d', '--shm-size=1G', 'a8d86a6b1152dbf326a631e6d11fcfa8b8e66c31e0a0e26872a7d3e166de9ed2', 'ray', 'start', '--head', '--block', '--redis-port=6379', '--num-redis-shards=10', '--num-cpus=10', '--num-gpus=0', '--no-ui']
Starting worker node with command:['docker', 'run', '-d', '--shm-size=1G', '--shm-size=1G', 'a8d86a6b1152dbf326a631e6d11fcfa8b8e66c31e0a0e26872a7d3e166de9ed2', 'ray', 'start', '--block', '--redis-address=172.17.0.2:6379', '--num-cpus=10', '--num-gpus=0']
Starting worker node with command:['docker', 'run', '-d', '--shm-size=1G', '--shm-size=1G', 'a8d86a6b1152dbf326a631e6d11fcfa8b8e66c31e0a0e26872a7d3e166de9ed2', 'ray', 'start', '--block', '--redis-address=172.17.0.2:6379', '--num-cpus=10', '--num-gpus=0']
Starting worker node with command:['docker', 'run', '-d', '--shm-size=1G', '--shm-size=1G', 'a8d86a6b1152dbf326a631e6d11fcfa8b8e66c31e0a0e26872a7d3e166de9ed2', 'ray', 'start', '--block', '--redis-address=172.17.0.2:6379', '--num-cpus=10', '--num-gpus=0']
Starting worker node with command:['docker', 'run', '-d', '--shm-size=1G', '--shm-size=1G', 'a8d86a6b1152dbf326a631e6d11fcfa8b8e66c31e0a0e26872a7d3e166de9ed2', 'ray', 'start', '--block', '--redis-address=172.17.0.2:6379', '--num-cpus=10', '--num-gpus=0']
Multi-node docker test started at: 2019-03-05 20:14:32.577489
driver_locations: [3]
Starting driver with command /ray/ci/jenkins_tests/multi_node_tests/test_0.py.
STDOUT:

STDERR:
2019-03-06 04:14:33,158	WARNING worker.py:1381 -- WARNING: Not updating worker name since `setproctitle` is not installed. Install this with `pip install setproctitle` (or ray[debug]) to enable monitoring of worker processes.
2019-03-06 04:14:33,158	WARNING worker.py:1249 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-03-06 04:14:34,160	WARNING worker.py:1249 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-03-06 04:14:35,162	WARNING worker.py:1249 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?
2019-03-06 04:15:43,750	WARNING worker.py:1249 -- Some processes that the driver needs to connect to have not registered with Redis, so retrying. Have you run 'ray start' on this node?

Multi-node docker test ended at: 2019-03-05 20:15:44.920110
stop_node {'is_head': False, 'container_id': '9ac4665e3b19fc3253316ef7f6084d46db29ed9e16d788652e511689d9e0cb8a'}
RESULT: Test /ray/ci/jenkins_tests/multi_node_tests/test_0.py failed.
Build step 'Execute shell' marked build as failure
Setting commit status on GitHub for https://github.com/ray-project/ray/commit/ced48698126b6bfabba290e18ff63951d0730daa
Test FAILed.
Refer to this link for build results (access rights to CI server needed): 
https://amplab.cs.berkeley.edu/jenkins//job/Ray-PRB/12578/
Test FAILed.
Finished: FAILURE
```

### PR DESCRIPTION
**Pull request by robertnishihara**
This fixes #4283. It also removes almost all of the Jenkins backend tests. `test_0.py` doesn't really do anything interesting and is flaky. `remove_driver_test.py` should be covered by `test_multi_node.py`, and `many_driver_test.py` should be covered by the new stress test I added, which essentially creates drivers in an infinite loop.

I also removed the `multi_node_docker_test.py` file because that has been replaced by `cluster_utils.py`.

### CODE REVIEW

File: ci/jenkins_tests/run_multi_node_tests.sh [hunk 1]
```diff
@@ -14,6 +14,11 @@ ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE:-$0}")"; pwd)
 DOCKER_SHA=$($ROOT_DIR/../../build-docker.sh --output-sha --no-cache)
 echo "Using Docker image" $DOCKER_SHA
 
+######################## RAY BACKEND TESTS #################################
```
Comment (robertnishihara) [inline ci/jenkins_tests/run_multi_node_tests.sh]: I moved this to the front so I can see the Jenkins results more quickly, but will move back to the end before merging.

Comment (robertnishihara) [reply ci/jenkins_tests/run_multi_node_tests.sh]: On the other hand, it doesn't take very long I think, so maybe it's fine here.

**Review by pcmoritz — APPROVED** [review]
