### PR TITLE
[GCS FT] Mark job as finished for dead node

### LINKED ISSUE #23963: [Core][flaky-test] linux://python/ray/tests:test_usage_stats is flaky
### What happened + What you expected to happen

linux://python/ray/tests:test_usage_stats has been flaky with following errors:
```


=================================== FAILURES ===================================
--
  | __________________________ test_usage_lib_report_data __________________________
  |  
  | monkeypatch = <_pytest.monkeypatch.MonkeyPatch object at 0x7f591d758898>
  | shutdown_only = None
  | tmp_path = PosixPath('/tmp/pytest-of-root/pytest-3/test_usage_lib_report_data0')
  |  
  | @pytest.mark.skipif(
  | sys.platform == "win32",
  | reason="Test depends on runtime env feature not supported on Windows.",
  | )
  | def test_usage_lib_report_data(monkeypatch, shutdown_only, tmp_path):
  | with monkeypatch.context() as m:
  | m.setenv("RAY_USAGE_STATS_ENABLED", "1")
  | m.setenv("RAY_USAGE_STATS_REPORT_URL", "http://127.0.0.1:8000")
  | # Runtime env is required to run this test in minimal installation test.
  | ray.init(num_cpus=0, runtime_env={"pip": ["ray[serve]"]})
  | """
  | Make sure the generated data is following the schema.
  | """
  | cluster_metadata = ray_usage_lib.get_cluster_metadata(
  | ray.experimental.internal_kv.internal_kv_get_gcs_client(), num_retries=20
  | )
  | cluster_config_file_path = tmp_path / "ray_bootstrap_config.yaml"
  | cluster_config_file_path.write_text(
  | """
  | cluster_name: minimal
  | max_workers: 1
  | provider:
  | type: aws
  | region: us-west-2
  | availability_zone: us-west-2a
  | """
  | )
  | cluster_config_to_report = ray_usage_lib.get_cluster_config_to_report(
  | cluster_config_file_path
  | )
  | d = ray_usage_lib.generate_report_data(
  | cluster_metadata, cluster_config_to_report, 2, 2, 2
  | )
  | validate(instance=asdict(d), schema=schema)
  |  
  | """
  | Make sure writing to a file works as expected
  | """
  | client = ray_usage_lib.UsageReportClient()
  | temp_dir = Path(tmp_path)
  | client.write_usage_data(d, temp_dir)
  |  
  | wait_for_condition(lambda: file_exists(temp_dir))
  |  
  | """
  | Make sure report usage data works as expected
  | """
  |  
  | @ray.remote(num_cpus=0, runtime_env={"pip": ["ray[serve]"]})
  | class ServeInitator:
  | def __init__(self):
  | # Start the ray serve server to verify requests are sent
  | # to the right place.
  | from ray import serve
  |  
  | serve.start()
  |  
  | @serve.deployment(ray_actor_options={"num_cpus": 0})
  | async def usage(request):
  | body = await request.json()
  | if body == asdict(d):
  | return True
  | else:
  | return False
  |  
  | usage.deploy()
  |  
  | def ready(self):
  | pass
  |  
  | # We need to start a serve with runtime env to make this test
  | # work with minimal installation.
  | s = ServeInitator.remote()
  | >           ray.get(s.ready.remote())
  |  
  | /ray/python/ray/tests/test_usage_stats.py:444:
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  | /ray/python/ray/_private/client_mode_hook.py:105: in wrapper
  | return func(*args, **kwargs)
  | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
  |  
  | object_refs = [ObjectRef(16310a0f0a45af5cf3019b4336c3332f5b1656030100000001000000)]
  |  
  | @PublicAPI
  | @client_mode_hook(auto_init=True)
  | def get(
  | object_refs: Union[ray.ObjectRef, List[ray.ObjectRef]],
  | *,
  | timeout: Optional[float] = None,
  | ) -> Union[Any, List[Any]]:
  | """Get a remote object or a list of remote objects from the object store.
  |  
  | This method blocks until the object corresponding to the object ref is
  | available in the local object store. If this object is not in the local
  | object store, it will be shipped from an object store that has it (once the
  | object has been created). If object_refs is a list, then the objects
  | corresponding to each object in the list will be returned.
  |  
  | Ordering for an input list of object refs is preserved for each object
  | returned. That is, if an object ref to A precedes an object ref to B in the
  | input list, then A will precede B in the returned list.
  |  
  | This method will issue a warning if it's running inside async context,
  | you can use ``await object_ref`` instead of ``ray.get(object_ref)``. For
  | a list of object refs, you can use ``await asyncio.gather(*object_refs)``.
  |  
  | Args:
  | object_refs: Object ref of the object to get or a list of object refs
  | to get.
  | timeout (Optional[float]): The maximum amount of time in seconds to
  | wait before returning.
  |  
  | Returns:
  | A Python object or a list of Python objects.
  |  
  | Raises:
  | GetTimeoutError: A GetTimeoutError is raised if a timeout is set and
  | the get takes longer than timeout to return.
  | Exception: An exception is raised if the task that created the object
  | or that created one of the objects raised an exception.
  | """
  | worker = global_worker
  | worker.check_connected()
  |  
  | if hasattr(worker, "core_worker") and worker.core_worker.current_actor_is_asyncio():
  | global blocking_get_inside_async_warned
  | if not blocking_get_inside_async_warned:
  | logger.warning(
  | "Using blocking ray.get inside async actor. "
  | "This blocks the event loop. Please use `await` "
  | "on object ref with asyncio.gather if you want to "
  | "yield execution to the event loop instead."
  | )
  | blocking_get_inside_async_warned = True
  |  
  | with profiling.profile("ray.get"):
  | is_individual_id = isinstance(object_refs, ray.ObjectRef)
  | if is_individual_id:
  | object_refs = [object_refs]
  |  
  | if not isinstance(object_refs, list):
  | raise ValueError(
  | "'object_refs' must either be an object ref "
  | "or a list of object refs."
  | )
  |  
  | # TODO(ujvl): Consider how to allow user to retrieve the ready objects.
  | values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  | for i, value in enumerate(values):
  | if isinstance(value, RayError):
  | if isinstance(value, ray.exceptions.ObjectLostError):
  | worker.core_worker.dump_object_store_memory_usage()
  | if isinstance(value, RayTaskError):
  | raise value.as_instanceof_cause()
  | else:
  | >                       raise value
  | E                       ray.exceptions.RuntimeEnvSetupError: Failed to setup runtime environment.
  | E                       Could not create the actor because its associated runtime env failed to be created.
  | E                       Traceback (most recent call last):
  | E                         File "/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 388, in _create_runtime_env_with_retry
  | E                           runtime_env_setup_task, timeout=setup_timeout_seconds
  | E                         File "/opt/miniconda/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
  | E                           return fut.result()
  | E                         File "/ray/python/ray/dashboard/modules/runtime_env/runtime_env_agent.py", line 297, in _setup_runtime_env
  | E                           uri, runtime_env, context, logger=per_job_logger
  | E                         File "/ray/python/ray/_private/runtime_env/pip.py", line 440, in create
  | E                           return await task
  | E                         File "/ray/python/ray/_private/runtime_env/pip.py", line 431, in _create_for_hash
  | E                           await PipProcessor(target_dir, runtime_env, logger)
  | E                         File "/ray/python/ray/_private/runtime_env/pip.py", line 331, in _run
  | E                           await self._create_or_get_virtualenv(path, exec_cwd, logger)
  | E                         File "/ray/python/ray/_private/runtime_env/pip.py", line 273, in _create_or_get_virtualenv
  | E                           await check_output_cmd(create_venv_cmd, logger=logger, cwd=cwd, env=env)
  | E                         File "/ray/python/ray/_private/runtime_env/utils.py", line 102, in check_output_cmd
  | E                           proc.returncode, cmd, output=stdout, cmd_index=cmd_index
  | E                       ray._private.runtime_env.utils.SubprocessCalledProcessError: Run cmd[7] failed with the following details.
  | E                       Command '['/opt/miniconda/bin/python3', '-m', 'virtualenv', '--app-data', '/tmp/ray/session_2022-04-15_03-50-51_422041_2132/runtime_resources/pip/5f03e216e7a7205e2f91d630e44c9c6e5040e702/virtualenv_app_data', '--reset-app-data', '--no-periodic-update', '--system-site-packages', '--no-download', '/tmp/ray/session_2022-04-15_03-50-51_422041_2132/runtime_resources/pip/5f03e216e7a7205e2f91d630e44c9c6e5040e702/virtualenv']' returned non-zero exit status 1.
  | E                       Last 50 lines of stdout:
  | E                           RuntimeError: failed to build image setuptools, pip because:
  | E                           Traceback (most recent call last):
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
  | E                               installer.install(creator.interpreter.version_info)
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 35, in install
  | E                               self._uninstall_previous_version()
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 151, in _uninstall_previous_version
  | E                               dist_name = self._dist_info.stem.split("-")[0]
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 115, in _dist_info
  | E                               raise RuntimeError(msg)  # pragma: no cover
  | E                           RuntimeError: no .dist-info at /tmp/ray/session_2022-04-15_03-50-51_422041_2132/runtime_resources/pip/5f03e216e7a7205e2f91d630e44c9c6e5040e702/virtualenv_app_data/wheel/3.6/image/1/CopyPipInstall/setuptools-59.6.0-py3-none-any, has pkg_resources, setuptools
  | E
  | E                           Traceback (most recent call last):
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 57, in _install
  | E                               installer.install(creator.interpreter.version_info)
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 35, in install
  | E                               self._uninstall_previous_version()
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 151, in _uninstall_previous_version
  | E                               dist_name = self._dist_info.stem.split("-")[0]
  | E                             File "/opt/miniconda/lib/python3.6/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 115, in _dist_info
  | E                               raise RuntimeError(msg)  # pragma: no cover
  | E                           RuntimeError: no .dist-info at /tmp/ray/session_2022-04-15_03-50-51_422041_2132/runtime_resources/pip/5f03e216e7a7205e2f91d630e44c9c6e5040e702/virtualenv_app_data/wheel/3.6/image/1/CopyPipInstall/pip-21.3.1-py3-none-any, has pip
  |  
  | /ray/python/ray/worker.py:1812: RuntimeEnvSetupError

```

@rkooo567 @jjyao could help debug or triage?

### Versions / Dependencies

latest master

### Reproduction script

check buildkite or flaky test dashboard.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### LINKED ISSUE #39947: [Core][GCS FT] The ray list jobs command experiences significant delays after the head Pod recovers from a failure
### What happened + What you expected to happen

https://ray-distributed.slack.com/archives/C01DLHZHRBJ/p1695265415103039

### Versions / Dependencies

2.7.0

### Reproduction script

1. Create a RayCluster with GCS FT
2. Use `ray job submit` to submit some jobs
3. Delete the head Pod
4. Run `ray list jobs` in the head Pod after it recovers from the failure

I cannot reproduce this consistently. I need to try 10x times to make it happen.

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by jonathan-anyscale**
## Why are these changes needed?
The issue is `ray list nodes` is timeout before it managed to return list of all nodes. The issue is caused by the timeout when GcsJobManager tried to get pending tasks from the driver of node which already dead (killed head nodes), which is 2 mins timeout to confirm if the node is dead. The solution we proposed is when node is dead, we mark all the job submitted to that head node as "finished", so the RPC calls for the pending tasks will only applied to drivers of current head node which most likely to be alive => resulting no timeout.

## Related issue number
Closes #23963
Closes #39947

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by rkooo567 — COMMENTED** [review]
Can u add e2e tests with test_gcs_fault_tolerance? 1. Start a job long running 2. Restart the head node 3. Verify the previous one is dead with correct error

File: src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc [hunk 1]
```diff
@@ -553,6 +553,93 @@ TEST_F(GcsJobManagerTest, TestPreserveDriverInfo) {
...
+  }
+
+  // Remove node and then check that the job is dead.
+  auto address = all_job_info_reply.job_info_list().Get(0).driver_address();
+  auto node_id = NodeID::FromBinary(address.raylet_id());
+  
+  std::promise<bool> on_node_dead_promise;
+  io_service_.post(
+    [&gcs_job_manager, node_id, &on_node_dead_promise]() {
+      gcs_job_manager.OnNodeDead(node_id);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc:614]: you don't need to call it within io service? You can just call it in the current thread.

File: src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc [hunk 2]
```diff
@@ -553,6 +553,90 @@ TEST_F(GcsJobManagerTest, TestPreserveDriverInfo) {
...
+  for (auto job_info : all_job_info_reply.job_info_list()) {
+    ASSERT_TRUE(!job_info.is_dead());
+  }
+
+  // Remove node and then check that the job is dead.
+  auto address = all_job_info_reply.job_info_list().Get(0).driver_address();
+  auto node_id = NodeID::FromBinary(address.raylet_id());
+  gcs_job_manager.OnNodeDead(node_id);
+
+  // Test get all jobs with limit larger than the number of jobs.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc:612]: What does this comment mean?

File: src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc [hunk 3]
```diff
@@ -553,6 +553,90 @@ TEST_F(GcsJobManagerTest, TestPreserveDriverInfo) {
...
+    gcs_job_manager.HandleGetAllJobInfo(
+        all_job_info_request2,
+        &all_job_info_reply2,
+        [&all_job_info_promise2](Status, std::function<void()>, std::function<void()>) {
+          all_job_info_promise2.set_value(true);
+        });
+    all_job_info_promise2.get_future().get();
+
+    auto job_info1 = all_job_info_reply2.job_info_list().Get(0);
+    auto job_info2 = all_job_info_reply2.job_info_list().Get(1);
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc:626]: These two variables are not used?

File: python/ray/tests/test_gcs_fault_tolerance.py [hunk 4]
```diff
@@ -975,6 +976,62 @@ def test_redis_logs(external_redis):
...
+def test_job_finished_after_gcs_server_restart(ray_start_regular_with_external_redis):
+    gcs_address = ray._private.worker.global_worker.gcs_client.address
+    client = JobSubmissionClient(gcs_address)
+
+    # submit job
+    job_id = client.submit_job(
+        entrypoint="python -c 'import ray; ray.init(); print(ray.cluster_resources());'"
+    )
+    # restart the gcs server
+    ray._private.worker._global_node.kill_gcs_server()
```
Comment (jjyao) [inline python/ray/tests/test_gcs_fault_tolerance.py:998]: Killing gcs won't mark the node as dead, is this what we want to test?

File: src/ray/gcs/gcs_server/gcs_job_manager.cc [hunk 5]
```diff
@@ -297,5 +302,28 @@ std::shared_ptr<rpc::JobConfig> GcsJobManager::GetJobConfig(const JobID &job_id)
   return it->second;
 }
 
+void GcsJobManager::OnNodeDead(const NodeID &node_id) {
+  RAY_LOG(INFO) << "Node " << node_id
```
[the remark this answers is not in the document]
Comment (jonathan-anyscale) [reply src/ray/gcs/gcs_server/gcs_job_manager.cc:306]: the other `OnNodeDead` wrote it on INFO instead of DEBUG

File: src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc (hunk 2 above)
Comment (jonathan-anyscale) [reply src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc:612]: it's not suppose to be there, will remove

File: python/ray/tests/test_gcs_fault_tolerance.py [hunk 6]
```diff
@@ -975,6 +976,62 @@ def test_redis_logs(external_redis):
...
+        )
+    ],
+    indirect=True,
+)
+def test_job_finished_after_gcs_server_restart(ray_start_regular_with_external_redis):
+    gcs_address = ray._private.worker.global_worker.gcs_client.address
+    client = JobSubmissionClient(gcs_address)
+
+    # submit job
+    job_id = client.submit_job(
```
Comment (rkooo567) [inline python/ray/tests/test_gcs_fault_tolerance.py:994]:
```
set the gcs_rpc_server_reconnect_timeout_s = ?
submit a long running job with 1 head node
cluster.remove_node(head)
Wait until driver pid is gone
Restart head node, cluster.add_node()
make sure driver is dead
```

File: src/ray/gcs/gcs_server/gcs_job_manager.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_job_manager.cc:306]: I think INFO sounds okay because frequency is low

File: src/ray/gcs/gcs_server/gcs_job_manager.cc [hunk 7]
```diff
@@ -297,5 +302,28 @@ std::shared_ptr<rpc::JobConfig> GcsJobManager::GetJobConfig(const JobID &job_id)
...
+
+  auto on_done = [this, node_id](const absl::flat_hash_map<JobID, JobTableData> &result) {
+    // If job is not dead and from driver in current node, then mark it as finished
+    for (auto &data : result) {
+      if (!data.second.is_dead() &&
+          NodeID::FromBinary(data.second.driver_address().raylet_id()) == node_id) {
+        RAY_LOG(DEBUG) << "Marking job: " << data.first << " as finished";
+        MarkJobAsFinished(data.second, [data](Status status) {
+          if (!status.ok()) {
+            RAY_LOG(WARNING) << "Failed to mark job as finished";
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_job_manager.cc:317]: Add status to logs 

<< "Failed to mark job as finished. Status: " << status

File: src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc [hunk 8]
```diff
@@ -553,6 +553,90 @@ TEST_F(GcsJobManagerTest, TestPreserveDriverInfo) {
...
+
+    bool job_condition = true;
+    // job1 from the current node should dead, while job2 is still alive
+    for (auto job_info : all_job_info_reply2.job_info_list()) {
+      auto job_node_id = NodeID::FromBinary(job_info.driver_address().raylet_id());
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/test/gcs_job_manager_test.cc:631]: Can you also verify the other one is not dead?

**Review by rkooo567 — APPROVED** [review]
LGTM. Need a little bit more modification to tests before merging it.

File: src/ray/gcs/gcs_server/gcs_job_manager.cc (hunk 5 above)
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_job_manager.cc:306]: Not a big issue but I feel as long as it's printed out in GcsNodeManager it should be enough. No need to print repeatedly in each GcsXXManager::OnNodeDead

File: python/ray/tests/test_gcs_fault_tolerance.py (hunk 6 above)
Comment (jonathan-anyscale) [reply python/ray/tests/test_gcs_fault_tolerance.py:998]: changed to this flow, but still failing when trying to check if job is marked as FAILED after raylet killed, so might need help on that

Comment (jjyao) [reply python/ray/tests/test_gcs_fault_tolerance.py:998]: I think instead of head_node.kill_raylet, we can kill the entire head node by `cluster.remote_node(head_node)` and then restart the head node by `cluster.add_node()`

File: src/ray/gcs/gcs_server/gcs_job_manager.cc [hunk 9]
```diff
@@ -218,11 +218,16 @@ void GcsJobManager::HandleGetAllJobInfo(rpc::GetAllJobInfoRequest request,
         auto client = core_worker_clients_.GetOrConnect(data.second.driver_address());
         std::unique_ptr<rpc::NumPendingTasksRequest> request(
             new rpc::NumPendingTasksRequest());
+        RAY_LOG(DEBUG) << "SendNumPendingTask: "
+                       << WorkerID::FromBinary(data.second.driver_address().worker_id());
         client->NumPendingTasks(
             std::move(request),
-            [reply, i, num_processed_jobs, try_send_reply](
+            [data, reply, i, num_processed_jobs, try_send_reply](
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_job_manager.cc:225]: Instead of capturing the entire data, let's just capture worker_id

**Comment by rkooo567** [comment]
lmk when it is ready to be merged

File: src/ray/gcs/gcs_server/gcs_job_manager.cc [hunk 10]
```diff
@@ -218,11 +218,17 @@ void GcsJobManager::HandleGetAllJobInfo(rpc::GetAllJobInfoRequest request,
...
-            [reply, i, num_processed_jobs, try_send_reply](
-                const Status &status,
-                const rpc::NumPendingTasksReply &num_pending_tasks_reply) {
+            [worker_id = data.second.driver_address().worker_id(),
+             reply,
+             i,
+             num_processed_jobs,
+             try_send_reply](const Status &status,
+                             const rpc::NumPendingTasksReply &num_pending_tasks_reply) {
+              RAY_LOG(DEBUG) << "SendNumPendingTaskReply: " << worker_id;
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_job_manager.cc:227]:
```suggestion
              RAY_LOG(DEBUG) << "Received NumPendingTasksReply from worker " << worker_id;
```

**Review by jjyao — APPROVED** [review]
