### PR TITLE
[core] Fix gcs healthch manager crash when node is removed by node manager.

### LINKED ISSUE #31717: [core] long_running_node_failures is flaky
### What happened + What you expected to happen

Failed on 12/25/22 and 1/8/23 but succeeded on 1/2 and 1/16.

https://console.anyscale.com/o/anyscale-internal/projects/prj_FKRmeV5pA6X72aVscFALNC32/clusters/ses_z54reexyaa99sy39frq4vx292h?command-history-section=command_history

```
2023-01-08 10:04:23,614 WARNING utils.py:1422 -- Unable to connect to GCS at 172.31.130.238:56704. Check that (1) Ray GCS with matching version started successfully at the specified address, and (2) there is no firewall setting preventing access.
[2023-01-08 10:05:08,491 E 786 1987] gcs_rpc_client.h:532: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.
```

### Versions / Dependencies

3.0dev

### Reproduction script

long_running_node_failures

### Issue Severity

None

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
The root cause is because the data structure is deleted, but call backs is not canceled and got executed. This PR simplify the life model and make it the way gRPC works. We only delete the structure after gRPC OnDone is called.

In the shortcut, according to the doc https://github.com/grpc/proposal/blob/master/L67-cpp-callback-api.md#unary-rpc-shortcuts , OnDone will call the callback function.

A better model is needed here. The code will be changed once we update the threading model in gRPC.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/test/gcs_health_check_manager_test.cc [hunk 1]
```diff
@@ -30,6 +34,20 @@ using namespace boost;
 #include "gtest/gtest.h"
 #include "ray/gcs/gcs_server/gcs_health_check_manager.h"
 
+int GetFreePort() {
```
Comment (iycheng) [inline src/ray/gcs/gcs_server/test/gcs_health_check_manager_test.cc:37]: fun fact: it's generated by chatgpt

**Comment by iycheng** [comment]
still failed in testing env

**Comment by iycheng** [comment]
```
*** SIGABRT received at time=1674687639 on cpu 0 ***
PC: @     0x7f0fd2f8400b  (unknown)  raise
    @     0x7f0fd4fa47b5        208  absl::lts_20220623::WriteFailureInfo()
    @     0x7f0fd4fa44f8         64  absl::lts_20220623::AbslFailureSignalHandler()
    @     0x7f0fd349f420       4032  (unknown)
    @     0x7f0fd31f838c        224  (unknown)
    @     0x7f0fd578f5ca        400  grpc::GenericDeserialize<>()
    @     0x7f0fd578eb5c        128  grpc::internal::CallOpRecvMessage<>::FinishOp()
    @     0x7f0fd578d63d         64  grpc::internal::CallOpSet<>::FinalizeResult()
    @     0x7f0fd5791ef8        256  grpc::internal::CallbackWithStatusTag::Run()
    @     0x7f0fd49c1bcc         48  grpc::(anonymous namespace)::CallbackAlternativeCQ::Ref()::{lambda()#1}::__invoke()
    @     0x7f0fd3d184ec         96  grpc_core::(anonymous namespace)::ThreadInternalsPosix::ThreadInternalsPosix()::{lambda()#1}::__invoke()
    @     0x7f0fd3493609  (unknown)  start_thread
```

File: src/ray/gcs/gcs_server/gcs_health_check_manager.h [hunk 2]
```diff
@@ -121,14 +110,14 @@ class GcsHealthCheckManager {
     NodeID node_id_;
 
     // Whether the health check has stopped.
-    std::shared_ptr<bool> stopped_;
+    bool stopped_ = false;
 
     /// gRPC related fields
     std::unique_ptr<::grpc::health::v1::Health::Stub> stub_;
 
     // The context is used in the gRPC callback which is in another
```
Comment (scv119) [inline src/ray/gcs/gcs_server/gcs_health_check_manager.h:118]: comments need update

File: src/ray/gcs/gcs_server/gcs_health_check_manager.cc [hunk 3]
```diff
@@ -75,27 +79,23 @@ std::vector<NodeID> GcsHealthCheckManager::GetAllNodes() const {
 void GcsHealthCheckManager::HealthCheckContext::StartHealthCheck() {
   using ::grpc::health::v1::HealthCheckResponse;
 
-  context_ = std::make_shared<grpc::ClientContext>();
+  // Reset the context/request/response for the next request.
+  context_.~ClientContext();
+  new (&context_) grpc::ClientContext();
```
Comment (scv119) [inline src/ray/gcs/gcs_server/gcs_health_check_manager.cc:84]: if we make context_ an pointer or unique_ptr, would it make it more nature?

**Review by scv119 — COMMENTED** [review]
mostly just nits!

**Review by scv119 — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_health_check_manager.cc (hunk 3 above)
Comment (iycheng) [reply src/ray/gcs/gcs_server/gcs_health_check_manager.cc:84]: It actually doesn't matter any difference I think since at the same time, only one in-flight request will be there per node.
I did this just following what gRPC did (https://sourcegraph.com/github.com/grpc/grpc/-/blob/test/cpp/qps/client_sync.cc?L189:26) and I think this is for performance (allocate on stack vs allocate on heap)(perf is not very important here, so I think no big difference.)
