### PR TITLE
[core] Autoscaler v2 consistency fix [1/2]

### LINKED ISSUE #36926: [Autoscaler] starts extra workers than necessary
### What happened + What you expected to happen

Autoscaler started extra worker while they are not needed.

From the following log, I believe it may have race condition on reading 
- pending tasks
- usage

Our tasks use 1 CPU, 30G memory, the worker has 120GB memory

At beginning, autoscaler started 12 workers correctly. (4 tasks each worker and 48 tasks)

Then, the moment the worker started, it seems  there is a race condition on the usage and pending tasks.
e.g.
Usage:
 10.0/176.0 CPU # 10 task is runing
so, there should be 38 (48-10) tasks pending.

However, the autoscaler think there are still 48 task pending and start 3 extra workers for them

```
======== Autoscaler status: 2023-06-28 14:34:29.072047 ========
Node status
---------------------------------------------------------------
Healthy:
 11 large-group
 1 head-group
Pending:
 192.168.26.101: large-group, waiting
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Usage:
 10.0/176.0 CPU
 0.0/1100.0 large-group
 279.40GiB/1.22TiB memory
 0.0/1100.0 no_gpu
 9.52KiB/181.94GiB object_store_memory

Demands:
 {'CPU': 1.0, 'memory': 30000000000.0}: 48+ pending tasks/actors
2023-06-28 14:34:29,073	INFO autoscaler.py:1374 -- StandardAutoscaler: Queue 3 new nodes for launch
2023-06-28 14:34:29,073	INFO node_launcher.py:166 -- BaseNodeLauncher: Got 3 nodes to launch.
2023-06-28 14:34:29,073	INFO node_launcher.py:166 -- BaseNodeLauncher: Launching 3 nodes, type large-group.
2023-06-28 14:34:29,074	INFO node_provider.py:287 -- Autoscaler is submitting the following patch to RayCluster ray in namespace pm-wuy-research.
2023-06-28 14:34:29,074	INFO node_provider.py:290 -- [{'op': 'replace', 'path': '/spec/workerGroupSpecs/0/replicas', 'value': 3}]
2023-06-28 14:34:29,119	INFO autoscaler.py:471 -- The autoscaler took 0.112 seconds to complete the update iteration.
2023-06-28 14:34:29,120	INFO monitor.py:425 -- :event_summary:Resized to 176 CPUs.
2023-06-28 14:34:29,120	INFO monitor.py:425 -- :event_summary:Adding 3 node(s) of type large-group.
2023-06-28 14:34:34,184	INFO node_provider.py:240 -- Listing pods for RayCluster ray in namespace pm-wuy-research at pods resource version >= 42434271.
2023-06-28 14:34:34,210	INFO node_provider.py:258 -- Fetched pod data at resource version 42434271.
2023-06-28 14:34:34,210	INFO autoscaler.py:148 -- The autoscaler took 0.065 seconds to fetch the list of non-terminated nodes.
2023-06-28 14:34:34,211	INFO autoscaler.py:427 -- 
```

### Versions / Dependencies

ray 2.5.1

### Reproduction script

normal setup

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by vitsai**
Separating out the fix for v2 from the [fix](https://github.com/ray-project/ray/pull/40254) for v1. Note the earlier PR originally contained both, but is now the second in the stack

## Related issue number

https://github.com/ray-project/ray/issues/36926

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 1]
```diff
@@ -184,13 +179,56 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
...
 
+void GcsAutoscalerStateManager::UpdateResourceLoadAndUsage(
+    const rpc::ResourcesData &data) {
+  NodeID node_id = NodeID::FromBinary(data.node_id());
+  auto iter = node_resource_info_.find(node_id);
+  if (iter == node_resource_info_.end()) {
+    iter = node_resource_info_
+               .emplace(node_id, std::make_pair(absl::Now(), rpc::ResourcesData()))
+               .first;
+  }
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:190]: gcs node manager should be the SOT of whether a node is part of the cluster or not: we should just ignore the message if the node is not in gcs node manager.

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 2]
```diff
@@ -262,8 +234,13 @@ void GcsResourceManager::HandleGetAllResourceUsage(
     reply->mutable_resource_usage_data()->CopyFrom(batch);
   }
 
-  RAY_DCHECK(static_cast<size_t>(reply->resource_usage_data().batch().size()) ==
-             num_alive_nodes_);
+  if (static_cast<size_t>(reply->resource_usage_data().batch().size()) ==
```
Comment (rickyyx) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:237]: is this intentional

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 1 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:190]: should we just initialize the data with `OnNodeAdd`?

Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc]: Yeah

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 2 above)
Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:237]: yeah, they might be different and we don't want to crash

File: python/ray/autoscaler/_private/fake_multi_node/node_provider.py [hunk 3]
```diff
@@ -650,6 +650,7 @@ def create_node(
         self, node_config: Dict[str, Any], tags: Dict[str, str], count: int
     ) -> Optional[Dict[str, Any]]:
         resources = self._head_resources
+        time.sleep(20)
```
Comment (rickyyx) [inline python/ray/autoscaler/_private/fake_multi_node/node_provider.py:653]: we should revert this before merging.

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 4]
```diff
@@ -214,6 +249,15 @@ void GcsAutoscalerStateManager::GetNodeStates(
     node_state_proto->set_node_ip_address(gcs_node_info.node_manager_address());
     node_state_proto->set_instance_type_name(gcs_node_info.instance_type_name());
 
+    // The only node state we use from GcsNodeInfo is dead.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:252]:
```suggestion
    // The only node state we use from GcsNodeInfo is dead state.
```

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 5]
```diff
@@ -224,37 +268,43 @@ void GcsAutoscalerStateManager::GetNodeStates(
         gcs_node_info.state_snapshot().node_activity());
 
     // The node is alive. We need to check if the node is idle.
-    auto const &node_resource_data = cluster_resource_manager_.GetNodeResources(
-        scheduling::NodeID(node_state_proto->node_id()));
-    if (node_resource_data.is_draining) {
+    auto const node_resource_iter =
+        node_resource_info_.find(NodeID::FromBinary(node_state_proto->node_id()));
+
+    // The node has been added to GcsInfo but we are missing reporting for it. Ignore.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:274]:
```suggestion
    // The node has been added to GcsNodeInfo but we are missing reporting for it. Ignore.
```

**Review by rickyyx — APPROVED** [review]
LGTM - make sure we also run some release tests for this.

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 6]
```diff
@@ -224,37 +268,43 @@ void GcsAutoscalerStateManager::GetNodeStates(
...
+    if (node_resource_iter == node_resource_info_.end()) {
+      return;
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:276]: I'm a bit concerned about this: if we early return, the proto will contain all the default values. Is that correct? How does the current node handle this case?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 7]
```diff
@@ -98,6 +100,7 @@ void GcsResourceManager::HandleGetAllAvailableResources(
     rpc::GetAllAvailableResourcesReply *reply,
     rpc::SendReplyCallback send_reply_callback) {
   auto local_scheduling_node_id = scheduling::NodeID(local_node_id_.Binary());
+  // TODO(vitsai) surgery on this thing
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:103]: make the TODO more descriptive

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 8]
```diff
@@ -233,6 +204,7 @@ void GcsResourceManager::HandleGetAllResourceUsage(
     if (cluster_task_manager_) {
       // Fill the gcs info when gcs actor scheduler is enabled.
       rpc::ResourcesData gcs_resources_data;
+      // TODO(vitsai) away with ye, harlot!
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:207]: ?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 9]
```diff
@@ -181,44 +184,12 @@ void GcsResourceManager::HandleReportResourceUsage(
...
-                                      demand.backlog_size());
-  }
-}
-
 void GcsResourceManager::HandleGetAllResourceUsage(
     rpc::GetAllResourceUsageRequest request,
     rpc::GetAllResourceUsageReply *reply,
     rpc::SendReplyCallback send_reply_callback) {
+  // This is a hack. We use the stale but less inconsistent resource info
+  // from GCS autoscaler state manager instead of our local resource info.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:192]: Where do you use the gcs autoscaler state manager?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 2 above)
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:237]: Comment on when they can be different

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 10]
```diff
@@ -283,6 +260,8 @@ void GcsResourceManager::UpdateFromResourceCommand(const rpc::ResourcesData &dat
 
 void GcsResourceManager::UpdateNodeResourceUsage(const NodeID &node_id,
                                                  const rpc::ResourcesData &resources) {
+  // TODO(vitsai): This may be inconsistent with autoscaler state, which is
+  // not reported as often as a Ray Syncer message.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:264]: What's the TODO here?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 9 above)
Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:192]: oops, old comment leftover from earlier revision

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 10 above)
Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:264]: Changed it to a note

**Comment by rickyyx** [comment]
Tests seem to be failing as well. https://buildkite.com/ray-project/premerge/builds/8874

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 6 above)
Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:277]: Looks like the unhandled edge case was pre-existing in the code, but when it was pulling from `cluster_resource_manager`, it was less likely to happen since it would just silently return stale data as long as at least one Ray Syncer message from the node was successfully received.

Now if we don't get any responses to the polling (interval 10x longer than syncer), we could run into this.

To handle this case I set the node state to `UNSPECIFIED`, I feel like the autoscaler-side work item can be separate? cc @rickyyx to confirm pre-existing behavior

File: src/ray/gcs/gcs_server/gcs_server.cc [hunk 11]
```diff
@@ -706,6 +715,7 @@ void GcsServer::InstallEventListeners() {
     gcs_resource_manager_->OnNodeAdd(*node);
     gcs_placement_group_manager_->OnNodeAdd(node_id);
     gcs_actor_manager_->SchedulePendingActors();
+    gcs_autoscaler_state_manager_->OnNodeAdd(node_id);
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_server.cc:718]: We should pass in `*node` and and initialize the node data inside gcs_autoscaler_state_manager.cc

**Review by jjyao — CHANGES_REQUESTED** [review]

File: src/ray/gcs/gcs_server/gcs_server.cc (hunk 11 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_server.cc:718]: good catch. I think otherwise we will report running node with empty resources before ray syncer sends data.

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 12]
```diff
@@ -184,13 +179,74 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
...
+
+  (*new_data.mutable_resource_load()) = data.resource_load();
+  (*new_data.mutable_resource_load_by_shape()) = data.resource_load_by_shape();
+
+  if (data.resources_total_size() > 0) {
+    (*new_data.mutable_resources_total()) = data.resources_total();
+  }
+
+  for (auto &it : data.resources_total()) {
+    RAY_LOG(INFO) << "vct total " << it.first << " " << it.second;
```
Comment (rickyyx) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:214]: nit: logging levels

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 6 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:298]: Before we will always have the node (otherwise map look fails and raises): https://github.com/ray-project/ray/blob/a77751707b528ecd3e55f580c415833d4179f4f1/src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc#L227-L228

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 13]
```diff
@@ -184,13 +179,66 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
...
+  (*new_data.mutable_resource_load()) = data.resource_load();
+  (*new_data.mutable_resource_load_by_shape()) = data.resource_load_by_shape();
+
+  if (data.resources_total_size() > 0) {
+    (*new_data.mutable_resources_total()) = data.resources_total();
+  }
+
+  (*new_data.mutable_resources_available()) = data.resources_available();
+
+  (*new_data.mutable_resources_normal_task()) = data.resources_normal_task();
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:215]: we don't need this right?

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 14]
```diff
@@ -184,13 +179,66 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
...
+
+  new_data.set_object_pulls_queued(data.object_pulls_queued());
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:217]: This is also unrelated to autoscaling?

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 15]
```diff
@@ -184,13 +179,66 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
...
+  iter->second.first = absl::Now();
+}
+
+std::unordered_map<google::protobuf::Map<std::string, double>, rpc::ResourceDemand>
+GcsAutoscalerStateManager::GetAggregatedResourceLoad() const {
+  std::unordered_map<google::protobuf::Map<std::string, double>, rpc::ResourceDemand>
+      aggregate_load;
+  if (node_resource_info_.empty()) {
+    return aggregate_load;
+  }
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:231]: This is not needed?

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 6 above)
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:290]: I think this should be a check?

```
RAY_CHECK(node_resource_iter != node_resource_info_.end())
```

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc (hunk 2 above)
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_resource_manager.cc:234]: When can they be different?

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 16]
```diff
@@ -15,6 +15,8 @@
 #include "ray/gcs/gcs_server/gcs_resource_manager.h"
 
 #include "ray/common/ray_config.h"
+#include "ray/gcs/gcs_server/gcs_autoscaler_state_manager.h"
+#include "ray/gcs/gcs_server/gcs_server.h"
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:19]: Do you need those in this PR?

File: src/ray/gcs/gcs_server/state_util.h [hunk 17]
```diff
@@ -0,0 +1,62 @@
+// Copyright 2017 The Ray Authors.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/state_util.h:1]: 2023

File: src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc [hunk 18]
```diff
@@ -65,19 +65,28 @@ class GcsAutoscalerStateManagerTest : public ::testing::Test {
...
+
+    // Normally, this would be periodically updated when polling the nodes.
+    // Since we are not running the periodical function, simulate it here.
+    rpc::ResourcesData data;
+    if (!node->resources_total().empty()) {
+      data.mutable_resources_available()->insert(node->resources_total().begin(),
+                                                 node->resources_total().end());
+      data.mutable_resources_total()->insert(node->resources_total().begin(),
+                                             node->resources_total().end());
+    }
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc:85]: This is no longer needed since `OnNodeAdd` does the work?

**Review by jjyao — COMMENTED** [review]
lg

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 14 above)
Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:215]: I think it doesn't hurt -- it's a "proxy for object store memory" which could be useful

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 6 above)
Comment (vitsai) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:287]: It could be transient network error though

File: src/ray/gcs/gcs_server/gcs_resource_manager.cc [hunk 19]
```diff
@@ -98,6 +98,7 @@ void GcsResourceManager::HandleGetAllAvailableResources(
     rpc::GetAllAvailableResourcesReply *reply,
     rpc::SendReplyCallback send_reply_callback) {
   auto local_scheduling_node_id = scheduling::NodeID(local_node_id_.Binary());
+  // TODO(vitsai): State API RPCs should use the same source of truth as autoscaler.
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_resource_manager.cc:101]: Actually why? If you only need usage, then the 100ms one is also fine?

**Review by jjyao — APPROVED** [review]
