### PR TITLE
[core] fix idle node termination on object pulling

### LINKED ISSUE #54372: [Core|Autoscaler|Kuberay] Cannot parallelize tasks across multiple nodes that depend on a large input arrow table
### What happened + What you expected to happen

We have come across a behavior on a Ray + KubeRay cluster where Ray schedules a remote function call, with a reference to a sizeable object as an argument, one task at a time while other tasks are waiting for scheduling even though worker nodes have already been allocated. The tasks are set up to consume most of the resources of each node, so that running multiple tasks in parallel would necessitate running across several nodes. We expect Ray to transfer the object to the other nodes and schedule the tasks there, but it seems data locality is taking precedence.

More specifically:
- Pulling a 25GB polars df from s3 and storing the ref
- Passing the ref to `[myfunc_w_ref.options(num_cpus=100).remote(ref) for _ in range(10)]` (purposely setting hints high to force 1 task per worker)
- Ray only schedules 1 `myfunc_w_ref task` at a time while the remaining 9 are waiting for scheduling even though worker nodes have already been allocated
If we do the same thing but call some `myfunc_simple` that doesn't take ref to the object then all 10 tasks get scheduled right away. 

Code to reproduce (further below) for the following steps:
1. Setting up
2. Generate and write a large dataframe to S3
3. Get reference to dataframe in objectstore
4. Attempt to process remote file in parallel with 10 tasks
Expected: All 10 tasks should be scheduled in parallel across available workers
Actual: Only 1 task runs at a time, with the remaining 9 waiting for scheduling

### Versions / Dependencies

Ray 2.43.0
KubeRay v0.6.0

### Reproduction script

1. Setting up
```
import os
import numpy as np
import polars as pl
import ray
import time
RAY_ADDRESS = "ray://******:80"
AUTH_TOKEN = "******"
ray_config = {
    'address'         : f"{RAY_ADDRESS}",
    '_metadata'       : [("authorization", f"Basic {AUTH_TOKEN}")],
    'runtime_env'     : {
        "env_vars": {
            "AWS_PROFILE": "s3_user",
            "BUCKET_NAME": "some-bucket-name",
            "AWS_CONFIG_FILE": "./aws_credentials.ini",
            "AWS_SHARED_CREDENTIALS_FILE": "./aws_credentials.ini",
        },
    }
}
# Initialize Ray.
ray_context = ray.init(**ray_config)
```
2. Generate and write a large dataframe to S3
```
@ray.remote
def gen_large_df():
    LENGTH = 35_000_000
    df_tmp = pl.DataFrame(np.random.randn(10_000, 100)).lazy()
    table = pl.concat((df_tmp,)* (LENGTH // 10_000)).collect()
    size = table.estimated_size("gb")
    print("Estimated size of the DataFrame:", size)
    return table.to_arrow()

@ray.remote
def polars_write_to_object_store(df, key):
    bucket = os.environ['BUCKET_NAME']
    s3_path = f"s3://{bucket}/{key}"
    df = pl.from_arrow(df)
    df.write_parquet(s3_path)
    print(f"DataFrame written to {s3_path}")
    return s3_path

# create large dummy df
table = gen_large_df.remote()
# upload to s3/object store as parquet file
my_file_path = ray.get(polars_write_to_object_store.remote(table,"foo_large.pq"))
```
3. Get reference to dataframe in objectstore
```
@ray.remote
def read_pl_df_from_object_store(s3_path):
    df = pl.read_parquet(s3_path)
    print(f"DataFrame read from {s3_path}, shape: {df.shape}")
    return df.to_arrow()
# download from s3/object store
reference = read_pl_df_from_object_store.remote(my_file_path)
```
4. Attempt to process remote file in parallel (only 1 task runs at a time)
```
@ray.remote
def remote_call(table):
    print("Starting remote call...Running long computation")
    print(type(table))
    print(table)
    time.sleep(2.5 * 60)  # Simulate a long computation
    np.random.randn(1_000_000, 100) # doing something to ensure some computation is done
    table = pl.from_arrow(table).head().with_columns(hello=pl.lit("hello"))
    size = table.estimated_size("gb")
    print("updated DataFrame size:", size)
    return table

# process the downloaded file in parallel
result = [remote_call.options(num_cpus= 100, memory=1024**3 * 100).remote(reference) for _ in range(10)]
result = [ray.get(r) for r in result]
```
We have the following autoscaler settings:
```
 enableInTreeAutoscaling: true
  autoscalerOptions:
    env:
    - name: TZ
      value: America/New_York
    # autoscale 1 container first, then autoscale the rest of the containers, per multi-tenancy
    upscalingMode: Conservative
    # idleTimeoutSeconds: 60
    # autoscaler sidecar image, that matches the ray head image ray version, and ray autoscaler
    image: "{{ artifactory }}/rayproject/ray:{{ ray_version }}-py39-gpu"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
```

### Issue Severity

None

### PR DESCRIPTION
**Pull request by can-anyscale**
Currently, a node is considered idle while pulling objects from the remote object store. This can lead to situations where a node is terminated as idle, causing the cluster to enter an infinite loop when pulling large objects that exceed the node idle termination timeout.

This PR fixes the issue by treating object pulling as a busy activity. Note that nodes can still accept additional tasks while pulling objects (since pulling consumes no resources), but the auto-scaler will no longer terminate the node prematurely.

Closes #54372

Test:
- CI

### CODE REVIEW

**Comment by edoakes** [comment]
@can-anyscale it looks like we'll call a callback for "resource change subscription" whenever this state changes: https://github.com/ray-project/ray/blob/9b0007aca1b5b6b1ca521a0ec819dfeadfc32422/src/ray/raylet/scheduling/local_resource_manager.cc#L392

Don't think we want to do that in this case?

**Comment by can-anyscale** [comment]
@edoakes hah true, we don't need to do that for object pulling; but why we're doing that for the WORKER footprint is also questionable; i'll ask around

**Comment by edoakes** [comment]
> @edoakes hah true, we don't need to do that for object pulling; but why we're doing that for the WORKER footprint is also questionable; i'll ask around

agreed... likely it was overlooked

File: src/ray/raylet/scheduling/local_resource_manager.cc [hunk 1]
```diff
@@ -128,16 +128,12 @@ void LocalResourceManager::SetBusyFootprint(WorkFootprint item) {
...
 
 void LocalResourceManager::SetIdleFootprint(WorkFootprint item) {
-  auto prev = last_idle_times_.find(item);
-  bool state_change = prev == last_idle_times_.end() || !prev->second.has_value();
-
   last_idle_times_[item] = absl::Now();
-  if (state_change) {
-    OnResourceOrStateChanged();
+  if (IsLocalNodeDraining() && IsLocalNodeIdle()) {
+    ShutdownRayletGracefully();
```
[the remark this answers is not in the document]
Comment (can-anyscale) [reply src/ray/raylet/scheduling/local_resource_manager.cc]: no, the subscribers only care about physical resources, not footprints

[the remark this answers is not in the document]
Comment (can-anyscale) [reply src/ray/raylet/scheduling/local_resource_manager.cc]: Concretely, the `OnResourceOrStateChanged` will fan-out the object created by this `ToNodeResources` function (https://github.com/ray-project/ray/blob/master/src/ray/raylet/scheduling/local_resource_manager.cc#L259). The object created by this function only depends on:
- local_resources_
- drain_request_

which are both not modified by `SetBusyFootprint` or `SetIdleFootprint`. The actual subscriber of the data change is cluster_resource_manager (https://github.com/ray-project/ray/blob/master/src/ray/raylet/scheduling/cluster_resource_scheduler.cc#L73-L75). It will add or update it node with the new resource count, etc. (which is no-op if the resource count doesn't change).

**Comment by can-anyscale** [comment]
ready for review \o/

File: src/ray/raylet/scheduling/local_resource_manager.h [hunk 2]
```diff
@@ -32,6 +32,7 @@ namespace ray {
 /// Encapsulates non-resource artifacts that evidence work when present.
 enum WorkFootprint {
   NODE_WORKERS = 1,
+  PULLING_FROM_OBJECT_STORE = 2,
```
Comment (edoakes) [inline src/ray/raylet/scheduling/local_resource_manager.h]: Let's call this something a little more semantically meaningful. I'd suggest: `PULLING_TASK_ARGUMENTS`

File: src/ray/raylet/local_lease_manager.cc [hunk 3]
```diff
@@ -887,6 +899,10 @@ std::vector<std::shared_ptr<internal::Work>> LocalLeaseManager::CancelLeasesWith
         cancelled_works.push_back(work);
         return true;
       });
+  if (waiting_lease_queue_.empty()) {
+    cluster_resource_scheduler_.GetLocalResourceManager().SetIdleFootprint(
+        WorkFootprint::PULLING_FROM_OBJECT_STORE);
+  }
```
Comment (edoakes) [inline src/ray/raylet/local_lease_manager.cc:903]: hm, how do we know that we are pulling args here?

**Review by edoakes — APPROVED** [review]
Need to be very careful that we don't have any state transitions that leave the node sitting in the new state and unable to be terminated.

I see a lot of callsites here where we transition to the new state if `waiting_lease_queue_.empty()`, but without any other checks. How do we know for certain that there _are_ arguments being pulled there? I think I must be missing something.

**Review by edoakes — CHANGES_REQUESTED** [review]
Sorry the approve was accidental

File: src/ray/raylet/local_lease_manager.cc (hunk 3 above)
Comment (can-anyscale) [reply src/ray/raylet/local_lease_manager.cc:903]: SetIdleFootprint is used to free the node, so we mark the node as free when the waiting_lease_queue_ is empty. The waiting_lease_queue_ tracks leases that haven’t been granted yet because the task arguments are still unavailable.

But makes sense, let me schedule some time with @Sparks0219 and @jjyao to go through the local_lease_manager code together.

File: src/ray/raylet/scheduling/local_resource_manager.cc [hunk 4]
```diff
@@ -128,16 +128,12 @@ void LocalResourceManager::SetBusyFootprint(WorkFootprint item) {
     return;
   }
   last_idle_times_[item] = absl::nullopt;
-  OnResourceOrStateChanged();
```
Comment (Sparks0219) [inline src/ray/raylet/scheduling/local_resource_manager.cc:131]: Hmmm could you explain why we don't call OnResourceOrStateChanged in SetBusyFootprint/SetIdleFootprint?

File: src/ray/raylet/scheduling/local_resource_manager.h (hunk 2 above)
Comment (Sparks0219) [reply src/ray/raylet/scheduling/local_resource_manager.h]: +1

**Comment by can-anyscale** [comment]
Updated version after talking to @Sparks0219 and others:
- Keep the call to `OnResourceOrStateChanged` when setting the footprint to busy or idle. This is because most of the logic of `OnResourceOrStateChanged` is necessary, up until this version++ line https://github.com/ray-project/ray/blob/master/src/ray/raylet/scheduling/local_resource_manager.cc#L399. The remaining is `resource_change_subscriber_`, which is actually just the [AddOrUpdateNode](https://github.com/ray-project/ray/blob/master/src/ray/raylet/scheduling/cluster_resource_manager.cc#L61), which does not have anything sitewise expensive effect. Will also run perf tests to make sure.
- The question about whether we can use `waiting_lease_queue_` to reliably determine if the node is busy pulling argument is yes. If the queue is empty, the node is not pulling; otherwise it is pulling.

File: src/ray/raylet/tests/local_lease_manager_test.cc
Comment (edoakes) [inline src/ray/raylet/tests/local_lease_manager_test.cc:1]: Looks like the only case being tested here is for infeasible lease requests. We should also have tests for the happy path (accepted -> pulling args -> running -> done), as well as any error cases between those state transitions.

File: src/ray/raylet/local_lease_manager.cc [hunk 5]
```diff
@@ -497,6 +501,10 @@ void LocalLeaseManager::SpillWaitingLeases() {
       num_waiting_lease_spilled_++;
       waiting_leases_index_.erase(lease_id);
       it = waiting_lease_queue_.erase(it);
+      if (waiting_lease_queue_.empty()) {
+        cluster_resource_scheduler_.GetLocalResourceManager().SetIdleFootprint(
+            WorkFootprint::PULLING_TASK_ARGUMENTS);
+      }
```
Comment (edoakes) [inline src/ray/raylet/local_lease_manager.cc:507]: I don't understand this block and the one below. In this case, we are unsubscribing from the lease dependencies and popping from the queue. Shouldn't this result in the idle footprint being reset to _not_ be `PULLING_TASK_ARUGMENTS` anymore?

File: src/ray/raylet/tests/local_lease_manager_test.cc
Comment (can-anyscale) [reply src/ray/raylet/tests/local_lease_manager_test.cc:1]: make sense, I'll add more

File: src/ray/raylet/local_lease_manager.cc (hunk 5 above)
Comment (can-anyscale) [reply src/ray/raylet/local_lease_manager.cc:507]: The `SetIdleFootprint` function does exactly what you described — it _no longer_ marks the node as PULLING_TASK_ARGUMENTS. The `SetBusyFootprint` function, on the other hand, is the counterpart that marks the node as PULLING_TASK_ARGUMENTS.

Comment (edoakes) [reply src/ray/raylet/local_lease_manager.cc:507]: Oh now I understand. So we have independent state machines for the "footprint" types and then we combine them together to determine if the node as a whole is idle. The naming and API are pretty strange 😕 (existing, not your change)

As a minimal change to improve readability, I'd suggest renaming to: `MarkFootprintAsBusy` and `MarkFootprinAstIdle`. The way it's written now makes it seem that we are setting a global state to be equal to the enum passed in.

**Comment by can-anyscale** [comment]
@edoakes's comments:
- Refactor function name to MarkFootprintAsBusy/MarkFootprintAsIdle
- Add test case for happy path (lease is granted)

**Review by edoakes — APPROVED** [review]
