### PR TITLE
Properly release resources of workers exiting due to max_calls

### LINKED ISSUE #10960: [Core] Resources are not returned when implicitly capturing object reference with `max_call` arg.
### What is the problem?

Reported from this https://github.com/ray-project/ray/issues/10739

When running the script below, GPU resources are never returned. There is a couple interesting behaviors.

1. We have local reference from our internal methods.
Screen Shot 2020-09-22 at 4 15 23 PM

2. When we move `X_id` and `int_ref` into the task, or when we pass them by arg, the error disappeared. 

3. When we remove `max_call`, the error disappeared.

It might be some unknown bugs from ref counting, but I am not sure.

cc @stephanie-wang @ericl 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
import ray
import time

ray.init(num_cpus=2, num_gpus=1)

sleep_seconds = 5

import numpy as np
X = np.zeros(int(1e6))
X_id = ray.put(X)

int_ref = ray.put(11)

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_thing():
    time.sleep(sleep_seconds)
    return len(ray.get(X_id))

@ray.remote(num_cpus=1, num_gpus=0.25, max_calls=1)
def do_sum():
    time.sleep(sleep_seconds)
    return ray.get(int_ref) + 20

for i in range(3):
    print(ray.get(do_thing.remote()))
    print(ray.get(do_sum.remote()))
    print(i, ray.available_resources())
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Previously code incorrectly assumed that an exiting worker would disconnect from the raylet promptly to release resources. This isn't the case if the worker is owning references. This PR plumbs through the right release resources call even in this scenario.

Closes https://github.com/ray-project/ray/issues/10960

### CODE REVIEW

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 1]
```diff
@@ -87,7 +87,7 @@ Status CoreWorkerDirectTaskSubmitter::SubmitTask(TaskSpecification task_spec) {
                       worker_to_lease_entry_.end());
             auto &lease_entry = worker_to_lease_entry_[active_worker_addr];
             if (!lease_entry.is_busy) {
-              OnWorkerIdle(active_worker_addr, scheduling_key, false,
+              OnWorkerIdle(active_worker_addr, scheduling_key, false, false,
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_task_transport.cc:90]:
```suggestion
OnWorkerIdle(active_worker_addr, scheduling_key, /*was_error*/false, /*worker_exiting*/false,
```

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 2]
```diff
@@ -525,23 +527,11 @@ void CoreWorkerDirectTaskSubmitter::PushNormalTask(
           RAY_CHECK_GE(scheduling_key_entry.num_busy_workers, 1u);
           scheduling_key_entry.num_busy_workers--;
 
-          if (reply.worker_exiting()) {
-            RAY_LOG(DEBUG) << "Worker " << addr.worker_id
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_task_transport.cc:529]: The same logic is performed from `ReturnWorker` right?

File: src/ray/raylet/node_manager.cc [hunk 3]
```diff
@@ -1707,7 +1707,9 @@ void NodeManager::HandleReturnWorker(const rpc::ReturnWorkerRequest &request,
         HandleDirectCallTaskUnblocked(worker);
       }
       cluster_task_manager_->ReleaseWorkerResources(worker);
-      HandleWorkerAvailable(worker);
+      if (!request.worker_exiting()) {
+        HandleWorkerAvailable(worker);
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:1711]: Btw, I have a question regarding semantics between `disconnect_worker ` and `worker_exiting `.

Is `disconnect_worker` for forceful termination (since there's something unrecoverable) initiated from the caller whereas `worker_exiting` is for graceful shutdown, and the clean up will be performed by the actor itself (callee), is this correct? 

If this is the right difference, can you comment it from the docstring of `ReturnWorker` method?

**Review by rkooo567 — APPROVED** [review]
LGTM! A couple nit comments

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 2 above)
Comment (ericl) [reply src/ray/core_worker/transport/direct_task_transport.cc:529]: Yep.
