### PR TITLE
[Core] Fix the named actor get or create race condition

### LINKED ISSUE #19896: [Bug] Hangs when concurrently trying to get-or-create a named actor
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

It seems there are some bad error messages / race conditions around trying to implement getOrCreate named actor. cc @edoakes @simon-mo 

### Versions / Dependencies

master

### Reproduction script

```
import ray

@ray.remote
class Actor:
    def ping(self):
        return "ok"


@ray.remote
def getter(name):
    try:
        try:
            actor = ray.get_actor("foo")
        except:
            print("Get failed, trying to create", name)
            actor = Actor.options(name="foo", lifetime="detached").remote()
    except:
        print("Someone else created it, trying to get", name)
        actor = ray.get_actor("foo")
    return ray.get(actor.ping.remote())


def do_run(name):
    name = "actor_" + str(name)
    tasks = [getter.remote(name) for i in range(4)]
    result = ray.get(tasks)
    try:
        ray.kill(ray.get_actor(name))  # Cleanup
    except:
        pass
    return result


for i in range(1000):
    print("iteration", i, do_run(i))
```

```
2021-10-29 12:56:53,914	WARNING worker.py:1239 -- 3 retries left for task ffffffffffffffff6c821488bb8018faf2270b9701000000, attempting to resubmit.
2021-10-29 12:56:53,914	WARNING worker.py:1239 -- 3 retries left for task ffffffffffffffff4da118be0a6f36cab78fa70301000000, attempting to resubmit.
(pid=gcs_server) [2021-10-29 12:56:53,909 E 1010929 1010929] gcs_actor_manager.cc:161: Failed to register actor: Invalid: Actor with name 'foo' already exists., job id = 01000000, actor id = 6c821488bb8018faf2270b9701000000
(pid=gcs_server) [2021-10-29 12:56:53,909 E 1010929 1010929] gcs_actor_manager.cc:161: Failed to register actor: Invalid: Actor with name 'foo' already exists., job id = 01000000, actor id = 4da118be0a6f36cab78fa70301000000
(pid=gcs_server) [2021-10-29 12:56:53,909 E 1010929 1010929] gcs_actor_manager.cc:187: Failed to create actor, job id = 01000000, actor id = 6c821488bb8018faf2270b9701000000, status: Invalid: Actor may be already destroyed.
(pid=gcs_server) [2021-10-29 12:56:53,909 E 1010929 1010929] gcs_actor_manager.cc:187: Failed to create actor, job id = 01000000, actor id = 4da118be0a6f36cab78fa70301000000, status: Invalid: Actor may be already destroyed.
(getter pid=1010992) [2021-10-29 12:56:53,909 E 1010992 1011158] direct_task_transport.cc:53: Failed to create actor 4da118be0a6f36cab78fa70301000000 with status: Invalid: Actor may be already destroyed.
(getter pid=1010992) Get failed, trying to create actor_0
(getter pid=1010991) [2021-10-29 12:56:53,909 E 1010991 1011162] direct_task_transport.cc:53: Failed to create actor 6c821488bb8018faf2270b9701000000 with status: Invalid: Actor may be already destroyed.
(getter pid=1010986) Get failed, trying to create actor_0
(getter pid=1010986) Someone else created it, trying to get actor_0
(getter pid=1010991) Get failed, trying to create actor_0
(getter pid=1010994) Get failed, trying to create actor_0
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### LINKED ISSUE #20092: [Bug] "PENDING_CREATION" status issue, and related resubmission problem. [non-head node]
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

Bugs and actor's creating problem:
1. Actor's status is frozen at "PENDING_CREATION", when register an actor from non-head nodes.
 ```
   class RemoteProc(Object): ...
        def __init__(self):
            pass
        def procTask(self, a, b):
            print('[%s]-> %s' % (a, b))
    RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()
```

   Dashboard shows this registered actor is remaining "PENDING_CREATION".
   It's neccessory to submit actor from other nodes, or at least to refuse these node's register submission and raise warnning.

2. Related problem with "PENDING_CREATION" actor. 
`proc= ray.get_actor('test', namespace='xxx')`
    a. This code could get "PENDING_CREATION" status actor, without status check. (this status shall be invalid, instead of obtainable). And actor will hang forever if tried to run it.
    b. This actor handler can be called by api: "ray.kill", without any logging. While dashboard shows the status turn to be "DEAD" in this namespace. After killing, if we wanna re-submit the same actor with "RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()", error " ailed to create actor" raised, and eventually  the terminal will crash.

Attachments.
Bug 1: 

b120ed0ac5c738a7a75892be09000000(0) | testProc | __main__ RemoteProc __init__ 9f8e28f28c3a4a1099b47adf8627c1b... | 09000000 | 0 |   | 0 | DEAD |  
-- | -- | -- | -- | -- | -- | -- | -- | --
acef0c60c51301feb1e7a33a0a000000(0) | testProc | __main__ RemoteProc __init__ 5ed1054cf7954252a28a25a55d6d681... | 0a000000 | 0 |   | 0 | DEAD |  
7d074daae2438b4f82c8755d0e000000(0) | testProc1 | __main__ RemoteProc __init__ 6487bdf6d75247689727eaae682024b... | 0e000000 | 0 |   | 0 | PENDING_CREATION |  
6d709b216bc19cdf77ce4a5310000000(0) | test | __main__ RemoteProc __init__ a09dfd3bd548485fa3f417fd9542ded... | 10000000 | 0 |   | 0 | PENDING_CREATION |  
77c3d47d01bce6d99a3c412211000000(0) | test | __main__ RemoteProc __init__ 6e6adfbbabe84c31a7617235ab8199f... | 11000000 | 94958 | 172.16.xxx.xxx | 10022 | Active

Bug 2:
In [8]: RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='nvh').remote()
[2021-11-05 10:33:06,468 E 94924 94948] direct_task_transport.cc:61: Failed to create actor ceab7a792cab03c5646a394511000000 with status: Invalid: Actor may be already destroyed.
Out[8]: Actor(RemoteProc, ceab7a792cab03c5646a394511000000)

In [9]: 2021-11-05 10:33:06,480	WARNING worker.py:1227 -- 3 retries left for task ffffffffffffffffceab7a792cab03c5646a394511000000, attempting to resubmit.
(pid=gcs_server) [2021-11-05 10:33:06,467 E 60903 60903] gcs_actor_manager.cc:148: Failed to register actor: Invalid: Actor with name 'test' already exists., job id = 11000000, actor id = ceab7a792cab03c5646a394511000000
(pid=gcs_server) [2021-11-05 10:33:06,468 E 60903 60903] gcs_actor_manager.cc:174: Failed to create actor, job id = 11000000, actor id = ceab7a792cab03c5646a394511000000, status: Invalid: Actor may be already destroyed.

(pid=gcs_server) [2021-11-05 10:33:12,050 E 60903 60903] gcs_actor_manager.cc:148: Failed to register actor: Invalid: Actor with name 'test' already exists., job id = 11000000, actor id = ceab7a792cab03c5646a394511000000
In [9]: [2021-11-05 10:33:17,251 C 94924 94948] core_worker.cc:966:  Check failed: _s.ok() Bad status: TimedOut: There was timeout in registering an actor. It is probably because GCS server is dead or there's a high load there.
*** StackTrace Information ***
    ray::SpdLogMessage::Flush()
    ray::RayLog::~RayLog()
    ray::core::CoreWorker::InternalHeartbeat()
    ray::PeriodicalRunner::DoRunFnPeriodically()
    ray::PeriodicalRunner::DoRunFnPeriodically()::{lambda()#1}::operator()()
    boost::asio::detail::executor_function<>::do_complete()
    boost::asio::io_context::executor_type::dispatch<>()
    boost::asio::detail::wait_handler<>::do_complete()
    boost::asio::detail::scheduler::do_run_one()
    boost::asio::detail::scheduler::run()
    boost::asio::io_context::run()
    ray::core::CoreWorker::RunIOService()
    execute_native_thread_routine

### Versions / Dependencies

Ubuntu 16.04
Ray 1.7.1

### Reproduction script

```
## This code is running on child node.
import ray
ray.init('auto')

@ray.remote(num_cpus=1)
class RemoteProc(object):
    def __init__(self):
        pass

    def procTask(self, a, b):
        print('[%s]-> %s' % (a, b))

RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()
proc = ray.get_actor('test', namespace='xxx')
ray.get(proc.procTask.remote(1,2))
# Kill and resubmit
# ray.kill(proc)
# RemoteProc.options(name='test', lifetime='detached', max_concurrency=10, namespace='xxx').remote()
```

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by rkooo567**
## NOTE
https://github.com/ray-project/ray/pull/20126 -> This issue actually wasn’t a regression. Repro had a mistake, and for some reasons with that mistake, it was broken from 1.8. The issue itself existed for a long time. cc @iycheng 

## Description

Currently, "RegisterActor" RPC is synchronous, so theoretically, we shouldn't have any race condition in creating same named actors. The problem was that `RegisterActor` RPC response status was not properly propagated to the caller, and it was always set to `Status::OK()`, which is a bug. 

I verified this fixes the issue https://github.com/ray-project/ray/issues/19896. I am adding more unit tests now. 

We can also close this as I verified it was working with the fix (check the test https://github.com/ray-project/ray/issues/20092)

Also, while I was working on this issue, I found https://github.com/ray-project/ray/issues/20129. I will probably work on it after this PR is merged.

**TODO**
 - [x] Add unit tests
 - [ ] Fix cpp unit tests

## Related issue number

Closes https://github.com/ray-project/ray/issues/19896
Closes https://github.com/ray-project/ray/issues/20092

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -453,6 +453,12 @@ Status GcsActorManager::CreateActor(const ray::rpc::CreateActorRequest &request,
     return Status::Invalid("Actor may be already destroyed.");
   }
 
+  const auto &actor_name = iter->second->GetName();
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:456]: The invariant here is that this RPC path is not called if the actor is not registered due to conflicting names.

File: src/ray/core_worker/actor_creator.h [hunk 2]
```diff
@@ -67,20 +67,20 @@ class DefaultActorCreator : public ActorCreatorInterface {
...
             ::RayConfig::instance().gcs_server_request_timeout_seconds())) !=
-            std::future_status::ready) {
+        std::future_status::ready) {
       std::ostringstream stream;
       stream << "There was timeout in registering an actor. It is probably "
                 "because GCS server is dead or there's a high load there.";
       return Status::TimedOut(stream.str());
     }
-    return status;
+    return future.get();
```
Comment (rkooo567) [inline src/ray/core_worker/actor_creator.h:83]: The bug was that `AsyncRegisterActor ` always returns the Status::OK() although the RegisterActor RPC failed (which we should retrieve from promise instead). I realized this was already properly used for placement group RPCs, but not for this particular actor RPC.

Comment (rkooo567) [reply src/ray/core_worker/actor_creator.h:83]: Since Registering named actor is synchronous, it is guaranteed that there's no race condition here. I will write a comment.

File: src/ray/core_worker/actor_manager.cc [hunk 3]
```diff
@@ -96,9 +96,8 @@ std::pair<std::shared_ptr<const ActorHandle>, Status> ActorManager::GetNamedActo
     std::ostringstream stream;
     stream << "Failed to look up actor with name '" << name << "'. This could "
            << "because 1. You are trying to look up a named actor you "
-           << "didn't create. 2. The named actor died. 3. The actor hasn't "
```
Comment (rkooo567) [inline src/ray/core_worker/actor_manager.cc:99]: 3 is not the case anymore.

Comment (rkooo567) [reply src/ray/core_worker/actor_manager.cc:99]: It also exposes implementation detail. Note that after we fix https://github.com/ray-project/ray/issues/20129, the 2 will be deleted from here too.

File: python/ray/tests/test_actor_advanced.py [hunk 4]
```diff
@@ -1331,6 +1331,87 @@ def ready(self):
...
+        except Exception:
+            pass
+        return result
+
+    for i in range(50):
+        # TODO(sang): Currently increasing concurrency
+        # to 8 will make test flaky due to this issue
+        # https://github.com/ray-project/ray/issues/20129
+        CONCURRENCY = 4
+        results = do_run(i, concurrency=CONCURRENCY)
```
Comment (ericl) [inline python/ray/tests/test_actor_advanced.py:1368]: Why does this bug affect this repro, don't we ray.kill only for cleanup here?

Comment (rkooo567) [reply python/ray/tests/test_actor_advanced.py:1368]: I think in the next round (next iteration), get_actor returns the killed actor instead of raising an ValueError.

Comment (rkooo567) [reply python/ray/tests/test_actor_advanced.py:1368]: (So it seems to take some time between ray.kill and ray.get_actor reflects that. IIUC that shouldn’t happen, but it does, so there must be a bug there)

Comment (scv119) [reply python/ray/tests/test_actor_advanced.py:1368]: sounds like this test will be flakey.

Comment (rkooo567) [reply python/ray/tests/test_actor_advanced.py:1368]: Yeah good point! Let me add a safe check and increase the concurrency here

**Review by scv119 — APPROVED** [review]
The fix makes sense. the flaky test looks like an unrelated issue.

File: python/ray/tests/test_actor_advanced.py (hunk 4 above)
Comment (rkooo567) [reply python/ray/tests/test_actor_advanced.py:1368]: actually, this was the typical ownership issue. It passes consistently after I changed the lifetime to detached. (So, actor was killed because the idle worker owns the actor handle, which is subsequently killed by the worker pool)

**Comment by rkooo567** [comment]
Windows failure seems unrelated
