### PR TITLE
[core] Fix inlined nested ids

### LINKED ISSUE #17719: [core] Safety bug in distributed reference counting
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

#13309 introduces an optimization for small objects that allows `ObjectRef` holders to get the value directly from the owner. I think this is causing a bug in the distributed ref counting code when ObjectRefs are nested.

The scenario is something like this, where worker W holds an ObjectRef to A, which contains ObjectRef B.
1. W gets A's value from A's owner.
2. A's owner responds with A's value, also says that A contains the nested ref B.
3. W submits a task that depends on A. A is small, so it gets inlined into the task's description.
4. W deletes local ref to A.

W's ref counts at the end will look like this:
A, local_ref_cnt = 0, submitted_ref_cnt = 0
B, local_ref_cnt = 0, submitted_ref_cnt = 1

W is supposed to keep track of the nested relationship between A <> B, so that eventually, B's owner will learn that W still has a reference to it. Right now we don't do this when A is small enough to be inlined.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments): See #17717.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Small objects get inlined for performance. If the small object contains an ObjectRef, we need to mark this in the ref counting so that we know to increment the inner ObjectRef's count whenever the outer ObjectRef is used. This PR:
1. Modifies the protocol for small objects to store the nested ObjectRefs instead of just the ObjectIDs.
2. Fixes a bug where we were not updating the ref counter correctly for inlined objects.

## Related issue number

Closes #17719.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/future_resolver.cc [hunk 1]
```diff
@@ -88,10 +89,14 @@ void FutureResolver::ProcessResolvedObject(const ObjectID &object_id,
...
           metadata.size());
     }
-    auto inlined_ids =
-        IdVectorFromProtobuf<ObjectID>(reply.object().nested_inlined_ids());
-    RAY_UNUSED(in_memory_store_->Put(RayObject(data_buffer, metadata_buffer, inlined_ids),
-                                     object_id));
+    auto inlined_refs =
+        VectorFromProtobuf<rpc::ObjectReference>(reply.object().nested_inlined_refs());
+    for (const auto &inlined_ref : inlined_refs) {
+      reference_counter_->AddBorrowedObject(ObjectID::FromBinary(inlined_ref.object_id()),
```
Comment (stephanie-wang) [inline src/ray/core_worker/future_resolver.cc:95]: This is the relevant line to fix #17719 (the rest of the PR is plumbing to make sure we pass the owner address around).

File: src/ray/protobuf/common.proto [hunk 2]
```diff
@@ -288,7 +288,7 @@ message TaskArg {
   // Metadata for pass-by-value arguments.
   bytes metadata = 3;
   // ObjectIDs that were nested in the inlined arguments of the data field.
-  repeated bytes nested_inlined_ids = 4;
+  repeated ObjectReference nested_inlined_refs = 4;
```
Comment (scv119) [inline src/ray/protobuf/common.proto:291]: nits: consider use a new index to avoid any unforeseen compatibility issue

**Review by scv119 — COMMENTED** [review]
wow, that's a lot of plumbing. will take a closer review during the weekend.

File: src/ray/core_worker/core_worker.h [hunk 3]
```diff
@@ -513,7 +522,7 @@ class CoreWorker : public rpc::CoreWorkerServiceHandler {
   /// \param[in] contained_object_ids The IDs serialized in this object.
```
Comment (scv119) [inline src/ray/core_worker/core_worker.h:522]: comments need update

**Review by scv119 — COMMENTED** [review]
Also the build failure looks relevant
```


src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc: In function ‘ray::Status PutSerializedObject(JNIEnv*, jobject, ray::ObjectID, ray::ObjectID*, bool, const std::unique_ptr<ray::rpc::Address>&)’:
--
  | src/ray/core_worker/lib/java/io_ray_runtime_object_NativeObjectStore.cc:38:73: error: ‘using element_type = class ray::RayObject’ {aka ‘class ray::RayObject’} has no member named ‘GetNestedIds’; did you mean ‘GetNestedRefs’?
  | 38 \|         native_ray_object->GetMetadata(), data_size, native_ray_object->GetNestedIds(),
  | \|                                                                         ^~~~~~~~~~~~
  | \|                                                                         GetNestedRefs

```

File: src/ray/protobuf/common.proto (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/protobuf/common.proto:291]: Would that mean keeping the old `nested_inlined_ids` field around? I think I'd rather not do that since we don't currently support core workers on different versions anyway.

File: src/ray/core_worker/core_worker.cc [hunk 4]
```diff
@@ -1030,6 +1030,18 @@ rpc::Address CoreWorker::GetOwnerAddress(const ObjectID &object_id) const {
...
 }
 
+std::vector<rpc::ObjectReference> CoreWorker::GetObjectRefs(
+    const std::vector<ObjectID> &object_ids) const {
+  std::vector<rpc::ObjectReference> refs;
+  for (const auto &object_id : object_ids) {
+    rpc::ObjectReference ref;
+    ref.set_object_id(object_id.Binary());
+    ref.mutable_owner_address()->CopyFrom(GetOwnerAddress(object_id));
+    refs.push_back(ref);
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:1040]:
```suggestion
    refs.push_back(std::move(ref));
```
? Or is it automatically done?

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -2110,8 +2123,15 @@ Status CoreWorker::AllocateReturnObject(const ObjectID &object_id,
...
   if (!object_already_exists) {
-    *return_object =
-        std::make_shared<RayObject>(data_buffer, metadata, contained_object_id);
+    std::vector<rpc::ObjectReference> contained_refs;
+    for (const auto &oid : contained_object_ids) {
+      RAY_LOG(DEBUG) << "Return object " << object_id << " contains ObjectRef " << oid;
+      rpc::ObjectReference ref;
+      ref.set_object_id(oid.Binary());
+      ref.mutable_owner_address()->CopyFrom(GetOwnerAddress(oid));
+      contained_refs.push_back(ref);
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:2132]: Same comment as above.

File: src/ray/core_worker/core_worker.cc [hunk 6]
```diff
@@ -2110,8 +2123,15 @@ Status CoreWorker::AllocateReturnObject(const ObjectID &object_id,
...
+    }
+    *return_object = std::make_shared<RayObject>(data_buffer, metadata, contained_refs);
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:2134]: Here too. Is it automatically moved for `contained_refs `?

File: src/ray/protobuf/common.proto (hunk 2 above)
Comment (rkooo567) [reply src/ray/protobuf/common.proto:291]: I think this proto wouldn't have backward compat issue, so it should be fine?  (not an autoscaling path)

**Review by rkooo567 — APPROVED** [review]
Only one question!

**Comment by rkooo567** [comment]
and it is a lot of plumbing haha...

File: python/ray/_raylet.pyx [hunk 7]
```diff
@@ -1198,14 +1205,17 @@ cdef class CoreWorker:
                     Buffer.make(data))
             if self.is_local_mode or (put_small_object_in_memory_store
                and <int64_t>total_bytes < put_threshold):
+                if not self.is_local_mode:
```
Comment (scv119) [inline python/ray/_raylet.pyx:1208]: i might miss the context of local mode. why local mode doesn't need contained_object_refs?

File: src/ray/core_worker/core_worker.cc [hunk 8]
```diff
@@ -2119,8 +2132,16 @@ Status CoreWorker::AllocateReturnObject(const ObjectID &object_id,
   }
   // Leave the return object as a nullptr if the object already exists.
   if (!object_already_exists) {
+    std::vector<rpc::ObjectReference> contained_refs;
```
Comment (scv119) [inline src/ray/core_worker/core_worker.cc:2135]: is it possible to reuse `GetObjectRefs` we introduced earlier in this file?

**Review by scv119 — COMMENTED** [review]
one more question.

File: src/ray/core_worker/core_worker.cc (hunk 8 above)
Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:2135]: Oh yes, good point!

File: python/ray/_raylet.pyx (hunk 7 above)
Comment (stephanie-wang) [reply python/ray/_raylet.pyx:1208]: Ah I was trying to fix a CI error that I don't think is actually related.

I don't really know how local mode works, but I don't think that it uses plasma at all, so it probably doesn't matter if we include contained_object_refs or not. Anyway, I'll just remove this.

**Review by wuisawesome — APPROVED** [review]
proto changes look fine
