### PR TITLE
[core] On GCS restart, destroy not forget the unused workers. Fixing PG leaks.

### LINKED ISSUE #45598: [core] Removed Placement group did not kill actors, if its ancestors are from detached actors.
### What happened + What you expected to happen

Part of https://github.com/ray-project/ray/issues/45596.

This issue tracks the PG killing acrors/tasks mechanism.

### Versions / Dependencies

master

### Reproduction script

(todo)

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by rynewang**
On GCS restart, it prunes any worker it did not bookkeep, via the RPC `ReleaseUnusedWorkers`. Raylet receives it and removes any workers not in a `worker_ids_in_use` list. However, it's only *forgetting* the worker by removing it from the `leased_workers_` not *killing* the worker, but the worker can be still in running and never gets killed, hence leaked.

The evidence leading to this PR is, in a Ray cluster I observed GCS failed to kill a placement group: it sends "pls remove all workers in this PG", and raylet did not kill any workers, and then it finds the PG is still in used and replied "failed, pls retry" for many minutes, and finally GCS gave up and the PG is removed from the GCS, and the worker leaked. I found the PG holding worker is NOT in leased_workers_, but it IS known by worker_pool, since it shows up in worker pool's state dump.

The reason behind the above case is, when GCS is restarting, it **wrongly** thinks the worker is no longer needed (due to another bug (https://github.com/ray-project/ray/pull/45791 actors whose parent is detached actor is considered dead but should be alive), and orders Raylet to release it. Raylet, as fixed in this PR, simply forgets the worker but does not kill it.

To make things more clear, here is a timeline:

1. Creates a detached actor `Parent`, which creates a PG `pg` and a normal actor `Child` in pg
2. Job for `Parent` dies. Everyone should live on, since everyone's lifetime = detached Parent's
3. GCS restarts
4. BUG1 (Fixed by #45791): GCS thinks `Child` should be die, and,
    - did not load it (it's forgotten by GCS). This makes the child is never killed later
        - should be: load it, can kill it later 
    - sends `ReleaseUnusedWorkers` to Raylet with this worker as "not used"
        - should be: mark this as "used" so it's not killed by Raylet
 5. BUG2 (this bug): Raylet should kill the worker since it's "not used" by GCS. However it simply forgets it.
    - this makes the worker leak on Raylet side: later when it needs to be killed (by PG removal), it can not.
    - should be: kill it (DestroyWorker) on the RPC, so we could have exposed the first bug earlier.
6. Because of BUG1, when the detached actor Parent is dead, nobody is killing Child actor. (forgot by GCS)
7. Because of BUG2, when the PG is removed since Parent is dead, the PG removal failed with a worker leak (forgot by raylet)

Note since FIX1 (#45791) is merged, Raylet should no longer kill the detached actor on RPC because it's considered used. This FIX2 is just for the sake of completeness, and for future leaks.

In this PR:
- On `ReleaseUnusedWorkers`, instead of forgetting the workers we call DestroyWorker to kill it
- In state dump, print the actors' worker ID for debugging ease.
- Removed useless `ReleaseWorkers` method
- Comments
- Renamed RPC to `ReleaseUnusedActorWorkers` to make it dead clear.

Fixes #45598.

### CODE REVIEW

File: src/ray/raylet/node_manager.cc [hunk 1]
```diff
@@ -2020,25 +2020,29 @@ void NodeManager::HandleShutdownRaylet(rpc::ShutdownRayletRequest request,
...
+    rpc::ReleaseUnusedActorWorkersReply *reply,
+    rpc::SendReplyCallback send_reply_callback) {
   std::unordered_set<WorkerID> in_use_worker_ids;
   for (int index = 0; index < request.worker_ids_in_use_size(); ++index) {
     auto worker_id = WorkerID::FromBinary(request.worker_ids_in_use(index));
     in_use_worker_ids.emplace(worker_id);
   }
 
-  std::vector<WorkerID> unused_worker_ids;
+  std::vector<std::shared_ptr<WorkerInterface>> unused_workers;
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:2033]:
```suggestion
  std::vector<std::shared_ptr<WorkerInterface>> unused_actor_workers;
```

File: src/ray/raylet/node_manager.h [hunk 2]
```diff
@@ -536,10 +533,13 @@ class NodeManager : public rpc::NodeManagerServiceHandler,
                           rpc::ReturnWorkerReply *reply,
                           rpc::SendReplyCallback send_reply_callback) override;
 
-  /// Handle a `ReleaseUnusedWorkers` request.
-  void HandleReleaseUnusedWorkers(rpc::ReleaseUnusedWorkersRequest request,
-                                  rpc::ReleaseUnusedWorkersReply *reply,
-                                  rpc::SendReplyCallback send_reply_callback) override;
+  /// Handle a `ReleaseUnusedActorWorkers` request.
+  // On GCS restart, there's a pruning effort. GCS sends raylet a list of workers it still
```
Comment (jjyao) [inline src/ray/raylet/node_manager.h:537]:
```suggestion
  // On GCS restart, there's a pruning effort. GCS sends raylet a list of actor workers it still
```

File: src/ray/raylet/node_manager.h [hunk 3]
```diff
@@ -536,10 +533,13 @@ class NodeManager : public rpc::NodeManagerServiceHandler,
...
+  // wants (that it keeps tracks of); and the raylet destroys all other workers.
```
Comment (jjyao) [inline src/ray/raylet/node_manager.h:538]:
```suggestion
  // wants (that it keeps tracks of); and the raylet destroys all other actor workers.
```

**Review by jjyao — COMMENTED** [review]
LGTM.

Lets add some tests

**Review by jjyao — APPROVED** [review]
