### PR TITLE
Disable port sharing in grpc server

### LINKED ISSUE #6460: Different workers in the same Java process may listen on the same RPC port
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

3adbe29450 with https://github.com/ray-project/ray/pull/6454 and https://github.com/ray-project/ray/pull/6455 merged

*Does the problem occur on the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html)?*

Not sure

In Java test, in a rare case we can see the test hangs (can be reproduced if run the test script multiple times). After analyzing the logs, I found that a normal task was assigned to a Java worker by raylet, but the worker refused to execute it with the warning log `Received task for mismatched WorkerID ca376a7326a613f6af47d4ad249fbc2e304ceda1`. Finally, I found that two workers in the same process listened on the same port (see port 39607 in below log segments).

```
$ cat ./java_worker20191212-222207.67150 | grep -E 'ca376a7326a613f6af47d4ad249fbc2e304ceda1|31a5c99433f2667029accb1b772d0c8b5ed04004'
I1212 22:22:07.043828 67179 core_worker.cc:97] Constructing core worker with worker ID 31a5c99433f2667029accb1b772d0c8b5ed04004
I1212 22:22:07.044101 67186 core_worker.cc:97] Constructing core worker with worker ID ca376a7326a613f6af47d4ad249fbc2e304ceda1
I1212 22:22:07.320737 67179 raylet_client.cc:214] Creating raylet client with worker ID 31a5c99433f2667029accb1b772d0c8b5ed04004 and port 39607
I1212 22:22:07.331719 67186 raylet_client.cc:214] Creating raylet client with worker ID ca376a7326a613f6af47d4ad249fbc2e304ceda1 and port 39607
W1212 22:22:07.359455 67179 raylet_transport.cc:27] Received task for mismatched WorkerID ca376a7326a613f6af47d4ad249fbc2e304ceda1
(py3)
```

```
$ grep 'worker server started' ./java_worker20191212-222207.67150
I1212 22:22:07.009845 67180 grpc_server.cc:57] worker server started, listening on port 35279.
I1212 22:22:07.010102 67185 grpc_server.cc:57] worker server started, listening on port 36199.
I1212 22:22:07.045218 67184 grpc_server.cc:57] worker server started, listening on port 37533.
I1212 22:22:07.045234 67183 grpc_server.cc:57] worker server started, listening on port 36609.
I1212 22:22:07.099090 67182 grpc_server.cc:57] worker server started, listening on port 42525.
I1212 22:22:07.099107 67187 grpc_server.cc:57] worker server started, listening on port 33725.
I1212 22:22:07.099473 67179 grpc_server.cc:57] worker server started, listening on port 39607.
I1212 22:22:07.100567 67181 grpc_server.cc:57] worker server started, listening on port 38541.
I1212 22:22:07.101475 67178 grpc_server.cc:57] worker server started, listening on port 44129.
I1212 22:22:07.103190 67186 grpc_server.cc:57] worker server started, listening on port 39607.
```

```
$ cat ./raylet-2019-12-12_22-22-5-02985.out | grep 'Assigned task' | grep df716c09effe2bfcffffffff0100
I1212 22:22:07.358687 67125 node_manager.cc:2287] Assigned task df716c09effe2bfcffffffff0100 to worker ca376a7326a613f6af47d4ad249fbc2e304ceda1
```

### Reproduction
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```
export RAY_INSTALL_JAVA=1
pip install -e python -v
while ./java/test.sh; do echo success; done
```

### PR DESCRIPTION
**Pull request by kfstorm**
## Why are these changes needed?

GRPC enables the `SO_REUSEPORT` option by default. See https://lwn.net/Articles/542629/ for details about this option.

However, ray doesn't need this option because we have no need to load balancing requests between different grpc servers. Actually, if this option is enabled, we may see multiple workers listen on the same port and the requests sent to this port may be handled by any of the workers.

## Related issue number

Closes https://github.com/ray-project/ray/issues/6460

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

File: src/ray/rpc/grpc_server.cc [hunk 1]
```diff
@@ -3,19 +3,7 @@
...
-  struct sockaddr_in server_addr = {0};
-  server_addr.sin_family = AF_INET;
-  server_addr.sin_addr.s_addr = htonl(INADDR_ANY);
-  server_addr.sin_port = htons(port);
-  return fd.get() >= 0 &&
-         bind(fd.get(), (struct sockaddr *)&server_addr, sizeof(server_addr)) == 0;
-}
-
-}  // namespace
+namespace {}  // namespace
```
Comment (zhijunfu) [inline src/ray/rpc/grpc_server.cc]: this can be removed.

**Review by zhijunfu — APPROVED** [review]
Nice finding, thanks!

File: src/ray/rpc/grpc_server.cc (hunk 1 above)
Comment (kfstorm) [reply src/ray/rpc/grpc_server.cc]: Thanks! Removed.

**Comment by ericl** [comment]
I've never seen multiple workers listen on the same port. Is this something that happens on Java only? In Python you can have the port reused, but only after the previous server dies, which is not the same as the port reused allowed by this flag.

**Comment by kfstorm** [comment]
@ericl, A Java worker process can have multiple logical workers, which means multiple grpc servers. That’s why you can see several logs about "worker server started" in the same log file as described in the issue #6460.

**Comment by ericl** [comment]
Looks like there are some segfaults in the core worker test.

**Comment by kfstorm** [comment]
@ericl Can't repro at local. Let me rerun the CI.

**Comment by kfstorm** [comment]
@ericl The core worker test has passed. I suspect that the crash is not related to this PR.

**Review by ericl — APPROVED** [review]
