### PR TITLE
Set RAY_FORCE_DIRECT=1 for run_rllib_tests, test_basic

### LINKED ISSUE #6264: Memory corruption for inline args if RAY_FORCE_DIRECT=1
The following will fail if RAY_FORCE_DIRECT=1. The issue seems to be that inline args aren't properly ref-counted in the object store.

```
import ray
import numpy as np

@ray.remote
def f():
    return np.zeros(1000, dtype=np.uint8)

@ray.remote
class Actor:
    def __init__(self):
        self.z = []

    def add(self, x):
        self.z.append(x)
        for prev in self.z:
            assert np.sum(prev) == 0, ("memory corruption detected", prev)
        print("iteration", len(self.z))

ray.init()
a = Actor.remote()
for i in range(5000):
    ray.get(a.add.remote(f.remote()))
```

This is causing APEX_DDPG in https://github.com/ray-project/ray/pull/6171 to sometimes flake.

### PR DESCRIPTION
**Pull request by ericl**
## Related issue number

Closes https://github.com/ray-project/ray/issues/6264

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
jenkins retest this please

File: python/ray/tests/BUILD [hunk 1]
```diff
@@ -1,11 +1,19 @@
...
     srcs = ["test_actor.py"],
     tags = ["exclusive"],
     deps = ["//:ray_lib"],
 )
 
+py_test(
+    name = "test_actor_direct",
+    size = "medium",
+    srcs = ["test_actor_direct.py", "test_actor.py"],
+    tags = ["exclusive", "manual"],
```
Comment (ericl) [inline python/ray/tests/BUILD]: test_actor_load_balancing is flaky, so setting it to MANUAL for now

File: python/ray/tests/BUILD [hunk 2]
```diff
@@ -24,16 +32,16 @@ py_test(
...
+    size = "medium",
     srcs = ["test_basic.py"],
     tags = ["exclusive"],
     deps = ["//:ray_lib"],
 )
 
 py_test(
-    name = "test_advanced",
-    size = "large",
-    srcs = ["test_advanced.py"],
```
Comment (stephanie-wang) [inline python/ray/tests/BUILD]: Should this have been removed?

File: src/ray/core_worker/transport/dependency_resolver.cc [hunk 3]
```diff
@@ -42,7 +42,7 @@ void DoInlineObjectValue(const ObjectID &obj_id, std::shared_ptr<RayObject> valu
   RAY_CHECK(found) << "obj id " << obj_id << " not found";
 }
 
-void LocalDependencyResolver::ResolveDependencies(const TaskSpecification &task,
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/dependency_resolver.cc]: Why no more const?

File: src/ray/core_worker/core_worker.cc [hunk 4]
```diff
@@ -620,7 +616,12 @@ Status CoreWorker::CreateActor(const RayFunction &function,
   *return_actor_id = actor_id;
   TaskSpecification task_spec = builder.Build();
   PinObjectReferences(task_spec, TaskTransportType::RAYLET);
-  return raylet_client_->SubmitTask(task_spec);
+  // TODO(ekl) if we moved actor creation to use direct call tasks, then we won't
+  // need to manually resolve direct call args here.
+  resolver_->ResolveDependencies(task_spec, [this, task_spec]() {
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc]: Just wondering, was there a test that was failing with the old version of this?

**Review by stephanie-wang — APPROVED** [review]

**Comment by ericl** [comment]
Interestingly, the RLlib test is failing with corrupted sample data returned.

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -873,7 +874,7 @@ Status CoreWorker::BuildArgsForExecutor(const TaskSpecification &task,
         metadata = std::make_shared<LocalMemoryBuffer>(
             const_cast<uint8_t *>(task.ArgMetadata(i)), task.ArgMetadataSize(i));
       }
-      args->at(i) = std::make_shared<RayObject>(data, metadata);
+      args->at(i) = std::make_shared<RayObject>(data, metadata, /*copy_data*/ true);
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc]: FYI @edoakes @stephanie-wang this fixes https://github.com/ray-project/ray/issues/6264

File: src/ray/core_worker/core_worker.cc (hunk 4 above)
Comment (ericl) [reply src/ray/core_worker/core_worker.cc]: Yeah, it causes rllib ES to hang, since we pass an object id to an actor constructor there.

File: python/ray/tests/BUILD (hunk 2 above)
Comment (ericl) [reply python/ray/tests/BUILD]: Oops, fixed.

File: src/ray/core_worker/transport/dependency_resolver.cc (hunk 3 above)
Comment (ericl) [reply src/ray/core_worker/transport/dependency_resolver.cc]: Since this mutates the task, it is weird to call it const.

**Comment by ericl** [comment]
hm //python/ray/tests:test_multi_node seems to be consistently failing in bazel, but passes locally.

**Comment by ericl** [comment]
multi_node_test errors seem to be due to breakage on master
