### PR TITLE
[core][serve][autoscaler] Fix resource time rounding down makes idle reporting incorrect

### LINKED ISSUE #38690: [core][serve][autoscaler] Idle time not reported correctly when resource check and report happens too close
### What happened + What you expected to happen

When we update resource usages, we mark if a certain resource is idle, and if so, we will have an idle time associated with this resource, that will be reported to GCS. 

When we report immediately after marking a resource usage idle, the idle time will be rounded down to **miliseconds**, which might be 0 if report to quickly after marking. 

This will make the node appear non-idle even though there's no more resource usages. 

### Versions / Dependencies

master

### Reproduction script

NA

### Issue Severity

None

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?
https://github.com/ray-project/ray/issues/38690

This makes sure when a node is idle (from resources perspective), it will always report idle time in miliseconds even if it's been idle less than 1 millisecond. 

## Related issue number
Fixes https://github.com/ray-project/ray/issues/38690

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/scheduling/local_resource_manager.cc [hunk 1]
```diff
@@ -429,9 +429,16 @@ std::optional<syncer::RaySyncMessage> LocalResourceManager::CreateSyncMessage(
...
 
-  const auto now = absl::Now();
-  resources_data.set_idle_duration_ms(
-      absl::ToInt64Milliseconds(now - GetResourceIdleTime().value_or(now)));
+  auto idle_time = GetResourceIdleTime();
+  if (idle_time.has_value()) {
+    // We round up the idle duration to the nearest millisecond such that the idle
+    // reporting would be correct even if it's less than 1 millisecond.
+    // This is needed since we will not be reporting resource usage if there's no more
+    // change due to lightweight resource reporting.
```
Comment (jjyao) [inline src/ray/raylet/scheduling/local_resource_manager.cc:437]:
```suggestion
    // We round UP the idle duration to the nearest millisecond such that the idle
    // reporting would be correct even if it's less than 1 millisecond.
    // Otherwise, we will report idle millisecond as 0 and autoscaler will think that the node is not idle which is wrong.```

I feel we don't need to mention lightweight resource reporting: regardless of whether we have lightweight or heavyweight resource reporting, we need to make sure every idle report is correct.

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 2]
```diff
@@ -12,6 +13,12 @@
 from ray.util.state.api import list_placement_groups, list_tasks
 
 
+def is_head_node_from_resource_usage(usage: Dict[str, float]) -> bool:
+    if "node:__internal_head__" in usage:
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:17]: You can use `HEAD_NODE_RESOURCE_NAME`

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 3]
```diff
@@ -200,6 +207,111 @@ def verify():
...
+            assert node.used_resources()["object_store_memory"] > 0
+            return True
+
+    wait_for_condition(verify)
+
+    del obj
+
+    import time
+
+    time.sleep(1)
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:229]: why do we need sleep here?

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 4]
```diff
@@ -200,6 +207,111 @@ def verify():
...
+            for node in cluster_state.healthy_nodes:
+                assert node.node_status == "RUNNING"
+                if not is_head_node_from_resource_usage(node.total_resources()):
+                    available = node.available_resources()
+                    assert available["CPU"] == 0
+            return True
+
+        wait_for_condition(verify)
+
+        # Downscale to 1 replicas, 2 workers nodes should be idle.
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:286]: this comment doesn't match the code

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 5]
```diff
@@ -200,6 +207,111 @@ def verify():
...
+        head_resources={"CPU": 0},
+        worker_node_types={
+            "type-1": {
+                "resources": {"CPU": 4},
+                "node_config": {},
+                "min_workers": 0,
+                "max_workers": 30,
+            },
+        },
+        idle_timeout_minutes=1,
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:254]: should it be very large to basically disable idle termination?

File: python/ray/autoscaler/v2/tests/test_e2e.py [hunk 6]
```diff
@@ -200,6 +207,111 @@ def verify():
...
+            for node in cluster_state.healthy_nodes:
+                if not is_head_node_from_resource_usage(node.total_resources()):
+                    available = node.available_resources()
+                    if node.node_status == "IDLE":
+                        assert available["CPU"] == 4
+                        idle_nodes.append(node)
+            from rich import print
+
+            print(cluster_state.healthy_nodes)
+            assert len(idle_nodes) == 3
```
Comment (jjyao) [inline python/ray/autoscaler/v2/tests/test_e2e.py:304]: 3 depends on that the remaining two replicas are on two nodes, which is not guaranteed. It's better to downscale to 1 replica and verify that 4 nodes are idle.

**Review by jjyao — COMMENTED** [review]
Could you also add c++ test?

File: python/ray/autoscaler/v2/tests/test_e2e.py (hunk 3 above)
Comment (rickyyx) [reply python/ray/autoscaler/v2/tests/test_e2e.py:229]: to assert on the idle time has an impact.

File: python/ray/autoscaler/v2/tests/test_e2e.py (hunk 5 above)
Comment (rickyyx) [reply python/ray/autoscaler/v2/tests/test_e2e.py:254]: test will run within 1 min i guess? but open to make it large.

File: python/ray/autoscaler/v2/tests/test_e2e.py (hunk 6 above)
Comment (rickyyx) [reply python/ray/autoscaler/v2/tests/test_e2e.py:304]: sg

File: src/ray/raylet/scheduling/local_resource_manager_test.cc [hunk 7]
```diff
@@ -12,6 +12,10 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+// Don't know why macro redefinition happens, but this is failing windows
+// build.
+#pragma warning(disable : 4005)
```
Comment (jjyao) [inline src/ray/raylet/scheduling/local_resource_manager_test.cc:17]: which macro is redefined?

**Review by jjyao — APPROVED** [review]

File: src/ray/raylet/scheduling/local_resource_manager_test.cc (hunk 7 above)
Comment (rickyyx) [reply src/ray/raylet/scheduling/local_resource_manager_test.cc:17]: BOOST_NO_CXX98_FUNCTION_BASE 
see this: https://buildkite.com/ray-project/oss-ci-build-pr/builds/32960#018a1a16-ce52-4591-a9ab-29301082b57b

Comment (rickyyx) [reply src/ray/raylet/scheduling/local_resource_manager_test.cc:17]: actually - i think the test failure didn't seem to be due to redefinition. https://buildkite.com/ray-project/oss-ci-build-pr/builds/32995#018a1a65-b371-482e-8a62-9fa426c4922b

still fails even though there's no more redefinition on the `local_resource_manager_test`
