### PR TITLE
[Serialization] Fix buffer alignment issues

### LINKED ISSUE #11760: [Core] Ray breaks alignment for NumPy arrays of doubles
### What is the problem?
I'm using Ray 1.0.0 with Python 3.8.3 on Ubuntu 18.04

When I use Ray to serialize/deserialize a NumPy array of doubles, I get an unaligned NumPy array (data is not 8-byte aligned).

### Reproduction

Here is a reproducer I use
```
import numpy as np
import ray
ray.init()

arr1 = np.array([10.1, 20.2, 30.3], dtype = np.double)
oid = ray.put(arr1)
arr2 = ray.get(oid)

ptr1 = arr1.__array_interface__["data"][0]
print(f"Original address: 0x{hex(ptr1)} - {'un' if ptr1 % 8 != 0 else ''}aligned")
assert(ptr1 % 8 == 0)
ptr2 = arr2.__array_interface__["data"][0]
print(f"Deserialized address: 0x{hex(ptr2)} - {'un' if ptr2 % 8 != 0 else ''}aligned")
assert(ptr2 % 8 == 0)
```

The output is:
```
Original address: 0x0x56150a88c9d0 - aligned
Deserialized address: 0x0x7f738756010c - unaligned
Traceback (most recent call last):
  File "1.py", line 14, in <module>
    assert(ptr2 % 8 == 0)
AssertionError
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by suquark**
## Why are these changes needed?

The plasma allocated buffers are 64-byte aligned. However, recently we append a msgpack header before our serialization context, so the serialized content are not aligned to 64 bytes in the plasma allocated buffers. This PR fixes the issue.

## Related issue number

Closes #11760

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by pcmoritz** [comment]
@suquark There are some serialization related test failures, can you have a look?

**Comment by suquark** [comment]
Hmmm, I find another issue is that the memory allocated by `LocalMemoryBuffer` is not aligned. Trying to find a cross-platform aligned allocator...

**Comment by pcmoritz** [comment]
Where do the bytes you see unaligned from the `LocalMemoryBuffer` buffer come from (in terms of code location)?

**Comment by suquark** [comment]
@pcmoritz https://github.com/ray-project/ray/blob/1c132f2ff89ce1ecbee5b2b3c26eac92ec6c214d/python/ray/_raylet.pyx#L309-L313

**Comment by pcmoritz** [comment]
Thanks, this looks good to me, there are a few compilation errors in some of the test remaining, can you fix them @suquark?

**Comment by pcmoritz** [comment]
Let's also make sure to copy this file

https://github.com/NickStrupat/AlignedMalloc/blob/master/LICENSE

into the header of aligned_alloc.h and aligned_alloc.c :)

File: src/ray/common/buffer.h [hunk 1]
```diff
@@ -65,10 +69,10 @@ class LocalMemoryBuffer : public Buffer {
       : has_data_copy_(copy_data) {
     if (copy_data) {
       RAY_CHECK(data != nullptr);
-      buffer_.resize(size);
-      std::copy(data, data + size, buffer_.begin());
-      data_ = buffer_.data();
-      size_ = buffer_.size();
+      buffer_ = (uint8_t *)aligned_malloc(size, BUFFER_ALIGNMENT);
```
Comment (pcmoritz) [inline src/ray/common/buffer.h:72]: consider using `reinterpret_cast<uint8_t *>` here (and in line 84 too).

**Review by pcmoritz — APPROVED** [review]
