### PR TITLE
[core] Queue subscription/unsubscription commands in the GCS

### LINKED ISSUE #8687: [ray] Consistent Crashes w/ Actor-Handle-Based Implementation of Parquet File Compactor
### What is the problem?
I’ve been running a task-based compactor against production Parquet datasets successfully and stably for the last few days, but just had my first crash with an actor-handle-based compactor running against a relatively small ~7GB parquet input dataset (divided into 20MB chunks).

The original pure-task-based compactor launches one distributed task per input delta in a table’s stream, takes a hash of the primary key modulo a desired number of buckets to group “like” primary keys together, saves each parallel task’s bucket groupings into distinct S3 files, and then "compacts" (i.e. sorts by sort key columns and dedupes by primary keys) these like-groupings by creating one parallel compaction task per hash bucket index.

The actor-based compactor I was just testing tries to reduce the number of small hash bucket grouping files by passing a list of hash bucket actor handles into the task - in this case 75 for 75 hash buckets. Basically this:
``` python
@ray.remote
class HashBucket:
    def __init__(self, ):
        self.dataframes = list()
    def append(self, dataframe):
        self.dataframes.append(dataframe)
    def write(self, file_path):
        output = next(iter(self.dataframes)) if len(self.dataframes) == 1 \
            else pd.concat(self.dataframes, axis=0, copy=False)
        output.to_parquet(file_path)
```
So, whereas each parallel task would previously just write multiple small dataframe parquet file to S3 for the same bucket, they now call hashBucket.append.remote(dataframe).

This step went just fine.

Once all appends have completed, I iterate through the completed hash buckets to produce 1 output file in S3 per bucket, like so:
``` python
 write_tasks_pending = []
    for hash_bucket_index in all_hash_bucket_indices:
        file_path = #[...]
        write_task_promise = hb_actors[hash_bucket_index].write.remote(file_path)
        write_tasks_pending.append(write_task_promise)
    while len(write_tasks_pending):
        write_task_complete, write_tasks_pending = ray.wait(write_tasks_pending)
```
The failure occurred here - it wrote several outputs successfully, then crashed with the following stack trace (while calling hb_actors[hash_bucket_index].write.remote(file_path)):
[simple_compactor_actor_stack_trace.txt](https://github.com/ray-project/ray/files/4707110/simple_compactor_actor_stack_trace.txt)

Subsequent ray exec attempts then fail to connect to the cluster:
```
2020-05-27 23:24:06,509	INFO updater.py:201 -- NodeUpdater: i-09bf37eaf088eef3d: Waiting for IP...
2020-05-27 23:24:06,510	INFO log_timer.py:17 -- NodeUpdater: i-09bf37eaf088eef3d: Got IP [LogTimer=571ms]
2020-05-27 23:24:06,510	INFO updater.py:257 -- NodeUpdater: i-09bf37eaf088eef3d: Running python ./simple_compactor_actors.py “compactor” “compactor” “testTableStreamId” ‘[“customer_id”,“session_id”]’ ‘[“dw_insert_date”]’ 1_000_000 75 on 54.84.223.16...
E0528 06:24:29.959751 24475 24475 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-05-27_14-47-54_876303_4354/sockets/raylet (num_attempts = 1, num_retries = 5)
E0528 06:24:30.459939 24475 24475 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-05-27_14-47-54_876303_4354/sockets/raylet (num_attempts = 2, num_retries = 5)
E0528 06:24:30.960027 24475 24475 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-05-27_14-47-54_876303_4354/sockets/raylet (num_attempts = 3, num_retries = 5)
E0528 06:24:31.460111 24475 24475 raylet_client.cc:69] Retrying to connect to socket for pathname /tmp/ray/session_2020-05-27_14-47-54_876303_4354/sockets/raylet (num_attempts = 4, num_retries = 5)
F0528 06:24:31.960207 24475 24475 raylet_client.cc:78] Could not connect to socket /tmp/ray/session_2020-05-27_14-47-54_876303_4354/sockets/raylet
*** Check failure stack trace: ***
  @   0x7f2cd19a6afd google::LogMessage::Fail()
  @   0x7f2cd19a7f6c google::LogMessage::SendToLog()
  @   0x7f2cd19a67d9 google::LogMessage::Flush()
  @   0x7f2cd19a69f1 google::LogMessage::~LogMessage()
  @   0x7f2cd1726439 ray::RayLog::~RayLog()
  @   0x7f2cd15010cd ray::raylet::RayletConnection::RayletConnection()
  @   0x7f2cd1501a5c ray::raylet::RayletClient::RayletClient()
  @   0x7f2cd149dc37 ray::CoreWorker::CoreWorker()
  @   0x7f2cd14a1ac4 ray::CoreWorkerProcess::CreateWorker()
  @   0x7f2cd14a204f ray::CoreWorkerProcess::CoreWorkerProcess()
  @   0x7f2cd14a269b ray::CoreWorkerProcess::Initialize()
  @   0x7f2cd140d064 __pyx_pw_3ray_7_raylet_10CoreWorker_1__cinit__()
  @   0x7f2cd140e145 __pyx_tp_new_3ray_7_raylet_CoreWorker()
  @   0x55eb57a1a725 type_call
  @   0x55eb5799338b _PyObject_FastCallDict
  @   0x55eb57a1a58e call_function
  @   0x55eb57a3ea1a _PyEval_EvalFrameDefault
  @   0x55eb57a13b3e _PyEval_EvalCodeWithName
  @   0x55eb57a146b1 fast_function
  @   0x55eb57a1a515 call_function
  @   0x55eb57a3f734 _PyEval_EvalFrameDefault
  @   0x55eb57a13814 _PyEval_EvalCodeWithName
  @   0x55eb57a146b1 fast_function
  @   0x55eb57a1a515 call_function
  @   0x55eb57a3f734 _PyEval_EvalFrameDefault
  @   0x55eb57a151c9 PyEval_EvalCodeEx
  @   0x55eb57a15f5c PyEval_EvalCode
  @   0x55eb57a985e4 run_mod
  @   0x55eb57a989e1 PyRun_FileExFlags
  @   0x55eb57a98be4 PyRun_SimpleFileExFlags
  @   0x55eb57a9c6c4 Py_Main
  @   0x55eb5796452e main
Shared connection to 54.84.223.16 closed.
Error: Command failed:
```

*Ray version and other system information (Python version, TensorFlow version, OS):*
Python 3.6
https://github.com/ray-project/ray/commit/99cc2e28b3f1f11b51c857c0fdffc7c9f64444cf
4 r5n-8xlarge instances in us-east-1 w/ ami-0dbb717f493016a1a (Deep Learning AMI, Ubuntu 18.04, Version 27.0)

### Reproduction (REQUIRED)
Reproduction relies on the files available at https://github.com/ray-project/ray/pull/8707.

1) Create an S3 bucket like "compactor-8687"
2) Create an "input" S3 folder within this bucket, and place 7GB+ of Parquet file input files (w/ 20MB per file to reproduce the original scenario). Ensure that each input file follows the naming convention: {tableStreamId}-{eventTimeInt}.[parq|parquet]. For example, testTableStreamId-0.parq" is a valid input file name for table steam ID "testTableStreamId" and event time "0". 
3) Stand up a new Ray cluster from https://github.com/ray-project/ray/blob/2d167062ccd64fc8c65a2a1be75cbe6a675fb978/doc/examples/compactor/compactor.yaml, sync https://github.com/ray-project/ray/blob/2d167062ccd64fc8c65a2a1be75cbe6a675fb978/doc/examples/compactor/compactor_actors_example.py, and run it with a command of the following form:
```
ray exec ./compactor.yaml 'python ./compactor_actors_example.py "compactor-8687" "compactor-8687" "testTableStreamId" --primary-keys "primary_key_column_1" "primary_key_column_2" --sort-keys "sort_key_column_1" --records-per-output-file 1_000_000 --hash-bucket-count 75'
```
4) Verify that the above failure occurs while attempting to write Parquet output files with the HashBucket actor.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Pubsub in #8180 and the subsequent PRs is broken because it assumes that the client waits for a successful subscription reply before it sends a command to unsubscribe, and vice versa. This problem can easily be triggered with the included unit test that repeatedly subscribes/unsubscribes to the same key. The test would hang on master.

This PR fixes the problem by queuing subscription commands to the same key and only sending a command once the previous command's reply has been received.

## Related issue number

fixes #8687 looks related, possibly fixed by this PR.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

**Comment by stephanie-wang** [comment]
@ffbin, can you write a regression test for this? I don't understand the pubsub logic well enough to figure it out. Also, do you know why this issue was coming up? And I was still seeing the issue even with this PR.

**Comment by ffbin** [comment]
@stephanie-wang I will write a regression test for this, thanks.

**Comment by rkooo567** [comment]
@stephanie-wang Is it a P0 issue? Also, is this PR related? https://github.com/ray-project/ray/pull/8760

**Comment by stephanie-wang** [comment]
> @stephanie-wang Is it a P0 issue? Also, is this PR related? #8760

Yes, I think it's a P0 because of the related issues that we've been seeing. It's hard to come up with a small reproducible script in Python, but I'm working on reproducing the issue in C++.

I think we need to fix either this PR or #8760, but I'm not sure of the best approach yet.

**Review by rkooo567 — COMMENTED** [review]
~~I might misunderstand, but it seems like when one subscription request succeed, any followup subscription command won't be actually sent until unsubscribe succeeds? I am curious if it is the possible scenario.~~

~~Sends 5 command asynchronously
SUBSCRIBE call_index = -1
SUBSCRIBE call_index = -1
SUBSCRIBE call_index = -1
SUBSCRIBE call_index = -1
UNSUBSCRIBE call_index = -1~~

~~Replied in this order
SUBSCRIBE
SUBSCRIBE
SUBSCRIBE
UNSUBSCRIBE
SUBSCRIBE => hanging?~~

Oh got it. UNSUBSCRIBE cannot be sent until SUBSCRIBE succeeds.

**Comment by stephanie-wang** [comment]
> I might misunderstand, but it seems like when one subscription request succeed, any followup subscription command won't be actually sent until unsubscribe succeeds? I am curious if it is the possible scenario.
> 
> Sends 5 command asynchronously
> SUBSCRIBE
> SUBSCRIBE
> SUBSCRIBE
> SUBSCRIBE
> UNSUBSCRIBE
> 
> Replied in this order
> SUBSCRIBE
> SUBSCRIBE
> SUBSCRIBE
> UNSUBSCRIBE
> SUBSCRIBE => hanging?

Actually the code requires that the caller alternates between `SUBSCRIBE` and `UNSUBSCRIBE`. The code ensures that the Redis client will not send an `UNSUBSCRIBE` command until the reply for the last `SUBSCRIBE` command is received. If the client calls `SUBSCRIBE` or `UNSUBSCRIBE` twice in a row, the code will throw an assertion failure.

I just realized, though, that I think there is a bug where it's possible to send a second `SUBSCRIBE` command if the previous command was also `SUBSCRIBE` and we didn't receive the reply yet. I'll update it to make sure this doesn't happen.

File: src/ray/gcs/pubsub/gcs_pub_sub.cc [hunk 1]
```diff
@@ -44,52 +44,104 @@ Status GcsPubSub::SubscribeAll(const std::string &channel, const Callback &subsc
...
+Status GcsPubSub::ExecuteCommandIfPossible(const std::string &channel_key,
+                                           GcsPubSub::Channel &channel) {
+  // Process the first command on the queue, if possible.
+  Status status;
+  auto &command = channel.command_queue.front();
+  if (command.is_subscribe && channel.callback_index == -1) {
+    int64_t callback_index =
+        ray::gcs::RedisCallbackManager::instance().AllocateCallbackIndex();
+    const auto &command_done = command.done_callback;
+    const auto &command_subscribe = command.subscribe_callback;
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/gcs/pubsub/gcs_pub_sub.cc:89]: Sure, I'll rename it!

**Comment by rkooo567** [comment]
I am not familiar with Redis pub/sub, but given it is okay to send two subscribe requests in a row, it is not a bug I guess? I also think it should allow to send the second SUBSCRIBE just in case the first SUBSCRIBE fails.

**Comment by stephanie-wang** [comment]
I think it's okay to require that the caller does not send duplicate subscribe requests since a) the caller can easily track whether it's subscribed or not to each channel, and b) the backend actually already uses these semantics.

For failure scenarios, I think it's a bit of an orthogonal issue because you can always retry the same subscribe request multiple times.

**Comment by rkooo567** [comment]
That makes sense. I have one more concerned scenario. Let's say 

SUB
succeeds
SUB
UNSUB

=> In this case, isn't UNSUB never be called?

**Comment by stephanie-wang** [comment]
> That makes sense. I actually have one more concerned scenario. Let's say
> 
> SUB
> succeeds
> SUB
> UNSUB
> 
> => In this case, isn't UNSUB never be called? We should probably iterate all the command in the queue and execute other commands behind blocked commands?

Hmm I don't think this is possible. The code asserts that the order of commands executed is always SUB UNSUB SUB UNSUB, etc.

**Comment by rkooo567** [comment]
It seems to me like this part https://github.com/ray-project/ray/blob/01a20f59b62eeb9cf76b0eeb131fa530cff93196/src/ray/gcs/pubsub/gcs_pub_sub.cc#L74 will just add a new command to the queue if two `SubscribeInternal` is called in a row. And command will never pop because the call_index is not -1 anymore. Please just ignore the message if it doesn't make sense to you. I might miss something.

**Comment by stephanie-wang** [comment]
Oh yeah, you're totally right about that, but since you brought it up I added a check for this scenario :)

https://github.com/ray-project/ray/blob/3c61b08ab26150a6eac850eb981110e3500fa9be/src/ray/gcs/pubsub/gcs_pub_sub.cc#L152

But please make sure to read it over in case I missed something! Unfortunately it's difficult to capture in the unit tests because of the fatal error, but I did check manually to make sure the check is working.

**Comment by rkooo567** [comment]
I see. So we just don't allow the duplicated subscribe calls in the first place. That makes sense. Other than this, I don't think I have any other thought to the PR!

**Review by rkooo567 — APPROVED** [review]

File: src/ray/gcs/pubsub/gcs_pub_sub.h [hunk 2]
```diff
@@ -89,6 +90,52 @@ class GcsPubSub {
   Status Unsubscribe(const std::string &channel, const std::string &id);
 
  private:
+  struct SubscribeCommand {
```
Comment (ffbin) [inline src/ray/gcs/pubsub/gcs_pub_sub.h:93]: It's maybe confusing. Actually, it's the command of sub or unsub.

File: src/ray/gcs/pubsub/gcs_pub_sub.cc [hunk 3]
```diff
@@ -44,52 +44,113 @@ Status GcsPubSub::SubscribeAll(const std::string &channel, const Callback &subsc
...
-    absl::MutexLock lock(&mutex_);
-    // If the same pattern has been subscribed more than once, the last subscription takes
-    // effect.
-    subscribe_callback_index_[pattern] = out_callback_index;
+    };
+    status = redis_client_->GetPrimaryContext()->PSubscribeAsync(channel_key, callback,
+                                                                 callback_index);
+    channel.pending_reply = true;
+    channel.command_queue.pop_front();
+  } else if (!command.is_subscribe && channel.callback_index != -1) {
```
Comment (ffbin) [inline src/ray/gcs/pubsub/gcs_pub_sub.cc:145]: How about add some comments to the conditional judgment branch?

File: src/ray/gcs/pubsub/gcs_pub_sub.cc [hunk 4]
```diff
@@ -44,52 +44,113 @@ Status GcsPubSub::SubscribeAll(const std::string &channel, const Callback &subsc
...
+    status = redis_client_->GetPrimaryContext()->PUnsubscribeAsync(channel_key);
+    channel.pending_reply = true;
+    channel.command_queue.pop_front();
+  } else if (!channel.pending_reply) {
+    // There is no in-flight command, but none of the queued commands are
+    // runnable. The caller must have sent a command out-of-order.
+    RAY_LOG(FATAL) << "Caller attempted a duplicate subscribe or unsubscribe to channel "
```
Comment (ffbin) [inline src/ray/gcs/pubsub/gcs_pub_sub.cc:152]: When gcs server restarts, gcs client should re-subscribe. Now we must unsubscribe first if we want re-subscribe, how about add some comments to Subscribe API ?

File: src/ray/gcs/pubsub/test/gcs_pub_sub_test.cc [hunk 5]
```diff
@@ -129,6 +131,29 @@ TEST_F(GcsPubSubTest, TestPubSubApi) {
...
+TEST_F(GcsPubSubTest, TestManyPubsub) {
+  std::string channel("channel");
+  std::string id("id");
+  std::string data("data");
+  std::vector<std::pair<std::string, std::string>> all_result;
+  SubscribeAll(channel, all_result);
+  // Test many concurrent subscribes and unsubscribes.
+  for (int i = 0; i < 1000; i++) {
+    std::vector<std::string> result;
+    Subscribe(channel, id, result);
```
Comment (ffbin) [inline src/ray/gcs/pubsub/test/gcs_pub_sub_test.cc:143]: Subscribe is a sync function, we can use pub_sub_->Subscribe directly.

File: src/ray/gcs/redis_context.cc [hunk 6]
```diff
@@ -203,25 +204,37 @@ void GlobalRedisCallback(void *c, void *r, void *privdata) {
...
+}
+
+int64_t RedisCallbackManager::AddCallback(const RedisCallback &function,
+                                          bool is_subscription,
+                                          boost::asio::io_service &io_service,
+                                          int64_t callback_index) {
   auto start_time = absl::GetCurrentTimeNanos() / 1000;
 
   std::lock_guard<std::mutex> lock(mutex_);
+  if (callback_index == -1) {
```
Comment (ffbin) [inline src/ray/gcs/redis_context.cc:219]: num_callbacks_ is start from 0, why callback_index will be -1, it maybe seems confusing.

File: src/ray/gcs/pubsub/gcs_pub_sub.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/gcs/pubsub/gcs_pub_sub.cc:152]: I don't think this is really necessary yet since the GCS is not fault-tolerant in any meaningful way right now.

File: src/ray/gcs/pubsub/test/gcs_pub_sub_test.cc (hunk 5 above)
Comment (stephanie-wang) [reply src/ray/gcs/pubsub/test/gcs_pub_sub_test.cc:143]: Makes sense, thanks!

File: src/ray/gcs/redis_context.cc (hunk 6 above)
Comment (stephanie-wang) [reply src/ray/gcs/redis_context.cc:219]: -1 means that the callback index is not set.

File: src/ray/gcs/pubsub/gcs_pub_sub.h [hunk 7]
```diff
@@ -89,6 +90,52 @@ class GcsPubSub {
...
+    /// index is set back to -1 if we receive a reply from Redis that we have
+    /// unsubscribed.
+    int64_t callback_index = -1;
+    /// Whether we are pending a reply from Redis. We cannot send another
+    /// command from the queue until this has been reset to false.
+    bool pending_reply = false;
+  };
+
+  /// Execute the first queued command for the given channel, if possible.  A
+  /// subscribe command can execute if the channel's callback index is not set.
```
Comment (ffbin) [inline src/ray/gcs/pubsub/gcs_pub_sub.h:132]: A subscribe command can be executed if the callback index of the channel is not set which means that this is the first subscription of the channel.
A unsubscribe command can be executed if the callback index of the channel is set which means that the channel subscription is completed.

File: src/ray/gcs/pubsub/gcs_pub_sub.cc (hunk 4 above)
Comment (ffbin) [reply src/ray/gcs/pubsub/gcs_pub_sub.cc:157]: We have add test_gcs_fault_tolerance.py, which will test restart gcs server.

Comment (stephanie-wang) [reply src/ray/gcs/pubsub/gcs_pub_sub.cc:157]: Does that test require pubsub? If not, I'll just leave a TODO here that we should retry the last subscribe command.

**Review by ffbin — APPROVED** [review]
LGTM

File: src/ray/gcs/pubsub/gcs_pub_sub.cc (hunk 4 above)
Comment (ffbin) [reply src/ray/gcs/pubsub/gcs_pub_sub.cc:157]: That test require pubsub.

**Comment by rkooo567** [comment]
@stephanie-wang Lmk when you merge this! I will start release testing.

**Comment by stephanie-wang** [comment]
Thanks, @rkooo567! I'm just going to disable the GCS fault tolerance tests for now since those are the only ones failing on the CI and GCS FT is not ready for the release anyway.
