### PR TITLE
[core] Increase worker lease parallelism

### LINKED ISSUE #14997: instability issues in cluster launcher
download the [data](https://drive.google.com/drive/folders/19GGSD_DvdM4Gi_UoVyCwbFVVGqgEWN2D?usp=sharing) (make sure you are logged in to anyscale account) and run:
- `ray up -y example-full.yaml`
- `ray attach example-full.yaml`
- `cd ~/data; python palettes.py`

it generates the errors shown below (1). If you wait 5 minutes and then rerun `python palettes.py` it generated below (2)
(1)
```
2021-03-29 10:08:55,570 INFO worker.py:655 -- Connecting to existing Ray cluster at address: 172.31.27.76:6379                                   [9/1866]
  1%|▊                                                                                                              | 940/134000 [00:08<58:42, 37.77it/s]
  2%|█▉                                                                                                           | 2380/134000 [00:42<18:04, 121.33it/s]
(autoscaler +1m0s) Tip: use `ray status` to view detailed autoscaling status. To disable autoscaler event messages, you can set AUTOSCALER_EVENTS=0.     
(autoscaler +1m0s) Resized to 160 CPUs.                                                                                                                  
(autoscaler +1m0s) Adding 28 nodes of type ray.worker.default.                                                                                           
  3%|███                                                                                                          | 3720/134000 [00:52<14:59, 144.84it/s]
(autoscaler +1m9s) Resized to 192 CPUs.                                                                                                                  
(autoscaler +1m9s) Adding 3 nodes of type ray.worker.default.                                                                                            
  4%|███▊                                                                                                         | 4700/134000 [00:59<15:36, 138.07it/s]
(autoscaler +1m16s) Adding 1 nodes of type ray.worker.default.
 16%|█████████████████▏                                                                                          | 21340/134000 [03:05<09:48, 191.48it/s]
(autoscaler +3m23s) Resized to 256 CPUs.
 17%|██████████████████▍                                                                                         | 22850/134000 [03:13<09:48, 188.72it/s]
(autoscaler +3m30s) Resized to 864 CPUs.
(autoscaler +3m30s) Adding 1 nodes of type ray.worker.default.
 18%|███████████████████▍                                                                                        | 24160/134000 [03:20<12:09, 150.60it/s]
(autoscaler +3m37s) Resized to 1184 CPUs.
 19%|████████████████████▌                                                                                       | 25520/134000 [03:27<09:21, 193.22it/s]
(autoscaler +3m44s) Resized to 1216 CPUs.
 25%|███████████████████████████▍                                                                                | 34080/134000 [04:13<09:01, 184.51it/s]
(autoscaler +4m30s) Removing 1 nodes of type ray.worker.default (idle).
 38%|█████████████████████████████████████████                                                                   | 51010/134000 [05:15<03:10, 436.67it/s]
(autoscaler +5m33s) Resized to 1248 CPUs.
 46%|██████████████████████████████████████████████████                                                          | 62070/134000 [05:39<02:18, 518.51it/s]
(autoscaler +5m57s) Removing 1 nodes of type ray.worker.default (idle).
 49%|████████████████████████████████████████████████████▋                                                       | 65310/134000 [05:46<02:08, 536.08it/s]
(autoscaler +6m3s) Removing 3 nodes of type ray.worker.default (idle).
 52%|███████████████████████████████████████████████████████▊                                                    | 69300/134000 [05:53<01:55, 561.48it/s]
(autoscaler +6m10s) Removing 28 nodes of type ray.worker.default (idle).
 55%|███████████████████████████████████████████████████████████▏                                                | 73430/134000 [05:59<01:28, 680.90it/s]
(autoscaler +6m17s) Removing 4 nodes of type ray.worker.default (idle).
 63%|███████████████████████████████████████████████████████████████████▉                                        | 84260/134000 [06:14<01:07, 739.24it/s]
2021-03-29 10:15:27,188 WARNING worker.py:1107 -- The node with node id 06c9f6941bafd537c595cd60bdc87367a120906a0ca5b90bb5c3b13d has been marked dead bec
ause the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
 65%|█████████████████████████████████████████████████████████████████████▋                                      | 86510/134000 [06:16<01:06, 719.33it/s]
(autoscaler +6m34s) Resized to 1216 CPUs.
(autoscaler +6m34s) Removing 1 nodes of type ray.worker.default (idle).
```
(2)
```
 37%|████████████████████████████████████████▎                                                                   | 50000/134000 [02:56<03:39, 381.92it/s](autoscaler +3m13s) Restarting 3 nodes of type ray.worker.default (lost contact with raylet).
 41%|████████████████████████████████████████████▍                                                               | 55200/134000 [03:08<03:20, 393.50it/s](autoscaler +3m25s) Restarting 1 nodes of type ray.worker.default (lost contact with raylet).
 48%|███████████████████████████████████████████████████▍                                                        | 63860/134000 [03:26<02:21, 496.36it/s](autoscaler +3m43s) Removing 1 nodes of type ray.worker.default (launch failed).
 50%|██████████████████████████████████████████████████████▏                                                     | 67220/134000 [03:33<02:05, 530.40it/s](autoscaler +3m50s) Resized to 128 CPUs.
(autoscaler +3m50s) Removing 1 nodes of type ray.worker.default (idle).
(autoscaler +3m50s) Removing 1 nodes of type ray.worker.default (launch failed).
 53%|████████████████████████████████████████████████████████▉                                                   | 70700/134000 [03:39<01:55, 546.48it/s](autoscaler +3m57s) Resized to 160 CPUs.
(autoscaler +3m57s) Removing 2 nodes of type ray.worker.default (launch failed).
 55%|███████████████████████████████████████████████████████████▊                                                | 74180/134000 [03:46<01:44, 571.46it/s](autoscaler +4m3s) Resized to 192 CPUs.
(autoscaler +4m3s) Removing 3 nodes of type ray.worker.default (launch failed).
 64%|████████████████████████████████████████████████████████████████████▋                                       | 85180/134000 [04:02<01:04, 752.67it/s]2021-03-29 11:56:33,348 WARNING worker.py:1107 -- The node with node id 982af9fb3524a995361645dfb220d97f64a4c864ede40457f206e8c8 has been marked dead because the detector has missed too many heartbeats from it. This can happen when a raylet crashes unexpectedly or has lagging heartbeats.
 64%|█████████████████████████████████████████████████████████████████████▌                                      | 86330/134000 [04:03<01:00, 782.41it/s](autoscaler +4m20s) Resized to 160 CPUs.
 85%|█████████████████████████████████████████████████████████████████████████████████████████▊                | 113540/134000 [04:32<00:16, 1238.87it/s](autoscaler +4m49s) Removing 2 nodes of type ray.worker.default (idle).
 86%|██████████████████████████████████████████████████████████████████████████████████████████▋               | 114590/134000 [04:33<00:11, 1666.62it/s] 86%|██████████████████████████████████████████████████████████████████████████████████████████▊               | 114780/134000 [04:33<00:11, 1723.50it/s]100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 134000/134000 [04:38<00:00, 480.73it/s]
Traceback (most recent call last):
  File "palettes.py", line 42, in <module>
    palettes = ray.get(progress_bar(palettes))
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/_private/client_mode_hook.py", line 47, in wrapper
    return func(*args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.7/site-packages/ray/worker.py", line 1456, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): ray::get_palette() (pid=126, ip=172.31.31.160)
  File "python/ray/_raylet.pyx", line 480, in ray._raylet.execute_task
RuntimeError: This function was not imported properly.
```

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
Currently we only allow 1 outstanding lease request per category,  this PR makes it configurable.

To avoid double counting worker backlog in autoscaler when we have multiple lease requests to different raylets, this PR separates the backlog report and lease request into different RPCs. The backlog report now only goes to home raylet and it has two report cadences:
1. Periodic (every 1s) report to make sure raylet has an eventually consistent view of its worker backlogs even in the case where a single report is lost or reordered.
2. Right after a lease request is sent, we report the worker backlog if the size is changed since last time for the given scheduling key. This makes sure we report backlog change promptly while not sending too many of them like one report for each submitted task (since the number of pending lease requests is capped).

Experiment shows that the time for loading 200 files on 40 nodes decreases from 87s to 67s if we increase the parallelism to 40.

## Related issue number
Closes #14997

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/common/ray_config_def.h [hunk 1]
```diff
@@ -300,6 +300,9 @@ RAY_CONFIG(int64_t, task_rpc_inlined_bytes_limit, 10 * 1024 * 1024)
 /// pipelining task submission.
 RAY_CONFIG(uint32_t, max_tasks_in_flight_per_worker, 1)
 
+/// Maximum number of pending lease requests per scheduling category
+RAY_CONFIG(uint64_t, max_pending_lease_requests_per_scheduling_category, 1)
```
Comment (ericl) [inline src/ray/common/ray_config_def.h:304]: Let's set this to 10 by default.

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 2]
```diff
@@ -434,12 +435,13 @@ CoreWorkerDirectTaskSubmitter::GetOrConnectLeaseClient(
 void CoreWorkerDirectTaskSubmitter::RequestNewWorkerIfNeeded(
     const SchedulingKey &scheduling_key, const rpc::Address *raylet_address) {
   auto &scheduling_key_entry = scheduling_key_entries_[scheduling_key];
-  auto &pending_lease_request = scheduling_key_entry.pending_lease_request;
 
-  if (pending_lease_request.first) {
-    // There's already an outstanding lease request for this type of task.
+  if (scheduling_key_entry.pending_lease_request_task_to_raylet.size() ==
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.cc:439]:
```suggestion
  if (scheduling_key_entry.pending_lease_request_task_to_raylet.size() >=
```

Prefer defensive code

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 3]
```diff
@@ -237,6 +241,8 @@ class CoreWorkerDirectTaskSubmitter {
   // worker using a single lease.
   const uint32_t max_tasks_in_flight_per_worker_;
 
+  const uint64_t max_pending_lease_requests_per_scheduling_category_;
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.h:244]: Comment.

**Review by ericl — COMMENTED** [review]
> Note: parallelism greater than 1 doesn't work with autoscaler now since we double count the backlog size. This will be fixed separately.

Can we fix this in this PR? It seems like not a big change, and blocks enabling this by default.

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 4]
```diff
@@ -296,8 +302,7 @@ class CoreWorkerDirectTaskSubmitter {
 
   struct SchedulingKeyEntry {
     // Keep track of pending worker lease requests to the raylet.
-    std::pair<std::shared_ptr<WorkerLeaseInterface>, TaskID> pending_lease_request =
-        std::make_pair(nullptr, TaskID::Nil());
+    absl::flat_hash_map<TaskID, rpc::Address> pending_lease_request_task_to_raylet;
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.h:305]: Do we still need the raylet address here, or can this be something like a list?

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 2 above)
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.cc:439]: I actually added a RAY_CHECK in the next line to make sure we never exceeds the limit.

File: src/ray/core_worker/transport/direct_task_transport.h (hunk 4 above)
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_task_transport.h:305]:
```suggestion
    absl::flat_hash_map<TaskID, rpc::Address> pending_lease_requests;
```

**Review by stephanie-wang — APPROVED** [review]
Nice, the PR looks pretty clean!

It'd be good to run `ray microbenchmark` or keep an eye on the nightly results for this PR.

File: src/ray/common/ray_config_def.h (hunk 1 above)
Comment (jjyao) [reply src/ray/common/ray_config_def.h]: Done

File: src/ray/core_worker/transport/direct_task_transport.h (hunk 3 above)
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.h:250]: Done

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 5]
```diff
@@ -551,8 +588,9 @@ void CoreWorkerDirectTaskSubmitter::RequestNewWorkerIfNeeded(
           RAY_LOG(FATAL) << status.ToString();
         }
       },
-      queue_size);
-  pending_lease_request = std::make_pair(lease_client, task_id);
+      task_queue.size());
+  scheduling_key_entry.pending_lease_requests.emplace(task_id, *raylet_address);
+  ReportWorkerBacklogIfNeeded(scheduling_key);
```
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.cc:593]: We don't need to: when we report backlog size we don't include tasks with pending or granted lease request.

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 6]
```diff
@@ -66,7 +66,10 @@ class CoreWorkerDirectTaskSubmitter {
       int64_t lease_timeout_ms, std::shared_ptr<ActorCreatorInterface> actor_creator,
       uint32_t max_tasks_in_flight_per_worker =
           ::RayConfig::instance().max_tasks_in_flight_per_worker(),
-      absl::optional<boost::asio::steady_timer> cancel_timer = absl::nullopt)
+      absl::optional<boost::asio::steady_timer> cancel_timer = absl::nullopt,
+      uint64_t max_pending_lease_requests_per_scheduling_category =
+          ::RayConfig::instance().max_pending_lease_requests_per_scheduling_category(),
+      bool report_worker_backlog = ::RayConfig::instance().report_worker_backlog())
```
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.h:72]: Sure,  I assume we don't need to care about backward compatibility here.

[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.h:72]: Actually, if we don't have auto scaling (i.e. min_workers == max_workers), then we don't need to report backlog?

File: src/ray/raylet_client/raylet_client.cc [hunk 7]
```diff
@@ -314,6 +314,21 @@ void raylet::RayletClient::RequestObjectSpillage(
...
+                                               const TaskSpecification &resource_spec,
+                                               const int64_t backlog_size) {
+  rpc::ReportWorkerBacklogRequest request;
+  request.set_worker_id(worker_id.Binary());
+  request.mutable_resource_spec()->CopyFrom(resource_spec.GetMessage());
+  request.set_backlog_size(backlog_size);
+  grpc_client_->ReportWorkerBacklog(
+      request, [](const Status &status, const rpc::ReportWorkerBacklogReply &reply) {
+        if (!status.ok()) {
+          RAY_LOG(INFO) << "Error reporting task backlog information: " << status;
```
Comment (wuisawesome) [inline src/ray/raylet_client/raylet_client.cc:327]: Can we make this a little louder? Maybe warning level since we don't have a periodic report to recover here?

File: src/ray/protobuf/node_manager.proto [hunk 8]
```diff
@@ -19,6 +19,17 @@ package ray.rpc;
 import "src/ray/protobuf/common.proto";
 import "src/ray/protobuf/gcs.proto";
 
+message ReportWorkerBacklogRequest {
+  // Unique id of the worker that's reporting the backlog
+  bytes worker_id = 1;
+  // TaskSpec containing the requested resources.
+  TaskSpec resource_spec = 2;
+  int64 backlog_size = 3;
+}
```
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/protobuf/node_manager.proto:28]: Since backlog size doesn't include tasks with pending lease requests, so whenever we send a lease request, backlog size changes, that's why I call `ReportWorkerBacklogIfNeeded` after requesting lease.

In terms of simplicity, this is actually simpler I think: no timer, no need to figure out the report frequency. Also this matches better with current behavior (i.g. backlog report as part of lease request) so less surprise.

I think the key here is that we decouple lease request and backlog report request so we can always change how we report in the future. @wuisawesome thoughts?

**Review by wuisawesome — APPROVED** [review]
Just want to make sure, it's intended behavior that we keep sending the backlog size in the lease request too right? 

I believe this will cause us to start more worker processes (which IMO is probably fine, but we should just watch out for it).

File: src/ray/common/ray_config_def.h (hunk 1 above)
Comment (ericl) [reply src/ray/common/ray_config_def.h:310]: I'd like to see this PR pass with it set to 10 though before we merge, even if it's off by default. Otherwise, we have code that is not covered by any nightly tests or performance tests.

File: src/ray/core_worker/transport/direct_task_transport.h (hunk 6 above)
[the remark this answers is not in the document]
Comment (ericl) [reply src/ray/core_worker/transport/direct_task_transport.h:72]: We should always report

File: src/ray/protobuf/node_manager.proto (hunk 8 above)
[the remark this answers is not in the document]
Comment (ericl) [reply src/ray/protobuf/node_manager.proto:28]: Actually this makes me think of an important edge case, where a stale backlog can cause extra GPU nodes to get allocated.

Suppose you have two GPU requests and both are leased at the same time. If the autoscaler gets a snapshot of "two pending GPU requests" and "backlog size 1", then it could launch 3 GPU machines.

**Review by ericl — CHANGES_REQUESTED** [review]
Let's discuss the backlog issue offline

File: src/ray/protobuf/node_manager.proto (hunk 8 above)
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/protobuf/node_manager.proto:28]: When raylets reports to autoscaler, it reports both the backlog and pending lease requests. So if backlog also includes pending lease requests, then we will overcount. @wuisawesome correct me if I'm wrong.

[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/protobuf/node_manager.proto:28]: Ah gotcha.

Hmm this actually seems quite complicated if parallel pending lease requests go to different nodes. Not sure if we can get an exact backlog count in that scenario.

**Comment by wuisawesome** [comment]
> Actually this makes me think of an important edge case, where a stale backlog can cause extra GPU nodes to get allocated.
Suppose you have two GPU requests and both are leased at the same time. If the autoscaler gets a snapshot of "two pending GPU requests" and "backlog size 1", then it could launch 3 GPU machines.

@ericl this is what my comment was about. If I'm reading this PR correctly, that won't happen because we're only using the backlog in the lease request to prewarm the worker pool, it's the other RPC that actually sets the backlog size for resource reporting purposes. We might start more worker processes, but we shouldn't launch extra nodes.

**Comment by stephanie-wang** [comment]
> > Actually this makes me think of an important edge case, where a stale backlog can cause extra GPU nodes to get allocated.
> > Suppose you have two GPU requests and both are leased at the same time. If the autoscaler gets a snapshot of "two pending GPU requests" and "backlog size 1", then it could launch 3 GPU machines.
> 
> @ericl this is what my comment was about. If I'm reading this PR correctly, that won't happen because we're only using the backlog in the lease request to prewarm the worker pool, it's the other RPC that actually sets the backlog size for resource reporting purposes. We might start more worker processes, but we shouldn't launch extra nodes.

Isn't this still an issue if the lease requests go to different nodes? I think we will end up double-counting the backlog.

**Comment by wuisawesome** [comment]
> Isn't this still an issue if the lease requests go to different nodes? I think we will end up double-counting the backlog.

We only `client-> ReportWorkerBacklog` to the local raylet. So now the local raylet always receives the backlog from its worker pool (whereas before it was the raylet that responded to the lease request).

@jjyao maybe it would help to describe the new backlog reporting mechanism/policy in the PR description?

File: src/ray/raylet/node_manager.cc [hunk 9]
```diff
@@ -1659,7 +1665,8 @@ void NodeManager::HandleReturnWorker(const rpc::ReturnWorkerRequest &request,
       if (worker->IsBlocked()) {
         HandleDirectCallTaskUnblocked(worker);
       }
-      cluster_task_manager_->ReturnWorkerResources(worker);
+      cluster_task_manager_->ReleaseWorkerResources(worker);
+      cluster_task_manager_->ClearWorkerBacklog(worker_id);
```
Comment (stephanie-wang) [inline src/ray/raylet/node_manager.cc:1669]: I don't think this is the right place to clear the worker backlog. This looks like it gets called when a lease is returned to the raylet, but I think we actually want to clear the backlog if the lease *requestor* is killed, etc.

**Comment by stephanie-wang** [comment]
> > Isn't this still an issue if the lease requests go to different nodes? I think we will end up double-counting the backlog.
> 
> We only `client-> ReportWorkerBacklog` to the local raylet. So now the local raylet always receives the backlog from its worker pool (whereas before it was the raylet that responded to the lease request).
> 
> @jjyao maybe it would help to describe the new backlog reporting mechanism/policy in the PR description?

I see. But I think @ericl's original comment still stands, though. Now that we're separating the RPCs for lease requesting and backlog reporting, they're no longer synchronized, so we can get stale backlog messages at the raylet.

What do you think about splitting this PR into the backlog RPC and the worker lease parallelism? I'm not too worried about the worker lease parallelism part, but the backlog RPC seems a bit tricky to get right.

**Comment by wuisawesome** [comment]
> we can get stale backlog messages at the raylet.

Yes, you can get a stale backlog, but of course, the resource report itself is also always stale to begin with. I think in practice, the staleness goes from (~100ms to ~100ms + rpc time) by the time the info makes its way to GCS.

> What do you think about splitting this PR into the backlog RPC and the worker lease parallelism? I'm not too worried about the worker lease parallelism part, but the backlog RPC seems a bit tricky to get right.

Backlog part is definitely tricky, but if we do split it, we need to do the backlog part first, otherwise we _will_ double count the backlog which would be very bad.

**Comment by ericl** [comment]
Hmm I'd like to see this PR passing e2e performance tests and also all the
unit tests with (1) backlog change on, and (2) parallelism on by default.
We can later decide to split it out, but let's make sure it "works for
real" at least.

Btw, I discussed offline and we think the asynchrony is likely fine. We
could even go further and always report backlog asynchronously from the
core workers to the local raylet (e.g., every 200ms). This would be the
simplest option, at the cost of more race conditions.

File: src/mock/ray/raylet/scheduling/cluster_task_manager_interface.h [hunk 10]
```diff
@@ -33,8 +33,6 @@ class MockClusterTaskManagerInterface : public ClusterTaskManagerInterface {
               (const, override));
   MOCK_METHOD(void, TaskFinished,
               (std::shared_ptr<WorkerInterface> worker, RayTask *task), (override));
-  MOCK_METHOD(void, ReturnWorkerResources, (std::shared_ptr<WorkerInterface> worker),
```
[the remark this answers is not in the document]
Comment (jjyao) [reply src/mock/ray/raylet/scheduling/cluster_task_manager_interface.h:36]: Yea, there is a TODO to remove ReturnWorkerResoruces in favor of ReleaseWorkerResources so I just did that.

File: src/ray/raylet/node_manager.cc (hunk 9 above)
Comment (jjyao) [reply src/ray/raylet/node_manager.cc:1669]: Oh yea, good catch. It's not returning itself but leased workers.

File: src/ray/core_worker/core_worker.cc [hunk 11]
```diff
@@ -980,6 +981,8 @@ void CoreWorker::InternalHeartbeat() {
     direct_actor_submitter_->CheckTimeoutTasks();
   }
 
+  direct_task_submitter_->ReportWorkerBacklog();
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc:984]: Add a comment on why?

File: src/ray/core_worker/test/direct_task_transport_test.cc [hunk 12]
```diff
@@ -2065,7 +2146,8 @@ TEST(DirectTaskTransportTest, TestNoWorkerRequestedIfStealingUnavailable) {
   uint32_t max_tasks_in_flight_per_worker = 10;
   CoreWorkerDirectTaskSubmitter submitter(
       address, raylet_client, client_pool, nullptr, lease_policy, store, task_finisher,
-      NodeID::Nil(), kLongTimeout, actor_creator, max_tasks_in_flight_per_worker);
+      NodeID::Nil(), kLongTimeout, actor_creator, max_tasks_in_flight_per_worker,
+      absl::nullopt, 1);
```
Comment (ericl) [inline src/ray/core_worker/test/direct_task_transport_test.cc:2150]: Is it possible to add a test that heartbeat reports the backlog (not sure if it's covered above).

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 13]
```diff
@@ -423,15 +422,54 @@ CoreWorkerDirectTaskSubmitter::GetOrConnectLeaseClient(
   return lease_client;
 }
 
+void CoreWorkerDirectTaskSubmitter::ReportWorkerBacklog() {
+  absl::MutexLock lock(&mu_);
+  std::unordered_map<SchedulingClass, std::pair<TaskSpecification, int64_t>> backlogs;
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.cc:427]:
```suggestion
  absl::flat_hash_map<SchedulingClass, std::pair<TaskSpecification, int64_t>> backlogs;
```

prefer absl maps when possible for performance

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 14]
```diff
@@ -107,6 +111,9 @@ class CoreWorkerDirectTaskSubmitter {
     return num_leases_requested_;
   }
 
+  /// Report worker backlog information to the local raylet
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.h:114]: Add explanation for why "local" only?

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 15]
```diff
@@ -127,6 +134,9 @@ class CoreWorkerDirectTaskSubmitter {
   std::shared_ptr<WorkerLeaseInterface> GetOrConnectLeaseClient(
       const rpc::Address *raylet_address) EXCLUSIVE_LOCKS_REQUIRED(mu_);
 
+  void ReportWorkerBacklogIfNeeded(const SchedulingKey &scheduling_key)
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.h:137]: Comment

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 16]
```diff
@@ -339,6 +352,18 @@ class CoreWorkerDirectTaskSubmitter {
...
     }
+
+    // Get the current backlog size for this scheduling key
+    inline int64_t BacklogSize() const {
+      if (task_queue.size() < pending_lease_requests.size()) {
+        // During work stealing we may have more pending lease requests than the number of
+        // queued tasks
+        return 0;
+      } else {
+        // Subtract tasks with pending lesae requests so we don't double count them.
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.h:363]:
```suggestion
        // Subtract tasks with pending lease requests so we don't double count them.
```

File: src/ray/core_worker/transport/direct_task_transport.h [hunk 17]
```diff
@@ -339,6 +352,18 @@ class CoreWorkerDirectTaskSubmitter {
       // If any worker has more than one task in flight, then that task can be stolen.
       return total_tasks_in_flight > active_workers.size();
     }
+
+    // Get the current backlog size for this scheduling key
+    inline int64_t BacklogSize() const {
+      if (task_queue.size() < pending_lease_requests.size()) {
+        // During work stealing we may have more pending lease requests than the number of
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.h:359]: @stephanie-wang do we have a timeline to discuss whether to remove work stealing?

File: src/ray/raylet/scheduling/cluster_task_manager.h [hunk 18]
```diff
@@ -360,8 +358,8 @@ class ClusterTaskManager : public ClusterTaskManagerInterface {
 
   void Spillback(const NodeID &spillback_to, const std::shared_ptr<Work> &work);
 
-  void AddToBacklogTracker(const RayTask &task);
-  void RemoveFromBacklogTracker(const RayTask &task);
+  /// Sum up the backlog size across all workers for a given scheduling class.
+  int64_t AggregateWorkerBacklog(SchedulingClass scheduling_class);
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.h:362]:
```suggestion
  int64_t TotalBacklogSIze(SchedulingClass scheduling_class);
```

**Review by ericl — APPROVED** [review]
LGTM. In addition to the inline comments, could you also
- Update the PR description on the high level strategy (e.g., delta update and also periodic global update)?
- Include any performance benchmarks?

**Comment by ericl** [comment]
Btw it seems quite a few tests are failing, likely due to PR changes. Maybe re-merge master and retry?

File: src/ray/core_worker/transport/direct_task_transport.h (hunk 17 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.h:364]: Ah not yet, I'll reach out to Gabriele.

**Comment by ericl** [comment]
@jjyao can merge when you're happy with nightly results!

**Comment by jjyao** [comment]
@ericl The PR passed unit tests, nightly release and core nightly.  The one case that I found where 10 parallelism is slower than 1 is `test_fair_queueing in  python/ray/tests/test_basic_3.py` (you can see the diff for more details). Everything else looks good to me.
