### PR TITLE
[CI] Fix share volume file leak

### LINKED ISSUE #17121: [CI] shared volume between dind and buildkite-job-container may cause file lead
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)

https://buildkite.com/ray-project/ray-builders-pr/builds/9123#7a727ab6-7de0-4b63-bfb4-2fcad57af450

The build error  reason is that contains other git branch file.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by chenk008**
## Why are these changes needed?

In any buildkite CI job, it will start dind on demand and start buildkite-job container. And the dind container's `/ray` is shared with buildkite-job container's `/ray-mount`.

The buildkite-job container will copy its `/ray` to `/ray-mount`, so the dind container's `/ray` will contains all source files, but the buildkite-job does not clean these files after job finished.

When a new buildkite-job container started in the same node, it will try to build Ray by `docker run --rm -w /ray -v /ray:/ray quay.io/pypa/manylinux2014_x86_64 /ray/python/build-wheel-manylinux2014.sh`, but the `/ray` in dind container still contains some files which belong to last buildkite-job.

## Related issue number

Closes https://github.com/ray-project/ray/issues/17121

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jovany-wang** [comment]
@simon-mo

File: ci/travis/ci.sh [hunk 1]
```diff
@@ -338,6 +338,7 @@ build_wheels() {
         docker run --rm -w /ray -v "${PWD}":/ray "${MOUNT_BAZEL_CACHE[@]}" \
         quay.io/pypa/manylinux2014_x86_64 /ray/python/build-wheel-manylinux2014.sh
       else
+        rm -rf /ray-mount/*
```
Comment (jovany-wang) [inline ci/travis/ci.sh:341]: Nice fix!

**Review by jovany-wang — APPROVED** [review]

**Comment by simon-mo** [comment]
@chenk008 good find, thx
