### PR TITLE
[GCS] Improve fallback for getting local valid IP for GCS server

### LINKED ISSUE #8660: [autoscaler] Local Cluster with Docker: Check failed: !local_node_id_.IsNil() This node is disconnected.
<!--Please include [tune], [rllib], [autoscaler] etc. in the issue title if relevant-->

### What is your question?

I've been trying to run a cluster using two hosts with docker. But after running `ray up -y cluster.yml`, I get the following situation after some minutes:

![image](https://user-images.githubusercontent.com/18473249/83157458-feb76280-a0d9-11ea-842b-2d34d1ace91a.png)

Workers keeps incresing by 16 (number of cores) on the worker node, and the same error popping up on the logs.

**View all logs:**
```
F0528 14:53:04.237076   138 service_based_accessor.cc:320]  Check failed: !local_node_id_.IsNil() This node is disconnected.
*** Check failure stack trace: ***
    @     0x55bb8f0f676d  google::LogMessage::Fail()
    @     0x55bb8f0f7bdc  google::LogMessage::SendToLog()
    @     0x55bb8f0f6449  google::LogMessage::Flush()
    @     0x55bb8f0f6661  google::LogMessage::~LogMessage()
    @     0x55bb8edb7029  ray::RayLog::~RayLog()
    @     0x55bb8ec285fc  ray::gcs::ServiceBasedNodeInfoAccessor::UnregisterSelf()
    @     0x55bb8eb37bd4  ray::raylet::Raylet::Stop()
    @     0x55bb8eb1c943  _ZZ4mainENKUlRKN5boost6system10error_codeEiE_clES3_i.isra.2014
    @     0x55bb8eb1cd58  _ZN5boost4asio6detail14signal_handlerIZ4mainEUlRKNS_6system10error_codeEiE_NS1_18io_object_executorINS0_8executorEEEE11do_completeEPvPNS1_19scheduler_operationES6_m
    @     0x55bb8f08841f  boost::asio::detail::scheduler::do_run_one()
    @     0x55bb8f089921  boost::asio::detail::scheduler::run()
    @     0x55bb8f08a7c2  boost::asio::io_context::run()
    @     0x55bb8eb06669  main
    @     0x7fa7e5fd909b  __libc_start_main
    @     0x55bb8eb17331  (unknown)
```
**Relevant messages on logs/monitor.\***
```
2020-05-28 14:52:26,124 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.2060968875885s, restarting Ray to recover...      
2020-05-28 14:53:01,399 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.24538493156433s, restarting Ray to recover...                              
2020-05-28 14:53:36,620 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.10585641860962s, restarting Ray to recover...                              
2020-05-28 14:54:11,807 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.12926173210144s, restarting Ray to recover...                              
2020-05-28 14:54:46,926 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.117576360702515s, restarting Ray to recover...                             
2020-05-28 14:55:22,223 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.251209259033203s, restarting Ray to recover...                             
2020-05-28 14:55:57,461 WARNING autoscaler.py:536 -- StandardAutoscaler: host02: No heartbeat in 30.201629877090454s, restarting Ray to recover...           
```

**cluster.yml:**
```
cluster_name: test                                                                               
                  
min_workers: 2         
initial_workers: 2      
max_workers: 2        
                         
docker:                  
  image: "python:3.8.3"             
  container_name: "ray"             
  run_options: ["--shm-size 25GB"]    
                                    
provider:                     
    type: local               
    head_ip: host01           
    worker_ips: [host02]           
                                   
auth:                              
  ssh_user: root                                                                                                                                              
  ssh_private_key: ~/.ssh/id_rsa                                                                                                                              
                                                                                                                                                              
head_start_ray_commands:                                                                                                                                      
 - ray stop                                                                                                                                                     
 - ulimit -c unlimited && ray start --head --redis-port=6379 --redis-password='' --webui-host=0.0.0.0 --autoscaling-config=~/ray_bootstrap_config.yaml        
                                                                    
worker_start_ray_commands:                                            
 - ray stop                                                         
 - ray start --address=$RAY_HEAD_IP:6379 --redis-password=''
```

I wasn't able to detect any blocked ports by the firewall (using telnet, netstat and nc).

**Ray version:** 0.8.5 and 0.9.0-dev
**OS:** Centos 7, kernel 4.4.96
**Python version:** 3.6

### PR DESCRIPTION
**Pull request by icaropires**
## Why are these changes needed?

Was getting `127.0.0.1` as `GcsServerAddres`  even having valid IP on NIC.

For some unknown reason, this code:
``` cpp
// Run with: g++ -lboost_system -pthread a.cpp -o a && ./a
#include <boost/asio.hpp>    
#include <iostream>    
    
namespace ip = boost::asio::ip;    
    
int main() {    
    boost::asio::io_service io_service;    
    boost::asio::ip::tcp::resolver resolver(io_service);    
    boost::asio::ip::tcp::resolver::query query(boost::asio::ip::host_name(),"");    
    boost::asio::ip::tcp::resolver::iterator it=resolver.resolve(query);    
    
    while(it!=boost::asio::ip::tcp::resolver::iterator()) {    
        boost::asio::ip::address addr=(it++)->endpoint().address();    
        std::cout << addr.to_string() << std::endl;    
    }    
    
    return 0;    
}
```

which is a simplified version of the fallback (for when not connecting) with `8.8.8.8`:
https://github.com/ray-project/ray/blob/646835d292d808dd5e60e86793f3a01e3adb7413/src/ray/common/network_util.cc#L31-L54

prints a list of all IPs in most linux environments I've tested, but not all. There're environments which just print `127.0.0.1` causing the behaviour observed at #8660 (For me it was at Centos 7).

This PR rewrites this fallback, getting a list of IPs addresses candidates (which are going to be tested for connection later) using `getifaddrs()` function for *unix systems. With this, I was a able to fix the undesired behaviour and this solution worked on every system I've tested, old or new distributions.

Additionally, I've included a logic for sorting and filtering out undesired interfaces (like Docker and KVM bridges, bluetooth interfaces, etc). So, interfaces with more priority are tested first for connection and undesired interfaces with valid IPs are not tested at all.

Example: Suppose I've got a system with all these interfaces:
```
br0
wwan1
veth3e80755
virbr1
eth0
br-3681c4c3d645
wlan0
br-123213
eth1
vboxnet0
vmnet1
ppp0
pan1
tap0
ap0
```

After the sorting and filtering out, I'll get this list:
```
eth0
eth1
wwan1
wlan0
br0
ap0
```
Only IPs from these will be tested for connection and in order.

The sorting decision is static and based on interface name prefix. If necessary, later the sorting order can be easily modified by changing the priorities associated with each prefix.

Hope it helps :smiley: 

## Related issue number

Closes #8660

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested (please justify below)

Not tested because would require to mock NICs

### CODE REVIEW

**Comment by icaropires** [comment]
Ready for review! I'm kind of confused about which checks were already broken and those which should pass, tell me if I need to fix anything

File: src/ray/common/network_util.cc [hunk 1]
```diff
@@ -16,49 +16,170 @@
 
 #include "ray/util/logging.h"
 
+typedef std::pair<std::string, std::string> NicAndIp;
+
+bool StartsWith(std::string s, std::string start) {
```
Comment (ffbin) [inline src/ray/common/network_util.cc:21]: const std::string &

File: src/ray/common/network_util.cc [hunk 2]
```diff
@@ -16,49 +16,170 @@
...
+  return s.find(start) == 0;
+}
+
+bool CompNicsAndIps(NicAndIp a, NicAndIp b){
```
Comment (ffbin) [inline src/ray/common/network_util.cc:25]: const NicAndIp &left, const NicAndIp &right?

File: src/ray/common/network_util.cc [hunk 3]
```diff
@@ -16,49 +16,170 @@
...
+}
+
+int GetNicPriority(std::string nic_name){
+  int priority = PRIORITY_TO_DELETE;  // smaller number, more priority
+
+  if(StartsWith(nic_name, "e")){  // eth0, enp7s0f1, ens160, en0, etc
+    priority = 1;
+  }
+  else if (StartsWith(nic_name, "w")) {  // wlp0s20f3, wlp2s0, etc
+    priority = 10;
```
Comment (ffbin) [inline src/ray/common/network_util.cc:36]: How about define a enum for priority?

File: src/ray/common/network_util.cc [hunk 4]
```diff
@@ -16,49 +16,170 @@
...
+  }
+  else if (StartsWith(nic_name, "br")) {
```
Comment (ffbin) [inline src/ray/common/network_util.cc:38]: How about define an array that includes all prefixes and its priority, then we can traverse it to call StartsWith and get priority, this will make the code simpler, thanks.

**Comment by rkooo567** [comment]
Thanks for pushing the PR and extensive test @icaropires! If we can get it merged, it'll be really amazing (also thanks for testing increasing the timeout :)). cc @edoakes and @barakmich who are much familiar with network programming. 

For the CI, can you merge the latest master again? The CI result seems a little weird (it looks like there are travis issues which I don't know if it is relevant to your PR).

Also, cc @mehrdadn to see if the solution is compatible to Windows.

**Comment by icaropires** [comment]
@ffbin Thank you for the considerations! I've already applied them to the code and it's ready for review again. For using the enum, I've reduced the priority options to just `very high`, `high`, `normal` and `exclude` but I guess it's enough:

image

@rkooo567 and @mehrdadn the new approach will be applied only for *unix, for Windows I've kept using the old approach as would require to use windows specific libraries and a different implementation to get the same effect

File: src/ray/common/network_util.h [hunk 5]
```diff
@@ -124,3 +134,51 @@ std::string GetValidLocalIp(int port, int64_t timeout_ms);
...
+  /// Lowest priority comes first
+  bool CompNamesAndIps(const NameAndIp &left, const NameAndIp &right);
+
+  /// Helper function to be used on std::sort.
+  /// Biggest prefix comes first
+  bool CompPrefixLen(const PrefixAndPriority &left, const PrefixAndPriority &right);
+
+  /// A helper tiny function to check if the interface name has a given prefix.
+  ///
+  /// \param s the string to be checked.
```
Comment (ffbin) [inline src/ray/common/network_util.h:180]: /// \param str the string to be checked.

File: src/ray/common/network_util.h [hunk 6]
```diff
@@ -124,3 +134,51 @@ std::string GetValidLocalIp(int port, int64_t timeout_ms);
...
+  /// \param start the prefix will compared with 's'.
```
Comment (ffbin) [inline src/ray/common/network_util.h:181]: /// \param prefix the prefix will compared with 'str'.

**Review by ffbin — APPROVED** [review]
LGTM

**Comment by icaropires** [comment]
@barakmich @edoakes @rkooo567 @mehrdadn Do I need to fix something else?

**Review by edoakes — APPROVED** [review]
LGTM, nice improvement. Seems like this isn't a complete fix though - users may in some cases still need to manually specify which interface to listen on.

**Comment by edoakes** [comment]
@icaropires I think there were some issues with CI, could you merge in the latest master and push to trigger it to run again?

**Comment by icaropires** [comment]
> LGTM, nice improvement. Seems like this isn't a complete fix though - users may in some cases still need to manually specify which interface to listen on.

@edoakes I fully agree with you and I've also said that in #8660 . If desired, I can open another PR adding this option to `ray.init` and CLI, something like `gcs_address`.



> @icaropires I think there were some issues with CI, could you merge in the latest master and push to trigger it to run again?

Done! I'm not very sure about what must be passing on CI. If any fix is needed, I'd appreciate any advice

**Comment by icaropires** [comment]
> @icaropires I think there were some issues with CI, could you merge in the latest master and push to trigger it to run again?

@edoakes Is the CI ok now? There was a problem with my clang-format version, but now it appears to be working

**Comment by edoakes** [comment]
@icaropires looks good!

**Comment by edoakes** [comment]
@icaropires would be awesome if you could also contribute a PR to add the GCS address option! Could you maybe first file an issue with the proposed interface so we can get buy-in from other maintainers before spending time coding?

**Comment by icaropires** [comment]
> @icaropires would be awesome if you could also contribute a PR to add the GCS address option! Could you maybe first file an issue with the proposed interface so we can get buy-in from other maintainers before spending time coding?

@edoakes Sure! I will

**Comment by rkooo567** [comment]
@icaropires Thanks again for digging into the issue and push the fix!! It will be really helpful for many users :) Excited to review your next PR!

**Comment by icaropires** [comment]
> @icaropires Thanks again for digging into the issue and push the fix!! It will be really helpful for many users :) Excited to review your next PR!

Thank you all for your attention! I'm happy to contribute to such a large and skilled community like ray!
