### PR TITLE
[Dashboard] Fix the wrong task timeline url for download

### LINKED ISSUE #41292: [Dashboard] Can't download the task timeline when use url path as the dashboard entry point
### What happened + What you expected to happen

Can't download the task timeline when use url path as the dashboard entry point. 

Example:
- Dashboard URL: http://example.com/ray/dashboard/
- Task Timeline Download URL:
    - Expected: http://example.com/ray/dashboard/api/v0/tasks/timeline?download=1&job_id=${jobId}
    - Actual: http://example.com/api/v0/tasks/timeline?download=1&job_id=${jobId}

### Versions / Dependencies

Ray versions: 2.8.0, 2.7.1 and so on. Not related to Python, OS and other libraries.

### Reproduction script

Should config the url path request rules in your web server or load balancer. 

NGINX Example:
```
Server {
    listen: 8090
    server_name: example.com
    
    location /ray/dashboard/ {
        proxy_pass  http://x.x.x.x:8265
    }
}
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by jiwq**
## Why are these changes needed?

Can't download the task timeline when use url path as the dashboard entry point

## Related issue number

Closes #41292 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: dashboard/client/src/service/task.ts [hunk 1]
```diff
@@ -18,7 +18,7 @@ export const getTask = (taskId: string) => {
 };
 
 export const downloadTaskTimelineHref = (jobId: string | undefined) => {
-  let url = "/api/v0/tasks/timeline?download=1";
+  let url = "api/v0/tasks/timeline?download=1";
```
Comment (alanwguo) [inline dashboard/client/src/service/task.ts:21]: This fix is fragile and will not work if we move away from "hash-based" routing to location based routing for the dashboard UI.

If we move to location based routing (standard for most single page apps), the path for the the job detail page will be `dashboard.com/jobs/{job_id}`, and thus, this link will go to `dashboard.com/jobs/{job_id}/api/v0/tasks/timeline?download=1` instead of `dashboard.com/api/v0/tasks/timeline?download=1`

I think the proper fix is to add an environment variable to dashboard_head.py called `RAY_DASHBOARD_PATH_PREFIX`. 
The path_prefix must then be injected into the web app and used throughout the code base.

Then user can launch ray like `RAY_DASHBOARD_PATH_PREFIX=ray/dashboard ray start --head`

Comment (alanwguo) [reply dashboard/client/src/service/task.ts:21]: Looking at our other apis, we follow this same pattern... Seems like we'd have to do a major migration if we moved from hash-based routing to location-based routing. I'll approve this then since this is the existing pattern.

**Review by alanwguo — APPROVED** [review]

**Comment by alanwguo** [comment]
Thanks for fixing!

File: dashboard/client/src/service/task.ts (hunk 1 above)
Comment (jiwq) [reply dashboard/client/src/service/task.ts:21]: Yeah, the hash-based routing is a major new feature and need more works to do. Maybe we should submit a REP first, and any suggestions? @alanwguo

**Comment by kevin85421** [comment]
cc @alanwguo @rkooo567 is this PR ready to merge? Thanks!

**Comment by alanwguo** [comment]
Yup, I don't have merging powers. @rkooo567, can you merge?

**Review by rkooo567 — APPROVED** [review]

**Comment by jiwq** [comment]
Thanks @alanwguo @kevin85421 @rkooo567 helps for this PR.
