### PR TITLE
[Core] Cancel lease requests before returning a PG bundle

### LINKED ISSUE #45642: [Core] Raylet check failed: placement_group_resource_manager.cc:29: Check failed: ReturnBundle(*iter->second).ok()
### What happened + What you expected to happen

```
2024-05-29 22:54:10	(/tmp/ray/session_2024-05-24_19-21-02_933825_4791/logs/raylet.out) [2024-05-29 22:54:10,723 C 359273 359273] (raylet) placement_group_resource_manager.cc:29: Check failed: ReturnBundle(*iter->second).ok()
```

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

None

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
To successfully return a PG bundle (`CancelResourceReserve` and `ReleaseUnusedBundles`), the bundle resource needs to be completely free (i.e. total == available). To make sure that, raylet will first destroy leased workers that are currently using the PG bundle resources so that these bundle resources can be freed. However this alone cannot guarantee that all bundle resources will be freed since a lease request that's popping worker also already acquires the bundle resources so we need to cancel these lease requests as well to free the bundle resources.

After this PR, we don't need the retry in #42942.

## Related issue number
Closes #45642

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/node_manager.cc [hunk 1]
```diff
@@ -683,6 +683,16 @@ void NodeManager::HandleReleaseUnusedBundles(rpc::ReleaseUnusedBundlesRequest re
...
+  // Cancel lease requests related to unused bundles
+  cluster_task_manager_->CancelTasks(
+      [&](const RayTask &task) {
+        const auto bundle_id = task.GetTaskSpecification().PlacementGroupBundleId();
+        return !bundle_id.first.IsNil() && 0 == in_use_bundles.count(bundle_id);
+      },
+      rpc::RequestWorkerLeaseReply::SCHEDULING_CANCELLED_INTENDED,
+      "The task is cancelled because it uses placement group bundles that are not "
+      "registered to GCS. It can happen upon GCS restart.");
+
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:695]: Actual fix.

File: src/ray/raylet/node_manager.cc [hunk 2]
```diff
@@ -1889,6 +1899,15 @@ void NodeManager::HandleCancelResourceReserve(
...
 
+  // Cancel lease requests related to the placement group to be removed.
+  cluster_task_manager_->CancelTasks(
+      [&](const RayTask &task) {
+        const auto bundle_id = task.GetTaskSpecification().PlacementGroupBundleId();
+        return bundle_id.first == bundle_spec.PlacementGroupId();
+      },
+      rpc::RequestWorkerLeaseReply::SCHEDULING_CANCELLED_PLACEMENT_GROUP_REMOVED,
+      "");
+
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1910]: Actual fix.

**Comment by rynewang** [comment]
Side comment: we found multiple similar cases, in that when we want to kill *all* workers under a predicate (e.g. job died, root detached actor died, pg died, ...), we have to do it multiple places:

- NodeManager::leased_workers_
- WorkerPool::PopWorkerCallbackInternal
- WorkerPool::InvokePopWorkerCallbackForProcess
- WorkerPool::KillIdleWorker

I wonder if we can have a unified mechanism to do the killing for all...

File: src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc [hunk 3]
```diff
@@ -261,11 +261,10 @@ void GcsPlacementGroupScheduler::CancelResourceReserve(
           RAY_LOG(INFO) << "Finished cancelling the resource reserved for bundle: "
                         << bundle_spec->DebugString() << " at node " << node_id;
         } else {
-          // We couldn't delete the pg resources either becuase it is in use
-          // or network issue. Retry.
-          RAY_LOG(INFO) << "Failed to cancel the resource reserved for bundle: "
-                        << bundle_spec->DebugString() << " at node " << node_id
-                        << ". Status: " << status;
+          // We couldn't delete the pg resources because network issue. Retry.
```
Comment (rynewang) [inline src/ray/gcs/gcs_server/gcs_placement_group_scheduler.cc:264]:
```suggestion
          // We couldn't delete the pg resources because of network issue. Retry.
```

File: src/ray/raylet/local_task_manager.cc [hunk 4]
```diff
@@ -765,16 +747,18 @@ void ReplyCancelled(std::shared_ptr<internal::Work> &work,
 }
 }  // namespace
 
-bool LocalTaskManager::CancelTask(
-    const TaskID &task_id,
+bool LocalTaskManager::CancelTasks(
```
Comment (rynewang) [inline src/ray/raylet/local_task_manager.cc:750]: I have seen this idiom of removing a task in a complex data structure, by playing with iterators and `erase` in Ray in many places. I feel we can try to split "cancel the task" and "remove it from data structure" by using `std::erase_if`. However it's in C++20 so we can make a poly fill. Here is what I get:

In container_util.h:
```cc

/// Polyfill for C++20 std::erase_if.
/// It's regrettable it's not landed in C++17 or earlier.
template <typename C, typename Pred>
size_t erase_if_polyfill(C &c, Pred pred) {
  auto it = std::remove_if(c.begin(), c.end(), pred);
  size_t count = std::distance(it, c.end());
  c.erase(it, c.end());
  return count;
}

```

Here:
```cc
#include "ray/util/container_util.h"

bool LocalTaskManager::CancelTasks(
    std::function<bool(const RayTask &)> predicate,
    rpc::RequestWorkerLeaseReply::SchedulingFailureType failure_type,
    const std::string &scheduling_failure_message) {
  size_t cancelled_from_to_dispatch = 0;
  size_t sched_cls_removed = erase_if_polyfill(
      tasks_to_dispatch_,
      [&predicate,
       &cancelled_from_to_dispatch,
       failure_type,
       scheduling_failure_message,
       this](auto &shape) -> bool {
        auto &[sched_cls, work_queue] = shape;
        size_t work_removed = erase_if_polyfill(
            work_queue,
            [&predicate, failure_type, scheduling_failure_message, this](
                std::shared_ptr<internal::Work> &work) -> bool {
              const auto &task = work->task;
              const bool should_cancel = predicate(task);
              if (should_cancel) {
                const TaskID task_id = task.GetTaskSpecification().TaskId();
                RAY_LOG(DEBUG) << "Canceling task " << task_id << " from dispatch queue.";
                ReplyCancelled(work, failure_type, scheduling_failure_message);
                if (work->GetState() == internal::WorkStatus::WAITING_FOR_WORKER) {
                  // We've already acquired resources so we need to release them.
                  cluster_resource_scheduler_->GetLocalResourceManager()
                      .ReleaseWorkerResources(work->allocated_instances);
                  // Release pinned task args.
                  ReleaseTaskArgs(task_id);
                }
                if (!task.GetTaskSpecification().GetDependencies().empty()) {
                  task_dependency_manager_.RemoveTaskDependencies(
                      task.GetTaskSpecification().TaskId());
                }
                RemoveFromRunningTasksIfExists(task);
                work->SetStateCancelled();
              }
              // Erase from work_queue if the work is cancelled.
              return should_cancel;
            });
        cancelled_from_to_dispatch += work_removed;
        // Erase from tasks_to_dispatch_ if the work_queue is empty.
        return work_queue.empty();
      });

  size_t cancelled_from_waiting_task_queue = erase_if_polyfill(
      waiting_task_queue_,
      [&predicate, failure_type, scheduling_failure_message, this](
          std::shared_ptr<internal::Work> &work) -> bool {
        const auto &task = work->task;
        const bool should_cancel = predicate(task);
        if (should_cancel) {
          ReplyCancelled(work, failure_type, scheduling_failure_message);
          if (!task.GetTaskSpecification().GetDependencies().empty()) {
            task_dependency_manager_.RemoveTaskDependencies(
                task.GetTaskSpecification().TaskId());
          }
          waiting_tasks_index_.erase(task.GetTaskSpecification().TaskId());
        }
        return should_cancel;
      });
  // Maybe we can return a size_t of num of work cancelled in CancelTasks.
  return (cancelled_from_to_dispatch + cancelled_from_waiting_task_queue > 0);
}

```

Comment (jjyao) [reply src/ray/raylet/local_task_manager.cc:750]: I don't think std::remove_if works with hash_map: https://stackoverflow.com/questions/9210014/remove-elements-from-an-unordered-map-fulfilling-a-predicate

File: src/ray/util/container_util.h [hunk 5]
```diff
@@ -97,19 +97,33 @@ typename C::mapped_type &map_find_or_die(C &c, const typename C::key_type &k) {
...
-/// @param matcher the matcher function to be applied to each elements
-/// @param container the container of the elements
-template <typename T>
-void remove_elements(std::function<bool(T)> matcher, std::deque<T> &container) {
-  auto itr = container.begin();
-  while (itr != container.end()) {
-    if (matcher(*itr)) {
-      itr = container.erase(itr);
+template <typename K, typename V>
+void erase_if(absl::flat_hash_map<K, std::deque<V>> &map,
```
Comment (rynewang) [inline src/ray/util/container_util.h:101]: [nit] do we want to return a size_t of removed elements?
[nit] Add comment on guarantees: each element is applied exactly once, in order

**Review by rynewang — APPROVED** [review]

**Comment by can-anyscale** [comment]
might be breaking https://github.com/orgs/anyscale/projects/76/views/1?pane=issue&itemId=67654997
