### PR TITLE
[Pubsub] Generalize the pubsub interface and adapt it for ref counting protocol

### LINKED ISSUE #14322: Excessive heap memory usage in raylet / owner process when shuffling many objects
To reproduce, run: python -m ray.experimental.shuffle --num-partitions=1000 --partition-size=1e6

You'll see that in `top` the raylet and owner process will end up using >10GB of heap memory. This is very unexpected, since theses processes should (1) only be storing metadata, and (2) the amount of "real data" is only 1GB in the benchmark above.

There might be some memory leak or other unexpected issue here.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

**This is fully review-able**

Recommended review workflow.
- First, look at core_worker.cc and reference_count.cc to see how the new interface looks like.
- Check subscriber.h and publisher.h.
- And then review other parts. 

The current interface is not ideal, but it is working pretty well with the current status. Let's **iterate** on the interface! 

I verified this reduced the number of WaitForRefRemoved requests. 

## Related issue number

Close https://github.com/ray-project/ray/issues/14322
#14762

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Current test failure should be temporary,.

**Review by clarkzinzow — COMMENTED** [review]
Did a usage first pass, I have a few high-level pubsub design questions before I dig deeper.

It looks like we're using a channel abstraction in order to be able to piggyback off of shared publisher <--> subscriber long-polling connections, where the publisher and subscriber interfaces expose the channel concept to the application code via the channel type and deal only with a generic `PubMessage` message type that oneofs across the messages for the different channels. This then entails pass-through methods to the subinterfaces for each channel, maintaining channel --> data structure maps internally, and leaking what is essentially a transport detail (the long-polling connection) to the application level by requiring publishers/subscribers to specify the channel type. I'm wondering if there's a better way to structure this such that the application code doesn't have to worry about channels and more of this logic is encoded in the type system so we have compile-time guarantees that things are 👌 .

What if we adopted a pattern similar to gRPC's shared transport channel, generalized from managing a 1-to-1 connection to managing 1-to-n connections, where we have a transport broker concept that encapsulates the publisher <--> subscriber long-polling connections. The subscriber interface for each pubsub instance takes a shared pointer to the broker on construction, and can therefore share the broker across different pubsub instances (e.g. separate subscriber objects for `WAIT_FOR_OBJECT_EVICTION` and `WAIT_FOR_REF_REMOVED`), where new publisher <--> subscriber connections can be registered by any of the pubsub instances at subscription time.

```
subscribers <--> broker <--transport--> broker <--> publishers
```

I think there could be a few advantages here:

1. We could then expose a subscriber interface per pubsub instance, templated on the concrete message type (no need for a proto oneof message to be exposed to the application code, that could be isolated to the broker), which will give better compile-time checking of the application-level pubsub messages and will obviate the need for those passthrough methods in a top-level subscriber interface that requires a channel type to be specified.
2. I think that you'd still need a proto-level channel type enum, but I think that you could get away with specializing the subscriber with _the enum value itself_. E.g. `Subscriber<typename MessageID, typename Message, rpc::ChannelType channel_type>` could be specialized as `Subscriber<ObjectID, rpc::WaitForObjectEvictionMessage, rpc::WAIT_FOR_OBJECT_EVICTION>`, where the `channel_type` is included when interacting with the broker (e.g. subscribe, unsubscribe). Dispatch of messages received in the long-poll response by the broker will still have to use a channel --> subscriber table, but that can be populated dynamically when the subscriber is constructed: `broker_.RegisterSubscriber(channel_type, this)`.
3. The transport-level optimization of sharing long-polling connections is pushed down as an implementation detail of the transport broker concept, and is a natural place to evolve other transport-level details, like switching to a bidi streaming connection or switching to a centralized message broker.
4. Other transport-level things, like the core worker client pool and the subscriber address/port, can be moved to the broker. Publisher addresses will probably continue to be required by subscriber methods, unless we want the broker to always map worker or node IDs to concrete addresses (probably less efficient in some cases?).
5. The current process of registering a new channel will be replaced by adding a new channel type to the proto enum, adding the channel's proto to the broker's pubsub message oneof, templating a subscriber with a new message type and the channel type, and reusing the existing broker. I don't think there should be much more required than that.

I think that you would have an analogous broker abstraction on the publisher side as well (encapsulating the cached long-polling connection, controlling the message batching), although I haven't thought it through as much since I think it should be simpler than the subscriber-side. My guess is that the publisher would be similarly templated, would similarly register itself with the publish-side broker on construction, and each publisher instance (one per channel type) would have its own subscription index. I think that the publisher's `Subscriber` would be internal to the publish-side broker.

The cons with this broker approach, as I see them:

1. Broker concept is exposed to the application level, although what's needed to configure that concept (worker client pool, subscriber address/port, etc.) is already exposed to the application level, so I'm not sure if this is any worse?
2. A shared transport-level broker will obviously have to be thread-safe, although that shouldn't be very difficult.
3. Hidden dragons that I haven't thought of.

Lmk what you think about this approach and whether I'm missing anything! This is also something that could wait until a future PR, e.g. when I port the OBOD object location subscriptions or the GCS node/actor tables to this pubsub I'm sure that I'll have to refactor some stuff anyway.

**Comment by rkooo567** [comment]
Thanks for the suggestion! Did I understand correctly the below API examples are what you are describing? 

```cpp
# either this
# manages the connection
broker_ 
# manages the tracking
wait_for_object_channel = Channel<ObjectID, MessageType>(broker)
wait_for_object_channel->interface();

# or this

subscriber_broker->Channel(WaitForObjectEviction)->interface()
```

File: src/ray/core_worker/reference_count.h [hunk 1]
```diff
@@ -66,13 +68,17 @@ class ReferenceCounter : public ReferenceCounterInterface,
...
                    bool distributed_ref_counting_enabled = true,
                    bool lineage_pinning_enabled = false,
                    rpc::ClientFactoryFn client_factory = nullptr)
       : rpc_address_(rpc_address),
         distributed_ref_counting_enabled_(distributed_ref_counting_enabled),
         lineage_pinning_enabled_(lineage_pinning_enabled),
-        borrower_pool_(client_factory) {}
+        borrower_pool_(client_factory),
+        object_status_publisher_(object_status_publisher),
+        object_status_subscriber_(object_status_subscriber) {}
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/reference_count.h:81]: publisher is shared by core worker.cc, so I don't think we need to move. I can consider it for subscriber, but I don't think it is a big deal here.

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -2384,7 +2403,9 @@ void CoreWorker::HandleSubscribeForObjectEviction(
     RAY_LOG(DEBUG) << stream.str();
     send_reply_callback(Status::NotFound(stream.str()), nullptr, nullptr);
   } else {
-    object_status_publisher_->RegisterSubscription(subscriber_node_id, object_id);
+    object_status_publisher_->RegisterSubscription(
+        rpc::ChannelType::WAIT_FOR_OBJECT_EVICTION, subscriber_node_id,
+        object_id.Binary());
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:2408]: Hmm I don't know which refactoring you are talking about, but I don't think this scenario is possible (unless you have 1~2 cpus in your machine. And although there are 1\~2 cpus, it is really unlikely because the class is thread-safe). If you are really concerned, I can just modify it because it is not a big change.

File: release/data_processing_tests/multi_node.yaml [hunk 3]
```diff
@@ -1,12 +1,12 @@
-cluster_name: Multi-node-cluster
+cluster_name: Multi-node-cluster-2
```
Comment (rkooo567) [inline release/data_processing_tests/multi_node.yaml:1]: This file will be reverted.

File: src/ray/core_worker/reference_count.h (hunk 1 above)
[the remark this answers is not in the document]
Comment (jovany-wang) [reply src/ray/core_worker/reference_count.h:81]: +1 for std::move() on copied arguments.

**Comment by jovany-wang** [comment]
BTW, I prefer name the channels to `OBJECT_EVICTION` and `REF_REMOVED`(Remove the `WAIT_FOR_` prefix.)?

File: src/ray/pubsub/publisher.h [hunk 4]
```diff
@@ -89,16 +105,19 @@ class Subscriber {
...
   ///
-  /// \param long_polling_reply_callback reply callback to the long polling request.
+  /// \param reply pubsub long polling reply.
+  /// \param send_reply_callback A callback to reply to the long polling subscriber.
   /// \return True if connection is new. False if there were already connections cached.
-  bool ConnectToSubscriber(LongPollConnectCallback long_polling_reply_callback);
+  bool ConnectToSubscriber(rpc::PubsubLongPollingReply *reply,
+                           rpc::SendReplyCallback send_reply_callback);
 
   /// Queue the object id to publish to the subscriber.
```
Comment (jovany-wang) [inline src/ray/pubsub/publisher.h:114]: Update this comment.

File: src/ray/pubsub/publisher.cc [hunk 5]
```diff
@@ -207,24 +249,31 @@ void Publisher::Publish(const ObjectID &object_id) {
     auto it = subscribers_.find(subscriber_id);
     RAY_CHECK(it != subscribers_.end());
     auto &subscriber = it->second;
-    subscriber->QueueMessage(object_id);
+    subscriber->QueueMessage(std::move(pub_message));
```
Comment (jovany-wang) [inline src/ray/pubsub/publisher.cc:252]: If the size of `maybe_subscribers` is 2, `pub_message` will be moved twice, which may lead segement fault.

**Review by jovany-wang — CHANGES_REQUESTED** [review]

**Comment by clarkzinzow** [comment]
> Thanks for the suggestion! Did I understand correctly the below API examples are what you are describing?
```
# either this
# manages the connection
broker_ 
# manages the tracking
wait_for_object_channel = Channel<ObjectID, MessageType>(broker)
wait_for_object_channel->interface();

# or this

subscriber_broker->Channel(WaitForObjectEviction)->interface()
```

@rkooo567 Closer to the first one! The idea was having the broker manage the connections and having one or more subscriber interfaces (not quite "channels") that the application-level interacts with:
```c++
broker_ = SubscriberBroker(subscriber_address, subscriber_port, worker_client_pool);
wait_for_object_eviction_subscriber_ = Subscriber<ObjectID, rpc::WaitForObjectEvictionMessage, rpc::WAIT_FOR_OBJECT_EVICTION>(broker_);
wait_for_ref_removed_subscriber_ = Subscriber<ObjectID, rpc::WaitForRefRemovedMessage, rpc::WAIT_FOR_REF_REMOVED>(broker_);
// ...
wait_for_object_eviction_subscriber_.Subscribe(publisher_address, object_id, message_published_callback, publisher_failed_callback);
```

**Comment by rkooo567** [comment]
> the connections and having one or more subscriber interfaces (not quite "channels") 

But one subscriber can still subscribe one channel right? Are you saying not quite channel because subscriber "subscribes" channels (that says, due to semantics) or is there other reasons?

Also, I originally tried with the second approach `subscriber_broker->Channel(WaitForObjectEviction)->interface()`, but I decided to go with the current approach cuz of some ugliness in implementation (for example, components need to share a lock and broker and subscriber or publisher needs to call each other. It wasn't possible to have a data structure that holds different subscribers created with template). Some of problems could be avoided if we go with the first approach, but I am not sure until we try that out. 

While I don't disagree with the new interface, I don't want to include that change into this PR for several reasons.

- Firstly, the interface is not user-facing. I think the current interface is not ideal as I mentioned, but since it is only for dev facing, and there will be probably less than 10 people who will use this interface for pretty long time, so I think this is fine. (But feel free to perform refactoring if you think that's ideal).
- For real general pubsub (GCS pubsub), this class will be hidden behind GCS pubsub interface, so we can ensure type checking and stuff there.
- The current implementation already worked pretty well (as you noticed 100TB shuffle succeed with the current change).
- This is something we need design discussion (the current impl is more like a "prototype"). So, I prefer to have design doc for general interfaces and things like that (instead of having discussion through comment here).

So, I suggest to move forward with the current impl as you mentioned here (`This is also something that could wait until a future PR`), and we compile a design doc that includes general interface of this and perform refactor in a separate PR. What do you think?

File: src/ray/pubsub/publisher.cc (hunk 5 above)
Comment (rkooo567) [reply src/ray/pubsub/publisher.cc:252]: Good catch. Will fix it and add tests

File: src/ray/core_worker/reference_count.cc [hunk 6]
```diff
@@ -778,18 +792,39 @@ void ReferenceCounter::WaitForRefRemoved(const ReferenceTable::iterator &ref_it,
...
+          return;
+        }
 
-        // Erase the previous borrower.
-        auto it = object_id_refs_.find(object_id);
-        RAY_CHECK(it != object_id_refs_.end());
-        RAY_CHECK(it->second.borrowers.erase(addr));
-        DeleteReferenceInternal(it, nullptr);
+        absl::MutexLock lock(&mutex_);
+        object_status_subscriber_->Subscribe(
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/reference_count.cc:825]: For the star model, it is hard to have the same unified interface for subscribe request (unlike things like GCS which will have the same type request for all pubsub).

File: src/ray/pubsub/publisher.h [hunk 7]
```diff
@@ -21,31 +21,33 @@
...
 
 namespace pubsub {
 
 using SubscriberID = UniqueID;
-using LongPollConnectCallback = std::function<void(const std::vector<ObjectID> &)>;
 
 namespace pub_internal {
 
 /// Index for object ids and node ids of subscribers.
+template <typename MessageID>
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/pubsub/publisher.h:38]: Let's think about the general purpose a bit later. This PR is not for using the module to be used for GCS pubsub (but to solve problems happening from distributed shuffle). We can have further discussion of the interface in the design doc and perform refactoring (which is better than discussing through a chat here).

**Comment by rkooo567** [comment]
@jovany-wang 

> BTW, I prefer name the channels to OBJECT_EVICTION and REF_REMOVED(Remove the WAIT_FOR_ prefix.).

Yeah it makes sense. But we probably want to have a prefix to distinguish worker-based channel and gcs-based channels? What about WORKER_OBJECT_EVICTION?

**Comment by clarkzinzow** [comment]
>But one subscriber can still subscribe one channel right? Are you saying not quite channel because subscriber "subscribes" channels (that says, due to semantics) or is there other reasons?

I'm saying that the different pubsub "channels" are presented to the application-level code as independent subscriber objects, with APIs that are channel-agnostic. The broker should hide all of the details around managing subscriber <--> publisher connections, and the multiplexing of multiple different pubsub channels over a single subscriber <--> publisher connection should be hidden from the application code.

>So, I suggest to move forward with the current impl as you mentioned here (This is also something that could wait until a future PR), and we compile a design doc that includes general interface of this and perform refactor in a separate PR if necessary. What do you think?

Definitely, that sounds like the best route to me! I should be able to get to another review pass of this PR today.

File: src/ray/pubsub/publisher.h (hunk 7 above)
[the remark this answers is not in the document]
Comment (jovany-wang) [reply src/ray/pubsub/publisher.h:38]: Sounds good.

**Comment by jovany-wang** [comment]
> @jovany-wang
> 
> > BTW, I prefer name the channels to OBJECT_EVICTION and REF_REMOVED(Remove the WAIT_FOR_ prefix.).
> 
> Yeah it makes sense. But we probably want to have a prefix to distinguish worker-based channel and gcs-based channels? What about WORKER_OBJECT_EVICTION?

I totally agree that adding a prefix to distinguish worker-based channels and gcs-based channels. But I don't have an idea on what the best prefix format is~

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
[the remark this answers is not in the document]
Comment (clarkzinzow) [reply src/ray/core_worker/core_worker.cc:2416]: The task execution thread runs concurrently with the asio IO context thread that this gRPC handler will be run on, so couldn't the task execution thread invoke the delete callback before the subscription is registered, therefore leaking the subscription since it will never get unregistered? I don't see any synchronization that would prevent the delete callback that's added in line 2408 being run before the subscription registration is added in line 2414.

Implicitly assuming that the delete callback (which unregisters the subscription) won't be invoked until after a later subscription registration, in the face of unsynchronized concurrent calling of the delete callback and registering of the subscription, is a fragile assumption that could be easy to miss on a refactor. Even if this is very unlikely or even impossible with the current higher-level design of the core worker, for the sake of being defensive towards future refactors, it makes a lot more sense to me to register the subscription before the delete callback is registered.

File: src/ray/pubsub/publisher.cc [hunk 8]
```diff
@@ -20,149 +20,188 @@ namespace pubsub {
...
     return false;
   }
 
   if (force || mailbox_.size() > 0) {
-    std::vector<ObjectID> mails_to_post;
-    while (mailbox_.size() > 0 && mails_to_post.size() < publish_batch_size_) {
-      // It ensures that mails are posted in the FIFO order.
-      mails_to_post.push_back(mailbox_.front());
-      mailbox_.pop_front();
+    // If force pubilsh is invoked, mailbox could be empty. Fill this up in that case.
```
Comment (clarkzinzow) [inline src/ray/pubsub/publisher.cc:163]: Nit:

```suggestion
    // If force publish is invoked, mailbox could be empty. Fill this up in that case.
```

File: src/ray/pubsub/publisher.cc (hunk 5 above)
Comment (clarkzinzow) [reply src/ray/pubsub/publisher.cc:252]: @rkooo567 This still needs to be fixed, right?

File: src/ray/pubsub/publisher.h (hunk 4 above)
Comment (clarkzinzow) [reply src/ray/pubsub/publisher.h:114]: Still needs to be updated.

```suggestion
  /// Queue the pubsub message to publish to the subscriber.
```

File: src/ray/pubsub/subscriber.cc [hunk 9]
```diff
@@ -18,174 +18,272 @@ namespace ray {
...
 }
 
-bool Subscriber::UnsubscribeObject(const rpc::Address &publisher_address,
-                                   const ObjectID &object_id) {
+template <typename MessageID>
+bool SubscriberChannel<MessageID>::Unsubscribe(const rpc::Address &publisher_address,
+                                               const std::string &message_id) {
   const auto publisher_id = PublisherID::FromBinary(publisher_address.worker_id());
-  RAY_LOG(DEBUG) << "Unsubscribing an object " << object_id << " from " << publisher_id;
+  const auto mid = MessageID::FromBinary(message_id);
```
Comment (clarkzinzow) [inline src/ray/pubsub/subscriber.cc:49]: Supernit: Not the _best_ variable name. 😉

File: src/ray/pubsub/subscriber.cc [hunk 10]
```diff
@@ -18,174 +18,272 @@ namespace ray {
...
+  RAY_LOG(DEBUG) << "Make a long polling request to " << publisher_id;
+  auto publisher_client = publisher_client_pool_.GetOrConnect(publisher_address);
+  rpc::PubsubLongPollingRequest long_polling_request;
+  long_polling_request.mutable_subscriber_address()->CopyFrom(subscriber_address);
+
+  publisher_client->PubsubLongPolling(
+      long_polling_request, [this, publisher_address, subscriber_address](
+                                Status status, const rpc::PubsubLongPollingReply &reply) {
+        HandleLongPollingResponse(publisher_address, subscriber_address, status, reply);
+      });
```
Comment (clarkzinzow) [inline src/ray/pubsub/subscriber.cc:229]: Nit: Could `std::bind` this to reduce pass-through boilerplate:
```suggestion
      long_polling_request, std::bind(&HandleLongPollingResponse, this, publisher_address, subscriber_address, std::placeholders::_1, std::placeholders::_2));
```

File: src/ray/pubsub/subscriber.cc [hunk 11]
```diff
@@ -18,174 +18,272 @@ namespace ray {
...
+                                           const Status &status,
+                                           const rpc::PubsubLongPollingReply &reply) {
+  const auto publisher_id = PublisherID::FromBinary(publisher_address.worker_id());
+  RAY_LOG(DEBUG) << "Long polling request has replied from " << publisher_id;
+  auto publishers_connected_it = publishers_connected_.find(publisher_id);
+  RAY_CHECK(publishers_connected_it != publishers_connected_.end());
+  if (!status.ok()) {
+    // If status is not okay, we treat that the publisher is dead.
+    RAY_LOG(DEBUG) << "A worker is dead. subscription_failure_callback will be invoked. "
+                      "Publisher id:"
```
Comment (clarkzinzow) [inline src/ray/pubsub/subscriber.cc:243]: Nit:
```suggestion
                      "Publisher id: "
```

File: src/ray/pubsub/subscriber.cc [hunk 12]
```diff
@@ -18,174 +18,272 @@ namespace ray {
...
+  }
+}
+
+inline bool Subscriber::SubscriptionExists(const PublisherID &publisher_id) {
+  for (const auto &channel_it : channels_) {
+    if (channel_it.second->SubscriptionExists(publisher_id)) {
+      return true;
+    }
+  }
+  return false;
```
Comment (clarkzinzow) [inline src/ray/pubsub/subscriber.cc:270]: Nit: Some of these helpers could be expressed pretty easily with `std::any_of`:
```suggestion
  return std::any_of(channels_.begin(), channels_.end(), [](const auto &p) { return p.second->SubscriptionExists(publisher_id); });
```
I like to use the std algorithms helpers when I think it will make the check clearer, lessen the chance of bugs, or reduce boilerplate, but it often comes to dev personal preference. So if you prefer to keep these as explicit checks like you have above, feel free! 😁

**Review by clarkzinzow — APPROVED** [review]
LGTM! I mostly have nits, although we should definitely fix the more-than-one-move when queueing messages before merging, but I trust that you'll fix that. I'm also still of the opinion that we should try to register subscriptions before adding ref deletion callbacks (which include unregistering subscriptions) to prevent surprise leaks of subscriptions in the future (thread [here](https://github.com/ray-project/ray/pull/15446#discussion_r619421883)), lmk what you think about that.

I also didn't get a chance to say this on the initial PR, but great work on the tests! 🙌

**Comment by clarkzinzow** [comment]
Btw, it looks like there's [an ASAN failure](https://buildkite.com/ray-project/ray-builders-pr/builds/4910#b3ad2871-cbc7-401d-8597-55edddf37409) for a [reference count](https://github.com/ray-project/ray/blob/5c59b726e82c89ce01cf2357e6eb938d95731326/src/ray/core_worker/reference_count_test.cc#L2218) test that might need attention.

**Comment by rkooo567** [comment]
@clarkzinzow Yeah I am aware of that one. It is super weird because it is not memory-related errors + never been reproducible in my laptop... I will make sure to fix this issue (probably there are some funny mistakes).

File: src/ray/pubsub/publisher.cc (hunk 5 above)
Comment (rkooo567) [reply src/ray/pubsub/publisher.cc:252]: Yep! Haven't addressed @jovany-wang's last comments.

File: src/ray/pubsub/publisher.cc [hunk 13]
```diff
@@ -20,149 +20,188 @@ namespace pubsub {
...
+                                            const SubscriberID &subscriber_id) {
+  const auto message_id = ParseBinary(message_id_binary);
+  auto &subscribing_message_ids = subscribers_to_message_id_[subscriber_id];
+  RAY_CHECK(subscribing_message_ids.emplace(message_id).second);
+  auto &subscriber_map = message_id_to_subscribers_[message_id];
   RAY_CHECK(subscriber_map.emplace(subscriber_id).second);
 }
 
+template <typename MessageID>
 absl::optional<std::reference_wrapper<const absl::flat_hash_set<SubscriberID>>>
```
Comment (iycheng) [inline src/ray/pubsub/publisher.cc:34]: I'd prefer returning raw pointer instead. std::ref makes things look complicated. 
```
const absl::flat_hash_set<SubscriberID>*
```
return nullptr if not exist. For optional kind of thing, you always need to check whether it exists or not. Usually, if it's passing-by-value, and it can also be null, I'll use optional.

File: src/ray/pubsub/publisher.h [hunk 14]
```diff
@@ -54,31 +56,45 @@ class SubscriptionIndex {
   /// Erase the object id and subscriber id from the index. Return the number of erased
   /// entries.
   /// NOTE: It cannot erase subscribers that were never added.
-  bool EraseEntry(const ObjectID &object_id, const SubscriberID &subscriber_id);
+  bool EraseEntry(const std::string &message_id_binary,
+                  const SubscriberID &subscriber_id);
 
   /// Return true if the object id exists in the index.
-  bool HasObjectId(const ObjectID &object_id) const;
+  bool HasMessageId(const std::string &message_id_binary) const;
```
Comment (iycheng) [inline src/ray/pubsub/publisher.h:63]: Is this API used outside of testing? If no, could you please move it into private and mark it as a testing API?

File: src/ray/pubsub/publisher.h [hunk 15]
```diff
@@ -89,16 +105,19 @@ class Subscriber {
...
-  bool ConnectToSubscriber(LongPollConnectCallback long_polling_reply_callback);
+  bool ConnectToSubscriber(rpc::PubsubLongPollingReply *reply,
+                           rpc::SendReplyCallback send_reply_callback);
 
   /// Queue the object id to publish to the subscriber.
   ///
-  /// \param object_id Object id to publish to the subscriber.
+  /// \param pub_message A message to publish.
   /// \param try_publish If true, it try publishing the object id if there is a
   /// connection. False is used only for testing.
```
Comment (iycheng) [inline src/ray/pubsub/publisher.h:118]: Not quite happy with exposing API for testing only purpose :(

File: src/ray/pubsub/publisher.h [hunk 16]
```diff
@@ -108,7 +127,7 @@ class Subscriber {
   bool PublishIfPossible(bool force = false);
 
   /// Testing only. Return true if there's no metadata remained in the private attribute.
-  bool AssertNoLeak() const;
+  bool CheckNoLeaks() const;
```
Comment (iycheng) [inline src/ray/pubsub/publisher.h:130]: Move to private if for testing.

File: src/ray/pubsub/publisher.cc [hunk 17]
```diff
@@ -20,149 +20,188 @@ namespace pubsub {
...
+
+  // Update the long polling reply.
+  auto *next_long_polling_reply = mailbox_.back().get();
+  auto *new_pub_message = next_long_polling_reply->add_pub_messages();
+  new_pub_message->Swap(pub_message.get());
+
+  // If the reply is too big, add a new entry.
+  if (next_long_polling_reply->pub_messages_size() >= publish_batch_size_) {
+    mailbox_.push_back(absl::make_unique<rpc::PubsubLongPollingReply>());
+  }
```
Comment (iycheng) [inline src/ray/pubsub/publisher.cc:150]: Let's try this:

```
if (mailbox_.empty() || mailbox_.back()->pub_messages() > publish_batch_size_) {
    mailbox_.push_back(absl::make_unique<rpc::PubsubLongPollingReply>());
}
```

File: src/ray/pubsub/publisher.cc [hunk 18]
```diff
@@ -20,149 +20,188 @@ namespace pubsub {
...
 
   if (force || mailbox_.size() > 0) {
-    std::vector<ObjectID> mails_to_post;
-    while (mailbox_.size() > 0 && mails_to_post.size() < publish_batch_size_) {
-      // It ensures that mails are posted in the FIFO order.
-      mails_to_post.push_back(mailbox_.front());
-      mailbox_.pop_front();
+    // If force pubilsh is invoked, mailbox could be empty. Fill this up in that case.
+    if (mailbox_.size() == 0) {
+      mailbox_.push_back(absl::make_unique<rpc::PubsubLongPollingReply>());
```
Comment (iycheng) [inline src/ray/pubsub/publisher.cc:165]: This part is wired here. Should we remove this? If it's empty, should we just skip sending the message?

File: src/ray/pubsub/subscriber.cc [hunk 19]
```diff
@@ -18,174 +18,272 @@ namespace ray {
...
+template <typename MessageID>
+bool SubscriberChannel<MessageID>::SubscriptionExists(const PublisherID &publisher_id) {
+  return subscription_map_.count(publisher_id);
+}
+
+///////////////////////////////////////////////////////////////////////////////
+/// Subscriber
+///////////////////////////////////////////////////////////////////////////////
+
+inline std::shared_ptr<SubscribeChannelInterface> Subscriber::Channel(
```
Comment (iycheng) [inline src/ray/pubsub/subscriber.cc:181]: why inline here?

**Review by fishbone — DISMISSED** [review]
This PR is too big. We should avoid this as much as possible in the future. I haven't reviewed `subscriber.h/cc` yet. Except for these, all the rest has been reviewed.

File: src/ray/common/ray_config_def.h [hunk 20]
```diff
@@ -405,7 +405,7 @@ RAY_CONFIG(int64_t, asio_stats_print_interval_ms, -1)
 RAY_CONFIG(float, max_task_args_memory_fraction, 0.7)
 
 /// The maximum number of objects to publish for each publish calls.
-RAY_CONFIG(uint64_t, publish_batch_size, 5000)
+RAY_CONFIG(int, publish_batch_size, 5000)
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/common/ray_config_def.h:410]: I will go with uint

File: src/ray/pubsub/mock_pubsub.h [hunk 21]
```diff
@@ -0,0 +1,58 @@
+// Copyright 2017 The Ray Authors.
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/pubsub/mock_pubsub.h:1]: It was hard for some reasons. Feel free to try out.

File: src/ray/core_worker/reference_count.cc [hunk 22]
```diff
@@ -866,12 +900,24 @@ void ReferenceCounter::HandleRefRemoved(const ObjectID &object_id,
...
   }
-  // Send the owner information about any new borrowers.
-  ReferenceTableToProto(borrowed_refs, reply->mutable_borrowed_refs());
 
-  RAY_LOG(DEBUG) << "Replying to WaitForRefRemoved, reply has "
-                 << reply->borrowed_refs().size();
-  send_reply_callback(Status::OK(), nullptr, nullptr);
+  // Send the owner information about any new borrowers.
+  std::unique_ptr<rpc::PubMessage> pub_message = absl::make_unique<rpc::PubMessage>();
+  pub_message->set_message_id(object_id.Binary());
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/reference_count.cc:906]: will use key

File: src/ray/pubsub/publisher.h (hunk 16 above)
Comment (rkooo567) [reply src/ray/pubsub/publisher.h:130]: Will use better gtest solution or tons of FRIEND_TEST instead.

File: src/ray/pubsub/subscriber.cc (hunk 19 above)
Comment (rkooo567) [reply src/ray/pubsub/subscriber.cc:181]: because this function is frequently called, but pretty tiny.

File: src/ray/pubsub/subscriber.cc (hunk 10 above)
Comment (rkooo567) [reply src/ray/pubsub/subscriber.cc:229]: Personally thinking this placeholder stuff is hard to read, so I will just keep the current style.

File: src/ray/core_worker/reference_count.cc (hunk 22 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/reference_count.cc:906]: Actually KeyIdType makes the most sense imo, so I will use it.

File: src/ray/pubsub/publisher.h (hunk 16 above)
Comment (rkooo567) [reply src/ray/pubsub/publisher.h:125]: For some classes like internal classes, this is necessary to be public, and I think it is fine for them because they are not meant to be re-used. But for the top level classes like Publisher and Subscriber, I will use friend test

File: src/ray/core_worker/reference_count.cc [hunk 23]
```diff
@@ -778,18 +792,39 @@ void ReferenceCounter::WaitForRefRemoved(const ReferenceTable::iterator &ref_it,
...
-            ReferenceTableFromProto(reply.borrowed_refs());
-        MergeRemoteBorrowers(object_id, addr, new_borrower_refs);
+        // If the message is published, this callback will be invoked.
+        const auto message_published_callback = [this, addr,
+                                                 object_id](const rpc::PubMessage &msg) {
+          RAY_CHECK(msg.has_wait_for_ref_removed_message());
+          const ReferenceTable new_borrower_refs =
+              ReferenceTableFromProto(msg.wait_for_ref_removed_message().borrowed_refs());
+
+          absl::MutexLock lock(&mutex_);
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/reference_count.cc]: Actually, making this thread-safe causes some test failures. Let me actually do this in a separate PR, so I can make sure the current changes work properly. Does it sound okay?

File: src/ray/core_worker/reference_count.cc [hunk 24]
```diff
@@ -778,18 +792,39 @@ void ReferenceCounter::WaitForRefRemoved(const ReferenceTable::iterator &ref_it,
...
+              rpc::ChannelType::WORKER_REF_REMOVED_CHANNEL, addr.ToProto(),
+              object_id.Binary()));
+        };
+
+        // If the borrower is failed, this callback will be called.
+        const auto publisher_failed_callback = [this, addr, object_id]() {
+          // When the request is failed, there's no new borrowers ref published from this
+          // borrower.
+          absl::MutexLock lock(&mutex_);
+          CleanupBorrowersOnRefRemoved({}, object_id, addr);
```
Comment (jovany-wang) [inline src/ray/core_worker/reference_count.cc:815]: `addr` can be moved here:
`CleanupBorrowersOnRefRemoved({}, object_id, std::move(addr));`

File: src/ray/core_worker/reference_count.cc [hunk 25]
```diff
@@ -778,18 +792,39 @@ void ReferenceCounter::WaitForRefRemoved(const ReferenceTable::iterator &ref_it,
...
+        };
+
+        // If the request was failed, we just invoke the failure callback right away.
+        if (!status.ok()) {
```
Comment (jovany-wang) [inline src/ray/core_worker/reference_count.cc:819]: It's better to print a log here to let us have a chance to know the wrong status if it fails.
Otherwise, once it fails, we have no idea on the issue.

File: src/ray/pubsub/publisher.cc [hunk 26]
```diff
@@ -20,149 +20,183 @@ namespace pubsub {
...
-    LongPollConnectCallback long_polling_reply_callback) {
-  if (long_polling_reply_callback_ == nullptr) {
-    long_polling_reply_callback_ = long_polling_reply_callback;
+bool Subscriber::ConnectToSubscriber(rpc::PubsubLongPollingReply *reply,
+                                     rpc::SendReplyCallback send_reply_callback) {
+  if (!long_polling_connection_) {
+    RAY_CHECK(reply != nullptr);
+    RAY_CHECK(send_reply_callback != nullptr);
+    long_polling_connection_ =
+        absl::make_unique<LongPollConnection>(reply, std::move(send_reply_callback));
```
Comment (jovany-wang) [inline src/ray/pubsub/publisher.cc:128]: Since C++14 is enabled in Ray, use `std::make_unique` instead because the type of `long_polling_connection_` is std::unique_ptr.

File: src/ray/pubsub/publisher.cc [hunk 27]
```diff
@@ -207,24 +243,30 @@ void Publisher::Publish(const ObjectID &object_id) {
...
   }
 }
 
-bool Publisher::UnregisterSubscriber(const SubscriberID &subscriber_id) {
+bool Publisher::UnregisterSubscription(const rpc::ChannelType channel_type,
+                                       const SubscriberID &subscriber_id,
+                                       const std::string &key_id_binary) {
   absl::MutexLock lock(&mutex_);
-  return UnregisterSubscriberInternal(subscriber_id);
+  return subscription_index_map_[channel_type].EraseEntry(key_id_binary, subscriber_id);
```
Comment (jovany-wang) [inline src/ray/pubsub/publisher.cc:254]: Is it safe that `subscription_index_map_` has no key `channel_type` and then this line is invoked？
It's inserted an empty entry and then invoke the `empty_entry.EraseEntry()`.

File: src/ray/pubsub/subscriber.cc [hunk 28]
```diff
@@ -18,174 +18,268 @@ namespace ray {
...
-  return subscription_map_.size() == 0;
+
+  if (SubscriptionExists(publisher_id)) {
+    MakeLongPollingPubsubConnection(publisher_address, subscriber_address);
+  } else {
+    publishers_connected_.erase(publisher_id);
+  }
 }
 
+inline bool Subscriber::SubscriptionExists(const PublisherID &publisher_id) {
```
Comment (jovany-wang) [inline src/ray/pubsub/subscriber.cc:263]: IIUC, inlining a member method should be placed into class definition in the .h file.

**Review by jovany-wang — APPROVED** [review]
Looks pretty good now. I left some minor comments.

File: src/ray/core_worker/core_worker.cc [hunk 29]
```diff
@@ -451,8 +451,25 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
   profiler_ = std::make_shared<worker::Profiler>(
       worker_context_, options_.node_ip_address, io_service_, gcs_client_);
 
+  core_worker_client_pool_ =
+      std::make_shared<rpc::CoreWorkerClientPool>(*client_call_manager_);
+
+  object_status_publisher_ = std::make_unique<pubsub::Publisher>(
+      /*periodical_runner=*/&periodical_runner_,
+      /*get_time_ms=*/[]() { return absl::GetCurrentTimeNanos() / 1e6; },
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:459]: This is for unit testing, and we use this pattern in many places (look at PullManager as an example).

File: src/ray/pubsub/subscriber.cc (hunk 28 above)
Comment (rkooo567) [reply src/ray/pubsub/subscriber.cc:263]: Hmm I see. Obviously I misunderstood the meaning of the keyword (thought inline keyword == header function). Will fix move then to header files.

File: src/ray/pubsub/publisher.cc (hunk 27 above)
Comment (rkooo567) [reply src/ray/pubsub/publisher.cc:254]: Hmm my assumption is people won't do this sort of mistake (or it will be revealed right away if you do so), but I can just add a CHECK instead here.

File: src/ray/core_worker/reference_count.cc (hunk 24 above)
Comment (rkooo567) [reply src/ray/core_worker/reference_count.cc:815]: Actually I should've just used pass by reference. It is probably just a mistake.

File: src/ray/pubsub/publisher.cc (hunk 26 above)
Comment (rkooo567) [reply src/ray/pubsub/publisher.cc:128]: Good catch. Will fix.

File: src/ray/pubsub/subscriber.cc (hunk 19 above)
Comment (rkooo567) [reply src/ray/pubsub/subscriber.cc:180]: Looks like inline doesn't mean the function is actually inlined. I will move the definition to the header instead to get true inline functions.

**Comment by rkooo567** [comment]
Docker / Mac wheel build times out frequently. The flaky test seems to pass, but it failed for some weird reasons. I will just merge it.
