### PR TITLE
Fix resource bookkeeping bug with acquiring unknown resource.

### LINKED ISSUE #4870: [tune] Raylet crashing if zero resource capacity is used
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.12 and Ubuntu 16.04 (can reproduce on both)
- **Ray installed from (source or binary)**: binary
- **Ray version**: 0.7.0
- **Python version**: 3.5, 3.6, 3.7 (can reproduce on all)
- **Exact command to reproduce**: See minimal snippet source code to reproduce.
 

### Describe the problem

I am attempting to use a Ray Actor (functioning as a data reader/cache singleton) inside of a function that is being optimized using Ray Tune. After the optimization process runs for about 10 minutes, it always fails with a Raylet connection closed exception and quits the optimization process. 

e.g.
```
Exception: [RayletClient] Raylet connection closed.

2019-05-25 22:23:57,216	ERROR worker.py:1678 -- The node with client ID 13f2e72398ffd893090f7fd31bae0c1409755432 has been marked dead because the monitor has missed too many heartbeats from it.
```

The error seems to be related to the duration of the optimization task, not the cpu load as evident from the minimal example (see below). Even with various changes to the task (run on OSX, run on Ubuntu, change python version, set reuse actors to false/true, change number of cpus in init), the error still appears. A minimal code to reproduce the error is provided below. Is this a bug in the heartbeat generation for Ray Actors?

A functioning work around was to remove the Ray Actor and instead create a function with a filesystem lock file to create the singleton.  Are Ray Actors supported as part of a Ray Tune optimization process?

### Source code / logs

Minimal source code to reproduce the error (Takes about 10 minutes to hit the error):

```
import ray
import time
from lockfile import LockFile
import numpy as np
import pickle
from ray.tune import Trainable, run, Experiment, sample_from
from ray.tune.schedulers import HyperBandScheduler, AsyncHyperBandScheduler

@ray.remote(resources={'datasource': 1})
class DataService(object):
    def __init__(self):
        pass
    
    def get_data_for_item(self,config):
        lock = LockFile
        lock = LockFile("/tmp/test.lockb")
        print(lock.path, 'trying to acquire.')
        lock.acquire()
        print(lock.path, 'is locked.')
        time.sleep(2)
        thing = config.get('identifier',"")+"whatever"
        lock.release()
        print(lock.path, 'is released.')
        return thing

class MyTrainableClass(Trainable):

    def _setup(self, config):
        self.config = config
        self.timestep = 0
    
    def _train(self):
        self.timestep += 1
        print("what is params",self.config)
        val = ray.get(self.config['remote_service'].get_data_for_item.remote(self.config))
        time.sleep(20)
        self.result = val
        print("result",self.config['identifier'],val)
        return {'objective': len(val), 'done': True}

        return {'objective': -1, 'done': True}

    def _save(self, checkpoint_dir):
        path = os.path.join(checkpoint_dir, "checkpoint",str(self.timestep))
        if not os.path.exists(os.path.dirname(path)):
            os.makedirs(os.path.dirname(path))
        with open(path, "wb") as f:
            pickle.dump(self.result,f)
        return path

    def _restore(self, checkpoint_path):
        with open(checkpoint_path,'rb') as f:
            self.config = pickle.load(f)
            self.timestep = 1


ray.shutdown()
ray.init(num_cpus=7,resources={"datasource": 1},object_store_memory=200000000,log_to_driver=True,)
remote_h = DataService.remote()
print("remote_h", remote_h)
hyperband = AsyncHyperBandScheduler(
    time_attr="training_iteration",
    reward_attr="objective",
        max_t=100,)
exp = Experiment(
    name="asynchyperband_class_testx",
    run=MyTrainableClass,
    num_samples=150,
    stop={"training_iteration": 150},
    config= 
    {
        'identifier' : ray.tune.sample_from(lambda x: np.random.choice(['good','better','best','longest'])),
        'useless' : ray.tune.sample_from(lambda x: np.random.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])),
        #'window' : ray.tune.sample_from(lambda x: np.random.choice([40,50,60,70,80,90,100,110])),
        #'window2' : ray.tune.sample_from(lambda x: np.random.choice([40,50,60,70,80,90,100,110])),
        #'thresh' : ray.tune.sample_from(lambda x: np.random.choice(list(range(20,70,2)))),
        #'thresh2' : ray.tune.sample_from(lambda x: np.random.choice(list(range(20,60,2)))),
        'remote_service' : remote_h 
    }
    )
trials = run(exp,scheduler=hyperband,verbose=1, reuse_actors=True)
del remote_h
ray.shutdown()
```

Observed Exception (OSX 10.12, Python 3.6.0, Ray 0.7.0 from pip):
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-4-38f977638a63> in <module>()
     24     }
     25     )
---> 26 trials = run(exp,scheduler=hyperband,verbose=1, reuse_actors=True)
     27 del remote_h
     28 ray.shutdown()

/Users/wgroves/venv/tensorflow/lib/python3.6/site-packages/ray/tune/tune.py in run(run_or_experiment, name, stop, config, resources_per_trial, num_samples, local_dir, upload_dir, trial_name_creator, loggers, sync_function, checkpoint_freq, checkpoint_at_end, export_formats, max_failures, restore, search_alg, scheduler, with_server, server_port, verbose, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial)
    245     last_debug = 0
    246     while not runner.is_finished():
--> 247         runner.step()
    248         if time.time() - last_debug > DEBUG_PRINT_INTERVAL:
    249             if verbose:

/Users/wgroves/venv/tensorflow/lib/python3.6/site-packages/ray/tune/trial_runner.py in step(self)
    274                 self.trial_executor.start_trial(next_trial)
    275         elif self.trial_executor.get_running_trials():
--> 276             self._process_events()  # blocking
    277         else:
    278             for trial in self._trials:

/Users/wgroves/venv/tensorflow/lib/python3.6/site-packages/ray/tune/trial_runner.py in _process_events(self)
    438 
    439     def _process_events(self):
--> 440         trial = self.trial_executor.get_next_available_trial()  # blocking
    441         with warn_if_slow("process_trial"):
    442             self._process_trial(trial)

/Users/wgroves/venv/tensorflow/lib/python3.6/site-packages/ray/tune/ray_trial_executor.py in get_next_available_trial(self)
    290         # See https://github.com/ray-project/ray/issues/4211 for details.
    291         start = time.time()
--> 292         [result_id], _ = ray.wait(shuffled_results)
    293         wait_time = time.time() - start
    294         if wait_time > NONTRIVIAL_WAIT_TIME_THRESHOLD_S:

/Users/wgroves/venv/tensorflow/lib/python3.6/site-packages/ray/worker.py in wait(object_ids, num_returns, timeout)
   2322             timeout_milliseconds,
   2323             False,
-> 2324             worker.current_task_id,
   2325         )
   2326         return ready_ids, remaining_ids

python/ray/_raylet.pyx in ray._raylet.RayletClient.wait()

python/ray/_raylet.pyx in ray._raylet.check_status()

Exception: [RayletClient] Raylet connection closed.

2019-05-25 22:23:57,216	ERROR worker.py:1678 -- The node with client ID 13f2e72398ffd893090f7fd31bae0c1409755432 has been marked dead because the monitor has missed too many heartbeats from it.
```

raylet_monitor.err file:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0525 22:23:57.210012 3839128512 monitor.cc:49] Client timed out: 13f2e72398ffd893090f7fd31bae0c1409755432
```

raylet.err file:
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
W0525 22:13:38.203748 3839128512 stats.h:50] Failed to create the Prometheus exporter. This doesn't affect anything except stats. Caused by: null context when constructing CivetServer. Possible problem binding to port.
W0525 22:14:23.657073 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:25.661929 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:27.668455 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:29.674670 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:31.684083 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:33.697531 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:47.302045 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:49.309584 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:51.318904 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:53.325412 3839128512 node_manager.cc:1726] Resources oversubscribed: {}
W0525 22:14:56.674257 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:14:58.680490 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:15:10.775121 3839128512 node_manager.cc:1726] Resources oversubscribed: {CPU,0.000000}
W0525 22:15:12.781167 3839128512 node_manager.cc:1726] Resources oversubscribed: {}
...
W0525 22:22:57.761237 3839128512 node_manager.cc:1726] Resources oversubscribed: {}
W0525 22:23:21.603353 3839128512 node_manager.cc:1726] Resources oversubscribed: {}
F0525 22:23:25.221491 3839128512 scheduling_resources.cc:171]  Check failed: resource_capacity_.count(resource_label) == 1 Attempt to acquire unknown resource: CPU
*** Check failure stack trace: ***
*** Aborted at 1558837405 (unix time) try "date -d @1558837405" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7fffdbf5ed42) received by PID 85294 (TID 0x7fffe4d473c0) stack trace: ***
    @     0x7fffdc03fb3a _sigtramp
    @        0x10ac0f551 (unknown)
    @     0x7fffdbec4420 abort
    @        0x105e1d899 google::logging_fail()
    @        0x105e1c5d6 google::LogMessage::SendToLog()
    @        0x105e1ccc5 google::LogMessage::Flush()
    @        0x105e1cda2 google::LogMessage::~LogMessage()
    @        0x105e16835 ray::RayLog::~RayLog()
    @        0x105d42a8c ray::raylet::ResourceSet::SubtractResourcesStrict()
    @        0x105d1368b ray::raylet::NodeManager::HandleTaskUnblocked()
    @        0x105d10748 ray::raylet::NodeManager::ProcessClientMessage()
    @        0x105d3331c std::__1::__function::__func<>::operator()()
    @        0x105e081fc ray::ClientConnection<>::ProcessMessage()
    @        0x105e101b8 boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @        0x105cecff3 boost::asio::detail::scheduler::do_run_one()
    @        0x105ceca42 boost::asio::detail::scheduler::run()
    @        0x105cdf561 main
    @     0x7fffdbe30235 start
    @               0x10 (unknown)
```

### LINKED ISSUE #4892: Zero resources might crash the raylet
The crash can be reproduced with the following script (this is on 0.7.0 from pip):

```python
import ray

ray.init(num_cpus=0)

@ray.remote(num_cpus=0) 
class A(object): 
    def __init__(self): 
        pass 
    def f(self): 
        pass

a = A.remote()
x = a.f.remote()
ray.get(x)
```

The last line crashes the raylet with
```
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0529 21:13:02.770886 18815 stats.h:48] Succeeded to initialize stats: exporter address is 127.0.0.1:8888
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
*** Aborted at 1559164424 (unix time) try "date -d @1559164424" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x3e80000497f) received by PID 18815 (TID 0x7f9b6a960740) from PID 18815; stack trace: ***
    @     0x7f9b6a540890 (unknown)
    @     0x7f9b69634e97 gsignal
    @     0x7f9b69636801 abort
    @     0x7f9b6a0298b7 (unknown)
    @     0x7f9b6a02fa06 (unknown)
    @     0x7f9b6a02fa41 std::terminate()
    @     0x7f9b6a02fc74 __cxa_throw
    @     0x7f9b6a02b78f (unknown)
    @           0x45800a std::__detail::_Map_base<>::at()
    @           0x465ae2 ray::raylet::NodeManager::AssignTask()
    @           0x466407 ray::raylet::NodeManager::DispatchTasks()
    @           0x46ef6a ray::raylet::NodeManager::ProcessGetTaskMessage()
    @           0x471b6b ray::raylet::NodeManager::ProcessClientMessage()
    @           0x43011d _ZNSt17_Function_handlerIFvSt10shared_ptrIN3ray16ClientConnectionIN5boost4asio5local15stream_protocolEEEElPKhEZNS1_6raylet6Raylet12HandleAcceptERKNS3_6system10error_codeEEUlS8_lSA_E0_E9_M_invokeERKSt9_Any_dataS8_lSA_
    @           0x4e21a0 ray::ClientConnection<>::ProcessMessage()
    @           0x4de5aa boost::asio::detail::read_op<>::operator()()
    @           0x4de6f3 boost::asio::detail::reactive_socket_recv_op<>::do_complete()
    @           0x42497d boost::asio::detail::scheduler::run()
    @           0x40e041 main
    @     0x7f9b69617b97 __libc_start_main
    @           0x41f571 (unknown)
```

### PR DESCRIPTION
**Pull request by robertnishihara**
This appears to fix #4870. Also fixes https://github.com/ray-project/ray/issues/4892

### CODE REVIEW

**Review by pcmoritz — APPROVED** [review]
LGTM, great catch!

File: src/ray/raylet/scheduling_resources.cc [hunk 1]
```diff
@@ -76,7 +76,11 @@ ResourceSet::ResourceSet() {}
 
 ResourceSet::ResourceSet(
     const std::unordered_map<std::string, FractionalResourceQuantity> &resource_map)
-    : resource_capacity_(resource_map) {}
+    : resource_capacity_(resource_map) {
+  for (auto const &resource_pair : resource_map) {
+    RAY_CHECK(resource_pair.second > 0);
```
Comment (atumanov) [inline src/ray/raylet/scheduling_resources.cc]: This prevents the ability to create a resource set with any zero capacity resource. One of the use cases we supported in the past is a local laptop with zero CPU allocation to prevent work assignment/force all work assignment to the remote cluster.

Comment (atumanov) [reply src/ray/raylet/scheduling_resources.cc]: so, this change would break backward compatibility

Comment (robertnishihara) [reply src/ray/raylet/scheduling_resources.cc]: That's actually still supported. This PR shouldn't have any API implications. The resources with quantity 0 are filtered out before getting to this constructor.

File: src/ray/raylet/node_manager.cc [hunk 2]
```diff
@@ -1814,9 +1814,9 @@ bool NodeManager::AssignTask(const Task &task) {
   cluster_resource_map_[my_client_id].Acquire(spec.GetRequiredResources());
 
   if (spec.IsActorCreationTask()) {
-    // Check that we are not placing an actor creation task on a node with 0 CPUs.
-    RAY_CHECK(cluster_resource_map_[my_client_id].GetTotalResources().GetResourceMap().at(
-                  kCPU_ResourceLabel) != 0);
+    // Check that the actor's placement resource requirements are satisfied.
+    RAY_CHECK(spec.GetRequiredPlacementResources().IsSubset(
+        cluster_resource_map_[my_client_id].GetTotalResources()));
```
Comment (atumanov) [inline src/ray/raylet/node_manager.cc]: this change looks like it would allow placing zero CPU actor creation tasks on a node with zero CPUs.  The current behavior is to disallow it. Is this what we want?

File: src/ray/raylet/scheduling_resources.cc (hunk 1 above)
Comment (atumanov) [reply src/ray/raylet/scheduling_resources.cc]: I'm just not comfortable with a constructor that breaks the whole raylet if you pass it a fairly reasonable zero resource capacity attribute. This restricts the programmatic expressivity of the ResourceSet. This should also be extensively tested with dynamic custom resources (ESCHER), while allowing some custom resource to drop down to zero capacity. There's a possibility that somewhere in the code we make a copy of the ResourceSet that's dynamically updated to \vec{r} = [..., 0, ...] and trigger this check. I.e., I'm not as worried about the static resource case as I am about the dynamic resource case.

File: src/ray/raylet/node_manager.cc (hunk 2 above)
Comment (robertnishihara) [reply src/ray/raylet/node_manager.cc]: Well, the current behavior is to crash according to https://github.com/ray-project/ray/issues/4892. I view this more as a bug fix and not a change in behavior. The requirement of needing a CPU for placing the actor only applies to actors that do not acquire lifetime resources. The actors that do acquire lifetime resources can be placed as long as they can acquire those resources.

File: src/ray/raylet/scheduling_resources.cc (hunk 1 above)
Comment (robertnishihara) [reply src/ray/raylet/scheduling_resources.cc]: We maintain the invariant that all quantities in a `ResourceSet` are positive. That means that there is a unique internal representation for a given set of resource capacities and reduces the number of cases we have to check. We implemented those semantics in https://github.com/ray-project/ray/pull/4555.

This change makes sure to enforce those semantics more clearly (and the absence of this change allowed the bug to creep in). Note that the constructor below has the same check.

Comment (romilbhardwaj) [reply src/ray/raylet/scheduling_resources.cc]: I think as long as other methods of ResourceSet that update capacity are correctly implemented, dynamic custom resources should be fine even when capacity drops to zero. As @robertnishihara pointed out, any illegal updates must be filtered out before this code is invoked. If they're not, raising a check fail here seems helpful for isolating bugs.

**Review by romilbhardwaj — APPROVED** [review]

File: src/ray/raylet/scheduling_resources.cc (hunk 1 above)
Comment (atumanov) [reply src/ray/raylet/scheduling_resources.cc]: @robertnishihara , I see, I suppose it makes sense to be consistent with the second constructor, which is already performing this check. Longer term, not having the ability to represent a zero in a system seems broken to me. There was this major breakthrough in mathematics when people invented zero...
