### PR TITLE
[gcs] Fix detached actor fail to restart when GCS restarted.

### LINKED ISSUE #25128: [core] Align semantics when GCS is down
As part of GCS HA project, we need to align the behavior when GCS is down to this doc:

https://docs.google.com/document/d/1k4C7KcUN-KCJ5wbO2NPz_pOhYn6PLLuKDBgWdvSmGbg/edit

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

When loading the data from GCS, for detached actors, we treat it the same as normal actors. 
But the detached actor lives beyond the job's scope and should be loaded even when the job is finished.
This PR fixed it.

## Related issue number
#25128 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -1176,7 +1176,8 @@ void GcsActorManager::Initialize(const GcsInitData &gcs_init_data) {
   for (const auto &[actor_id, actor_table_data] : gcs_init_data.Actors()) {
     auto job_iter = jobs.find(actor_id.JobId());
     auto is_job_dead = (job_iter == jobs.end() || job_iter->second.is_dead());
-    if (actor_table_data.state() != ray::rpc::ActorTableData::DEAD && !is_job_dead) {
+    if (actor_table_data.state() != ray::rpc::ActorTableData::DEAD &&
```
Comment (scv119) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:1179]: can you add an inline comment

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
LGTM!
