### PR TITLE
[Core] Fix check failure due to negative available resource

### LINKED ISSUE #50433: [Core] Crash in raylet (ray::RayLog::~RayLog)
### What happened + What you expected to happen

I am experiencing raylet crashes like this:

```
(raylet) [2025-02-11 18:42:15,859 C 30797 30797] resource_instance_set.cc:374:  Check failed: RAY_PREDICT_TRUE(_left_ >= _right_)  0 vs 10000
(raylet) *** StackTrace Information ***
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc17c7a) [0x559ef7d2ac7a] ray::operator<<()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc1a0c1) [0x559ef7d2d0c1] ray::RayLog::~RayLog()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x67b7a9) [0x559ef778e7a9] ray::NodeResourceInstanceSet::AllocateWithReference()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x67c545) [0x559ef778f545] ray::NodeResourceInstanceSet::TryAllocate()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4b4fe1) [0x559ef75c7fe1] ray::LocalResourceManager::AllocateTaskResourceInstances()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4ba4fd) [0x559ef75cd4fd] ray::LocalResourceManager::AllocateLocalTaskResources()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4ba5c3) [0x559ef75cd5c3] ray::LocalResourceManager::AllocateLocalTaskResources()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x3b2fd2) [0x559ef74c5fd2] ray::raylet::LocalTaskManager::DispatchScheduledTasksToWorkers()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x3b4262) [0x559ef74c7262] ray::raylet::LocalTaskManager::ScheduleAndDispatchTasks()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x4a1011) [0x559ef75b4011] ray::raylet::ClusterTaskManager::ScheduleAndDispatchTasks()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x32f58f) [0x559ef744258f] ray::raylet::NodeManager::HandleReturnWorker()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x31ed17) [0x559ef7431d17] ray::rpc::ServerCallImpl<>::HandleRequestImpl()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x6a0248) [0x559ef77b3248] EventTracker::RecordExecution()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x69b23e) [0x559ef77ae23e] std::_Function_handler<>::_M_invoke()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x69b6b6) [0x559ef77ae6b6] boost::asio::detail::completion_handler<>::do_complete()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc8c2bb) [0x559ef7d9f2bb] boost::asio::detail::scheduler::do_run_one()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc8e849) [0x559ef7da1849] boost::asio::detail::scheduler::run()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0xc8ed62) [0x559ef7da1d62] boost::asio::io_context::run()
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x1ecb8f) [0x559ef72ffb8f] main
(raylet) /lib/x86_64-linux-gnu/libc.so.6(+0x2724a) [0x7fa042a6324a]
(raylet) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x85) [0x7fa042a63305] __libc_start_main
(raylet) /usr/local/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet(+0x246ec7) [0x559ef7359ec7]
(raylet) 
Traceback (most recent call last):
  File "/code/labs/jakob/ray/test/crash.py", line 33, in <module>
    main()
  File "/code/labs/jakob/ray/test/crash.py", line 30, in main
    ray.get(tasks)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 2772, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/ray/_private/worker.py", line 921, in get_objects
    raise value
ray.exceptions.LocalRayletDiedError: The task's local raylet died. Check raylet.out for more information.
```

The above error is reproduced by the Python script provided below. To reproduce, one can simply run the script as `python3 script.py` and let Ray start up a local cluster.

However, it is worth noting that I am experiencing the same issue in my productions system on KubeRay with separate head and worker nodes.

### Versions / Dependencies

Ray version: 2.41.0

### Reproduction script

```
import os
os.environ['RAY_DEDUP_LOGS'] = "0"
import ray
from ray.util.placement_group import placement_group
from ray.util.scheduling_strategies import PlacementGroupSchedulingStrategy
import time

ray.init()

# Limit number of worker nodes
NUM_WORKERS = 6
pg = placement_group([{"CPU": 1}] * NUM_WORKERS)
pg_strategy = PlacementGroupSchedulingStrategy(pg)

@ray.remote(scheduling_strategy=pg_strategy)
def g(i: int):
    print(f"g {i}")
    time.sleep(0.1)

@ray.remote(scheduling_strategy=pg_strategy)
def f():
    print("f")
    ray.get([g.remote(i) for i in range(10)])
    print("f done")

def main():
    tasks = []
    for i in range(4):
        tasks.append(f.remote())
    ray.get(tasks)

main()
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?

The sequence of events that can trigger the check failure:
1. A node has PG resources `{"CPU_group_aaa": 2, "CPU_group_0_aaa": 1, "CPU_group_1_aaa": 1}`
2. Worker1 acquires 1 PG CPU resource, node available resource becomes `{"CPU_group_aaa": 1, "CPU_group_0_aaa": 0, "CPU_group_1_aaa": 1}`
3. Worker1 calls ray.get() which temporarily released its CPU resource, node available resource becomes  `{"CPU_group_aaa": 2, "CPU_group_0_aaa": 1, "CPU_group_1_aaa": 1}`
4. Worker2 acquires 1 PG CPU resource, node available resource becomes `{"CPU_group_aaa": 1, "CPU_group_0_aaa": 0, "CPU_group_1_aaa": 1}`
5. ray.get() returns from worker1 and it acquires back the resource, node available resource becomes `{"CPU_group_aaa": 0, "CPU_group_0_aaa": -1, "CPU_group_1_aaa": 1}`
6. Worker3 acquires 1 PG CPU resource and the check failure happens since it can get `CPU_group_1_aaa` but not `CPU_group_aaa`. The fix is that we allow `CPU_group_aaa` to go negative as well to match the indexed PG CPU resources.

## Related issue number
Closes #50433

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/common/scheduling/resource_instance_set.cc [hunk 1]
```diff
@@ -371,7 +371,12 @@ void NodeResourceInstanceSet::AllocateWithReference(
   RAY_CHECK_EQ(available.size(), ref_allocation.size());
 
   for (size_t i = 0; i < ref_allocation.size(); i++) {
-    RAY_CHECK_GE(available[i], ref_allocation[i]);
+    if (available[i] < ref_allocation[i]) {
+      // Only CPU resource can go negative due to the behavior
```
Comment (MengjinYan) [inline src/ray/common/scheduling/resource_instance_set.cc:375]: Probably need to update the comment to the function description as well:
https://github.com/ray-project/ray/blob/master/src/ray/common/scheduling/resource_instance_set.h#L153

File: src/ray/common/scheduling/resource_instance_set.cc [hunk 2]
```diff
@@ -371,7 +371,12 @@ void NodeResourceInstanceSet::AllocateWithReference(
...
+      // that ray.get() will temporarily release the CPU resource.
+      // See https://github.com/ray-project/ray/pull/50517.
+      RAY_CHECK(IsCPUOrPlacementGroupCPUResource(resource_id));
```
Comment (MengjinYan) [inline src/ray/common/scheduling/resource_instance_set.cc:378]: Nit: The result of resource id check failure can be confusing. I'm wondering if it is better to use `RAY_CHECK_WITH_DISPLAY` and with a explicit error message to it.

Comment (dentiny) [reply src/ray/common/scheduling/resource_instance_set.cc:378]: `RAY_CHECK(...) << ...` should include more information

File: src/ray/common/bundle_spec.h [hunk 3]
```diff
@@ -126,6 +126,8 @@ std::string GetOriginalResourceName(const std::string &resource);
 // Returns "" if the resource is not a wildcard resource.
 std::string GetOriginalResourceNameFromWildcardResource(const std::string &resource);
 
+bool IsCPUOrPlacementGroupCPUResource(ResourceID resource_id);
```
Comment (dentiny) [inline src/ray/common/bundle_spec.h:129]: nit: documentation

**Review by MengjinYan — APPROVED** [review]
Thanks!
