### PR TITLE
[Core] Prevent dedicated workers from being returned to general idle pool

### LINKED ISSUE #15360: [Core] override_environment_variables reuses old processes with wrong envs
### What is the problem?
```python
import ray
ray.init()

import os

@ray.remote
def f():
    return os.environ.get("TEST123")

@ray.remote
def g():
    return os.environ.get("TEST123")

ray.get(f.options(override_environment_variables={"TEST123": "VAL123"}).remote())

print(ray.get(g.remote()))
# Output: "VAL123"
# Output is supposed to be empty.
```

In this example, when running `g` it appears that Ray incorrectly reuses the worker process created for `f`, which retains the environment variables for `f`.  This seems to happen when there are no environment variable overrides provided, so it goes into this code path where it "pops the most recent worker": https://github.com/ray-project/ray/blob/master/src/ray/raylet/worker_pool.cc#L843

*Ray version and other system information (Python version, TensorFlow version, OS):*
Ray 1.2.0 and master. Python 3.6, Mac OS Big Sur
### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by architkulkarni**
Previously, dedicated workers (those with dynamic options for an Actor creation task) were returned to the general idle pool after use.  This is fine for when the dynamic options don't change the state of the worker process.

However, we now want to use this functionality for Runtime Envs for actors and tasks.  Worker processes with runtime envs will have environment variables set and other kinds of state (conda envs, docker, etc), so they should not be returned to the general idle pool.  Instead, they should be cached using the Runtime Env as a key.

This PR is a first step towards that worker caching.  In this PR, we keep track of dedicated workers and don't return them to the general idle pool.  This PR adds a test that failed before because workers with specified environment variables were being returned to the general idle pool.

This PR does not change the worker cache, which just uses TaskID as a key.  A followup PR will cache these workers using a key which is the tuple (Runtime env, taskID, dynamic_options). 

This outline contains my understanding of the code path of a new task which requires a dedicated worker, and it might help the reviewer:
1. `PopWorker` is called.  There is no suitable worker (HasPendingWorkerforTask is false), so a new process is created.  The relationship is saved in `dedicated_workers_to_tasks` and `task_to_dedicated_workers`.  (This PR renames these maps by adding the word "pending" before "dedicated."). These maps are checked by `HasPendingWorkerforTask`.
2. `PopWorker` may be called again.  Since `HasPendingWorkerforTask` is now true, we skip the above code path and nothing happens.
3. At some point, `PushWorker` is called. We check the maps above and place the ready worker into the `idle_dedicated_workers` map.
4. `PopWorker` is called.  A suitable worker is found in `idle_dedicated_workers`, so we can actually run the task.  (New in this PR: We save the relationship in a new map `dedicated_registered_workers_to_tasks`)
5. `PushWorker` is called when the task is done.  Rather than push the worker into the general pool `idle_of_all_languages`, in this PR we return it to `idle_dedicated_workers`.
## Related issue number

Closes https://github.com/ray-project/ray/issues/15360

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/worker_pool.cc [hunk 1]
```diff
@@ -664,15 +664,23 @@ void WorkerPool::PushWorker(const std::shared_ptr<WorkerInterface> &worker) {
...
-  if (it != state.dedicated_workers_to_tasks.end()) {
-    // The worker is used for the actor creation task with dynamic options.
-    // Put it into idle dedicated worker pool.
-    const auto task_id = it->second;
+  auto it_p = state.pending_dedicated_workers_to_tasks.find(worker->GetProcess());
+  auto it_r = state.registered_dedicated_workers_to_tasks.find(worker->GetProcess());
+  if (it_p != state.pending_dedicated_workers_to_tasks.end()) {
+    // The worker is used for a task which needs a dedicated worker process.
+    // Put it into the idle dedicated worker pool.
+    const auto task_id = it_p->second;
```
Comment (edoakes) [inline src/ray/raylet/worker_pool.cc:672]: why don't we need to remove the entry from `pending_dedicated_workers_to_tasks` here?

File: src/ray/raylet/worker_pool.cc [hunk 2]
```diff
@@ -664,15 +664,23 @@ void WorkerPool::PushWorker(const std::shared_ptr<WorkerInterface> &worker) {
   RAY_CHECK(worker->GetAssignedTaskId().IsNil())
       << "Idle workers cannot have an assigned task ID";
   auto &state = GetStateForLanguage(worker->GetLanguage());
-  auto it = state.dedicated_workers_to_tasks.find(worker->GetProcess());
-  if (it != state.dedicated_workers_to_tasks.end()) {
-    // The worker is used for the actor creation task with dynamic options.
-    // Put it into idle dedicated worker pool.
-    const auto task_id = it->second;
+  auto it_p = state.pending_dedicated_workers_to_tasks.find(worker->GetProcess());
+  auto it_r = state.registered_dedicated_workers_to_tasks.find(worker->GetProcess());
```
Comment (edoakes) [inline src/ray/raylet/worker_pool.cc:668]: It seems like we should be able to combine these into a single map, but I'm probably missing something -- what's the reason they need to be separate?

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (architkulkarni) [reply src/ray/raylet/worker_pool.cc:672]: This is the existing code, and the entries are removed in PopWorker here: https://github.com/ray-project/ray/pull/15545/files/dc9402c85dc504013ce8ce3522541379f74136cd#diff-4c19d6ebd8575189e9439fa5646b567546dc54f64d576a959ce1bb43902d1a03L842

But it's a good question, I'm not really sure why they need to be removed in PopWorker and not in PushWorker.  I'll keep thinking about it

Comment (architkulkarni) [reply src/ray/raylet/worker_pool.cc:672]: Okay, I think the two approaches are actually equivalent, so let me move the erasing from Popworker to Pushworker.  This will also allow me to unify the two maps to address your comment above https://github.com/ray-project/ray/pull/15545/files/dc9402c85dc504013ce8ce3522541379f74136cd#r621478246.

File: src/ray/raylet/worker_pool.cc (hunk 2 above)
Comment (architkulkarni) [reply src/ray/raylet/worker_pool.cc:668]: Good point, at first I thought this wasn't possible but I think I was limiting myself by trying to make an incremental change.  Let me rewrite things so it just uses one map

**Comment by edoakes** [comment]
@architkulkarni looks like there was a failure in `test_runtime_env` this time.

**Review by edoakes — APPROVED** [review]
