### PR TITLE
Fix asyncio plasma integration in cluster mode

### LINKED ISSUE #11649: Async await not working when result is fetched from another node's object store
### What is the problem?

* ray 1.0.0

### Reproduction (REQUIRED)
Ray remote actor tasks can be `await`ed. However, this only works reliably when the driver and the actor run on the same ray node. If this is not the case, `await` statements can take infinitely long.

In the script below, the `OTHER_NODE` custom resource is to indicate that this actor should be scheduled a node that's different from the driver of the script.
```
import os
import numpy as np
import ray
import asyncio

head_service = os.environ.get('RAY_HEAD_SERVICE_HOST')
head_port = os.environ.get('RAY_HEAD_SERVICE_PORT_REDIS_PRIMARY')
address = f"{head_service}:{head_port}" if head_service is not None else None
ray.init(address=address)

TOTAL_IMAGES = 10

@ray.remote(num_cpus=0,  resources={"OTHER_NODE": 1})
class ResultActor:
    def __init__(self):
        self.results = {}

    def predict(self, i, image):
        self.results[i] = image
    
    async def get_async_result(self, i):
        result = self.results.pop(i, None)
        while result is None:
            print(f"Awaiting {i}")
            result = self.results.pop(i, None)
            print(f"Done awaiting {i}")
            await asyncio.sleep(1)
        print(f"GOT RESULT FOR {i}")
        return result


result_actor = ResultActor.remote()

# SEND DATA TO ResultActor
for i in range(TOTAL_IMAGES):
    image = (np.random.random((192, 1080, 3)) * 255).astype(np.uint8)  # ~ 0.5MB
    result_actor.predict.remote(i, image)

# Async get all data
async def get_all_results():
    futs = []
    fails = 0
    for i in range(TOTAL_IMAGES):
        fut = result_actor.get_async_result.remote(i)
        futs.append(fut)
        try:
            await asyncio.wait_for(fut, timeout=5)
            print(f"SUCCESS {i}")
        except:
            print(f"FAIL {i}")
            fails += 1

    # ALTERNATIVE: Await all at the same time
    # done, pending = await asyncio.wait(futs, timeout=5)
    # if len(pending):
    #     print(f"FAILED! {int(100.*len(pending)/TOTAL_IMAGES)}% tasks not succeeded!")

    print(f"FAIL RATIO: {int(100.*fails/TOTAL_IMAGES)}%")


loop = asyncio.new_event_loop()
loop.run_until_complete(get_all_results())
```
The output of this script is:
```
2020-10-27 16:31:23,203	INFO worker.py:634 -- Connecting to existing Ray cluster at address: 10.43.87.248:6379
(pid=883, ip=10.42.0.8) GOT RESULT FOR 0
FAIL 0
(pid=883, ip=10.42.0.8) GOT RESULT FOR 1
FAIL 1
SUCCESS 2
(pid=883, ip=10.42.0.8) GOT RESULT FOR 2
(pid=883, ip=10.42.0.8) GOT RESULT FOR 3
FAIL 3
(pid=883, ip=10.42.0.8) GOT RESULT FOR 4
FAIL 4
(pid=883, ip=10.42.0.8) GOT RESULT FOR 5
FAIL 5
(pid=883, ip=10.42.0.8) GOT RESULT FOR 6
FAIL 6
SUCCESS 7
(pid=883, ip=10.42.0.8) GOT RESULT FOR 7
(pid=883, ip=10.42.0.8) GOT RESULT FOR 8
FAIL 8
(pid=883, ip=10.42.0.8) GOT RESULT FOR 9
FAIL 9
FAIL RATIO: 80%
```
As shown, we get print statements from the actor returning data, but the main process does not receive the data it is awaiting.

When the Actor is scheduled on the driver node, there is no issue.
When the data that is transfered is small (I assume <100kB) there also is no issue.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
See more details in https://github.com/ray-project/ray/issues/11649, this PR fixes `await object_ref` hanging in cluster mode when it involves plasma objects.

## Related issue number
Closes #11649

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -2283,10 +2283,17 @@ void CoreWorker::PlasmaCallback(SetResultCallback success,
                                 std::shared_ptr<RayObject> ray_object, ObjectID object_id,
                                 void *py_future) {
   std::vector<std::shared_ptr<RayObject>> vec;
+  bool object_is_local = false;
+
   // Check if object is available before subscribing to plasma.
-  if (Get(std::vector<ObjectID>{object_id}, 0, &vec).ok() && vec.size() > 0) {
+  if (Contains(object_id, &object_is_local).ok() && object_is_local) {
```
Comment (simon-mo) [inline src/ray/core_worker/core_worker.cc:2289]: Changed it to `Contains` so it won't trigger unnecessary pull requests and immediately cancel them.

Comment (ijrsvt) [reply src/ray/core_worker/core_worker.cc:2289]: Could you throw a comment in explaining this behavior?

File: src/ray/raylet/node_manager.cc [hunk 2]
```diff
@@ -2957,6 +2968,13 @@ void NodeManager::ProcessSubscribePlasmaReady(
 
   auto message = flatbuffers::GetRoot<protocol::SubscribePlasmaReady>(message_data);
   ObjectID id = from_flatbuf<ObjectID>(*message->object_id());
+
+  // Tell task dependency manager to pull the objects.
+  // NOTE(simon): This doesn't handle cancellation and edge case invovling eviciton.
```
Comment (ijrsvt) [inline src/ray/raylet/node_manager.cc:2973]: Could you maybe expand on this TODO/NOTE?

File: python/ray/tests/test_asyncio_cluster.py [hunk 3]
```diff
@@ -0,0 +1,34 @@
...
+    def get_array():
+        return np.random.random((192, 1080, 3)).astype(np.uint8)  # ~ 0.5MB
+
+    object_ref = get_array.remote()
+
+    await asyncio.wait_for(object_ref, timeout=10)
+
+    ray.shutdown()
+    cluster.shutdown()
+
```
Comment (ijrsvt) [inline python/ray/tests/test_asyncio_cluster.py:30]: Is this guaranteed to fail without this fix? Or do you need to run it more times?

**Review by ijrsvt — APPROVED** [review]
Looks good overall--left a few comments on changes to make!

File: python/ray/tests/test_asyncio_cluster.py (hunk 3 above)
Comment (simon-mo) [reply python/ray/tests/test_asyncio_cluster.py:30]: It's guaranteed to fail without `SubscribeWaitDependencies`. It's a little more flakey with the Get() we had originally but we guarded them with `Contains` now.

File: src/ray/raylet/node_manager.cc [hunk 4]
```diff
@@ -2957,6 +2968,13 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
+  std::vector<rpc::ObjectReference> refs = {FlatbufferToSingleObjectReference(
+      *message->object_id(), *message->owner_address())};
+  task_dependency_manager_.SubscribeWaitDependencies(associated_worker->WorkerId(), refs);
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:2976]: Just purely out of curiosity, but why do we use `SubscribeWaitDependencies ` instead of `SubscribeGetDependencies `?

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -2304,7 +2311,7 @@ void CoreWorker::PlasmaCallback(SetResultCallback success,
   SubscribeToPlasmaAdd(object_id);
 
   // Check in-memory store in case object became ready *before* SubscribeToPlasmaAdd.
-  if (Get(std::vector<ObjectID>{object_id}, 0, &vec).ok() && vec.size() > 0) {
+  if (Contains(object_id, &object_is_local).ok() && object_is_local) {
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc:2314]: Hmm now that I'm looking at this code more carefully, isn't there still an issue with this block of code? I get the race condition that this is supposed to guard against, but the worker doesn't wait for the raylet to reply that the subscription completed. So there's still a window after this block of code where the object could appear but we haven't subscribed yet.

It seems like a better approach would be to remove this block completely and just have the raylet fire the callbacks if the object is already local when it receives the subscribe request.

File: src/ray/raylet/node_manager.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc:2976]: The methods are not named that well, but I copied the main differences from the header file:
```
SubscribeWaitDependencies
  /// The TaskDependencyManager will track all remote dependencies until the
  /// dependencies are local, or until UnsubscribeWaitDependencies is called
  /// with the same worker ID, whichever occurs first.
```
```
SubscribeGetDependencies
  /// The TaskDependencyManager will track the task's dependencies
  /// until UnsubscribeGetDependencies is called on the same task ID.
```

So SubscribeGetDependencies is supposed to be for tasks that are blocked on some dependencies, and SubscribeWaitDependencies is for a worker that is subscribing asynchronously to stream of dependencies (like with `ray.wait`). I think this class could use a refactor though :)

File: src/ray/core_worker/core_worker.cc (hunk 5 above)
Comment (edoakes) [reply src/ray/core_worker/core_worker.cc:2314]: Yep, agreed. Another potential solution would be to make the `SubscribeToPlasmaAdd` RPC synchronous and optionally return a boolean indicating that the object is ready. I don't see a significant to that and it adds a codepath, so preference for @stephanie-wang's suggestion.

We could actually even drop the initial `Get` call in that case, though that might be a worthwhile optimization.

File: src/ray/raylet/node_manager.cc (hunk 2 above)
Comment (simon-mo) [reply src/ray/raylet/node_manager.cc]: Added, PTAL!

File: src/ray/raylet/node_manager.cc [hunk 6]
```diff
@@ -2957,16 +2968,47 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
-    if (!async_plasma_objects_notification_.contains(id)) {
-      async_plasma_objects_notification_.emplace(
-          id, absl::flat_hash_set<std::shared_ptr<WorkerInterface>>());
-    }
 
-    // Only insert a worker once
-    if (!async_plasma_objects_notification_[id].contains(associated_worker)) {
-      async_plasma_objects_notification_[id].insert(associated_worker);
+  if (task_dependency_manager_.CheckObjectLocal(id)) {
+    // Object is already local, so we directly fires the callback to tell core worker
```
Comment (edoakes) [inline src/ray/raylet/node_manager.cc:2973]:
```suggestion
    // Object is already local, so we directly fire the callback to tell the core worker
```

File: src/ray/raylet/node_manager.cc [hunk 7]
```diff
@@ -2957,16 +2968,47 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
+    // plasma object is ready.
```
Comment (edoakes) [inline src/ray/raylet/node_manager.cc:2974]:
```suggestion
    // that the plasma object is ready.
```

File: src/ray/raylet/node_manager.cc [hunk 8]
```diff
@@ -2957,16 +2968,47 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
+    // The object is not local, so we are subscribing to pull and wait for the objects.
+    std::vector<rpc::ObjectReference> refs = {FlatbufferToSingleObjectReference(
+        *message->object_id(), *message->owner_address())};
+
+    // NOTE(simon): This call will issue a pull request to remote workers and make sure
+    // the object will be local.
+    // 1. We currently do not allow user to cancel this call. The object will be pulled
+    //    even if the `await object_ref` is cancelled.
+    // 2. We currently do not handle edge cases with object eviction where the object
+    //    is evicted locally or on remote machine.
```
Comment (edoakes) [inline src/ray/raylet/node_manager.cc:2996]: Could you elaborate on what the edge cases we need to handle are?

File: src/ray/raylet/node_manager.cc [hunk 9]
```diff
@@ -2957,16 +2968,47 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
+        });
+  } else {
+    // The object is not local, so we are subscribing to pull and wait for the objects.
+    std::vector<rpc::ObjectReference> refs = {FlatbufferToSingleObjectReference(
+        *message->object_id(), *message->owner_address())};
+
+    // NOTE(simon): This call will issue a pull request to remote workers and make sure
+    // the object will be local.
+    // 1. We currently do not allow user to cancel this call. The object will be pulled
+    //    even if the `await object_ref` is cancelled.
```
Comment (edoakes) [inline src/ray/raylet/node_manager.cc:2994]: This seems fine for now. In the future is it possible to have a hook in python that cancels the subscription when the coroutine is cancelled/timed out?

File: src/ray/raylet/node_manager.cc (hunk 8 above)
Comment (edoakes) [reply src/ray/raylet/node_manager.cc:2996]: There seems to be a possible issue where the object is local during this handler but by the time it reaches the worker it has been evicted locally. This should already be handled by the `GetAsync` callback that will recursively subscribe if it fails to get the objects locally. I'd add a comment in the core worker specifying this.

File: src/ray/core_worker/core_worker.cc [hunk 10]
```diff
@@ -2301,24 +2312,11 @@ void CoreWorker::PlasmaCallback(SetResultCallback success,
...
-    for (auto callback : callbacks) {
-      // This callback needs to be asynchronous because it runs on the io_service_, so no
-      // RPCs can be processed while it's running. This can easily lead to deadlock (for
-      // example if the callback calls ray.get() on an object that is dependent on an RPC
-      // to be ready).
-      callback();
-    }
-  }
+  // Ask raylet to subscribe to object notification. Raylet will call this core worker
+  // when the object is local. HandlePlasmaObjectReady handles such request.
```
Comment (edoakes) [inline src/ray/core_worker/core_worker.cc:2317]: Add a comment that the raylet will fire the callback immediately if the object is already available

File: src/ray/raylet/node_manager.cc [hunk 11]
```diff
@@ -2957,16 +2968,47 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
-    absl::MutexLock guard(&plasma_object_notification_lock_);
-    if (!async_plasma_objects_notification_.contains(id)) {
-      async_plasma_objects_notification_.emplace(
-          id, absl::flat_hash_set<std::shared_ptr<WorkerInterface>>());
-    }
 
-    // Only insert a worker once
-    if (!async_plasma_objects_notification_[id].contains(associated_worker)) {
-      async_plasma_objects_notification_[id].insert(associated_worker);
+  if (task_dependency_manager_.CheckObjectLocal(id)) {
```
Comment (edoakes) [inline src/ray/raylet/node_manager.cc:2972]: The semantics of this method are now a bit more complicated (and important as evidenced by the issue we're solving). Could you makes sure to update the header comment for `ProcessSubscribePlasmaReady` to be more clear?

**Review by edoakes — APPROVED** [review]
LGTM, just nits and suggestions for comments. Let's also wait for @stephanie-wang to sign off because she's most familiar with the subscribing logic.

File: src/ray/core_worker/core_worker.cc [hunk 12]
```diff
@@ -2282,22 +2282,26 @@ void CoreWorker::YieldCurrentFiber(FiberEvent &event) {
 void CoreWorker::PlasmaCallback(SetResultCallback success,
                                 std::shared_ptr<RayObject> ray_object, ObjectID object_id,
                                 void *py_future) {
-  std::vector<std::shared_ptr<RayObject>> vec;
+  // This is the base case. A typical call stack for async plasma get looks like:
+  // GetAsync -> PlasmaCallback (ask Raylet) -> HandlePlasmaObjectReady ->
+  // plasma_arrived_callback -> GetAsync -> PlasmaCallback (this base case).
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc:2287]: Maybe a nit, but I don't really understand this comment (I'm not very familiar with the async code). It would be nice if the comment could be self-contained, so you don't need to reference other parts of the code to understand this part.

File: src/ray/raylet/node_manager.cc (hunk 8 above)
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc:2996]: Yes, just to confirm, it shouldn't be a problem as long as the worker subscribes again.

File: src/ray/raylet/node_manager.cc [hunk 13]
```diff
@@ -2969,22 +2969,46 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
+    // NOTE(simon): This call will issue a pull request to remote workers and make sure
+    // the object will be local.
+    // 1. We currently do not allow user to cancel this call. The object will be pulled
+    //    even if the `await object_ref` is cancelled.
+    // 2. We currently do not handle edge cases with object eviction where the object
+    //    is evicted locally or on remote machine.
+    task_dependency_manager_.SubscribeWaitDependencies(associated_worker->WorkerId(),
+                                                       refs);
+
+    // Add this worker to listener for the object id.
```
Comment (stephanie-wang) [inline src/ray/raylet/node_manager.cc:3000]:
```suggestion
    // Add this worker to the listeners for the object ID.
```

File: src/ray/raylet/node_manager.cc [hunk 14]
```diff
@@ -2969,22 +2969,46 @@ void NodeManager::ProcessSubscribePlasmaReady(
...
+    {
+      absl::MutexLock guard(&plasma_object_notification_lock_);
+      if (!async_plasma_objects_notification_.contains(id)) {
```
Comment (stephanie-wang) [inline src/ray/raylet/node_manager.cc:3003]: FYI, I think you can replace all this code with just `async_plasma_objects_notification_[id].insert(associated_worker)` (C++ will dedupe shared_ptrs).

**Review by stephanie-wang — APPROVED** [review]
Left a few suggestions, but the fix looks good!
