### PR TITLE
[runtime env] Short-circuit protobuf serialization/deserialization for empty runtime envs

### LINKED ISSUE #21760: [1.10.0 Release] `stress_test_many_tasks` regression
Context: https://github.com/ray-project/ray/pull/21512#discussion_r788310272

Result from 1.10.0:
```
"stage_3_creation_time": 0.06580400466918945,
"stage_3_time": 2932.907886981964,
```
 

This is a significant regression from 1.9:
```
"stage_3_creation_time": 0.05767488479614258, 
"stage_3_time": 1949.1530861854553
```

### PR DESCRIPTION
**Pull request by architkulkarni**
## Why are these changes needed?
`stress_test_many_tasks` had a performance regression.

A test PR attributed a significant part of the performance loss to `OverrideTaskOrActorRuntimeEnv`: https://github.com/ray-project/ray/pull/21780

Inside this function, we short circuit some serialization/deserialization logic if the runtime environment is empty.  However, an empty serialized runtime environment is `"{}"` (a serialized empty JSON dict.), but the existing code only checked for equality to `""`.  This PR fixes the check.

We should probably wait to merge this until we verify that the `stress_test_many_tasks` performance was improved.

## Related issue number

Partially addresses #21760 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -1462,13 +1462,13 @@ std::string CoreWorker::OverrideTaskOrActorRuntimeEnv(
     std::vector<std::string> *runtime_env_uris) {
   std::shared_ptr<rpc::RuntimeEnv> parent = nullptr;
   if (options_.worker_type == WorkerType::DRIVER) {
-    if (serialized_runtime_env == "") {
+    if (serialized_runtime_env == "{}") {
```
Comment (jjyao) [inline src/ray/core_worker/core_worker.cc:1465]: Is it possible to be `""` as well in some cases? Should we check both?

**Review by rkooo567 — APPROVED** [review]

File: src/ray/core_worker/core_worker.cc (hunk 1 above)
Comment (architkulkarni) [reply src/ray/core_worker/core_worker.cc]: Good point, I only observed `"{}"` but it's probably better to be safe and also check `""`.  I've updated the PR.

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -1462,13 +1462,13 @@ std::string CoreWorker::OverrideTaskOrActorRuntimeEnv(
     std::vector<std::string> *runtime_env_uris) {
   std::shared_ptr<rpc::RuntimeEnv> parent = nullptr;
   if (options_.worker_type == WorkerType::DRIVER) {
-    if (serialized_runtime_env == "") {
+    if (serialized_runtime_env == "" || serialized_runtime_env == "{}") {
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:1465]: Thinking now, can we just create a util function? Like `IsRuntimeEnvEmpty(serialized_runtime_env)` and use it all across the codebase

Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:1465]: This doesn't need to block this PR

Comment (jjyao) [reply src/ray/core_worker/core_worker.cc:1465]: Agree, we should clean this up.

**Review by jjyao — APPROVED** [review]

**Comment by architkulkarni** [comment]
Results:
```
INFO:__main__:Finished stage 3 actor creation in 0.06654715538024902 seconds.
INFO:__main__:Finished stage 3 in 2339.6809968948364 seconds.
```

**Comment by rkooo567** [comment]
Seems to be consistent with jiajun. but there’s still 300-400 seconds regressionxz

**Comment by rkooo567** [comment]
I believe it is good enough to unblock the release though.. (about 20%). Thoughts @iycheng ?

**Review by SongGuyang — APPROVED** [review]
LGTM. Thank you for this fix!

**Comment by rkooo567** [comment]
Hey @architkulkarni can you make sure to follow up on https://github.com/ray-project/ray/pull/21788#discussion_r790045804?
