### PR TITLE
[Core][CoreWorker] fix data race during exiting

### LINKED ISSUE #18857: [Core] CoreWorker crash due to destruction order
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen
```
Caught signal 11 (Segmentation fault: address not mapped to object at address 0x7eff867fbcc0)
==== backtrace (tid:  74387) ====
 0  /usr/lib/libucs.so.0(ucs_handle_error+0x10c) [0x7eced5f1a08c]
 1  /usr/lib/libucs.so.0(+0x2640c) [0x7eced5f1a40c]
 2  /usr/lib/libucs.so.0(+0x26684) [0x7eced5f1a684]
 3  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xb996ba) [0x7f000bb6f6ba]
 4  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xb5c01b) [0x7f000bb3201b]
 5  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xb63aff) [0x7f000bb39aff]
 6  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(_ZN9grpc_core6Server8CallData25RecvTrailingMetadataReadyEPvP10grpc_error+0xd5) [0x7f000bb277b5]
 7  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xb103af) [0x7f000bae63af]
 8  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xb0bd58) [0x7f000bae1d58]
 9  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xb0cee5) [0x7f000bae2ee5]
10  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(_ZN9grpc_core7ExecCtx5FlushEv+0x64) [0x7f000bb6bf04]
11  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(grpc_call_start_batch+0x1c9) [0x7f000bb3b619]
12  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(_ZN4grpc8internal9CallOpSetINS0_25CallOpSendInitialMetadataENS0_17CallOpSendMessageENS0_22CallOpServerSendStatusENS0_8CallNoOpILi4EEENS5_ILi5EEENS5_ILi6EEEE32ContinueFillOpsAfterInterceptionEv+0x206) [0x7f000b602796]
13  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(_ZN3ray3rpc14ServerCallImplINS0_24CoreWorkerServiceHandlerENS0_15PushTaskRequestENS0_13PushTaskReplyEE9SendReplyERKNS_6StatusE+0x145) [0x7f000b651ca5]
14  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(_ZNSt17_Function_handlerIFvN3ray6StatusESt8functionIFvvEES4_EZNS0_3rpc14ServerCallImplINS6_24CoreWorkerServiceHandlerENS6_15PushTaskRequestENS6_13PushTaskReplyEE17HandleRequestImplEvEUlS1_S4_S4_E_E9_M_invokeERKSt9_Any_dataOS1_OS4_SI_+0xf1) [0x7f000b651f51]
15  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0x6de364) [0x7f000b6b4364]
16  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0x6de8ba) [0x7f000b6b48ba]
17  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0x6cb8c2) [0x7f000b6a18c2]
18  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0x6d4772) [0x7f000b6aa772]
19  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xcba928) [0x7f000bc90928]
20  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xcbb4e1) [0x7f000bc914e1]
21  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xcbb5eb) [0x7f000bc915eb]
22  /opt/conda/lib/python3.7/site-packages/ray/_raylet.so(+0xcb47c1) [0x7f000bc8a7c1]
23  /lib/x86_64-linux-gnu/libpthread.so.0(+0x76db) [0x7f000d4f06db]
24  /lib/x86_64-linux-gnu/libc.so.6(clone+0x3f) [0x7f000d21971f]
=================================
*** SIGSEGV received at time=1632393798 on cpu 5 ***
PC: @     0x7f000bb6f6ba  (unknown)  pollset_kick()
    @     0x7f000d4fb980  (unknown)  (unknown)
    @     0x7f000bb3201b         96  cq_end_op_for_next()
    @     0x7f000bb39aff        144  post_batch_completion()                                                                                                                         [230/21514]
    @     0x7f000bb277b5         48  grpc_core::Server::CallData::RecvTrailingMetadataReady()
    @     0x7f000bae63af         48  recv_trailing_metadata_ready()
    @     0x7f000bae1d58         48  hs_recv_trailing_metadata_ready()
    @     0x7f000bae2ee5         32  grpc_core::(anonymous namespace)::CallData::OnRecvTrailingMetadataReady()
    @     0x7f000bb6bf04         48  grpc_core::ExecCtx::Flush()
    @     0x7f000bb3b619        192  grpc_call_start_batch
    @     0x7f000b602796        656  grpc::internal::CallOpSet<>::ContinueFillOpsAfterInterception()
    @     0x7f000b651ca5        160  ray::rpc::ServerCallImpl<>::SendReply()
    @     0x7f000b651f51        144  std::_Function_handler<>::_M_invoke()
    @     0x7f000b6b4364        368  ray::core::CoreWorkerDirectTaskReceiver::HandleTask()::{lambda()#1}::operator()()
    @     0x7f000b6b48ba         80  std::_Function_handler<>::_M_invoke()
    @     0x7f000b6a18c2         80  std::_Function_handler<>::_M_invoke()
    @     0x7f000b6aa772        208  boost::asio::detail::executor_op<>::do_complete()
    @     0x7f000bc90928        112  boost::asio::detail::scheduler::do_run_one()
    @     0x7f000bc914e1        160  boost::asio::detail::scheduler::run()
    @     0x7f000bc915eb         32  boost::asio::detail::posix_thread::func<>::run()
    @     0x7f000bc8a7c1         32  boost_asio_detail_posix_thread_function
    @     0x7f000d4f06db  (unknown)  start_thread
logging.cc:315: *** SIGSEGV received at time=1632393798 on cpu 5 ***
logging.cc:315: PC: @     0x7f000bb6f6ba  (unknown)  pollset_kick()
logging.cc:315:     @     0x7f000d4fb980  (unknown)  (unknown)
logging.cc:315:     @     0x7f000bb3201b         96  cq_end_op_for_next()
logging.cc:315:     @     0x7f000bb39aff        144  post_batch_completion()
logging.cc:315:     @     0x7f000bb277b5         48  grpc_core::Server::CallData::RecvTrailingMetadataReady()
logging.cc:315:     @     0x7f000bae63af         48  recv_trailing_metadata_ready()
logging.cc:315:     @     0x7f000bae1d58         48  hs_recv_trailing_metadata_ready()
logging.cc:315:     @     0x7f000bae2ee5         32  grpc_core::(anonymous namespace)::CallData::OnRecvTrailingMetadataReady()
logging.cc:315:     @     0x7f000bb6bf04         48  grpc_core::ExecCtx::Flush()
logging.cc:315:     @     0x7f000bb3b619        192  grpc_call_start_batch
logging.cc:315:     @     0x7f000b602796        656  grpc::internal::CallOpSet<>::ContinueFillOpsAfterInterception()
logging.cc:315:     @     0x7f000b651ca5        160  ray::rpc::ServerCallImpl<>::SendReply()
logging.cc:315:     @     0x7f000b651f51        144  std::_Function_handler<>::_M_invoke()
logging.cc:315:     @     0x7f000b6b4364        368  ray::core::CoreWorkerDirectTaskReceiver::HandleTask()::{lambda()#1}::operator()()
logging.cc:315:     @     0x7f000b6b48ba         80  std::_Function_handler<>::_M_invoke()
logging.cc:315:     @     0x7f000b6a18c2         80  std::_Function_handler<>::_M_invoke()
logging.cc:315:     @     0x7f000b6aa772        208  boost::asio::detail::executor_op<>::do_complete()
logging.cc:315:     @     0x7f000bc90928        112  boost::asio::detail::scheduler::do_run_one()
logging.cc:315:     @     0x7f000bc914e1        160  boost::asio::detail::scheduler::run()
logging.cc:315:     @     0x7f000bc915eb         32  boost::asio::detail::posix_thread::func<>::run()
logging.cc:315:     @     0x7f000bc8a7c1         32  boost_asio_detail_posix_thread_function
logging.cc:315:     @     0x7f000d4f06db  (unknown)  start_thread
```
### Reproduction script

Follow up with internal user.

### Anything else

_No response_

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by scv119**
exiting_ is being accessed by multiple threads; it should be atomic to be thread safe.

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -3057,15 +3058,16 @@ void CoreWorker::HandleExit(const rpc::ExitRequest &request, rpc::ExitReply *rep
...
-  send_reply_callback(Status::OK(),
-                      [this, is_idle]() {
-                        // If the worker is idle, we exit.
-                        if (is_idle) {
-                          Exit(rpc::WorkerExitType::IDLE_EXIT);
-                        }
-                      },
-                      // We need to kill it regardless if the RPC failed.
-                      [this]() { Exit(rpc::WorkerExitType::INTENDED_EXIT); });
+  send_reply_callback(
```
Comment (scv119) [inline src/ray/core_worker/core_worker.cc:3061]: clang-formatted

File: src/ray/core_worker/core_worker.h [hunk 2]
```diff
@@ -1409,7 +1409,8 @@ class CoreWorker : public rpc::CoreWorkerServiceHandler {
                       ObjectID object_id, void *py_future);
 
   /// Whether we are shutting down and not running further tasks.
-  bool exiting_ = false;
+  /// Being accessed by grpc thread and task_execution_service_ thread.
+  std::atomic<bool> exiting_;
```
Comment (mwtian) [inline src/ray/core_worker/core_worker.h:1413]: Good to comment on the behavior.

Btw, why not keep setting its default value?

Does it matter to call `exiting_.load(std::memory_order_relaxed)` when it is read?

**Review by mwtian — APPROVED** [review]
