### PR TITLE
[core] Cancel worker lease requests that are no longer needed

### LINKED ISSUE #7887: [Core] Apparent task/object leak on certain direct task calls.
### What is the problem?

Ray appears to be leaking tasks/objects on certain direct task calls. Namely, it appears that the raylet/node manager is losing track of direct task calls that depend on the same return object of an upstream task (and are possibly sharing a worker lease, need to confirm that.) So far, all instances of leaked tasks appear to correspond to pairs of tasks, sharing the same scheduler key and submitted nearly at the same time, both depending on the same task return object, with the task submitted second tending to be leaked.

From an end-user perspective, this leak manifests in many orphaned objects being left in the object store, none of which are retrievable (`ray.get()` hangs indefinitely.)

#### Version information

- Python 3.7.5
- Ubuntu 19.10
- ray at commit 93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b (will test on most recently built master commit soon)

### Bug Information

Currently unable to create a minimal reproduction, still working on that. @stephanie-wang said that it'd be a good idea to open an issue so this bug isn't only tracked by a Slack thread, and she was pretty confident that there is in fact a leak. Below is a summary of some log and code spelunking.

#### Summary

- Two tasks, `240f6960faf7db13ffffffff0100` and `c83000702c305163ffffffff0100`, depend on the same object `1d539110471eab4dffffffff010000c801000000`, and both appear to have the same scheduling key and both are making worker lease requests at around the same time.
- It appears that the lease request for the second task, `c83000702c305163ffffffff0100`, is never granted.
- It also appears that the raylet loses track of the second task: the task is never transitioned out of `READY`. Namely, in the node manager, [`FinishAssignTask()`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L3016-L3055) and [`FinishAssignedTask()`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L2412-L2456) are never called for the task.
- An object with ID `1d539110471eab4dffffffff010000c801000000` ends up being orphaned in the object store since the node manager thinks that task `c83000702c305163ffffffff0100` still depends on the object after its unpinned; this results in a failed object pull and a failed object reconstruction, which I believe means that the object orphaned in the object store is an error object.
- Not sure if the second task is reusing the first task's worker lease and is somehow making a lease request of its own, or if they aren't sharing a worker lease and the lease request never returns and the raylet loses track of the task for a different reason.

#### Details

There are two downstream tasks that depend on the return object of task `1d539110471eab4dffffffff0100`:

raylet:
```
I0331 01:26:54.120884  4315 task_dependency_manager.cc:184] Task 240f6960faf7db13ffffffff0100 blocked on object 1d539110471eab4dffffffff010000c801000000
I0331 01:26:55.895077  4315 task_dependency_manager.cc:184] Task c83000702c305163ffffffff0100 blocked on object 1d539110471eab4dffffffff010000c801000000
```

Both of these downstream tasks complete according to the worker:

python-worker:
```
I0331 01:26:55.904520  4339 core_worker.cc:1186] Finished executing task 240f6960faf7db13ffffffff0100
I0331 01:26:55.909976  4352 task_manager.cc:127] Completing task 240f6960faf7db13ffffffff0100
I0331 01:26:55.930382  4339 core_worker.cc:1186] Finished executing task c83000702c305163ffffffff0100
I0331 01:26:55.930879  4352 task_manager.cc:127] Completing task c83000702c305163ffffffff0100
```

However, according to the raylet logs, task `240f6960faf7db13ffffffff0100` finished but task `c83000702c305163ffffffff0100` did not:

raylet:
```
I0331 01:26:55.950846  4315 node_manager.cc:2414] Finished task 240f6960faf7db13ffffffff0100
```

In fact, from the raylet's perspective, the `c83000702c305163ffffffff0100`  task is never moved out of the ready queue into the running queue by the scheduler, the node manager never assigns the task to a worker, etc. I'm assuming that this is because that task is a direct task call whose scheduling decision is cached and an existing worker lease (provisioned by task `240f6960faf7db13ffffffff0100`) is being reused, so no worker lease is granted and it appears to go through a different code path that doesn't call [`FinishAssignTask()`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L3016-L3055) or [`FinishAssignedTask()`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L2412-L2456) in the node manager. Therefore, from the node manager's perspective, `c83000702c305163ffffffff0100`  is a queued task that still depends on the return object of task `1d539110471eab4dffffffff0100` when that object gets unpinned:

raylet:
```
I0331 01:26:55.950737  4315 node_manager.cc:3264] Unpinning object 1d539110471eab4dffffffff010000c801000000
I0331 01:26:56.616161  4315 node_manager.cc:2815] Object missing 1d539110471eab4dffffffff010000c801000000,  on 87b1fb4ac8cb822f02545201693611dc853749e7, 1 tasks waiting, tasks: c83000702c305163ffffffff0100
```

This will cause the task dependency manager to consider the object ID required, which causes an attempted (and failed) object pull and object reconstruction to kick off 10 seconds later:

https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L2804
https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/task_dependency_manager.cc#L170
https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/task_dependency_manager.cc#L73-L74
https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/reconstruction_policy.cc#L210-L223 

raylet:
```
# unpinned
I0331 01:26:55.950737  4315 node_manager.cc:3264] Unpinning object 1d539110471eab4dffffffff010000c801000000
I0331 01:26:56.616024  4315 object_directory.cc:71] Reporting object removed to GCS 1d539110471eab4dffffffff010000c801000000
I0331 01:26:56.616030  4315 service_based_accessor.cc:748] Removing object location, object id = 1d539110471eab4dffffffff010000c801000000, node id = 87b1fb4ac8cb822f02545201693611dc853749e7
# attempted object pull request
I0331 01:26:56.616096  4315 object_manager.cc:126] Pull on 87b1fb4ac8cb822f02545201693611dc853749e7 of object 1d539110471eab4dffffffff010000c801000000
I0331 01:26:56.616108  4315 service_based_accessor.cc:776] Subscribing object location, object id = 1d539110471eab4dffffffff010000c801000000
I0331 01:26:56.616137  4315 service_based_accessor.cc:781] Finished subscribing object location, object id = 1d539110471eab4dffffffff010000c801000000
# object reconstruction in 10 seconds from this point since pull request will fail
I0331 01:26:56.616145  4315 reconstruction_policy.cc:211] Listening and maybe reconstructing object 1d539110471eab4dffffffff010000c801000000
I0331 01:26:56.616161  4315 node_manager.cc:2815] Object missing 1d539110471eab4dffffffff010000c801000000,  on 87b1fb4ac8cb822f02545201693611dc853749e7, 1 tasks waiting, tasks: c83000702c305163ffffffff0100
# failed object pull
E0331 01:26:56.616714  4315 object_manager.cc:189] The object manager with ID 87b1fb4ac8cb822f02545201693611dc853749e7 is trying to pull object 1d539110471eab4dffffffff010000c801000000 but the object table suggests that this object manager already has the object. The object may have been evicted.
I0331 01:26:56.618919  4315 service_based_accessor.cc:762] Finished removing object location, status = OK, object id = 1d539110471eab4dffffffff010000c801000000, node id = 87b1fb4ac8cb822f02545201693611dc853749e7
# object reconstruction starts here, after waiting for 10 seconds
I0331 01:27:06.616205  4315 service_based_accessor.cc:653] Subscribing task lease, task id = 1d539110471eab4dffffffff0100
I0331 01:27:06.616250  4315 service_based_accessor.cc:658] Finished subscribing task lease, task id = 1d539110471eab4dffffffff0100
I0331 01:27:06.618786  4315 service_based_accessor.cc:574] Getting task, task id = 1d539110471eab4dffffffff0100
# task lineage not available in GCS since it was already cleaned up
W0331 01:27:06.619911  4315 node_manager.cc:2703] Metadata of task 1d539110471eab4dffffffff0100 not found in either GCS or lineage cache. It may have been evicted by the redis LRU configuration. Consider increasing the memory allocation via ray.init(redis_max_memory=<max_memory_bytes>).
I0331 01:27:06.620035  4315 service_based_accessor.cc:585] Finished getting task, status = Invalid: Task not exist., task id = 1d539110471eab4dffffffff0100
```

After the reconstruction fails, it appears that an object is put into the object store under that ID, which I believe is an error object (I can't inspect it since the object has already gone out of scope according to the Ray workers; a `ray.get()` call hangs indefinitely):

```
I0331 01:27:06.620035  4315 service_based_accessor.cc:585] Finished getting task, status = Invalid: Task not exist., task id = 1d539110471eab4dffffffff0100
I0331 01:27:06.620261  4315 object_manager.cc:78] Object added 1d539110471eab4dffffffff010000c801000000
I0331 01:27:06.620273  4315 object_directory.cc:62] Reporting object added to GCS 1d539110471eab4dffffffff010000c801000000
I0331 01:27:06.620281  4315 service_based_accessor.cc:721] Adding object location, object id = 1d539110471eab4dffffffff010000c801000000, node id = 87b1fb4ac8cb822f02545201693611dc853749e7
I0331 01:27:06.620378  4315 service_based_accessor.cc:787] Unsubscribing object location, object id = 1d539110471eab4dffffffff010000c801000000
I0331 01:27:06.620412  4315 service_based_accessor.cc:789] Finished unsubscribing object location, object id = 1d539110471eab4dffffffff010000c801000000
I0331 01:27:06.620429  4315 reconstruction_policy.cc:226] Reconstruction for object 1d539110471eab4dffffffff010000c801000000 canceled
I0331 01:27:06.620440  4315 service_based_accessor.cc:664] Unsubscribing task lease, task id = 1d539110471eab4dffffffff0100
I0331 01:27:06.620460  4315 service_based_accessor.cc:666] Finished unsubscribing task lease, task id = 1d539110471eab4dffffffff0100
I0331 01:27:06.620471  4315 node_manager.cc:2756] Object local 1d539110471eab4dffffffff010000c801000000,  on 87b1fb4ac8cb822f02545201693611dc853749e7, 1 tasks ready
I0331 01:27:06.620859  4315 service_based_accessor.cc:736] Finished adding object location, status = OK, object id = 1d539110471eab4dffffffff010000c801000000, node id = 87b1fb4ac8cb822f02545201693611dc853749e7
```

I believe that the reference counting logic is behaving as expected. It appears to be the `c83000702c305163ffffffff0100` task becoming untracked by the raylet/node manager that's causing the failed object pull and the failed task reconstruction. Whatever code path this task is taking, it needs to tell the raylet/node manager that the task is assigned (once it's assigned) and that it's finished (once it's finished.)

#### Direct Task Model Confusion

I'm still trying to wrap my head around the code path differences between a direct task that leases a worker and a direct task that reuses an existing worker lease. In this case, it appears that both tasks request a worker lease:

raylet:
```
I0331 01:26:54.120754  4315 node_manager.cc:1626] Worker lease request 240f6960faf7db13ffffffff0100
I0331 01:26:55.894937  4315 node_manager.cc:1626] Worker lease request c83000702c305163ffffffff0100
```

but only one is granted:

python-driver
```
I0331 01:26:55.894311  4352 direct_task_transport.cc:133] Lease granted 240f6960faf7db13ffffffff0100
```

suggesting that (if the lease is shared) a lease request is made for each task once dependencies are resolved, the lease is granted for the first task while the second task's lease request is not, the latter task is pushed to the worker after the former completes, but the former never calls the [`task_done_`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/core_worker/transport/direct_actor_transport.cc#L283-L290) callback, which never causes the raylet to indicate that the worker is available, so the worker is never put back into the worker pool, which causes the latter task to never be "assigned" (via [`NodeManager.AssignTask()`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L2327-L2410) or [`NodeManager.FinishAssignTask()`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/raylet/node_manager.cc#L3016-L3055)) to a worker, so the task is never transitioned to `RUNNING`.

However, I can't see how two lease requests on the same scheduling key could be in flight concurrently, given that the direct task submitter's [`RequestNewWorkerIfNeeded`](https://github.com/ray-project/ray/blob/93b5c38b7dc75b64a4812c1b300f48f9f1bf5d2b/src/ray/core_worker/transport/direct_task_transport.cc#L108-L151) is guarded by a mutex and a collision in `pending_lease_requests_` should short-circuit the function, preventing the second task from submitting a lease request. This would suggest that the second task isn't sharing a worker lease, but that makes the fact that the lease is never granted and the raylet losing track of the task even more confusing. Moreover, I've pretty sure that both tasks have the same scheduling key (they have the same resource requirements, function descriptor, and arguments.)

### Next Steps

- If anyone could shed some light on the intended submission flow and lifetime of direct tasks reusing worker leases, I would be forever grateful.
- I'm going to keep working on a minimal reproducible example and will add it to this issue if/when I find one.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://ray.readthedocs.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

During task submission, the core worker attempts to reuse leased workers to execute new tasks with the same resource requirements and plasma dependencies. This means that a previous lease request may not be necessary anymore, if the task it was meant for has already been executed by a reused worker. This PR cancels lease requests that are no longer needed.

Lease requests are canceled by contacting the raylet whom we asked for resources. Since grpc messages sent to the raylet can be reordedered, we retry the lease cancellation request until we receive the original reply for the lease request, or the raylet confirms that the request was cancelled.

## Related issue number

Closes #7887 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 1]
```diff
@@ -76,11 +76,39 @@ void CoreWorkerDirectTaskSubmitter::OnWorkerIdle(
...
+  if (it != pending_lease_requests_.end()) {
+    auto &lease_client = it->second.first;
+    auto &lease_id = it->second.second;
+    RAY_LOG(DEBUG) << "Canceling lease request " << lease_id;
+    RAY_UNUSED(lease_client->CancelWorkerLease(
+        lease_id, [this, lease_id, scheduling_key](
+                      const Status &status, const rpc::CancelWorkerLeaseReply &reply) {
+          absl::MutexLock lock(&mu_);
+          if (!status.ok() || reply.success()) {
+            RequestNewWorkerIfNeeded(scheduling_key);
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.cc:104]: Why is it needed to request a new worker?

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 2]
```diff
@@ -76,11 +76,39 @@ void CoreWorkerDirectTaskSubmitter::OnWorkerIdle(
...
+          } else {
+            CancelWorkerLeaseIfNeeded(scheduling_key);
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.cc:106]: Add a comment as to why we might need to retry.

Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.cc:106]: Is it possible cancellation failed, but we don't need to retry? For example, if the lease was granted before we could cancel it. Or should that be considered a successful cancellation?

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.cc:104]: This is needed in case a task gets submitted while we're trying to cancel a task. I can add a test case for this.

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.cc:106]: Oh oops, I did mean to count a granted lease as a successful cancellation in the raylet. I'll update it. Unfortunately, I can't think of a good way to test that.

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.cc:104]: Oh hmm actually I think it's fine since we retry in the callback for the original lease request. Anyway, the test will cover this scenario.

File: src/ray/raylet/node_manager.cc [hunk 3]
```diff
@@ -1821,6 +1826,36 @@ void NodeManager::HandleReturnWorker(const rpc::ReturnWorkerRequest &request,
   send_reply_callback(status, nullptr, nullptr);
 }
 
+void NodeManager::HandleCancelWorkerLease(const rpc::CancelWorkerLeaseRequest &request,
+                                          rpc::CancelWorkerLeaseReply *reply,
+                                          rpc::SendReplyCallback send_reply_callback) {
+  const TaskID task_id = TaskID::FromBinary(request.task_id());
+  Task removed_task;
+  TaskState removed_task_state;
+  auto canceled = local_queues_.RemoveTask(task_id, &removed_task, &removed_task_state);
```
Comment (ericl) [inline src/ray/raylet/node_manager.cc:1835]: reply->set_success(canceled)

**Review by ericl — APPROVED** [review]
