### PR TITLE
[Core][ConcurrencyGroup] Fix blocking task in default group block tasks in other group.

### LINKED ISSUE #20475: [Bug][ConcurrencyGroup] Tasks in different concurrency groups noises others due to task order issue.
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

```java
  @DefConcurrencyGroup(name = "io", maxConcurrency = 1)
  private static class StaticConcurrentActor {

    public long f1() throws InterruptedException {
      TimeUnit.SECONDS.sleep(5000);
      return Thread.currentThread().getId();
    }

    @UseConcurrencyGroup(name = "io")
    public long f2() throws InterruptedException {
      return Thread.currentThread().getId();
    }
  }
```

```java
  public void testF() {
    ActorHandle<StaticConcurrentActor> myActor = Ray.actor(StaticConcurrentActor::new).remote();
    ObjectRef<Long> obj1 = myActor.task(StaticConcurrentActor::f1).remote();
    ObjectRef<Long> obj2 = myActor.task(StaticConcurrentActor::f2).remote();
    System.out.println("1=========" + System.currentTimeMillis());
    Ray.get(obj2);
    System.out.println("2=========" + System.currentTimeMillis());
    Ray.get(obj1);
    System.out.println("3=========" + System.currentTimeMillis());
  }
```
`Ray.get(obj2)` will be blocked forever since the eventloop is in `request.Accept()` and invoking the task `f1`.

### Versions / Dependencies

master/1.8

### Reproduction script

NA

### Anything else
The issue is due to tasks executing in the default concurrent group run in the main task execution thread, and tasks in other concurrent groups will be blocked if the main task execution thread is blocked.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jovany-wang**
## Why are these changes needed?
If max concurrency is 1 in default group, a blocking task executing in default group will block the following tasks in different group. See  reproduction script in #20475

The issue is due to tasks executing in the default concurrent group run in the main task execution thread, and tasks in other concurrent groups will be blocked if the main task execution thread is blocked.

This PR only changes concurrent actor behavior that default group will not block other groups.

## Related issue number
Fix https://github.com/ray-project/ray/issues/20475

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/transport/thread_pool_manager.cc [hunk 1]
```diff
@@ -58,7 +58,8 @@ PoolManager::PoolManager(const std::vector<ConcurrencyGroup> &concurrency_groups
   }
   // If max concurrency of default group is 1, the tasks of default group
   // will be performed in main thread instead of any executor pool.
```
Comment (kfstorm) [inline src/ray/core_worker/transport/thread_pool_manager.cc:60]: Will you update the comment above?

**Review by kfstorm — COMMENTED** [review]
The bug is due to tasks executing in the default concurrent group run in the main task execution thread, and tasks in other concurrent groups will be blocked if the main task execution thread is blocked, right? Could you state this clearly in the PR description?

**Review by kfstorm — APPROVED** [review]
LGTM.

**Comment by jovany-wang** [comment]
`:serverless: Dashboard + Serve Tests` still fails on master.
windows failure is not related to this PR either.
