### PR TITLE
[Core] GCS Actor Management Race Condition

### LINKED ISSUE #9287: [GCS Actor Management] Race condition between `CreatingOnWorker` and `CancelOnWorker`
### What is the problem?

There's one parts of code that are vulnerable to race condition. After we succeed to lease a worker, we stores the actor data and call `CreateOnWorker`

```
    RAY_CHECK_OK(gcs_actor_table_.Put(actor->GetActorID(), actor->GetActorTableData(),
                                      [this, actor, leased_worker](Status status) {
                                        RAY_CHECK_OK(status);
                                        CreateActorOnWorker(actor, leased_worker);
                                      }));
```

The problem is before `CreateActorOnWorker` is called, the owner of this actor can die, and then `DestroyActor` will be called. 

Fix will be included in this PR. https://github.com/ray-project/ray/pull/9215

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python3
    @ray.remote(num_cpus=1, num_gpus=1)
    class A:
        def __init__(self):
            self.actors = []
        
        def create_actors(self):
            self.actors = [B.remote() for _ in range(2)]
        
        def ping(self):
            return 3

    @ray.remote(num_gpus=1)
    class B:
        def ping(self):
            return True

    @ray.remote(num_gpus=1)
    def f():
        return True

    a = A.remote()
    # Create pending actors
    ray.get(a.create_actors.remote())
    
    # Owner is dead. pending actors should be killed
    # and raylet should return workers correctly.
    time.sleep(2)
    del a
    a = B.remote()
    assert ray.get(a.ping.remote())
    ray.kill(a)
    assert ray.get(f.remote())
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by rkooo567**
## GCS Actor Creation Process
It is for helping understanding the PR.

1. Worker sends a creation request to GCS.
2. GCS registers an actor.
3. GCS schedule an actor.
4. Mark actor as "pending" if it is infeasible to create.
5. First, put the actor within "leasing_map" until we found a place to lease
6. Once we found a place to lease, put actor in "creating_map".
7. After actor is created, put it onto "created_map".

There are two problems in this process.

### Root cause
- GCS sends a leasing request for actor A to node A. (step 5)
- node A cannot schedule actor A to any worker because there's no available resources in the cluster. (but it is not infeasible).
- node A didn't reply to GCS until it finds a node to spillback, or A is scheduled.
- Actor A owner dies
- GCS now destroy actor A.
- In the function `DestroyActor(actor_A)`, it only handles step 4, 6, and 7.
- Broken!

### Solution
`DestroyActor` will heck if the actor is in the leasing map if the check for 4, 6, and 7 fails.

## `CreateOnWorker` race condition.
It also covers this issue https://github.com/ray-project/ray/issues/9287. It is handled simply by connecting to worker client before we call gcs_client->Put() because `CancelOnNode`, which checks the connected worker client can be called before `CreateOnWorker` is called.

## Related issue number

Fix `test_drivers_release_resources`
Fix https://github.com/ray-project/ray/issues/9287

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -623,7 +638,13 @@ void GcsActorManager::OnNodeDead(const ClientID &node_id) {
 
 void GcsActorManager::ReconstructActor(const ActorID &actor_id, bool need_reschedule) {
   auto &actor = registered_actors_[actor_id];
-  RAY_CHECK(actor != nullptr);
+  if (actor == nullptr) {
+    // NOTE(sang): It happens under this condition:
```
Comment (stephanie-wang) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:642]: It'd be nice to just write it out. Maybe something like, the actor was destroyed and deregistered before the node granted the actor creation request.

**Review by stephanie-wang — COMMENTED** [review]
Nice find! It would be good to have unit tests, though. I think it should be possible since all of the logic to test is in the GcsActorManager and the GcsActorScheduler can be mocked out. I'm not sure, though. Let me know if you need help with this!

**Review by rkooo567 — COMMENTED** [review]
I'd love to write tests together. But the problem I found is that this race condition depends on non-exposed internal states of `GcsActorScheduler`.

To correctly simulate the scenario, we should expose implementation details of `Scheduler->Schedule` function, which I believe is  a bad way of writing unit tests. One alternative solution we can do is refactoring some code to make it more testable. (If we can make it much more testable by exposing the scheduling state to `ActorManager`).

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc]: I don't have a strong preference!

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 2]
```diff
@@ -577,12 +587,17 @@ void GcsActorManager::OnWorkerDead(const ray::ClientID &node_id,
     actor_id = gcs_actor_scheduler_->CancelOnWorker(node_id, worker_id);
   }
 
-  if (!actor_id.IsNil()) {
-    RAY_LOG(INFO) << "Worker " << worker_id << " on node " << node_id
-                  << " failed, restarting actor " << actor_id;
-    // Reconstruct the actor.
-    ReconstructActor(actor_id, /*need_reschedule=*/!intentional_exit);
+  // If actor is not created & not in the creation process, don't do anything.
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:589]: I don't have a strong preference!

**Comment by stephanie-wang** [comment]
Hmm I'm not sure if I'm understanding this correctly, but how about this?
1. For the first case, we just check that `DestroyActor` calls a mocked `scheduler->CancelLeasingRequest` in the case that you described.
2. For the second case, I think we just need to simulate the owner dying, and then the worker dying, right?

**Comment by rkooo567** [comment]
Ah, I thought the problem was that the test depends on the internal states of `scheduler`, which is not exposed (`leasing_map` and `creating_map`). But after reading your comment, I actually realized it is possible to simulate it by mocking `CancelOnWorker` method. I will add a test rn!!

**Comment by rkooo567** [comment]
Bug will be tracked here https://github.com/ray-project/ray/issues/9266

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 3]
```diff
@@ -520,13 +520,21 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id) {
...
+      // The actor was pending scheduling. Remove it from the queue.
+      if (pending_it != pending_actors_.end()) {
+        pending_actors_.erase(pending_it);
+      } else {
+        // When actor creation request of this actor id is pending in raylet, we should
+        // cancel lease. NOTE(sang): It is possible the raylet replies to the lease
+        // request after this function is called. It will be fine because at the end of
+        // this function, we will publish the dead actor state, and it will make the
+        // raylet return the worker that was leased.
+        gcs_actor_scheduler_->CancelLeasingRequest(node_id, actor_id);
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: If the result of the request worker lease is returned after this line is executed, we should send a message to the raylet to cancel the lease worker?

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: At the end of this method, we'll publish the raylet that this actor is dead. Raylet handles this scenario at `HandleActorStateTransition`. 

One concerning I found after your comment is `HandleActorStateTransition`'s DEAD actor code and `HandleWorkerLeaseRequest`'s code is a little bit different. 

@stephanie-wang, are they working in the same way?

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: I went deep down to the code, and it seems like `HandleActorStateTransition ` is for actor and `CancelLeaseWorker` is for tasks. Dead actor workers lease should be returned by `HandleActorStateTransition`. That means this should handle the case. I'll wait until @stephanie-wang confirms it.

Comment (stephanie-wang) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: Hmm I'm not sure if the node manager actually does that when receiving the notification. How about we do something similar to normal tasks where we just return the lease immediately if the actor has already been destroyed? It'd be good to centralize as much of the logic in the GCS as possible.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: Got it. I will then make it call the cancelWorkerLease request here!

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: Actually, let me do some experiment before we do this. I will get back to you.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: Just confirm, it correctly returns the lease request without explicitly calling `CancelLeaseRequest`. I think they are cleaned by published actor dead state messages. 

I will probably just add a TODO message here just in case. I will also add one more integration test to verify this scenario.

**Comment by rkooo567** [comment]
@stephanie-wang @ffbin I couldn't reproduce the second scenario after I merged the latest master. I will just revert this change.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 4]
```diff
@@ -520,13 +520,22 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id) {
...
+      // The actor was pending scheduling. Remove it from the queue.
+      if (pending_it != pending_actors_.end()) {
+        pending_actors_.erase(pending_it);
+      } else {
+        // When actor creation request of this actor id is pending in raylet,
+        // it doesn't responds, and the actor should be still in leasing state.
+        // TODO(sang): Theoretically, worker leaks should not happen because
+        // gcs will publish the actor dead state to raylet after, and it will
+        // clean up leased workers.
+        // Call raylet->CancelWorkerLease explicitly if worker leaks are detected.
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: I didn't find the code to call raylet->CancelWorkerLease explicitly if worker leaks are detected.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 5]
```diff
@@ -577,12 +587,17 @@ void GcsActorManager::OnWorkerDead(const ray::ClientID &node_id,
     actor_id = gcs_actor_scheduler_->CancelOnWorker(node_id, worker_id);
   }
 
-  if (!actor_id.IsNil()) {
-    RAY_LOG(WARNING) << "Worker " << worker_id << " on node " << node_id
-                     << " failed, restarting actor " << actor_id;
-    // Reconstruct the actor.
-    ReconstructActor(actor_id, /*need_reschedule=*/!intentional_exit);
+  // If actor is not created & not in the creation process, don't do anything.
+  if (actor_id.IsNil()) {
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:591]: move it to line 588?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 6]
```diff
@@ -577,12 +587,17 @@ void GcsActorManager::OnWorkerDead(const ray::ClientID &node_id,
...
+    return;
   }
+
+  // Otherwise, try to reconstruct the actor that was already created or in the creation
+  // process.
+  RAY_LOG(INFO) << "Worker " << worker_id << " on node " << node_id
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:597]: RAY_LOG(WARNING) is better.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 4 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:536]: Sorry for vague wording. I will change the comment. What I meant was that from my experiment (and there's a test), I confirmed worker leaks don't happen although we don't call `raylet->CancelWorkerLease` because published DEAD message will handle this. I just wanted to add a todo message as a warning.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 5 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:591]: This is equivalent to the previous logic. Do you mean to change it like before?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 6 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:597]: My bad. I changed by mistake. Will fix.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 7]
```diff
@@ -169,11 +176,12 @@ void GcsActorScheduler::LeaseWorkerFromNode(std::shared_ptr<GcsActor> actor,
         // gcs_actor_manager will reconstruct it again.
         auto iter = node_to_actors_when_leasing_.find(node_id);
         if (iter != node_to_actors_when_leasing_.end()) {
-          // If the node is still available, the actor must be still in the leasing map as
-          // it is erased from leasing map only when `CancelOnNode` or the
-          // `RequestWorkerLeaseReply` is received from the node, so try lease again.
           auto actor_iter = iter->second.find(actor->GetActorID());
-          RAY_CHECK(actor_iter != iter->second.end());
+          if (actor_iter == iter->second.end()) {
+            // if actor is not in leasing state, it means it is cancelled.
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:181]: add a log?

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 8]
```diff
@@ -123,6 +123,13 @@ std::vector<ActorID> GcsActorScheduler::CancelOnNode(const ClientID &node_id) {
   return actor_ids;
 }
 
+void GcsActorScheduler::CancelLeasingRequest(const ClientID &node_id,
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:126]: The function name CancelLeasingRequest is confusing because it doesn't actually cancel the request, it just ignores the result that the request returned.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 9]
```diff
@@ -123,6 +123,13 @@ std::vector<ActorID> GcsActorScheduler::CancelOnNode(const ClientID &node_id) {
...
+                                             const ActorID &actor_id) {
+  auto node_it = node_to_actors_when_leasing_.find(node_id);
+  RAY_CHECK(node_it != node_to_actors_when_leasing_.end());
+  node_it->second.erase(actor_id);
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:130]: How about add some comments to explain that it is actually effective for RequestWorkerLease callback function?

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 10]
```diff
@@ -252,6 +260,8 @@ void GcsActorScheduler::HandleWorkerLeasedReply(
                   .emplace(leased_worker->GetWorkerID(), leased_worker)
                   .second);
     actor->UpdateAddress(leased_worker->GetAddress());
+    // Make sure to connect to the client before calling GCS.
+    GetOrConnectCoreWorkerClient(leased_worker->GetAddress());
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:264]: I'm confused why we call GetOrConnectCoreWorkerClient here, because we will call  GetOrConnectCoreWorkerClient in CreateActorOnWorker function.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:264]: This addresses the second race condition in the description. The problem here is that we call `CreateActorOnWorker ` is called as a callback of `Put`. This means that `DestroyActor` which calls `CancelOnWorker` can be called before `CreateActorOnWorker` is called (in my integration scenario). Since `CancelOnWorker` checks if the client is already connected or not (to GC), it is broken there. => https://github.com/ray-project/ray/blob/726c4cd6d44ca10850fc4490b8fd04d0e009390a/src/ray/gcs/gcs_server/gcs_actor_scheduler.cc#L137

There is a couple solution. 

1. We make the connection before calling `Put` => this solution.
2. Just relieve the invariant check within `OnCancelNode`, meaning instead of checking if connection is already made, we just add an if statement and erase.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 9 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:130]: Sounds good!

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 5 above)
Comment (ffbin) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:591]: I'm not sure if the actor_id returned on line 581 will be nil.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 3 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:537]: Added TODO instead. I understand explicitly cancelling lease to raylet is a better implementation, so please let me know if you think that's the blocker for this PR.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 5 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc]: Will move it inside the else statement!

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 8 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc]: Will changing to `CancelOnLeasing` following other conventions.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 7 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:183]: Added

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 10 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:272]: Added a better comment.

File: python/ray/tests/test_actor_advanced.py [hunk 11]
```diff
@@ -908,6 +908,45 @@ def set_count(self, count):
...
+    # Create pending actors
+    ray.get(a.create_actors.remote())
+
+    # Owner is dead. pending actors should be killed
+    # and raylet should return workers correctly.
+    del a
+    a = B.remote()
+    assert ray.get(a.ping.remote())
+    ray.kill(a)
+    assert ray.get(f.remote())
```
Comment (stephanie-wang) [inline python/ray/tests/test_actor_advanced.py:947]: Nice test!

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 12]
```diff
@@ -123,6 +123,15 @@ std::vector<ActorID> GcsActorScheduler::CancelOnNode(const ClientID &node_id) {
   return actor_ids;
 }
 
+void GcsActorScheduler::CancelOnLeasing(const ClientID &node_id,
+                                        const ActorID &actor_id) {
+  /// Note(sang): It is currently effective only inside RequestWorkerLease callback.
```
Comment (stephanie-wang) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:128]: What does this comment mean?

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 13]
```diff
@@ -123,6 +123,15 @@ std::vector<ActorID> GcsActorScheduler::CancelOnNode(const ClientID &node_id) {
...
+  /// TODO(sang): Cancel lease request explictly from this API.
```
Comment (stephanie-wang) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:129]: What does this comment mean? What API do you mean?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 3 above)
Comment (stephanie-wang) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:537]: Hmm I think it does cancel the lease request if the owner dies, so I think you're right that we can remove the RPC to the raylet (and the TODOs).

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 12 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:128]: Sorry I realized the comment is really bad. The comment is added based on this feedback https://github.com/ray-project/ray/pull/9215/files#r449460230. 

I will modify to
```
// NOTE(sang): This method does not currently cancel the outstanding lease request.  
It only removes leasing information from the internal state so that RequestWorkerLease ignores the response from raylet. 
```

This comment is added to avoid the situation that people use this method thinking it will cancel the lease request which is actually not true for now

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 13 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:129]: This means to call `raylet_client->CancelLeaseRequest`. I will also modify this comment.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 3 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:537]: Got it. I will remove the todo here! One concern I have is that people might misunderstand this method will actually cancel lease request. I will explicitly mention this in the method declaration instead!

**Review by stephanie-wang — APPROVED** [review]
Nice unit tests!

I think you're right about not needing the extra RPC to the raylet, so let's just remove the TODOs and merge this one as is. Can you just replace the TODOs with a note that the raylet will cancel the lease request when it receives the notification that the owner has died?

There could still be a leak with the current code if the owner is still alive but the actor handle goes out of scope while it's still in the leasing stage. But I think this should get fixed with my suggested change to only poll the owner *after* the actor has been created (see comments on #9302).

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 3 above)
Comment (stephanie-wang) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc]: Yeah maybe also a different name for the method.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc]: Decided to use `CancelOnLeasing`, which is consistent to other methods (`CancelOnWorker` or `CacnelOnNode`).

**Comment by rkooo567** [comment]
Confirm that this will also fix the last issue. [P0] test_calling_put_on_actor_handle crashes GCS on Mac (@rkooo567, fixed by #9215)

Every known issues are in review now.

**Comment by rkooo567** [comment]
Jenkins, retest this please.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 10 above)
Comment (wumuzi520) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:273]: > This addresses the second race condition in the description. The problem here is that `CreateActorOnWorker ` is called as a callback of `Put`. This means that `DestroyActor` which calls `CancelOnWorker` can be called before `CreateActorOnWorker` is actually called (in my integration scenario). Since `CancelOnWorker` checks if the client is already connected or not (to GC), it is broken there. =>
> 
> https://github.com/ray-project/ray/blob/726c4cd6d44ca10850fc4490b8fd04d0e009390a/src/ray/gcs/gcs_server/gcs_actor_scheduler.cc#L137
> 
> ```
> worker in creating map
> Put
> DestroyActor # will be broken here because of RAY_CHECK
> CreateActorOnWorker
> ```
> 
> There is a couple solution.
> 
> 1. We make the connection before calling `Put` => this solution.
> 2. Just relieve the invariant check within `OnCancelNode`, meaning instead of checking if connection is already made, we just add an if statement and erase.

As you said, the `CreateActorOnWorker` may be invoked after `DestroyActor` as the `CreateActorOnWorker` inside the callback of `Put`.
It means that the `CreateActorOnWorker` will be invoked anyway.
I think it still has problem.

Comment (wumuzi520) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:273]: I think you could check the actor status inside `CreateActorOnWorker`, if it already died then just return.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:273]: This part is added to avoid breaking `DestroyActor`, which calles `CancelOnNode` which checks if the client is already created to GC it. The scenario you mentioned is already covered inside `CreateActorOnWorker`.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:273]: https://github.com/ray-project/ray/blob/f395e480316e31d47883c746f06a1b45e1bc7711/src/ray/gcs/gcs_server/gcs_actor_scheduler.cc#L287
