### PR TITLE
Fix async actor high cpu utilization when idle

### LINKED ISSUE #6871: Async actor uses 100% cpu
Script:
```
import ray
import asyncio

ray.init()

@ray.remote
class AsyncActor:
    async def run(self):
        print("started")
        await asyncio.sleep(1000)
        print("done")

a = AsyncActor.options(is_direct_call=True,is_asyncio=True).remote()
ray.get([a.run.remote() for _ in range(10)])
```

Observe:
the worker process use 100% cpu.

### PR DESCRIPTION
**Pull request by simon-mo**
Fix #6871

### CODE REVIEW

**Review by ericl — APPROVED** [review]

**Comment by simon-mo** [comment]
Turns out `suspend` sleeps a little too much and cause deadlock. I moved work sharing to explicit synchronized channel

File: src/ray/core_worker/fiber.h [hunk 1]
```diff
@@ -0,0 +1,121 @@
...
+};
+
+/// Used by async actor mode. The FiberRateLimiter is a barrier that
+/// allows at most num fibers running at once. It implements the
+/// semaphore data structure.
+class FiberRateLimiter {
+ public:
+  FiberRateLimiter(int num) : num_(num) {}
+
+  // Enter the semaphore. Wait fo the value to be > 0 and decrement the value.
```
Comment (edoakes) [inline src/ray/core_worker/fiber.h]:
```suggestion
  // Enter the semaphore. Wait for the value to be > 0 and decrement the value.
```

File: src/ray/core_worker/fiber.h [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+    num_ -= 1;
+  }
+
+  // Exit the semaphore. Increment the value and notify other waiter.
+  void Release() {
+    {
+      std::unique_lock<boost::fibers::mutex> lock(mutex_);
+      num_ += 1;
+    }
+    // TODO(simon): This not does guarantee to wake up the first queued fiber.
```
Comment (edoakes) [inline src/ray/core_worker/fiber.h]: Does regular python `asyncio` give this guarantee? If so, this is definitely a gotcha that should be surfaced in the documentation.

Also could be fixed by using some form of queue instead of the `cond_`, right?

File: src/ray/core_worker/fiber.h [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+ public:
+  FiberState(int max_concurrency) : rate_limiter_(max_concurrency) {
+    fiber_runner_thread_ = std::thread([&]() {
+      while (!channel_.is_closed()) {
+        std::function<void()> func;
+        auto op_status = channel_.pop(func);
+        if (op_status == boost::fibers::channel_op_status::success) {
+          boost::fibers::fiber(boost::fibers::launch::dispatch, func).detach();
+        } else {  // Errored
+          RAY_LOG(ERROR) << "Fiber worker popped errrored. Exiting";
```
Comment (edoakes) [inline src/ray/core_worker/fiber.h]: typos and this is a really bad error message to surface to users. maybe add some more context?

File: src/ray/core_worker/fiber.h [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+  ~FiberState() {
+    channel_.close();
+    shutdown_worker_event_.Notify();
+    if (fiber_runner_thread_.joinable()) {
+      fiber_runner_thread_.join();
+    }
+  }
+
+ private:
+  FiberChannel channel_;
```
Comment (edoakes) [inline src/ray/core_worker/fiber.h]: comment

**Review by edoakes — COMMENTED** [review]
Much nicer having the standalone `FiberState`!

File: src/ray/core_worker/fiber.h (hunk 2 above)
Comment (simon-mo) [reply src/ray/core_worker/fiber.h]: No regular python doesn't give ordering guarantee because they rely on the OS for scheduling some of the operations. This TODO should really just be a NOTE.

**Review by edoakes — APPROVED** [review]
LGTM, thanks. Do we have a test for the rate limiting btw? If not would be good to add one.

**Comment by simon-mo** [comment]
yes there is an existing test for rate limiting https://github.com/ray-project/ray/blob/4dd41844d0eb4ed8a49df78479484f0ed2e79b42/python/ray/tests/py3_test.py#L140
