### PR TITLE
Fix stress_test_state_api_scale

### LINKED ISSUE #36445: Release test stress_test_state_api_scale.aws failed
Release test stress_test_state_api_scale.aws failed.
See https://buildkite.com/ray-project/release-tests-branch/builds/1800#0188bdc1-69cc-461d-ba46-726ecfcd9d6f for more details.
cc @core

	 -- created by ray-test-bot

### PR DESCRIPTION
**Pull request by can-anyscale**
Fix stress_test_state_api_scale. The test is currently failing on BYOD because it needs some env vars that be set before `ray start`, and runtime_env happens after `ray start`. Need to build the env vars into a part of the docker image for this to work.

Fix #36445

Test
- [Release test](https://buildkite.com/ray-project/release-tests-pr/builds/43740)

### CODE REVIEW

**Comment by can-anyscale** [comment]
Test is green: https://buildkite.com/ray-project/release-tests-pr/builds/43740

File: release/ray_release/byod/byod_increase_ray_max_limit_test.sh [hunk 1]
```diff
@@ -0,0 +1,8 @@
+#!/bin/bash
```
Comment (rickyyx) [inline release/ray_release/byod/byod_increase_ray_max_limit_test.sh:1]: is this the recommended strategy for modifying the server env now?

**Review by rickyyx — APPROVED** [review]

File: release/ray_release/byod/byod_increase_ray_max_limit_test.sh (hunk 1 above)
Comment (can-anyscale) [reply release/ray_release/byod/byod_increase_ray_max_limit_test.sh:1]: if it is before ray.init yes; otherwise using runtime_env is cheaper

File: release/ray_release/byod/byod_increase_ray_max_limit_test.sh [hunk 2]
```diff
@@ -0,0 +1,8 @@
...
+# This script is used to build an extra layer on top of the base anyscale/ray image 
+# to run the horovod tests
+
+set -exo pipefail
+
+echo "export RAY_MAX_LIMIT_FROM_API_SERVER=1000000000" >> /home/ray/.bashrc
+echo "export RAY_MAX_LIMIT_FROM_DATA_SOURCE=1000000000" >> /home/ray/.bashrc
```
Comment (aslonnie) [inline release/ray_release/byod/byod_increase_ray_max_limit_test.sh:8]: why adding it into `.bashrc` fixes it? yeah, I have the same feeling that this is not the right way.

Comment (can-anyscale) [reply release/ray_release/byod/byod_increase_ray_max_limit_test.sh:8]: byod runtime_env is set during ray.init; but these two variables need to be set before ray.start (which is also before ray.init)

**Comment by can-anyscale** [comment]
Oh, I think I also need approval from @aslonnie as code owner

File: release/release_tests.yaml [hunk 3]
```diff
@@ -5018,9 +5018,7 @@
   team: core
   cluster:
     byod:
-      runtime_env:
-        - RAY_MAX_LIMIT_FROM_API_SERVER=1000000000
-        - RAY_MAX_LIMIT_FROM_DATA_SOURCE=1000000000
+      post_build_script: byod_increase_ray_max_limit_test.sh
```
Comment (aslonnie) [inline release/release_tests.yaml:5021]: if it is adding two env variables, why not add a env list here under byod, and add `ENV RAY_MAX_LIMIT_FROM_API_SERVER=1000000000` into the Dockerfile that you generated? that way, you do not need to alter the `.bashrc` file, and it will be much more stable.

we cannot really build on the assumption that `.bashrc` will be always executed for a ray job.

File: release/ray_release/byod/byod_increase_ray_max_limit_test.sh (hunk 2 above)
Comment (aslonnie) [reply release/ray_release/byod/byod_increase_ray_max_limit_test.sh:8]: same as the other comment: why not add a env list here under byod, and add ENV RAY_MAX_LIMIT_FROM_API_SERVER=1000000000 into the Dockerfile

File: release/release_tests.yaml (hunk 3 above)
Comment (can-anyscale) [reply release/release_tests.yaml:5021]: Unless we dynamically generate Dockerfile at runtime which is way too complicated. 

We own the infrastructure of bootstrapping ray from anyscale so we should be able to make some assumptions about what file to load at runtime no?

Comment (can-anyscale) [reply release/release_tests.yaml:5021]: I wonder how anyscale builds image with a dynamic list of env today, like this one: https://console.anyscale-staging.com/o/anyscale-internal/configurations/app-config-details/bld_c41b4hfb5h1rqjtbtkxtamkqjp

Comment (aslonnie) [reply release/release_tests.yaml:5021]: > how anyscale builds image with a dynamic list of env

the Dockerfile it uses is dynamically generated. you can do the same thing. like when env is not empty, insert several lines of `ENV KEY=value` into the Dockerfile.

Comment (aslonnie) [reply release/release_tests.yaml:5021]: > dynamically generate Dockerfile at runtime which is way too complicated.

why is that complicated?

Comment (aslonnie) [reply release/release_tests.yaml:5021]: > own the infrastructure of bootstrapping ray from anyscale so we should be able to make some assumptions about what file to load at runtime no?

we have the ownership of the infra, but that does not mean that it is justified to use `bashrc` as an init interface. we still need to design and maintain the interface to be clean and tidy.

Comment (can-anyscale) [reply release/release_tests.yaml:5021]: I see. Sound good. It feel like though that anyscale should publish its api for building its docker image with an arbitrary base image. Seem like I reinvent the wheel for its cluster_env build process.

Comment (aslonnie) [reply release/release_tests.yaml:5021]: > > dynamically generate Dockerfile at runtime which is way too complicated.
> 
> why is that complicated?

like you are already dynamic sending in this `post_build_script` thing.

what you need to do is create a temp tarball with the dynamically generated Dockerfile (and the post build script) in it, and send the tarball in either via stdin.

Comment (aslonnie) [reply release/release_tests.yaml:5021]: cc @yifeif too.

Comment (can-anyscale) [reply release/release_tests.yaml:5021]: Also the runtime_env here is probably incorrect or confusing. It doesn't not run as part of the docker entrypoint env, it runs as part of ray.init https://docs.anyscale.com/reference/python-sdk/models#createproductionjobconfig


Should it be invoked through docker run -env instead?

Comment (ckw017) [reply release/release_tests.yaml:5021]: Since this discussion is more about product than open source use cases, opening thread in product instead.

**Review by aslonnie — APPROVED** [review]
