### PR TITLE
[core] Fix a memory leak due to lineage counting

### LINKED ISSUE #31421: [core] Object store memory leak in simple while loop
### What happened + What you expected to happen

Running the following script leads to an infinite object store memory leak and disk spilling. Interestingly, `ray memory` doesn't show any leak of references at the ref counting layer.

From discuss: https://discuss.ray.io/t/object-store-spilling-terabytes-of-data/8699/5

### Versions / Dependencies

master

### Reproduction script

```
import ray

ray.init()

@ray.remote
def process(data):
    return b"\0" * 100_000_000

while True:
    data = ray.put(b"\0" * 100_000_000)
    ref = process.remote(data)
    ray.get(ref)
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by fishbone**
Signed-off-by: Yi Cheng <74173148+iycheng@users.noreply.github.com>

## Why are these changes needed?
Assume two objects A and B and B depends on A. If A got delete first, it's won't be released because we need to preserve it for B.

The bug here is that even B is released, A won't be released and thus memory leak.

This PR fixed this issue by force delete the object when the ref goes to 0.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/reference_count.cc [hunk 1]
```diff
@@ -483,6 +483,7 @@ int64_t ReferenceCounter::ReleaseLineageReferences(ReferenceTable::iterator ref)
       RAY_CHECK(arg_it->second.on_ref_removed == nullptr);
       lineage_bytes_evicted += ReleaseLineageReferences(arg_it);
       EraseReference(arg_it);
+      ReleasePlasmaObject(arg_it);
```
Comment (stephanie-wang) [inline src/ray/core_worker/reference_count.cc:486]: The fix looks good to me! I think we just need to move this to go before the above line, though, because the previous line deletes `arg_it`.

**Review by stephanie-wang — APPROVED** [review]

File: src/ray/core_worker/reference_count.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/reference_count.cc:486]: Actually I think you could also just call DeleteReferenceInternal instead of EraseReference and ReleasePlasmaObject.

File: src/ray/core_worker/reference_count.cc [hunk 2]
```diff
@@ -478,11 +478,9 @@ int64_t ReferenceCounter::ReleaseLineageReferences(ReferenceTable::iterator ref)
     RAY_LOG(DEBUG) << "Releasing lineage internal for argument " << argument_id;
     arg_it->second.lineage_ref_count--;
     if (arg_it->second.ShouldDelete(lineage_pinning_enabled_)) {
-      // We only decremented the lineage ref count, so the argument value
-      // should already be released.
       RAY_CHECK(arg_it->second.on_ref_removed == nullptr);
       lineage_bytes_evicted += ReleaseLineageReferences(arg_it);
-      EraseReference(arg_it);
+      DeleteReferenceInternal(arg_it, nullptr);
```
Comment (rkooo567) [inline src/ray/core_worker/reference_count.cc:483]: Should we rewrite the docstring for these 2 APIs? (EraseReference, DeleteReferenceInternal). 

From reading the docstring, it is not clear why EraseReference doesn't work but DeleteReferenceInternal does from this code

Comment (iycheng) [reply src/ray/core_worker/reference_count.cc]: I realize that DeleteReferenceInternal also doesn't work. It need to be 

```
ReleasePlasmaObject
EraseReference
```

I'm  not very familiar with this part so I'm going to leave it here.
