### PR TITLE
[core] Critical Bug-fix: Fix ray memory metric calculation in CGroup V1 environment

### LINKED ISSUE #35989: [Ray Core] Memory resource monitor on cluster takes into account cache memory
### What happened + What you expected to happen

I started seeing an issue on our Ray cluster where I'd see nodes with no activity still displaying high memory usage. When I looked into the k8s pod, I didn't see any tasks running or internal ray processes using significant memory. As I dug more, I found that most of the memory was being assigned from disk cache due to our jobs doing significant disk I/O. 

I've attached screenshots of what I saw. 

Screen Shot 2023-06-01 at 10 55 33 AM
Screen Shot 2023-06-01 at 10 56 04 AM

I was also able to check this through the ray apis.

```
>>> def _get_mem_usage():
...     import ray
...     total = ray._private.utils.get_system_memory()
...     used = ray._private.utils.get_used_memory()
...     available = total - used
...     percent = round(used / total, 3) * 100
...     return total, available, percent, used
...
>>> _get_mem_usage()
(137438953472, 63870889984, 53.5, 73568063488)
```

Node memory stats did show a high amount of cache memory but since I'm running in k8s, it's harder to prove that it belongs to the ray pod. I was able to prove that the node memory cleared up once I cleared the cache memory. 
```
cat /sys/fs/cgroup/memory/memory.stat
cache 75654529024
rss 770076672
rss_huge 0
shmem 118947840
mapped_file 132734976
dirty 0
writeback 7569408
pgpgin 50643603417
pgpgout 50624962189
pgfault 50566393449
pgmajfault 6501
inactive_anon 51986432
active_anon 840511488
inactive_file 2895663104
active_file 72646320128
unevictable 0
hierarchical_memory_limit 137438953472
total_cache 75654529024
total_rss 770076672
total_rss_huge 0
total_shmem 118947840
total_mapped_file 132734976
total_dirty 0
total_writeback 7569408
total_pgpgin 50643603417
total_pgpgout 50624962189
total_pgfault 50566393449
total_pgmajfault 6501
total_inactive_anon 51986432
total_active_anon 840511488
total_inactive_file 2895663104
total_active_file 72646320128
total_unevictable 0
```
What this ended up resulting in was ray killing our tasks because the cache memory was being accounted for as process memory. 

```
Error Type: OUT_OF_MEMORY

Task was killed due to the node running low on memory.
Memory on the node (IP: 172.26.48.188, ID: 81a2fdccdb0b6661460f0979a8fa4768e37cb76f70f817fd554b2d87) where the task (task ID: f50a1e531867a01b91ce54eb6ef2d1646def8fcde7070000, name=abhinav-sharded-rms-gt-task, pid=4199, memory used=4.58GB) was running was 122.14GB / 128.00GB (0.954213), which exceeds the memory usage threshold of 0.95. Ray killed this worker (ID: 1670d4098031279e8e28aff41a566b141b705b733d1edc11994d9043) because it was the most recently scheduled task; to see more information about memory usage on this node, use `ray logs raylet.out -ip 172.26.48.188`. To see the logs of the worker, use `ray logs worker-1670d4098031279e8e28aff41a566b141b705b733d1edc11994d9043*out -ip 172.26.48.188. Top 10 memory users:
PID	MEM(GB)	COMMAND
118484	15.70	ray::abhinav-sharded-rms-gt-task
125845	15.67	ray::abhinav-sharded-rms-gt-task
118151	8.33	ray::abhinav-sharded-rms-gt-task
4199	4.58	ray::abhinav-sharded-rms-gt-task
113	0.49	/home/ray/anaconda3/lib/python3.10/site-packages/ray/core/src/ray/raylet/raylet --raylet_socket_name...
310	0.22	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.10/site-packages/ray/dashboard/age...
7	0.09	/home/ray/anaconda3/bin/python /home/ray/anaconda3/bin/ray start --address=ray-cluster-head-svc.ray-...
186	0.04	/home/ray/anaconda3/bin/python -u /home/ray/anaconda3/lib/python3.10/site-packages/ray/_private/log_...
118354	0.00	/tmp/ray/session_2023-05-25_18-12-40_361764_7/runtime_resources/pip/f0c7b6d444d14248d95c410d2da45452...
118743	0.00	/tmp/ray/session_2023-05-25_18-12-40_361764_7/runtime_resources/pip/f0c7b6d444d14248d95c410d2da45452...
Refer to the documentation on how to address the out of memory issue: https://docs.ray.io/en/latest/ray-core/scheduling/ray-oom-prevention.html. Consider provisioning more memory on this node or reducing task parallelism by requesting more CPUs per task. To adjust the kill threshold, set the environment variable `RAY_memory_usage_threshold` when starting Ray. To disable worker killing, set the environment variable `RAY_memory_monitor_refresh_ms` to zero.
```

### Versions / Dependencies

Ray 2.4.0

### Reproduction script

Not sure how exactly to prove this yet with a repro script.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by WeichenXu123**
## Why are these changes needed?

Fix ray memory metric calculation.

**Current Ray memory metric calculation in container environment it will heavily underestimate available memory, and it causes Ray MemoryMonitor misleadingly triggered to kill Ray tasks with OOM error.**

## Related issue number

Closes https://github.com/ray-project/ray/issues/35989

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/common/memory_monitor.cc [hunk 1]
```diff
@@ -123,29 +123,26 @@ int64_t MemoryMonitor::GetCGroupV1MemoryUsedBytes(const char *path) {
...
-  int64_t cache_bytes = kNull;
   int64_t inactive_file_bytes = kNull;
   while (std::getline(memstat_ifs, line)) {
     std::istringstream iss(line);
     iss >> title >> value;
     if (title == "total_rss") {
       rss_bytes = value;
-    } else if (title == "total_cache") {
-      cache_bytes = value;
     } else if (title == "total_inactive_file") {
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:132]: `total_cache` item in `/sys/fs/cgroup/memory/memory.stat` should means "Linux OS page cache / buffer", this part memory should be count as "available", because this part memory is borrowed by Linux OS to cache Page or buffers but if user process want to allocate more memory , Linux will evict them immediately and allocate to user process.

File: src/ray/common/memory_monitor.cc [hunk 2]
```diff
@@ -111,41 +111,71 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  // in-used memory ?
+  // In my test the calculated number is much less than `MemTotal - MemAvailable`.
+  //  so the formular must miss something (but I haven't figured out which part is missed)
+  // But in my test,
+  //  cgroup `memory.usage_in_bytes` value perfectly matches (`MemTotal` - `MemFree`) value,
+  //  so I am sure that `memory.usage_in_bytes` value is correct.
+  //  and cgroup `memory.stat.total_cache` value also perfectly matches
+  //  (`MemAvailable` - `MemFree`) value,
+  // so that I am confident that this formular must be correct:
+  //   available_mem = `memory.usage_in_bytes` - `memory.stat.total_cache`
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:144]: NOTE: 

Current master Ray code calculation problems:
1. It counts `memory.stat.total_cache` as "in-used" memory, which causes the issue that it heavily underestimate available memory,
and it leads to Ray memory monitor misleadingly triggered to kill Ray tasks while there are lots of available memory.

2. Inaccurate formula, see ”Explanation 2“ in above comment.

File: src/ray/common/memory_monitor.cc [hunk 3]
```diff
@@ -111,41 +111,78 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  // Explanation: What's this part `OS_managed_cache_and_buffer` memory for and why
+  //   we should treat this part memory as "Not-in-used" ?
+  // Linux OS tries to fully use the whole physical memory size, so that in many
+  // cases we can observe that the system has very little `MemFree` size,
+  // but at the same time system might have a large `MemAvailable` size,
+  // then this part `MemAvailable - MemFree` size is borrowed by Linux OS
+  // to cache pages / buffers , BUT, once user process requests to allocate memory,
+  // and there is no sufficient free memory, OS will evict cache data out of this
+  // part memory and allocate them to user proces.
+  //
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:133]: NOTE: 

Current master Ray code calculation counts "OS_managed_cache_and_buffer" as "in-used" memory, which causes the issue that it heavily underestimate available memory,
and it leads to Ray memory monitor misleadingly triggered to kill Ray tasks while there are lots of available memory.

This is a very big issue.

Because for some IO-heavy tasks, it can quickly fill up physical memory with "OS_managed_cache_and_buffer", then Ray monitor will misleadingly think OS has very few available memory and then kill Ray tasks.

File: src/ray/common/memory_monitor.cc [hunk 4]
```diff
@@ -111,41 +111,89 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  // Explanation: What's the part of `shmem` and why we should treat it as "in-used" ?
+  //   `shmem` overview: https://man7.org/linux/man-pages/man7/shm_overview.7.html
+  //   Ray object store use `/dev/shm`, which is a `tmpfs` file system,
+  //   In linux, `tmpfs` file system uses `shmem` memory.
+  //   Note that `tmpfs` file system might swap data to disk (when option noswap=False)
+  //   but `shmem` value always means the `tmpfs` data size in physical memory.
+  //   We can read `shmem` value from /proc/meminfo `Shmem` item or from
+  //   /sys/fs/cgroup/memory/memory.stat `total_shmem` item.
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:142]: NOTE: 

Current master Ray code calculation counts "OS_managed_cache_and_buffer" as "in-used" memory, which causes the issue that it heavily underestimate available memory,
and it leads to Ray memory monitor misleadingly triggered to kill Ray tasks while there are lots of available memory.

This is a very big issue.

Because for many IO-heavy tasks, it can quickly fill up physical memory with "OS_managed_cache_and_buffer", then Ray monitor will misleadingly think OS has very few available memory and then kill Ray tasks.

File: src/ray/common/memory_monitor.cc [hunk 5]
```diff
@@ -111,41 +111,107 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  //
+  // Explanation: What's this part `OS_managed_cache_and_buffer` memory for and why
+  //   we should treat this part memory as "Not-in-used" ?
+  //   Linux OS tries to fully use the whole physical memory size, so that in many
+  //   cases we can observe that the system has very little `MemFree` size,
+  //   but at the same time system might have a large `MemAvailable` size,
+  //   then this part `MemAvailable - MemFree` size is borrowed by Linux OS
+  //   to cache pages / buffers , BUT, once user process requests to allocate memory,
+  //   and there is no sufficient free memory, OS will evict cache data out of this
+  //   part memory and allocate them to user proces.
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:138]: NOTE:

Current master Ray code calculation counts "OS_managed_cache_and_buffer" as "in-used" memory, which causes the issue that it heavily underestimate available memory,
and it leads to Ray memory monitor misleadingly triggered to kill Ray tasks while there are lots of available memory.

This is a very big issue.

Because for many IO-heavy tasks, it can quickly fill up physical memory with "OS_managed_cache_and_buffer", then Ray monitor will misleadingly think OS has very few available memory and then kill Ray tasks.

File: src/ray/common/memory_monitor.cc [hunk 6]
```diff
@@ -111,41 +111,107 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  //    Use dd command to write a large file to disk, after dd  completes,
+  //    the calculated used_memory value should keep nearly the same with the value
+  //    before dd execution.
+  //    But note that free memory will decrease significantly because OS
+  //    cached the file data as part of "OS_managed_cache_and_buffer" I mentioned above.
+  //
+  //  - If we use dd command to write a large file to /dev/shm,
+  //    and no swapping occurs (you can use `free -h` to check whether swap size increases),
+  //    after dd completes, the calculated used-memory value should be nearly
+  //    previous_in_used_memory_bytes + bytes_of_written_file
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:177]: This part verification is very important.

The current `GetCGroupV1MemoryUsedBytes` just reads some items from CGroup mem stat file without fully understanding their meanings and without verification, and it turns out to be wrong number and causes this hidden bug.

File: src/ray/common/memory_monitor.cc [hunk 7]
```diff
@@ -111,41 +111,120 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  //
+  //  - [Host OS SIGKILL signal test]:
+  //    1. get current "used_memory" by running this `GetCGroupV1MemoryUsedBytes` function.
+  //    2. get "swap_space_size" by running `free` command
+  //    3. read "swapped_data_size" value by reading "total_swap" item from /sys/fs/cgroup/memory/memory.stat
+  //    4. Create a program that gradually requests to allocate memory,
+  //       record that after the number "oom_size" memory it get allocated,
+  //       the process is killed by OS SIGKILL signal.
+  //    The "oom_size" recorded in step-(4) should approximately satisfy the following formula:
+  //    oom_size ~== (total_memory + swap_space_size) - used_memory - swapped_data_size
```
Comment (WeichenXu123) [inline src/ray/common/memory_monitor.cc:190]: This part verification is very important.

Note that CGroup official doc is very fuzzy on concrete meanings of values in CGroup mem stat file,

We can do these verifications I listed here to ensure the calculation logic correctness.

Comment (WeichenXu123) [reply src/ray/common/memory_monitor.cc:190]: another related issue worth discussion:

Current Ray memory monitor logic is:

When `used_physical_memory / total_physical_memory > 0.95`, trigger killing Ray tasks.

But this does not fully match Host OS SIGKILL criteria ,
Actually Host OS SIGKILL is triggered by the following criteria:

`(used_physical_memory + used_swap_size) ~== (total_physical_memory + total_swap_size)`

So correspondingly,
Ray memory monitor killing Ray task threshold should be:

`(used_physical_memory + used_swap_size) / (total_physical_memory + total_swap_size) > 0.95`

(We can fix this in follow-up PR)

**Comment by rkooo567** [comment]
@WeichenXu123 thanks for the PR. It's been an issue for a while, and I really appreicate you try fixing the issue!

**Comment by rkooo567** [comment]
I believe it is the same issue as https://github.com/ray-project/ray/issues/35989, is this correct?

File: src/ray/common/memory_monitor.cc [hunk 8]
```diff
@@ -111,41 +111,71 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
+  // In my test the calculated number is much less than `MemTotal - MemAvailable`.
+  //  so the formular must miss something (but I haven't figured out which part is missed)
+  // But in my test,
+  //  cgroup `memory.usage_in_bytes` value perfectly matches (`MemTotal` - `MemFree`) value,
+  //  so I am sure that `memory.usage_in_bytes` value is correct.
+  //  and cgroup `memory.stat.total_cache` value also perfectly matches
+  //  (`MemAvailable` - `MemFree`) value,
+  // so that I am confident that this formular must be correct:
+  //   available_mem = `memory.usage_in_bytes` - `memory.stat.total_cache`
   std::ifstream memstat_ifs(path, std::ios::in | std::ios::binary);
```
[the remark this answers is not in the document]
Comment (WeichenXu123) [reply src/ray/common/memory_monitor.cc]: yes, I have updated it

**Comment by WeichenXu123** [comment]
> I believe it is the same issue as #35989, is this correct?

Correct!

**Comment by rkooo567** [comment]
Btw, there are some core test failures. Can you take a look?

File: src/ray/common/memory_monitor.cc [hunk 9]
```diff
@@ -111,41 +111,120 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
   return std::tuple(system_used_bytes, system_total_bytes);
 }
 
-int64_t MemoryMonitor::GetCGroupV1MemoryUsedBytes(const char *path) {
-  std::ifstream memstat_ifs(path, std::ios::in | std::ios::binary);
+int64_t MemoryMonitor::GetCGroupV1MemoryUsedBytes(const char *stat_path,
+                                                  const char *usage_path) {
+  // How does this function calculate in-used memory from cgroup memory info file?
```
Comment (rkooo567) [inline src/ray/common/memory_monitor.cc:116]: Q: is the implementation aligned with python ones?

**Review by rkooo567 — COMMENTED** [review]
Can you take a look at test failures? I may need a bit of time to review the PR. But we will make sure to finish it by this week.

File: src/ray/common/memory_monitor.cc (hunk 9 above)
Comment (WeichenXu123) [reply src/ray/common/memory_monitor.cc:116]: Sure.

**Comment by WeichenXu123** [comment]
I will fix test :)

File: src/ray/common/memory_monitor.cc [hunk 10]
```diff
@@ -111,41 +111,121 @@ std::tuple<int64_t, int64_t> MemoryMonitor::GetMemoryBytes() {
...
 
   std::string line;
   std::string title;
   int64_t value;
 
-  int64_t rss_bytes = kNull;
-  int64_t cache_bytes = kNull;
-  int64_t inactive_file_bytes = kNull;
+  int64_t cgroup_usage_in_bytes;
+  std::getline(memusage_ifs, line);
```
Comment (rkooo567) [inline src/ray/common/memory_monitor.cc:207]: can you comment the structure of this file here?

**Review by rkooo567 — APPROVED** [review]
I think the approach makes sense (and we should definitely not include cache and buffer. that's aligned with psutil implementation https://github.com/giampaolo/psutil/blob/2f1cd0cafa895786183cf43bb5f02fceeb68de55/psutil/_pslinux.py#L491). I have several questions. Also, the expert from our end will also review the PR. 

1. What's the reason why cgroup2 doesn't have the issue?
2. From the psutil implementation, it doesn't really subtract the shmem https://github.com/giampaolo/psutil/blob/2f1cd0cafa895786183cf43bb5f02fceeb68de55/psutil/_pslinux.py#L491. Do you think this is necessary change (there's possibility this can underestimate the memory usage)?

**Comment by WeichenXu123** [comment]
@rkooo567 

> What's the reason why cgroup2 doesn't have the issue?

cgroup2 should have similar issue, I haven't checked cgroup2 part code, it might need another PR to fix. Our databricks runtime uses cgroup1.

> From the psutil implementation, it doesn't really subtract the shmem

For the reason I substract "shmem", you can test 

```
  //  - [/dev/shm test]
  //    If we use dd command to write a large file to /dev/shm,
  //    and no swapping occurs (you can use `free -h` to check whether swap size increases),
  //    after dd completes, the calculated used-memory value should be nearly
  //    previous_in_used_memory_bytes + bytes_of_written_file
```

"shmem" means the in-memory size used by "/dev/shm", i.e., once **free memory** is insufficient, "OS_managed_cache_and_buffer" part will be throw away, but "shmem" part will be kept in memory or swapped it to swap space, this is the major difference. So "shmem" part should be counted as "in-used".

You can copy a large file into /dev/shm, and use `free -h` command to check before vs. after changes of the each part of memory.

You can also test:

```
  //  - [Host OS SIGKILL signal test]:
  //    1. get current "used_memory" by running this `GetCGroupV1MemoryUsedBytes` function.
  //    2. get "swap_space_size" by running `free` command
  //    3. read "swapped_data_size" value by reading "total_swap" item from /sys/fs/cgroup/memory/memory.stat
  //    4. Create a program that gradually requests to allocate memory,
  //       record that after the number "oom_size" memory it get allocated,
  //       the process is killed by OS SIGKILL signal.
  //    The "oom_size" recorded in step-(4) should approximately satisfy the following formula:
  //    oom_size ~== (total_memory + swap_space_size) - used_memory - swapped_data_size
```

Assuming you put large file in /dev/shm, then you will file the "oom_size" becomes much smaller, i.e. this part is occupied by file data in /dev/shm

also note that Ray uses /dev/shm as the object-store-memory, so this part is important to Ray workloads.

File: src/ray/common/memory_monitor.cc (hunk 5 above)
Comment (lanbochen-anyscale) [reply src/ray/common/memory_monitor.cc:138]: Question, do we want to reserve some memory for cache+buffer, maybe have a flag to define certain threshold? It may impact some performance if there is no memory cache.

**Comment by WeichenXu123** [comment]
Btw, the `psutil` library isn't python builtin library, I don't think its implementation is authoritative and trustable,

But the /proc/meminfo and `free` command output should be trustable, they are OS builtin metrics / tools.

File: src/ray/common/memory_monitor.cc (hunk 5 above)
Comment (WeichenXu123) [reply src/ray/common/memory_monitor.cc:139]: @lanbochen-anyscale

> do we want to reserve some memory for cache+buffer

OS managed "cache+buffer" cache isn't used in this way. Linux OS fully decides what to cache to "cache+buffer", you can't control it.

But you can set "RAY_memory_usage_threshold" to be 0.8 so that 20% memory are reserved for "cache+buffer".

For the function "get_cgroupv1_used_memory" I modified, it should return the correct result of "in-used" memory, if you return some value like "in-used-memory + reserved_size", it makes code logic in a mess. You can consider to add logic for "reserved_size", but not in this function. For the "reserved_size" logic you mentioned, tuning "RAY_memory_usage_threshold" should be a better idea.

Comment (WeichenXu123) [reply src/ray/common/memory_monitor.cc:139]: More explanation:

> Where is "get_cgroupv1_used_memory" function used ?

1. It is used by "Ray memory monitor" to detect out-of-memory case in advance. i.e if `used_memory / physical_memory >  RAY_memory_usage_threshold` occurs, killing Ray tasks to prevent real OOM. Then if you change "used_memory" to be some value like "real_used_memory + reserved_size", it will heavily confuses user "what does the 'used_memory'" mean" ?  It is an an ugly patch containing disordered logic.

2. It is used in "Ray dashboard" to display available memory. This also requires it to return a "correct" value but not a tweaked value with some fuzzy "reserved_size" , otherwise user would ask why the dashboard shows wrong available memory size ?

**Comment by WeichenXu123** [comment]
@rkooo567 Any more comments ? :) Can we merge it ?

**Comment by rkooo567** [comment]
yes. Can you make sure the premerge tests pass and ping me? I think we can merge it. We should follow up with cgroup2

**Comment by WeichenXu123** [comment]
> yes. Can you make sure the premerge tests pass and ping me? I think we can merge it. We should follow up with cgroup2

@rkooo567 Thanks! All tests passed.

**Comment by WeichenXu123** [comment]
Follow-ups:

(1) Update logic for "cgroup2"
(2) Update logic for non-container Linux OS.
(3) See https://github.com/ray-project/ray/pull/42508#discussion_r1460294042

@rkooo567 
For databricks usage, these follow-ups are not urgent, so I might not allocate time-slots for these follow-ups. Would you help assign them to other folks.

**Comment by rkooo567** [comment]
I think non-container case already subtracts cached/buffer because that's what psutil does. I will create a follow up issue

File: src/ray/common/memory_monitor.cc (hunk 7 above)
Comment (rkooo567) [reply src/ray/common/memory_monitor.cc]: we actually want to kill those processes before the Host OS kills them. It can give us better error message (e.g., host os kills procs using sigkill which we cannot detect).

Comment (WeichenXu123) [reply src/ray/common/memory_monitor.cc]: > we actually want to kill those processes before the Host OS kills them

Yes . To accurately implement the goal "kill those processes before the Host OS kills them" , the Memory monitor killing condition should be:

```
(used_physical_memory + used_swap_size) / (total_physical_memory + total_swap_size) > `RAY_memory_usage_threshold`
```

@rkooo567 Is my understanding correct ?

Comment (rkooo567) [reply src/ray/common/memory_monitor.cc]: Hmm I think it depends on the definition of "~=" in the OS OOM killer. I think if OS oom killer has similar threshold as 95% (including the swap size), the ray memory monitor is useless. Besides, I agree it makes more sense to include swap size in the calculation (though iiuc, most of EC2 disabled swap by default?)
