### PR TITLE
[Core] Cancel lease requests before returning a PG bundle

### LINKED ISSUE #45642: [Core] Raylet check failed: placement_group_resource_manager.cc:29: Check failed: ReturnBundle(*iter->second).ok()
### What happened + What you expected to happen

```
2024-05-29 22:54:10	(/tmp/ray/session_2024-05-24_19-21-02_933825_4791/logs/raylet.out) [2024-05-29 22:54:10,723 C 359273 359273] (raylet) placement_group_resource_manager.cc:29: Check failed: ReturnBundle(*iter->second).ok()
```

### Versions / Dependencies

N/A

### Reproduction script

N/A

### Issue Severity

None

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
Redo ##45919

## Related issue number
Closes #45642

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/node_manager.cc [hunk 1]
```diff
@@ -1889,6 +1899,20 @@ void NodeManager::HandleCancelResourceReserve(
...
                  << bundle_spec.DebugString();
 
+  // Cancel lease requests that are waiting for workers
+  // to free the acquired pg bundle resources
+  // so that pg bundle can be returned.
+  local_task_manager_->CancelTasks(
+      [&](const std::shared_ptr<internal::Work> &work) {
+        const auto bundle_id = work->task.GetTaskSpecification().PlacementGroupBundleId();
+        return (bundle_id.first == bundle_spec.PlacementGroupId()) &&
+               (work->GetState() == internal::WorkStatus::WAITING_FOR_WORKER);
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1909]: Fix for the revert: CancelResourceReserve rpc might be called when prepare failed and in this case, we shouldn't cancel the lease request since the PG will be retried and created eventually. So this fix only limits the cancellation to the lease requests that are waiting for workers since this is the case where we need to free bundle resources.

**Review by rynewang — APPROVED** [review]
