### PR TITLE
Fixing flaky TestRemovingLeasingPlacementGroup caused by race condition

### LINKED ISSUE #29530: [Core][Test] Gcs_placement_group_test fails with asan
### What happened + What you expected to happen

Screen Shot 2022-10-20 at 3 28 30 PM
https://buildkite.com/ray-project/oss-ci-build-branch/builds/636#0183f6c2-1f11-4c14-bef5-21caed593b2b

Seems to start happening recently. We should fix it

### Versions / Dependencies

n/a

### Reproduction script

n/a

### Issue Severity

_No response_

### PR DESCRIPTION
**Pull request by cadedaniel**
Signed-off-by: Cade Daniel <edacih@gmail.com>

## Description
This test became flaky recently when running with ASAN. It is caused by a race condition; the thread that runs the cpp test and an io_service thread both invoke SchedulePendingPlacementGroups, causing use-after-free when that function attempts to remove an element from a container.

See https://github.com/ray-project/ray/issues/29530#issuecomment-1286342816 for further details.

## Testing
To reproduce the failure, I built Ray with ASAN and ran `gcs_placement_group_manager_test` 100 times via `--gtest_repeat=100`. It failed after 16 iterations. With my changes, I can run `gcs_placement_group_manager_test` and it passes, even with `--gtest_repeat=100`.

## Issue
Closes https://github.com/ray-project/ray/issues/29530

### CODE REVIEW

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc [hunk 1]
```diff
@@ -346,8 +346,12 @@ TEST_F(GcsPlacementGroupManagerTest, TestRemovingLeasingPlacementGroup) {
   gcs_placement_group_manager_->OnPlacementGroupCreationFailed(
       placement_group, GetExpBackOff(), true);
 
+  // Sleep 1 second so that io_service_ can invoke SchedulePendingPlacementGroups.
+  // If we invoke it from this thread, then both threads race and cause use-after-free
+  // bugs.
+  std::this_thread::sleep_for(std::chrono::seconds(1));
```
Comment (cadedaniel) [inline src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc:352]: @rkooo567 this is the easiest way to fix this issue but isn't solving the root problem. I think to do that, the best way is to enqueue the individual test steps into the `io_service_` loop so that all interactions with the `gcs_placement_group_manager_` are done from the same thread. Do you think it's worth the tradeoff to do this now, or create an issue and follow up later?

**Comment by cadedaniel** [comment]
edit: actually the flaky test isn't so reproducible, it took 388 repeats to reproduce in one case. I am testing it again with my fix with num_repeats=1000 to verify the flakyness is gone.

**Comment by cadedaniel** [comment]
Failed tests are unrelated. I am running Mac tests now.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Let's try the legit fix (run all in one thread) if this becomes flaky again.
