### PR TITLE
[xray] Cache a task's object dependencies

### LINKED ISSUE #2622: [xray] Stress test with many dependencies hanging on Travis
### Describe the problem
Travis sometimes hangs on this test when using raylet:
`python -m pytest -v -s test/stress_tests.py::test_dependencies[ray_start_combination1]`. Further investigation shows that sometimes a lot of time (>100ms) is being spent computing a task's dependencies. Most likely this is delaying a timer for the task leases, and that is causing a spurious reconstruction. I'm not sure why the job is hanging, though. Most likely the raylet is crashing somewhere.

### Source code / logs
 Here are some [example logs](https://travis-ci.com/ray-project/ray/jobs/139211770) from Travis. If run on verbose on 170e08c, the logs show messages like:
```
.../src/ray/common/client_connection.cc:160: [worker]ProcessMessage with type 1 took 127 ms
```

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

When a task has many dependencies, calling `task.GetDependencies()` may take a very long time (10s of ms). The same is true for calling `GetParentTaskIds` on a `LineageEntry`, which computes the IDs of the tasks that produced the object dependencies. This PR caches these values as part of the `Task` or `LineageEntry`.

## Related issue number
This partially resolves #2622.

### CODE REVIEW

**Comment by robertnishihara** [comment]
cc @heyucongtom

File: src/ray/raylet/lineage_cache.cc [hunk 1]
```diff
@@ -286,7 +290,7 @@ Lineage LineageCache::GetUncommittedLineage(const TaskID &task_id,
         // The stopping condition for recursion is that the entry has
         // been committed to the GCS or has already been forwarded.
         // The lineage always includes the requested task id.
-        return entry.WasExplicitlyForwarded(node_id) && !(entry.GetEntryId() == task_id);
```
Comment (ujvl) [inline src/ray/raylet/lineage_cache.cc]: Doesn't removing this reintroduce the bug where the lineage didn't include the requested task id if it was forwarded before, or is that no longer necessary to have?

Comment (stephanie-wang) [reply src/ray/raylet/lineage_cache.cc]: Oops, nice catch! I was debugging something and left this in the commit by accident...

Comment (ujvl) [reply src/ray/raylet/lineage_cache.cc]: Hmm `LineageCacheTest#TestMarkTaskAsForwarded` has an `assert` that should catch the error if that line is missing, did it not get flagged? I can fix the test if not.

Comment (stephanie-wang) [reply src/ray/raylet/lineage_cache.cc]: Ah, good point! I think we also want to check `forwarded_task_id` in the test you have [here](https://github.com/ray-project/ray/blob/master/src/ray/raylet/lineage_cache_test.cc#L219). I can go ahead and add that to this PR.

File: src/ray/raylet/lineage_cache.cc [hunk 2]
```diff
@@ -35,20 +37,28 @@ const TaskID LineageEntry::GetEntryId() const {
...
 }
 
-const std::unordered_set<TaskID> LineageEntry::GetParentTaskIds() const {
+const std::unordered_set<TaskID> &LineageEntry::GetParentTaskIds() const {
+  return parent_task_ids_;
+}
+
+void LineageEntry::ComputeParentTaskIds() {
+  parent_task_ids_.clear();
   std::unordered_set<TaskID> parent_ids;
```
Comment (pcmoritz) [inline src/ray/raylet/lineage_cache.cc]: This can be removed I think

Comment (stephanie-wang) [reply src/ray/raylet/lineage_cache.cc]: Ah, thanks! Not sure how that compiled...

**Review by pcmoritz — APPROVED** [review]
LGTM, but we should merge https://github.com/ray-project/ray/pull/2642 first since this seems to be triggering it (more?)
