### PR TITLE
Pass in actor creation dummy object for Java

### LINKED ISSUE #3434: Java tests are failing.
The Java tests were broken by https://github.com/ray-project/ray/pull/3422.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

Fixes #3434.

Also, Java has a nicer way of handling this in that the object ID returned by an actor creation task is automatically used as the actor ID. We should consider doing the same in Python.

### CODE REVIEW

File: java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java [hunk 1]
```diff
@@ -172,7 +172,7 @@ private static ByteBuffer convertTaskSpecToFlatbuffer(TaskSpec task) {
     final int parentTaskIdOffset = fbb.createString(task.parentTaskId.toByteBuffer());
     final int parentCounter = task.parentCounter;
     final int actorCreateIdOffset = fbb.createString(task.actorCreationId.toByteBuffer());
-    final int actorCreateDummyIdOffset = fbb.createString(UniqueId.NIL.toByteBuffer());
+    final int actorCreateDummyIdOffset = fbb.createString(task.actorId.toByteBuffer());
```
Comment (robertnishihara) [inline java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java]: The dummy object ID isn't actually the actor ID, right? It's the dummy object for the actor creation task.

Comment (stephanie-wang) [reply java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java]: In the Python frontend, that's true, but it turns out that Java is actually using the dummy object ID as the actor ID [here](https://github.com/ray-project/ray/blob/master/java/runtime/src/main/java/org/ray/runtime/AbstractRayRuntime.java#L222). I think it's actually nice to have some association like this.

Comment (robertnishihara) [reply java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java]: Oh I see, thanks.

**Review by raulchen — APPROVED** [review]
LGTM

File: java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java (hunk 1 above)
Comment (raulchen) [reply java/runtime/src/main/java/org/ray/runtime/raylet/RayletClientImpl.java]: One thing I found useful about having this association is when I debug issues about actor reconstruction, I can easily find the actor creation task id from the actor id, and vice versa.

**Review by raulchen — APPROVED** [review]

**Comment by ericl** [comment]
Some tests failing, but the Java ones look good.
