### PR TITLE
[Core]  Fix nested ref count bug: add NestedIds to reference_counter once a task returns

### LINKED ISSUE #17553: [Core] ref count safety issue when task argument is nested in the return value.
sometimes OBOD gets lookups for objects that the ref counter thinks is out of scope, and responds with error. This causes ObjectNotFound to get raised to the user, crashing the problem:
```
[2021-08-02 18:38:01,396 D 18578 19138] reference_count.cc:500: Calling on_delete for object e2362ccb840337beffffffffffffffffffffffff0100000001000000
[2021-08-02 18:38:01,396 D 18578 19138] core_worker.cc:2626: Object e2362ccb840337beffffffffffffffffffffffff0100000001000000 is deleted. Unpinning the object.
[2021-08-02 18:38:01,396 D 18578 19138] reference_count.cc:483: Deleting Reference to object e2362ccb840337beffffffffffffffffffffffff0100000001000000
[2021-08-02 18:38:01,396 D 18578 19138] reference_count.cc:486: Releasing lineage for object e2362ccb840337beffffffffffffffffffffffff0100000001000000
[2021-08-02 18:38:01,396 D 18578 19138] task_manager.cc:411: Plasma object e2362ccb840337beffffffffffffffffffffffff0100000001000000 out of scope
[2021-08-02 18:38:01,396 D 18578 19138] task_manager.cc:413: Task e2362ccb840337beffffffffffffffffffffffff01000000 has e2362ccb840337beffffffffffffffffffffffff0100000001000000 in scope
[2021-08-02 18:38:01,396 D 18578 19138] task_manager.cc:416: Task e2362ccb840337beffffffffffffffffffffffff01000000 now has 0 plasma returns in scope
[2021-08-02 18:38:01,718 D 18578 19138] reference_count.cc:979: Tried to remove an object location for an object e2362ccb840337beffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. It can happen if the object is already evicted.
[2021-08-02 18:38:02,406 D 18578 19138] reference_count.cc:1168: Tried to register a location subscriber for an object e2362ccb840337beffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. The object has probably already been freed.
[2021-08-02 18:38:02,407 D 18578 19138] reference_count.cc:1168: Tried to register a location subscriber for an object e2362ccb840337beffffffffffffffffffffffff0100000001000000 that doesn't exist in the reference table. The object has probably already been freed.
```

repro cluster: https://beta.anyscale.com/o/anyscale-internal/projects/prj_Rztp4a5rBZCDvG6vtLZDgpX8/?tab=session-list

```
import time
import numpy as np
import torch
import ray
import argparse
paths = [
    f's3://shuffling-data-loader-benchmarks/data/input_data_{i}.parquet.snappy' for i in range(0, 25)
]
def create_parser():
    parser = argparse.ArgumentParser(description="Eric Example")
    parser.add_argument("--address")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=250000,
        metavar="N",
        help="input batch size for training (default: 64)")
    parser.add_argument("--num-workers", type=int, default=4)
    return parser
def create_torch_iterator(split, batch_size, rank=None):
    print(f"Creating Torch shuffling dataset for worker {rank} with "
          f"{batch_size} batch size.")
    numpy_to_torch_dtype = {
        np.bool: torch.bool,
        np.uint8: torch.uint8,
        np.int8: torch.int8,
        np.int16: torch.int16,
        np.int32: torch.int32,
        np.int64: torch.int64,
        np.float16: torch.float16,
        np.float32: torch.float32,
        np.float64: torch.float64,
        np.complex64: torch.complex64,
        np.complex128: torch.complex128
    }
    DATA_SPEC = {
        "embeddings_name0": (0, 2385, np.int64),
        "embeddings_name1": (0, 201, np.int64),
        "embeddings_name2": (0, 201, np.int64),
        "embeddings_name3": (0, 6, np.int64),
        "embeddings_name4": (0, 19, np.int64),
        "embeddings_name5": (0, 1441, np.int64),
        "embeddings_name6": (0, 201, np.int64),
        "embeddings_name7": (0, 22, np.int64),
        "embeddings_name8": (0, 156, np.int64),
        "embeddings_name9": (0, 1216, np.int64),
        "embeddings_name10": (0, 9216, np.int64),
        "embeddings_name11": (0, 88999, np.int64),
        "embeddings_name12": (0, 941792, np.int64),
        "embeddings_name13": (0, 9405, np.int64),
        "embeddings_name14": (0, 83332, np.int64),
        "embeddings_name15": (0, 828767, np.int64),
        "embeddings_name16": (0, 945195, np.int64),
        "one_hot0": (0, 3, np.int64),
        "one_hot1": (0, 50, np.int64),
        "labels": (0, 1, np.float64),
    }
    feature_columns = list(DATA_SPEC.keys())
    feature_types = [
        numpy_to_torch_dtype[dtype] for _, _, dtype in DATA_SPEC.values()
    ]
    label_column = feature_columns.pop()
    label_type = feature_types.pop()
    torch_iterator = split.to_torch(
         label_column=label_column,
         feature_columns=feature_columns,
         label_column_dtype=label_type,
         feature_column_dtypes=feature_types,
         batch_size=batch_size,
         # prefetch_blocks: int = 0,
         # drop_last: bool = False
    )
    return torch_iterator
def create_dataset(filenames):
    pipeline = ray.data.read_parquet(list(filenames))\
        .repeat().random_shuffle()
    return pipeline
if __name__ == '__main__':
    parser = create_parser()
    args = parser.parse_args()
    print("Connecting to Ray cluster...")
    ray.init(address=args.address)
    pipeline = create_dataset(paths)
    splits = pipeline.split(args.num_workers)
    @ray.remote
    def consume(split, rank=None, batch_size=None):
        torch_iterator = create_torch_iterator(split, batch_size=batch_size, rank=rank)
        for i, (x, y) in enumerate(torch_iterator):
            time.sleep(1)
            if i % 10 == 0:
                print(i)
        return
    tasks = [
        consume.remote(split, rank=idx, batch_size=args.batch_size)
        for idx, split in enumerate(splits)
    ]
    ray.get(tasks)
```

### PR DESCRIPTION
**Pull request by scv119**
at high level, our fix composes of follow two steps:

1. when task returns it returns all the nested object refs, currently only inlined nested object refs are returned
2. when the caller received the returned rpc, we update the nest information to reference counter.

Test Plan:
- [x] add integration tests

### CODE REVIEW

File: src/ray/core_worker/task_manager.cc [hunk 1]
```diff
@@ -222,18 +228,18 @@ void TaskManager::CompletePendingTask(const TaskID &task_id,
...
       bool stored_in_direct_memory = in_memory_store_->Put(
           RayObject(data_buffer, metadata_buffer, nested_ids), object_id);
       if (stored_in_direct_memory) {
         direct_return_ids.push_back(object_id);
       }
     }
+
+    rpc::Address owner_address;
+    if (reference_counter_->GetOwner(object_id, &owner_address) &&
+        reference_counter_->OwnedByUs(object_id)) {
```
Comment (stephanie-wang) [inline src/ray/core_worker/task_manager.cc:240]: I don't think we need these if checks since we will always own an object returned by a task we called.

Maybe just check if `!nested_ids.empty()`?

**Comment by stephanie-wang** [comment]
Nice, did it fix the issue?

**Comment by scv119** [comment]
yup it did fixed the issue! it has some other integration tests failure i'm currently looking into.

**Review by stephanie-wang — APPROVED** [review]

File: src/ray/core_worker/reference_count.cc [hunk 2]
```diff
@@ -832,9 +832,12 @@ void ReferenceCounter::AddNestedObjectIdsInternal(
       // contained in the outer object ID so we do not GC the inner objects
       // until the outer object goes out of scope.
       for (const auto &inner_id : inner_ids) {
-        it->second.contains.insert(inner_id);
         auto inner_it = object_id_refs_.find(inner_id);
-        RAY_CHECK(inner_it != object_id_refs_.end());
```
Comment (scv119) [inline src/ray/core_worker/reference_count.cc:837]: @stephanie-wang  sometimes this check fails. could this be a race condition we should handle? (like add it as borrower)

Comment (stephanie-wang) [reply src/ray/core_worker/reference_count.cc:837]: Hmm yeah I think this check is probably too strong. Should be fine to remove it and insert an empty entry if one does not exist yet.

**Comment by scv119** [comment]
looks test_multi_tenancy.py is failing deterministically. taking a look.

**Comment by scv119** [comment]
```pytest ./ray/tests/test_multi_tenancy.py -k test_kill_idle_workers_that_are_behind_owned_workers``` fails. The test failure seemly introduced by this PR

File: src/ray/core_worker/reference_count.cc [hunk 3]
```diff
@@ -833,10 +833,13 @@ void ReferenceCounter::AddNestedObjectIdsInternal(
...
       for (const auto &inner_id : inner_ids) {
         it->second.contains.insert(inner_id);
-        auto inner_it = object_id_refs_.find(inner_id);
-        RAY_CHECK(inner_it != object_id_refs_.end());
         RAY_LOG(DEBUG) << "Setting inner ID " << inner_id
                        << " contained_in_owned: " << object_id;
+      }
+      // WARNING: Following loop could invalidate `it` iterator on insertion.
+      // That's why we use two loops, and we should avoid using `it` hearafter.
+      for (const auto &inner_id : inner_ids) {
```
Comment (scv119) [inline src/ray/core_worker/reference_count.cc:841]: cc @rkooo567  another iterator invalidation bug. tricky stuff...

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 4]
```diff
@@ -510,9 +510,9 @@ void CoreWorkerDirectTaskReceiver::HandleTask(
             return_object->set_metadata(result->GetMetadata()->Data(),
                                         result->GetMetadata()->Size());
           }
-          for (const auto &nested_id : result->GetNestedIds()) {
-            return_object->add_nested_inlined_ids(nested_id.Binary());
-          }
+        }
+        for (const auto &nested_id : result->GetNestedIds()) {
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_actor_transport.cc:514]: I am confused about this change. It means we can have inlined nested IDs where the outer id is a plasma object?

Comment (scv119) [reply src/ray/core_worker/transport/direct_actor_transport.cc:514]: yup, I assume that's necessary for both inlined and plasma objects.

File: src/ray/core_worker/task_manager.cc [hunk 5]
```diff
@@ -189,6 +189,9 @@ void TaskManager::CompletePendingTask(const TaskID &task_id,
     RAY_LOG(DEBUG) << "Task return object " << object_id << " has size "
                    << return_object.size();
 
+    std::vector<ObjectID> nested_ids =
```
[the remark this answers is not in the document]
Comment (scv119) [reply src/ray/core_worker/task_manager.cc:192]: no this one doesn't as it been used in two places.

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 4 above)
Comment (rkooo567) [reply src/ray/core_worker/transport/direct_actor_transport.cc:514]: Are we testing both cases? It looks like the test case is only for outer_id : inlined? (lmk if I misunderstand this)

**Review by rkooo567 — COMMENTED** [review]
Will rely on @stephanie-wang for final merge & approval!

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 4 above)
Comment (rkooo567) [reply src/ray/core_worker/transport/direct_actor_transport.cc:514]: Oops I guess it is merged before it is handled?

Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_actor_transport.cc:514]: Ah my bad. I think it's fine without a test, but I'll leave it to @scv119 to decide.

**Comment by scv119** [comment]
manually tested test passes with RAY_max_direct_call_object_size=0; will add a follow up nightly tests.
