### PR TITLE
[core] Fix reference counter crashes during worker graceful shutdown

### LINKED ISSUE #51408: [Serve/Core] Core Worker crash encountered in Serve during Actor termination
### What happened + What you expected to happen

**Setup**

While testing how my Serve app logic handles Actor termination, I encountered occasional `500`s. Because this issue is quite sporadic and hard to repro, I setup a very adversarial "worst case" test in which I send _a lot_ of concurrent requests and have each request issue a `SIGTERM` to its Actor.

**repro**
```Python
import asyncio
import os
import signal

from ray import serve
import httpx


CONCURRENCY = 100

@serve.deployment(max_ongoing_requests=CONCURRENCY)
class MyDeployment:
    async def __call__(self) -> None:
        os.kill(os.getpid(), signal.SIGTERM)
        await asyncio.sleep(.5)


serve.run(MyDeployment.bind())

# send *a lot* of requests
async def make_request(client: httpx.AsyncClient, request_id: int) -> None:
    response = await client.get("http://localhost:8000/")
    response.raise_for_status()


async def main() -> None:
    while True:
        async with httpx.AsyncClient(timeout=3600) as client:
            tasks = [make_request(client, i) for i in range(CONCURRENCY)]
            await asyncio.gather(*tasks)


asyncio.run(main())
```

Upon failure, I see this Proxy log,

```bash
(ProxyActor pid=58676) ERROR:    ASGI callable returned without starting response.
```

and this Raylet stacktrace,

```bash
[2025-03-16 10:16:49,100 C 58673 1198819] reference_count.cc:945:  Check failed: GetAndClearLocalBorrowersInternal(borrowed_id, false, true, &borrowed_refs) cf57a8fb6704985aae1b951de7f2423be2a62c2f0100000002000000
*** StackTrace Information ***
0   _raylet.so                          0x0000000148d62a1c _ZN3raylsERNSt3__113basic_ostreamIcNS0_11char_traitsIcEEEERKNS_10StackTraceE + 84 ray::operator<<()
1   _raylet.so                          0x0000000148d66320 _ZN3ray6RayLogD2Ev + 84 ray::RayLog::~RayLog()
2   _raylet.so                          0x00000001482d8a10 _ZN3ray4core16ReferenceCounter25PopAndClearLocalBorrowersERKNSt3__16vectorINS_8ObjectIDENS2_9allocatorIS4_EEEEPN6google8protobuf16RepeatedPtrFieldINS_3rpc20ObjectReferenceCountEEEPS7_ + 296 ray::core::ReferenceCounter::PopAndClearLocalBorrowers()
3   _raylet.so                          0x00000001481e1cb0 _ZN3ray4core10CoreWorker26ReportGeneratorItemReturnsERKNSt3__14pairINS_8ObjectIDENS2_10shared_ptrINS_9RayObjectEEEEERKS4_RKNS_3rpc7AddressExyRKNS5_INS0_27GeneratorBackpressureWaiterEEE + 464 ray::core::CoreWorker::ReportGeneratorItemReturns()
4   _raylet.so                          0x00000001480ee4b0 _ZL55__pyx_f_3ray_7_raylet_report_streaming_generator_outputP58__pyx_obj_3ray_7_raylet_StreamingGeneratorExecutionContextP7_objectxS2_ + 2844 __pyx_f_3ray_7_raylet_report_streaming_generator_output()
5   _raylet.so                          0x000000014817a5c0 _ZL173__pyx_pw_11cfunc_dot_to_py_137__Pyx_CFunc_b3889d__3ray_7_raylet_object__lParenStreamingGenerator__etc_to_py_7context_6output_15generator_index_22interrupt_signal_event_1wrapP7_objectPKS0_lS0_ + 1244 __pyx_pw_11cfunc_dot_to_py_137__Pyx_CFunc_b3889d__3ray_7_raylet_object__lParenStreamingGenerator__etc_to_py_7context_6output_15generator_index_22interrupt_signal_event_1wrap()
6   Python                              0x000000010310e8f0 _PyEval_EvalFrameDefault + 50280 _PyEval_EvalFrameDefault
7   Python                              0x000000010301a95c method_vectorcall + 372 method_vectorcall
8   Python                              0x00000001031de8ac thread_run + 144 thread_run
9   Python                              0x0000000103174e2c pythread_wrapper + 48 pythread_wrapper
10  libsystem_pthread.dylib             0x00000001812a1f94 _pthread_start + 136 _pthread_start
11  libsystem_pthread.dylib             0x000000018129cd34 thread_start + 8 thread_start
```

### Versions / Dependencies

```bash
ray=2.43.0
Python=3.12
```

### Reproduction script

please see above!

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### LINKED ISSUE #53012: [core] Reference counter accesses crash during executing during worker draining sequence
### What happened + What you expected to happen

More minimal & general version of: https://github.com/ray-project/ray/issues/51408

We invalidate local references while still allowing tasks to run to completion.

### Versions / Dependencies

master

### Reproduction script

```python
import os
import signal
from typing import List

import ray
from ray._private.test_utils import SignalActor

s = SignalActor.remote()

@ray.remote(max_concurrency=2)
class A:
    def hang(self, ref: List[ray.ObjectRef]):
        print("Hanging until signal...")
        ray.get(s.wait.remote())
        print("Got signal, calling ray.get on ref")
        return ray.get(ref[0])

    def exit(self):
        os.kill(os.getpid(), signal.SIGTERM)

a = A.remote()
hang_ref = a.hang.remote([ray.put("hi")])
ray.get(a.exit.remote())
ray.get(s.send.remote())
ray.get(hang_ref)
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by edoakes**
## Problem description

See https://github.com/ray-project/ray/issues/53012 for minimal reproduction of the issue.

Currently the shutdown sequence looks approximately like:

1. Blindly decrement all local reference counts.
2. Drain ongoing _submitted_ tasks.
3. Drain the local task executor. This drains ongoing _executed_ tasks if the worker is part of a concurrent actor. For single-threaded actors and task workers, it's basically a no-op.
4. Drain the reference counter.

Step (1) essentially invalidates the state of the reference counter, meaning that subsequently executing any user code that interacts with the reference counter will cause undefined behavior and/or crashes. This is the problem observed in the two linked issues. In both cases, the worker is executing concurrent actor tasks which are not drained until step (3).

## Original motivation for `ReleaseAllLocalReferences`

The original motivation for this code is documented in: https://github.com/ray-project/ray/issues/19639. However, I haven't been able to fully understand the rationale or the fix. I also haven't been able to reproduce the issue described, even when substituting the driver for an owner actor to avoid job-level worker cleanup.

What happens in the described setup inside the worker is (confirmed empirically):

1. Before the worker starts to execute the task, we [increase the local reference count](https://github.com/ray-project/ray/blob/871cc89ceda42caaa4819112343ff7b0e005e0e4/src/ray/core_worker/core_worker.cc#L3762) for the argument as part of [GetAndPinArgsForExecutor](https://github.com/ray-project/ray/blob/871cc89ceda42caaa4819112343ff7b0e005e0e4/src/ray/core_worker/core_worker.cc#L3739).
2. The worker executes the task, blocks in `time.sleep`, then raises `SystemExit` when it receives a `SIGTERM`.
3. After `SystemExit` is raised, the rest of `ExecuteTask` is executed, which [decrements the local reference count](https://github.com/ray-project/ray/blob/871cc89ceda42caaa4819112343ff7b0e005e0e4/src/ray/core_worker/reference_count.cc#L968) as part of [PopAndClearLocalBorrowers](https://github.com/ray-project/ray/blob/871cc89ceda42caaa4819112343ff7b0e005e0e4/src/ray/core_worker/core_worker.cc#L3403).
4. The worker calls [CoreWorker::Exit()](https://github.com/ray-project/ray/blob/871cc89ceda42caaa4819112343ff7b0e005e0e4/src/ray/core_worker/core_worker.cc#L3455).

During the shutdown sequence in (4), the reference has already been cleared, so the call to `ReleaseAllLocalReferences` is a no-op.

However, there is another edge case that `ReleaseAllLocalReferences` does currently handle, which is when a normal task (not an actor task) stores an `ObjectRef` in a global variable before exiting. We currently [assume this never happens](https://github.com/ray-project/ray/blob/871cc89ceda42caaa4819112343ff7b0e005e0e4/src/ray/core_worker/core_worker.cc#L1229). In this case, the call to `ReleaseAllLocalReferences` will decrement the globally-held reference(s) and allow the worker to exit.

## Solution and alternatives

Originally I planned to fully delete the call to `ReleaseAllLocalReferences`, but it would cause a behavior change in the edge case described above pertaining to `ObjectRef`s stored in global variables.

Therefore, I'm opting for a safe option for now: move the call to `ReleaseAllLocalReferences` _after_ we drain the task executor, which should be a no-op change for single-threaded actors and normal task workers, but solve the issue of tasks executing after the reference counter has been invalidated in the case of concurrent actors.

## Follow-up items

- We should solve the global `ObjectRef` issue for tasks separately, then remove the `ReleaseAllLocalReferences` logic. (TODO: file ticket before merging -- 1 ref and multiple refs)

Closes https://github.com/ray-project/ray/issues/51408
Closes https://github.com/ray-project/ray/issues/53012

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -1220,12 +1216,20 @@ void CoreWorker::Exit(
             not_actor_task = actor_id_.IsNil();
           }
           if (not_actor_task) {
-            // If we are a task, then we cannot hold any object references in the
-            // heap. Therefore, any active object references are being held by other
-            // processes. Wait for these processes to release their references
-            // before we shutdown. NOTE(swang): This could still cause this worker
-            // process to stay alive forever if another process holds a reference
-            // forever.
+            // Normal tasks should not hold any object references in the heap after
```
Comment (jjyao) [inline src/ray/core_worker/core_worker.cc:1219]: > However, there is another edge case that ReleaseAllLocalReferences does currently handle, which is when a normal task (not an actor task) stores an ObjectRef in a global variable before exiting.

Did you find it out due to a failed test? I doubt `ReleaseAllLocalReferences` is intended to be used to fix the global var issue.

**Review by jjyao — COMMENTED** [review]
Could you add a test?

File: src/ray/core_worker/core_worker.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/core_worker/core_worker.cc:1219]: OK, let's keep it for now then.

**Comment by edoakes** [comment]
@jjyao I've added a regression test

**Review by jjyao — APPROVED** [review]

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -1220,12 +1216,20 @@ void CoreWorker::Exit(
...
+            // references left to drain should be those that are in use by remote
+            // workers. If these workers hold their references forever, the call to
+            // drain the reference counter will hang forever and this process will not
+            // exit until it is forcibly removed (e.g., via SIGKILL).
+            //
+            // NOTE(edoakes): this is only safe to do _after_ we have drained executing
+            // tasks in the task_receiver_, otherwise there might still be user code
+            // running that relies on the state of the reference counter.
+            // See: https://github.com/ray-project/ray/pull/53002.
+            reference_counter_->ReleaseAllLocalReferences();
```
Comment (codope) [inline src/ray/core_worker/core_worker.cc:1232]: Just for my understanding: with this change, the `ReleaseAllLocalReferences` is never called before actor shutdown. So:
1. Is that expected? Can there be a leaking actor worker?
2. Why don't we follow the same release order for actors? From the comment in the actor branch, I can understand why we need not wait to drain the object refs but I don't fully get it why there is no need to release all local refs for actor.

File: src/ray/core_worker/core_worker.cc [hunk 3]
```diff
@@ -1176,10 +1176,6 @@ void CoreWorker::Exit(
   }
 
   RAY_LOG(DEBUG) << "Exit signal received, remove all local references.";
```
Comment (codope) [inline src/ray/core_worker/core_worker.cc:1178]: Should this log be also moved inside the `not_actor_task` branch?

Comment (edoakes) [reply src/ray/core_worker/core_worker.cc:1178]: yes it should! let me fix

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
Comment (edoakes) [reply src/ray/core_worker/core_worker.cc:1232]: We really shouldn't need to call this method for either case, as written in the PR description I cannot find a strong reasoning for it.

Note that in the other branch, we already assume that actors can have "dangling" local references. For example, they might do this:

```python
@ray.remote
class Actor:
    def __init__(self):
        self._dangling_ref = None

    def method(self):
        self._dangling_ref = ray.put(123)
```

In this case, after an invocation of `method` finishes, the actor will still have `dangling_ref` in scope. So the call to drain the reference counter would hang forever, therefore we don't drain it at all (and immediately call `shutdown` instead0.

In the current code, we assume that tasks cannot do this because they are "pure" functions. However, there's an edge case where they might store a ref in a global variable in a similar way. The `ReleaseAllLocalRefs` call is incidentally handling that today despite not being intended for that purpose. That's why I'm still including it in that branch of the logic.

File: src/ray/core_worker/core_worker.cc (hunk 3 above)
Comment (edoakes) [reply src/ray/core_worker/core_worker.cc]: fixed, thx

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
Comment (codope) [reply src/ray/core_worker/core_worker.cc:1232]: got it, this is very helpful. thanks!

**Review by codope — APPROVED** [review]

**Review by israbbani — APPROVED** [review]
🚢
