### PR TITLE
[Core] Event loop instrumentation concurrency fixes.

### LINKED ISSUE #14715: Fix Asyncio Event Metrics on Java
### What is the problem?
* Asyncio Event Loop Metrics (introduced in #14546) seem to cause segfaults in Java Tests.
* This caused Asyncio Event Metrics to be disabled in #14692. This issue is to fix the cause of the segfaults and re-enable Event Loop Metrics.

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by clarkzinzow**
## Why are these changes needed?

The event loop instrumentation was designed under the assumption that the thread that creates the `instrumented_io_context` object (the main thread) will join all handler executing threads (threads in which `io_context.run()` is called) before exiting itself, therefore ensuring that all `instrumented_io_context` members will outlive all handlers and allowing us to freely reference those members in the handlers. Although this holds true for Ray components in which we control the exit behavior (such as the raylet), the main core worker thread can be killed by language frontend code without joining the threads (e.g. via `sys.exit(-1)` in Java), which violates this assumption and can cause segfaults. This is currently happening in Java tests, which call `sys.exit(-1)` [in failure tests](https://github.com/ray-project/ray/blob/bd641a5e7137e23a340454902a6f1b95efe2f719/java/test/src/main/java/io/ray/test/FailureTest.java#L64).

This PR moves the likely culprit, the global stats struct, behind a shared pointer, and ensures that handler lambdas close over that stats struct by-value, thereby incrementing the reference count and ensuring that the global stats struct lifetime will be tied to the last handler that executes or the main thread, which ever lives longest. This PR also fixes a potential issue with unintentionally copying a handler stats struct outside of a lock, and ports the move capture helper function to use C++14 generalized lambda capture.

NOTE: Java tests still occasionally segfault, although seemingly less frequently. This might solve one of more than one hard exit segfault triggers.

## TODOs

~- [ ] Ensure that the Java tests pass several times in the CI.~ Failed on the third run.

## Related issue number

Towards #14715 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/common/asio/instrumented_io_context.cc [hunk 1]
```diff
@@ -80,63 +55,65 @@ void instrumented_io_context::post(std::function<void()> handler,
...
 }
 
 /// A helper for creating a snapshot view of the stats for a handler.
-/// This acquires a reader lock on the provided guarded handler stats, and creates a
+/// This acquires a lock on the provided guarded handler stats, and creates a
 /// lockless copy of the stats.
-inline HandlerStats to_handler_stats_view(const GuardedHandlerStats &stats) {
-  absl::MutexLock lock(&(stats.mutex));
-  return HandlerStats(stats.stats);
+inline HandlerStats to_handler_stats_view(std::shared_ptr<GuardedHandlerStats> stats) {
```
Comment (iycheng) [inline src/ray/common/asio/instrumented_io_context.cc:114]: nit: I think the inline here is not necessary. It's cpp file, not included in other files.

**Review by fishbone — COMMENTED** [review]
I feel good about this. Could you run the benchmark again to make sure there is no regression?

File: src/ray/common/asio/instrumented_io_context.cc (hunk 1 above)
Comment (clarkzinzow) [reply src/ray/common/asio/instrumented_io_context.cc:114]: It was my [initial impression](https://github.com/ray-project/ray/pull/14546#discussion_r589860536) that these explicit `inline` specifiers weren't necessary. Would it be best practice here to remove the explicit `inline` specifier and put these helper functions into an anonymous namespace (to guarantee that it won't be externally visible)?

**Comment by clarkzinzow** [comment]
@iycheng I ran the microbenchmarks to ensure the event loop stats collection was working well, I'll do a before-and-after.

**Comment by clarkzinzow** [comment]
### Before

```
single client get calls per second 49628.79 +- 835.5
single client put calls per second 36534.62 +- 378.83
multi client put calls per second 79604.35 +- 1341.16
single client get calls (Plasma Store) per second 8657.44 +- 57.11
single client put calls (Plasma Store) per second 3506.18 +- 11.53
multi client put calls (Plasma Store) per second 5207.03 +- 35.36
single client put gigabytes per second 14.01 +- 7.69
multi client put gigabytes per second 7.15 +- 0.54
single client tasks sync per second 1314.56 +- 1.56
single client tasks async per second 9440.87 +- 44.22
multi client tasks async per second 10975.97 +- 58.85
1:1 actor calls sync per second 2271.33 +- 24.77
1:1 actor calls async per second 6759.61 +- 69.74
1:1 actor calls concurrent per second 4751.42 +- 1369.51
1:n actor calls async per second 12064.39 +- 180.7
n:n actor calls async per second 13442.32 +- 343.65
n:n actor calls with arg async per second 5399.44 +- 71.75
1:1 async-actor calls sync per second 1563.8 +- 10.31
1:1 async-actor calls async per second 3721.01 +- 8.27
1:1 async-actor calls with args async per second 2501.78 +- 10.89
1:n async-actor calls async per second 7292.43 +- 69.24
n:n async-actor calls async per second 8349.6 +- 21.45
client: get calls per second 1744.66 +- 5.33
client: put calls per second 902.41 +- 3.07
client: remote put calls per second 5014.5 +- 32.22
client: 1:1 actor calls sync per second 545.36 +- 2.49
client: 1:1 actor calls async per second 602.74 +- 1.75
client: 1:1 actor calls concurrent per second 601.12 +- 2.37
```

### After

```
single client get calls per second 49437.78 +- 2458.23
single client put calls per second 37273.85 +- 114.48
multi client put calls per second 81536.83 +- 2260.87
single client get calls (Plasma Store) per second 8644.42 +- 89.19
single client put calls (Plasma Store) per second 3488.68 +- 17.14
multi client put calls (Plasma Store) per second 5128.85 +- 41.53
single client put gigabytes per second 13.82 +- 7.63
multi client put gigabytes per second 7.22 +- 0.65
single client tasks sync per second 1306.31 +- 9.54
single client tasks async per second 9393.71 +- 59.25
multi client tasks async per second 10891.09 +- 167.58
1:1 actor calls sync per second 2324.7 +- 19.46
1:1 actor calls async per second 6976.31 +- 161.68
1:1 actor calls concurrent per second 6052.16 +- 57.26
1:n actor calls async per second 12200.43 +- 203.43
n:n actor calls async per second 13652.14 +- 232.01
n:n actor calls with arg async per second 5470.06 +- 37.89
1:1 async-actor calls sync per second 1587.25 +- 14.02
1:1 async-actor calls async per second 3708.15 +- 15.08
1:1 async-actor calls with args async per second 2398.18 +- 88.97
1:n async-actor calls async per second 6550.88 +- 929.14
n:n async-actor calls async per second 8110.03 +- 140.3
client: get calls per second 1765.36 +- 6.15
client: put calls per second 886.79 +- 8.3
client: remote put calls per second 4985.33 +- 49.77
client: 1:1 actor calls sync per second 545.32 +- 2.29
client: 1:1 actor calls async per second 602.74 +- 2.82
client: 1:1 actor calls concurrent per second 602.56 +- 0.42
```

cc @iycheng 

NOTE: I kicked off a big Bazel build while running the "After" `1:n async-actor calls async` benchmark before remembering that I had microbenchmarks running, so that should explain the small dip in that benchmark.

File: src/ray/common/asio/instrumented_io_context.cc (hunk 1 above)
Comment (clarkzinzow) [reply src/ray/common/asio/instrumented_io_context.cc]: I opted for the anonymous namespace: https://github.com/ray-project/ray/pull/14719/commits/ea65e28c5a6d15c6c9a4422c8ad153205f831220

Comment (iycheng) [reply src/ray/common/asio/instrumented_io_context.cc]: Actually, I think I'm wrong. `inline` is still useful here, which gives the compiler the hint for optimization. No inline can still make things compiled successfully though.

'anonymous namespace' is useful for the function defined in cc only since it'll be invisible from outside. I remember you can use inline and anonymous together, they are for different purpose.

File: src/ray/common/asio/instrumented_io_context.cc [hunk 2]
```diff
@@ -19,31 +19,42 @@
...
-capture_impl<T, F> capture(T &&x, F &&f) {
-  return capture_impl<T, F>(std::forward<T>(x), std::forward<F>(f));
+/// A helper for converting a duration into a human readable string, such as "5.346 ms".
+std::string to_human_readable(int64_t duration) {
+  return to_human_readable(static_cast<double>(duration));
 }
 
+}  // namespace
+
 void instrumented_io_context::post(std::function<void()> handler,
```
Comment (iycheng) [inline src/ray/common/asio/instrumented_io_context.cc:58]: I just notice `instrumented_io_context` is not put in ray namespace. Do you think it's good to add `namespace ray`?

Comment (clarkzinzow) [reply src/ray/common/asio/instrumented_io_context.cc:58]: Yeah I considered doing that in the first PR, but I noticed that some similar Ray utilities aren't in the `ray` namespace. I'd be happy to put it in the `ray` namespace (I do think it should be in that namespace), but I'd prefer to do it in another PR since it will probably touch a lot of files.

**Comment by clarkzinzow** [comment]
@iycheng @ericl The Java tests passed in the PR build: https://travis-ci.com/github/ray-project/ray/jobs/491603201

File: src/ray/common/asio/instrumented_io_context.cc (hunk 2 above)
Comment (iycheng) [reply src/ray/common/asio/instrumented_io_context.cc:58]: Sure, that sounds good to me

**Review by fishbone — APPROVED** [review]

File: src/ray/common/asio/instrumented_io_context.cc (hunk 1 above)
Comment (clarkzinzow) [reply src/ray/common/asio/instrumented_io_context.cc]: I thought that the anonymous namespace pattern was useful within non-header files when you're wanting to (1) prevent link collisions with your helper functions and other unnamespaced functions outside of the module, (2) make all such helpers translation unit local such that external linkage is impossible. Even if (2) doesn't serve as an extra inlining compiler hint, it will hopefully serve as a hint to future developers that want to publicly expose those helpers that they may want to consider whether they should add an explicit `inline` specifier given that they are opening the function up to external linkage.

Comment (clarkzinzow) [reply src/ray/common/asio/instrumented_io_context.cc]: And I don't think that an explicit `inline` specifier would do anything more to encourage the compiler to inline the function than defining the function within an anonymous namespace (guaranteed no external linkage) in a non-header source file, right? The `inline` specifier is just a linker directive and is only useful when the function definition might show up in multiple translation units (i.e. defined in the header).

**Comment by rkooo567** [comment]
@clarkzinzow how many times did you run Java tests? (Can we wait until it succeed 3 times in a row?)

**Comment by clarkzinzow** [comment]
@rkooo567 Just ran once, I'll run it two more times to confirm.

**Comment by clarkzinzow** [comment]
@rkooo567 I assume that you restarted the Java test build just now?

**Comment by rkooo567** [comment]
Yeah! That’s what I did!

**Comment by clarkzinzow** [comment]
@rkooo567 Java tests passed on the second run, running one more time.

**Comment by clarkzinzow** [comment]
@rkooo567 It looks like I celebrated too early, the Java tests segfaulted on the third run 😞  https://travis-ci.com/github/ray-project/ray/jobs/491603201

**Comment by clarkzinzow** [comment]
I can either keep iterating on the fix in this PR, or I can turn the feature flag back off, merge this PR, and the fix + turning the feature flag back on can happen in another PR. I'm leaning towards the latter.

**Comment by rkooo567** [comment]
Yeah I am okay to merge this PR first and keep working on it. Please make sure to turn off the feature flag, and lmk when it is ready to merge :)

**Comment by clarkzinzow** [comment]
@rkooo567 Feature flag has been turned off by the last revert commit, should be ready to merge after I ensure all tests are passing.
