### PR TITLE
Fix hang if actor object id is returned from a task that exits

### LINKED ISSUE #6878: Getting a released nested actor will block forever
Getting a released nested actor will block forever. I do understand this is an error in code but I guess some improvements can be achieved like raising an exception.

### Reproduction 
``` Python
@ray.remote
class A:
    def __init__(self):
        print('A::init')
    def fa(self):
        print('A::a')
        return 'a'

@ray.remote
def func_a():
    a = A.remote()
    return ray.get(a.fa.remote())

@ray.remote
def func_b():
    a = A.remote()
    return a.fa.remote()  # after this, `a` is released!

@ray.remote
def func_c():
    a = A.remote()
    ret = a.fa.remote()
    ray.wait([ret])  # wait until a.fa.remote() really got excuted
    return ret 

# good case
>>> a = ray.get(func_a.remote())  # OK, a is 'a'
(pid=xxxx) A::init         # expected print
(pid=xxxx) A::a            # expected print
# bad case
>>> b = ray.get(func_b.remote())  # OK, b is a remote ObjectID
(pid=xxxx) A::init         # expected print, but "A::a" is not printed
>>> ray.get(b)             # blocking forever in a `__pthread_cond_wait` call

>>> c = ray.get(func_c.remote())  # OK, c is a remote ObjectID
(pid=xxxx) A::init         # expected print
(pid=xxxx) A::a            # expected print
>>> c = ray.get(ray.get(c))   # OK, c is 'a' now       
```

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Since we unsubscribe from actor notifications, the core worker never receives the actor death notification.

Fix is to not unsubscribe.

Closes https://github.com/ray-project/ray/issues/6878

### CODE REVIEW

**Review by stephanie-wang — APPROVED** [review]
Looks good.

We should eventually clean up the subscriptions, though, or else this will break too if a function like the one in the test is called enough times. Can you leave a TODO for the AsyncSubscribe call to say what condition we should wait for before it's safe to permanently unsubscribe?

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -635,6 +624,14 @@ std::string CoreWorker::MemoryUsageString() {
   return plasma_store_provider_->MemoryUsageString();
 }
 
+TaskID CoreWorker::GetInitialCallerId() {
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc]: @stephanie-wang this effectively makes the caller id per-worker for purposes of actor sequencing. This is now needed since the actor handles are shared across multiple tasks.
