### PR TITLE
[core] on plasma server, ref count fds to each client, and request unmaps on release.

### LINKED ISSUE #39229: [Core] Data jobs able to trigger persistent mmap file leak in between job runs
### What happened + What you expected to happen

When I have a long-running Ray cluster that I’m running multiple jobs on (for iteration in development), eventually I will start getting OOMs during initial SQL read (i.e. `SplitBlocks`). I’m under the impression that sometimes Ray is “spilling” some data into tmpfs or shmem, but I don’t think it should persist in between jobs. Is there any way to clean up this junk in between runs so that I don’t have to restart my cluster?

I’m aware that spilling in Ray happens when object memory is high, but I have 500GiB object memory and my usage never reaches anywhere near that.

What's more is that the OOMs are always just *slightly* above Ray's 95% kill rate -- it's as if there is a rounding error happening somewhere.

// This is only tangentially related to datasets, I’m writing it here because my jobs only use the datasets library, and I’m wondering if this phenomenon is specific to the ray library. If this is the wrong place to post this, please let me know

### Versions / Dependencies

* Ray 2.6.1 using this Docker image`ray:2.6.1.7474f8-py38-cpu`. You can pull down the docker image I have on top of it [here](https://hub.docker.com/r/paulvorobyev/ray-test), but I don't think it's relevant

* Python 3.8.13

* Running using Ray clusters (ie not in Kuberay)

* Running on a fleet of AWS `m5.4xlarge` and `g5.2xlarge`

### Reproduction script

Run a script like this repeatedly. Eventually machines will OOM
```
import ray

ray.init()

@ray.remote()
def do_data():
   ds = ray.data.read_sql("<read huge SQL table here>") # we use this snowflake table: https://app.snowflake.com/marketplace/listing/GZTSZ290BUX1X/cybersyn-inc-cybersyn-llm-training-essentials
     .materialize().show()

ray.get(do_data.remote())
```

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by rynewang**
Plasma memory  sharing works this way: the plasma server creates a temp file and mmaps it; then upon plasma client's Get, the server sends the fd to client who mmaps that fd. Then client can Release an object, and if all clients released refs to an fd, the server unmaps it. See the missing piece? the plasma client never unmaps.

This is normally not a problem because we don't want to unmap the main memory in /dev/shm anyway; but on memory pressure when we do fallback allocations (mmaps to disk files in /tmp/ray), we will leak mmaps by never unmapping them in plasma client, even if nobody is using those mmap files. To make things worse, raylet itself has a plasma client so even if the core workers exit we are still leaking.

A good place for a plasma client to unmap is at Release, after which it may no longer read or write an object ID. However a mmap region may be used by more than 1 object (this is NOT the case today for fallback allocations, but we want to be future proof); also if a mmap region is unmapped and mapped again, the plasma client fails, because the plasma server did not know the client unmapped it and hence would not send the fd.

This PR allows the plasma server to ask a plasma client to unmap. The server maintains a per-client ref count table: {object ID -> mmap fd}, and if a certain fd is no longer referenced by a Release request, the server sends a boolean "should_unmap" which orders the client to do that. The client MUST unmap.

If some time later the same fd needs to be mapped again in a Get request, it's fine, because the server knows the client no longer mmaps that fd, and would send the fd; and the client had removed the knowledge of that fd so it receives the fd and maps again.

Fixes #39229

### CODE REVIEW

File: src/ray/object_manager/plasma/protocol.cc [hunk 1]
```diff
@@ -395,18 +395,23 @@ Status ReadReleaseRequest(uint8_t *data, size_t size, ObjectID *object_id) {
 
 Status SendReleaseReply(const std::shared_ptr<Client> &client,
                         ObjectID object_id,
+                        bool should_reply,
                         PlasmaError error) {
   flatbuffers::FlatBufferBuilder fbb;
-  auto message =
-      fb::CreatePlasmaReleaseReply(fbb, fbb.CreateString(object_id.Binary()), error);
+  auto message = fb::CreatePlasmaReleaseReply(
+      fbb, fbb.CreateString(object_id.Binary()), should_reply, error);
```
Comment (rkooo567) [inline src/ray/object_manager/plasma/protocol.cc:402]: should_unmap?

File: src/ray/object_manager/test/get_request_queue_test.cc [hunk 2]
```diff
@@ -106,7 +108,9 @@ TEST_F(GetRequestQueueTest, TestObjectSealed) {
   GetRequestQueue get_request_queue(
       io_context_,
       object_lifecycle_manager,
-      [&](const ObjectID &object_id, const auto &request) {},
+      [&](const ObjectID &object_id,
+          std::optional<MEMFD_TYPE> fallback_allocated_fd,
```
Comment (rkooo567) [inline src/ray/object_manager/test/get_request_queue_test.cc:112]: can you add a simple unit test to verify this is passed correctly?

File: src/ray/object_manager/plasma/connection.h [hunk 3]
```diff
@@ -54,7 +91,15 @@ class Client : public ray::ClientConnection, public ClientInterface {
...
 
   /// Object ids that are used by this client.
+  /// TODO: remove this as we can always count on object_ids_to_fds_.
   std::unordered_set<ray::ObjectID> object_ids;
+
+  // Records each fd sent to the client and which object IDs are in this fd.
+  // Only tracks fallback-allocated fds. This means the main memory is not tracked, and we
+  // won't tell client to unmap the main memory. Incremented by `Get`, Decremented by
+  // `Release`. If an FD is emptied out, the fd can be unmapped on the client side.
+  absl::flat_hash_map<MEMFD_TYPE, size_t> fds_ref_count_;
```
Comment (rkooo567) [inline src/ray/object_manager/plasma/connection.h:101]:
```suggestion
  absl::flat_hash_map<MEMFD_TYPE, size_t> fallback_allocated_fds_ref_count_;
```

File: src/ray/object_manager/plasma/connection.h [hunk 4]
```diff
@@ -54,7 +91,15 @@ class Client : public ray::ClientConnection, public ClientInterface {
...
+  absl::flat_hash_map<ray::ObjectID, MEMFD_TYPE> object_ids_to_fds_;
```
Comment (rkooo567) [inline src/ray/object_manager/plasma/connection.h:102]:
```suggestion
  absl::flat_hash_map<ray::ObjectID, MEMFD_TYPE> object_ids_to_fallback_allocated_fds_;
```

File: src/ray/object_manager/plasma/connection.h [hunk 5]
```diff
@@ -37,12 +38,48 @@ class Client : public ray::ClientConnection, public ClientInterface {
...
+      return false;
+    }
+    auto iter = object_ids_to_fds_.find(object_id);
+    if (iter == object_ids_to_fds_.end()) {
+      return false;
+    }
+    MEMFD_TYPE fd = iter->second;
+    object_ids_to_fds_.erase(iter);
+
+    size_t &ref_count = fds_ref_count_[iter->second];
```
Comment (rkooo567) [inline src/ray/object_manager/plasma/connection.h:75]: if fds_ref_count_[iter->second]; didn't exist before (this will create a new entry if it didn't exist), it can have a leak (because ref_count == 0 and you decrement - 1).

Comment (rkooo567) [reply src/ray/object_manager/plasma/connection.h:75]: Maybe we can have a bit stronger check since the state between `fds_ref_count_` and `object_ids_to_fds_` should be in sync ? (I beleive it is still idepmotent)

```
auto it = fds_ref_count_.find(fd)
// If fd existed before from object_ids_to_fds_ the ref count should have been > 0
RAY_CHECK(it != fds_ref_count_.end());
size_t &ref_cnt = fds_ref_count_[fd];
RAY_CHECK(ref_cnt > 0);
fds_ref_count_[fd] -= 1
if (ref_count == 0) {
...
}
```

File: src/ray/object_manager/plasma/client.cc [hunk 6]
```diff
@@ -581,16 +586,33 @@ Status PlasmaClient::Impl::Release(const ObjectID &object_id) {
...
     RAY_RETURN_NOT_OK(MarkObjectUnused(object_id));
     RAY_RETURN_NOT_OK(SendReleaseRequest(store_conn_, object_id));
+    std::vector<uint8_t> buffer;
+    RAY_RETURN_NOT_OK(
+        PlasmaReceive(store_conn_, MessageType::PlasmaReleaseReply, &buffer));
+    ObjectID released_object_id;
+    bool should_unmap;
+    RAY_RETURN_NOT_OK(ReadReleaseReply(
+        buffer.data(), buffer.size(), &released_object_id, &should_unmap));
+    if (should_unmap) {
```
Comment (rkooo567) [inline src/ray/object_manager/plasma/client.cc:608]: Can you add a comment this is always false if the mmap is not fallback allocated? (it'd be nice to have assertion here, but I assume there's no way to check if mmap is fallback allocated vs not in client and add RAY_CHECK right?)

**Review by rkooo567 — COMMENTED** [review]
Generally LGTM. I will approve it after addressing comments (small)

File: src/ray/object_manager/plasma/protocol.cc (hunk 1 above)
Comment (rynewang) [reply src/ray/object_manager/plasma/protocol.cc]: fixed

File: src/ray/object_manager/plasma/client.cc (hunk 6 above)
Comment (rynewang) [reply src/ray/object_manager/plasma/client.cc:612]: yeah there's no way. In fact this is the main reason why we need to transfer this bool in the first place (because client can't tell)

File: src/ray/object_manager/plasma/connection.h (hunk 5 above)
Comment (rynewang) [reply src/ray/object_manager/plasma/connection.h]: done.

File: src/ray/object_manager/test/get_request_queue_test.cc (hunk 2 above)
Comment (rynewang) [reply src/ray/object_manager/test/get_request_queue_test.cc:119]: done.

File: src/ray/object_manager/plasma/connection.h [hunk 7]
```diff
@@ -37,12 +38,52 @@ class Client : public ray::ClientConnection, public ClientInterface {
...
   const std::unordered_set<ray::ObjectID> &GetObjectIDs() override { return object_ids; }
 
-  virtual void MarkObjectAsUsed(const ray::ObjectID &object_id) override {
-    object_ids.insert(object_id);
+  // Holds the object ID. If the object ID has a fallback-allocated fd, adds the ref count
+  // to that fd. Note: used_fds_ is not updated. rather, it's updated in SendFd().
+  //
+  // Idempotency: only increments ref count if the object ID was not held.
+  // TODO(ryw): if this method is called with same object_id but different fd, the latter
+  // fd is ignored. Is this possible? Is it OK?
```
Comment (jjyao) [inline src/ray/object_manager/plasma/connection.h:46]: Convert this to a CHECK?

File: src/ray/object_manager/plasma/connection.h [hunk 8]
```diff
@@ -37,12 +38,52 @@ class Client : public ray::ClientConnection, public ClientInterface {
...
+      return false;
+    }
+    MEMFD_TYPE fd = fd_iter->second;
+    object_ids_to_fallback_allocated_fds_.erase(fd_iter);
+
+    auto ref_cnt_iter = fallback_allocated_fds_ref_count_.find(fd);
+    // If fd existed before from object_ids_to_fds_ the ref count should have been > 0
+    RAY_CHECK(ref_cnt_iter != fallback_allocated_fds_ref_count_.end());
+    size_t &ref_cnt = ref_cnt_iter->second;
+    RAY_CHECK(ref_cnt > 0);
```
Comment (jjyao) [inline src/ray/object_manager/plasma/connection.h:79]: RAY_CHECK_GT

**Review by jjyao — APPROVED** [review]

File: src/ray/object_manager/plasma/client.cc [hunk 9]
```diff
@@ -581,16 +586,37 @@ Status PlasmaClient::Impl::Release(const ObjectID &object_id) {
...
   if (object_entry->second->count == 0) {
+    // object_entry is invalidated in MarkObjectUnused, need to read the fd beforehand.
+    MEMFD_TYPE fd = object_entry->second->object.store_fd;
     // Tell the store that the client no longer needs the object.
     RAY_RETURN_NOT_OK(MarkObjectUnused(object_id));
     RAY_RETURN_NOT_OK(SendReleaseRequest(store_conn_, object_id));
+    std::vector<uint8_t> buffer;
+    RAY_RETURN_NOT_OK(
+        PlasmaReceive(store_conn_, MessageType::PlasmaReleaseReply, &buffer));
+    ObjectID released_object_id;
```
[the remark this answers is not in the document]
Comment (rynewang) [reply src/ray/object_manager/plasma/client.cc:604]: will monitor release perf tests after this PR.

File: src/ray/object_manager/plasma/connection.h (hunk 7 above)
Comment (rynewang) [reply src/ray/object_manager/plasma/connection.h:46]: done

File: src/ray/object_manager/plasma/connection.h (hunk 8 above)
Comment (rynewang) [reply src/ray/object_manager/plasma/connection.h]: done

File: src/ray/object_manager/plasma/client.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/object_manager/plasma/client.cc:604]: I don't think any of existing test can find perf diff from this change (it is only applied to fallbcak allocation). We should write a new test. I feel like it is probably okay not to do this.

**Comment by rkooo567** [comment]
@rynewang can you handle the premerge failures? Also plz double check if the data tests failing in this CI is also flaky in the master (since they could be related )

**Comment by rkooo567** [comment]
Let's merge this asap since it is high risk change

File: src/ray/object_manager/plasma/client.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (rynewang) [reply src/ray/object_manager/plasma/client.cc:604]: no this applies to all object releases, just for fallback allocations the bool should_unmap == true.

**Comment by rynewang** [comment]
> @rynewang can you handle the premerge failures? Also plz double check if the data tests failing in this CI is also flaky in the master (since they could be related )

ok. I think it's due to too far behind the master && a linter complaint. updated

**Comment by jjyao** [comment]
Premerge failed. Can you take a look?

**Comment by rkooo567** [comment]
get_request_queue test in windows failure seem related

**Comment by rynewang** [comment]
premerge is green now

**Review by rkooo567 — CHANGES_REQUESTED** [review]
workflow failure is a real issue and we shouldn't modify by fixing a test.

**Comment by rynewang** [comment]
Premerge passed; CI civ1 test failed on test_memory_pressure which is already failing on master:

image

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
This was a really awesome investigation! Great job!
