### PR TITLE
Fix CHECK_FAIL when scheduling task with duplicate object requests

### LINKED ISSUE #15990: Ray 1.3.0 CHECK fail during normal task scheduling
### What is the problem?

While transitioning Modin to Ray version 1.3.0 we have several tests crash in Github Actions CI. Crashes could not be reproduced in development environment until I tried to create a VM with the same specs as Github Actions run: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
Running such VM with 2 CPU cores and 7GB of RAM stably reproduces these crashes.

*Ray version and other system information (Python version, TensorFlow version, OS):*

Ray 1.3.0. Ubuntu 20.04.2 LTS.

### Reproduction (REQUIRED)
I created a Vagrantfile to easily create and provision a reproducer VM:
[Vagrantfile.gz](https://github.com/ray-project/ray/files/6525000/Vagrantfile.gz)

To use it follow these steps:
1. You need to have virtualization settings enabled in your BIOS https://bce.berkeley.edu/enabling-virtualization-in-your-pc-bios.html
2. Install vagrant from https://www.vagrantup.com/downloads
3. Install VM provider if not installed. By default vagrant uses VirtualBox.
3.1. Install VirtualBox from https://www.virtualbox.org/wiki/Linux_Downloads
3.2. Alternatively you can use KVM. I checked that both VMs produce the same result. To use KVM you need to install `vagrant-libvirt` plugin by `vagrant plugin install vagrant-libvirt`. It requires a bunch of dependencies which can be found here https://github.com/vagrant-libvirt/vagrant-libvirt. Also since my /var/lib filesystem is not large enough, I set up VMs to use an `images` pool which can be created and activated like this:
```
virsh pool-define-as images dir --target /localdisk/libvirt
virsh pool-start images
```
4. Add your user to `vboxusers` or `libvirt` group and make sure that setting is effective.
5. Run `vagrant up` in the same directory as Vagrantfile.
6. To get to VM run `vagrant ssh ubuntu2004-7gb`.
6. On VM activate conda environment and run tests command line.

This is a stack trace that I am getting in the crash:
```
Thread 37 "worker.io" received signal SIGABRT, Aborted.
[Switching to Thread 0x7fffd55fa700 (LWP 16109)]
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50      ../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff7c6d859 in __GI_abort () at abort.c:79
#2  0x00007fffdd32bb05 in ray::SpdLogMessage::Flush() ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#3  0x00007fffdd32bb3d in ray::RayLog::~RayLog() () from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#4  0x00007fffdcf48b6c in ray::CoreWorkerDirectTaskSubmitter::RequestNewWorkerIfNeeded(std::tuple<int, std::vector<ray::ObjectID, std::allocator<ray::ObjectID> >, ray::ActorID> const&, ray::rpc::Address const*)::{lambda(ray::Status const&, ray::rpc::RequestWorkerLeaseReply const&)#1}::operator()(ray::Status const&, ray::rpc::RequestWorkerLeaseReply const&) const ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#5  0x00007fffdcf93dd5 in ray::rpc::ClientCallImpl<ray::rpc::RequestWorkerLeaseReply>::OnReplyReceived() ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#6  0x00007fffdce9dacb in std::_Function_handler<void (), ray::rpc::ClientCallManager::PollEventsFromCompletionQueue(int)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#7  0x00007fffdd2daa08 in boost::asio::detail::completion_handler<std::function<void ()> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#8  0x00007fffdd3e09a1 in boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#9  0x00007fffdd3e0ad1 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#10 0x00007fffdd3e25d0 in boost::asio::io_context::run() ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#11 0x00007fffdce9b895 in ray::CoreWorker::RunIOService() ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#12 0x00007fffdd685d10 in execute_native_thread_routine ()
   from /home/vagrant/miniconda3/envs/modin/lib/python3.8/site-packages/ray/_raylet.so
#13 0x00007ffff7fa8609 in start_thread (arg=<optimized out>) at pthread_create.c:477
#14 0x00007ffff7d6a293 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

This fixes https://github.com/ray-project/ray/issues/15990 by handling tasks that request the same object multiple times correctly. The particular edge case happens if we have multiple tasks requesting the same object multiple times.

I was not able to easily reproduce this in a Python unit test, so a C++ unit test will have to do for now. It is easily reproducible in Modin CI tests.

### CODE REVIEW

File: src/ray/object_manager/pull_manager.cc [hunk 1]
```diff
@@ -408,10 +409,14 @@ void PullManager::TryToMakeObjectLocal(const ObjectID &object_id) {
     return;
   }
 
-  // The object waiting for local pull retry; abort.
+  // The object is no longer needed; abort.
   auto it = object_pull_requests_.find(object_id);
-  RAY_CHECK(it != object_pull_requests_.end());
+  if (it != object_pull_requests_.end()) {
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.cc:414]: Why the change here? I think we should try to keep the invariant that an object that was in the active pull requests should always be in this map too.

File: src/ray/object_manager/pull_manager.cc [hunk 2]
```diff
@@ -335,6 +335,7 @@ std::vector<ObjectID> PullManager::CancelPull(uint64_t request_id) {
       // here could be a no-op.
       it->second.bundle_request_ids.erase(bundle_it->first);
       if (it->second.bundle_request_ids.empty()) {
+        active_object_pull_requests_.erase(obj_id);
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.cc:338]: Why the change?

File: src/ray/object_manager/pull_manager.cc (hunk 1 above)
Comment (ericl) [reply src/ray/object_manager/pull_manager.cc:414]: The check is failing. I was not able to reproduce the reason why, but removing this add adding a defensive remove above also fixes the problem.

In general, I think we should prefer to write code in a more defensive style (correct even if invariants are violated), if possible.

File: src/ray/object_manager/pull_manager.cc (hunk 2 above)
Comment (ericl) [reply src/ray/object_manager/pull_manager.cc:338]: Defensive removal.

File: src/ray/object_manager/pull_manager.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:414]: I see. Can you log a warning, though? This case really should not occur so if it does, it's likely a bug.

File: src/ray/object_manager/pull_manager.cc [hunk 3]
```diff
@@ -25,20 +25,29 @@ PullManager::PullManager(
 uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_bundle,
                            bool is_worker_request,
                            std::vector<rpc::ObjectReference> *objects_to_locate) {
+  // To avoid edge cases dealing with duplicated object ids in the bundle,
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:28]: This also fixes an issue where we failed to issue a pull since num_objects_missing_sizes was calculated incorrectly with duplicate object ids.

File: src/ray/object_manager/pull_manager.cc [hunk 4]
```diff
@@ -125,17 +134,18 @@ void PullManager::DeactivatePullBundleRequest(
   for (const auto &ref : request_it->second.objects) {
     absl::MutexLock lock(&active_objects_mu_);
     auto obj_id = ObjectRefToId(ref);
-    if (!active_object_pull_requests_[obj_id].erase(request_it->first)) {
-      // If a bundle contains multiple duplicated object ids, the active pull request
-      // could've been already removed. Then do nothing.
+    auto it = active_object_pull_requests_.find(obj_id);
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:137]: The use of the `[]` operator caused the errant CHECK failure, since it default-allocated an empty set as the value.

File: src/ray/object_manager/pull_manager.cc (hunk 1 above)
Comment (ericl) [reply src/ray/object_manager/pull_manager.cc]: I did a bit more digging and fixed the root cause bug (see other comments), which the defensive erase above was also handling.

**Review by rkooo567 — APPROVED** [review]

File: src/ray/object_manager/pull_manager.cc [hunk 5]
```diff
@@ -125,17 +134,18 @@ void PullManager::DeactivatePullBundleRequest(
...
+    if (it == active_object_pull_requests_.end() ||
+        !it->second.erase(request_it->first)) {
+      // The object is already deactivated, no action is required.
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:140]: Technically this isn't needed, but leaving this in just in case.

**Review by stephanie-wang — APPROVED** [review]

**Comment by stephanie-wang** [comment]
Looks like there is a build error on osx.

**Comment by ericl** [comment]
Windows tests is existing flaky; also passed previously.

**Comment by ericl** [comment]
This will be picked into 1.4

**Comment by rkooo567** [comment]
cc @devin-petersohn (I also followed up with him in slack)
