### PR TITLE
[Core] Support != Filter in GCS for Task State API

### LINKED ISSUE #48251: [Dashboard] Fix listing APIs to avoid truncating at 10k entities
### What happened + What you expected to happen

Currently, listing APIs in StateHead work along the following lines

1. Fetch *all* entities from GCS (with some exceptions)
2. Filter matching ones inside StateManager component

This is making these APIs practically useless for cases when we exceed the default GCS threshold of 10k entities -- meaning that if your cluster has 100k tasks, GCS will only return 10k of them when querying listing API.

We need to make sure:

1. We're NOT truncating the data at the source, instead we're applying limit on the final resulting set
2. GCS supports proper common filtering ('=', '!=', etc)

### Versions / Dependencies

2.38

### Reproduction script

Spin up 20k tasks
Try to find tasks that are currently anything but `FINISHED`

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by MengjinYan**
## Why are these changes needed?

Today, when the State API handles the list tasks requests with filters, it will:
1. Fetch the task events from GCS with certain "=" filters
2. With the events fetched from GCS, further filtering them with rest of the specified filters

At the same time, when fetching events from GCS, there is a 10k limit to avoid overwhelming the service. 

Therefore, when there are more than 10k task events after filtering on GCS, the events will be truncated and incomplete information will be returned.

To fundamentally fix the issue, the idea is to move the whole task events pipeline outside of GCS. 

This PR is a short term fix to add support for more filters in GCS so that the return result set can be smaller than 10k. To be specific, this PR:
* Added "!=" filter support for the existing filter fields (task id, actor id, job id, task name, state) in GCS
* Modified & add tests for the new logic

## Related issue number
Closes #48251

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 1]
```diff
@@ -407,18 +417,47 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
...
+      for (const auto &task_filter_obj : filters.task_filters()) {
+        if (task_filter_obj.predicate() == rpc::FilterPredicate::NOT_EQUAL &&
+            TaskID::FromBinary(task_event.task_id()) ==
+                TaskID::FromBinary(task_filter_obj.task_id())) {
+          return false;
+        }
+      }
+    }
+
+    if (filters.has_job_filter() &&
```
Comment (MengjinYan) [inline src/ray/gcs/gcs_server/gcs_task_manager.cc:430]: I might miss some historical context. Here is seem that the original logic assumes only either task id or job id will be specified. So I updated here to make sure that both filters can be applied

File: src/ray/protobuf/gcs_service.proto [hunk 2]
```diff
@@ -437,6 +437,11 @@ enum GcsServiceFailureType {
   GCS_SERVER_RESTART = 1;
 }
 
+enum FilterPredicate {
+  EQUAL = 0;
```
Comment (dentiny) [inline src/ray/protobuf/gcs_service.proto:441]: nit: protobuf encourages to declare unspecified default value: https://protobuf.dev/programming-guides/dos-donts/#unspecified-enum, though for us it's less of a problem since we don't have different releases between client and server

File: src/ray/protobuf/gcs_service.proto [hunk 3]
```diff
@@ -767,18 +772,59 @@ message AddTaskEventDataReply {
...
+    // The filter to filter on the actor id of a task.   
+    message ActorIdFilter {
+      // The prediate of the filter.
+      FilterPredicate predicate = 1;
+      // The actor id to filter on.
+      bytes actor_id = 2;
+    }
+
+    // The filter to filer on the task name.
+    message NameFilter {
```
Comment (dentiny) [inline src/ray/protobuf/gcs_service.proto:801]: nit: TaskNameFilter? I'm not sure if we will have job name as well

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 4]
```diff
@@ -407,18 +417,47 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
       return false;
     }
 
-    if (filters.has_actor_id() && task_event.task_info().has_actor_id() &&
-        ActorID::FromBinary(task_event.task_info().actor_id()) !=
-            ActorID::FromBinary(filters.actor_id())) {
+    if (filters.task_filters_size() > 0) {
+      for (const auto &task_filter_obj : filters.task_filters()) {
+        if (task_filter_obj.predicate() == rpc::FilterPredicate::NOT_EQUAL &&
+            TaskID::FromBinary(task_event.task_id()) ==
```
Comment (dentiny) [inline src/ray/gcs/gcs_server/gcs_task_manager.cc:423]: Curious, does plain string comparison work here?

Comment (rynewang) [reply src/ray/gcs/gcs_server/gcs_task_manager.cc:423]: we prefer typed ids.

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 5]
```diff
@@ -396,7 +405,8 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
   int64_t num_limit_truncated = 0;
 
   // A lambda filter fn, where it returns true for task events to be included in the
-  // result. Task ids and job ids are already filtered by the storage with indexing above.
+  // result. Task ids or job ids with equal predicate are already filtered by the
+  // storage with indexing above.
```
Comment (rynewang) [inline src/ray/gcs/gcs_server/gcs_task_manager.cc:409]: I tried to reduce some boilerplate by doing this:

1. define `apply_op` and alike to treat the ==EQUAL or ==NOT_EQUAL thing
2. use it in filter_fn.

Please see if this makes sense. (did not build it, you may want to tweak a bit)



```cpp

template <typename T>
bool apply_op(const T& lhs, rpc::FilterPredicate op, const T& rhs) {
  switch (op) {
  case rpc::FilterPredicate::EQUAL:
    return lhs == rhs;
  case rpc::FilterPredicate::NOT_EQUAL:
    return lhs != rhs;
  default:
    RAY_LOG(FATAL) << "Unknown filter predicate: " << op;
  }
}


bool apply_op_ignore_case(std::string_view lhs,
                          rpc::FilterPredicate op,
                          std::string_view rhs) {
  bool equals = absl::EqualsIgnoreCase(lhs, rhs);
  switch (op) {
  case rpc::FilterPredicate::EQUAL:
    return equals;
  case rpc::FilterPredicate::NOT_EQUAL:
    return !equals;
  default:
    RAY_LOG(FATAL) << "Unknown filter predicate: " << op;
  }
}
```

```cpp

  // A lambda filter fn, where it returns true for task events to be included in the
  // result. Task ids and job ids are already filtered by the storage with indexing above.
  auto filter_fn = [&filters](const rpc::TaskEvents &task_event) {
    if (!task_event.has_task_info()) {
      // Skip task events w/o task info.
      return false;
    }
    if (filters.exclude_driver() &&
        task_event.task_info().type() == rpc::TaskType::DRIVER_TASK) {
      return false;
    }

    // Job filter
    if (filters.has_job_filter() && !apply_op(
        JobID::FromBinary(task_event.job_id()),
        filters.job_filter().predicate(),
        JobID::FromBinary(filters.job_filter().job_id()))) {
      return false;
    }

    // Tasks filters (OR semantics)
    if (filters.task_filters_size() > 0) {
      if (!std::any_of(filters.task_filters().begin(),
                       filters.task_filters().end(),
                       [&task_event](const auto &task_filter) {
                         return apply_op(TaskID::FromBinary(task_event.task_id()),
                                       task_filter.predicate(),
                                       TaskID::FromBinary(task_filter.task_id()));
                       })) {
        return false;
      }
    }

    // Actor filter
    if (filters.has_actor_filter() && task_event.task_info().has_actor_id() &&
        !apply_op(ActorID::FromBinary(task_event.task_info().actor_id()),
                  filters.actor_filter().predicate(),
                  ActorID::FromBinary(filters.actor_filter().actor_id()))) {
      return false;
    }

    // Name filter
    if (filters.has_name_filter()) {
      if (!apply_op_ignore_case(
              task_event.task_info().name(),
              filters.name_filter().predicate(),
              filters.name_filter().name())) {
        return false;
      }
    }

    // State filter
    if (filters.has_state_filter()) {
      const google::protobuf::EnumDescriptor *task_status_descriptor =
          ray::rpc::TaskStatus_descriptor();

      // Figure out the latest state of a task
      ray::rpc::TaskStatus state = ray::rpc::TaskStatus::NIL;
      if (task_event.has_state_updates()) {
        for (int i = task_status_descriptor->value_count() - 1; i >= 0; --i) {
          if (task_event.state_updates().state_ts_ns().contains(
                  task_status_descriptor->value(i)->number())) {
            state = static_cast<ray::rpc::TaskStatus>(
                task_status_descriptor->value(i)->number());
            break;
          }
        }
      }

      if (!apply_op_ignore_case(
              task_status_descriptor->FindValueByNumber(state)->name(),
              filters.state_filter().predicate(),
              filters.state_filter().state())) {
        return false;
      }
    }

    return true;
  };

```

File: src/ray/protobuf/gcs_service.proto (hunk 2 above)
Comment (MengjinYan) [reply src/ray/protobuf/gcs_service.proto:441]: Good point! Will add a default value. 

At the same time, I would think the backward compatibility is already broken when the format of the request is updated. And I'm hoping the format change in this PR can be extensible enough so that all the future updates can backward compatible changes.

File: src/ray/protobuf/gcs_service.proto [hunk 6]
```diff
@@ -767,18 +772,59 @@ message AddTaskEventDataReply {
...
+    message StateFilter {
+      // The predicate of the filter.
+      FilterPredicate predicate = 1;
+      // The latest state of the task to filter on.
+      string state = 2;
+    }
+
+    // Task events filter by a job id.
+    optional JobIdFilter job_filter = 1;
+    // Task events filter by a set of task filters.
```
[the remark this answers is not in the document]
Comment (MengjinYan) [reply src/ray/protobuf/gcs_service.proto:818]: Will add the comment.

Agree that `== TASK1 OR != TASK2` would be weird. At the same time, today, we don't have a constraint on how the filter can be set and it is possible for the user to set a filter like that. I'll need to also add the constraints and make it clear in the docs to avoid confusions.

File: src/ray/protobuf/gcs_service.proto (hunk 2 above)
Comment (rynewang) [reply src/ray/protobuf/gcs_service.proto:441]: we don't need backward compatibility in this. We do need to know if a filter is "not set" or "EQUAL" but we already can test that. So I guess current enum is OK

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 7]
```diff
@@ -446,7 +490,7 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
   };
 
   int64_t num_filtered = 0;
-  for (auto itr = task_events.rbegin(); itr != task_events.rend(); ++itr) {
+  for (auto itr = task_events->rbegin(); itr != task_events->rend(); ++itr) {
```
[the remark this answers is not in the document]
Comment (rynewang) [reply src/ray/gcs/gcs_server/gcs_task_manager.cc:493]: https://www.boost.org/doc/libs/1_76_0/libs/range/doc/html/range/reference/adaptors/introduction.html

```
#include <boost/range/adaptor/reversed.hpp>

    // Using boost::adaptors::reverse for range-based loop
    for (const auto& task_event : task_events | boost::adaptors::reversed) {
        std::cout << num << " ";
    }
```

idk this works, did not build it - if this is not, you can keep the current for loop.

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 8]
```diff
@@ -361,24 +363,31 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
...
+    const auto job_id = JobID::FromBinary(filters.job_filter().job_id());
     task_events = task_event_storage_->GetTaskEvents(job_id);
     // Populate per-job data loss.
     if (task_event_storage_->HasJob(job_id)) {
       const auto &job_summary = task_event_storage_->GetJobTaskSummary(job_id);
       reply->set_num_profile_task_events_dropped(job_summary.NumProfileEventsDropped());
       reply->set_num_status_task_events_dropped(job_summary.NumTaskAttemptsDropped());
     }
-  } else {
+  }
```
[the remark this answers is not in the document]
Comment (MengjinYan) [reply src/ray/gcs/gcs_server/gcs_task_manager.cc:388]: Here it is to handle the case where only "not equal" filters are there in the task filters. 

In this case, we cannot get the events from specifying the list of task IDs but need to get the events through getting all the task events. 

I'll add comments to clarify the logic.

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 9]
```diff
@@ -361,24 +363,31 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
   RAY_LOG(DEBUG) << "Getting task status:" << request.ShortDebugString();
 
   // Select candidate events by indexing if possible.
-  std::vector<rpc::TaskEvents> task_events;
+  std::optional<std::vector<rpc::TaskEvents>> task_events;
```
[the remark this answers is not in the document]
Comment (MengjinYan) [reply src/ray/gcs/gcs_server/gcs_task_manager.cc:366]: The `std::optional` here is needed to differentiate the case where there is no valid event for the filter and the case where the `task_events` are not assigned. 

In the case when the task filters are specified but all filters are "not equal" filters, the `task_events` will not be assigned within the `filters.task_filters_size() > 0` statement and should be assigned later with all the task events on GCS. Checking whether the `task_events` has value will make sure the assignment handles the above case and avoid reassignment in the empty vector situation due to the existing task/job filter.

File: src/ray/protobuf/gcs_service.proto (hunk 2 above)
Comment (MengjinYan) [reply src/ray/protobuf/gcs_service.proto:441]: That's right. I think backward compatibility is not needed for now. 

At the same time, if ever we want to separate different components (API server and GCS in this case) into different products, compatibility will be a concern at that time.

File: src/ray/protobuf/gcs_service.proto (hunk 6 above)
[the remark this answers is not in the document]
Comment (MengjinYan) [reply src/ray/protobuf/gcs_service.proto:818]: Actually, I have some more findings after testing with the list ask state API. 

From what I see, although in the GCS processing logic, the task_ids are OR together, in the `transform` logic in the `list_tasks` function: 
https://github.com/ray-project/ray/blob/b3b6f2cc5989b012026c0046fdbd28f6b8e3a85a/python/ray/dashboard/state_aggregator.py#L461
All the filters will be processed again with `AND` sematics. 

This means that, with today's logic, it seems that the task ids are actually AND together. And from a code search, I don't see any logic is using the GCS `HandleGetTaskEvents`. If that's the case, I think we should fix the internal GCS API to be aligned with the existing publish API logic using `AND` semantics. 

@rynewang Not sure if I missed any historical context and wondering what's your take on it?

[the remark this answers is not in the document]
Comment (MengjinYan) [reply src/ray/protobuf/gcs_service.proto:818]: Synced offline with @jjyao. We should make the GCS behavior be consistent with the behavior in the API server which is to make all task_ids AND together. Will update the code.

[the remark this answers is not in the document]
Comment (rickyyx) [reply src/ray/protobuf/gcs_service.proto:818]: I think sticking with `AND` is fine given we don't really have a way to specify `OR` from the frontend yet without some complex query parsing. 

I guess if we do with `AND`, what's the usecase there's repeated id filters? Guess if we don't do `OR` here, we just need a single task id filter?

File: python/ray/tests/test_state_api.py [hunk 10]
```diff
@@ -1007,6 +1009,86 @@ async def test_api_manager_list_tasks(state_api_manager):
...
+
+    assert filters_arg.HasField("name_filter")
+    assert filters_arg.name_filter.name == test_task_name
+    assert filters_arg.name_filter.predicate == FilterPredicate.EQUAL
+
+    assert filters_arg.HasField("state_filter")
+    assert filters_arg.state_filter.state == test_state
+    assert filters_arg.state_filter.predicate == FilterPredicate.EQUAL
+
+    assert filters_arg.exclude_driver == input_exclude_driver
```
Comment (rickyyx) [inline python/ray/tests/test_state_api.py:1089]: nice test!

**Review by rickyyx — APPROVED** [review]
LGTM! 

nit: I also believe the filter lambda refactoring ruiyang suggests will make things cleaner and more testable.

File: src/ray/protobuf/gcs_service.proto (hunk 6 above)
[the remark this answers is not in the document]
Comment (MengjinYan) [reply src/ray/protobuf/gcs_service.proto:818]: I think the `AND` semantics should still make sense in the "!=" scenario when the same task id is specified multiple times and the user want to filter out multiple task ids. 

At the same time, it makes me think whether we want to make other filters also have multiple filters so that more filters can be pushed down to GCS.

**Comment by jjyao** [comment]
@rickyyx can you take another look since a significant change is made after your last review.

File: python/ray/dashboard/state_aggregator.py [hunk 11]
```diff
@@ -463,6 +463,16 @@ def transform(reply) -> ListApiResponse:
             Transforms from proto to dict, applies filters, sorts, and truncates.
             This function is executed in a separate thread.
             """
+            # In the error case
```
Comment (rickyyx) [inline python/ray/dashboard/state_aggregator.py:466]: nit: should we do the error checking outside of this  func?

File: python/ray/util/state/state_manager.py [hunk 12]
```diff
@@ -279,6 +279,28 @@ async def get_all_actor_info(
...
 
+    def add_task_filter(
+        self,
+        existing_val: Union[JobID, ActorID, TaskID, str],
+        new_val: Union[JobID, ActorID, TaskID, str],
+        filter_predicate: int,
+        filter_obj,
+        filter_field,
+        val_field_name: str,
+    ) -> Tuple[bool, bool]:
```
Comment (rickyyx) [inline python/ray/util/state/state_manager.py:290]: nit: doc args and return values?

File: python/ray/util/state/state_manager.py [hunk 13]
```diff
@@ -292,40 +314,104 @@ async def get_all_task_info(
...
+            filter_predicate = None
             if predicate == "=":
-                filterPredicate = FilterPredicate.EQUAL
+                filter_predicate = FilterPredicate.EQUAL
             elif predicate == "!=":
-                filterPredicate = FilterPredicate.NOT_EQUAL
+                filter_predicate = FilterPredicate.NOT_EQUAL
             else:
                 # We only support EQUAL and NOT_EQUAL predicate for source side
                 # filtering.
```
Comment (rickyyx) [inline python/ray/util/state/state_manager.py:332]: should we just raise here?

File: python/ray/util/state/state_manager.py [hunk 14]
```diff
@@ -292,40 +314,104 @@ async def get_all_task_info(
...
                 continue
 
             if key == "actor_id":
-                req_filters.actor_filter.actor_id = ActorID(
-                    hex_to_binary(value)
-                ).binary()
-                req_filters.actor_filter.predicate = filterPredicate
+                is_empty_reply, new_actor_id = self.add_task_filter(
```
Comment (rickyyx) [inline python/ray/util/state/state_manager.py:336]: what does `is_empty_reply` here mean?

File: python/ray/util/state/state_manager.py [hunk 15]
```diff
@@ -292,40 +314,104 @@ async def get_all_task_info(
...
+                )
+
+                if new_state:
+                    state = new_state
+
             else:
                 continue
 
+            if is_empty_reply:
+                # return empty reply when more than 2 equal filters with the same filter
```
Comment (rickyyx) [inline python/ray/util/state/state_manager.py:404]: hmm, i wonder if we could do the checking earlier than here? Instead of checking if early returns are possible while building the actual protobuf filter, could we do the checking on `filters` object?

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 16]
```diff
@@ -372,18 +407,31 @@ void GcsTaskManager::HandleGetTaskEvents(rpc::GetTaskEventsRequest request,
...
+      task_events = task_event_storage_->GetTaskEvents(job_id);
+
+      // Populate per-job data loss.
+      if (task_event_storage_->HasJob(job_id)) {
+        const auto &job_summary = task_event_storage_->GetJobTaskSummary(job_id);
+        reply->set_num_profile_task_events_dropped(job_summary.NumProfileEventsDropped());
+        reply->set_num_status_task_events_dropped(job_summary.NumTaskAttemptsDropped());
+      }
+    } else if (job_ids.size() > 1) {
+      task_events = std::vector<rpc::TaskEvents>();
```
Comment (rickyyx) [inline src/ray/gcs/gcs_server/gcs_task_manager.cc:434]: just nit: i think for future readability, we could probably split this part from the routine below. Logically, there are two types of filters:
1. filter that we could use index: equal filter with indexes on them. 
2. filter that has to be applied per task (task event): all remaining filters.

Having a routine that split filters into `filters_with_index` and `per_task_filter` might help with both readability and performance I think (the perf gain is probably not too much) because we don't need to apply some per element on the selected tasks.

**Review by rickyyx — COMMENTED** [review]
A couple of nits only. 

The main comment is on the `add_task_filter` routine where I think we could separate the filter building from early return filters checking, which is currently coupled in the function.

**Comment by rickyyx** [comment]
Also, I wonder if we have plans in followup to make it expose to users (in high level apis/docs and other places?)

File: python/ray/util/state/state_manager.py (hunk 15 above)
Comment (MengjinYan) [reply python/ray/util/state/state_manager.py:404]: Good point! If all filters are with AND semantics, we should be able to move the early return to a more general location. Let me check it out.

File: python/ray/util/state/common.py [hunk 17]
```diff
@@ -163,6 +164,30 @@ def __post_init__(self):
                     "Available predicates: =, !=."
                 )
 
+    def has_conflicting_filters(self) -> bool:
+        # Check the filters in the ListApiOptions conflicts. Specifically for:
```
Comment (rickyyx) [inline python/ray/util/state/common.py:168]: nit: potentially a `=` with the same value and a `!=` with the same value would also result in empty results on the same key i guess - but given this is an optimization and the doc is clear. I think it's fine.

**Review by rickyyx — APPROVED** [review]
Thanks for the great work!

File: python/ray/util/state/common.py (hunk 17 above)
Comment (MengjinYan) [reply python/ray/util/state/common.py:168]: Good point! Added a todo in the PR for the optimization
