### PR TITLE
use an agent-id rather than the process PID

### LINKED ISSUE #24361: [Core] ray.exceptions.LocalRayletDiedError: The task's local raylet died. Check raylet.out for more information.
### What happened + What you expected to happen

I was using ray as a dependency to run the Modin library in  Win 11 however I am getting Raylet error

### Versions / Dependencies

OS: Windows 11
Python: 3.7
Ray Version: 1.12.0

Ray agent failed
[dashboard.log](https://github.com/ray-project/ray/files/8596197/dashboard.log)
[dashboard_agent.log](https://github.com/ray-project/ray/files/8596198/dashboard_agent.log)

### Reproduction script

```
df.head(20):

Unnamed: 0                       game score home_odds draw_odds away_odds country                 league             datetime
0            0  Sport Recife - Imperatriz   2:2      1.36      4.31      7.66  Brazil  Copa do Nordeste 2020  2020-02-07 00:00:00
1            1           ABC - America RN   2:1      2.62      3.30      2.48  Brazil  Copa do Nordeste 2020  2020-02-02 22:00:00
2            2  Frei Paulistano - Nautico   0:2      5.19      3.58      1.62  Brazil  Copa do Nordeste 2020  2020-02-02 00:00:00
3            3    Botafogo PB - Confianca   1:1      2.06      3.16       3.5  Brazil  Copa do Nordeste 2020  2020-02-02 22:00:00
4            4          Fortaleza - Ceara   1:1      2.19      2.98      3.38  Brazil  Copa do Nordeste 2020  2020-02-02 22:00:00
5            5             River-PI - CSA   3:1      3.41      3.07       2.1  Brazil  Copa do Nordeste 2020  2020-02-02 20:00:00
6            6     Sport Recife - Vitoria   1:1      1.92      3.20      3.93  Brazil  Copa do Nordeste 2020  2020-02-02 20:00:00
7            7           CRB - Santa Cruz   1:0      2.22      3.06      3.18  Brazil  Copa do Nordeste 2020  2020-01-29 23:30:00
8            8         Bahia - Imperatriz   2:0      1.31      4.75      8.55  Brazil  Copa do Nordeste 2020  2020-01-29 00:00:00
9            9    Ceara - Frei Paulistano   2:2       1.2      5.43     12.94  Brazil  Copa do Nordeste 2020  2020-01-26 22:00:00
10          10            Confianca - ABC   1:0      2.09      3.01      3.58  Brazil  Copa do Nordeste 2020  2020-01-26 00:00:00
11          11   America RN - Botafogo PB   0:0      2.14      3.30      3.11  Brazil  Copa do Nordeste 2020  2020-01-26 22:00:00
12          12         CSA - Sport Recife   0:1      2.63      3.04      2.62  Brazil  Copa do Nordeste 2020  2020-01-26 22:00:00
13          13         Santa Cruz - Bahia   0:0      3.72      3.22      1.96  Brazil  Copa do Nordeste 2020  2020-01-26 20:00:00
14          14        Vitoria - Fortaleza   0:0      3.13      3.02      2.27  Brazil  Copa do Nordeste 2020  2020-01-26 20:00:00
15          15         Nautico - River-PI   1:1      1.44      4.06      6.19  Brazil  Copa do Nordeste 2020  2020-01-23 23:30:00
16          16           Imperatriz - CRB   2:1      2.34      2.94      3.08  Brazil  Copa do Nordeste 2020  2020-01-21 23:00:00
17          17       Nautico - Campinense   2:0       1.4      4.18      7.26  Brazil  Copa do Nordeste 2020  2019-05-16 00:30:00
18          18          CRB - Juazeirense   2:1       1.4      4.19      7.32  Brazil  Copa do Nordeste 2020  2019-05-14 23:00:00
19          19             ABC - AE Altos   2:0      1.44      3.83      7.02  Brazil  Copa do Nordeste 2020  2019-05-08 22:30:00
```

```
import os
import ray
ray.init()
os.environ["MODIN_ENGINE"] = "ray"
import modin.pandas as pd
df = pd.read_csv(r"data.csv", low_memory=False)
df['game'] = df['game'].astype(str).str.replace('(\(\w+\))', '', regex=True)
df['league'] = df['league'].astype(str).str.replace('(\s\d+\S\d+)$', '', regex=True)
df['league'] = df['league'].astype(str).str.replace('é', 'e', regex=True)
df['game'] = df['game'].astype(str).str.replace('(\s\d+\S\d+)$', '', regex=True)
df[['home_team', 'away_team']] = df['game'].str.split(' - ', expand=True, n=1)
df[['home_score', 'away_score']] = df['score'].str.split(':', expand=True)
df['away_score'] = df['away_score'].astype(str).str.replace('[a-zA-Z\s\D]', '', regex=True)
print (df.head())
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by mattip**
## Why are these changes needed?
When using ray inside a virtualenv on windows, `python.exe` as reported by `sys.executable` is a PEP397 launcher to the actual python as reported by `os.getpid()`:
```
>>> import sys, os, psutil
>>> >>> print(sys.executable)
C:\temp\issue24361\Scripts\python.exe
>>> os.getpid()
2208
>>> child = psutil.Process(2208)
>>> child.cmdline()
['C:\\oss\\CPython38\\python.exe']
>>> child.parent().cmdline()
['C:\\temp\\issue24361\\Scripts\\python.exe']
>>> child.parent().pid
6424
```

When the `agent_manager` launches the agent process via `Process::Process()`, it gets the PID of the launcher process (6424), which is what is expected as an ID when registering the agent in the gRPC callback. But inside `agent.py`, the child process reports the PID via `os.getpid()`, which is 2208, and this is the wrong PID to register the agent.

The solution proposed here is another version of #24905 that creates a `int agent_id = rand();` before starting the python process, and passes the `agent_id` to the process.

## Related issue number
Closes #24361, #23945

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by mattip** [comment]
@rkooo567 this replaces the other PR, which I closed.

File: src/ray/raylet/agent_manager.cc [hunk 1]
```diff
@@ -55,27 +55,34 @@ void AgentManager::StartAgent() {
     RAY_LOG(INFO) << "Not starting agent, the agent command is empty.";
     return;
   }
```
Comment (mattip) [inline src/ray/raylet/agent_manager.cc:57]: I moved the stanza below to after adding the new arguments so it prints out everything

File: src/ray/raylet/agent_manager.cc [hunk 2]
```diff
@@ -56,58 +56,65 @@ void AgentManager::StartAgent() {
...
+    RAY_LOG(INFO) << "Monitor agent process with id " << agent_id << ", register timeout "
                   << RayConfig::instance().agent_register_timeout_ms() << "ms.";
     auto timer = delay_executor_(
-        [this, child]() mutable {
-          if (agent_pid_ != child.GetId()) {
-            RAY_LOG(WARNING) << "Agent process with pid " << child.GetId()
-                             << " has not registered. ip " << agent_ip_address_
-                             << ", pid " << agent_pid_;
+        [this, child, agent_id]() mutable {
+          if (agent_pid_ != agent_id) {
```
Comment (rkooo567) [inline src/ray/raylet/agent_manager.cc:104]: Instead of agent_pid_, can we rename it to agent_id_? Since it is not pid anymore.

File: dashboard/agent.py [hunk 3]
```diff
@@ -54,6 +54,7 @@ def __init__(
         raylet_name=None,
         logging_params=None,
         disable_metrics_collection: bool = False,
+        agent_id: int = os.getpid(),
```
Comment (rkooo567) [inline dashboard/agent.py:57]: I think we don't need the default id as pid in this case. Can you remove it?

**Review by rkooo567 — COMMENTED** [review]
This seems a lot better! I think we should do 2 additional things.

(1) Remove agent_pid from the gRPC request of `RegisterAgentRequest` since it is not pid anymore
(2) https://github.com/ray-project/ray/blob/0212f5e09516c21cf06f4d88cccafdcdff9f7545/src/ray/raylet/agent_manager.cc#L34 At this code, can you change the code to `agent_id_ = request.agent_id();`?

File: src/ray/raylet/agent_manager.cc [hunk 4]
```diff
@@ -56,58 +56,65 @@ void AgentManager::StartAgent() {
...
-    stream << "Starting agent process with command:";
-    for (const auto &arg : options_.agent_commands) {
-      stream << " " << arg;
-    }
-    RAY_LOG(DEBUG) << stream.str();
-  }
-
-  // Launch the process to create the agent.
-  std::error_code ec;
+  // Create a random agent_id to pass to the child process
```
Comment (rkooo567) [inline src/ray/raylet/agent_manager.cc:59]:
```suggestion
  // Create a random agent_id to pass to the child process. We cannot use pid an id because os.getpid() from the python process is not reliable in Windows. See [Github issue link]
```

**Comment by mattip** [comment]
I refactored all the naming and also tried to improve the error reporting.

File: src/ray/raylet/agent_manager.cc (hunk 2 above)
Comment (mattip) [reply src/ray/raylet/agent_manager.cc]: Done, and improved the error message

File: dashboard/agent.py (hunk 3 above)
Comment (mattip) [reply dashboard/agent.py:57]: Refactored to use a required keyword-only `*` signature.

Comment (rkooo567) [reply dashboard/agent.py:57]: Hmm I might be missing something here, but it still seems to receive os.getpid() as default?

**Review by rkooo567 — APPROVED** [review]
Looks great!!

File: dashboard/agent.py (hunk 3 above)
Comment (mattip) [reply dashboard/agent.py]: Sorry, check now :)

**Comment by rkooo567** [comment]
Failed tests seem unrelated. @mattip can you verify `test_args` failure from Windows is unrelated to your PR?

**Comment by jjyao** [comment]
Looks like StartupToken for worker process :)

**Comment by mattip** [comment]
Can you link to the `test_args` failure? It looks to me like windows is passing...

**Comment by rkooo567** [comment]
Oh I re-ran the test. It is okay to merge I think

**Comment by rkooo567** [comment]
Thanks for addressing the comment :). Pretty happy for the final version of this fix!!
