### PR TITLE
Route core worker ERROR/FATAL logs to driver logs

### LINKED ISSUE #12893: [Logging] Core worker ERRORs/check failures not streamed to drivers.
### What is the problem?

This probably didn't work for a long time, but we should add this feature so that users won't lose core worker logs. 

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by ericl**
## Why are these changes needed?

Currently, core worker ERROR and FATAL logs are sent to `python-core-worker-*` files in /tmp/ray. This makes it hard to detect error conditions and check failures, as the user only gets a message to "check logs".

This change configures the spdlog to also send err+ message unconditionally to the stderr, which means the normal log routing machinery picks it up.

## Related issue number

Closes https://github.com/ray-project/ray/issues/12893

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -570,13 +570,13 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
           // Retry after a delay to emulate the existing Raylet reconstruction
           // behaviour. TODO(ekl) backoff exponentially.
           uint32_t delay = RayConfig::instance().task_retry_delay_ms();
-          RAY_LOG(ERROR) << "Will resubmit task after a " << delay
-                         << "ms delay: " << spec.DebugString();
+          RAY_LOG(INFO) << "Will resubmit task after a " << delay
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc:573]: Avoid excess log spam since we print a message elsewhere on retry already.

**Review by scv119 — APPROVED** [review]
