### PR TITLE
Auto discover dashboard agent port

### LINKED ISSUE #17498: new dashboard agent port conflict issues
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 3.7

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

Users are getting a few different error messages, this is one that’s spamming me a lot:
```
(pid=4670) (raylet, ip=...) E0802 07:40:46.542383278   63998 server_chttp2.cc:49]        {"created":"@1627890046.542339446","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":872,"referenced_errors":[{"created":"@1627890046.542335288","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":340,"referenced_errors":[{"created":"@1627890046.542316804","description":"Address family not supported by protocol","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":446,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:59332"},{"created":"@1627890046.542334837","description":"Unable to configure socket","fd":19,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":216,"referenced_errors":[{"created":"@1627890046.542332583","description":"Address already in use","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":190,"os_error":"Address already in use","syscall":"bind"}]}]}]}
(pid=4670) (raylet, ip=...) Traceback (most recent call last):
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 381, in <module>
(pid=4670) (raylet, ip=...)     raise e
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 366, in <module>
(pid=4670) (raylet, ip=...)     logging_params=logging_params)
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/ray/new_dashboard/agent.py", line 94, in __init__
(pid=4670) (raylet, ip=...)     f"[::]:{self.dashboard_agent_port}")
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/aio/_server.py", line 84, in add_insecure_port
(pid=4670) (raylet, ip=...)     address, self._server.add_insecure_port(_common.encode(address)))
(pid=4670) (raylet, ip=...)   File "/opt/conda/lib/python3.7/site-packages/grpc/_common.py", line 166, in validate_port_binding_result
(pid=4670) (raylet, ip=...)     raise RuntimeError(_ERROR_MESSAGE_PORT_BINDING_FAILED % address)
```

Also, --include-dashboard=False does not flag this off.

cc @fyrestone @rkooo567

### PR DESCRIPTION
**Pull request by fyrestone**
- raylet updates the dashboard agent address to internal kv store.
- The metrics reporting logic auto find the latest dashboard agent address in GCS / raylet / core worker.
- Remove the `metrics_agent_port` argument from GCS / raylet / core worker.

## Related issue number

Closes https://github.com/ray-project/ray/issues/17498

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
> Remove the metrics_agent_port argument from GCS / raylet / core worker.

We should avoid this. It is already documented, and it can break many people's prod setup. Can keep this option?

**Comment by fyrestone** [comment]
> metrics_agent_port

The `metrics_agent_port` is reserved in the `RayParams`, user can set the dashboard agent port for the docker. The option is removed from the cmdline of GCS / raylet / core worker. BWT, where is it documented? I can't find it.

**Comment by rkooo567** [comment]
@fyrestone Ah, this is metrics export port, not agent. 

One question I have is that is `metrics_agent_port` needs to be accessed by other machines? I am asking it because there are many users who have port restriction (e.g., they need to whitelist available ports ahead of time). If it is the case, we should expose this option for them.

**Comment by fyrestone** [comment]
> @fyrestone Ah, this is metrics export port, not agent.
> 
> One question I have is that is `metrics_agent_port` needs to be accessed by other machines? I am asking it because there are many users who have port restriction (e.g., they need to whitelist available ports ahead of time for security reasons). If it is the case, we should expose this option for them. (I will also review it next week)

Good question. The `metrics_agent_port` is generated from the `Node._get_cached_port` in node.py: https://github.com/ray-project/ray/blob/master/python/ray/node.py#L221 before this PR.

I think we can provide an option `--dashboard-agent-port` in scripts.py just similar to `--dashboard-port`. Then, user can set a fixed port for the dashboard agent gRPC server, and all other components (GCS / raylet / core worker) will get the port from the interval kv store automatically.

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -155,6 +157,37 @@ CoreWorkerProcess::CoreWorkerProcess(const CoreWorkerOptions &options)
...
+        absl::MutexLock lock(&gcs_server_address_mutex_);
+        if (gcs_server_address_.second != 0) {
+          address->first = gcs_server_address_.first;
+          address->second = gcs_server_address_.second;
+          return true;
+        }
+        return false;
+      });
+
+  RAY_CHECK_OK(gcs_client_->Connect(io_service_));
```
Comment (simon-mo) [inline src/ray/core_worker/core_worker.cc:189]: hmmm looks like now we are opening up multiple gcs connection from worker. AFAIK, python workers also connects to gcs within its python code. Now this adds separate connection from core worker to gcs server. I think this might be ok for now, but not sure what's the scalability limitation here. cc @rkooo567 @wuisawesome @scv119

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -182,14 +215,36 @@ CoreWorkerProcess::CoreWorkerProcess(const CoreWorkerOptions &options)
...
+    GetAgentAddress(gcs_client_, current_node_id, callback);
+  });
 
   // Initialize event framework.
   if (RayConfig::instance().event_log_reporter_enabled() && !options_.log_dir.empty()) {
     RayEventInit(ray::rpc::Event_SourceType::Event_SourceType_CORE_WORKER,
                  std::unordered_map<std::string, std::string>(), options_.log_dir);
   }
 
+  io_thread_ = std::thread([&] {
```
Comment (simon-mo) [inline src/ray/core_worker/core_worker.cc:235]: we are also adding a new io_thread_ to core worker here. Is this required? maybe there are other io_service_ or context that can be reused? @rkooo567

File: src/ray/raylet/agent_manager.cc [hunk 3]
```diff
@@ -16,25 +16,44 @@
...
-                << ", port: " << agent_port_ << ", pid: " << agent_pid_;
-  reply->set_status(rpc::AGENT_RPC_STATUS_OK);
-  send_reply_callback(ray::Status::OK(), nullptr, nullptr);
+  RAY_LOG(INFO) << "HandleRegisterAgent, ip: " << request.agent_ip_address()
+                << ", port: " << request.agent_port() << ", pid: " << request.agent_pid();
+  json address;
+  address.push_back(request.agent_ip_address());
+  address.push_back(request.agent_port());
+  const std::string address_str = address.dump();
+  put_agent_address_(
```
Comment (simon-mo) [inline src/ray/raylet/agent_manager.cc:38]: can we just put the protobuf in there? no arbitrary json construction and parsing is involved.

**Review by simon-mo — APPROVED** [review]
The overall PR looks good. However I have two main concern:
- This creates a new thread in core worker and open connection to gcs_server. What overhead would it add? 
- Seems like we are putting the address from RegisterAgentRequest -> json -> gcs. Why don't we just put protobuf in gcs?.

File: src/ray/core_worker/core_worker.cc (hunk 1 above)
Comment (fyrestone) [reply src/ray/core_worker/core_worker.cc:189]: For the new thread to loop the gcs client in the core worker, I hope there is a better way. Currently, one core worker process may contains multiple core workers.

- core worker process (this PR add a new thread to loop a new io service in the core worker process)
  - core worker - io service
  - core worker - io service
  - ...
 
The stats is global in a process, it is shared by multiple core workers. The new thread does not cost too much, but it adds one more connection from core worker to the GCS.

File: src/ray/raylet/agent_manager.cc (hunk 3 above)
Comment (fyrestone) [reply src/ray/raylet/agent_manager.cc:38]: Good suggestion. I will change the json to protobuf.

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
Comment (fyrestone) [reply src/ray/core_worker/core_worker.cc:235]: Currently, each core worker binds to a thread and owns one io service. It's more complex to share the core worker io service to the stats (global in a  process).

Comment (fyrestone) [reply src/ray/core_worker/core_worker.cc:235]: @kfstorm Do you have a better solution?

**Comment by rkooo567** [comment]
> I think we can provide an option --dashboard-agent-port in scripts.py just similar to --dashboard-port. Then, user can set a fixed port for the dashboard agent gRPC server, and all other components (GCS / raylet / core worker) will get the port from the interval kv store automatically.

This SGMT. Can you add this to the PR? 

Also about implementation, why don't we just call Put from the raylet, and just publish to the component in the designated IP? I think that can simplify a lot of implementation?

**Comment by fyrestone** [comment]
> > I think we can provide an option --dashboard-agent-port in scripts.py just similar to --dashboard-port. Then, user can set a fixed port for the dashboard agent gRPC server, and all other components (GCS / raylet / core worker) will get the port from the interval kv store automatically.
> 
> This SGMT. Can you add this to the PR?
> 
> Also about implementation, why don't we just call Put from the raylet, and just publish to the component in the designated IP? I think that can simplify a lot of implementation?

I can add an option `--dashboard-agent-port` in this PR, but it makes this PR larger. Also, there is no way to set the dashboard agent port before this PR. Maybe a separate PR for the option is better?

About the implementation, publish the dashboard agent address is much simpler in most cases. But, if a component is not available (down or starting) during the publish, then we have to make the component able to find the latest dashboard agent address after recovery. So, this PR is simpler than publish + pull when recovery.

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
Comment (kfstorm) [reply src/ray/core_worker/core_worker.cc:235]: I think creating a new thread in `CoreWorkerProcess` for the process-scope event loop is reasonable (we already did this internally). However, I do have some concerns about the additional GCS client. Maybe we can open-source our internal approach of sharing a single GCS client among multiple `CoreWorker` instances and the `CoreWorkerProcess` instance.

@simon-mo @fyrestone If you both agree with this, I can create another PR to open-source it.

Comment (fyrestone) [reply src/ray/core_worker/core_worker.cc:235]: @fyrestone Thanks. It sounds good. sharing the GCS client will reduce the connections from core worker to GCS.

**Comment by fyrestone** [comment]
> Yeah I am fine with that! So we need dashboard agent port option and thread safe gcs client?

Yes. I think this PR is ready to be merged.
