### PR TITLE
[core] Output the error log on the driver side if the failed task will still retry

### LINKED ISSUE #49288: [Core] Ray doesn't print retry task errors on the driver
### What happened + What you expected to happen

I ran a Ray Data pipeline that retries some actor task errors.  I observed my pipeline hanging because of retry tasks, but I was confused because I didn't see any errors reported on the driver.

To make it clear why Ray retries actor tasks, it'd be useful if Ray printed retry task errors on the driver. Most users won't know to look at the Ray Core logs.

### Versions / Dependencies

644b5946a82d7cc26982942ec7125e5f97ba34f9

### Reproduction script

```python
import ray

ray.data.DataContext.get_current().actor_task_retry_on_errors = [OSError]


class Embed:
    def __init__(self):
        self._num_attempts = 0

    def __call__(self, batch):
        if self._num_attempts < 3:
            self._num_attempts += 1
            raise OSError("Simulated error")

        return batch


ray.data.range(1).map_batches(Embed, concurrency=1).materialize()
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by Qiaolin-Yu**
## Related issue number
Close #49288

## Why are these changes needed?

If the failed task will still retry, we should print the error log on the driver side; otherwise, it’s not necessary, since ray.get can retrieve it. This is for better observability.

Note that this feature can be disabled by `export RAY_enable_output_error_log_if_still_retry=0`.

Tried the example in the issue
Before this PR:
```
2025-09-11 22:45:16,569  INFO logging.py:295 -- Registered dataset logger for dataset dataset_2_0
2025-09-11 22:45:16,590  INFO streaming_executor.py:159 -- Starting execution of Dataset dataset_2_0. Full logs are in /tmp/ray/session_2025-09-11_22-44-45_753182_597098/logs/ray-data
2025-09-11 22:45:16,590  INFO streaming_executor.py:160 -- Execution plan of Dataset dataset_2_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(Embed)]
Running 0: 0.00 row [00:00, ? row/s][2025-09-11 22:45:16,626 E 597098 597098] core_worker.cc:2151: Actor with class name: 'MapWorker(MapBatches(Embed))' and ID: '80871f7866b6f8a9cd68308801000000' has constructor arguments in the object store and max_restarts > 0. If the arguments in the object store go out of scope or are lost, the actor restart will fail. See https://github.com/ray-project/ray/issues/53727 for more details.

- ReadRange->SplitBlocks(256) 1: 0.00 row [00:00, ?
 row/s]
- MapBatches(E2025-09-11 22:45:16,6280, ? WARNING resource_manager.py:134 -- ⚠️  Ray's object store is configured to use only 10.2% of available memory (186.3GiB out of 1823.1GiB total). For optimal Ray Data performance, we recommend setting the object store to at least 50% of available memory. You can do this by setting the 'object_store_memory' parameter when calling ray.init() or by setting the RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION environment variable.
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 10.0B/93.1GB object store: : 0.00 row [00:01, ? Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 10.0B/93.1GB object store: : 0.00 row [00:01, ? Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 10.0B/93.1GB object store: : 0.00 row [00:01, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 10.0B object store: : 0.00 row [00:01, ? row/s
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 10.0B object store: : 1.00 row [00:01, 1.03s/ 
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 10.0B object store: : 1.00 row [00:01, 1.03s/ 
row]
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/7 objects local]:
 : 0.00 row [00:0
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/7 objects local]:
 : 0.00 row [00:0
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/7 objects local]:
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store: : 1.00 row [00:02, 1.03s/ r
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store: : 1.00 row [00:02, 1.03s/ r
ow]
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/27 objects local]
: : 0.00 row [00:
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:02, ? rRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:02, ? row/s]

- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/49 objects local]
: : 0.00 row [00:
- MapBatches(Embe                                                                                     Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: : 0.00 row [00:03, ? rRunning Dataset:                                                                                                       Running Dataset: 
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store: : 1.00 row [00:03, 1.03s/ r
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store: : 1.00 row [02025-09-11 22:45:20,489       INFO streaming_executor.py:279 -- ✔️  Dataset dataset_2_0 execution finished in 3.90 seconds
                 
                                                                                                                       ✔️  Dataset datas 
   
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store: : 1.00 row [00:03, 1.03s/ r
- ReadRange->SplitBlocks(256): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store: : 1.00 row [00:03, 1.03s/ r
- ReadRange->Spli                                                                                                      - ReadRange->Spli
- MapBatches(Embe
```

After this pr:
```
/workspace/ray/python/ray/_private/worker.py:1987: FutureWarning: Tip: In future versions of Ray, Ray will no longer override accelerator visible devices env var if num_gpus=0 or num_gpus=None (default). To enable this behavior and turn off this error message, set RAY_ACCEL_ENV_VAR_OVERRIDE_ON_ZERO=0
  warnings.warn(
2025-09-19 21:18:58,059 INFO logging.py:295 -- Registered dataset logger for dataset dataset_2_0
2025-09-19 21:18:58,101 INFO streaming_executor.py:159 -- Starting execution of Dataset dataset_2_0. Full logs are in /tmp/ray/session_2025-09-19_21-18-47_658581_2956326/logs/ray-data
2025-09-19 21:18:58,101 INFO streaming_executor.py:160 -- Execution plan of Dataset dataset_2_0: InputDataBuffer[Input] -> TaskPoolMapOperator[ReadRange] -> ActorPoolMapOperator[MapBatches(Embed)]
Running 0: 0.00 row [00:00, ? row/s][2025-09-19 21:18:58,205 E 2956326 2956326] core_worker.cc:2151: Actor with class name: 'MapWorker(MapBatches(Embed))' and ID: 'f1a874d3f4dd2fd81467ccf101000000' has constructor arguments in the object store and max_restarts > 0. If the arguments in the object store go out of scope or are lost, the actor restart will fail. See https://github.com/ray-project/ray/issues/53727 for more details.
                                                2025-09-19 21:18:58,211 WARNING resource_manager.py:134 -- ⚠️  Ray's object store is configured to use only 10.2% of available memory (186.3GiB out of 1824.3GiB total). For optimal Ray Data performance, we recommend setting the object store to at least 50% of available memory. You can do this by setting the 'object_store_memory' parameter when calling ray.init() or by setting the RAY_DEFAULT_OBJECT_STORE_MEMORY_PROPORTION environment variable.
Running Dataset: dataset_2_0. Active & requested resources: 1/128 CPU, 256.0MB/93.1GB object store (pendingRunning Dataset: dataset_2_0. Active & requested resources: 1/128 CPU, 256.0MB/93.1GB object store (pending: 1 CPU): : 0.00 row [00:01, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 256.0MB object st
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 256.0MB object st
ore: : 0.00 row [00:01, ? row/s]
                                                                                                                                                : 1 (running=0, restarting=0, pending=1); Queued blocks: 0; Resources:
                                                                                                           
(raylet) Task MapWorker(MapBatches(Embed)).submit failed. There are infinite retries remaining, so the task will be retried. Error: User exception:                                                                   
nner/plan_udf_map_op.py", line 486, in transform_fn                          
    res = fn(batch)
          ^^^^^^^^^
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 386, in _wrapped_udf_map_fn
    _try_wrap_udf_exception(e)
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 410, in _try_wrap_udf_exception
    raise UserCodeException("UDF failed to process a data block.") from e
ray.exceptions.UserCodeException: UDF failed to process a data block.
Running Dataset: dataset_2_0. Active & requested resources: 1/128 CPU, 256.0MB/93.1GB object store (pending: 1 CPU): : 0.00 row [00:01, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 256.0MB object st
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 rowRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 rowRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:02, ? row/s]
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 9.0B object store
: : 1.00 row [00:02, 2.10s/ row]
- MapBatches(Embed): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/13 ob
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 9.0B/93.1GB object store: : 0.00 row [00:03, ? row/s]d): Tasks: 3; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/13 ob
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 8.0B object store
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 8.0B object store
: : 1.00 row [00:03, 2.10s/ row]
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: : 0.00 rowRunning Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store:   0%| | 0.Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: 100%|█| 1.

- MapBatches(Embed): Tasks: 2; Actors: 1; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/65 ob
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: 100%|█| 1.
Running Dataset: dataset_2_0. Active & requested resources: 2/128 CPU, 0.0B/93.1GB object store: 100%|█| 1.
- ReadRange->SplitBlocks(256): T2025-09-19 21:19:05,248uINFO streaming_executor.py:279 -- ✔️  Dataset dataset_2_0 execution finished in 7.14 seconds; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/201 o
                                                                                                           
✔️  Dataset dataset_2_0 execution finished in 7.14 seconds: 100%|█████| 1.00/1.00 [00:07<00:00, 7.14s/ row] 
                                
- ReadRange->SplitBlocks(256): Tasks: 1; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store
- ReadRange->SplitBlocks(256): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store
- ReadRange->SplitBlocks(256): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 0.0 CPU, 0.0B object store
- MapBatches(Embed): Tasks: 0; Actors: 0; Queued blocks: 0; Resources: 1.0 CPU, 0.0B object store; [0/256 o
(raylet) Task MapWorker(MapBatches(Embed)).submit failed. There are infinite retries remaining, so the task will be retried. Error: User exception:                                                                   
nner/plan_udf_map_op.py", line 486, in transform_fn
    res = fn(batch)
          ^^^^^^^^^
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 386, in _wrapped_udf_map_fn
    _try_wrap_udf_exception(e)
  File "/workspace/ray/python/ray/data/_internal/planner/plan_udf_map_op.py", line 410, in _try_wrap_udf_exception
    raise UserCodeException("UDF failed to process a data block.") from e
ray.exceptions.UserCodeException: UDF failed to process a data block.
```

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/task_manager.cc [hunk 1]
```diff
@@ -1169,6 +1169,15 @@ bool TaskManager::RetryTaskIfPossible(const TaskID &task_id,
...
                     worker::TaskStatusEvent::TaskStateUpdate(error_info));
       task_entry.MarkRetry();
+      // Push the error to the driver if the task will still retry.
+      Status push_error_status =
+          push_error_callback_(task_entry.spec_.JobId(),
+                               rpc::ErrorType_Name(error_info.error_type()),
+                               error_info.error_message(),
+                               current_time_ms());
+      if (!push_error_status.ok()) {
+        RAY_LOG(INFO) << "Failed to push error to driver for task " << spec.TaskId();
```
Comment (edoakes) [inline src/ray/core_worker/task_manager.cc]: this should be `ERROR` level (or `WARNING` at least)

File: src/ray/core_worker/task_manager.cc [hunk 2]
```diff
@@ -1169,6 +1169,15 @@ bool TaskManager::RetryTaskIfPossible(const TaskID &task_id,
                     rpc::TaskStatus::FAILED,
                     worker::TaskStatusEvent::TaskStateUpdate(error_info));
       task_entry.MarkRetry();
+      // Push the error to the driver if the task will still retry.
+      Status push_error_status =
+          push_error_callback_(task_entry.spec_.JobId(),
+                               rpc::ErrorType_Name(error_info.error_type()),
+                               error_info.error_message(),
+                               current_time_ms());
```
Comment (edoakes) [inline src/ray/core_worker/task_manager.cc]: we need to add more context to the error log, otherwise this is likely to be very confusing. for example, I would expect something like:
```
Task {function_name} failed. There are N retries remaining, so the task will be retried. Error: {stacktrace}
```

**Comment by edoakes** [comment]
once you've addressed comment, let's also add a unit test to the task manager for this behavior (assert that the expected error is pushed/not pushed under the expected circumstances)

File: src/ray/core_worker/task_manager.cc (hunk 1 above)
Comment (Qiaolin-Yu) [reply src/ray/core_worker/task_manager.cc]: done

**Review by edoakes — APPROVED** [review]
LGTM, thanks!

**Comment by edoakes** [comment]
Linter failed: https://buildkite.com/ray-project/premerge/builds/49379#019963dd-4f15-4887-aa41-0f0d9a7c9341

File: src/ray/core_worker/task_manager.cc [hunk 3]
```diff
@@ -1169,6 +1169,21 @@ bool TaskManager::RetryTaskIfPossible(const TaskID &task_id,
                     rpc::TaskStatus::FAILED,
                     worker::TaskStatusEvent::TaskStateUpdate(error_info));
       task_entry.MarkRetry();
+      // Push the error to the driver if the task will still retry.
```
Comment (jjyao) [inline src/ray/core_worker/task_manager.cc:1207]: Can we put this behind a feature flag (on by default)? Since this goes through GCS and I'm a bit concerned that during excessive node preemption, we will tons of these messages and overload the GCS and driver. cc @edoakes

Comment (edoakes) [reply src/ray/core_worker/task_manager.cc:1207]: makes sense, sounds good

Comment (Qiaolin-Yu) [reply src/ray/core_worker/task_manager.cc:1207]: done

File: src/ray/core_worker/task_manager.cc [hunk 4]
```diff
@@ -1169,7 +1175,23 @@ bool TaskManager::RetryTaskIfPossible(const TaskID &task_id,
...
+                             error_info.error_message();
+        Status push_error_status =
+            push_error_callback_(task_entry.spec_.JobId(),
+                                 rpc::ErrorType_Name(error_info.error_type()),
+                                 error_message,
+                                 current_time_ms());
+        if (!push_error_status.ok()) {
+          RAY_LOG(ERROR) << "Failed to push error to driver for task " << spec.TaskId();
+        }
+      }
```
[the remark this answers is not in the document]
Comment (edoakes) [reply src/ray/core_worker/task_manager.cc:1232]: push_error_callback_ just sends an IPC, so no issue there: https://github.com/ray-project/ray/blob/0eca07b323bb68916c10b6e73ceafb4c27331e62/src/ray/core_worker/core_worker.cc#L1740

the OOM point is real @Qiaolin-Yu. for OOMs, I think we retry infinitely. you should be back to add a check for that.

[the remark this answers is not in the document]
Comment (Qiaolin-Yu) [reply src/ray/core_worker/task_manager.cc:1232]: done

File: src/ray/core_worker/task_manager.cc [hunk 5]
```diff
@@ -38,6 +39,11 @@ constexpr int64_t kTaskFailureThrottlingThreshold = 50;
 // Throttle task failure logs to once this interval.
 constexpr int64_t kTaskFailureLoggingFrequencyMillis = 5000;
 
+// Environment variable to disable the feature of outputting error log if the task is
+// still retryable.
+constexpr char kDisableOutputErrorLogIfStillRetryEnv[] =
+    "RAY_DISABLE_OUTPUT_ERROR_LOG_IF_STILL_RETRY";
```
Comment (edoakes) [inline src/ray/core_worker/task_manager.cc]: this should go in `ray_config_def.h` w/ the rest of our env var feature flags

Comment (Qiaolin-Yu) [reply src/ray/core_worker/task_manager.cc]: done

File: src/ray/common/ray_config_def.h [hunk 6]
```diff
@@ -967,3 +967,7 @@ RAY_CONFIG(int64_t, worker_num_grpc_internal_threads, 0)
 
 // Whether to start a background thread to manage Python GC in workers.
 RAY_CONFIG(bool, start_python_gc_manager_thread, true)
+
+// Whether to disable the feature of outputting error log if the task is
+// still retryable.
+RAY_CONFIG(bool, disable_output_error_log_if_still_retry, false)
```
Comment (edoakes) [inline src/ray/common/ray_config_def.h]: sorry for multiple iterations on this, but the feature flags are generally structured as `enable_...` and marked false to disable, so let's follow that convention

**Review by edoakes — APPROVED** [review]
one minor comment then lgtm

File: src/ray/common/ray_config_def.h (hunk 6 above)
Comment (Qiaolin-Yu) [reply src/ray/common/ray_config_def.h]: done

**Comment by edoakes** [comment]
@Qiaolin-Yu please sign off commits to fix DCO
