### PR TITLE
Actor dummy object garbage collection

### LINKED ISSUE #3308: Garbage collection for actor dummy objects
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Any
- **Ray installed from (source or binary)**: Any
- **Ray version**: 0.5.3
- **Python version**: Any
- **Exact command to reproduce**:

### Describe the problem

1. For long running jobs, actor won't exit and it will submit tasks continuously. Each task will have a dummy object put in `local_objects_` in task_dependency_manager.cc. This unordered map will grow very big. When the size grows to 13-16 million, the rehashing algorithm will take more than 10 second, which cause heartbeat timeout. 
2. For python functions, even if there is no return value, a `None` object will be put into Plasma. However, users don't aware there is a None value put into Plasma and they will not call Free to release it, which will also cause very big Plasma usage or large amount of `local_objects_` elements.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

This minimizes the number of pinned dummy objects per actor by only pinning the ones necessary to execute new actor tasks. This implements the solution described in #3308. Note that this does not solve the issue of garbage-collecting actor handles that are no longer needed, or the issue of general actor garbage collection.

## Related issue number

Closes #3308.

### CODE REVIEW

**Comment by ericl** [comment]
How do we test the map size doesn't grow indefinitely? I don't think the existing tests cover this. Run python code and check the C++ stats?

**Review by raulchen — COMMENTED** [review]
I took a brief look and left a few comments. Will continuing reviewing tmr.

Also, there're a bunch of unrelated changes (converting `UniqueID::nil()` to `UniqueId()`), are they unintentional?

File: src/ray/raylet/node_manager.cc [hunk 1]
```diff
@@ -1491,16 +1499,22 @@ bool NodeManager::AssignTask(const Task &task) {
...
           // We successfully assigned the task to the worker.
           worker->AssignTaskId(spec.TaskId());
           worker->AssignDriverId(spec.DriverId());
+
+          // Make a copy of the task to add to the lineage cache and eventually
+          // flush to the GCS.
+          // TODO(swang): We use a copy of the task so that for actor tasks, we
+          // can keep the original execution dependencies in the copy in the
+          // scheduling queue, but ideally the task in the lineage cache would
+          // match the queued task exactly.
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc]: Yeah this is a little unfortunate...we need access to the original execution dependency because that is the object that gets released in the actor's frontier once the task completes. I thought about doing the dummy object accounting when the task is assigned, but you don't know yet whether the task succeeded.

[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc]: Oh hmm actually just realized that we can separate the logic so that we release the previous object when the task is assigned and add the new object when the task finishes. Then I can get rid of this code. :)

File: src/ray/raylet/node_manager.cc [hunk 2]
```diff
@@ -1605,60 +1648,74 @@ void NodeManager::FinishAssignedTask(Worker &worker) {
...
   }
+  auto actor_entry = actor_registry_.find(actor_id);
+  RAY_CHECK(actor_entry != actor_registry_.end());
+  // Process any new actor handles that were forked from the current handle.
+  // The first task submitted on a new actor handle will depend on the
+  // finished task's execution dependency, so do not release the dependency
+  // until this first task is submitted.
+  for (auto &new_handle_id : task.GetTaskSpecification().NewActorHandles()) {
+    // An actor creation task is the first task, so it cannot have new handles.
+    RAY_CHECK(task.GetTaskSpecification().IsActorTask());
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc]: Thanks!

**Comment by stephanie-wang** [comment]
@ericl, yeah we don't have a way to automatically test this right now. Can you try it out on one of the RLlib workloads that would be affected?

File: src/ray/raylet/node_manager.cc [hunk 3]
```diff
@@ -1612,54 +1682,38 @@ void NodeManager::FinishAssignedTask(Worker &worker) {
...
-  // Unset the worker's assigned driver Id if this is not an actor.
-  if (!task.GetTaskSpecification().IsActorCreationTask() &&
-      !task.GetTaskSpecification().IsActorTask()) {
-    worker.AssignDriverId(DriverID::nil());
+  // Update the actor's frontier.
+  ActorID actor_id;
+  ActorHandleID actor_handle_id;
+  if (task.GetTaskSpecification().IsActorCreationTask()) {
+    actor_id = task.GetTaskSpecification().ActorCreationId();
+    actor_handle_id = ActorHandleID();
```
Comment (robertnishihara) [inline src/ray/raylet/node_manager.cc]: Maybe clearer to use `ActorHandleID::nil()` here. Alternatively could remove the line entirely.

File: src/ray/raylet/actor_registration.h [hunk 4]
```diff
@@ -118,8 +132,10 @@ class ActorRegistration {
   /// dependencies. This is indexed by handle.
   std::unordered_map<ActorHandleID, FrontierLeaf> frontier_;
 
-  /// All of the dummy object IDs from this actor's tasks.
-  std::vector<ObjectID> dummy_objects_;
+  /// A map from all of the dummy object IDs stored for this
+  /// actor to the number of actor handles that have the object
+  /// ID in scope.
+  std::unordered_map<ObjectID, int64_t> dummy_objects_;
```
Comment (robertnishihara) [inline src/ray/raylet/actor_registration.h]: I think this field would be a good place to provide a fairly in-depth description of how we determine precisely which dummy objects must be kept around and when we know that one can be marked as unavailable.

Someone trying to understand this code will probably look here.

File: python/ray/actor.py [hunk 5]
```diff
@@ -691,17 +700,22 @@ def _serialization_helper(self, ray_forking):
...
 
         if ray_forking:
             self._ray_actor_forks += 1
+        # Notify the backend to expect this new actor handle. The backend will
+        # not release the cursor for any new handles until the first task for
+        # each of the new handles is submitted.
+        # NOTE(swang): If the new actor handle fails to be used (e.g., due
+        # to a failure to register a named actor), then this may cause a
+        # memory leak in the backend.
+        self._ray_new_actor_handles.append(actor_handle_id)
```
Comment (robertnishihara) [inline python/ray/actor.py]: In the pickling case, we set `actor_handle_id = self._ray_actor_handle_id`. Why not use a nil ID (or some fixed ID like that) instead?

File: python/ray/actor.py [hunk 6]
```diff
@@ -691,17 +700,22 @@ def _serialization_helper(self, ray_forking):
...
             "ray_forking": ray_forking
         }
 
         if ray_forking:
             self._ray_actor_forks += 1
+        # Notify the backend to expect this new actor handle. The backend will
+        # not release the cursor for any new handles until the first task for
+        # each of the new handles is submitted.
+        # NOTE(swang): If the new actor handle fails to be used (e.g., due
+        # to a failure to register a named actor), then this may cause a
```
Comment (robertnishihara) [inline python/ray/actor.py]: This could happen even without any failure to register a named actor, right? E.g.,

```python
a = Actor.remote()

@ray.remote
def f(a):
    return

f.remote(a)
```

What precisely gets leaked? The dummy object ID that the forked ID depends on?

File: src/ray/raylet/actor_registration.h (hunk 4 above)
Comment (robertnishihara) [inline src/ray/raylet/actor_registration.h]: Will we always leak one dummy object ID per actor handle? That is, the very last dummy object ID produced by the handle? If I understand correctly, the only way to release a dummy object is to extend the frontier, which happens when a new task gets submitted. But some task will be the last task.

E.g., what happens to the `dummy_objects_` map for the workload

```python
a = Actor.remote()

@ray.remote
def f(a):
    return

while True:
    f.remote(a)
```

**Review by robertnishihara — COMMENTED** [review]
Thanks @stephanie-wang, this solution seems pretty nice.

File: src/ray/raylet/actor_registration.cc [hunk 7]
```diff
@@ -40,13 +40,39 @@ const std::unordered_map<ActorHandleID, ActorRegistration::FrontierLeaf>
...
+  // Add the reference to the new cursor for this actor handle.
+  dummy_objects_[execution_dependency]++;
+  return object_to_release;
+}
+
+void ActorRegistration::AddHandle(const ActorHandleID &handle_id,
+                                  const ObjectID &execution_dependency) {
+  if (frontier_.find(handle_id) == frontier_.end()) {
+    frontier_[handle_id] = FrontierLeaf{
+        .task_counter = 0, .execution_dependency = execution_dependency,
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/actor_registration.cc]: Hmm, I wasn't aware of any pros/cons. Do you have any suggestions in mind?

File: test/actor_test.py [hunk 8]
```diff
@@ -1858,8 +1858,87 @@ def fork(queue, key, num_items):
...
+        fork.remote(queue, i, num_items_per_fork) for i in range(num_forks)
+    ]
+    # Submit some more tasks on the original actor handle.
+    for item in range(num_items_per_fork):
+        local_fork = queue.enqueue.remote(num_forks, item)
+    forks.append(local_fork)
+    # Wait for tasks from all handles to complete.
+    ray.get(forks)
+    # Check that all tasks from all handles have completed.
+    items = ray.get(queue.read.remote())
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply test/actor_test.py]: Yep. We don't really provide any cross-handle properties anyway, so not much to test here.

File: python/ray/actor.py (hunk 5 above)
Comment (stephanie-wang) [reply python/ray/actor.py]: Hmm actually I guess we could just set a random actor handle ID in Python. We don't want to use nil because that represents the original actor handle.

File: python/ray/actor.py (hunk 6 above)
Comment (stephanie-wang) [reply python/ray/actor.py]: Hmm yeah, I guess the more general problem is GC for actor handles.

File: src/ray/raylet/actor_registration.h (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/raylet/actor_registration.h]: Yes, this is because we don't do GC for actor handles.

File: src/ray/raylet/actor_registration.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (robertnishihara) [reply src/ray/raylet/actor_registration.cc]: Ok, when we converted from C to C++, e.g., in #321, we had to make some changes like

https://github.com/ray-project/ray/pull/321/files#diff-450748b4523710897a16506dabc79950L573

and

https://github.com/ray-project/ray/pull/321/files#diff-303e99e77aad9f39624c3769dd615ea0L220

which switched away from using this syntax. I thought it wasn't valid C++, though if it's compiling in your PR maybe I'm remembering it incorrectly. I'm sure @mehrdadn knows the answer.

As for suggestions, I'd defer to other people here. If it's valid C++11 then it's probably fine especially since it's super simple. I guess the alternative would be to manually set the fields after the declaration or to define a simple constructor.

**Review by robertnishihara — APPROVED** [review]

File: src/ray/raylet/actor_registration.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (mehrdadn) [reply src/ray/raylet/actor_registration.cc]: These are called designated initializers in C. They were extensions I believe until C99? I had no idea but apparently they've finally made it into C++20. I'd avoid using them given they're not valid C++11.

[the remark this answers is not in the document]
Comment (robertnishihara) [reply src/ray/raylet/actor_registration.cc]: Thanks @mehrdadn!

Ok, in that case let's either do

```cpp
frontier_[handle_id] = FrontierLeaf();
frontier_[handle_id].task_counter = 0;
frontier_[handle_id].execution_dependency = execution_dependency;
```

or define a constructor.

[the remark this answers is not in the document]
Comment (mehrdadn) [reply src/ray/raylet/actor_registration.cc]: If you want to initialize fields externally I'd get a reference and avoid looking up the same object even time. If you make a constructor that should be fine too, though semantically it'd be creating a new object to move onto the old object rather than modifying it or constructing it in place. (Note that using `operator[]` to index into a map automatically calls the default constructor, so if you don't want to call that, you'd want to use `insert`.)

[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/actor_registration.cc]: Okay, thanks!

File: src/ray/gcs/format/gcs.fbs [hunk 9]
```diff
@@ -73,6 +73,10 @@ table TaskInfo {
   actor_counter: int;
   // True if this task is an actor checkpoint task and false otherwise.
   is_actor_checkpoint_method: bool;
+  // If this is an actor task, then this will be populated with all of the new
+  // actor handles that were forked from this handle since the last task on
+  // this handle was submitted.
+  new_actor_handles: [string];
```
Comment (raulchen) [inline src/ray/gcs/format/gcs.fbs]: The Java CI failure is because when we change `TaskInfo` definition, the corresponding Java file needs to be changed as well. 

Unfortunately, for now, generating this file isn't automatic. Because the generated file lacks a certain API and needs some manual patch. I proposed adding the required API to flatbuffers. But they're not willing to do that (https://github.com/google/flatbuffers/issues/5092).

For this PR, you can apply this patch to fix https://gist.github.com/raulchen/1fcecac74ddb809b836ab9bbf9f9e178.

We'll add a script to simplify this process.

Comment (raulchen) [reply src/ray/gcs/format/gcs.fbs]: The TLDR explanation of this issue is: we define some ObjectID fields as `string` in `fbs`. But these fields are actually `byte array`s. For C++ and Python 2, `string` and `byte array` are equivalent. But for Java and Python 3, they're different. 

Flatbuffers Java API will decode the bytes with UTF8 if a field is defined as `string`, but the content is actually not UTF8-decodable. Python API doesn't do that for now, but may do in the future. Because Flatbuffers prefers to distinguish strings and byte arrays. If so, our Python code will face the same problem. 

An alternative solution is to store hex strings in fbs. But that might require substantial code changes.

File: src/ray/raylet/actor_registration.h [hunk 10]
```diff
@@ -118,8 +132,28 @@ class ActorRegistration {
...
+  /// the dummy object returned by the finished task, since this means that the
+  /// next task submitted by the handle will depend on that object. If new
+  /// actor handles are created, these will be included in the next task
+  /// submitted on the original actor handle and are given a reference to the
+  /// same dummy object as the original handle.
+  ///
+  /// Once all handles have released a dummy object, it will be removed from
+  /// this map. This object is safe to evict, since no handle will submit
+  /// another method dependent on that object.
+  std::unordered_map<ObjectID, int64_t> dummy_objects_;
```
Comment (raulchen) [inline src/ray/raylet/actor_registration.h]: It took me quiet a while to understand the above comment.
Base on my understanding, I'm trying to summarize the comment and make it easier to understand for future readers. 

-------

This map is used to track all the unreleased dummy objects for this actor. The map key is the dummy object ID, and the map value is the number of actor handles that depends on this dummy object. When the map value decreases to 0, the dummy object is safe to release from the object manager.

An actor handle depends on a dummy object when its next unfinished task depends on the dummy object. For a given dummy object (say D), there could be 2 types of such actor handles:
1) The actor handle (say H) on which D's creating task (say T) was submitted. If T's next task hasn't finished yet, H still depends on D.
2) Any handles that were forked from H after T finished, and before T's next task finishes.  Such handles depend on H until their first tasks finish.

File: src/ray/gcs/format/gcs.fbs (hunk 9 above)
Comment (stephanie-wang) [reply src/ray/gcs/format/gcs.fbs]: Ah, thanks!

File: src/ray/raylet/node_manager.cc [hunk 11]
```diff
@@ -1451,14 +1460,13 @@ bool NodeManager::AssignTask(const Task &task) {
...
-      TreatTaskAsFailedIfLost(task);
-      return true;
-    }
+    // An actor task should only be ready to be assigned if it matches the
+    // expected task counter.
+    int64_t expected_task_counter =
+        GetExpectedTaskCounter(actor_registry_, spec.ActorId(), spec.ActorHandleId());
+    RAY_CHECK(spec.ActorCounter() == expected_task_counter)
+        << "Expected actor counter: " << expected_task_counter
+        << ", got: " << spec.ActorCounter();
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc]: Sure, thank you!

File: src/ray/raylet/actor_registration.h (hunk 10 above)
Comment (stephanie-wang) [reply src/ray/raylet/actor_registration.h]: Thanks! I agree that this is clearer.

**Comment by stephanie-wang** [comment]
Thanks for the comments, @raulchen! I tried to address all of them, so please let me know what you think. I tried for a bit to figure out how to implement the same logic that I did in Python in the Java client, but wasn't quite sure how to proceed. Maybe you or @guoyuhong could try it in a separate PR? I'm also happy to do it, but just need some pointers on where I should be looking.

**Comment by raulchen** [comment]
@stephanie-wang Java part looks good. We'll implement the logic in a separate PR later.

File: src/ray/raylet/actor_registration.h (hunk 10 above)
Comment (songpengwei) [reply src/ray/raylet/actor_registration.h]: I can not understand this very well. Because all calls in an Actor form a line in timeline, then should not all the handles for the same Actor depends on the latest same dummy object instead of each handle's last task dummy object?

Comment (stephanie-wang) [reply src/ray/raylet/actor_registration.h]: Hmm I'm not sure exactly what you're asking, but the dummy objects represent the last task that was known to execute on an actor. So when a task is submitted, it depends on the last task submitted on the same handle. When a task is executed, we might update that dependency to reflect the last task that was actually executed on the actor, which may have come from a different handle.

Comment (songpengwei) [reply src/ray/raylet/actor_registration.h]: Then I mean why should we keep each dependency for all ActorHandles of the same Actor instead of just keeping the latest one? Because we will always update the ActorHandle dependency  to the latest one when execute the actor task, then what is the sense to keep a dependency for each ActorHandle when submit the task?

Comment (stephanie-wang) [reply src/ray/raylet/actor_registration.h]: I think I understand your question now. We keep the dependency for each ActorHandle so that we know which tasks have executed so far and which task from each handle can execute next. The former is mostly important for failure scenarios (e.g., making sure you don't re-execute the same task twice on an actor), and the latter comes up during normal execution when there are multiple tasks from the same handle that could execute.

Both of these things don't strictly need the "dependency"; you could accomplish the same thing with task counters for each handle. However, it's convenient to use dependencies since this is also how we determine whether non-actor tasks can be executed.

Comment (songpengwei) [reply src/ray/raylet/actor_registration.h]: That is to say, when re-execute an Actor Method Sequences after failure, we can only guarantee call order in one ActorHandle, but not in global order(across all handles) with the last Actor method sequences?
