### PR TITLE
[Core] Adding the node id to the base event

### LINKED ISSUE #58879: [Core] Adding the node id to the base event
### Description

The node id is important when users want to figure out what happened in the Ray cluster, especially when the Ray process unexpected terminated and node id changed. But this information is not exported in the event. We hope the node id can be added to the base event.

### Use case

I am developing the history server for the Ray cluster. When the Ray process unexpected terminated, I have to flush the events generated by the previous node. If the ray process was restarted fast, it is difficult to know which events are generated by the previous node.

### PR DESCRIPTION
**Pull request by machichima**
## Description

When the Ray process unexpected terminated and node id changed, we cannot know the previous and current node id through event as we did not include `node_id` in the base event.

This feature is needed by the history server for the Ray cluster. When the Ray process unexpected terminated, we have to flush the events generated by the previous node. If the ray process was restarted fast, it is difficult to know which events are generated by the previous node.

This PR add the `node_id` into the base event showing where the event is being emitted. 

### Main changes

- `src/ray/protobuf/public/events_base_event.proto`
    - Add node id to the base event proto (`RayEvent`)

For GCS:

- `src/ray/gcs/gcs_server_main.cc`
    - add `--node_id` as cli args
- `src/ray/observability/` and `src/ray/gcs/` (some files)
    - Add `node_id` as arguments and pass to `RayEvent`

For CoreWorker

- `src/ray/core_worker/`
    - Passing the `node_id` to the `RayEvent`

Python side

- `python/ray/_private/node.py`
    - Passing `node_id` when starting gcs server

## Related issues

Closes #58879

### Testing process

1. export env var:
    - `RAY_enable_core_worker_ray_event_to_aggregator=1`
    - `RAY_DASHBOARD_AGGREGATOR_AGENT_EVENTS_EXPORT_ADDR="http://localhost:8000"`
2. `ray start --head --system-config='{"enable_ray_event":true}'`
3. Submit simple job `ray job submit -- python rayjob.py`. E.g.

```py
import ray

@ray.remote
def hello_world():
    return "hello world"

ray.init()
print(ray.get(hello_world.remote()))
```

4. Run event listener (script below) to start listening the event export host `python event_listener.py`

```py
import http.server
import socketserver
import json
import logging

PORT = 8000

class EventReceiver(http.server.SimpleHTTPRequestHandler):
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        post_data = self.rfile.read(content_length)
        print(json.loads(post_data.decode('utf-8')))
        self.send_response(200)
        self.send_header('Content-type', 'application/json')
        self.end_headers()
        self.wfile.write(json.dumps({"status": "success", "message": "Event received"}).encode('utf-8'))


if __name__ == "__main__":
    with socketserver.TCPServer(("", PORT), EventReceiver) as httpd:
        print(f"Serving event listener on http://localhost:{PORT}")
        print("Set RAY_DASHBOARD_AGGREGATOR_AGENT_EVENTS_EXPORT_ADDR to this address.")
        httpd.serve_forever()
```

Will get the event as below:

- GCS event:

```json
[
   {
      "eventId":"A+yrzknbyDjQALBvaimTPcyZWll9Te3Tw+FEnQ==",
      "sourceType":"GCS",
      "eventType":"DRIVER_JOB_LIFECYCLE_EVENT",
      "timestamp":"2025-12-07T10: 54: 12.621560Z",
      "severity":"INFO",
      "sessionName":"session_2025-12-07_17-33-33_853835_27993",
      "driverJobLifecycleEvent":{
         "jobId":"BAAAAA==",
         "stateTransitions":[
            {
               "state":"FINISHED",
               "timestamp":"2025-12-07T10: 54: 12.621562Z"
            }
         ]
      },
      "nodeId":"k4hj3FDLYStB38nSSRZQRwOjEV32EoAjQe3KPw==",   // <- nodeId set
      "message":""
   }
]
```

- CoreWorker event:

```json
[
   {
      "eventId":"TIAp8D4NwN/ne3VhPHQ0QnsBCYSkZmOUWoe6zQ==",
      "sourceType":"CORE_WORKER",
      "eventType":"TASK_DEFINITION_EVENT",
      "timestamp":"2025-12-07T10:54:12.025967Z",
      "severity":"INFO",
      "sessionName":"session_2025-12-07_17-33-33_853835_27993",
      "taskDefinitionEvent":{
         "taskId":"yoDzqOi6LlD///////////////8EAAAA",
         "taskFunc":{
            "pythonFunctionDescriptor":{
               "moduleName":"rayjob",
               "functionName":"hello_world",
               "functionHash":"a37aacc3b7884c2da4aec32db6151d65",
               "className":""
            }
         },
         "taskName":"hello_world",
         "requiredResources":{
            "CPU":1.0
         },
         "jobId":"BAAAAA==",
         "parentTaskId":"//////////////////////////8EAAAA",
         "placementGroupId":"////////////////////////",
         "serializedRuntimeEnv":"{}",
         "taskAttempt":0,
         "taskType":"NORMAL_TASK",
         "language":"PYTHON",
         "refIds":{
            
         }
      },
      "nodeId":"k4hj3FDLYStB38nSSRZQRwOjEV32EoAjQe3KPw==",   // <- nodeId set here
      "message":""
   }
]
```

### CODE REVIEW

**Comment by machichima** [comment]
For most of the test changes, I just pass in the `node_id` to the `Event` class constructor. Added the assertion for checking if `node_id` is set correctly in `src/ray/gcs/tests/gcs_node_manager_test.cc`

File: src/ray/core_worker/tests/core_worker_test.cc [hunk 1]
```diff
@@ -171,7 +171,8 @@ class CoreWorkerTest : public ::testing::Test {
     auto task_event_buffer = std::make_unique<worker::TaskEventBufferImpl>(
         std::make_unique<gcs::MockGcsClient>(),
         std::make_unique<rpc::EventAggregatorClientImpl>(0, *client_call_manager_),
-        "test_session");
+        "test_session",
+        NodeID::Nil());
```
Comment (Future-Outlier) [inline src/ray/core_worker/tests/core_worker_test.cc:175]: Hi, @machichima 
why some tests use `NodeID::Nil())`, but some tests use `NodeID::FromRandom())`?
Can we unify them?

Comment (machichima) [reply src/ray/core_worker/tests/core_worker_test.cc:175]: Yes sure. I will make tests use `NodeID::Nil()` and only use `NodeID::FromRandom()` in `src/ray/gcs/tests/gcs_node_manager_test.cc` that has the assertion check for the `node_id`

Comment (machichima) [reply src/ray/core_worker/tests/core_worker_test.cc:175]: Fixed in https://github.com/ray-project/ray/pull/59242/commits/cf2f8d19d2d655e4c7a2a2b47ec1f6dbfc062ffd

**Comment by Future-Outlier** [comment]
cc @MengjinYan to review or ping others who have expertise if you have time, this is related to the history server's log collector

File: src/ray/core_worker/tests/task_event_buffer_export_event_test.cc [hunk 2]
```diff
@@ -68,7 +68,8 @@ class TaskEventTestWriteExport : public ::testing::Test {
     task_event_buffer_ = std::make_unique<TaskEventBufferImpl>(
         std::make_unique<ray::gcs::MockGcsClient>(),
         std::make_unique<MockEventAggregatorClient>(),
-        "test_session_name");
+        "test_session_name",
+        NodeID::Nil());
```
Comment (MengjinYan) [inline src/ray/core_worker/tests/task_event_buffer_export_event_test.cc:72]: Nit: Probably we should use a valid the node id to test whether the node id can be populated correctly in task event.

File: src/ray/observability/ray_node_definition_event.cc [hunk 3]
```diff
@@ -18,13 +18,15 @@ namespace ray {
 namespace observability {
 
 RayNodeDefinitionEvent::RayNodeDefinitionEvent(const rpc::GcsNodeInfo &data,
-                                               const std::string &session_name)
+                                               const std::string &session_name,
+                                               const NodeID &node_id)
```
Comment (MengjinYan) [inline src/ray/observability/ray_node_definition_event.cc]: To avoid confusion, we need to add comment saying that this is the gcs node id but not the node id from the `GcsNodeInfo` data or renaming the parameter name to be `local_node_id`. 

Similar comment to the lifecycle event as well.

File: src/ray/observability/ray_event.h [hunk 4]
```diff
@@ -73,6 +76,7 @@ class RayEvent : public RayEventInterface {
   ray::rpc::events::RayEvent::Severity severity_;
   std::string message_;
   std::string session_name_;
+  const std::string node_id_;
```
Comment (MengjinYan) [inline src/ray/observability/ray_event.h]: Minor: I think it's better to make the `node_id_` with type `NodeID` and call `node_id_.Binary()` during serialization to be less confusion and it also moves the conversion to the non critical path. Or is there any reason why we should make it a string?

File: src/ray/observability/tests/ray_actor_definition_event_test.cc [hunk 5]
```diff
@@ -36,7 +36,8 @@ TEST_F(RayActorDefinitionEventTest, TestSerialize) {
   (*data.mutable_label_selector())["team"] = "core";
   (*data.mutable_label_selector())["tier"] = "prod";
 
-  auto event = std::make_unique<RayActorDefinitionEvent>(data, "test_session_name");
+  auto event =
```
Comment (MengjinYan) [inline src/ray/observability/tests/ray_actor_definition_event_test.cc]: I think we should use a real node id for the tests related to events and make sure the node ids are set correctly.

File: src/ray/gcs/gcs_server.cc [hunk 6]
```diff
@@ -148,6 +150,9 @@ GcsServer::GcsServer(const ray::gcs::GcsServerConfig &config,
   // Init GCS table storage. Note this is on the default io context, not the one with
   // GcsInternalKVManager, to avoid congestion on the latter.
   RAY_LOG(INFO) << "GCS storage type is " << storage_type_;
+  if (!gcs_node_id_.IsNil()) {
```
Comment (MengjinYan) [inline src/ray/gcs/gcs_server.cc]: nit: I think we should log the line no matter if the gcs node id value is Nil or not.

**Review by MengjinYan — COMMENTED** [review]
All nit comments. Thanks for the effort! 

To make sure correctness, you might also want to update the following test files to verify the node id as well:
* test_ray_event_export_task_events.py
* test_ray_actor_events.py
* test_ray_node_events.py
* test_ray_job_event.py

File: src/ray/observability/tests/ray_actor_definition_event_test.cc (hunk 5 above)
Comment (machichima) [reply src/ray/observability/tests/ray_actor_definition_event_test.cc]: Thank you! Just want to confirm if I should modify all tests that related to event to use `NodeID::FromRandom()` and assert if it's set correctly? Or is it just needed for this test file?

Comment (Future-Outlier) [reply src/ray/observability/tests/ray_actor_definition_event_test.cc]: I think maybe you can hardcode a node id for testing?

Comment (MengjinYan) [reply src/ray/observability/tests/ray_actor_definition_event_test.cc]: I think anything that is not Nil should be fine. Can either be `NodeID::FromRandom()` or a hardcoded value.

File: src/ray/core_worker/tests/task_event_buffer_export_event_test.cc (hunk 2 above)
Comment (machichima) [reply src/ray/core_worker/tests/task_event_buffer_export_event_test.cc:72]: I think this test is testing the Export API, which writes `rpc::ExportEvent` to log files and I think it's separate from the `RayEvent` that I modified. I put the `NodeID::Nil()` here as `TaskEventBuffer` requires a `node_id` parameter in its constructor

File: src/ray/observability/ray_node_definition_event.cc (hunk 3 above)
Comment (machichima) [reply src/ray/observability/ray_node_definition_event.cc]: Thank you! Renamed in https://github.com/ray-project/ray/pull/59242/commits/6fa2e008b9f745d88c2bf6c62adb9958be7cbcd2

File: src/ray/observability/ray_event.h (hunk 4 above)
Comment (machichima) [reply src/ray/observability/ray_event.h]: Thank you for pointing this out! This is the mistake on my side, changing it to `NodeID` type in https://github.com/ray-project/ray/pull/59242/commits/d44563a2c5a4663d9c7f644c8970038ffa4b48c7

File: src/ray/gcs/gcs_server.cc (hunk 6 above)
Comment (machichima) [reply src/ray/gcs/gcs_server.cc]: No problem! Modified in https://github.com/ray-project/ray/pull/59242/commits/21eac304ccc298f3de1fbed059d27dbcd636659b

File: src/ray/observability/tests/ray_actor_definition_event_test.cc (hunk 5 above)
Comment (machichima) [reply src/ray/observability/tests/ray_actor_definition_event_test.cc]: Modify tests in: https://github.com/ray-project/ray/pull/59242/commits/06220f8eade1fab5fff05753dde087706758a744

Also modified for:
- `src/ray/observability/tests/ray_actor_lifecycle_event_test.cc`
- `src/ray/observability/tests/ray_driver_job_lifecycle_event_test.cc`

**Comment by machichima** [comment]
Updated the python test files to check the `node_id` in https://github.com/ray-project/ray/pull/59242/commits/9332dd55b870ee5f0c51632ce27dae1402acbd8a

**Review by MengjinYan — APPROVED** [review]
Thanks for the contribution!

**Comment by MengjinYan** [comment]
cc: @jjyao for merging

File: src/ray/protobuf/public/events_base_event.proto [hunk 7]
```diff
@@ -103,4 +103,7 @@ message RayEvent {
   NodeLifecycleEvent node_lifecycle_event = 15;
   ActorDefinitionEvent actor_definition_event = 16;
   ActorLifecycleEvent actor_lifecycle_event = 17;
+
+  // Unique identifier of the node
+  bytes node_id = 18;
```
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/protobuf/public/events_base_event.proto:108]: This is not related to RPC.

File: src/ray/protobuf/public/events_base_event.proto [hunk 8]
```diff
@@ -103,4 +103,7 @@ message RayEvent {
   NodeLifecycleEvent node_lifecycle_event = 15;
   ActorDefinitionEvent actor_definition_event = 16;
   ActorLifecycleEvent actor_lifecycle_event = 17;
+
+  // Unique identifier of the node
```
Comment (jjyao) [inline src/ray/protobuf/public/events_base_event.proto]:
```suggestion
  // ID of the node where this event is emitted from
```

File: src/ray/protobuf/public/events_base_event.proto (hunk 7 above)
Comment (jjyao) [inline src/ray/protobuf/public/events_base_event.proto:108]: Since it's a common field, should we set it in a central place: the event agent? I think this can make the code simpler, for example, you don't need to pass node id to GCS. cc @MengjinYan

**Review by jjyao — COMMENTED** [review]
Could you update the PR description with more clear motivation why we need this PR?

File: src/ray/protobuf/public/events_base_event.proto (hunk 7 above)
Comment (machichima) [reply src/ray/protobuf/public/events_base_event.proto:108]: Updated, thank you! This makes code a lot cleaner

**Comment by Future-Outlier** [comment]
Hi, @machichima can you solve the merge conflict?

File: src/ray/observability/ray_event_recorder.cc [hunk 9]
```diff
@@ -74,6 +76,8 @@ void RayEventRecorder::ExportEvents() {
   }
   for (auto &event : grouped_events) {
     rpc::events::RayEvent ray_event = std::move(*event).Serialize();
+    // Set node_id centrally for all events
```
Comment (MengjinYan) [inline src/ray/observability/ray_event_recorder.cc:79]: Nice! I think it's better to put the logic in the `AddEvents` function so that the event constructions will all when we add the event to the buffer.

File: python/ray/_private/services.py [hunk 10]
```diff
@@ -1504,6 +1504,9 @@ def start_gcs_server(
         f"--node-id={node_id}",
     ]
 
+    if node_id:
+        command += [f"--node-id={node_id}"]
```
[the remark this answers is not in the document]
Comment (machichima) [reply python/ray/_private/services.py]: Fixed in https://github.com/ray-project/ray/pull/59242/commits/cd76a95fb5a5fc6c1bb3aabd8a285bdb33404e70

**Comment by MengjinYan** [comment]
Please let me know when the comment is fixed. I'll do a final review on the PR. Thanks!

File: src/ray/observability/ray_event_recorder.cc (hunk 9 above)
Comment (machichima) [reply src/ray/observability/ray_event_recorder.cc:79]: If we want to move `ray_event.set_node_id(node_id_.Binary())` to `RayEventRecorder::AddEvents`, we need to add `node_id` to `RayEvent` constructor. This requires a lot more changes for the classes that inherit from `RayEvent` (e.g. `RayActorLifecycleEvent`, `RayActorDefinitionEvent`, ...), like what we did before.

Current approach set the `node_id` in `RayEventRecorder::ExportEvents`. It's adding `node_id` to protobuf directly, so we do not need to change the constructor, making code much cleaner.

I think it's better to keep the current approach. WDYT?

Thank you!

**Review by MengjinYan — APPROVED** [review]

**Comment by Future-Outlier** [comment]
cc @dayshah to merge if you are not in vacation, thank you! < 3

File: src/ray/core_worker/task_event_buffer.h [hunk 11]
```diff
@@ -73,7 +73,10 @@ struct RayEventsTuple {
 class TaskEvent {
  public:
   /// Constructor for Profile events
-  explicit TaskEvent(TaskID task_id, JobID job_id, int32_t attempt_number);
+  explicit TaskEvent(TaskID task_id,
+                     JobID job_id,
+                     int32_t attempt_number,
+                     const NodeID &node_id = NodeID::Nil());
```
Comment (dayshah) [inline src/ray/core_worker/task_event_buffer.h:79]: It looks like this is always set by its subclasses, does this need a default?
```suggestion
                     const NodeID &node_id);
```

**Review by dayshah — COMMENTED** [review]
one super nit

**Comment by dayshah** [comment]
I think @edoakes needs to merge this one because codeowner on one of these files
