### PR TITLE
[Core] Fix graceful task cancellation of queued tasks.

### LINKED ISSUE #30760: [Core] Graceful task cancellation of queued tasks kills the worker.
The semantics of `ray.cancel(ref, force=False)` are that the executing worker won't be killed, and that a `TaskCancelledError` will be raised in the driver. This is particularly important for data-intensive workloads, where kill the executing workers when cancelling a task will lead to a lot of worker pool churn, which can slow down workloads. Currently, however, if a task is cancelled while it is queued, the worker will be killed and a `WorkerCrashedError` will be raised on the driver.

There appear to be two issues with the task cancellation protocol:

## Rejecting the task push RPC on queued task cancellation
It looks like when we cancel a queued task ([1](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/core_worker.cc#L3134), [2](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/normal_scheduling_queue.cc#L71)), this will reject the task push RPC ([1](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/actor_scheduling_util.cc#L39), [2](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/direct_actor_transport.cc#L204)), which will set the error flag when returning the worker to the raylet ([1](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/direct_task_transport.cc#L619), [2](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/direct_task_transport.cc#L197), [3](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/direct_task_transport.cc#L167)), which will cause the raylet to [destroy the worker](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/raylet/node_manager.cc#L2036-L2039) since it thinks that the leased worker encountered an unrecoverable failure. Graceful task cancellation (`ray.cancel(…, force=False)`, i.e. the default) isn’t supposed to force-terminate the worker, so the fact that we’re only terminating the worker if the task happens to be `force=False` cancelled during task queueing is violating those semantics. It’s also going through a code path where we assume that the raylet has information on the task failure, which is not the case (see next section).

## Task failure info propagation via raylet

In the [OOM exception propagation PR](https://github.com/ray-project/ray/pull/28466), we added logic to ping the leasing raylet to [get the concrete task failure](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/direct_task_transport.cc#L599-L612) when the task (push) fails. There are two issues with this:
1. This currently [uses the lease entry task ID](https://github.com/ray-project/ray/blob/36aebcbe1a5bba676f16b49c0184e091af07e73c/src/ray/core_worker/transport/direct_task_transport.cc#L612) (i.e. the task ID used to initially obtain the worker lease), but this assumes that failures are uniform across all tasks within the lease.
2. We also don’t set the task failure reason to be “task cancelled” in the raylet if the receiving worker cancels the task push RPC for the sake of task cancellation, so this failure reason state isn’t accurate anyway for this case.

## Possible Solutions
So it seems like our options are:
1. Change the task push protocol where the receiving core worker accepts the task push RPC while short-circuiting task execution, via setting some reply->set_cancelled_before_execution() flag on the RPC reply and eagerly returning. The task submitter can then see that the task was cancelled and go through the requisite logic (task_manager->FailOrRetryPendingTask()).
2. Propagate the task failure info from the receiving core worker to its raylet (the leasing raylet) and stick with the existing task push RPC rejection, relying on the later ping to the leasing raylet to get the task failure info.

I’d vote for (1), since (2) would involve an (unnecessary) ping to the leasing raylet to get the task cancellation info, and we’d still be unnecessarily destroying the receiving worker even for graceful cancellations. Task cancellation is fundamentally different than OOM killing since the protocol is handled at the worker level, and the receiving worker will be able to respond to the task push RPC, so there’s no need to involve the raylet for the graceful cancellation case. For the force=True cancellation case, the existing “worker died due to intentional user exit” handling should work as expected.

### PR DESCRIPTION
**Pull request by clarkzinzow**
Graceful task cancellation of queued tasks currently kills the underlying worker, which causes a `WorkerCrashedError` to be raised instead of a `TaskCancelledError`. This PR fixes this by ensuring that the worker isn't killed, and that the `TaskCancelledError` is eventually raised.

In particular, this PR:
- adds an `is_cancelled_before_running` field to the task push RPC reply,
- sets that field in the executing worker if the task is cancelled before it starts running,
- ensures that the task is marked as cancelled in the submitting worker if that field is set.

## Related issue number

Closes https://github.com/ray-project/ray/issues/30760

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 1]
```diff
@@ -609,7 +609,7 @@ void CoreWorkerDirectTaskSubmitter::PushNormalTask(
                 };
             auto &lease_entry = worker_to_lease_entry_[addr];
             RAY_CHECK(lease_entry.lease_client);
-            lease_entry.lease_client->GetTaskFailureCause(lease_entry.task_id, callback);
```
Comment (clarng) [inline src/ray/core_worker/transport/direct_task_transport.cc:612]: I think this breaks the oom killer , this is the task spec task id and is what is used by the raylet to track the failures, if we need to change it here we also need to change the task id in the raylet

https://buildkite.com/ray-project/oss-ci-build-pr/builds/6536#0184c5c2-b382-4d65-9ae4-8823d5fe69e6

Comment (clarkzinzow) [reply src/ray/core_worker/transport/direct_task_transport.cc:612]: Ah yes, I think the raylet is never updated with the new task ID when tasks reuse an existing lease, right? I'll remove this change since changing that would definitely be out-of-scope.

File: src/ray/protobuf/core_worker.proto [hunk 2]
```diff
@@ -135,6 +135,8 @@ message PushTaskReply {
   bool is_retryable_error = 5;
   // Whether the result contains an application-level error.
   bool is_application_error = 6;
+  // Whether the task was cancelled before it started running (i.e. while queued).
+  bool is_cancelled_before_running = 7;
```
Comment (stephanie-wang) [inline src/ray/protobuf/core_worker.proto:139]: Maybe `was_cancelled`?

**Review by stephanie-wang — APPROVED** [review]
Nice, thanks for making this fix!

File: src/ray/protobuf/core_worker.proto (hunk 2 above)
Comment (clarkzinzow) [reply src/ray/protobuf/core_worker.proto]: Ah yeah, I felt peer-pressured by the other present-tense fields! 😁 I'll make that change.

**Comment by clarkzinzow** [comment]
The tests that are timing out pass for me locally, I'm wondering if this is a CI-specific issue?

**Comment by clarkzinzow** [comment]
All tests failures appear to be unrelated, going to merge and keep an eye on the master build.
