### PR TITLE
[Core] Fix build issue with ignoring attributes on template argument

### LINKED ISSUE #46804: [Core] Build time error due to `-Wignored-attributes`
### What happened + What you expected to happen

I'm building Ray from source; the build fails with the following error:

```
src/ray/util/process.cc: In static member function 'static std::string ray::Process::Exec(std::string)':
src/ray/util/process.cc:410:42: error: ignoring attributes on template argument 'int (*)(FILE*)' [-Werror=ignored-attributes]
  410 |   std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(command.c_str(), "r"), pclose);
      |                                          ^
cc1plus: all warnings being treated as errors
```

I'm guessing this is because I'm building with a new version of GCC - I know in the past we've been restricted to much older versions, though I'm surprised we haven't seen this come up as I know it was introduced first in GCC 6 (maybe we're still restricted to gcc<6? As far as I can tell [there's no restriction in the docs](https://docs.ray.io/en/latest/ray-contribute/development.html)).

I'm happy to make a PR for this, in fact I have a branch with the fix already - but I wanted to create an issue to track this. Let me know if a PR would be of interest.

### Versions / Dependencies

`python -VV`: Python 3.11.9 (main, Jul  5 2024, 12:36:19) [GCC 14.1.1 20240522]
`uname -rms`: Linux 6.9.10-arch1-1 x86_64
`gcc -v`:

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/14.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --enable-languages=ada,c,c++,d,fortran,go,lto,m2,objc,obj-c++,rust --enable-bootstrap --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://gitlab.archlinux.org/archlinux/packaging/packages/gcc/-/issues --with-build-config=bootstrap-lto --with-linker-hash-style=gnu --with-system-zlib --enable-__cxa_atexit --enable-cet=auto --enable-checking=release --enable-clocale=gnu --enable-default-pie --enable-default-ssp --enable-gnu-indirect-function --enable-gnu-unique-object --enable-libstdcxx-backtrace --enable-link-serialization=1 --enable-linker-build-id --enable-lto --enable-multilib --enable-plugin --enable-shared --enable-threads=posix --disable-libssp --disable-libstdcxx-pch --disable-werror
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 14.1.1 20240522 (GCC) 
```

Ray version: ff789b95b8bd22af257fc168a9cc8ab689af6ede

### Reproduction script

I actually cannot build `ray` in my current `pyenv` environment using the steps detailed in the documentation (using `pip install -ve .` inside the `ray/python` directory). However I was able to get the compiled extensions building with `python setup.py build_ext` (deprecated, I know, but somehow this was the only way I found to get this building, and anyway the issue I ran into is purely in the C compilation step so I think it's unrelated to my `python setup.py build_ext` invocation which IMO is a separate issue).

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR fixes an issue where a structure with attributes is used as a template argument, triggering `-Wignored-attributes` and causing a build error on my system. The fix here is to just wrap `pclose` in a lambda expression.

## Related issue number

Closes #46804.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/util/process.cc [hunk 1]
```diff
@@ -407,7 +407,8 @@ std::string Process::Exec(const std::string command) {
 #ifdef _WIN32
   std::unique_ptr<FILE, decltype(&_pclose)> pipe(_popen(command.c_str(), "r"), _pclose);
 #else
-  std::unique_ptr<FILE, decltype(&pclose)> pipe(popen(command.c_str(), "r"), pclose);
+  std::unique_ptr<FILE, void (*)(FILE *)> pipe(popen(command.c_str(), "r"),
+                                               [](FILE *f) -> void { pclose(f); });
```
Comment (jjyao) [inline src/ray/util/process.cc:411]: Can you try https://code.videolan.org/videolan/vlc/-/merge_requests/4057/diffs?commit_id=7cf5d6977a07593a1b7cdb163b0748e6e60ee600. This might fix the issue without lambda.

Comment (peytondmurray) [reply src/ray/util/process.cc]: Looks like this build issue is fixed, but now I'm getting something else:

```
    bazel-out/k8-opt/bin/external/com_github_spdlog/_virtual_includes/spdlog/spdlog/fmt/bundled/core.h:1735:15: error: possibly dangling reference to a temporary [-Werror=dangling-reference]
     1735 |   const auto& arg = arg_mapper<Context>().map(FMT_FORWARD(val));
```

I'll file a separate issue.

**Review by jjyao — APPROVED** [review]
