### PR TITLE
[RFC] Fix object size inconsistency caused by object-marked-failed.

### LINKED ISSUE #16923: Check failed: data_size == static_cast<uint64_t>(object_buffer.data->Size() + object_buffer.metadata->Size())
object_buffer_pool.cc:74:  Check failed: data_size == static_cast<uint64_t>(object_buffer.data->Size() + object_buffer.metadata->Size()) 

I (very rarely) see the above when running https://github.com/ray-project/ray/issues/16342. It seems to occur at most a couple times per hundred runs.

This is a very strange, it seems to indicate that nodes are disagreeing about the size of an object.

### PR DESCRIPTION
**Pull request by scv119**
the bug in #16923 demonstrated as object metadata/data size mismatches in object_pull_manager. After investigation we figured it's turned out to be because a sequence of following events:
1. the object was first created and being GCed.
2. node_manager mark the object as failed, by setting datasize to 0 and metadata to error_type
3. the push manager still has stale information of this object, where it thought the data_size should be 329227, then failed the request.
4. 
See https://github.com/ray-project/ray/issues/16923#issuecomment-877712079 for detailed log.

In this PR we fix the issue by updating the staled info and proceed sending the object.

To fix the PR, we actually did following refactor:
1. refactor the SpilledObject into SpilledObject(Reader) and ChunkObjectReader.
2. create a MemoryObjectReader similar to SpilledObject, but wraps from plasma::ObjectBuffer.
3. Update object_buffer_pool to return a MemoryObjectReader directly on CreateObjectReader call.
4. In ObjectManager, call CreateObjectReader for pushing local object, and detect if the MemoryObjectReader is marked ad deleted, update the ObjectManager's local_object_info and continue the push.

TBD: 

- [x] add unittest for MemoryObjectReader
- [x] verify the bug is fixed by stress testing:
- run stress test `decision_tree_autoscaling_20_runs`  3 times successfully without issue, 1 times with object lost error (unrelated to this PR)

### CODE REVIEW

**Comment by scv119** [comment]
hmm the test_reconstruction failure looks related.

**Comment by ericl** [comment]
Instead of failing the transfer, how about deleting the out of date / incorrectly sized buffer and allocating a new one of the right size? I think this is better since presumably the failed object needs to be transferred to raise the error to the user. Also, in reconstruction the object size may change.

File: src/ray/object_manager/object_manager.cc [hunk 1]
```diff
@@ -378,39 +378,50 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &node_id) {
...
+
+  if (object_reader->GetDataSize() != data_size ||
+      object_reader->GetMetadataSize() != metadata_size) {
+    if (object_reader->GetDataSize() == 0 && object_reader->GetMetadataSize() == 1) {
+      RAY_LOG(WARNING) << object_id
+                       << " is marked as failed but object_manager has stale info "
+                       << " with data size: " << data_size
+                       << ", metadata size: " << metadata_size
+                       << ". This is likely due to race condition."
+                       << " Update the info and procceed sending failed object.";
```
Comment (ericl) [inline src/ray/object_manager/object_manager.cc:410]:
```suggestion
                       << " Update the info and proceed sending failed object.";
```

File: src/ray/object_manager/object_manager.cc [hunk 2]
```diff
@@ -378,39 +378,50 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &node_id) {
...
-  auto release_chunk_callback = [this, object_id](uint64_t chunk_index) {
-    buffer_pool_.ReleaseGetChunk(object_id, chunk_index);
-  };
+  std::shared_ptr<MemoryObjectReader> object_reader = std::move(reader_status.first);
+  RAY_CHECK(object_reader) << "object_reader can't be null";
+
+  if (object_reader->GetDataSize() != data_size ||
+      object_reader->GetMetadataSize() != metadata_size) {
+    if (object_reader->GetDataSize() == 0 && object_reader->GetMetadataSize() == 1) {
+      RAY_LOG(WARNING) << object_id
```
Comment (ericl) [inline src/ray/object_manager/object_manager.cc:405]: Maybe add a TODO we should handle object size changes in a more graceful way?

**Review by ericl — COMMENTED** [review]
The workaround LGTM assuming it passes the stress tests.

I did not review the refactored code carefully, but it looks reasonable to me as well.

File: src/ray/object_manager/object_manager.cc [hunk 3]
```diff
@@ -480,63 +463,64 @@ void ObjectManager::PushObjectInternal(
...
-  auto status = chunk_reader(chunk_index, push_request);
-  if (!status.ok()) {
-    RAY_LOG(WARNING) << "Attempting to push object " << object_id
-                     << " which is not local. It may have been evicted.";
-    on_complete(status);
+  auto optional_chunk = chunk_reader->GetChunk(chunk_index);
+  if (!optional_chunk.has_value()) {
+    RAY_LOG(ERROR) << "Read chunk " << chunk_index << " of object " << object_id
+                   << " failed. "
+                   << " It may have been evicted.";
```
Comment (suquark) [inline src/ray/object_manager/object_manager.cc:514]: combine this string with the previous line

File: src/ray/object_manager/object_manager.h [hunk 4]
```diff
@@ -369,41 +369,27 @@ class ObjectManager : public ObjectManagerInterface,
 
   /// The internal implementation of pushing an object.
   ///
-  /// \param chunk_reader Read the chunk into push_request's data fields; return
+  /// \param chunk_reader Chunk reader used to read a chunk of the object
   /// Status::OK() if the read succeeded.
```
Comment (suquark) [inline src/ray/object_manager/object_manager.h:373]: this line seems disconnected from the comment above

File: src/ray/object_manager/spilled_object.h [hunk 5]
```diff
@@ -23,39 +23,54 @@
...
-  uint64_t GetNumChunks() const;
+  virtual const rpc::Address &GetOwnerAddress() const = 0;
 
-  /// Return the value in a given chunk, identified by chunk_index.
-  /// It migh return an empty optional if the file is deleted.
+  /// Read from data/metadata sections into output.
+  /// Return false if the object is corrupted or size/offset is invalid.
+  virtual bool ReadFromDataSection(uint64_t offset, uint64_t size,
+                                   char *output) const = 0;
+  virtual bool ReadFromMetadataSection(uint64_t offset, uint64_t size,
```
Comment (suquark) [inline src/ray/object_manager/spilled_object.h:45]: docs?

**Comment by scv119** [comment]
Yup. let me run the stress tests for few times to ensure the bug is actually fixed.

File: src/ray/object_manager/object_manager.cc [hunk 6]
```diff
@@ -378,39 +378,51 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &node_id) {
...
-    if (status.ok()) {
-      ObjectBufferPool::ChunkInfo chunk_info = chunk_status.first;
-      push_request.set_data(chunk_info.data, chunk_info.buffer_length);
-    }
-    return status;
-  };
+  std::pair<std::shared_ptr<MemoryObjectReader>, ray::Status> reader_status =
+      buffer_pool_.CreateObjectReader(object_id, owner_address);
+  Status status = reader_status.second;
+  if (!status.ok()) {
```
Comment (scv119) [inline src/ray/object_manager/object_manager.cc:393]: @rkooo567 one behavior change here is that if the object read failed the push manager won't send anything over the network. will this cause any issue?

Comment (rkooo567) [reply src/ray/object_manager/object_manager.cc:393]: What did it send over the network before?

File: src/ray/object_manager/object_manager.cc [hunk 7]
```diff
@@ -378,39 +378,51 @@ void ObjectManager::Push(const ObjectID &object_id, const NodeID &node_id) {
...
+    RAY_LOG(ERROR) << "Failed to read object " << object_id
+                   << ". It may have been evicted.";
+    return;
+  }
 
-  auto release_chunk_callback = [this, object_id](uint64_t chunk_index) {
-    buffer_pool_.ReleaseGetChunk(object_id, chunk_index);
-  };
+  std::shared_ptr<MemoryObjectReader> object_reader = std::move(reader_status.first);
```
Comment (rkooo567) [inline src/ray/object_manager/object_manager.cc:399]:
```suggestion
  auto object_reader = std::move(reader_status.first);
```

File: src/ray/object_manager/memory_object_reader.h [hunk 8]
```diff
@@ -0,0 +1,43 @@
...
+#pragma once
+
+#include "ray/object_manager/plasma/client.h"
+#include "ray/object_manager/spilled_object.h"
+
+namespace ray {
+
+/// A wrapper over plasma object.
+/// This class is thread safe.
+class MemoryObjectReader : public IObjectReader {
```
Comment (rkooo567) [inline src/ray/object_manager/memory_object_reader.h:24]: Why don't we just call it IRayObject or sth?

File: src/ray/object_manager/object_manager.cc [hunk 9]
```diff
@@ -480,63 +464,63 @@ void ObjectManager::PushObjectInternal(
...
 
   // read a chunk into push_request and handle errors.
-  auto status = chunk_reader(chunk_index, push_request);
-  if (!status.ok()) {
-    RAY_LOG(WARNING) << "Attempting to push object " << object_id
-                     << " which is not local. It may have been evicted.";
-    on_complete(status);
+  auto optional_chunk = chunk_reader->GetChunk(chunk_index);
+  if (!optional_chunk.has_value()) {
+    RAY_LOG(ERROR) << "Read chunk " << chunk_index << " of object " << object_id
```
Comment (rkooo567) [inline src/ray/object_manager/object_manager.cc:513]: Change it to INFO?

File: src/ray/object_manager/plasma/client.cc [hunk 10]
```diff
@@ -512,17 +512,6 @@ Status PlasmaClient::Impl::Get(const std::vector<ObjectID> &object_ids,
...
 }
 
-Status PlasmaClient::Impl::Get(const ObjectID *object_ids, int64_t num_objects,
-                               int64_t timeout_ms, ObjectBuffer *out,
-                               bool is_from_worker) {
-  std::lock_guard<std::recursive_mutex> guard(client_mutex_);
-
-  const auto wrap_buffer = [](const ObjectID &object_id,
-                              const std::shared_ptr<Buffer> &buffer) { return buffer; };
-  return GetBuffers(object_ids, num_objects, timeout_ms, wrap_buffer, out,
```
Comment (rkooo567) [inline src/ray/object_manager/plasma/client.cc:522]: Why do we remove this?

File: src/ray/object_manager/spilled_object.h [hunk 11]
```diff
@@ -23,39 +23,66 @@
 
 namespace ray {
 
-/// Represent a local object spilled in the object_url.
-/// This class is thread safe.
-class SpilledObject {
+/// Reader over an immutable Ray object.
+class IObjectReader {
```
Comment (rkooo567) [inline src/ray/object_manager/spilled_object.h:27]: Move this class to other files?

File: src/ray/object_manager/test/spilled_object_test.cc [hunk 12]
```diff
@@ -217,76 +250,81 @@ TEST(SpilledObjectTest, GetNumChunks) {
...
+        auto chunk = reader.GetChunk(i);
+        ASSERT_TRUE(chunk.has_value());
+        ASSERT_GE(chunk_size, chunk->size());
+        if (i + 1 != reader.GetNumChunks()) {
+          ASSERT_EQ(chunk_size, chunk->size());
+        }
+        actual_output_by_chunks.append(chunk.value());
       }
-      actual_output_by_chunks.append(chunk.value());
+      ASSERT_EQ(expected_output, actual_output_by_chunks);
```
Comment (rkooo567) [inline src/ray/object_manager/test/spilled_object_test.cc:315]: Can we also test other methods like GetDataSection, GetMetadataSection

File: src/ray/object_manager/spilled_object.h [hunk 13]
```diff
@@ -23,39 +23,66 @@
...
+  /// \param size number of bytes to copy.
+  /// \param output pointer to the memory location to copy to.
+  /// \return bool.
+  virtual bool ReadFromMetadataSection(uint64_t offset, uint64_t size,
+                                       char *output) const = 0;
+};
+
+/// Reader for a local object spilled in the object_url.
+/// This class is thread safe.
+/// TODO(scv119): rename it to SpilledObjectReader
```
Comment (rkooo567) [inline src/ray/object_manager/spilled_object.h:63]: Why not renaming all now?

File: src/ray/object_manager/plasma/client.cc (hunk 10 above)
Comment (rkooo567) [reply src/ray/object_manager/plasma/client.cc:522]: Is it not used?

File: src/ray/object_manager/memory_object_reader.h (hunk 8 above)
Comment (scv119) [reply src/ray/object_manager/memory_object_reader.h:24]: too many Objects...

Comment (rkooo567) [reply src/ray/object_manager/memory_object_reader.h:24]: Hmm I see lol. Then can we change SpillObject -> SpillObjectReader (just for the consistency)?

File: src/ray/object_manager/object_manager.cc (hunk 9 above)
Comment (scv119) [reply src/ray/object_manager/object_manager.cc:513]: hmm, at least this should be a warning? (as it's not expected)

File: src/ray/object_manager/memory_object_reader.h (hunk 8 above)
Comment (scv119) [reply src/ray/object_manager/memory_object_reader.h:24]: yup. I'm trying to keep this RP as small as possible...

File: src/ray/object_manager/test/spilled_object_test.cc (hunk 12 above)
Comment (scv119) [reply src/ray/object_manager/test/spilled_object_test.cc:315]: I had some implicit test for it. maybe it's time to add explicit test for it!

File: src/ray/object_manager/memory_object_reader.cc [hunk 14]
```diff
@@ -0,0 +1,51 @@
...
+}
+
+const rpc::Address &MemoryObjectReader::GetOwnerAddress() const { return owner_address_; }
+
+bool MemoryObjectReader::ReadFromDataSection(uint64_t offset, uint64_t size,
+                                             char *output) const {
+  if (offset + size > GetDataSize()) {
+    return false;
+  }
+  std::memcpy(output, object_buffer_.data->Data() + offset, size);
```
Comment (rkooo567) [inline src/ray/object_manager/memory_object_reader.cc:38]: Isn't this regression? I remember we talked about that the plasma object is not copied until it is copied to the grpc request, but now it seems like we are copying twice? (plasma -> chunk -> grpc)?

Comment (scv119) [reply src/ray/object_manager/memory_object_reader.cc:38]: in the new code we only copy once too! because we moved to grpc instead of copy:
https://github.com/ray-project/ray/pull/16976/files#diff-1b792600903619ac4375f3eaf4cfe68f30cb8df813128d2a6fbee968a656554bR520

Comment (scv119) [reply src/ray/object_manager/memory_object_reader.cc:38]: added two tests to demonstrate the new code and the old code both only copy once.

File: src/ray/object_manager/test/spilled_object_test.cc [hunk 15]
```diff
@@ -217,76 +240,157 @@ TEST(SpilledObjectTest, GetNumChunks) {
...
   }
 }
-}  // namespace
 
-TEST(SpilledObjectTest, GetChunk) {
-  AssertGetChunkWorks("meta", "alotofdata", {1, 2, 3, 5, 100});
-  AssertGetChunkWorks("alotofactualmeta", "meh", {1, 2, 3, 5, 100});
-  AssertGetChunkWorks("", "weonlyhavedata", {1, 2, 3, 5, 100});
-  AssertGetChunkWorks("weonlyhavemetadata", "", {1, 2, 3, 5, 100});
+TEST(StringAllocationTest, TestNoCopyWhenStringMoved) {
```
Comment (scv119) [inline src/ray/object_manager/test/spilled_object_test.cc:376]: here is the test!

**Review by ericl — APPROVED** [review]
