### PR TITLE
[Core] Fix reference counting bug on objects borrowed for a cancelled actor creation.

### LINKED ISSUE #27297: [Core] Borrowed objects are leaked when actor creation is cancelled before the creation task is scheduled.
Objects borrowed by an actor creation task will be leaked if the creation task is cancelled before it is scheduled.

### Explicit Actor Creation Cancellation

```python
    import ray
    import time

    @ray.remote(resources={"nonexistent_resource": 1})
    class Actor:
        def __init__(self, obj_containing_ref):
            raise ValueError(
                "The actor constructor should not be reached; the actor creation task "
                "should be cancelled before the actor is scheduled."
            )

    ref = ray.put(1)
    a = Actor.remote({"foo": ref})
    ray.kill(a)
    del ref
    time.sleep(5)
    print(ray._private.worker.global_worker.core_worker.get_all_reference_counts())
    print(ray._private.internal_api.memory_summary())
```

### Implicit Actor Creation Cancellation via Scope

```python
    import ray
    import time

    @ray.remote(resources={"nonexistent_resource": 1})
    class Actor:
        def __init__(self, obj_containing_ref):
            raise ValueError(
                "The actor constructor should not be reached; the actor creation task "
                "should be cancelled before the actor is scheduled."
            )

    def leak():
        ref = ray.put(1)
        Actor.remote({"foo": ref})

    time.sleep(5)
    print(ray._private.worker.global_worker.core_worker.get_all_reference_counts())
    print(ray._private.internal_api.memory_summary())
```

### PR DESCRIPTION
**Pull request by clarkzinzow**
This PR fixes a reference counting bug for borrowed objects sent to an actor creation task that is then cancelled.

Before this PR, when actor creation is cancelled before the creation task has been scheduled, the GCS-based actor manager would would destroy the actor without replying to the task submission RPC from the actor creating worker, resulting in the reference counts on that worker to never get cleaned up. This caused us to leak borrowed objects when such cancellation-before-scheduling happened for actors.

This PR fixes this by ensuring that the task submission RPC receives a reply indicating that the actor creation task has been cancelled, at which point the submitting worker will run through the same reference counting cleanup as is done for normal task cancellation.

## Related issue number

Closes #27297 

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -801,6 +809,15 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id,
         // Destroy placement group owned by this actor.
         destroy_owned_placement_group_if_needed_(actor_id);
       }));
+
+  // Inform all creation callbacks that the actor was cancelled, not created.
+  auto iter = actor_to_create_callbacks_.find(actor_id);
```
Comment (wumuzi520) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:814]: Since the same logic exists when `OnActorSchedulingSuccess`, I think it's better to move this logic from `DestroyActor` to `OnActorSchedulingFailed`.

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 2]
```diff
@@ -44,12 +44,19 @@ Status CoreWorkerDirectTaskSubmitter::SubmitTask(TaskSpecification task_spec) {
           task_spec,
           [this, actor_id, task_id](Status status, const rpc::CreateActorReply &reply) {
             if (status.ok()) {
-              RAY_LOG(DEBUG) << "Created actor, actor id = " << actor_id;
-              // Copy the actor's reply to the GCS for ref counting purposes.
-              rpc::PushTaskReply push_task_reply;
-              push_task_reply.mutable_borrowed_refs()->CopyFrom(reply.borrowed_refs());
-              task_finisher_->CompletePendingTask(
-                  task_id, push_task_reply, reply.actor_address());
+              if (reply.creation_cancelled()) {
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_task_transport.cc:47]: Why don't we just handle this in `if (!status.ok())` code path? Why do we need a special `creation_cancelled `? (I think if the actor scheduling is already cancelled by because the actor is already killed, it should go that path?)

Comment (clarkzinzow) [reply src/ray/core_worker/transport/direct_task_transport.cc:47]: I initially went that route, ended up going with a cancellation field for a few reasons:
1. We need to be able to delineate between actor creation failure (which should be retried) and actor creation cancellation (which should not be retried), and there wasn't an existing status code that seemed like a good delineator, so we'd need to add a new one.
2. The operation didn't fail, it was determined to not be needed and was therefore canceled, which feels like a valid part of the success path in the actor creation protocol, so returning a non-ok status felt weird. E.g., we don't return a non-ok status when a worker lease request is cancelled: https://github.com/ray-project/ray/blob/0b39285dea6b4266c05a52652678db5f2939f813/src/ray/protobuf/node_manager.proto#L81

Could you say more about why you think this should fall in the `!status.ok()` path?

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 3]
```diff
@@ -44,12 +44,19 @@ Status CoreWorkerDirectTaskSubmitter::SubmitTask(TaskSpecification task_spec) {
...
-              // Copy the actor's reply to the GCS for ref counting purposes.
-              rpc::PushTaskReply push_task_reply;
-              push_task_reply.mutable_borrowed_refs()->CopyFrom(reply.borrowed_refs());
-              task_finisher_->CompletePendingTask(
-                  task_id, push_task_reply, reply.actor_address());
+              if (reply.cancelled()) {
+                RAY_LOG(DEBUG) << "Actor creation cancelled, actor id = " << actor_id;
+                task_finisher_->MarkTaskCanceled(task_id);
+                RAY_UNUSED(task_finisher_->FailOrRetryPendingTask(
+                    task_id, rpc::ErrorType::TASK_CANCELLED, nullptr));
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_task_transport.cc:51]: Can you use `ACTOR_CREATION_FAILED `? 

`TASK_CANCELLED ` raises
```
class TaskCancelledError(RayError):
    """Raised when this task is cancelled.

    Attributes:
        task_id (TaskID): The TaskID of the function that was directly
            cancelled.
    """

    def __init__(self, task_id=None):
        self.task_id = task_id

    def __str__(self):
        if self.task_id is None:
            return "This task or its dependency was cancelled by"
        return "Task: " + str(self.task_id) + " was cancelled"
```
and actor creation == task is an implementation detail. (maybe we can raise an exception saying the actor scheduling is cancelled). You can also add an useful error message by providing `const rpc::RayErrorInfo *ray_error_info,` to `FailOrRetryPendingTask `.

File: src/ray/protobuf/gcs_service.proto [hunk 4]
```diff
@@ -330,6 +324,8 @@ message CreateActorReply {
   Address actor_address = 2;
   // Info about any refs that the created actor is borrowing.
   repeated ObjectReferenceCount borrowed_refs = 3;
+  // Whether the actor creation was cancelled.
```
Comment (rkooo567) [inline src/ray/protobuf/gcs_service.proto:327]:
```suggestion
  // Whether the actor creation was cancelled. It happens when the actor is killed before it is created (e.g., ray.kill is called, owner is dead, or its ref goes out of scope)
```

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 5]
```diff
@@ -259,10 +259,18 @@ void GcsActorManager::HandleCreateActor(const rpc::CreateActorRequest &request,
       request,
       [reply, send_reply_callback, actor_id](const std::shared_ptr<gcs::GcsActor> &actor,
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:260]: Can you rewrite the docstring of `CreateActor` method? (the definition of callback param). It is incorrect with the new implementation. (it says the callback is called when the actor is created successfully )

File: python/ray/tests/test_reference_counting.py [hunk 6]
```diff
@@ -554,6 +554,38 @@ class A:
...
+    @ray.remote(resources={"nonexistent_resource": 1})
+    class Actor:
+        def __init__(self, obj_containing_ref):
+            raise ValueError(
+                "The actor constructor should not be reached; the actor creation task "
+                "should be cancelled before the actor is scheduled."
+            )
+
+    # Test with explicit cancellation via ray.kill().
+    ref = ray.put(1)
```
Comment (rkooo567) [inline python/ray/tests/test_reference_counting.py:571]: nice test!

**Review by rkooo567 — CHANGES_REQUESTED** [review]

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 2 above)
Comment (rkooo567) [reply src/ray/core_worker/transport/direct_task_transport.cc]: status.ok() sounded like it means the actor creation is succeeded. But it seems like the definition of status is not clearly defined within a callback, so it might be okay. 

Still prefer to have a status like SchedulingCancelled error and handle it within !status.ok() path, but if this pattern is already used at other places, it might be okay (still don't prefer it...)

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 7]
```diff
@@ -801,6 +809,15 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id,
...
         destroy_owned_placement_group_if_needed_(actor_id);
       }));
+
+  // Inform all creation callbacks that the actor was cancelled, not created.
+  auto iter = actor_to_create_callbacks_.find(actor_id);
+  if (iter != actor_to_create_callbacks_.end()) {
+    for (auto &callback : iter->second) {
+      callback(actor, rpc::PushTaskReply());
+    }
+    actor_to_create_callbacks_.erase(iter);
```
[the remark this answers is not in the document]
Comment (clarkzinzow) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:819]: Ah good point about leaking the callbacks! 🤦 

>Maybe keep the raise location as it is, but we can store a list of callbacks up there and use it here?

I was trying to limit the scope of this change to cancellation, but should the callbacks also be invoked for any of the early-return cases? This was my thinking for each case:
1. Actor doesn't exist - actor creation callback shouldn't exist since it was never registered.
2. Actor is already dead - this should only happen if actor creation has already succeeded.

Let me know if I'm missing anything there. Otherwise, I'll do as you suggest, erase the callbacks from the `actor_to_create_callbacks_` map early and invoke the callbacks at the end.

File: src/ray/protobuf/gcs_service.proto (hunk 4 above)
Comment (clarkzinzow) [reply src/ray/protobuf/gcs_service.proto:327]: Yep good protocol comment.

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 2 above)
Comment (clarkzinzow) [reply src/ray/core_worker/transport/direct_task_transport.cc]: >status.ok() sounded like it means the actor creation is succeeded. But it seems like the definition of status is not clearly defined within a callback, so it might be okay.

Our mixture of transport-level and application-level statuses, piggybacking off of the gRPC status rather than keeping them separate and using the rich error model or the protobuf payload for the latter, has always bothered me. So I think I have a subconscious aversion to using it for anything other than transport-level failures. 😂 

>Still prefer to have a status like SchedulingCancelled error and handle it within !status.ok() path, but if this pattern is already used at other places, I am okay with the current style

I'll take a stab at this and see how it feels!

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 3 above)
Comment (clarkzinzow) [reply src/ray/core_worker/transport/direct_task_transport.cc:51]: Ah good point!

**Review by stephanie-wang — APPROVED** [review]
Nice find and fix!

File: python/ray/tests/test_reference_counting.py [hunk 8]
```diff
@@ -554,6 +554,38 @@ class A:
...
+
+    # Confirm that the ref object is not leaked.
+    check_refcounts({})
+
+    # Test with implicit cancellation by letting the actor handle go out-of-scope.
+    def test_implicit_cancel():
+        ref = ray.put(1)
+        Actor.remote({"foo": ref})
+
+    test_implicit_cancel()
```
Comment (rkooo567) [inline python/ray/tests/test_reference_counting.py:584]: Can you also test if calling an actor gives you the right exception?

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 9]
```diff
@@ -51,10 +51,20 @@ Status CoreWorkerDirectTaskSubmitter::SubmitTask(TaskSpecification task_spec) {
               task_finisher_->CompletePendingTask(
                   task_id, push_task_reply, reply.actor_address());
             } else {
-              RAY_LOG(INFO) << "Failed to create actor " << actor_id
-                            << " with status: " << status.ToString();
+              rpc::RayErrorInfo ray_error_info;
+              if (status.IsSchedulingCancelled()) {
+                RAY_LOG(DEBUG) << "Actor creation cancelled, actor id = " << actor_id;
+                task_finisher_->MarkTaskCanceled(task_id);
+                ray_error_info.mutable_actor_died_error()->CopyFrom(reply.death_cause());
```
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_task_transport.cc:58]: Should we add an error message that the actor scheduling has cancelled? (maybe the current way is good enough?)

File: src/ray/protobuf/gcs_service.proto [hunk 10]
```diff
@@ -330,6 +324,8 @@ message CreateActorReply {
   Address actor_address = 2;
   // Info about any refs that the created actor is borrowing.
   repeated ObjectReferenceCount borrowed_refs = 3;
+  // The cause of this actor's death if creation was cancelled.
+  ActorDeathCause death_cause = 4;
```
Comment (rkooo567) [inline src/ray/protobuf/gcs_service.proto:328]: Make it optional?

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 9 above)
Comment (rkooo567) [inline src/ray/core_worker/transport/direct_task_transport.cc:58]: if reply.has_death_cause()?

**Review by rkooo567 — APPROVED** [review]
LGTM! Last nits

File: src/ray/protobuf/gcs_service.proto (hunk 10 above)
Comment (clarkzinzow) [reply src/ray/protobuf/gcs_service.proto:328]: Ah I was going to go with the default enum "NOT_SET" value, but yeah optional would be better.

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 9 above)
Comment (clarkzinzow) [reply src/ray/core_worker/transport/direct_task_transport.cc:58]: It should always be set if the actor has been cancelled, should it be an `if` check or a `RAY_CHECK` in your opinion?

Comment (clarkzinzow) [reply src/ray/core_worker/transport/direct_task_transport.cc:58]: Yeah I was looking at that. 🤔 The actor death cause provides the underlying method of cancellation (e.g. `ray.kill`), but I'll check to see what the error message looks like.

Comment (rkooo567) [reply src/ray/core_worker/transport/direct_task_transport.cc:58]: I think it can be RAY_CHECK in this case?

Comment (rkooo567) [reply src/ray/core_worker/transport/direct_task_transport.cc:58]: if might be a safer choice though

Comment (rkooo567) [reply src/ray/core_worker/transport/direct_task_transport.cc:58]: Sgtm. I think the benefit of having better error message is it indicates if the actor was ever created or not. But I think it's okay not to handle it if it is too hard.

**Comment by clarkzinzow** [comment]
@scv119 @ericl Could I get a codeowner review?

**Review by ericl — APPROVED** [review]
protobuf changes lgtm

**Comment by clarkzinzow** [comment]
Current test state:
- Failing tune test is failing in master (fixed since the last rebase)
- Failing external Redis test is failing in master (fixed since the last rebase)
- MacOS tests are queued, but they all succeeded in the last run except for the test that was fixed in the most recent commit, and I've confirmed that that test is passing on Linux.

Since the MacOS build queue is super backed up, I'm thinking about merging now. In the very unlike case that a MacOS-specific issue pops up due to the most recent commit, I can resolve it in a follow-up PR.

**Comment by clarkzinzow** [comment]
MacOS tests look god as well as others, merging.
