### PR TITLE
[gcs] Fix in_memory_store not handling nullptr callback issue

### LINKED ISSUE #22319: [nightly] node_failures failed
It's related to redisless flag being turned on. 

```
Iteration 999:
  - Iteration time: 2.418158531188965.
  - Absolute time: 1644570204.7196364.
  - Total elapsed time: 8090.201013803482.
2022-02-11 09:03:42,300 ERROR utils.py:1208 -- Internal KV Get failed
Traceback (most recent call last):
  File "/mnt/yic/ray/python/ray/_private/utils.py", line 1206, in internal_kv_get_with_retry
    result = gcs_client.internal_kv_get(key, namespace)
  File "/mnt/yic/ray/python/ray/_private/gcs_utils.py", line 146, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/yic/ray/python/ray/_private/gcs_utils.py", line 230, in internal_kv_get
    reply = self._kv_stub.InternalKVGet(req)
  File "/mnt/yic/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/mnt/yic/miniconda3/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.UNAVAILABLE
        details = "failed to connect to all addresses"
        debug_error_string = "{"created":"@1644570222.300159531","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":3093,"referenced_errors":[{"created":"@1644570222.300158761","description":"failed to connect to all addresses","file":"src/core/lib/transport/error_utils.cc","file_line":163,"grpc_status":14}]}"
>
```

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
in memory store is not handling the nullptr callback well which leads to gcs crash in node failure tests. This PR fixed it.

## Related issue number

Closes #22319 
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]

File: src/ray/gcs/store_client/in_memory_store_client.cc [hunk 1]
```diff
@@ -37,37 +40,45 @@ Status InMemoryStoreClient::AsyncPutWithIndex(const std::string &table_name,
...
+  RAY_CHECK(callback);
   auto table = GetOrCreateTable(table_name);
   absl::MutexLock lock(&(table->mutex_));
-  auto result = std::make_shared<std::unordered_map<std::string, std::string>>();
-  result->insert(table->records_.begin(), table->records_.end());
-  main_io_service_.post([result, callback]() { callback(std::move(*result)); },
-                        "GcsInMemoryStore.GetAll");
+  auto result = std::unordered_map<std::string, std::string>();
+  result.insert(table->records_.begin(), table->records_.end());
+  if (callback != nullptr) {
```
Comment (mwtian) [inline src/ray/gcs/store_client/in_memory_store_client.cc:77]: `callback` cannot be `nullptr` in this function? Or remove `RAY_CHECK(callback);`?

File: src/ray/gcs/store_client/test/store_client_test_base.h [hunk 2]
```diff
@@ -70,6 +70,8 @@ class StoreClientTestBase : public ::testing::Test {
       RAY_CHECK_OK(store_client_->AsyncPut(table_name_, elem.first.Binary(),
                                            elem.second.SerializeAsString(),
                                            put_calllback));
+      RAY_CHECK_OK(store_client_->AsyncPut(table_name_, elem.first.Binary(),
```
Comment (mwtian) [inline src/ray/gcs/store_client/test/store_client_test_base.h:73]: Add a comment about why we need the 2nd call with `nullptr` in addition to the same args?

**Review by mwtian — APPROVED** [review]

**Review by rkooo567 — APPROVED** [review]

**Comment by zhe-thoughts** [comment]
@iycheng Could you create a separate cherry-pick PR with the `1.11.0rc0-pick` label? Thanks!
