### PR TITLE
[Core] Use fd instead of handle for windows log redirection

### LINKED ISSUE #52739: [Core] `ray.init()` and `ray start` fails on Windows 11 in ray 2.45+
### What happened + What you expected to happen

Hello,

after installing latest release 2.45 - no upgrade, removed older release before - I notice following fundamental issue.

Calling ray start --head in CLI leads to following console output.

> (py311-raynew) C:\Users\Philipp>ray start --head
> Usage stats collection is disabled.
> 
> Local node IP: 192.168.178.26
> 2025-05-02 16:53:36,888 ERROR services.py:1362 -- Failed to start the dashboard , return code 3221226505
> 2025-05-02 16:53:36,888 ERROR services.py:1387 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/user-guides/configure-logging.html#logging-directory-structure' to find where the log file is.
> 2025-05-02 16:53:36,888 ERROR services.py:1397 -- Couldn't read dashboard.log file. Error: 'utf-8' codec can't decode byte 0xfc in position 40: invalid start byte. It means the dashboard is broken even before it initializes the logger (mostly dependency issues). Reading the dashboard.err file which contains stdout/stderr.
> 2025-05-02 16:53:36,888 ERROR services.py:1431 --
> The last 20 lines of C:\Users\Philipp\AppData\Local\Temp\ray\session_2025-05-02_16-53-32_217596_35728\logs\dashboard.err (it contains the error message from the dashboard):
> 
> Ray runtime started.

I am surprised that the app says "Ray runtime started", but I do not get` ray status` feedback.

> (py311-raynew) C:\Users\Philipp>ray status
> No cluster status. It may take a few seconds for the Ray internal services to start up.

Content of `dashboard.log` file

> 2025-05-02 16:53:33,639	ERROR dashboard.py:305 -- The dashboard on node PHILIPP-MAIN failed with the following error:
> Traceback (most recent call last):
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\dashboard\dashboard.py", line 247, in <module>
>     logging_utils.redirect_stdout_stderr_if_needed(
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\logging_utils.py", line 48, in redirect_stdout_stderr_if_needed
>     sys.stderr = open_log(stderr_fileno, unbuffered=True, closefd=False)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Philipp\anaconda3\envs\py311-raynew\Lib\site-packages\ray\_private\utils.py", line 446, in open_log
>     stream = open(path, **kwargs)
>              ^^^^^^^^^^^^^^^^^^^^
> OSError: [WinError 6] Das Handle ist ungültig

Content of `dashboard.error` file

> [0m

### Versions / Dependencies

ray == 2.45
Windows == 26100.3915

### Reproduction script

`> ray start --head`

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?

Windows has two sets of APIs for working with files. One is the WinAPI which works with `HANDLE`. The other is C API which works with `fd` (just like Unix). Currently in master we are mix using both and seems have caused issues like #52739. In this PR, we use the C API instead which is more consistent with the Unix code path.

`ray start` previously failed on my windows machine now passes with this PR.

## Related issue number

Closes #52739

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/util/compat.cc [hunk 1]
```diff
@@ -64,36 +64,39 @@ Status Flush(MEMFD_TYPE_NON_UNIQUE fd) {
...
   return Status::OK();
 }
-Status Flush(MEMFD_TYPE_NON_UNIQUE fd) {
-  if (!FlushFileBuffers(fd)) {
+Status Flush(int fd) {
+  HANDLE handle = reinterpret_cast<HANDLE>(_get_osfhandle(fd));
+  if (handle == INVALID_HANDLE_VALUE) {
+    return Status::IOError("") << "Fails to get file handle for flushing";
+  }
+  if (!FlushFileBuffers(handle)) {
```
Comment (jjyao) [inline src/ray/util/compat.cc:91]: For flush, there is no corresponding C API so we need to covert fd back to HANDLE and use the WinAPI

**Comment by edoakes** [comment]
Have you verified that this fixes the reported issue? If so, can you detail how you tested it?

File: src/ray/util/compat.cc (hunk 1 above)
Comment (edoakes) [reply src/ray/util/compat.cc:91]: will mixing the APIs in this way cause issues like the one this PR intends to fix?

**Comment by czgdp1807** [comment]
I tried it and it works,

```zsh
(ray-dev) PS C:\Users\czgdp1807\Anyscale\ray\python> ray start --head
Usage stats collection is enabled. To disable this, add `--disable-usage-stats` to the command that starts the cluster, or run the following command: `ray disable-usage-stats` before starting the cluster. See https://docs.ray.io/en/master/cluster/usage-stats.html for more details.

Local node IP: 127.0.0.1

--------------------
Ray runtime started.
--------------------

Next steps

  To connect to this Ray cluster:
    import ray
    ray.init()

  To terminate the Ray runtime, run
    ray stop

  To view the status of the cluster, use
    ray status
(ray-dev) PS C:\Users\czgdp1807\Anyscale\ray\python> ray status
======== Autoscaler status: 2025-06-17 17:50:13.618875 ========
Node status
---------------------------------------------------------------
Active:
 1 node_1f5d161361f94b4077b0d9ee34c485990b85c77bd55bd6db82d8766a
Pending:
 (no pending nodes)
Recent failures:
 (no failures)

Resources
---------------------------------------------------------------
Total Usage:
 0.0/4.0 CPU
 0B/7.21GiB memory
 0B/3.09GiB object_store_memory

Total Constraints:
 (no request_resources() constraints)
Total Demands:
 (no resource demands)
```

**Review by czgdp1807 — APPROVED** [review]
Seems like `fd`s are bing directly used in this PR and that's why its working on Windows 11.

File: src/ray/util/compat.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/util/compat.cc:91]: From the testing, it didn't cause issues.

I actually didn't fully understand the root cause. I initially started the PR just trying to simplify things by uniformly using fd and then realized that it fixed the issue.

One thing I noticed is that converting from HANDLE to fd transfer the ownership. But getting a HANDLE back from fd (`_get_osfhandle`) should be safe as long as we don't close the handle directly. All these are based on my very limited Windows knowledge.

```
The _open_osfhandle call transfers ownership of the Win32 file handle to the file descriptor. To close a file opened by using _open_osfhandle, call [_close](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/close?view=msvc-170). The underlying OS file handle is also closed by a call to _close. Don't call the Win32 function CloseHandle on the original handle. If the file descriptor is owned by a FILE * stream, then a call to [fclose](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fclose-fcloseall?view=msvc-170) closes both the file descriptor and the underlying handle. In this case, don't call _close on the file descriptor or CloseHandle on the original handle.
```

**Review by edoakes — APPROVED** [review]

**Comment by PhilippWillms** [comment]
Could we get a cherry-pick for that PR to be integrated in recently published 2.47 release?

**Comment by jjyao** [comment]
@PhilippWillms we will release it as 2.48 which should be released in 2-3 weeks. Would that work?

File: src/ray/util/compat.cc (hunk 1 above)
Comment (israbbani) [reply src/ray/util/compat.cc:91]: I don't pretend to understand this and the PR is merged, but could you please leave a comment in `compat.h` that describes your current understanding and can aid in future debugging? This might break again in the future.

File: src/ray/util/compat.cc [hunk 2]
```diff
@@ -64,36 +64,39 @@ Status Flush(MEMFD_TYPE_NON_UNIQUE fd) {
...
 #elif defined(_WIN32)
-Status CompleteWrite(MEMFD_TYPE_NON_UNIQUE fd, const char *data, size_t len) {
-  DWORD bytes_written;
-  BOOL success = WriteFile(fd, data, (DWORD)len, &bytes_written, NULL);
-  if (!success) {
-    return Status::IOError("") << "Fails to write to file";
+Status CompleteWrite(int fd, const char *data, size_t len) {
+  const int ret = _write(fd, data, len);
+  if (ret == -1) {
+    return Status::IOError("") << "Fails to write to file because " << strerror(errno);
```
Comment (israbbani) [inline src/ray/util/compat.cc:78]: s/Fails/Failed/

Comment (israbbani) [inline src/ray/util/compat.cc:78]: s/Fails/Failed/

File: src/ray/util/compat.cc [hunk 3]
```diff
@@ -64,36 +64,39 @@ Status Flush(MEMFD_TYPE_NON_UNIQUE fd) {
   }
   return Status::OK();
 }
-Status Close(MEMFD_TYPE_NON_UNIQUE fd) {
```
Comment (israbbani) [inline src/ray/util/compat.cc:67]: Why was this `MEMFD_TYPE_NON_UNIQUE` before and isn't that just an alias for `int` anyway?

File: src/ray/util/compat.cc [hunk 4]
```diff
@@ -64,36 +64,39 @@ Status Flush(MEMFD_TYPE_NON_UNIQUE fd) {
...
-  if (!success) {
-    return Status::IOError("") << "Fails to write to file";
+Status CompleteWrite(int fd, const char *data, size_t len) {
+  const int ret = _write(fd, data, len);
+  if (ret == -1) {
+    return Status::IOError("") << "Fails to write to file because " << strerror(errno);
   }
-  if ((DWORD)len != bytes_written) {
+  if (ret != static_cast<int>(len)) {
     return Status::IOError("") << "Fails to write all requested bytes, requests to write "
```
Comment (israbbani) [inline src/ray/util/compat.cc:81]: s/Fails/Failed/
s/write/wrote/

File: src/ray/util/pipe_logger.cc [hunk 5]
```diff
@@ -222,22 +194,24 @@ bool ShouldUsePipeStream(const StreamRedirectionOption &stream_redirect_opt) {
 }
 
 RedirectionFileHandle OpenFileForRedirection(const std::string &file_path) {
-  boost::iostreams::file_descriptor_sink fd_sink{file_path, std::ios_base::out};
-  auto handle = fd_sink.handle();
-  auto ostream =
-      std::make_shared<boost::iostreams::stream<boost::iostreams::file_descriptor_sink>>(
-          std::move(fd_sink));
+#if defined(__APPLE__) || defined(__linux__)
```
Comment (israbbani) [inline src/ray/util/pipe_logger.cc:197]: Probably also deserves a comment that explains the edge case that caused this issue.

**Review by israbbani — COMMENTED** [review]
I don't understand the change fully, but it might be worth documenting this in the code to aid future debugging.

Thanks for debugging and fixing this!

**Comment by PhilippWillms** [comment]
> @PhilippWillms we will release it as 2.48 which should be released in 2-3 weeks. Would that work?

Ok, fine for me.
