### PR TITLE
Redis returns OK when removing a non-existent set entry

### LINKED ISSUE #4406: Redis LRU plus object store LRU can lead to fatal crash.
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS
- **Ray installed from (source or binary)**: source
- **Ray version**: `0.7.0.dev1`
- **Python version**: 3.6.4
- **Exact command to reproduce**:

```python
import numpy as np
import ray

ray.init(object_store_memory=10**8)

x = np.zeros(8*10**7, dtype=np.uint8)
x_id = ray.put(x)

# Remove the object from the object table to simulate Redis LRU eviction.
assert ray.global_state.redis_clients[0].delete(b'OBJECT' + x_id.binary()) == 1

# Now evict the object from the object store.
ray.put(x)  # This will crash.
```

The raylet crashes with **Redis error: ERR The entry to remove doesn't exist.**:

```
F0318 19:14:06.948998 2466321280 redis_context.cc:58] Redis error: ERR The entry to remove doesn't exist.
*** Check failure stack trace: ***
*** Aborted at 1552961646 (unix time) try "date -d @1552961646" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x7fff5a64ab66) received by PID 43368 (TID 0x7fff93011380) stack trace: ***
    @     0x7fff5a808f5a _sigtramp
    @                0x0 (unknown)
    @     0x7fff5a5a61ae abort
    @        0x104bb5cb9 google::logging_fail()
    @        0x104bb4992 google::LogMessage::SendToLog()
    @        0x104bb5095 google::LogMessage::Flush()
    @        0x104bb5172 google::LogMessage::~LogMessage()
    @        0x104bae955 ray::RayLog::~RayLog()
    @        0x104b33dc3 ray::gcs::GlobalRedisCallback()
    @        0x104b97fad redisProcessCallbacks
    @        0x104b2ae5a RedisAsioClient::handle_read()
    @        0x104b2b4ac boost::asio::detail::reactive_null_buffers_op<>::do_complete()
    @        0x104aa77af boost::asio::detail::scheduler::do_run_one()
    @        0x104aa71d2 boost::asio::detail::scheduler::run()
    @        0x104a9c44e main
    @     0x7fff5a4fa015 start
    @               0x10 (unknown)
```

This is related to https://github.com/ray-project/ray/pull/4199. cc @stephanie-wang @kfstorm Thoughts about the best way to fix this?

### PR DESCRIPTION
**Pull request by kfstorm**
## What do these changes do?

When trying to remove an non-existent set entry from GCS, instead of returning error from redis, return OK and log an error message.
## Related issue number

Fixes #4406

### CODE REVIEW

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 1]
```diff
@@ -514,8 +514,12 @@ int SetRemove_RedisCommand(RedisModuleCtx *ctx, RedisModuleString **argv, int ar
   if (Set_DoWrite(ctx, argv, argc, /*is_add=*/false, &changed) != REDISMODULE_OK) {
     return REDISMODULE_ERR;
   }
-  REPLY_AND_RETURN_IF_FALSE(changed, "ERR The entry to remove doesn't exist.");
-  return Set_DoPublish(ctx, argv, /*is_add=*/false);
+  if (changed) {
+    return Set_DoPublish(ctx, argv, /*is_add=*/false);
+  } else {
+    RAY_LOG(ERROR) << "The entry to remove doesn't exist.";
```
Comment (kfstorm) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: Do we still need to publish the update if the entry doesn't exist?

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 2]
```diff
@@ -491,7 +491,7 @@ int SetAdd_RedisCommand(RedisModuleCtx *ctx, RedisModuleString **argv, int argc)
   if (changed) {
     return Set_DoPublish(ctx, argv, /*is_add=*/true);
   }
-  return REDISMODULE_OK;
+  return RedisModule_ReplyWithSimpleString(ctx, "OK");
```
Comment (kfstorm) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: This fixes a bug in #4199: The `RAY.SET_ADD` command have no reply if trying to add a duplicate entry.

**Review by robertnishihara — APPROVED** [review]
This looks good to me assuming the tests pass, thanks!

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 2 above)
Comment (robertnishihara) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: I think either way would be ok.

**Comment by guoyuhong** [comment]
@AmplabJenkins retest this, please.

File: python/ray/tests/test_basic.py [hunk 3]
```diff
@@ -2840,3 +2840,23 @@ def test_shutdown_disconnect_global_state():
     with pytest.raises(Exception) as e:
         ray.global_state.object_table()
     assert str(e.value).endswith("ray.init has been called.")
+
+
+def test_redis_lru_with_set(shutdown_only):
+    ray.init(object_store_memory=10**8)
```
Comment (guoyuhong) [inline python/ray/tests/test_basic.py]: Do you need use many cpus? You can use `ray_start_regular` according to https://github.com/ray-project/ray/pull/4390 . Now the test fixtures is refactors and we want the user to avoid using `shutdown_only`, because there is some default test setting can be applied. `object_store_memory=10**8` is one of the default setting.

**Review by guoyuhong — APPROVED** [review]
I left one comment. Other part looks good to me.

File: python/ray/tests/test_basic.py (hunk 3 above)
Comment (kfstorm) [reply python/ray/tests/test_basic.py]: Replaced `shutdown_only` with `ray_start_object_store_memory`
