### PR TITLE
[core] Nested task support via task depth + backpressure

### LINKED ISSUE #16973: Improve handling of nested tasks to avoid crashing due to too many workers
When a workload of nested tasks executes, Ray should prioritize launching under-represented task classes. For example, in the following workload:

```
ray.init(num_cpus=2)

@ray.remote
def outer():
   return ray.get(inner.remote())

@ray.remote
def inner():
  return 0

ray.get([f.remote() for _ in range(1000)])
```

Ray should be executing at most 2 concurrent instances of `outer`. Priority should be given to scheduling `inner` tasks. This may be a regression.

cc @wuisawesome @stephanie-wang @anabranch

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This PR makes a couple of scheduling changes to improve the usability of nested tasks. 

1. It adds depth to the scheduling class. Every task's depth is 1 greater than its owner's depth. The depth of an actor task is the same as that of its actor creation task.
2. Adds back pressure to the scheduling of a given scheduling class. In particular it ensures that no more than `node_cpus / task_cpus` worth of a given task run on the node. For example, if a node has 4 cpus and `foo` requires 2. Then only 2 instances of `foo` can run on the node at once, even if those 2 instances are blocked and have released their cpu. 

Incidental bug fixes that this uncovered:
* Ensure that worker processes always release their resources at the right time rather than just waiting for shutdown. 

## Related issue number

Closes #16973

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -1641,13 +1641,18 @@ void CoreWorker::SubmitTask(const RayFunction &function,
       task_options.override_environment_variables;
   override_environment_variables.insert(current_override_environment_variables.begin(),
                                         current_override_environment_variables.end());
+  int64_t depth;
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc:1644]: It would be good if we could avoid putting a lock around depth, since there's only one thread accessing it anyway.

Can we move it to the WorkerContext, which is already tracking current task index, etc?

File: python/ray/tests/test_basic_3.py [hunk 2]
```diff
@@ -136,12 +136,12 @@ def f(block, accepted_resources):
 def test_background_tasks_with_max_calls(shutdown_only):
     ray.init(num_cpus=2)
 
-    @ray.remote
+    @ray.remote(num_cpus=0)
```
Comment (stephanie-wang) [inline python/ray/tests/test_basic_3.py:139]: Why the change?

File: python/ray/tests/test_scheduling.py [hunk 3]
```diff
@@ -519,6 +519,26 @@ def f(s, ref):
...
+    def g():
+        return ray.get(h.remote())
+
+    @ray.remote(num_cpus=1, resources={"worker": 1})
+    def f():
+        return ray.get(g.remote())
+
+    ready, _ = ray.wait(
+        [f.remote() for _ in range(1000)], timeout=60.0, num_returns=1000)
+    assert len(ready) == 1000, len(ready)
```
Comment (stephanie-wang) [inline python/ray/tests/test_scheduling.py:539]: Can we check the number of workers that were started?

Can we add a recursive test that checks for deadlock (and make sure it actually deadlocks if we don't add depth to the scheduling class)?

File: src/ray/common/task/task_spec.h [hunk 4]
```diff
@@ -31,9 +31,33 @@ extern "C" {
...
+  FunctionDescriptor function_descriptor;
+  int64_t depth;
+
+  bool operator==(const SchedulingClassDescriptor &other) const {
+    bool resource_sets_match = resource_set == other.resource_set;
+    bool functions_match = function_descriptor == other.function_descriptor;
+    bool depth_match = depth == other.depth;
+    return resource_sets_match && functions_match && depth_match;
+  }
+  struct hash_fn {
```
Comment (stephanie-wang) [inline src/ray/common/task/task_spec.h:51]: Specialize std::hash so we don't need to pass this everywhere?

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -1861,14 +1871,18 @@ void CoreWorker::SubmitActorTask(const ActorID &actor_id, const RayFunction &fun
                              ? function.GetFunctionDescriptor()->DefaultTaskName()
                              : task_options.name;
   const std::unordered_map<std::string, std::string> override_environment_variables = {};
+  int64_t depth;
+  {
+    absl::MutexLock lock(&mutex_);
+    depth = current_task_.GetDepth();
```
Comment (stephanie-wang) [inline src/ray/core_worker/core_worker.cc:1877]: Why not +1?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 6]
```diff
@@ -1289,5 +1247,16 @@ ResourceSet ClusterTaskManager::CalcNormalTaskResources() const {
   return total_normal_task_resources;
 }
 
+uint64_t ClusterTaskManager::MaxRunningTasksPerSchedulingClass(
+    SchedulingClass sched_cls_id) const {
+  auto sched_cls = TaskSpecification::GetSchedulingClassDescriptor(sched_cls_id);
+  double cpu_req = sched_cls.resource_set.GetNumCpusDouble();
+  // Handle the num_cpus=0 edge case.
+  cpu_req = std::max(cpu_req, 0.01);
+  uint64_t total_cpus = cluster_resource_scheduler_->GetNumCpus();
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:1256]: We should return INT_MAX if we have 0 CPUs on this node. Can we add a Python test to make sure tasks still get scheduled in this case?

It would be nice to make this caluclation a method of `SchedulingClassDescriptor`.

File: src/ray/raylet/scheduling/cluster_task_manager.h [hunk 7]
```diff
@@ -267,6 +275,8 @@ class ClusterTaskManager : public ClusterTaskManagerInterface {
   std::unordered_map<SchedulingClass, std::deque<std::shared_ptr<Work>>>
       tasks_to_schedule_;
 
+  absl::flat_hash_map<SchedulingClass, uint64_t> scheduling_backpressure_tracker_;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.h:278]:
```suggestion
  absl::flat_hash_map<SchedulingClass, uint64_t> num_running_tasks_by_scheduling_cls_;
```

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 8]
```diff
@@ -97,6 +101,7 @@ bool ClusterTaskManager::SchedulePendingTasks() {
       if (node_id_string == self_node_id_.Binary()) {
         // Warning: WaitForTaskArgsRequests must execute (do not let it short
         // circuit if did_schedule is true).
+        scheduling_backpressure_tracker_[sched_cls]++;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:104]: Shouldn't we do this when the task actually gets dispatched? Otherwise, we will not fetch args, etc.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 9]
```diff
@@ -709,51 +716,8 @@ void ClusterTaskManager::FillResourceUsage(
 
   int num_reported = 0;
 
-  // 1-CPU optimization
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:712]: Why the removal?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 10]
```diff
@@ -125,7 +125,7 @@ RayTask CreateTask(const std::unordered_map<std::string, double> &required_resou
       id, "dummy_task", Language::PYTHON,
       FunctionDescriptorBuilder::BuildPython("", "", "", ""), job_id, TaskID::Nil(), 0,
       TaskID::Nil(), address, 0, required_resources, {},
-      std::make_pair(PlacementGroupID::Nil(), -1), true, "", serialized_runtime_env);
+      std::make_pair(PlacementGroupID::Nil(), -1), true, "", 0, serialized_runtime_env);
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:128]: Can we add a C++ test for the worker cap?

**Review by stephanie-wang — CHANGES_REQUESTED** [review]

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 11]
```diff
@@ -63,9 +63,13 @@ bool ClusterTaskManager::SchedulePendingTasks() {
   bool did_schedule = false;
   for (auto shapes_it = tasks_to_schedule_.begin();
        shapes_it != tasks_to_schedule_.end();) {
+    auto sched_cls = shapes_it->first;
     auto &work_queue = shapes_it->second;
+    auto max_running_tasks = MaxRunningTasksPerSchedulingClass(sched_cls);
     bool is_infeasible = false;
-    for (auto work_it = work_queue.begin(); work_it != work_queue.end();) {
+    for (auto work_it = work_queue.begin();
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:70]: Can you add a comment here to explain why we cap tasks by scheduling class? It's nice to have the explanation inline so we don't have to go to github to understand the code.

File: python/ray/tests/test_scheduling.py (hunk 3 above)
Comment (wuisawesome) [reply python/ray/tests/test_scheduling.py:539]: Hmm the worker resource isn't released on `ray.get`, so I believe this test should be ensuring that only 3 workers are used. (I suppose it's possible that the worker pool is starting other idle workers, but that doesn't exactly seem relevant for this test?). 

I can add a comment about that, and add a test for the recursive case though.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 8 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:104]: hmm if we do that, won't we end up in a case where the task can be scheduled on another node, but is still blocked on this node due to the cap?

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 9 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:712]: There isn't really a canonical task shape any more once function descriptors are added to the scheduling class. Also, in practice, I think we always send all resource shapes with every request, so it shouldn't lead to any regressions.

File: python/ray/tests/test_scheduling.py (hunk 3 above)
Comment (stephanie-wang) [reply python/ray/tests/test_scheduling.py:539]: I see, that seems pretty dependent on the fact that we're not releasing the "worker" resource, though. Could we somehow add a check for the number of workers started or the number of concurrently running tasks (e.g., with a Counter actor)? It would be good to directly check the condition that we care about that.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 8 above)
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:104]: I think it would make more sense to check the cap on dispatch, then try spillback if the task is not schedulable due to the cap (same as we do if there are no local resources available). That should achieve the same effect and we can reuse an existing codepath to block dispatch.

But in general, I think this corner case is not worth worrying about right now. In the common case, the driver should already have requested leases for the same scheduling class at the other raylet.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 9 above)
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:712]: I see, I've lost the context for this part of the code. But as long as we have regression tests, I'm fine with it.

File: python/ray/tests/test_basic_3.py [hunk 12]
```diff
@@ -136,12 +136,12 @@ def f(block, accepted_resources):
...
     def g():
         time.sleep(.1)
         return 0
 
-    @ray.remote(max_calls=1, max_retries=0)
+    @ray.remote(num_cpus=0, max_calls=1, max_retries=0)
```
Comment (ericl) [inline python/ray/tests/test_basic_3.py:144]: Please revert these changes.

File: python/ray/tests/test_scheduling.py [hunk 13]
```diff
@@ -519,6 +519,26 @@ def f(s, ref):
     wait_for_condition(lambda: not fetches_queued())
 
 
+def test_nested_tasks(shutdown_only):
+    ray.init(num_cpus=1, resources={"worker": 3})
+
+    @ray.remote(num_cpus=1, resources={"worker": 1})
```
Comment (ericl) [inline python/ray/tests/test_scheduling.py:525]: Can you make the test not use this weird "worker" resource? It's not testing the original issue.

Instead, you can use a counter actor to track max number of instances of each task type.

File: python/ray/tests/test_basic_3.py [hunk 14]
```diff
@@ -163,29 +163,6 @@ def f():
...
-
-    @ray.remote
-    def f():
-        return ray.get(g.remote())
-
-    # This will never finish without fair queueing of {f, g, h}:
-    # https://github.com/ray-project/ray/issues/3644
-    ready, _ = ray.wait(
-        [f.remote() for _ in range(1000)], timeout=60.0, num_returns=1000)
-    assert len(ready) == 1000, len(ready)
```
Comment (ericl) [inline python/ray/tests/test_basic_3.py:186]: Please restore this unit test.

**Review by ericl — CHANGES_REQUESTED** [review]
Please add a C++ unit test for capping in cluster_task_manager_test, and address the comments on the Python test layer.

File: python/ray/tests/test_scheduling.py (hunk 13 above)
Comment (wuisawesome) [reply python/ray/tests/test_scheduling.py:525]: This worker resource guarantees that we have exactly one of each task type running though. Otherwise we're going to go back to relying on timing, which clearly wasn't reliable before.

Comment (ericl) [reply python/ray/tests/test_scheduling.py:525]: Doesn't the capping guarantee the max number per type regardless of timing?

**Comment by ericl** [comment]
Please add a new unit test specifically for this issue that checks the invariant via a counter actor that the capping is working; and also leave the existing unit tests alone.

File: python/ray/tests/test_cancel.py [hunk 15]
```diff
@@ -23,7 +23,7 @@ def valid_exceptions(use_force):
 def test_cancel_chain(ray_start_regular, use_force):
     signaler = SignalActor.remote()
 
-    @ray.remote
+    @ray.remote(num_cpus=0)
```
Comment (wuisawesome) [inline python/ray/tests/test_cancel.py:26]: These changes are necessary because the test relies on running more than num_cpus of `wait_for` concurrently.

File: python/ray/tests/test_basic.py [hunk 16]
```diff
@@ -37,7 +37,10 @@ def test_release_resources_race(shutdown_only):
     ray.init(
         num_cpus=2,
         object_store_memory=700e6,
-        _system_config={"inline_object_status_in_refs": True})
+        _system_config={
+            "inline_object_status_in_refs": True,
+            "worker_lease_timeout_milliseconds": 1000
```
Comment (wuisawesome) [inline python/ray/tests/test_basic.py:42]: This test seems to fail due to lease expiration without this. I don't think this should be a problem, but if it is, we should rely on microbenchmarks to catch it, not this test.

**Review by stephanie-wang — COMMENTED** [review]
Hmm can you explain the new changes around the worker leasing? I didn't have much context there, but ideally we should try to keep all the changes contained to `ClusterTaskManager`.

File: src/ray/raylet_client/raylet_client.h [hunk 17]
```diff
@@ -75,7 +75,7 @@ class WorkerLeaseInterface {
   /// \param disconnect_worker Whether the raylet should disconnect the worker.
```
Comment (iycheng) [inline src/ray/raylet_client/raylet_client.h:75]: update the doc here?

File: src/ray/common/task/scheduling_resources.cc [hunk 18]
```diff
@@ -189,6 +189,11 @@ const ResourceSet ResourceSet::GetNumCpus() const {
   return cpu_resource_set;
 }
 
+double ResourceSet::GetNumCpusDouble() const {
```
Comment (iycheng) [inline src/ray/common/task/scheduling_resources.cc:192]: no strong opinion here, but just feel GetNumCpusDouble looks bad.

One way to work around for this one is: 

```
template<typename T>
T ResourceSet::GetNumCpus() const {
}
```

File: src/ray/common/task/task_spec.cc [hunk 19]
```diff
@@ -92,10 +93,13 @@ void TaskSpecification::ComputeResources() {
   if (!IsActorTask()) {
     // There is no need to compute `SchedulingClass` for actor tasks since
     // the actor tasks need not be scheduled.
-
+    auto resource_set = GetRequiredResources();
```
Comment (iycheng) [inline src/ray/common/task/task_spec.cc:96]: const auto& ?

File: src/ray/common/task/task_spec.cc [hunk 20]
```diff
@@ -92,10 +93,13 @@ void TaskSpecification::ComputeResources() {
...
+    auto function_descriptor = FunctionDescriptor();
```
Comment (iycheng) [inline src/ray/common/task/task_spec.cc:97]: ditto

File: src/ray/common/task/task_spec.h [hunk 21]
```diff
@@ -29,11 +29,41 @@
...
 }
-
 namespace ray {
-typedef ResourceSet SchedulingClassDescriptor;
+/* typedef ResourceSet SchedulingClassDescriptor; */
 typedef int SchedulingClass;
 
+struct SchedulingClassDescriptor {
+ public:
+  explicit SchedulingClassDescriptor(ResourceSet &rs, FunctionDescriptor &fd, int64_t d)
```
Comment (iycheng) [inline src/ray/common/task/task_spec.h:38]: If there is a copy, usually we do either:

```
struct A {
A(const std::string& f): field(f) {}
std::string field;
}
```
or
```
struct A {
A(std::string f): field(std::move(f)) {}
std::string field;
}
```

(Prefer the later one since it gives the caller the ability to move).

So here, please add const to `fd` and `rs`.

File: src/ray/common/task/task_spec.h [hunk 22]
```diff
@@ -29,11 +29,41 @@
...
+      : resource_set(rs), function_descriptor(fd), depth(d) {}
+  ResourceSet resource_set;
+  FunctionDescriptor function_descriptor;
+  int64_t depth;
+
+  bool operator==(const SchedulingClassDescriptor &other) const {
```
Comment (iycheng) [inline src/ray/common/task/task_spec.h:44]: Use

```
return depth == other.depth && 
    resource_set == other.resource_set && 
    function_descriptor == other.function_descriptor && 
```
for the following reasons:
1. Short-circuit return
2. depth is cheaper to compare

File: src/ray/protobuf/common.proto [hunk 23]
```diff
@@ -218,12 +218,15 @@ message TaskSpec {
   // Breakpoint if this task should drop into the debugger when it starts executing
   // and "" if the task should not drop into the debugger.
   bytes debugger_breakpoint = 23;
+  // The depth of the task. The driver has depth 0, anything it calls has depth
+  // 1, etc.
+  int64 depth = 24;
```
Comment (iycheng) [inline src/ray/protobuf/common.proto:223]: why put it here but not just put it at the end?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 24]
```diff
@@ -1299,5 +1266,19 @@ ResourceSet ClusterTaskManager::CalcNormalTaskResources() const {
...
 
+uint64_t ClusterTaskManager::MaxRunningTasksPerSchedulingClass(
+    SchedulingClass sched_cls_id) const {
+  auto sched_cls = TaskSpecification::GetSchedulingClassDescriptor(sched_cls_id);
+  double cpu_req = sched_cls.resource_set.GetNumCpusDouble();
+  // Handle the num_cpus=0 edge case.
+  cpu_req = std::max(cpu_req, 0.01);
+  uint64_t total_cpus = cluster_resource_scheduler_->GetNumCpus();
+  if (total_cpus == 0) {
+    total_cpus = INT_MAX;
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:1277]: INT_MAX is for int32.

Do you mean, std::numeric_limits<uint64_t>::max() ?

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 25]
```diff
@@ -606,16 +607,9 @@ void CoreWorkerDirectTaskSubmitter::PushNormalTask(
...
-            // it to the Raylet since that will kill it early.
-            worker_to_lease_entry_.erase(addr);
-            auto &scheduling_key_entry = scheduling_key_entries_[scheduling_key];
-            scheduling_key_entry.active_workers.erase(addr);
-            if (scheduling_key_entry.CanDelete()) {
-              // We can safely remove the entry keyed by scheduling_key from the
-              // scheduling_key_entries_ hashmap.
-              scheduling_key_entries_.erase(scheduling_key);
-            }
+            // Since this worker is draining, make sure the raylet doesn't
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/core_worker/transport/direct_task_transport.cc:597]: It seems we do :(. This fixes a bug where worker processes weren't returned they were killed (which could be quite late since they don't die until their ref counts go away). It seems we most likely didn't notice before because we did unblock the worker, which freed the CPUs.

File: src/ray/core_worker/transport/dependency_resolver.cc [hunk 26]
```diff
@@ -119,7 +119,8 @@ void LocalDependencyResolver::ResolveDependencies(
       {
         absl::MutexLock lock(&mu_);
         state->local_dependencies[obj_id] = std::move(obj);
-        if (--state->obj_dependencies_remaining == 0) {
+        if (--state->obj_dependencies_remaining == 0 &&
```
Comment (wuisawesome) [inline src/ray/core_worker/transport/dependency_resolver.cc:122]: @stephanie-wang I needed to do this to fix `test_reference_counting.py::test_dependency_refcounts` (this is the same test that's been broken on windows). I'm wondering if this PR just made the bug more frequent on other platforms?

File: src/ray/common/task/task_spec.h [hunk 27]
```diff
@@ -29,11 +29,41 @@
 extern "C" {
 #include "ray/thirdparty/sha256.h"
 }
-
 namespace ray {
-typedef ResourceSet SchedulingClassDescriptor;
+/* typedef ResourceSet SchedulingClassDescriptor; */
```
Comment (iycheng) [inline src/ray/common/task/task_spec.h:33]: remove completely?

File: src/ray/core_worker/core_worker.cc [hunk 28]
```diff
@@ -3062,16 +3062,15 @@ void CoreWorker::HandleExit(const rpc::ExitRequest &request, rpc::ExitReply *rep
...
-      [this, is_idle]() {
-        // If the worker is idle, we exit.
-        if (is_idle) {
-          Exit(rpc::WorkerExitType::IDLE_EXIT);
-        }
-      },
-      // We need to kill it regardless if the RPC failed.
-      [this]() { Exit(rpc::WorkerExitType::INTENDED_EXIT); });
+  send_reply_callback(Status::OK(),
+                      [this, is_idle]() {
```
Comment (iycheng) [inline src/ray/core_worker/core_worker.cc:3066]: I actually like the old formatter better. :(

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 29]
```diff
@@ -622,6 +623,7 @@ void CoreWorkerDirectTaskSubmitter::PushNormalTask(
           if (!task_spec.GetMessage().retry_exceptions() ||
               !reply.is_application_level_error() ||
               !task_finisher_->RetryTaskIfPossible(task_id)) {
+            RAY_LOG(ERROR) << "Completing pending task: " << task_id;
```
Comment (iycheng) [inline src/ray/core_worker/transport/direct_task_transport.cc:626]: Remove

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 30]
```diff
@@ -341,6 +341,8 @@ void CoreWorkerDirectTaskSubmitter::OnWorkerIdle(
     while (!current_queue.empty() &&
            !lease_entry.PipelineToWorkerFull(max_tasks_in_flight_per_worker_)) {
       auto task_spec = current_queue.front();
```
Comment (iycheng) [inline src/ray/core_worker/transport/direct_task_transport.cc:343]: auto task_spec = std::move(current_queue.front());

File: src/ray/core_worker/transport/dependency_resolver.cc (hunk 26 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/dependency_resolver.cc:122]: Please revert this, should be fixed in #18862.

**Comment by stephanie-wang** [comment]
@wuisawesome can you resolve the conflicts?

File: src/ray/core_worker/core_worker.cc (hunk 5 above)
Comment (wuisawesome) [reply src/ray/core_worker/core_worker.cc]: added comment, but it doesn't really matter since depth is inherited from its actor creation task

File: src/ray/raylet/node_manager.cc [hunk 31]
```diff
@@ -1654,11 +1653,19 @@ void NodeManager::HandleReturnWorker(const rpc::ReturnWorkerRequest &request,
         HandleDirectCallTaskUnblocked(worker);
       }
       cluster_task_manager_->ReturnWorkerResources(worker);
-      HandleWorkerAvailable(worker);
+      // The worker may not be reusable (i.e. already exiting).
+      if (request.reuse_worker()) {
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/node_manager.cc:1667]: Same as here: https://github.com/ray-project/ray/pull/17887/files?authenticity_token=w%2BcY8Uy8zeHPUKHnkYDcV5v5f2m9xxF5k1bARsB7aqcZlQaMQ6amo4f%2BYcZY73eINGONKBvqKqAidTXscWnaNA%3D%3D&file-filters%5B%5D=.cc#r717182437

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 32]
```diff
@@ -454,11 +462,18 @@ void ClusterTaskManager::TasksUnblocked(const std::vector<TaskID> &ready_ids) {
...
+    return;
+  }
   *task = worker->GetAssignedTask();
+  auto sched_cls = task->GetTaskSpecification().GetSchedulingClass();
+  num_running_tasks_by_sched_cls_[sched_cls]--;
   ReleaseTaskArgs(task->GetTaskSpecification().TaskId());
   if (worker->GetAllocatedInstances() != nullptr) {
     ReleaseWorkerResources(worker);
   }
+  ScheduleAndDispatchTasks();
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:476]: I think we should always try to schedule and dispatch when we release args/resources since that frees up potential tasks on the dispatch queue.

File: src/ray/raylet/node_manager.cc [hunk 33]
```diff
@@ -1239,6 +1236,9 @@ void NodeManager::DisconnectClient(
       }
     }
 
+    // Erase any lease metadata.
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/node_manager.cc:1250]: This was just aesthetic (clear up all the data structures together)

File: src/ray/core_worker/core_worker.cc (hunk 28 above)
Comment (wuisawesome) [reply src/ray/core_worker/core_worker.cc]: i agree, but don't know how to get the linter to do that :(

File: src/ray/common/task/task_spec.h (hunk 21 above)
Comment (wuisawesome) [reply src/ray/common/task/task_spec.h:38]: the second one looks better, so let's do that?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 34]
```diff
@@ -454,11 +462,18 @@ void ClusterTaskManager::TasksUnblocked(const std::vector<TaskID> &ready_ids) {
 void ClusterTaskManager::TaskFinished(std::shared_ptr<WorkerInterface> worker,
                                       RayTask *task) {
   RAY_CHECK(worker != nullptr && task != nullptr);
+  if (leased_workers_.count(worker->WorkerId()) == 0) {
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:465]: why is count a leaky abstraction here? i'm mostly worried that we don't consistently unset these things (we don't event have that op for task id and task), we rely on removing them from the map so it would be easy to miss edge cases if we tried that.

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc [hunk 35]
```diff
@@ -865,10 +872,13 @@ void ClusterResourceScheduler::UpdateLocalAvailableResourcesFromResourceInstance
   auto local_view = it_local_node->second.GetMutableLocalView();
   for (size_t i = 0; i < PredefinedResources_MAX; i++) {
     local_view->predefined_resources[i].available = 0;
+    local_view->predefined_resources[i].total = 0;
```
Comment (wuisawesome) [inline src/ray/raylet/scheduling/cluster_resource_scheduler.cc:875]: Incidental bug fix that the unit test hits (actually i wonder if this could be related to the placement group instability issues?)

Comment (iycheng) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:875]: i think it could be. the value should be undefined.

File: python/ray/data/tests/test_dataset_pipeline.py [hunk 36]
```diff
@@ -129,7 +129,11 @@ def test_split(ray_start_regular_shared):
         .map(lambda x: x + 1) \
         .repeat(10)
 
-    @ray.remote
+    # We need all the `consume` tasks to run concurrently. Since the
+    # PipelineSplitExecutorCoordinator won't move on to the next chunk until
+    # all the shards of the first split are processed. Note that the other
+    # consume tasks can't run when one of them releases its cpu.
+    @ray.remote(num_cpus=0)
```
Comment (ericl) [inline python/ray/data/tests/test_dataset_pipeline.py:136]: If we are disabling the limit for when object references are passed, can we remove the num_cpus=0 in the dataset tests?

File: python/ray/tests/test_cancel.py [hunk 37]
```diff
@@ -129,7 +129,7 @@ def wait_for(t):
 def test_comprehensive(ray_start_regular, use_force):
     signaler = SignalActor.remote()
 
-    @ray.remote
+    @ray.remote(num_cpus=0)
```
Comment (ericl) [inline python/ray/tests/test_cancel.py:132]: Can we remove this now?

File: python/ray/tests/test_client_terminate.py [hunk 38]
```diff
@@ -53,7 +53,7 @@ def test_cancel_chain(ray_start_regular, use_force):
         SignalActor = create_remote_signal_actor(ray)
         signaler = SignalActor.remote()
 
-        @ray.remote
+        @ray.remote(num_cpus=0)
```
Comment (ericl) [inline python/ray/tests/test_client_terminate.py:56]: etc.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 39]
```diff
@@ -908,6 +871,24 @@ bool ClusterTaskManager::AnyPendingTasks(RayTask *exemplar, bool *any_pending,
...
+  std::stringstream stream;
+  stream << "tasks_to_schedule:\n";
+  for (const auto &pair : tasks_to_schedule_) {
+    const auto &queue = pair.second;
+    for (const auto &work_ptr : queue) {
+      const auto &task = work_ptr->task;
+      stream << "\t" << task.DebugString() << "\n";
+    }
+  }
+  stream << "tasks_to_dispatch:\n";
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:883]: Remove debugging statements.

**Comment by ericl** [comment]
@wuisawesome @stephanie-wang what was the final strategy for how to resolve the deadlock issue with references to tasks of the same class? Is that implemented (it doesn't seem to be in the PR description).

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 25 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.cc:598]: I'm not sure I understand why this is needed. If the worker is exiting anyway, why would it matter if we return it or not? I also don't understand what this has to do with the rest of the PR. Does it make sense to separate this part out and test it separately?

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 34 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:465]: What I meant is that this is checking whether the worker is in the leased workers map, but this class doesn't actually erase from that map. So the logic here is not self-contained and e2e correctness depends on an implicit assumption about the caller (brittle).

Put another way, we want to write this in a way that is unit-testable. Currently, it's not because there's no way to test that the NodeManager is updating leased_workers_ and calling this method in the correct order.

**Comment by wuisawesome** [comment]
I believe we wanted to get this PR merged first and then handle the deadlock issue in a separate PR. (cc @iycheng).

This PR is already doing 2 things with more minor bug fixes, and the issue it causes for workflows is very limited in scope. 

If we're in agreement that we want to try to detect nested object refs in args, then we should probably do that in a separate pr.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 32 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:476]: Can you revert this unless it's necessary for the PR? It would be best to keep the changes specific to the original issue.

File: python/ray/tests/test_scheduling.py (hunk 3 above)
Comment (stephanie-wang) [reply python/ray/tests/test_scheduling.py:553]: Bump?

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Still have some outstanding comments about testing.

**Comment by stephanie-wang** [comment]
Hold on, I think we should try to address the workflows issue before merging. I thought that we agreed it's a more general problem with wrapped ObjectRefs, not just workflows.

Also, @wuisawesome can you split out any code not related to this PR and file issues as necessary? We should try to limit the changes in the PR to the original issue.

**Comment by ericl** [comment]
We can't push that into a separate PR since this would break existing
workloads right? Or at least we need to feature flag this.

File: python/ray/tests/test_scheduling.py (hunk 3 above)
Comment (wuisawesome) [reply python/ray/tests/test_scheduling.py:553]: This uses the counter and not worker resource now?

I think this particular line of code just didn't change

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 32 above)
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:476]: I mean I think this _is_ necessary since we're calling `ReturnWorker` more often now (and in the scheduling unit tests that I added there aren't many other triggers that call `ScheduleAndDispatch`).

[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:476]: What I meant is that I would like to see an end-to-end example in C++ or ideally Python that shows that this is necessary.

File: python/ray/tests/test_scheduling.py (hunk 3 above)
Comment (stephanie-wang) [reply python/ray/tests/test_scheduling.py:553]: I see, I think I was looking at an old version of the PR.

I'm not sure where my comment went, but I think there is still an issue with this test because ray.wait doesn't throw exceptions. Can you use ray.get and make sure that this actually fails on master?

**Comment by wuisawesome** [comment]
I've added the feature flag (probably a good idea in general). 

>I thought that we agreed it's a more general problem with wrapped ObjectRefs, not just workflows.

Agreed, but workflows is the only known workload where this issue comes up, since it requires (1) a small number of cpus in the cluster (2) a task need to fail due to a system error and be retried. 

Frankly, I'm pretty sure this corner case isn't going to break anyone's workload. If we have concerns about breaking people's workloads, I'd be more concerned about the overall scheduling policy change in this PR (see all the tests that needed to be changed). 

I can pull all the bug fixes out, but I suspect they're quite hard to test without this PR, and will delay this PR (again). Another way to think about it maybe is that they weren't "bugs" in the sense that the e2e behavior looks ok, but the system just wasn't behaving the way we thought it was.

**Comment by stephanie-wang** [comment]
> Agreed, but workflows is the only known workload where this issue comes up, since it requires (1) a small number of cpus in the cluster (2) a task need to fail due to a system error and be retried.

Not sure if I agree with this. It seems possible to trigger just based on the order that tasks get scheduled, which is nondeterministic. But if this is behind a feature flag, seems fine for now.

> I can pull all the bug fixes out, but I suspect they're quite hard to test without this PR, and will delay this PR (again). Another way to think about it maybe is that they weren't "bugs" in the sense that the e2e behavior looks ok, but the system just wasn't behaving the way we thought it was.

In general, I strongly believe that we should not merge PRs that have additional changes in them unless they're necessary for correctness of the PR. It makes reviewing and code maintenance more difficult. For example, if one of these additional changes happens to cause a regression, we'd have to revert this whole PR. It also concerns me that there is no clear regression testing for  the additional changes, which tells me that either they were not actually bugs or the new code is not fully tested.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 34 above)
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:465]: I mean I generally agree with those statements, but I don't understand why that's in scope of this PR. 

If that's a refactor that's worth doing, then I'm all for it, but I don't see why _this_ PR is the time to make that change since we've been sharing the state of `leased_workers_` since the new scheduler was written to begin with.

**Comment by wuisawesome** [comment]
Wait to be clear, all of the changes are necessary for this PR to function correctly. If any of them are pulled out or reverted, then this PR wouldn't pass the existing unit tests. Like I could pull them out, but then this PR would have to be stacked/blocked on those PRs being merged.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 34 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:465]: The problem is that this code was previously idempotent (I believe releasing task resources is idempotent), but now it's not because of the new task count. So we need to make sure it's idempotent in a way that is still unit-testable.

I don't think this is a terribly big change, as it just requires unsetting the task spec assigned to the worker. Is there a problem with that solution?

File: python/ray/tests/test_cancel.py (hunk 37 above)
Comment (wuisawesome) [reply python/ray/tests/test_cancel.py:132]: Same as the above test, but I don't think so, because there are multiple `wait_for` tasks and they can't run while the other is blocked on `ray.get()` now

File: python/ray/data/tests/test_dataset_pipeline.py (hunk 36 above)
Comment (wuisawesome) [reply python/ray/data/tests/test_dataset_pipeline.py:136]: I don't think so. I think the issue is just that the way `dataset_pipeline.split` is implemented, all shards of the first chunk need to be read in before anyone can move on to the next chunk, so we need these tasks to run at the same time.

**Comment by ericl** [comment]
Here's another concern. If resources are freed but tasks can't be scheduled
due to worker capping, will the autoscaler fail to add new nodes since it
thinks those resource slots are open?

**Comment by iycheng** [comment]
My feeling is that since the PR actually involves more problems and there probably are some issues not caught by this one. For example, workflow tests catch one edge case, but we are not sure about the others.
So I'd say, let's use a feature flag and try to resolve the edge cases one-by-one.
In the meantime, we also need to test this one with the nightly test to make sure it's working for most normal cases.

File: python/ray/data/tests/test_dataset_pipeline.py (hunk 36 above)
Comment (stephanie-wang) [reply python/ray/data/tests/test_dataset_pipeline.py:211]: Can we remove it now?

File: python/ray/tests/test_basic.py [hunk 40]
```diff
@@ -37,7 +37,12 @@ def test_release_resources_race(shutdown_only):
     ray.init(
         num_cpus=2,
         object_store_memory=700e6,
-        _system_config={"inline_object_status_in_refs": True})
+        _system_config={
+            "inline_object_status_in_refs": True,
+            # Prevent the test from becoming flaky due to worker lease
+            # expirations.
+            "worker_lease_timeout_milliseconds": 10000
```
Comment (stephanie-wang) [inline python/ray/tests/test_basic.py:44]: Do we still need this? What was the bug again?

File: src/ray/common/ray_config_def.h [hunk 41]
```diff
@@ -98,6 +98,12 @@ RAY_CONFIG(bool, lineage_pinning_enabled, false)
 /// See also: https://github.com/ray-project/ray/issues/14182
 RAY_CONFIG(bool, preallocate_plasma_memory, false)
 
+/// The interval before the scheduling class capacity is increased. If set to
```
Comment (stephanie-wang) [inline src/ray/common/ray_config_def.h:101]: Can you explain this a bit more? It's hard to understand what "scheduling class capacity" means without the context about worker processes, deadlock, etc.

File: src/ray/core_worker/test/direct_task_transport_test.cc [hunk 42]
```diff
@@ -1230,12 +1230,6 @@ TEST(DirectTaskTransportTest, TestSchedulingKeys) {
                     BuildTaskSpec(resources1, descriptor1),
                     BuildTaskSpec(resources2, descriptor1));
 
-  // Tasks with different function descriptors do not request different worker leases.
```
Comment (stephanie-wang) [inline src/ray/core_worker/test/direct_task_transport_test.cc:1233]: Why remove this?

File: src/ray/raylet/node_manager.cc [hunk 43]
```diff
@@ -508,6 +511,8 @@ ray::Status NodeManager::RegisterGcs() {
   return ray::Status::OK();
 }
 
+void NodeManager::ExecuteAfter(std::function<void()> fn, double wait_ns) {}
```
Comment (stephanie-wang) [inline src/ray/raylet/node_manager.cc:514]: Remove?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 44]
```diff
@@ -1436,5 +1441,24 @@ ResourceSet ClusterTaskManager::CalcNormalTaskResources() const {
   return ResourceSet(total_normal_task_resources);
 }
 
+uint64_t ClusterTaskManager::MaxRunningTasksPerSchedulingClass(
+    SchedulingClass sched_cls_id) const {
+  auto sched_cls = TaskSpecification::GetSchedulingClassDescriptor(sched_cls_id);
+  double cpu_req = sched_cls.resource_set.GetNumCpusDouble();
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:1447]: Can we simplify this and early-return INT_MAX if cpu_req=0 or total_cpus=0? I got a bit lost trying to figure out whether the type casting was correct.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 45]
```diff
@@ -295,6 +315,24 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+          }
+
+          double wait_time =
+              (1e6 * sched_cls_cap_interval_ms_) * (1L << sched_cls_info.num_updates++);
+          sched_cls_info.next_update_time = get_time_() + wait_time;
+          sched_cls_info.timer =
+              execute_after_([this]() { ScheduleAndDispatchTasks(); }, wait_time);
+        }
+        work_it++;
+        continue;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:333]: Shouldn't we break if we are at capacity and the timer is still active? Because everything else in this class should also be blocked.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 46]
```diff
@@ -295,6 +315,24 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+          // Don't increase the capacity on the very first update since that
+          // will unblock a new task immediately, instead of after the timeout.
+          if (sched_cls_info.num_updates > 0) {
+            sched_cls_info.capacity++;
+          }
+
+          double wait_time =
+              (1e6 * sched_cls_cap_interval_ms_) * (1L << sched_cls_info.num_updates++);
+          sched_cls_info.next_update_time = get_time_() + wait_time;
+          sched_cls_info.timer =
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:329]: Do we need the new timer? I thought that ScheduleAndDispatchTasks is already called periodically from the node manager. If it's not, can we move the timer there instead?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 47]
```diff
@@ -295,6 +315,24 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
         continue;
       }
 
+      if (sched_cls_info.running_tasks.size() >= sched_cls_info.capacity) {
+        if (get_time_() > sched_cls_info.next_update_time) {
+          // Don't increase the capacity on the very first update since that
+          // will unblock a new task immediately, instead of after the timeout.
+          if (sched_cls_info.num_updates > 0) {
+            sched_cls_info.capacity++;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:323]: Can we keep the capacity constant and just use the timer to decide whether to dispatch the task? It would be nice to make sure that the capacity eventually goes back down once other tasks finish.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 48]
```diff
@@ -469,6 +511,15 @@ void ClusterTaskManager::TaskFinished(std::shared_ptr<WorkerInterface> worker,
                                       RayTask *task) {
   RAY_CHECK(worker != nullptr && task != nullptr);
   *task = worker->GetAssignedTask();
+  auto sched_cls = task->GetTaskSpecification().GetSchedulingClass();
+  info_by_sched_cls_[sched_cls].running_tasks.erase(
+      task->GetTaskSpecification().TaskId());
+  RAY_LOG(ERROR) << "Erasing " << task->GetTaskSpecification().TaskId();
+  RAY_LOG(ERROR) << "Size is now: " << info_by_sched_cls_[sched_cls].running_tasks.size();
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:518]: Remove?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 49]
```diff
@@ -300,6 +306,8 @@ class ClusterTaskManagerTest : public ::testing::Test {
   int node_info_calls_;
   int announce_infeasible_task_calls_;
   absl::flat_hash_map<NodeID, rpc::GcsNodeInfo> node_info_;
+  std::vector<std::pair<std::function<void()>, double>> delayed_execution_;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:309]: Can you make sure to call AssertNoLeaks at the end of new tests?

Can you add a test for increasing capacity on timeout?

**Review by stephanie-wang — COMMENTED** [review]
I noticed the PR still has changes to existing Python unit tests; could we remove those now?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 50]
```diff
@@ -295,6 +315,24 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
         continue;
       }
 
+      if (sched_cls_info.running_tasks.size() >= sched_cls_info.capacity) {
+        if (get_time_() > sched_cls_info.next_update_time) {
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:319]: Shouldn't we reset next_update_time if the running tasks drops below the capacity? Otherwise eventually naturally enough time will pass that we exceed this time immediately on hitting capacity.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 48 above)
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:518]: Please clean up the logs

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 51]
```diff
@@ -714,50 +765,8 @@ void ClusterTaskManager::FillResourceUsage(
 
   int num_reported = 0;
 
-  // 1-CPU optimization
-  static const ResourceSet one_cpu_resource_set(
-      absl::flat_hash_map<std::string, double>({{kCPU_ResourceLabel, 1}}));
-  static const SchedulingClass one_cpu_scheduling_cls(
-      TaskSpecification::GetSchedulingClass(one_cpu_resource_set));
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:721]: Can we remove this in a separate PR?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 52]
```diff
@@ -1557,6 +1566,157 @@ TEST_F(ClusterTaskManagerTest, PopWorkerExactlyOnce) {
...
+  task_manager_.QueueAndScheduleTask(task3, &reply, callback);
+  pool_.TriggerCallbacks();
+
+  // We shouldn't cap anything for zero cpu tasks (and shouldn't crash before
+  // this point).
+  ASSERT_EQ(num_callbacks, 3);
+}
+
+/// Test that we exponentially increase the amount of time it takes to increase
+/// the dispatch cap for a scheduling class.
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1717]: Is this a TODO? I don't see fake timer code.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 46 above)
Comment (ericl) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:329]: Agree we should try to avoid extra timers. If we ensure the regular scheduling is <= 1s, I think we can just skip this. It's not necessary for the delay to be precise.

File: python/ray/tests/test_scheduling_2.py [hunk 53]
```diff
@@ -0,0 +1,145 @@
+import os
+import sys
+import tempfile
+
+import ray
+
+from ray._private.test_utils import (Semaphore)
+
+
```
Comment (ericl) [inline python/ray/tests/test_scheduling_2.py:9]: Can you add a simple barrier test like this?

```
import ray
import time
import asyncio

ray.init(num_cpus=2)


@ray.remote(num_cpus=0)
class Barrier:
    def __init__(self, limit):
        self.i = 0
        self.limit = limit

    async def join(self):
        self.i += 1
        while self.i < self.limit:
            await asyncio.sleep(1)


b = Barrier.remote(10)

@ray.remote
def f(i, start):
    print("Launch", i, time.time() - start)
    ray.get(b.join.remote())

start = time.time()
ray.get([f.remote(i, start) for i in range(10)])
```

Btw, when I ran the above, I expected to see exponential scale-up of the delays, but I got this instead:
```
(f pid=155291) Launch 0 0.03812384605407715
(f pid=155362) Launch 1 0.5240130424499512
(f pid=155361) Launch 2 9.340767860412598
(f pid=155424) Launch 3 9.78423523902893
(f pid=155423) Launch 4 9.785459518432617
(f pid=155471) Launch 5 19.341200351715088
(f pid=155509) Launch 6 19.79110550880432
(f pid=155508) Launch 7 19.798838138580322
```

Followed by hanging forever. I think we should have a max cap on the time delay, and also figure out why the step-up isn't smooth above (e.g., 1, 2, 4, 8, etc.)

**Review by ericl — CHANGES_REQUESTED** [review]
Just tried it out and the capping seems pretty effective, though I was able to get some odd timing in the barrier unit test (see nested comment). I think there are a few items left before we can merge:

Process-wise:
- The unrelated fixes should be split out and merged in a separate PR.
- We should be able to merge with zero code changes to existing tests now.
- We should add a feature flag (RAY_enable_worker_capping) on by default for this feature.

Code-wise:
- The exponential backoff protocol needs to be cleaned up (see comments).
- It would be great if you can show the status of each scheduling class (e.g., backoff state, current number of tasks) in debug_state.txt (DebugString() of scheduler). I thought this used to be printed, seems to be missing from what I can tell.

File: src/ray/core_worker/test/direct_task_transport_test.cc (hunk 42 above)
Comment (wuisawesome) [reply src/ray/core_worker/test/direct_task_transport_test.cc:1233]: Because we've added function descriptors to the scheduling class so we _do_ want them to request different leases now?

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc [hunk 54]
```diff
@@ -592,6 +592,13 @@ std::string ClusterResourceScheduler::DebugString(void) const {
   return buffer.str();
 }
 
+uint64_t ClusterResourceScheduler::GetNumCpus(void) const {
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_resource_scheduler.cc:595]: Could it be possible that the user has num_cpus=2.5 ?

Comment (iycheng) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:595]: Btw, why void in the parameter?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 55]
```diff
@@ -39,7 +39,11 @@ ClusterTaskManager::ClusterTaskManager(
     std::function<bool(const std::vector<ObjectID> &object_ids,
                        std::vector<std::unique_ptr<RayObject>> *results)>
         get_task_arguments,
-    size_t max_pinned_task_arguments_bytes)
+    size_t max_pinned_task_arguments_bytes,
+    std::function<std::shared_ptr<boost::asio::deadline_timer>(std::function<void()>,
+                                                               int64_t)>
+        execute_after,
+    std::function<int64_t(void)> get_time, int64_t sched_cls_cap_interval_ms)
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:46]: I actually don't like get_time method here since it's purely for testing and kind of making things more complicated (one more parameters).

I'm ok with this right now, but we probably can do a better job later.

I'm thinking we probably can have a lib:

```
#ifdef UNIT_TEST
int64_t time = 0;
auto GetCurrentTimeNano = []() {
    return time;
}
#else 
int64_t GetCurrentTimeNano() {
    return absl::GetCurrentTImeNano();
}
#endif
```

File: src/ray/raylet/scheduling/cluster_task_manager.h [hunk 56]
```diff
@@ -314,6 +339,23 @@ class ClusterTaskManager : public ClusterTaskManagerInterface {
   absl::flat_hash_map<SchedulingClass, std::deque<std::shared_ptr<internal::Work>>>
       tasks_to_schedule_;
 
+  struct SchedulingClassInfo {
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_task_manager.h:342]: Comment about the purpose of this class.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 57]
```diff
@@ -295,6 +315,27 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+        if (get_time_() >= sched_cls_info.next_update_time) {
+          // Don't increase the capacity on the very first update since that
+          // will unblock a new task immediately, instead of after the timeout.
+          if (sched_cls_info.num_updates > 0) {
+            sched_cls_info.capacity++;
+          }
+
+          int64_t wait_time =
+              (1e6 * sched_cls_cap_interval_ms_) * (1L << sched_cls_info.num_updates++);
+          sched_cls_info.next_update_time = get_time_() + wait_time;
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:330]: I feel next_update_time always increases actually. Do we have the reset there? 

What if the cap is 2 and it eventually it increased to 8, does this mean, later for this scheduling class, we don't wait if there are less than 8 tasks?


Should we do things like (current_capacity - allowed_capacity) and when scheduling tasks exceeds the allowed capacity, we wait the seconds exponential to the difference?

Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:330]: it gets reset when all the tasks in the scheduling class finish and the entry gets removed. There's a c++ unit test for this.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 45 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:336]: Updated to make it a little more precise, but the capacity may have been increased here.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 57 above)
Comment (ericl) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:326]: I like the suggestion of making this based on (current - allowed), which eliminates the need for reset, can we implement that?

File: python/ray/tests/test_scheduling_2.py (hunk 53 above)
Comment (wuisawesome) [reply python/ray/tests/test_scheduling_2.py:9]: Added as a test and just reran with latest changes pulled in, which seem to have fixed it. 

```
(f pid=90535)[0m Launch 0 0.05490303039550781
(f pid=90543)[0m Launch 1 0.6045780181884766
(f pid=90542)[0m Launch 2 0.6046791076660156
(f pid=90548)[0m Launch 3 1.4007248878479004
(f pid=90552)[0m Launch 4 1.941673994064331
(f pid=90551)[0m Launch 5 2.2514801025390625
(f pid=90557)[0m Launch 6 3.883697032928467
(f pid=90560)[0m Launch 7 7.1504950523376465
(f pid=90563)[0m Launch 8 13.55370807647705
(f pid=90566)[0m Launch 9 26.449985027313232
12.89627718925476 6.403211832046509
```

The ratio between the last two numbers is 2.014. Adding as a test (I guess we can assert the last numbers grow exponentially since the short wait times are pretty noisy).

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc (hunk 52 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:1707]: yep forgot to push, it's added now

File: python/ray/workflow/tests/test_recovery.py [hunk 58]
```diff
@@ -103,12 +103,6 @@ def test_dedupe_downloads_list(workflow_start_regular):
         assert get_objects_count == 5
 
 
-@pytest.mark.parametrize(
```
Comment (stephanie-wang) [inline python/ray/workflow/tests/test_recovery.py:106]: Do we still need the changes to this test?

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc (hunk 35 above)
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:794]: Is there a separate unit test that we can write for this that we can split out from this PR?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 59]
```diff
@@ -369,6 +398,14 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
         }
         work_it = dispatch_queue.erase(work_it);
       } else {
+        sched_cls_info.running_tasks.insert(spec.TaskId());
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:401]: Hmm I find it confusing that we're setting the wait time here instead of at the same time as when the timer is checked above. Couldn't this cause a bug like this: CPU limit 1, task A gets scheduled and sets the wait timer. Task B gets queued much later on and gets scheduled immediately, when it should have waited for the timer.

Can we add a unit test to this effect?

File: src/ray/raylet/scheduling/cluster_task_manager.h [hunk 60]
```diff
@@ -314,6 +336,18 @@ class ClusterTaskManager : public ClusterTaskManagerInterface {
...
+    SchedulingClassInfo() : running_tasks(), capacity(0), next_update_time(-1) {}
+    /// Track the running task ids in this scheduling class.
+    absl::flat_hash_set<TaskID> running_tasks;
+    /// The total number of tasks that can run from this scheduling class.
+    uint64_t capacity;
+    /// The next tie to update the class's capacity.
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.h:345]:
```suggestion
    /// The next time to update the class's capacity.
```

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 61]
```diff
@@ -62,7 +62,7 @@ class MockWorkerPool : public WorkerPoolInterface {
 
   const std::vector<std::shared_ptr<WorkerInterface>> GetAllRegisteredWorkers(
       bool filter_dead_workers) const {
-    RAY_CHECK(false) << "Not used.";
+    // RAY_CHECK(false) << "Not used.";
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:65]: Remove?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 62]
```diff
@@ -1557,6 +1561,287 @@ TEST_F(ClusterTaskManagerTest, PopWorkerExactlyOnce) {
...
+  // Even though there are free resources, we've hit our cap of (8/4=)2 workers
+  // of the given scheduling class so we shouldn't dispatch the remaining task.
+  ASSERT_EQ(num_callbacks, 2);
+
+  RayTask buf;
+  task_manager_.TaskFinished(workers[1], &buf);
+
+  task_manager_.ScheduleAndDispatchTasks();
+  pool_.TriggerCallbacks();
+  ASSERT_EQ(num_callbacks, 3);
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1607]: AssertNoLeaks(), same for the tests below.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 63]
```diff
@@ -1557,6 +1561,287 @@ TEST_F(ClusterTaskManagerTest, PopWorkerExactlyOnce) {
...
+  ASSERT_EQ(num_callbacks, 2);
+
+  // Now it should run
+  task_manager_.ScheduleAndDispatchTasks();
+  current_time_ns_ += UNIT;
+  task_manager_.ScheduleAndDispatchTasks();
+  pool_.TriggerCallbacks();
+  task_manager_.ScheduleAndDispatchTasks();
+  ASSERT_EQ(num_callbacks, 3);
+}
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1774]: We should also check the behavior in the other cases that were commented on/fixed earlier:
- check that timer gets reset if any task finishes, not just when all tasks finish
- check that timer is still set when the time between task submissions is long 

It would also be nice to check that the timer doesn't affect scheduling for a different class.

File: python/ray/workflow/tests/test_recovery.py (hunk 58 above)
Comment (wuisawesome) [reply python/ray/workflow/tests/test_recovery.py:106]: hold on yeah i just messed up reverting this change.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 64]
```diff
@@ -1519,6 +1519,132 @@ TEST_F(ClusterTaskManagerTest, PopWorkerExactlyOnce) {
   AssertNoLeaks();
 }
 
+TEST_F(ClusterTaskManagerTest, CapRunningOnDispatchQueue) {
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:1564]: > Ideally, we should also add a test that checks that tasks of different depth are assigned different resource classes.

This was now added in #20004 so it should be there. 

> Also, was there a bug related to TaskFinished not being idempotent? Can we add a test for this?
Added as `IdempotencyTest`

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 65]
```diff
@@ -1519,6 +1519,132 @@ TEST_F(ClusterTaskManagerTest, PopWorkerExactlyOnce) {
...
+  ASSERT_EQ(num_callbacks, 2);
+
+  task_manager_.ReleaseCpuResourcesFromUnblockedWorker(workers[0]);
+  task_manager_.ReleaseCpuResourcesFromUnblockedWorker(workers[1]);
+
+  task_manager_.ScheduleAndDispatchTasks();
+
+  // Even though there are free resources, we've hit our cap of (8/4=)2 workers
+  // of the given scheduling class so we shouldn't dispatch the remaining task.
+  ASSERT_EQ(num_callbacks, 2);
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:1600]: Assuming this comment came before the `  ASSERT_EQ(num_callbacks, 3);` below

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc (hunk 54 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:576]: > Could it be possible that the user has num_cpus=2.5 will this lead to the precision issue?
I believe resource _totals_ are required to be whole numbers. 

> Btw, why void in the parameter?
Idk, removing.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 59 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:401]: hmmm are you saying that the timer should only start when the raylet receives the next lease request? not when the capacity gets hit?

Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:401]: btw, this also brings up the question, when does the timer start, if the lease request is submitted, but the task can't be dispatched because the arguments couldn't be pinned?

**Review by ericl — COMMENTED** [review]
Could we also decrease the multiplier on when we get the "too many workers" warning? Basically now that we have this backoff, it seems the user doesn't see the warning until way too late--- potentially confusing them as to why there is a backoff.

Alternatively, we could ourselves print a warning when the backoff reaches noticeable thresholds (e.g., 5 seconds).

**Comment by ericl** [comment]
Seems very close! Mostly want to wrap up concerns around error messages / internal readability now.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 59 above)
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:406]: I think the simplest would be to start the timer in the same spot where we check the timer.

File: python/ray/tests/test_scheduling_2.py [hunk 66]
```diff
@@ -0,0 +1,182 @@
...
+    last_wait = results[-1] - results[-2]
+    second_last = results[-2] - results[-3]
+
+    assert 1.5 < last_wait / second_last < 2.5
+    assert 5 < last_wait < 8
+
+
+if __name__ == "__main__":
+    import pytest
+    sys.exit(pytest.main(["-v", __file__]))
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply python/ray/tests/test_scheduling_2.py]: seems to be passing consistently

File: src/ray/common/ray_config_def.h [hunk 67]
```diff
@@ -98,18 +98,19 @@ RAY_CONFIG(bool, lineage_pinning_enabled, false)
 /// See also: https://github.com/ray-project/ray/issues/14182
 RAY_CONFIG(bool, preallocate_plasma_memory, false)
 
+/// We place a soft cap on the number of tasks of a given scheduling class that
+/// can run at once. After the specified interval, a the new task above that
```
Comment (stephanie-wang) [inline src/ray/common/ray_config_def.h:102]:
```suggestion
/// can run at once to limit the total number of worker processes. After the specified interval, a the new task above that
```

File: src/ray/common/ray_config_def.h [hunk 68]
```diff
@@ -98,18 +98,19 @@ RAY_CONFIG(bool, lineage_pinning_enabled, false)
...
+/// cap is allowed to run. The time before the next tasks (above the cap) are
+/// allowed to run increases exponentially. The soft cap is needed to prevent
+/// deadlock in the case where a task begins to execute and tries to `ray.get`
+/// another task of the same class.
+RAY_CONFIG(int64_t, worker_cap_initial_backoff_delay_ms, 100)
```
Comment (stephanie-wang) [inline src/ray/common/ray_config_def.h:107]:
```suggestion
RAY_CONFIG(int64_t, worker_cap_initial_backoff_delay_ms, 1000)
```

I think 100ms is still too fast; we should have it be at least as long as it takes to start a new Python process.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 69]
```diff
@@ -295,6 +312,23 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
 
+      // Check if the scheduling class is at capacity now.
+      if (sched_cls_info.running_tasks.size() >= sched_cls_info.capacity &&
+          work->GetState() == internal::WorkStatus::WAITING) {
+        RAY_LOG(DEBUG) << "Hit cap! time=" << get_time_ms_()
+                       << " next update time=" << sched_cls_info.next_update_time;
+        if (get_time_ms_() < sched_cls_info.next_update_time) {
+          // We're over capacity and it's not time to admit a new task yet.
+          // Calculate the next time we should admit a new task.
+          UpdateSchedulingClassWaitTime(sched_cls_info);
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:323]: I'm confused by the logic here. Why do we update the timer each time we see that we haven't reached the timer yet? That seems like it could cause us to hang if we always call ScheduleAndDispatch before the timeout (if this logic is right, can you check this behavior in the unit tests?).

It seems like it should be:
```
if (next time not set) {
  update next time
  break
} else if (get_time > next time) {
  schedule task, reset next time to nil
} else {
  break
}
```

Seems like the first and third cases are getting squashed together into one case now.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 70]
```diff
@@ -1399,5 +1463,29 @@ ResourceSet ClusterTaskManager::CalcNormalTaskResources() const {
...
+
+  if (cpu_req == 0 || total_cpus == 0) {
+    return std::numeric_limits<uint64_t>::max();
+  }
+  return static_cast<uint64_t>(std::round(total_cpus / cpu_req));
+}
+
+void ClusterTaskManager::UpdateSchedulingClassWaitTime(
+    SchedulingClassInfo &sched_cls_info) {
+  if (sched_cls_info.running_tasks.size() >= sched_cls_info.capacity) {
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:1480]: Can you remove this method? Generally if there is a method that only gets called once, I think it's nicer to be able to read the code where it's used.

File: src/ray/raylet/scheduling/cluster_task_manager.h [hunk 71]
```diff
@@ -314,6 +345,27 @@ class ClusterTaskManager : public ClusterTaskManagerInterface {
...
       tasks_to_schedule_;
 
+  /// Tracking information about the currently running tasks in a scheduling
+  /// class. This information is used to place a cap on the number of running
+  /// running tasks per scheduling class.
+  struct SchedulingClassInfo {
+    SchedulingClassInfo(int64_t cap)
+        : running_tasks(),
+          capacity(cap),
+          next_update_time(std::numeric_limits<int64_t>::max()) {}
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.h:355]: I think the logic will be simpler if you use 0 to mean nil instead of int_max.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 72]
```diff
@@ -1557,6 +1615,440 @@ TEST_F(ClusterTaskManagerTest, PopWorkerExactlyOnce) {
...
+        std::make_shared<MockWorker>(WorkerID::FromRandom(), 1234, runtime_env_hash);
+    pool_.PushWorker(std::static_pointer_cast<WorkerInterface>(worker));
+    pool_.TriggerCallbacks();
+    workers.push_back(worker);
+  }
+  task_manager_.ScheduleAndDispatchTasks();
+
+  ASSERT_EQ(num_callbacks, 1);
+
+  current_time_ms_ += UNIT;
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:1822]: Just skimming this, it does look like the case I mentioned above is not covered here. So we should  also check that calling ScheduleAndDispatchTasks while the timer is set has no effect on the timer.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 73]
```diff
@@ -284,6 +287,20 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+          scheduling_class,
+          SchedulingClassInfo(MaxRunningTasksPerSchedulingClass(scheduling_class)));
+    }
+    auto &sched_cls_info = info_by_sched_cls_.at(scheduling_class);
+
+    /// We cap the maximum running tasks of a scheduling class to avoid
+    /// scheduling too many tasks of a single type/depth, when there are
+    /// deeper/other functions that should be run. We need to apply back
+    /// pressure here because workers don't submit their lease requests until
+    /// dependencies are resolved.
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:303]: Minor, but it's a bit hard to understand the last sentence of this comment.

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
It's looking good, I think we just need to fix one last bug(?) in the dispatch loop.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 69 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:323]: > That seems like it could cause us to hang if we always call ScheduleAndDispatch before the timeout (if this logic is right, can you check this behavior in the unit tests?).

I'm not sure I understand what you mean, but the update takes the min of the existing wait time and the newly calculated one. Since we're calling ScheduleAndDispatch every 100ms, and the existing test cases take 10+ seconds to timeout, it seems like we must be calling ScheduleAndDispatch before the timeout?

File: src/ray/raylet/scheduling/cluster_task_manager.h (hunk 71 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.h:355]: How so? What do you imagine the simplified logic would look like? I thought we would need a `if (get_time < wait_time) ...` case no matter what in order to handle the case where a task finishes before the timeout gets triggered (i.e. the last portion of `SchedulingClassCapIncrease` where we let one task finish)

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc (hunk 72 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:1822]: Doesn't the block starting on line 1831 do that? at that point the time is  200ms, and the wait is set to 300ms. On 1840, it goes up to 300ms and then the task runs.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 69 above)
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:323]: I see, I didn't catch the "min" part. I found this confusing because the UpdateSchedulingClassWaitTime makes it sound like the timer will get renewed, but it's actually only getting renewed if it's not already set.

Can you take care of the other comment to inline the code here? I think that will help with the clarity.

**Review by stephanie-wang — APPROVED** [review]
Nice work! Thanks for pushing on this, it's great to see this issue finally fixed in Ray (I think it first came up ~2017) :')

**Comment by ericl** [comment]
@wuisawesome it seems these tests are consistently failing:

//python/ray/util/sgd:test_torch_2                                      TIMEOUT in 3 out of 3 in 900.1s
//python/ray/data:tests/test_dataset_pipeline                           TIMEOUT in 3 out of 3 in 900.0s
 //python/ray/workflow:tests/test_basic_workflows_2                       FAILED in 3 out of 3 in 213.2s

**Review by ericl — APPROVED** [review]

**Comment by ericl** [comment]
Should we wait for windows?

**Comment by wuisawesome** [comment]
Maybe just for the build to finish. There was a type conversion warning earlier. (should be passing now, but just want to make sure).

**Comment by zhe-thoughts** [comment]
Quick question for @wuisawesome , @ericl and @iycheng for me to better understand the revert:

Did these tests pass when we merged this PR? test_multinode_failures, test_virtual_actor, test_component_failures_2

Thanks!
