### PR TITLE
Check that the user's python version is supported

### LINKED ISSUE #6985: build.sh should be more specific about the allowed Python version
I ran into an issue where `build.sh` dutifully detected I have Python 3.8 installed, but then the build mysteriously failed when it couldn't find the `0.14.0.RAY` wheel for `pyarrow`. That happened because no wheel exists at this time for Python 3.8.

So, 

1. `build.sh` should only allow versions of Python that are supported, i.e., for which artifacts exist.
2. As an extra sanity check, if the `pyarrow` wheel can't be found, suggest that the user verify they are using a supported version or Python (or similarly helpful message).

### PR DESCRIPTION
**Pull request by deanwampler**
## Why are these changes needed?

If you're using Python 3.8, you get this mystifying error that a Ray-customized build for PyArrow can't be found. The real problem is that we haven't built it for Python other than v3.6 and v3.7. Now this script checks that version of Python is supported and errors out if not. Also, I made it relatively easy to edit the list of supported Pythons by editing a bash array near the top of the script.

## Related issue number

Fixes #6985

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://ray.readthedocs.io/en/latest/.
  I don't think our docs explicit say which versions of Python 3 are supported, but probably should.
- [x ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.

### CODE REVIEW

File: build.sh [hunk 1]
```diff
@@ -5,20 +5,24 @@ set -x
 # Cause the script to exit if a single command fails.
 set -e
 
+# As the supported Python versions change, edit this array:
+SUPPORTED_PYTHONS=( "3.6" "3.7" )
```
Comment (edoakes) [inline build.sh]: we also support python 3.5

**Review by edoakes — APPROVED** [review]
LGTM just fix to also include python 3.5

File: build.sh (hunk 1 above)
Comment (deanwampler) [reply build.sh]: Pushed a fix that adds 3.5.
