### PR TITLE
[New scheduler] Fix test_global_state

### LINKED ISSUE #12434: [New scheduler] Fix test_global_state::* (resource demand reporting not implemented)

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

Depends on #12557

## Related issue number

#12582
Closes https://github.com/ray-project/ray/issues/12434

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by wuisawesome** [comment]
The diff should clean itself up (5 files changes) once Stephanie's PR is merged.

**Comment by ericl** [comment]
[will review once the diff base is merged]

**Comment by ericl** [comment]
@wuisawesome needs rebase

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 1]
```diff
@@ -480,6 +480,44 @@ TEST_F(ClusterTaskManagerTest, HeartbeatTest) {
...
+  ASSERT_EQ(fulfills_dependencies_calls_, 0);
+  ASSERT_EQ(node_info_calls_, 0);
+
+  auto data = std::make_shared<rpc::HeartbeatTableData>();
+  task_manager_.Heartbeat(false, data);
+
+  auto resource_load_by_shape = data->resource_load_by_shape();
+  auto shape1 = resource_load_by_shape.resource_demands()[0];
+
+  ASSERT_EQ(shape1.backlog_size(), 45);
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:518]: Can we check the backlog goes back to zero after the task is done?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 2]
```diff
@@ -480,6 +480,44 @@ TEST_F(ClusterTaskManagerTest, HeartbeatTest) {
...
+  ASSERT_EQ(leased_workers_.size(), 0);
+  ASSERT_EQ(pool_.workers.size(), 1);
+  ASSERT_EQ(fulfills_dependencies_calls_, 0);
+  ASSERT_EQ(node_info_calls_, 0);
+
+  auto data = std::make_shared<rpc::HeartbeatTableData>();
+  task_manager_.Heartbeat(false, data);
+
+  auto resource_load_by_shape = data->resource_load_by_shape();
+  auto shape1 = resource_load_by_shape.resource_demands()[0];
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:516]: Can you also test other parts of the proto like num_infeasible_queued, etc?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 3]
```diff
@@ -431,5 +519,22 @@ void ClusterTaskManager::Spillback(const NodeID &spillback_to, const Work &work)
...
 }
 
+void ClusterTaskManager::AddToBacklog(const Task &task) {
+  if (report_worker_backlog_) {
+    auto cls = task.GetTaskSpecification().GetSchedulingClass();
+    backlog_tracker_[cls] += task.BacklogSize();
+  }
+}
+
+void ClusterTaskManager::RemoveFromBacklog(const Task &task) {
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:529]:
```suggestion
void ClusterTaskManager::RemoveFromBacklogTracker(const Task &task) {
```

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 4]
```diff
@@ -431,5 +519,22 @@ void ClusterTaskManager::Spillback(const NodeID &spillback_to, const Work &work)
   send_reply_callback();
 }
 
+void ClusterTaskManager::AddToBacklog(const Task &task) {
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:522]:
```suggestion
void ClusterTaskManager::AddToBacklogTracker(const Task &task) {
```

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 5]
```diff
@@ -277,16 +287,69 @@ bool ClusterTaskManager::CancelTask(const TaskID &task_id) {
...
 
-  // TODO (Alex): Implement the 1-CPU task optimization.
+  int num_reported = 0;
+
+  // 1-CPU optimization
+  static const ResourceSet one_cpu_resource_set(
+      std::unordered_map<std::string, double>({{kCPU_ResourceLabel, 1}}));
+  static const SchedulingClass one_cpu_scheduling_cls(
+      TaskSpecification::GetSchedulingClass(one_cpu_resource_set));
+  {
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:307]: Add a comment that this block is for reporting resource load.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 6]
```diff
@@ -277,16 +287,69 @@ bool ClusterTaskManager::CancelTask(const TaskID &task_id) {
...
+      if (backlog_it != backlog_tracker_.end()) {
+        by_shape_entry->set_backlog_size(backlog_it->second);
+      }
+    }
+  }
+
   for (const auto &pair : tasks_to_schedule_) {
     const auto &scheduling_class = pair.first;
+    if (scheduling_class == one_cpu_scheduling_cls) {
+      continue;
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:345]:
```suggestion
      continue;  // Covered in block above.
```

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 7]
```diff
@@ -277,16 +287,69 @@ bool ClusterTaskManager::CancelTask(const TaskID &task_id) {
...
   // heartbeat. Now we just report it every time.
   data->set_resource_load_changed(true);
   auto resource_loads = data->mutable_resource_load();
   auto resource_load_by_shape =
       data->mutable_resource_load_by_shape()->mutable_resource_demands();
 
-  // TODO (Alex): Implement the 1-CPU task optimization.
+  int num_reported = 0;
+
+  // 1-CPU optimization
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:302]: Comment why we handle it separately.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 8]
```diff
@@ -254,7 +260,9 @@ bool ClusterTaskManager::CancelTask(const TaskID &task_id) {
        shapes_it++) {
     auto &work_queue = shapes_it->second;
     for (auto work_it = work_queue.begin(); work_it != work_queue.end(); work_it++) {
-      if (std::get<0>(*work_it).GetTaskSpecification().TaskId() == task_id) {
+      const auto &task = std::get<0>(*work_it);
+      if (task.GetTaskSpecification().TaskId() == task_id) {
+        RemoveFromBacklog(task);
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:265]: Actually do we need the backlog tracker? Why not instead calculate the max backlog size during the Heartbeat call, since you are looping over the tasks anyways?

**Review by ericl — CHANGES_REQUESTED** [review]
See inline: main comment is we should try to get rid of backlog tracker; instead the backlog can be calculated on the fly during Heartbeat while scanning over the tasks.

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 8 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:265]: So we can do that, it just means to heartbeat will take O(n) time instead of O(k). n=# of tasks, k=# of scheduling classes

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 7 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:302]: @stephanie-wang what was the reason for this? IIRC it had something to do with 1-cpu tasks being the most common, but in hindsight, I'm not sure because they're also the most easily fulfilled by any node (therefore less important to report).

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc (hunk 2 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:516]: What additional testing do you think this needs (beyond what's already tested in `HeartbeatTest`)?

Comment (ericl) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc:516]: All the fields of the proto?

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 8 above)
Comment (ericl) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:265]: Yes, let's do that. It's actually just O(k) still since queueing happens on the core worker anyways.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 9]
```diff
@@ -275,21 +279,90 @@ bool ClusterTaskManager::CancelTask(const TaskID &task_id) {
...
+    num_reported++;
+    int count = 0;
+    int backlog_size = 0;
+    auto it = tasks_to_schedule_.find(one_cpu_scheduling_cls);
+    if (it != tasks_to_schedule_.end()) {
+      count += it->second.size();
+      const auto &work_queue = it->second;
+      for (const auto &work : work_queue) {
+        const auto &task = std::get<0>(work);
+        backlog_size += task.BacklogSize();
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:309]: It's not correct to be adding up the backlog sizes right? Or is this assuming core worker only sends one task per type?

If the latter, we should add a comment about the assumptions we are making here.

Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:309]: Yeah we're making that assumption (same assumption was made in the old scheduler). 

Avoiding that assumption would be very hard/annoying actually, since the raylet would have to track the backlog per core worker per shape (and we would have to de-dupe backlogs from the same core worker to multiple raylets).

**Comment by ericl** [comment]
Actually @wuisawesome  I think you're right scanning over all the tasks could be O(n), I was forgetting about tasks with object dependencies. Tasks with unique object dependencies have unique scheduling key in the core worker, so if the core worker submitted say 10k tasks with unique dependencies, then the heartbeat scan could be quite slow. So we can probably revert to your previous implementation which LGTM, sorry about that!

**Review by ericl — APPROVED** [review]
LGTM to revert to the older impl
