### PR TITLE
[Core] Fix race condition in setting node death info

### LINKED ISSUE #45625: [Core] gcs is crashing
### What happened + What you expected to happen

Core gcs is crashing. To track the work to unblock the next release.

### Versions / Dependencies

master

### Reproduction script

N/A

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by ruisearch42**
## Why are these changes needed?

When setting node death info, node was checked to be alive and then later used.
However, there could be other callers that remove the alive node in between the
check and use. This PR fixes the race condition by rechecking at the use time and
skip the action if it is already removed.

It also fixes the preemption deadline checking by using `current_sys_time_ms()`
instead of `current_time_ms()`.

## Related issue number
Closes #45625

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 1]
```diff
@@ -354,11 +356,14 @@ std::shared_ptr<rpc::GcsNodeInfo> GcsNodeManager::RemoveNode(
...
-  bool is_expected_termination =
-      (death_info.reason() == rpc::NodeDeathInfo::AUTOSCALER_DRAIN_PREEMPTED);
-  if (auto node = RemoveNode(node_id, is_expected_termination)) {
+  auto maybe_node = GetAliveNode(node_id);
+  if (maybe_node.has_value()) {
+    rpc::NodeDeathInfo death_info = InferDeathInfo(node_id);
+    auto node = RemoveNode(node_id, death_info);
+    if (!node) {
+      return;
+    }
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:353]: this must be non-None?

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 2]
```diff
@@ -113,8 +113,7 @@ void GcsNodeManager::HandleUnregisterNode(rpc::UnregisterNodeRequest request,
                                           rpc::SendReplyCallback send_reply_callback) {
   NodeID node_id = NodeID::FromBinary(request.node_id());
   RAY_LOG(DEBUG) << "HandleUnregisterNode() for node id = " << node_id;
-  SetDeathInfo(node_id, request.node_death_info());
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:116]: SetDeathInfo can be removed?

Comment (ruisearch42) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:116]: Yes - I just removed it.

File: src/ray/gcs/gcs_server/gcs_node_manager.cc (hunk 1 above)
Comment (ruisearch42) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:353]: I think you are right, since the GCS event loop is single-threaded, there should be no race here.

File: src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc [hunk 3]
```diff
@@ -752,6 +752,38 @@ TEST_F(GcsAutoscalerStateManagerTest, TestDrainingStatus) {
...
+  RemoveNode(node);
+
+  // Simulates raylet accepts the drain request and replies to GCS.
+  ASSERT_TRUE(raylet_client_->ReplyDrainRaylet());
+
+  // The GCS request is accepted now.
+  ASSERT_TRUE(reply.is_accepted());
+}
+
 TEST_F(GcsAutoscalerStateManagerTest, TestIdleTime) {
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc:787]: I think you need to update existing tests as well since you now need to manually call `ReplyDrainRaylet`

**Review by jjyao — APPROVED** [review]

File: src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc (hunk 3 above)
Comment (ruisearch42) [reply src/ray/gcs/gcs_server/test/gcs_autoscaler_state_manager_test.cc:787]: Discussed offline, for other cases (node already removed, or invalid node) they won't call to Raylet, so no need to call `ReplyDrainRaylet`.
