### PR TITLE
[Core] Fix GCS check failure due to autoscaler V2

### LINKED ISSUE #39249: Release test stress_test_placement_group.aws failed
Release test **stress_test_placement_group.aws** failed. See https://buildkite.com/ray-project/release-tests-branch/builds/2123#018a5f58-f022-481b-8a50-1022918b49bf for more details.

Managed by OSS Test Policy

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Currently, `GetPlacementGroupLoad` can include REMOVED placement group states when the placement group is just removed and failed to schedule (https://github.com/ray-project/ray/blob/8a434b4ee7cd48e60fa1531315d39901fac5d79e/src/ray/gcs/gcs_server/gcs_placement_group_manager.cc#L306). The removed pgs will be cleaned when it is scheduled next time.

If we call `GetPlacementGroupLoad` at this time, it triggers the check failure because the downstream consumer (autoscaler v2) assumes this should be only in PENDING & RESCHEDULING state. I fixed the issue by

- making the API `GetPlacementGroupLoad` have stronger guarantee (it now only returns PENDING & RESCHEDULING).
- making the downstream consumer to be more graceful (instead of check, we just add if). 

## Related issue number

Closes https://github.com/ray-project/ray/issues/39249

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc [hunk 1]
```diff
@@ -316,6 +318,39 @@ TEST_F(GcsPlacementGroupManagerTest, TestRemoveNamedPlacementGroup) {
...
+  gcs_placement_group_manager_->RemovePlacementGroup(placement_group_id,
+                                                     [](const Status &status) {});
+  ASSERT_EQ(placement_group->GetState(), rpc::PlacementGroupTableData::REMOVED);
+  /// This is a hack to make a synchronization point here.
+  /// This test verifies GetPlacementGroupLoad doesn't return REMOVED pgs.
+  /// If IO service keeps running, it will invoke `SchedulePendingPlacementGroups`
+  /// which cleans up REMOVED pgs from the pending list (which is
+  /// used to obtain the load). It makes test accidently pass when REMOVED
+  /// pgs can still be reported as load.
+  StopIoService();
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/test/gcs_placement_group_manager_test.cc:346]: I'd love to talk in person why we need this if it doesn't make sense.

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc [hunk 2]
```diff
@@ -135,15 +135,17 @@ void GcsAutoscalerStateManager::GetPendingGangResourceRequests(
...
   for (const auto &pg_data : placement_group_load->placement_group_data()) {
     auto gang_resource_req = state->add_pending_gang_resource_requests();
+    auto pg_state = pg_data.state();
+    auto pg_id = PlacementGroupID::FromBinary(pg_data.placement_group_id());
     // For each placement group, if it's not pending/rescheduling, skip it since.
     // it's not part of the load.
-    RAY_CHECK(pg_data.state() == rpc::PlacementGroupTableData::PENDING ||
-              pg_data.state() == rpc::PlacementGroupTableData::RESCHEDULING)
-        << "Placement group load should only include pending/rescheduling PGs. ";
+    if (pg_state != rpc::PlacementGroupTableData::PENDING &&
```
Comment (rickyyx) [inline src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:142]: if we are not adding removed pg's, do we still need to remove this check now?

**Review by rickyyx — APPROVED** [review]
Great catch! LGTM

File: src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc (hunk 2 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:142]: Yeah I think technically it is not necessary... but since it is hard to test this regression, I would just keep it here.

Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_autoscaler_state_manager.cc:142]: i am adding a bunch of metrics to this - and I think i could surface this through that maybe later on instead of simply continuing.

**Comment by rickyyx** [comment]
https://buildkite.com/ray-project/premerge/builds/4857 blocks merge.
