### PR TITLE
Fix LRU eviction of client notification datastructure

### LINKED ISSUE #3997: Redis LRU eviction causes hangs with ray.wait() (but get() is fine)
### System information
- **Ray version**: 0.6.4

### Describe the problem
```
import ray

@ray.remote
def f():
    return 0

@ray.remote
def g():
    import time
    start = time.time()
    while time.time() < start + 1:
        ray.get([f.remote() for _ in range(10)])

import ray
# 10MB -> hangs after ~5 iterations
# 20MB -> hangs after ~20 iterations
# 50MB -> hangs after ~50 iterations
ray.init(redis_max_memory=1024 * 1024 * 50)

i = 0
while True:
    i += 1
    a = g.remote()
    [ok], _ = ray.wait([a])
    print("iter", i)
```
### Source code / logs
The above example will reproducibly hang with number of iterations proportional to the redis memory size.

The expected behaviour is that once the memory size is large enough, it can run forever.

Also, we shouldn't be hanging and should throw an error if redis capacity is too small.

### PR DESCRIPTION
**Pull request by pcmoritz**
This should fix https://github.com/ray-project/ray/issues/3997

One question that is still open is if this datastructure is cleaned up properly (both if the wait exits and also if clients die that are blocked in a wait).

### CODE REVIEW

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 1]
```diff
@@ -39,6 +39,9 @@ extern RedisChainModule module;
     }                                                            \
   }
 
+/// Map from pub sub channel to clients that are waiting on that channel.
+std::unordered_map<std::string, std::vector<std::string>> notification_map;
```
Comment (ericl) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: Can we add the size of this to the debug string somehow?

**Comment by ericl** [comment]
Could you also add

```
import ray

@ray.remote
def f():
    return 0

@ray.remote
def g():
    import time
    start = time.time()
    while time.time() < start + 1:
        ray.get([f.remote() for _ in range(10)])

# 10MB -> hangs after ~5 iterations
# 20MB -> hangs after ~20 iterations
# 50MB -> hangs after ~50 iterations
ray.init(redis_max_memory=1024 * 1024 * 10)

i = 0
for i in range(50):
    i += 1
    a = g.remote()
    [ok], _ = ray.wait([a])
    print("iter", i)
```

to the jenkins tests? This will hang-fail before this fix.

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 1 above)
Comment (ericl) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: We could alternatively print a warning if this map exceeds certain size bounds, e.g. 1000, 10k, 100k.

**Comment by robertnishihara** [comment]
@pcmoritz @ericl how long does that take to run assuming it's successful? The Jenkins tests take quite a long time as it is.

**Comment by ericl** [comment]
It takes about 30 seconds.

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 2]
```diff
@@ -117,15 +120,12 @@ Status OpenPrefixedKey(RedisModuleKey **out, RedisModuleCtx *ctx,
...
 /// Open the key used to store the channels that should be published to when an
 /// update happens at the given keyname.
-Status OpenBroadcastKey(RedisModuleKey **out, RedisModuleCtx *ctx,
-                        RedisModuleString *pubsub_channel_str, RedisModuleString *keyname,
-                        int mode) {
+std::string GetBroadcastKey(RedisModuleCtx *ctx, RedisModuleString *pubsub_channel_str,
+                            RedisModuleString *keyname) {
   RedisModuleString *channel;
-  RAY_RETURN_NOT_OK(FormatPubsubChannel(&channel, ctx, pubsub_channel_str, keyname));
+  RAY_CHECK_OK(FormatPubsubChannel(&channel, ctx, pubsub_channel_str, keyname));
```
Comment (robertnishihara) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: @guoyuhong removed all `RAY_CHECK` calls in https://github.com/ray-project/ray/pull/3855. So let's keep it that way.

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 1 above)
Comment (pcmoritz) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: done, I added a redis command that can query the DEBUG_STRING. Also found a bug doing so, which was there before this PR: https://github.com/ray-project/ray/pull/4021/commits/4c62c3b01faa7ca6372eac87e1485902ca43b525

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 2 above)
Comment (pcmoritz) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: good idea, done

**Review by ericl — APPROVED** [review]
LGTM

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 3]
```diff
@@ -171,26 +172,24 @@ int PublishTableAdd(RedisModuleCtx *ctx, RedisModuleString *pubsub_channel_str,
...
-      RedisModuleString *client_channel =
-          RedisModule_ZsetRangeCurrentElement(notification_key, NULL);
+  auto it = notification_map.find(notification_key);
+  if (it != notification_map.end()) {
+    for (const std::string& client_channel : it->second) {
+      // RedisModule_Call seems to be broken and cannot accept "bb",
+      // therefore we construct a temporary redis string here, which
+      // will be garbage collected by redis.
+      auto channel = RedisModule_CreateString(
+          ctx, client_channel.data(), client_channel.size());
```
Comment (guoyuhong) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: @pcmoritz Can we delete this temporary redis string immediately after PUBLISH command finishes? In our system we do not enable redis LRU by default. That may cause redis memory leak.

**Comment by guoyuhong** [comment]
One more question, what is the typical request key number in the key value of the map `std::unordered_map<std::string, std::vector<std::string>> notification_map;`. If the number is not big, it is fine. Otherwise, `std::remove` may be very slow for a vector, since we often call `CancelNotifications` in task table and object table.

**Comment by ericl** [comment]
jenkins retest this please

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 3 above)
Comment (robertnishihara) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: Are you talking about LRU eviction or about automatic memory management? We shouldn’t have to free strings or close keys because redis automatic memory management takes care of that. If you do need to free strings then we you would need to do it in many places.

File: src/ray/gcs/redis_module/ray_redis_module.cc [hunk 4]
```diff
@@ -171,26 +172,24 @@ int PublishTableAdd(RedisModuleCtx *ctx, RedisModuleString *pubsub_channel_str,
...
       RedisModuleCallReply *reply = RedisModule_Call(
-          ctx, "PUBLISH", "sb", client_channel, fbb.GetBufferPointer(), fbb.GetSize());
+          ctx, "PUBLISH", "sb", channel, fbb.GetBufferPointer(), fbb.GetSize());
       if (reply == NULL) {
         return RedisModule_ReplyWithError(ctx, "error during PUBLISH");
       }
     }
+    notification_map.erase(it);
```
Comment (robertnishihara) [inline src/ray/gcs/redis_module/ray_redis_module.cc]: Can you explain this line? You said it was a bug, but shouldn’t we only update this when a client calls subscribe or unsubscribe?

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 3 above)
Comment (guoyuhong) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: Sorry, I thought it was a key... It is just a Redis String, which is fine.

**Comment by ericl** [comment]
jenkins retest this please

Also some lint errors...

File: src/ray/gcs/redis_module/ray_redis_module.cc (hunk 4 above)
Comment (pcmoritz) [reply src/ray/gcs/redis_module/ray_redis_module.cc]: This was a fluke, I just had forgotten how to erase from a c++ vector properly

**Comment by pcmoritz** [comment]
@guoyuhong The number of elements in the vector will be fairly small (= the number of clients subscribed to that key). I expect vectors to be faster in this case than other datastructures.

**Review by guoyuhong — APPROVED** [review]
@pcmoritz Thanks for the confirmation.

**Comment by ericl** [comment]
jenkins retest this please

**Comment by ericl** [comment]
`OOM command not allowed when used memory > 'maxmemory'.`

Odd this happens when the test is initializing, perhaps 10MB is too small on the jenkins environment.

**Comment by pcmoritz** [comment]
Jenkins retest this please

**Comment by pcmoritz** [comment]
alright, looks like Jenkins is finally happy (the multinode_test script might not pass through the flag to redis, it's a little strange but also not the intended use case...)

**Comment by ericl** [comment]
Ok, no luck with jenkins. I'm going to merge this and we can figure out the test issue separately.
