### PR TITLE
[core] Add bundle id as a label;

### LINKED ISSUE #15842: [core/placement groups] placement group `ready()` occupies resources, blocks usage
### What is the problem?

See discussion in #15670

When using Ray Tune with different placement groups (that cannot be reused) we sometimes run into this error:

```
2021-05-17 14:07:56,831	WARNING worker.py:1102 -- The actor or task with ID ffffffffffffffff4a211a45f051050d12f7293c01000000 cannot be scheduled right now. 
It requires {CPU_group_74230d0c7e8c8b02d219a8e2a6abcca1: 0.010000} for placement, but this node only has remaining {5.850000/16.000000 CPU, 6.269998 GiB/6.269998 GiB memory, 3.134999 GiB/3.134999 GiB object_store_memory, 0.010000/0.010000 CPU_group_3_932e6a7cc1a315428bc51b7e0b38a227, 5.000000/5.000000 CPU_group_0_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_5_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_10_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_8_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_7_932e6a7cc1a315428bc51b7e0b38a227, 0.009000/5.049000 CPU_group_74230d0c7e8c8b02d219a8e2a6abcca1, 0.010000/0.010000 CPU_group_4_74230d0c7e8c8b02d219a8e2a6abcca1, 0.010000/0.010000 CPU_group_4_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_9_932e6a7cc1a315428bc51b7e0b38a227, 0.000000/5.000000 CPU_group_0_74230d0c7e8c8b02d219a8e2a6abcca1, 0.010000/0.010000 CPU_group_3_74230d0c7e8c8b02d219a8e2a6abcca1, 0.010000/0.010000 CPU_group_2_74230d0c7e8c8b02d219a8e2a6abcca1, 0.010000/0.010000 CPU_group_1_74230d0c7e8c8b02d219a8e2a6abcca1, 0.010000/0.010000 CPU_group_5_74230d0c7e8c8b02d219a8e2a6abcca1, 5.100000/5.100000 CPU_group_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_2_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_6_932e6a7cc1a315428bc51b7e0b38a227, 0.010000/0.010000 CPU_group_1_932e6a7cc1a315428bc51b7e0b38a227, 1.000000/1.000000 node:10.212.57.96}
. In total there are 0 pending tasks and 1 pending actors on this node. This is likely due to all cluster resources being claimed by actors. To resolve the issue, consider creating fewer actors or increase the resources available to this Ray cluster. You can ignore this message if this Ray cluster is expected to auto-scale.
```

Relevant excerpt:

```
It requires {CPU_group_74230d0c7e8c8b02d219a8e2a6abcca1: 0.010000} for placement
...
0.009000/5.049000 CPU_group_74230d0c7e8c8b02d219a8e2a6abcca1
```

It seems this is due to a repeated call of `pg.ready()` in the tune loop. The `ready()` check requests a resource:

```
        resource_name, value = self._get_a_non_zero_resource(bundle)
```

which uses a CPU  request of 0.001:

```
    def _get_a_non_zero_resource(self, bundle: Dict):
        # Any number between 0-1 should be fine.
        MOCK_VALUE = 0.001
        for key, value in bundle.items():
            if value > 0:
                value = MEMORY_RESOURCE_UNIT_BYTES \
                    if key == "memory" else MOCK_VALUE
                return key, value
        assert False, "This code should be unreachable."
```

Sometimes these tasks blocks the requested resources even after returning True (i.e. `ray.get(pg.ready())` succeeds). The actor can then not be scheduled.

I created a repro script that does not use Tune:

### Reproduction (REQUIRED)

```
import ray
import time

ray.init()

@ray.remote
class ChildActor:
    def __init__(self):
        self.val = 1


@ray.remote
class RemoteActor:
    def __init__(self):
        self.val = 1

main_actors = []
child_actors = []

for num_children in [10, 1, 20, 10, 5] * 4:
    pg = ray.util.placement_group(bundles=[{"CPU": 1}] + [{"CPU": 0.01}] * num_children)
    while not ray.get(pg.ready()):
        pass

    main_actor = RemoteActor.options(num_cpus=1, placement_group=pg, placement_group_bundle_index=0).remote()
    main_actors.append(main_actor)

    for j in range(num_children):
        actor = ChildActor.options(
            placement_group=pg,
            num_cpus=0.01).remote()
        child_actors.append(actor)
    pg.ready()

    print("Created actor with", num_children, "children")
    time.sleep(1)
```

cc @rkooo567 @wuisawesome 

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
Right now, we have a bug where the waiting jobs will fail due to resources capacity.
This PR fixed it by adding bundle id as an implicit flag.

TODO: add this flag to all jobs when the bundle is assigned.

## Related issue number

Closes #15842
## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc [hunk 1]
```diff
@@ -775,6 +773,9 @@ bool ClusterResourceScheduler::AllocateTaskResourceInstances(
         }
       }
     } else {
+      // Allocation failed. Restore node's local resources by freeing the resources
+      // of the failed allocation.
+      FreeTaskResourceInstances(task_allocation);
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_resource_scheduler.cc:778]: @wuisawesome I think it's a bug here, but not sure, could you confirm it?

File: src/ray/raylet/scheduling/cluster_resource_data.cc [hunk 2]
```diff
@@ -313,13 +316,6 @@ std::string NodeResources::DebugString(StringIdMap string_to_in_map) const {
   return buffer.str();
 }
 
-const std::string format_resource(std::string resource_name, double quantity) {
```
Comment (iycheng) [inline src/ray/raylet/scheduling/cluster_resource_data.cc:316]: Remove duplicate function in scheduling_resources.h

**Comment by rkooo567** [comment]
I will leave the label until tests are actually passing? If you'd like us to see the PR before that, let us know.

**Comment by iycheng** [comment]
> I will leave the label until tests are actually passing? If you'd like us to see the PR before that, let us know.

@rkooo567  It'll be good if you can check whether this solution is a reasonable one. It'll change the behavior of the current implementation. 

Before:

If resource == 0, it'll be scheduled to any node that fit even placement group bundle is given.

After:
Even resource == 0, when placement group is given,  it'll only be scheduled to the node allocated for that PG.

**Comment by rkooo567** [comment]
I think the general approach makes sense to me. Btw, did you verify with 

```python3
import ray
import time

ray.init()

@ray.remote
class ChildActor:
    def __init__(self):
        self.val = 1


@ray.remote
class RemoteActor:
    def __init__(self):
        self.val = 1

main_actors = []
child_actors = []

for num_children in [10, 1, 20, 10, 5] * 4:
    pg = ray.util.placement_group(bundles=[{"CPU": 1}] + [{"CPU": 0.01}] * num_children)
    while not ray.get(pg.ready()):
        pass

    main_actor = RemoteActor.options(num_cpus=1, placement_group=pg, placement_group_bundle_index=0).remote()
    main_actors.append(main_actor)

    for j in range(num_children):
        actor = ChildActor.options(
            placement_group=pg,
            num_cpus=0.01).remote()
        child_actors.append(actor)
    pg.ready()

    print("Created actor with", num_children, "children")
    time.sleep(1)
```

File: python/ray/tests/test_placement_group.py [hunk 3]
```diff
@@ -28,6 +28,30 @@ def method(self, x):
         return x + 2
 
 
+@pytest.mark.parametrize("connect_to_client", [False, True])
+def test_placement_ready(ray_start_cluster, connect_to_client):
```
Comment (wuisawesome) [inline python/ray/tests/test_placement_group.py:32]:
```suggestion
def test_placement_ready(ray_start_regular_shared, connect_to_client):
```

Comment (wuisawesome) [reply python/ray/tests/test_placement_group.py:32]: (And remove the corresponding cluster utils stuff)

**Review by wuisawesome — APPROVED** [review]

**Comment by iycheng** [comment]
@rkooo567  it's running good with this script.

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc (hunk 1 above)
Comment (iycheng) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:776]: @wuisawesome  in case you missed this one

File: src/ray/common/task/scheduling_resources.h [hunk 4]
```diff
@@ -21,6 +21,8 @@ const std::string kGPU_ResourceLabel = "GPU";
 const std::string kObjectStoreMemory_ResourceLabel = "object_store_memory";
 const std::string kMemory_ResourceLabel = "memory";
```
Comment (rkooo567) [inline src/ray/common/task/scheduling_resources.h:23]: nit, but can you remove the newline here? (put all these variables together without an empty line)

File: src/ray/raylet/placement_group_resource_manager_test.cc [hunk 5]
```diff
@@ -205,7 +215,7 @@ TEST_F(NewPlacementGroupResourceManagerTest, TestNewMultipleBundlesCommitAndRetu
   remaining_resource_instance = remaining_resource_scheduler->GetLocalNodeResources();
   ASSERT_TRUE(update_called_);
   ASSERT_TRUE(delete_called_);
-  CheckRemainingResourceCorrect(remaining_resource_instance);
+  // CheckRemainingResourceCorrect(remaining_resource_instance);
```
Comment (rkooo567) [inline src/ray/raylet/placement_group_resource_manager_test.cc:218]: Can you uncomment this and change the function to take into account of remaining bundle resource information?

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc (hunk 1 above)
Comment (rkooo567) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:808]: @wuisawesome please verify if this makes sense. @iycheng is this related to this PR? Can we make a separate PR for the fix?

File: python/ray/tests/test_placement_group.py [hunk 6]
```diff
@@ -28,6 +28,24 @@ def method(self, x):
...
+        def __init__(self):
+            pass
+
+        def v(self):
+            return 10
+
+    with connect_to_client_or_not(connect_to_client):
+        pg = ray.util.placement_group(bundles=[{"CPU": 1}])
+        ray.get(pg.ready())
+        a = Actor.options(num_cpus=1, placement_group=pg).remote()
```
Comment (rkooo567) [inline python/ray/tests/test_placement_group.py:44]: This is not the right test isn't this? We should test with the default actor that requires 0 cpu?

Comment (iycheng) [reply python/ray/tests/test_placement_group.py:44]: no, this PR only fix the issue https://github.com/ray-project/ray/issues/15842 here

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc (hunk 1 above)
Comment (iycheng) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:808]: I think it's just a fix for this one but feel like worth separating for it. I'm not sure whether it's easy to add a unit test for this as well. Lack of bandwidth for that if it's too difficult. I'm ok to roll it back and create an issue if you prefer.

Comment (rkooo567) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:808]: So it seems like the scenario you are thinking is the allocation only contains the subset of custom resources right? 

e.g., 

Task: custom_1: 1.0, custom_2: 1.0

Node: custom_1: 1.0

and this won't free custom_1.

I think this should be easy to unit test? If we add this in this PR, I think we should add unit test at least

Comment (iycheng) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc:808]: Ok, then let me roll it back for now and create a p1 ticket for this.

File: src/ray/raylet/placement_group_resource_manager_test.cc (hunk 5 above)
Comment (iycheng) [reply src/ray/raylet/placement_group_resource_manager_test.cc:218]: Goot catch! That's commented by accidiental.

**Comment by iycheng** [comment]
Roll it back and let's follow the bug in a separate ticket https://github.com/ray-project/ray/issues/17044

File: python/ray/tests/test_placement_group.py (hunk 6 above)
Comment (rkooo567) [reply python/ray/tests/test_placement_group.py:44]: Hmm I see. Can you actually add a comment here to explain what the test is doing? I think you can say; 

```
# Test when all the bundle is occupied by the placement group, ready task is still schedulable
```

Also, I prefer to test 0 cpu case because that's the behavior change the PR will invoke.

**Review by rkooo567 — CHANGES_REQUESTED** [review]
Can you follow up with https://github.com/ray-project/ray/pull/16819#discussion_r669131784? That's the last thing I'd like to discuss. Other parts LGMT

File: python/ray/tests/test_placement_group.py (hunk 6 above)
Comment (rkooo567) [reply python/ray/tests/test_placement_group.py:44]: oh actually, I saw https://github.com/ray-project/ray/pull/16819#issuecomment-875842202. 

Does that mean this won't work for 0 cpu actor case still right?

Comment (rkooo567) [reply python/ray/tests/test_placement_group.py:44]: Last followup after sync:
- Comment what the test is doing. 
- Make the bundle resource private?

**Review by rkooo567 — APPROVED** [review]
LGTM once the last comments are addressed https://github.com/ray-project/ray/pull/16819/files#r669822319

File: src/ray/raylet/scheduling/cluster_resource_scheduler.cc (hunk 1 above)
Comment (iycheng) [reply src/ray/raylet/scheduling/cluster_resource_scheduler.cc]: @rkooo567 I think this code path will only be reached in this case:

- placement group created
- schedule with that pg (before running this function)
- placement group returned
- fail to allocate the resource for placement group

The case you mentioned won't trigger this error, since it won't even be scheduled to this node.
