### PR TITLE
[core] Fix flaky `ShutdownCoordinator` test under tsan

### LINKED ISSUE #55801: CI test linux://src/ray/core_worker/tests:shutdown_coordinator_test is flaky
CI test **linux://src/ray/core_worker/tests:shutdown_coordinator_test** is flaky. Recent failures: 
	- https://buildkite.com/ray-project/postmerge/builds/12396#0198ca49-bc94-44a0-a4d8-8e7098d21969
	- https://buildkite.com/ray-project/postmerge/builds/12396#0198c9f1-d56e-4479-a045-f7d3dace2568

DataCaseName-linux://src/ray/core_worker/tests:shutdown_coordinator_test-END
Managed by OSS Test Policy

### PR DESCRIPTION
**Pull request by codope**
## Why are these changes needed?

TSAN failure is a data race only in the test's `FakeShutdownExecutor`, not production code. Fake was writing shared `std::string` fields from two threads without synchronization -- https://buildkite.com/ray-project/postmerge/builds/12666#019907c0-3bdd-4401-9aa8-6f13215ce819/176-796

- Added a `std::mutex` to `FakeShutdownExecutor` and guarded assignments to `last_exit_type` and `last_detail` in all `Execute*` methods. No production code changes.
- Added mutex-guarded getters in `FakeShutdownExecutor` and used them in the assertion to eliminate remaining unsynchronized reads in the TSAN test.

## Related issue number

Closes #55801

### CODE REVIEW

File: src/ray/core_worker/tests/shutdown_coordinator_test.cc [hunk 1]
```diff
@@ -41,42 +42,68 @@ class FakeShutdownExecutor : public ShutdownExecutorInterface {
 
   std::string last_exit_type;
   std::string last_detail;
+  mutable std::mutex mu_;
```
Comment (jjyao) [inline src/ray/core_worker/tests/shutdown_coordinator_test.cc]: Why mutable?

Comment (codope) [reply src/ray/core_worker/tests/shutdown_coordinator_test.cc]: It's marked mutable so const methods (like thread-safe getters GetLastExitType and GetLastDetail) can lock it.

Comment (edoakes) [reply src/ray/core_worker/tests/shutdown_coordinator_test.cc]: we should use `absl::Mutex` not `std::mutex`

Comment (codope) [reply src/ray/core_worker/tests/shutdown_coordinator_test.cc]: we'll need to take a dependency on `com_google_absl//absl/synchronization`, is that ok?

Comment (codope) [reply src/ray/core_worker/tests/shutdown_coordinator_test.cc]: For this test fake, the extra dependency and changes aren't buying much. So, i kept std::mutex.

Comment (edoakes) [reply src/ray/core_worker/tests/shutdown_coordinator_test.cc]: yep we already depend on it ~everywhere

Comment (codope) [reply src/ray/core_worker/tests/shutdown_coordinator_test.cc]: done 👍

**Review by jjyao — APPROVED** [review]
