### PR TITLE
[core] Reconstruct manually freed objects

### LINKED ISSUE #27265: [2.0][Data] chaos_pipelined_ingestion_* tests failed
### What happened + What you expected to happen

the [chaos_pipelined_ingestion_..](https://buildkite.com/ray-project/release-tests-branch/builds/837#01824a5f-cac7-4678-8b7d-3d1e7d9276b6) is still failing while the non-pipelined chaos tests are now passing after https://github.com/ray-project/ray/pull/27149 fix the split ownership. We should drill down to this and see why it failed.

### Versions / Dependencies

releases/2.0.0
this should fail on master as well.

### Reproduction script

run release test

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Object freed by the manual and internal `free` call previously would not get reconstructed. This PR introduces the following semantics after a `free` call:
1. If no failures occurs, and the object is needed by a downstream task, an `ObjectFreedError` will be thrown.
2. If a failure occurs, causing a downstream task to be re-executed, the freed object will get reconstructed as usual.

Also fixes some incidental bugs:
1. Don't crash on failure to contact local raylet during object recovery. This will produce a nicer error message because we will instead throw an application-level error when someone tries to get an object.
2. Fix a circular lock dependency between task failure <> task dependency resolution.

## Related issue number

Closes #27265.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
We should document this behavior in the fault tolerance page? cc @iycheng

**Comment by ericl** [comment]
Nice! This should also make it much easier to debug reconstruction, since
you can just use the delete call to emulate node failure.

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 1]
```diff
@@ -364,152 +364,153 @@ void CoreWorkerDirectTaskSubmitter::RequestNewWorkerIfNeeded(
       /*grant_or_reject=*/is_spillback,
       [this, scheduling_key, task_id, is_spillback, raylet_address = *raylet_address](
           const Status &status, const rpc::RequestWorkerLeaseReply &reply) {
-        absl::MutexLock lock(&mu_);
+        std::deque<TaskSpecification> tasks_to_fail;
```
Comment (scv119) [inline src/ray/core_worker/transport/direct_task_transport.cc:367]: is this file change purely adding error message?

**Review by scv119 — COMMENTED** [review]
The change looks reasonable to me but I don't have full context of reference counting. @jjyao @clarkzinzow can you take another look?

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.cc:367]: Ah no, there was actually a deadlock here before where the callback would call into the same class again and try to re-acquire the lock.

File: python/ray/exceptions.py [hunk 2]
```diff
@@ -443,6 +443,26 @@ def __str__(self):
         )
 
 
+@DeveloperAPI
+class ObjectFreedError(ObjectLostError, AssertionError):
```
Comment (jjyao) [inline python/ray/exceptions.py:447]: Why is it an AssertionError?

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.cc:367]: Which class method will be called again inside the callback? Should we make the lock reentrant?

**Review by jjyao — COMMENTED** [review]
LGTM.

**Review by clarkzinzow — APPROVED** [review]
LGTM!

File: python/ray/exceptions.py (hunk 2 above)
Comment (stephanie-wang) [reply python/ray/exceptions.py:447]: Ah mistake from copy-paste...

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_task_transport.cc:367]: SubmitTask, if the objects being failed here cause their dependent tasks to be resolved. IMO, I think this way of fixing the issue is more robust; if we allow the circular callback it can cause other internal data structures to get modified mid-execution.

**Review by ericl — APPROVED** [review]
