### PR TITLE
[core] Start less worker processes

### LINKED ISSUE #13725: [core][new scheduler] New scheduler starts too many workers
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 2.0dev

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

I saw this issue when testing Dask-on-Ray to sort a 100GB dataframe. After a minute or so, many more workers than the number of CPUs would get started. Some would get destroyed, but there were always consistently more workers than the number of CPUs. The number of workers was stable on the same workload with the old scheduler.

Script [here](https://gist.github.com/stephanie-wang/1bc13114de2422f509de8749e69878b7).

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by wuisawesome**
## Why are these changes needed?

This fixes a nasty bug which created too many worker processes. What was happening:

1. Scheduler tried to pop a worker process
2. Worker pool tries to create a process if the idle pool is empty
3. Worker process is created
3. Scheduler determines that the node does not have the available resources to run the task on the dispatch queue. This only happens if the task is unable to immediately acquire resources after leaving the scheduling queue. **_This only happens if the task first waits for dependencies to resolve, thus it only happens when we stress the object layer_**.
Scheduler would try to pop a worker process from the pool, then try to dispatch a task. When the scheduler tried to pop the worker, it would potentially create a new worker process.
4. Since the task couldn't run, there is now an idle worker. The worker pool kills it after 1s.
5. Repeat step 1. 

Theoretically this issue is very easy to solve, just check for resource availability, then pop the worker. In practice, we needed to clean up the dispatch loop logic quite a bit in order to avoid excessive pushing/popping of workers. 

## Related issue number

Closes #13725 

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 1]
```diff
@@ -183,51 +183,80 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+        if (!worker) {
+          // No worker available, we won't be able to schedule any kind of task.
+          // Worker processes spin up pretty quickly, so it's not worth trying to spill
+          // this task.
+          RAY_LOG(DEBUG) << "This node has available resources, but no worker processes "
+                            "to grant the lease.";
+          // We've already acquired resources so we need to release them to avoid
+          // double-acquiring when the next invocation of this function tries to schedule
+          // this task.
+          cluster_resource_scheduler_->ReleaseWorkerResources(allocated_instances);
```
Comment (wuisawesome) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:231]: @rkooo567 we forgot this subtle little detail at first ;)

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 2]
```diff
@@ -237,48 +266,25 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+bool ClusterTaskManager::TrySpillback(const Work &work) {
+  const auto &spec = std::get<0>(work).GetTaskSpecification();
+  int64_t _unused;
+  bool is_infeasible;
+  auto placement_resources = spec.GetRequiredPlacementResources().GetResourceMap();
+  std::string node_id_string = cluster_resource_scheduler_->GetBestSchedulableNode(
+      placement_resources, spec.IsActorCreationTask(), &_unused, &is_infeasible);
+
+  // All tasks on the dispatch queue must at least be feasible on the local node.
+  RAY_CHECK(!is_infeasible)
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:278]: I know this was there before, but is this actually a safe check? It seems like this could be true if the resources on this node got modified, because of placement groups for example. It would probably be safer to move it to the infeasible queue.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 3]
```diff
@@ -183,51 +183,80 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
-          num_pinned_task_arguments_ += args.size();
-          RAY_CHECK(pinned_task_arguments_.emplace(spec.TaskId(), std::move(args)).second)
-              << spec.TaskId();
-
-          auto reply = std::get<1>(*work_it);
-          auto callback = std::get<2>(*work_it);
-          Dispatch(worker, leased_workers_, task, reply, callback);
-        } else {
-          worker_pool_.PushWorker(worker);
+        // The local node has the available resources to run the task, so we should run
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:219]: It's getting a bit hard to read; could you split this block of code out into a helper function like `TrySpillback`?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 4]
```diff
@@ -183,51 +183,80 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
+      bool schedulable = cluster_resource_scheduler_->AllocateLocalTaskResources(
+          spec.GetRequiredResources().GetResourceMap(), allocated_instances);
+
+      if (!schedulable) {
+        // The local node currently does not have the resources to run the task, so we
+        // should try spilling to another node.
+        bool did_spill = TrySpillback(work);
+        if (!did_spill) {
+          // This must be the only feasible node in the cluster, so keep the task on the
+          // dispatch queue.
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:215]: Can you add a comment to say why we break?

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 5]
```diff
@@ -183,51 +183,80 @@ void ClusterTaskManager::DispatchScheduledTasksToWorkers(
...
-          auto reply = std::get<1>(*work_it);
-          auto callback = std::get<2>(*work_it);
-          Dispatch(worker, leased_workers_, task, reply, callback);
-        } else {
-          worker_pool_.PushWorker(worker);
+        // The local node has the available resources to run the task, so we should run
+        // it.
+        std::shared_ptr<WorkerInterface> worker = worker_pool_.PopWorker(spec);
+        if (!worker) {
+          // No worker available, we won't be able to schedule any kind of task.
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:223]: I think this comment was supposed to go with the `return;` statement.

**Review by stephanie-wang — CHANGES_REQUESTED** [review]
Nice find! Can we add a unit test for this case?

**Comment by rkooo567** [comment]
Can we add a python unit test that can detect regression in the future?

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 2 above)
Comment (rkooo567) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:278]: Hmm yeah our assumption was the value is static. But it is a good point about that placement group can change the story here. Potentially related issue; https://github.com/ray-project/ray/issues/14092

But do you think it makes sense to handle it in a different PR? Removing check from here probably could cause other issues.

**Review by rkooo567 — APPROVED** [review]
LGTM if you handle Stephanie's comment & add a regression test

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:278]: Yes, let's fix it in a separate PR. I'll make a note on the issue about the potential cause.

Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:278]: I suspect that will have an easy fix, but I agree it looks problematic in the placement group case, gut we shouldn't solve it in this PR (I'll add a TODO though)

File: src/ray/raylet/scheduling/cluster_task_manager.cc (hunk 3 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:219]: Yeah, we tried moving it into a helper, but it depends on a bunch of random things so it won't be as clean. I can move it as an organizational thing I guess

**Comment by wuisawesome** [comment]
@rkooo567 how about just the c++ unit test? this feels like a very awkward/flaky test to write at the python unit test layer.

**Comment by rkooo567** [comment]
Hmm isn't it pretty easy to make not flaky test here? Like

- Run the workload that was generating many worker files
- Just make sure the number of worker files are less than 1.5 * num_cpus.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 6]
```diff
@@ -398,6 +407,62 @@ TEST_F(ClusterTaskManagerTest, TestSpillAfterAssigned) {
...
+
+  rpc::RequestWorkerLeaseReply local_reply;
+  task_manager_.QueueAndScheduleTask(task2, &local_reply, callback);
+  task_manager_.QueueAndScheduleTask(task, &local_reply, callback);
+
+  ASSERT_EQ(num_callbacks, 1);
+  ASSERT_EQ(leased_workers_.size(), 1);
+  ASSERT_EQ(pool_.num_pops, 1);
+
+  {
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:436]: Can we please use only public methods to modify the task manager's internal state?

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc [hunk 7]
```diff
@@ -398,6 +407,62 @@ TEST_F(ClusterTaskManagerTest, TestSpillAfterAssigned) {
...
+  task_manager_.ScheduleAndDispatchTasks();
+
+  ASSERT_EQ(num_callbacks, 1);
+  ASSERT_EQ(leased_workers_.size(), 0);
+  ASSERT_EQ(pool_.num_pops, 1);
+
+  task_manager_.TaskFinished(worker, &task2);
+  pool_.PushWorker(worker);
+
+  RAY_LOG(ERROR) << task_manager_.DebugStr();
```
Comment (stephanie-wang) [inline src/ray/raylet/scheduling/cluster_task_manager_test.cc:456]: Please remove.

File: src/ray/raylet/scheduling/cluster_task_manager_test.cc (hunk 6 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/cluster_task_manager_test.cc]: Yeah, just realized all this fancy dependency manager stuff is here and you already wrote the test I was going to write, so I added some asserts to your test instead.

**Review by stephanie-wang — APPROVED** [review]
