### PR TITLE
[core] fix detached actor being unexpectedly killed

### LINKED ISSUE #40864: [core] Detached actor being killed when its parent actor crashes
While debugging a [release test failure](https://github.com/anyscale/runtime/issues/314), we discovered that in some cases Serve replica actors are being killed due to fate sharing with the controller.

This should **never** happen because all actors started by Serve (the controller, replicas, proxies) are detached, so they should not fate share with the controller ([relevant code in the raylet](https://github.com/ray-project/ray/blob/f5c59745d00982835feb145d14d1f9e0d4b0db6c/src/ray/raylet/node_manager.cc#L1079)).

We see a number of log lines like the following in the Raylet logs in multiple runs of the Serve long-running failure test case:
```
[2023-11-01 07:10:17,273 I 825 825] (raylet) node_manager.cc:1104: The leased worker dd7d4d82da8fef21e59667dba16f2bce15203c8832039284cbb26461 is killed because the owner process 2b60b506544d378c192b7e1cbf989be4058f41015c00fa7f30e50f91 died.
[2023-11-01 07:10:17,273 I 825 825] (raylet) node_manager.cc:1104: The leased worker 3844620037d1ea4a19c830bb548edd9726cd4521cc78f2c7871367d6 is killed because the owner process 2b60b506544d378c192b7e1cbf989be4058f41015c00fa7f30e50f91 died.
```

All of the referenced actors are detached actors.

### PR DESCRIPTION
**Pull request by rueian**
By replacing the inaccurate `worker->IsDetachedActor()` with `worker->GetAssignedTask().GetTaskSpecification().IsDetachedActor()`.

## Why are these changes needed?

In the previous PR https://github.com/ray-project/ray/pull/14184, the `worker.MarkDetachedActor()` that happened on assigning a task to a worker was [deleted](https://github.com/ray-project/ray/pull/14184/files#diff-d2f22b8f1bf5f9be47dacae8b467a72ee94629df12ffcc18b13447192ff3dbcfL1982).
image
And that causes a leased worker for a detached worker can be killed by [HandleUnexpectedWorkerFailure](https://github.com/ray-project/ray/blob/f5c59745d00982835feb145d14d1f9e0d4b0db6c/src/ray/raylet/node_manager.cc#L1059), as mentioned in https://github.com/ray-project/ray/issues/40864, which is also even triggered by a normal exit of driver. The reproducible scripts can be found in [the comment](https://github.com/ray-project/ray/issues/40864#issuecomment-2941105709).

I think actually `Worker::IsDetachedActor` and `Worker::MarkDetachedActor` are redundant and better be removed because we can access the info of whether the worker is detached or not through its assigned task.

The info is first ready after `worker->SetAssignedTask(task)`(L962) during `LocalTaskManager::Dispatch` and then the worker is inserted into the `leased_workers` map (L972).
https://github.com/ray-project/ray/blob/118c37058ae2904a79da9be160633a6a8d3ee3b6/src/ray/raylet/local_task_manager.cc#L962-L972

Therefore, we can access the info through `worker->GetAssignedTask().GetTaskSpecification().IsDetachedActor()` safely while looping over the `leased_workers_` in the `NodeManager`. By doing that, we don't need to worry about we could miss `worker.MarkDetachedActor()` sometimes.

## Related issue number
Closes https://github.com/ray-project/ray/issues/40864
Related to https://github.com/ray-project/kuberay/issues/3701 and https://github.com/ray-project/kuberay/pull/3700

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
open an issue to track the progress: https://github.com/ray-project/kuberay/pull/3700

File: src/ray/raylet/node_manager.cc [hunk 1]
```diff
@@ -966,18 +966,10 @@ void NodeManager::NodeRemoved(const NodeID &node_id) {
...
-    // If the leased worker's owner was on the failed node, then kill the leased
-    // worker.
-    RAY_LOG(INFO).WithField(worker->WorkerId()).WithField(owner_node_id)
-        << "The leased worker is killed because the owner node died.";
-    KillWorker(worker);
-  }
+  KillWorkersOwnedByNodeID(
+      leased_workers_,
+      [this](const std::shared_ptr<WorkerInterface> &worker) { KillWorker(worker); },
+      node_id);
```
Comment (rueian) [inline src/ray/raylet/node_manager.cc]: This PR essentially replaces `worker->IsDetachedActor()` with `worker->GetAssignedTask().GetTaskSpecification().IsDetachedActor()`.

To make the changes be tested, I followed the practice in [TestHandleReportWorkerBacklog](https://github.com/ray-project/ray/pull/50280) to extract the loop on the `leased_workers_` to static methods  `KillWorkersOwnedByNodeID` and `KillWorkersOwnedByWorkerID` for unit testing.

**Comment by rueian** [comment]
> open an issue to track the progress: [ray-project/kuberay#3700](https://github.com/ray-project/kuberay/pull/3700)

@kevin85421 Done. This PR is also ready for review. Please take a look. Thanks!

File: src/ray/raylet/node_manager.cc (hunk 1 above)
Comment (edoakes) [reply src/ray/raylet/node_manager.cc]: Should we fully remove `worker.IsDetachedActor()` and/or replace its implementation with what you have here? Looks like it's likely to cause similar bugs in the future.

Comment (rueian) [reply src/ray/raylet/node_manager.cc]: Sure. `Worker::IsDetachedActor` will no longer be used after this PR. I was originally planning to remove it in a follow-up PR, but now the removal is included here.

File: src/ray/raylet/node_manager.h [hunk 2]
```diff
@@ -304,6 +313,14 @@ class NodeManager : public rpc::NodeManagerServiceHandler,
   /// \return Void.
   void NodeRemoved(const NodeID &node_id);
 
+  /// This is created for unit test purpose so that we don't need to create
+  /// a node manager in order to test KillWorkersOwnedByNodeID.
+  static void KillWorkersOwnedByNodeID(
+      const absl::flat_hash_map<WorkerID, std::shared_ptr<WorkerInterface>>
+          &leased_workers,
+      const std::function<void(const std::shared_ptr<WorkerInterface> &)> &kill_worker,
+      const NodeID &node_id);
```
Comment (edoakes) [inline src/ray/raylet/node_manager.h]: This is an anti-pattern, we should be writing tests against the public interface of the relevant class (in this case, `NodeManager`.

Is it possible to rewrite it in that way instead?

**Comment by edoakes** [comment]
@israbbani can you help review this PR please

File: src/ray/raylet/test/util.h [hunk 3]
```diff
@@ -119,16 +118,11 @@ class MockWorker : public WorkerInterface {
     RAY_CHECK(false) << "Method unused";
     return "";
   }
-  void MarkDetachedActor() override { is_detached_actor_ = true; }
-  bool IsDetachedActor() const override { return is_detached_actor_; }
```
Comment (israbbani) [inline src/ray/raylet/test/util.h:123]: The code would be a simpler if you deleted `MarkDetachedActor()` and changed the implementation of `IsDetachedActor` to do the right thing i.e.

```C++
bool IsDetachedActor() const override {
    return assigned_task_.GetTaskSpecification().IsDetachedActor();
}
```

That way the rest of the code will work as is.

Comment (israbbani) [reply src/ray/raylet/test/util.h:123]: When calling a chain of functions like that, it's also worth making sure that each function in the chain returns a valid object i.e. GetTaskSpecification() always returns a properly constructed TaskSpec object.

File: src/ray/raylet/node_manager.h (hunk 2 above)
Comment (israbbani) [reply src/ray/raylet/node_manager.h]: +1. I think we're going to have to setup a NodeManager with the right workers and then call the public API.

**Review by israbbani — COMMENTED** [review]
Excellent find and root cause. I left a few comments.

File: src/ray/raylet/test/util.h (hunk 3 above)
Comment (rueian) [reply src/ray/raylet/test/util.h:123]: > When calling a chain of functions like that, it's also worth making sure that each function in the chain returns a valid object i.e. GetTaskSpecification() always returns a properly constructed TaskSpec object.

Hi @israbbani, are you suggesting that I add a check in the GetTaskSpecification() method to ensure that the underlying specification is properly constructed, or make the method fail if it’s not?

Comment (israbbani) [reply src/ray/raylet/test/util.h:123]: Hi @rueian. I looked at the code and in this case RayTask and TaskSpec both have default no-args constructors so we should be okay to just write
```C++
bool IsDetachedActor() const override {
    return assigned_task_.GetTaskSpecification().IsDetachedActor();
}
```

File: src/ray/raylet/node_manager.h (hunk 2 above)
Comment (rueian) [reply src/ray/raylet/node_manager.h]: Hi @edoakes and @israbbani, thanks for the reviews.

I managed to test this with public APIs. I found that was quite complicated:
1. The public way to create workers is by calling `NodeManager::HandleRequestWorkerLease` via a grpc client.
2. However, that will let the worker pool launch a real worker which then requires a connection to GCS.
3. Even with a GCS set up, we would need to create a real detached actor creation task and have the GCS publish a worker failure message to trigger `NodeManager::HandleUnexpectedWorkerFailure`.

Then the whole steps essentially become an E2E test which, I think, may not be suitable for `node_manager_test.cc`. Thus, I instead mocked the entire worker pool in the `NodeManger` to avoid relying on GCS:

1. Updated the `WorkerPoolInterface` to cover all methods of `WorkerPool`.
2. Updated all the existing mock implementations of `WorkerPoolInterface` to cover new missing methods.
3. Replaced `WorkerPool worker_pool_` to `WorkerPoolInterface &worker_pool_` in the `NodeManger` so that we can swap it out for testing.
4. Added a new `NodeManager` constructor that accepts a `WorkerPoolInterface &worker_pool_`.
5. Modified the old `NodeManager` constructor to use the new constructor under the hood.
6. Finally, used a `MockWorkerPool` in `node_manager_test.cc` to test this PR.

Now the PR is quite large due to the above changes.
Please let me know if you have any concerns about this approach or suggestions for improvement.

Comment (edoakes) [reply src/ray/raylet/node_manager.h]: @rueian this is absolutely the right direction, great work and thanks for slogging through that!

One question about the approach: why do we need to maintain both constructors? Looks like we can instead dependency inject the `worker_pool_` when constructing the `NodeManager` in the raylet `main.cc` codepath as well.

Comment (rueian) [reply src/ray/raylet/node_manager.h]: The real `WorkerPool` still depends on `cluster_resource_scheduler_` and `cluster_task_manager_`, both of which are constructed by the `NodeManager` constructor. Additionally, `cluster_task_manager_` depends on `local_task_manager_`, which in turn depends on `leased_workers_`.

If we want to inject the real `WorkerPool` from `main.cc`, I believe we’ll also need to move all these dependencies to `main.cc`. If that approach sounds good, I will proceed to make the change.

Comment (edoakes) [reply src/ray/raylet/node_manager.h]: as painful as it is, yes that is the right direction. it will also allow us to test with fake implementations of those other classes if ever needed.

Comment (rueian) [reply src/ray/raylet/node_manager.h]: Ok, I have moved all required dependencies to `main.cc`:

```c
  std::shared_ptr<plasma::PlasmaClient> plasma_client;
  std::shared_ptr<ray::raylet::NodeManager> node_manager;
  std::shared_ptr<ray::rpc::ClientCallManager> client_call_manager;
  std::shared_ptr<ray::rpc::CoreWorkerClientPool> worker_rpc_pool;
  std::shared_ptr<ray::raylet::WorkerPoolInterface> worker_pool;
  std::shared_ptr<ray::raylet::LocalObjectManager> local_object_manager;
  std::shared_ptr<ray::ClusterResourceScheduler> cluster_resource_scheduler;
  std::shared_ptr<ray::raylet::LocalTaskManager> local_task_manager;
  std::shared_ptr<ray::raylet::ClusterTaskManagerInterface> cluster_task_manager;
  std::shared_ptr<ray::pubsub::SubscriberInterface> core_worker_subscriber;
  std::shared_ptr<ray::IObjectDirectory> object_directory;
  std::shared_ptr<ray::ObjectManagerInterface> object_manager;
  std::shared_ptr<ray::raylet::DependencyManager> dependency_manager;
  absl::flat_hash_map<WorkerID, std::shared_ptr<ray::raylet::WorkerInterface>> leased_workers;
```

Now, we can inject the worker_pool into the `NodeManager` and keep only one constructor for `NodeManager`.

Comment (rueian) [reply src/ray/raylet/node_manager.h]: Again, now the PR is quite large. Please let me know if you have any concerns or suggestions for improvement regarding that.

Comment (rueian) [reply src/ray/raylet/node_manager.h]: Note that the build errors are unrelated to this change. They were:
image

Comment (edoakes) [reply src/ray/raylet/node_manager.h]: > Again, now the PR is quite large. Please let me know if you have any concerns or suggestions for improvement regarding that.

In general, it's best practice to split behavior changes and pure refactoring into separate PRs. Given that the scope of refactoring here is quite large, we should do that, so concretely:

- Make a separate PR that makes all the interface changes for dependency injection. In this PR, you can add 1-2 minor unit tests for the node manager.
- Then rebase this PR on top of that one. It'll be scoped to only the behavior change then.

Comment (rueian) [reply src/ray/raylet/node_manager.h]: Sure, I have opened a separate PR https://github.com/ray-project/ray/pull/53782 that does pure refactoring.
Please take a look. I will rebase the current one once the pure refactoring PR is merged.

Comment (rueian) [reply src/ray/raylet/node_manager.h]: Hi @edoakes @israbbani, thanks for merging the interface refactoring. I have rebased this PR on top of that. Now this PR contains only the change to `Worker::IsDetachedActor` and a unit test. Please take a look again.

File: src/ray/raylet/test/util.h [hunk 4]
```diff
@@ -47,6 +48,11 @@ class MockWorker : public WorkerInterface {
     task_ = assigned_task;
     task_assign_time_ = absl::Now();
     root_detached_actor_id_ = assigned_task.GetTaskSpecification().RootDetachedActorId();
+    const auto &task_spec = assigned_task.GetTaskSpecification();
+    SetJobId(task_spec.JobId());
+    SetBundleId(task_spec.PlacementGroupBundleId());
+    SetOwnerAddress(task_spec.CallerAddress());
```
Comment (rueian) [inline src/ray/raylet/test/util.h:54]: Make the MockWorker::SetAssignedTask align with the real one.

File: src/ray/raylet/test/util.h [hunk 5]
```diff
@@ -85,9 +91,9 @@ class MockWorker : public WorkerInterface {
   void MarkUnblocked() override { blocked_ = false; }
   bool IsBlocked() const override { return blocked_; }
 
-  Process GetProcess() const override { return Process::CreateNewDummy(); }
+  Process GetProcess() const override { return proc_; }
   StartupToken GetStartupToken() const override { return 0; }
-  void SetProcess(Process proc) override { RAY_CHECK(false) << "Method unused"; }
+  void SetProcess(Process proc) override { proc_ = std::move(proc); }
```
Comment (rueian) [inline src/ray/raylet/test/util.h:96]: This allows us to inject a Process into a MockWorker.

**Comment by edoakes** [comment]
ping @israbbani

**Comment by israbbani** [comment]
> ping @israbbani

@rueian I'm sorry. I've been pulled into a P0 issue. I'll review this tomorrow once I've resolved the issue. Thanks for being patient!

File: src/ray/raylet/test/node_manager_test.cc [hunk 6]
```diff
@@ -391,6 +392,146 @@ TEST_F(NodeManagerTest, TestRegisterGcsAndCheckSelfAlive) {
   thread.join();
 }
 
+TEST_F(NodeManagerTest, TestDetachedWorkerNotToBeKilledByFailedWorker) {
```
Comment (israbbani) [inline src/ray/raylet/test/node_manager_test.cc]:
```suggestion
TEST_F(NodeManagerTest, TestDetachedWorkerIsKilledByFailedWorker) {
```

File: src/ray/raylet/test/node_manager_test.cc [hunk 7]
```diff
@@ -391,6 +392,146 @@ TEST_F(NodeManagerTest, TestRegisterGcsAndCheckSelfAlive) {
...
+      .WillOnce(Return(Status::OK()));
+  EXPECT_CALL(*mock_gcs_client_->mock_node_accessor, AsyncCheckSelfAlive(_, _))
+      .WillRepeatedly(Return(Status::OK()));
+  EXPECT_CALL(mock_worker_pool_, GetAllRegisteredWorkers(_, _))
+      .WillRepeatedly(Return(std::vector<std::shared_ptr<WorkerInterface>>{}));
+  EXPECT_CALL(mock_worker_pool_, GetAllRegisteredDrivers(_))
+      .WillRepeatedly(Return(std::vector<std::shared_ptr<WorkerInterface>>{}));
+  EXPECT_CALL(mock_worker_pool_, IsWorkerAvailableForScheduling())
+      .WillRepeatedly(Return(false));
+  EXPECT_CALL(mock_worker_pool_, PrestartWorkers(_, _)).Times(1);
```
Comment (israbbani) [inline src/ray/raylet/test/node_manager_test.cc:452]: All unit tests should be written against an API and not an implementation. See discussion [here](https://github.com/ray-project/ray/pull/52812#discussion_r2085325706) for more context.

Are all of these EXPECT_CALLs strictly necessary?

File: src/ray/raylet/test/node_manager_test.cc [hunk 8]
```diff
@@ -391,6 +392,146 @@ TEST_F(NodeManagerTest, TestRegisterGcsAndCheckSelfAlive) {
...
+                                               /*ray_namespace=*/"",
+                                               /*is_asyncio=*/false,
+                                               /*concurrency_groups=*/{},
+                                               /*extension_data=*/"",
+                                               /*execute_out_of_order=*/false,
+                                               /*root_detached_actor_id=*/actor_id);
+
+    // Invoke RequestWorkerLease to request a leased worker for the task in the
+    // NodeManager.
+    grpc::ClientContext context;
```
Comment (israbbani) [inline src/ray/raylet/test/node_manager_test.cc:498]: Can you call `HandleRequestWorkerLease` directly instead of creating a gRPC client?

File: src/ray/raylet/test/node_manager_test.cc [hunk 9]
```diff
@@ -391,6 +392,146 @@ TEST_F(NodeManagerTest, TestRegisterGcsAndCheckSelfAlive) {
...
+    publish_worker_failure_callback(std::move(delta_data));
+  }};
+
+  // Prepare a mock worker with a real process so that we can check if the process is
+  // alive later.
+  const auto worker = std::make_shared<MockWorker>(WorkerID::FromRandom(), 10);
+  auto [proc, spawn_error] =
+      Process::Spawn(std::vector<std::string>{"sleep", "1000"}, true);
+  EXPECT_FALSE(spawn_error);
+  worker->SetProcess(proc);
```
Comment (israbbani) [inline src/ray/raylet/test/node_manager_test.cc:629]: If possible, we should avoid creating subprocesses in unit tests. Ideally tests run fast and have as few dependencies as possible. Is there a way to detect this through inspecting the MockWorker?

File: src/ray/raylet/test/node_manager_test.cc [hunk 10]
```diff
@@ -391,6 +392,146 @@ TEST_F(NodeManagerTest, TestRegisterGcsAndCheckSelfAlive) {
...
+      .WillRepeatedly(Return(false));
+  EXPECT_CALL(mock_worker_pool_, PrestartWorkers(_, _)).Times(1);
+
+  std::promise<void> pop_worker_callback_promise;
+  PopWorkerCallback pop_worker_callback;
+  gcs::ItemCallback<rpc::WorkerDeltaData> publish_worker_failure_callback;
+
+  // Save the publish_worker_failure_callback for publishing a worker failure event later.
+  EXPECT_CALL(*mock_gcs_client_->mock_worker_accessor,
+              AsyncSubscribeToWorkerFailures(_, _))
```
Comment (israbbani) [inline src/ray/raylet/test/node_manager_test.cc:460]: Do we need a test for the NodeChange notification to test the `NodeManager::NodeRemoved` code as well?

**Review by israbbani — COMMENTED** [review]
Looks good. A few more comments about making the test a little more robust.

File: src/ray/raylet/test/node_manager_test.cc (hunk 7 above)
Comment (rueian) [reply src/ray/raylet/test/node_manager_test.cc:452]: The test will still pass without those assertions, but without any of them, there will be GMOCK WARNINGs like this:
```
GMOCK WARNING:
Uninteresting mock function call - returning default value.
    Function call: AsyncSubscribeToNodeChange(@0x16b1e21e8 32-byte object <88-85 68-07 01-00 00-00 00-B6 00-3A 01-00 00-00 10-93 81-38 01-00 00-00 E8-21 1E-6B 01-00 00-00>, @0x16b1e21c8 32-byte object <70-86 68-07 01-00 00-00 00-B6 00-3A 01-00 00-00 E8-28 1E-6B 01-00 00-00 C8-21 1E-6B 01-00 00-00>)
          Returns: OK
NOTE: You can safely ignore the above warning unless this call should not happen.  Do not suppress it by blindly adding an EXPECT_CALL() if you don't mean to enforce the call.  See https://github.com/google/googletest/blob/main/docs/gmock_cook_book.md#knowing-when-to-expect-useoncall for details.
```

Do you think we should still remove those assertions and keep those warnings?

File: src/ray/raylet/test/node_manager_test.cc (hunk 8 above)
Comment (rueian) [reply src/ray/raylet/test/node_manager_test.cc:498]: I wish I could, but `HandleRequestWorkerLease` is a private method.

File: src/ray/raylet/test/node_manager_test.cc (hunk 9 above)
Comment (rueian) [reply src/ray/raylet/test/node_manager_test.cc:629]: I agree, and that will require us to move the entire [`NodeManager::KillWorker`](https://github.com/ray-project/ray/blob/dd1e3cb42b4607954f8d7e52f2df660f972482e0/src/ray/raylet/node_manager.cc#L386) to worker implementations, which makes sense to me actually, but a little out of the scope of this PR. Do you think we should do that together here?

File: src/ray/raylet/test/node_manager_test.cc (hunk 10 above)
Comment (rueian) [reply src/ray/raylet/test/node_manager_test.cc:460]: I deleted the test after refactoring because the `NodeRemoved ` case was not linked to the original issue, but I will add it back by duplicating the refactored test.

Comment (rueian) [reply src/ray/raylet/test/node_manager_test.cc:460]: The test for NodeChange notification has been added. @israbbani, please take a look again. Thanks!

File: src/ray/raylet/test/node_manager_test.cc (hunk 8 above)
Comment (israbbani) [reply src/ray/raylet/test/node_manager_test.cc:498]: Huh. This is strange to me. Maybe we can revisit this later.

File: src/ray/raylet/test/node_manager_test.cc (hunk 9 above)
Comment (israbbani) [reply src/ray/raylet/test/node_manager_test.cc:629]: Lets tackle this separately in another PR. I'd be happy to review it!

**Review by israbbani — APPROVED** [review]
🚢 Excellent work. Lets keep cleaning this stuff up!

**Comment by israbbani** [comment]
@rueian can you debug the doc failure? @edoakes ready for merge after that.

**Comment by rueian** [comment]
> @rueian can you debug the doc failure? @edoakes ready for merge after that.

@israbbani @edoakes Thanks for the reviews. Now, the doc failure has been resolved. It was just a `git pull` failure when building the doc.

**Comment by edoakes** [comment]
@rueian looks great, thank you.

In the future, add the `go` label to run the CI tests once ready.
