### PR TITLE
[core] [compiled graphs] Exit dagref waiting based on sigint

### LINKED ISSUE #47136: [aDAG][Core] ray.get on a DagReference doesn't work with ctrl+C
### What happened + What you expected to happen

ray.get on a channel doesn't work with ctrl+C when I have long timeout. 

### Versions / Dependencies

master

### Reproduction script

```
import ray
from ray.dag.input_node import InputNode
import time

@ray.remote
class Worker:
    def __init__(self):
        pass

    def echo(self, x):
        time.sleep(10)
        return x

w = Worker.remote()

with InputNode() as inp:
    dag = w.echo.bind(inp)

cdag = dag.experimental_compile()
ref = cdag.execute(1)
print("getting result ...")
res = ray.get(ref)
print("got result {}".format(res))
```

### Issue Severity

None

### PR DESCRIPTION
**Pull request by dayshah**
## Why are these changes needed?
This pr does two things
- Uses check_signals from cython code that checks signals using PyErr_CheckSignals to check for signals the same way it's checked for the standard ray get control flow. https://github.com/ray-project/ray/blob/d9f69fd4549b2ee951db7acd0480ebde6ee01440/src/ray/core_worker/store_provider/memory_store/memory_store.cc#L359-L370
- Turns timeout point to an optional from a unique ptr to avoid an unnecessary heap allocation.

Example of output off of ctrl+c
```
  File "/Users/dhyey/ray/python/ray/_private/worker.py", line 893, in get_objects
    ] = self.core_worker.get_objects(
  File "python/ray/_raylet.pyx", line 3188, in ray._raylet.CoreWorker.get_objects
  File "python/ray/includes/common.pxi", line 78, in ray._raylet.check_status
KeyboardInterrupt
2024-12-23 10:51:36,148	INFO compiled_dag_node.py:1885 -- Tearing down compiled DAG
2024-12-23 10:51:36,148	INFO compiled_dag_node.py:1890 -- Cancelling compiled worker on actor: Actor(Actor, 743f0c9b338d6e2bdcb1825001000000)
2024-12-23 10:51:36,150	INFO compiled_dag_node.py:1910 -- Waiting for worker tasks to exit
2024-12-23 10:52:06,249	WARNING compiled_dag_node.py:1850 -- Compiled DAG actor Actor(Actor, 743f0c9b338d6e2bdcb1825001000000) is still running 30s after teardown(). Force-killing actor.
2024-12-23 10:52:06,256	INFO compiled_dag_node.py:1912 -- Teardown complete
```

## Related issue number

Closes https://github.com/ray-project/ray/issues/47136
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/object_manager/common.cc [hunk 1]
```diff
@@ -180,17 +198,25 @@ Status PlasmaObjectHeader::ReadAcquire(
 
   // TODO(jhumphri): Wouldn't a futex be better here than polling?
   // Wait for the requested version (or a more recent one) to be sealed.
-  while (version < version_to_read || !is_sealed) {
-    RAY_CHECK_EQ(sem_post(sem.header_sem), 0);
-    sched_yield();
```
Comment (dayshah) [inline src/ray/object_manager/common.cc:185]: this is something that should change looks like there's an old todo and was just a short-term hacky fix https://github.com/ray-project/ray/pull/44720, will look at a better way to do this, I think most times the scheduler will just try to run this again

File: src/ray/core_worker/experimental_mutable_object_manager.cc [hunk 2]
```diff
@@ -461,15 +472,14 @@ Status MutableObjectManager::SetErrorAll() {
...
 }
 
-std::unique_ptr<std::chrono::steady_clock::time_point>
-MutableObjectManager::ToTimeoutPoint(int64_t timeout_ms) {
-  if (timeout_ms == -1) {
-    return nullptr;
+std::optional<std::chrono::steady_clock::time_point> MutableObjectManager::ToTimeoutPoint(
+    int64_t timeout_ms) {
+  std::optional<std::chrono::steady_clock::time_point> timeout_point;
+  if (timeout_ms != -1) {
```
Comment (ruisearch42) [inline src/ray/core_worker/experimental_mutable_object_manager.cc:478]: nit: let's keep the original order, check -1 and return early

File: src/ray/core_worker/experimental_mutable_object_manager.h [hunk 3]
```diff
@@ -221,9 +221,8 @@ class MutableObjectManager : public std::enable_shared_from_this<MutableObjectMa
  private:
   /// Converts a timeout in milliseconds to a timeout point.
   /// \param[in] timeout_ms The timeout in milliseconds.
-  /// \return The timeout point, or nullptr if the timeout_ms is -1.
-  std::unique_ptr<std::chrono::steady_clock::time_point> ToTimeoutPoint(
-      int64_t timeout_ms);
+  /// \return The timeout point, or std::nullopt if it doesn't exist.
```
Comment (ruisearch42) [inline src/ray/core_worker/experimental_mutable_object_manager.h:224]: It's vague what "doesn't exist" means, let's still mention the special value -1

File: src/ray/core_worker/experimental_mutable_object_manager.cc [hunk 4]
```diff
@@ -315,13 +320,20 @@ Status MutableObjectManager::ReadAcquire(const ObjectID &object_id,
...
   bool expired = false;
-  do {
-    RAY_RETURN_NOT_OK(object->header->CheckHasError());
-    // The channel is still open. This lock ensures that there is only one reader
-    // at a time. The lock is released in `ReadRelease()`.
-    locked = channel->lock->try_lock();
-    expired = timeout_point && std::chrono::steady_clock::now() >= *timeout_point;
-  } while (!locked && !expired);
+  {
+    std::signal(SIGINT, SignalHandler);
```
Comment (ruisearch42) [inline src/ray/core_worker/experimental_mutable_object_manager.cc:324]: hmm, this is called every time `ReadAcquire()` is called. I think we should do it only once.

File: src/ray/core_worker/experimental_mutable_object_manager.cc [hunk 5]
```diff
@@ -315,13 +320,20 @@ Status MutableObjectManager::ReadAcquire(const ObjectID &object_id,
...
+      RAY_RETURN_NOT_OK(object->header->CheckHasError());
+      // The channel is still open. This lock ensures that there is only one reader
+      // at a time. The lock is released in `ReadRelease()`.
+      locked = channel->lock->try_lock();
+      expired = timeout_point && std::chrono::steady_clock::now() >= *timeout_point;
+    } while (!locked && !expired && signal_received != -1);
+  }
+  if (signal_received != -1) {
+    RAY_LOG(ERROR) << "Interrupted by signal";
+    return Status::Interrupted("Interrupted by signal");
```
Comment (ruisearch42) [inline src/ray/core_worker/experimental_mutable_object_manager.cc:335]: We should print out what the signal is.

Also, can you show an example in the description what the final exception looks like?

File: src/ray/object_manager/common.cc [hunk 6]
```diff
@@ -180,17 +198,25 @@ Status PlasmaObjectHeader::ReadAcquire(
...
-    // We need to get the desired version before timeout
-    if (timeout_point && std::chrono::steady_clock::now() >= *timeout_point) {
-      return Status::ChannelTimeoutError(absl::StrCat(
-          "Timed out waiting for object available to read. ObjectID: ", object_id.Hex()));
+  {
+    std::signal(SIGINT, SignalHandler);
```
Comment (ruisearch42) [inline src/ray/object_manager/common.cc:202]: ditto: can we do this only once?

File: src/ray/object_manager/common.cc [hunk 7]
```diff
@@ -180,17 +198,25 @@ Status PlasmaObjectHeader::ReadAcquire(
...
+      // Unlike other header, this is used for busy waiting, so we need to apply
+      // timeout_point.
+      RAY_RETURN_NOT_OK(TryToAcquireSemaphore(sem.header_sem, timeout_point));
     }
-    // Unlike other header, this is used for busy waiting, so we need to apply
-    // timeout_point.
-    RAY_RETURN_NOT_OK(TryToAcquireSemaphore(sem.header_sem, timeout_point));
+  }
+  if (signal_received != -1) {
+    return Status::Interrupted("Interrupted by signal: " +
```
Comment (ruisearch42) [inline src/ray/object_manager/common.cc:218]: Can you add a unit test?

**Review by ruisearch42 — COMMENTED** [review]
Overall looks good. Can you add a unit test?

File: src/ray/core_worker/experimental_mutable_object_manager.cc [hunk 8]
```diff
@@ -315,13 +320,21 @@ Status MutableObjectManager::ReadAcquire(const ObjectID &object_id,
...
   bool expired = false;
-  do {
-    RAY_RETURN_NOT_OK(object->header->CheckHasError());
-    // The channel is still open. This lock ensures that there is only one reader
-    // at a time. The lock is released in `ReadRelease()`.
-    locked = channel->lock->try_lock();
-    expired = timeout_point && std::chrono::steady_clock::now() >= *timeout_point;
-  } while (!locked && !expired);
+  {
+    std::signal(SIGINT, SignalHandler);
```
Comment (kevin85421) [inline src/ray/core_worker/experimental_mutable_object_manager.cc:324]: What is the scope of the signal handler? Does it affect the whole process?

**Review by kevin85421 — COMMENTED** [review]
1. Would you mind providing more details in the PR description about where the Python code gets stuck?

2. I remember that you were also investigating the limitations of `PyErr_CheckSignals`. Would you mind including that in the PR description?

3. Is it possible to listen for signals in the Python main thread and call `teardown` when the process receives them? In that case, the codepath seems to be more unified.

File: src/ray/core_worker/experimental_mutable_object_manager.cc (hunk 5 above)
Comment (dayshah) [reply src/ray/core_worker/experimental_mutable_object_manager.cc]: added in description

File: src/ray/object_manager/common.cc (hunk 7 above)
Comment (dayshah) [reply src/ray/object_manager/common.cc:216]: added

File: src/ray/core_worker/experimental_mutable_object_manager.cc (hunk 8 above)
Comment (dayshah) [reply src/ray/core_worker/experimental_mutable_object_manager.cc:324]: it's just this scope where it's contained, not the whole process

**Comment by dayshah** [comment]
> 1. Would you mind providing more details in the PR description about where the Python code gets stuck?
> 2. I remember that you were also investigating the limitations of `PyErr_CheckSignals`. Would you mind including that in the PR description?
> 3. Is it possible to listen for signals in the Python main thread and call `teardown` when the process receives them? In that case, the codepath seems to be more unified.

1. Currently the code seems to most often get stuck inside `PlasmaObjectHeader::ReadAcquire`. 
2. Yup, there are limitations I've outlined that issue in #49319 which is fixing that problem separately. Avoided PyErr_CheckSignals here because of that, not functioning on non-main thread + checking signals through this should be more performant that calling into the cpython function on every iteration.
3. Everyone should be calling `get(dagref)` on the main thread. We can use the check_signals calling into PyErr_CheckSignals logic for this and it'll work, I just think we should move to a consistent approach across all core worker code.

File: src/ray/core_worker/experimental_mutable_object_manager.cc (hunk 4 above)
Comment (dayshah) [reply src/ray/core_worker/experimental_mutable_object_manager.cc:324]: Only doing this once would mean placing the signal handler on the process, which is different from normal ray.get, which only checks for signals on the waiting while loops. I'm not totally sure why it does that though?

Comment (ruisearch42) [reply src/ray/core_worker/experimental_mutable_object_manager.cc:324]: Which loop of normal ray.get were you referring to?

File: src/ray/core_worker/experimental_mutable_object_manager.cc (hunk 8 above)
Comment (ruisearch42) [reply src/ray/core_worker/experimental_mutable_object_manager.cc:324]: hmm, that sounds surprising. If you call `std::signal(SIGINT, SignalHandler)` inside a function, the setting still takes effect after execution leaves the function, right?

File: python/ray/dag/compiled_dag_node.py [hunk 9]
```diff
@@ -1908,7 +1908,7 @@ def teardown(self, kill_actors: bool = False):
                     _destroy_nccl_group(nccl_group_id)
 
                 logger.info("Waiting for worker tasks to exit")
-                self.wait_teardown()
+                self.wait_teardown(kill_actors=kill_actors)
```
Comment (ruisearch42) [inline python/ray/dag/compiled_dag_node.py:1911]: Do you really need to kill the actors? When the driver exits, won't it clean up ray resources?

Comment (dayshah) [reply python/ray/dag/compiled_dag_node.py:1911]: ray's shutdown calls 
https://github.com/ray-project/ray/blob/cdaeaaef672a49568eed515f097cc068958a648b/python/ray/dag/compiled_dag_node.py#L90-L95

We just never passed the kill_actors all the way through to wait_teardown before. It can hang otherwise here on shutdown if we have tasks that don't end

File: src/ray/core_worker/experimental_mutable_object_manager.cc (hunk 4 above)
Comment (dayshah) [reply src/ray/core_worker/experimental_mutable_object_manager.cc:324]: https://github.com/ray-project/ray/blob/cdaeaaef672a49568eed515f097cc068958a648b/src/ray/core_worker/store_provider/memory_store/memory_store.cc#L355-L363

from here

Comment (ruisearch42) [reply src/ray/core_worker/experimental_mutable_object_manager.cc:324]: I think we should try to use the same mechanism `check_signals_`, we can discuss more offline.

Comment (dayshah) [reply src/ray/core_worker/experimental_mutable_object_manager.cc]: using check_signals now

File: python/ray/dag/tests/experimental/test_accelerated_dag.py [hunk 10]
```diff
@@ -2646,6 +2652,42 @@ def g(self, x, y, z=1):
...
+
+ray.init()
+
+@ray.remote
+class Actor:
+    def sleep(self, x):
+        while(True):
+            time.sleep(x)
+    def get(self, x):
+        return x
```
Comment (ruisearch42) [inline python/ray/dag/tests/experimental/test_accelerated_dag.py:2670]: not needed?

File: python/ray/dag/tests/experimental/test_accelerated_dag.py [hunk 11]
```diff
@@ -2646,6 +2652,42 @@ def g(self, x, y, z=1):
...
+
+a = Actor.remote()
+with InputNode() as inp:
+    dag = a.sleep.bind(inp)
+    dag = a.get.bind(dag)
```
Comment (ruisearch42) [inline python/ray/dag/tests/experimental/test_accelerated_dag.py:2675]: not needed?

File: python/ray/dag/tests/experimental/test_accelerated_dag.py [hunk 12]
```diff
@@ -2646,6 +2652,42 @@ def g(self, x, y, z=1):
...
+"""
+    driver_proc = run_string_as_driver_nonblocking(driver_script)
+    pid = driver_proc.pid
+    # wait for graph execution to start
+    time.sleep(5)
+    proc = psutil.Process(pid)
+    assert proc.status() == psutil.STATUS_RUNNING
+    os.kill(pid, signal.SIGINT)  # ctrl+c
+    # teardown will kill actors after standard 30 second timeout
+    wait_for_pid_to_exit(pid, 40)
```
[the remark this answers is not in the document]
Comment (ruisearch42) [reply python/ray/dag/tests/experimental/test_accelerated_dag.py:2688]: Wondering if the timing is robust in CI environment. Does ctrl+C work in the Ci environment without this script/setup? You can use the sleep technique described in go/reproci to further narrow down the problem.

**Comment by ruisearch42** [comment]
Please also run `microbenchmark_unstable` release test to check perf

**Comment by dayshah** [comment]
> Please also run `microbenchmark_unstable` release test to check perf

```
[unstable]_local_put_local_get,_single_channel_calls = [79117.44950970734, 296.3149947942985]
--
  | [unstable]_local_put_1_remote_get,_single_channel_calls = [123748.59291310453, 1616.0280269184302]
  | [unstable]_local_put_n_remote_get,_single_channel_calls = [2684.6686969003363, 53.415384095545946]
  | [unstable]_local_put_1_remote_get,_n_channels_calls = [4893.430052062124, 79.46254051382995]
  | [unstable]_local_put_n_remote_get,_n_channels_calls = [2484.55696356952, 4.106826998056388]
  | [unstable]_single_actor_DAG_calls = [1000.0535293808977, 16.632348956336365]
  | [unstable]_compiled_single_actor_DAG_calls = [17660.25529912193, 33.2124535980476]
  | [unstable]_compiled_single_actor_asyncio_DAG_calls = [3335.88452895861, 29.531000266145963]
  | [unstable]_scatter_gather_DAG_calls,_n=32_actors = [75.88061300553986, 1.6644548876123173]
  | [unstable]_compiled_scatter_gather_DAG_calls,_n=32_actors = [1427.4715393750353, 41.352562138935184]
  | [unstable]_compiled_scatter_gather_asyncio_DAG_calls,_n=32_actors = [475.16571196068605, 34.933724280955005]
  | [unstable]_chain_DAG_calls,_n=32_actors = [32.20141060992636, 1.7601247637243407]
  | [unstable]_compiled_chain_DAG_calls,_n=32_actors = [756.0415381065413, 7.992062876579606]
  | [unstable]_compiled_chain_asyncio_DAG_calls,_n=32_actors = [511.82025609808807, 14.241533715574334]
  | [unstable]_multiple_args_with_small_payloads_DAG_calls,_n=8_actors = [150.73808044666256, 10.444789495631209]
  | [unstable]_compiled_multiple_args_with_small_payloads_DAG_calls,_n=8_actors = [4130.734653789592, 40.497591992518466]
  | [unstable]_multiple_args_with_medium_payloads_DAG_calls,_n=8_actors = [35.27314807128102, 1.3718701691738233]
  | [unstable]_compiled_multiple_args_with_medium_payloads_DAG_calls,_n=8_actors = [320.4288845327088, 7.376453682908929]
  | [unstable]_multiple_args_with_large_payloads_DAG_calls,_n=8_actors = [1.3427383998801123, 0.04421374325563888]
  | [unstable]_compiled_multiple_args_with_large_payloads_DAG_calls,_n=8_actors = [9.261433238857695, 0.26816239230080885]
  | [unstable]_single_actor_with_all_args_with_small_payloads_DAG_calls,_n=1_actors = [5342.001021107195, 29.071862479081773]
```
checked some there doesn't seem to be a regression

File: python/ray/dag/tests/experimental/test_accelerated_dag.py (hunk 12 above)
[the remark this answers is not in the document]
Comment (dayshah) [reply python/ray/dag/tests/experimental/test_accelerated_dag.py:2685]: passing now

File: python/ray/dag/tests/experimental/test_accelerated_dag.py [hunk 13]
```diff
@@ -2646,6 +2652,39 @@ def g(self, x, y, z=1):
             _ = worker.g.bind(inp)
 
 
+@pytest.mark.skipif(sys.platform == "win32", reason="Sigint not supported on Windows")
```
Comment (kevin85421) [inline python/ray/dag/tests/experimental/test_accelerated_dag.py:2655]: how long will this test take?

**Review by kevin85421 — APPROVED** [review]

File: python/ray/dag/tests/experimental/test_accelerated_dag.py (hunk 13 above)
Comment (dayshah) [reply python/ray/dag/tests/experimental/test_accelerated_dag.py:2655]: updated using teardown timeout env variable, so it'll take ~10 seconds now
