### PR TITLE
[Core] Guarantee the ordering of put ActorTaskSpecTable and ActorTable

### LINKED ISSUE #35622: [Core] [2023-05-20 05:18:33,131 C 151 151] (gcs_server) gcs_actor_manager.cc:1271:  Check failed: iter != actor_task_specs.end()
### What happened + What you expected to happen

[2023-05-20 05:18:33,131 C 151 151] (gcs_server) gcs_actor_manager.cc:1271:  Check failed: iter != actor_task_specs.end() 

### Versions / Dependencies

2.4.0

### Reproduction script

https://console.anyscale.com/o/anyscale-internal/services/service2_ft2lspe385g81ptalr2nqk161i

### Issue Severity

None

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
In order to guarantee that we put ActorTaskSpecTable before ActorTable, we should put ActorTable inside the ActorTaskSpecTable put callback. Otherwise, Redis may receive ActorTable put before ActorTaskSpecTable put. If we crash in the middle, we may end up with actor data inside ActorTable but not ActorTaskSpecTable.

## Related issue number

Closes #35622
## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -591,38 +591,41 @@ Status GcsActorManager::RegisterActor(const ray::rpc::RegisterActorRequest &requ
...
-        // actor_to_register_callbacks_.
-        // Reply to the owner to indicate that the actor has been registered.
-        auto iter = actor_to_register_callbacks_.find(actor->GetActorID());
-        RAY_CHECK(iter != actor_to_register_callbacks_.end() && !iter->second.empty());
-        auto callbacks = std::move(iter->second);
-        actor_to_register_callbacks_.erase(iter);
-        for (auto &callback : callbacks) {
-          callback(actor);
-        }
+      actor_id, request.task_spec(), [](const Status &status) {
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:594]: Can you write an unit tests? I believe we can simulate this from gcs_actor_manager_test.

**Review by rkooo567 — APPROVED** [review]

**Review by fishbone — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:594]: It's actually hard to write the unit test since we need a crash in order to simulate this. I'll merge this now to unblock the  release.
