### PR TITLE
[Fix][Dashboard] Fix Place Group Table table cells overflow

### LINKED ISSUE #47315: [Dashboard] Placement group table reserved resources text clipped
### What happened + What you expected to happen

Screenshot from 2024-08-24 11-49-54

In the screenshot above, the text in the red circle are clipped.

### Versions / Dependencies

2.34.0

### Reproduction script

Follow the steps in this doc

https://docs.ray.io/en/releases-2.34.0/cluster/kubernetes/examples/mnist-training-example.html

### Issue Severity

None

### PR DESCRIPTION
**Pull request by MortalHappiness**
## Why are these changes needed?

See the description in the corresponding issue for details.

In this PR, the ID will never be cut, and the bundles will display differently according to the array length.

Before:

image

After:

- length is 0 (show `-`)

image

- length is 1 (show directly)

image

- length >= 2 (click to expand)

image
image

## Related issue number

Closes: ray-project/ray#47315

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [x] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by MortalHappiness** [comment]
@kevin85421 PTAL

**Comment by kevin85421** [comment]
@alanwguo would you mind taking a look? Thanks!

File: python/ray/dashboard/client/src/common/RowStyles.tsx [hunk 1]
```diff
@@ -1,9 +1,7 @@
 const rowStyles = {
   idCol: {
     display: "block",
-    width: "50px",
-    overflow: "hidden",
-    textOverflow: "ellipsis",
+    width: "100%",
     whiteSpace: "nowrap",
```
Comment (alanwguo) [inline python/ray/dashboard/client/src/common/RowStyles.tsx:5]: this rowStyles is it used by multiple tables? Have you verified if other tables don't break their layout due to this change?

**Review by alanwguo — COMMENTED** [review]
Thanks for the fix. The approach looks good.

@scottsun94 , can you review the UX design?

**Comment by scottsun94** [comment]
Thanks for the PR! RE the design, can we make it a bit simpler?
1. first, we shouldn't truncate the text when it doesn't even fully use the cell's width
2. when it gets too long, can we just truncate it and add an arrow to expand it? The design in the PR seems to take a lot of space and requires the user to click first to see anything?
Screenshot 2024-09-04 at 2 53 09 PM

File: python/ray/dashboard/client/src/common/RowStyles.tsx (hunk 1 above)
Comment (MortalHappiness) [reply python/ray/dashboard/client/src/common/RowStyles.tsx:5]: This style is used in 
image

And this can fix them all.

Before:
image
image
image

After:

image
image
image

**Comment by MortalHappiness** [comment]
@scottsun94 I've updated the design. See the following video for details.

https://github.com/user-attachments/assets/40d58ae5-9269-4ddc-96be-82d972d30b93

**Comment by scottsun94** [comment]
@MortalHappiness Cool. LGTM. Thanks!

**Comment by kevin85421** [comment]
cc @alanwguo does the code change look good to you?

**Review by alanwguo — APPROVED** [review]
thanks, lgtm!
