### PR TITLE
[core] Move reconnection to RPC layer for GCS client.

### LINKED ISSUE #24499: [core] Better support of gRPC channel reconnection
The reconnection right now happens in application layer:

- Health check is in the application layer by starting a new channel.
- Monitor the GCS address change and do resubscribe.
- Always retry the failed request and do reconnection in case of a failure.

However, there are several issues with this approach:

- We need service to discover for GCS address change.
- Monitor is too heavy since it always creates a channel.
- Reconnection is a blocking call that prevents the code from running.

The plan is to move the reconnection from application layer to gRPC layer:

- DNS name resolution is done by gRPC so we don't need to write this.
- Health check is done by checking the channel state.
- Queue the failed call and retry once GCS is up so that it's not a blocking call.

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
This PR support reconnection of the GCS client in gRPC channel layer. Previously this is implemented in the application layer:

- Health check is in the application layer by starting a new channel.
- Monitor the GCS address change and do resubscribe.
- Always retry the failed request and do reconnection in case of a failure.

However, there are several issues with this approach:

- We need service to discover for GCS address change. 
- Monitor is too heavy since it always creates a channel.
- Reconnection is a blocking call that prevents the code from running.

This new approach moves the reconnection to gRPC layer directly to fix these issues.

- DNS name resolution is done by gRPC so we don't need to write this.
- Health check is done by checking the channel state.
- Queue the failed call and retry once GCS is up so that it's not a blocking call.

## Related issue number
Closes: https://github.com/ray-project/ray/issues/24499

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
I'm working on adding a unit test to cover all cases.

Right now, I'm not sure how to cover DNS change part. I've manually tested it in the dev.

**Comment by iycheng** [comment]
Resubscribe will be fixed in the next PR.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 1]
```diff
@@ -137,41 +138,104 @@ class GcsRpcClient {
...
+          auto status = channel_->GetState(true);
+          // https://grpc.github.io/grpc/core/connectivity__state_8h_source.html
+          RAY_LOG(DEBUG) << "GCS channel status: " << status;
+          switch (status) {
+          case GRPC_CHANNEL_TRANSIENT_FAILURE:
+          case GRPC_CHANNEL_CONNECTING:
+            if (!gcs_is_down_) {
+              gcs_is_down_ = true;
+            } else {
+              RAY_CHECK(absl::ToInt64Seconds(absl::Now() - gcs_last_alive_time_) <
```
Comment (scv119) [inline src/ray/rpc/gcs_server/gcs_rpc_client.h:213]: should we make some check to ensure gcs_rpc_server_reconnect_timeout_s always greater than the gcs reconnect retry timeout?

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 2]
```diff
@@ -137,41 +138,104 @@ class GcsRpcClient {
...
+
+    // Setup monitor for gRPC channel status.
+    // TODO(iycheng): Push this into ClientCallManager with CQ by using async call.
+    periodical_runner_->RunFnPeriodically(
+        [this] {
+          if (shutdown_) {
+            return;
+          }
+          auto status = channel_->GetState(true);
+          // https://grpc.github.io/grpc/core/connectivity__state_8h_source.html
```
Comment (scv119) [inline src/ray/rpc/gcs_server/gcs_rpc_client.h:205]: https://grpc.github.io/grpc/core/md_doc_connectivity-semantics-and-api.html has some better description

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 3]
```diff
@@ -427,6 +507,14 @@ class GcsRpcClient {
...
   std::unique_ptr<GrpcClient<InternalKVGcsService>> internal_kv_grpc_client_;
   std::unique_ptr<GrpcClient<InternalPubSubGcsService>> internal_pubsub_grpc_client_;
+
+  std::shared_ptr<grpc::Channel> channel_;
+  bool gcs_is_down_ = false;
+  absl::Time gcs_last_alive_time_ = absl::Now();
+
+  bool shutdown_ = false;
+  std::unique_ptr<PeriodicalRunner> periodical_runner_;
+  std::vector<Executor *> queued_executors_;
```
Comment (scv119) [inline src/ray/rpc/gcs_server/gcs_rpc_client.h:517]: would `pending_requests_` be a better name?

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 4]
```diff
@@ -97,8 +97,9 @@ class Executor {
                 : Status(StatusCode(reply.status().code()), reply.status().message()); \
         callback(status, reply);                                                       \
         delete executor;                                                               \
+      } else if (gcs_is_down_) {                                                       \
+        queued_executors_.emplace_back(executor);                                      \
```
Comment (scv119) [inline src/ray/rpc/gcs_server/gcs_rpc_client.h:101]: should be bound the `queued_executors_` so it doesn't oom?

**Review by scv119 — COMMENTED** [review]
Thanks for clean it up! Mostly just nits.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h (hunk 4 above)
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:101]: I had the same concern here. Then I was thinking about two options:

1. fail the request when it reaches the limit: it might crash raylet as well.
2. retry it immediately, it might OOM as well

Now I think, another way is to block the thread until GCS is back. Let me investigate it.
I'll update the description to include this one.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 5]
```diff
@@ -137,41 +138,104 @@ class GcsRpcClient {
...
+  /// reconnected due to some error.
+  GcsRpcClient(const std::string &address,
+               const int port,
+               ClientCallManager &client_call_manager)
+      : gcs_address_(address),
+        gcs_port_(port),
+        io_context_(&client_call_manager.GetMainService()),
+        periodical_runner_(std::make_unique<PeriodicalRunner>(*io_context_)) {
+    grpc::ChannelArguments arguments;
+    arguments.SetInt(GRPC_ARG_MAX_RECONNECT_BACKOFF_MS,
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:151]: One concern from me is that it might affect the setup of other gRPC connections. But it might not be bad.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h (hunk 1 above)
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:213]: I feel it's not necessary here given that channel reconnection is a dynamic thing: 100ms for the initial one and 2s for the maximum one with exponential backoff.

Any concerns here for this?

**Comment by scv119** [comment]
this looks good to me. does anyone depend on the removed `get_server_address_func_` today?

File: python/ray/tests/test_gcs_fault_tolerance.py [hunk 6]
```diff
@@ -214,6 +215,72 @@ def test_gcs_client_reconnect(ray_start_regular_with_external_redis, auto_reconn
         assert gcs_client.internal_kv_get(b"a", None) == b"b"
 
 
+@pytest.mark.parametrize(
+    "ray_start_regular_with_external_redis",
+    [
+        {
+            **generate_system_config_map(
+                num_heartbeats_timeout=20, gcs_rpc_server_reconnect_timeout_s=3600
```
Comment (mwtian) [inline python/ray/tests/test_gcs_fault_tolerance.py:223]: Can we verify these two situations?
1. When GCS went down but the issue is not yet discovered by the periodic check status thread, GCS reconnection still works in this case. (I believe so, via `executor->Retry()`).
2. When GCS went down and there is a background request to GCS (which may be hanging), core worker's main event loop (`ray.get()`?) still works.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 7]
```diff
@@ -97,8 +100,20 @@ class Executor {
...
         delete executor;                                                               \
+      } else if (gcs_is_down_) {                                                       \
+        pending_requests_.emplace_back(executor);                                      \
+        if (pending_requests_.size() >                                                 \
+            ::RayConfig::instance().gcs_grpc_max_request_queued()) {                   \
+          RAY_LOG(WARNING) << "Pending queue for failed GCS request has reached the "  \
+                           << "limit. Blocking the current thread until GCS is back";  \
+          while (gcs_is_down_ && !shutdown_) {                                         \
+            CheckChannelStatus();                                                      \
+            std::this_thread::sleep_for(std::chrono::milliseconds(                     \
```
Comment (mwtian) [inline src/ray/rpc/gcs_server/gcs_rpc_client.h:111]: Is it acceptable to block until GCS is up? How about using a timer or something else and run `CheckChannelStatus()` asynchronously `gcs_client_check_connection_status_interval_milliseconds` later?

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 8]
```diff
@@ -97,8 +100,20 @@ class Executor {
...
+                ::RayConfig::instance()                                                \
+                    .gcs_client_check_connection_status_interval_milliseconds()));     \
+          }                                                                            \
+        }                                                                              \
       } else {                                                                         \
```
Comment (mwtian) [inline src/ray/rpc/gcs_server/gcs_rpc_client.h:116]: Why do we need to handle `gcs_is_down_ = true` vs `false` differently? It seem even when `gcs_is_down_ = false`, GCS can be down in reality but not yet discovered by periodic check status. Retry immediately with `executor->Retry()` should work, but it seems more consistent to handle both situations by checking GCS status then retry if connected. Or I may be missing something.

**Review by mwtian — COMMENTED** [review]
Nice cleanup! Really glad we can make this logic simpler.

File: src/ray/gcs/gcs_client/gcs_client.cc [hunk 9]
```diff
@@ -75,54 +75,17 @@ void GcsSubscriberClient::PubsubCommandBatch(
...
-         i < RayConfig::instance().gcs_service_connect_retries()) {
-    std::this_thread::sleep_for(std::chrono::milliseconds(
-        RayConfig::instance().internal_gcs_service_connect_wait_milliseconds()));
-    get_server_address_func_(&current_gcs_server_address_);
-    i++;
-  }
-
-  resubscribe_func_ = [this]() {
-    job_accessor_->AsyncResubscribe();
-    actor_accessor_->AsyncResubscribe();
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/gcs/gcs_client/gcs_client.cc:109]: My plan is that, when GCS restarts, it'll load data from storage. At that time, it'll ask the node to resubscribe (reuse the resubscribe func here).

One bug here is that there is a race condition: GCS restarts, but raylet somehow fails to catch that and all subscription will be lost.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h (hunk 7 above)
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:111]: I think it's not acceptable, but it's the best we can do for now.

The concern here is that there are too many requests queued when GCS is down. And when this happens we either:
- fail some request 
- blocking until GCS is up so it can clear the queue.

The former one is better, but given that our codebase is not handling this very well and a lot of places assume GCS request is always successful, it'll need more effort. I guess the long-term plan is to make sure gRPC error is handled correctly. Some of this will be handled in GCS HA project, others might need some cleanup or redesign of the protocol.


Actually, we do the check async if the queue is not full.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h (hunk 8 above)
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:116]: It's right. Immediately retry should work.

But the concern here is 1) save CPU since always retry immediately definitely will overload the thread. 2) for memory safety. if GCS is down and there are a lot of requests coming, we'd like to make sure OOM won't happen here. Or at least we'll have some way to control this.

The previous implementation will trigger a blocking reconnection so it's not an issue there.

**Comment by iycheng** [comment]
> this looks good to me. does anyone depend on the removed `get_server_address_func_` today?
> 
> also let's add a C++ unit test to ensure the reconnection is working.

Previously gcs address is written to redis, so we need this. But now, we use DNS for this, it's not necessary anymore.

**Review by rkooo567 — COMMENTED** [review]
Is there any good way to unit test the new RPC client? It seems like we are adding lots of state-based logic which I am a little scared to do production testing.

**Comment by iycheng** [comment]
> Is there any good way to unit test the new RPC client? It seems like we are adding lots of state-based logic which I am a little scared to do production testing. 

That's planned.

File: src/ray/common/ray_config_def.h [hunk 10]
```diff
@@ -332,9 +332,25 @@ RAY_CONFIG(bool, support_fork, false)
...
 
+/// The timeout for GCS connection in seconds
+RAY_CONFIG(int32_t, gcs_rpc_server_connect_timeout_s, 5)
+
 /// Minimum interval between reconnecting gcs rpc server when gcs server restarts.
 RAY_CONFIG(int32_t, minimum_gcs_reconnect_interval_milliseconds, 5000)
 
+/// gRPC channel reconnection related configs to GCS.
+/// Check https://grpc.github.io/grpc/core/group__grpc__arg__keys.html for details
+RAY_CONFIG(int32_t, gcs_grpc_max_reconnect_backoff_ms, 2000)
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/common/ray_config_def.h:343]: No. I just pick a one I feel good about. 2s maximum backoff seems fair here.

File: src/ray/common/ray_config_def.h [hunk 11]
```diff
@@ -332,9 +332,25 @@ RAY_CONFIG(bool, support_fork, false)
...
+RAY_CONFIG(int32_t, gcs_grpc_min_reconnect_backoff_ms, 100)
+RAY_CONFIG(int32_t, gcs_grpc_initial_reconnect_backoff_ms, 100)
+
+/// Maximum number of request queued when RPC failed due to GCS is down.
+/// If reach the limit, the core worker will hang until GCS is reconnected.
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/common/ray_config_def.h:348]: Yes

File: python/ray/tests/test_gcs_fault_tolerance.py [hunk 12]
```diff
@@ -214,6 +215,72 @@ def test_gcs_client_reconnect(ray_start_regular_with_external_redis, auto_reconn
...
+
+    c = Counter.options(lifetime="detached", name="C").remote()
+
+    assert ray.get(c.r.remote(10)) == 10
+
+    ray.worker._global_node.kill_gcs_server()
+
+    sleep(2)
+
+    assert ray.get(c.r.remote(10)) == 10
```
Comment (iycheng) [inline python/ray/tests/test_gcs_fault_tolerance.py:268]: > Can you add a test if GCS fails and "not recovered" (which is the common path for non HA), APIs will fail properly and things won't be hanging?


@rkooo567 it's been covered here.

Comment (iycheng) [reply python/ray/tests/test_gcs_fault_tolerance.py:268]: To be honest, it's not covering everything e2e because we also have other issues.

The main goal of this PR is to make sure the channel is reconnected and cpp test should cover this one.

The e2e ci test here is to cover the case where function is broken because of reconnection is not working properly.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h (hunk 8 above)
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:116]: Good point here. I think I'll change the behavior to:

- if rpc failed, I'll check channel connection first
- and if gcs is not down, I'll retry this.
- otherwise queue this

File: src/ray/gcs/gcs_client/gcs_client.h [hunk 13]
```diff
@@ -69,11 +69,9 @@ class RAY_EXPORT GcsClient : public std::enable_shared_from_this<GcsClient> {
   ///
   /// \param options Options for client.
   /// \param get_gcs_server_address_func Function to get GCS server address.
-  explicit GcsClient(const GcsClientOptions &options,
-                     std::function<bool(std::pair<std::string, int> *)>
-                         get_gcs_server_address_func = nullptr);
+  explicit GcsClient(const GcsClientOptions &options);
 
-  virtual ~GcsClient() = default;
+  virtual ~GcsClient() { Disconnect(); };
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/gcs/gcs_client/gcs_client.h:74]: The disconnect is to stop the io thread.

Disconnect is to give the user a way to stop the client and later do connection. I feel if this is like you said, it should be some issues related to something higher layer. Not sure whether the function is needed, but when we delete the GCS client, we need to stop something in io context and this is to avoid race condition.

Even if there is no io context issues here and I don't do disconnect here, the ordering of destruction depends on the order it's declared. So disconnect shouldn't be the root cause of the issue you mentioned. 

The root cause is that we have complicated dependence on core worker which makes everything complicated.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 14]
```diff
@@ -97,8 +100,20 @@ class Executor {
...
+        pending_requests_.emplace_back(executor);                                      \
+        if (pending_requests_.size() >                                                 \
+            ::RayConfig::instance().gcs_grpc_max_request_queued()) {                   \
+          RAY_LOG(WARNING) << "Pending queue for failed GCS request has reached the "  \
+                           << "limit. Blocking the current thread until GCS is back";  \
+          while (gcs_is_down_ && !shutdown_) {                                         \
+            CheckChannelStatus();                                                      \
+            std::this_thread::sleep_for(std::chrono::milliseconds(                     \
+                ::RayConfig::instance()                                                \
+                    .gcs_client_check_connection_status_interval_milliseconds()));     \
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:113]: If GCS is not recovered, we'll fail the cluster eventually, and how to make sure the ray cluster can still operate without GCS should be an orthogonal issue that won't be covered in this PR.

But just for some discussion here, the problem right now is that in our code, we are not handling the issue when GCS crashed and never goes back. I believe this is a wrong design choice but hard to fix given the current case.

Ideally, for every RPC request, we should consider the possibility that the request might fail and do retry and rollback.

I guess, for the long-term plan, once we revisit the protocol between GCS <-> Raylet, we should get a better picture about this and eventually, we never assume rpc always succeed.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 15]
```diff
@@ -97,8 +100,20 @@ class Executor {
...
+          }                                                                            \
+        }                                                                              \
       } else {                                                                         \
-        gcs_service_failure_detected_(GcsServiceFailureType::RPC_DISCONNECT);          \
         executor->Retry();                                                             \
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:117]: For timeout, I think it's orthogonal to this issue and this one only fixes the reconnection issue and it's not handled by the current codebase as well.

> Also, do you think it is a good idea to add some grace period instead of immediately retrying here?

I think it's necessary. Internally in grpc there is retry logic (https://github.com/grpc/proposal/blob/master/A6-client-retries.md#retryable-status-codes) which we can use.

But for this one, at most, it'll cover 5 retries and the application layer should handle the timeout failure.

I think for the short term, we can just use that feature, but for long-term, we need to handle gRPC failure properly in application layer. In case of any kind of failure, application layer should be able to take care of them instead of letting the gRPC handling the logic like here (queueing and retrying).

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 16]
```diff
@@ -137,41 +152,60 @@ class GcsRpcClient {
...
+                     << " within "
+                     << ::RayConfig::instance().gcs_rpc_server_connect_timeout_s()
+                     << " seconds.";
+      gcs_is_down_ = true;
+    } else {
+      gcs_is_down_ = false;
+    }
+
     job_info_grpc_client_ =
-        std::make_unique<GrpcClient<JobInfoGcsService>>(channel, client_call_manager);
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:154]: I don't think so and it's a recommended behavior (https://grpc.io/docs/guides/performance/)

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 17]
```diff
@@ -412,8 +446,61 @@ class GcsRpcClient {
...
+                  ::RayConfig::instance().gcs_rpc_server_reconnect_timeout_s())
+            << "Failed to connect to GCS within "
+            << ::RayConfig::instance().gcs_rpc_server_reconnect_timeout_s() << " seconds";
+      }
+      break;
+    case GRPC_CHANNEL_SHUTDOWN:
+      RAY_CHECK(shutdown_) << "Channel shoud never go to this status.";
+      break;
+    case GRPC_CHANNEL_READY:
+    case GRPC_CHANNEL_IDLE:
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:487]: That's also what I thought, but I remember I do it in this way because somehow, it reaches this state.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 18]
```diff
@@ -412,8 +446,61 @@ class GcsRpcClient {
...
+    return std::make_pair(gcs_address_, gcs_port_);
+  }
+
  private:
-  std::function<void(GcsServiceFailureType)> gcs_service_failure_detected_;
+  void CheckChannelStatus() {
+    if (shutdown_) {
+      return;
+    }
+    auto status = channel_->GetState(/* try_to_connect = */ true);
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:467]: Good point. Initially, I added this to make sure errors can be caught as early as possible. I'll remove try to connect.

File: src/ray/rpc/gcs_server/gcs_rpc_client.h [hunk 19]
```diff
@@ -412,8 +446,61 @@ class GcsRpcClient {
...
+    case GRPC_CHANNEL_SHUTDOWN:
+      RAY_CHECK(shutdown_) << "Channel shoud never go to this status.";
+      break;
+    case GRPC_CHANNEL_READY:
+    case GRPC_CHANNEL_IDLE:
+      gcs_last_alive_time_ = absl::Now();
+      gcs_is_down_ = false;
+      // Retry the one queued.
+      while (!pending_requests_.empty()) {
+        pending_requests_.back()->Retry();
```
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:492]: Good point about this one! My consideration here is that if GCS is back, we probably will like to spend some time recovering from the previous failure. Besides, even if we post here, eventually, these requests still will run and block the thread (there is no priority in asio right now). So I'd keep this logic here.

**Comment by iycheng** [comment]
@rkooo567 thanks for the review and thoughts here. I think the concerns you mentioned are valid and are something broken in the gRPC used in ray. But for this PR it's purely focusing on channel reconnection. I'll update the PR to make sure it's not worse than before. Please refer to the comments for details.

**Comment by iycheng** [comment]
I double-checked the code and the error handling part is purely for grpc error. I thnk I'll change the behavior here to queue the request immediately instead of check gcs is down flag.

**Comment by rkooo567** [comment]
Talked to @iycheng offline, and we agree with this policy! 

```
If the buffer queue still have space, it’ll not block and crash
If the buffer queue is full, it’ll block
If GCS is down for more than defined time, the ray cluster should fail (crash)
```
This should satisfies all comments I said

File: src/ray/rpc/gcs_server/gcs_rpc_client.h (hunk 17 above)
[the remark this answers is not in the document]
Comment (iycheng) [reply src/ray/rpc/gcs_server/gcs_rpc_client.h:489]: I remove try_to_connect=true. Close this comment.

File: python/ray/tests/test_gcs_fault_tolerance.py (hunk 6 above)
Comment (iycheng) [reply python/ray/tests/test_gcs_fault_tolerance.py:223]: > When GCS went down but the issue is not yet discovered by the periodic check status thread, GCS reconnection still works in this case. (I believe so, via executor->Retry()).

I updated the code. Here if there is a request going on and it errored because of grpc it'll set the status to down.  So it won't go with Retry, but queued directly.

File: python/ray/tests/test_gcs_fault_tolerance.py [hunk 20]
```diff
@@ -214,6 +215,71 @@ def test_gcs_client_reconnect(ray_start_regular_with_external_redis, auto_reconn
...
+
+    print("GCS is killed")
+    ray.worker._global_node.kill_gcs_server()
+
+    print("Start to create a new actor")
+    cc = Counter.remote()
+    with pytest.raises(ray.exceptions.GetTimeoutError):
+        ray.get(cc.r.remote(10), timeout=5)
+
+    assert ray.get(c.r.remote(10)) == 10
```
Comment (iycheng) [inline python/ray/tests/test_gcs_fault_tolerance.py:253]: > When GCS went down and there is a background request to GCS (which may be hanging), core worker's main event loop (ray.get()?) still works.

@mwtian  I covered it here.

**Comment by iycheng** [comment]
@scv119 @mwtian @rkooo567  ready for another round of review.

**Comment by sriram-anyscale** [comment]
I'll take a look over the weekend.

File: python/ray/tests/test_gcs_fault_tolerance.py (hunk 20 above)
Comment (mwtian) [reply python/ray/tests/test_gcs_fault_tolerance.py:253]: I mean can we call `ray.get(cc.r.remote(10))` on a separate thread without timeout? Just to make sure concurrent calls are working, even when another call is hanging..

**Comment by mwtian** [comment]
> I double-checked the code and the error handling part is purely for grpc error. I thnk I'll change the behavior here to queue the request immediately instead of check gcs is down flag.

This sounds good.

**Comment by scv119** [comment]
@WangTaoTheTonic FYI on the GCS related changes.

File: src/ray/common/ray_config_def.h [hunk 21]
```diff
@@ -332,9 +332,25 @@ RAY_CONFIG(bool, support_fork, false)
...
+RAY_CONFIG(uint64_t, gcs_grpc_max_request_queued, 1000000)
```
Comment (scv119) [inline src/ray/common/ray_config_def.h:349]: need to see if this will cause OOM

**Review by scv119 — APPROVED** [review]

**Comment by scv119** [comment]
also some tests look failure related.

**Comment by iycheng** [comment]
```
 ray.exceptions.RayActorError: The actor died unexpectedly before finishing this task.
  | (TrainTrainable pid=29396) 	class_name: BackendExecutor
  | (TrainTrainable pid=29396) 	actor_id: dbc88abfe87ab1a9e2243c3401000000
  | (TrainTrainable pid=29396) 	namespace: 045f1fe5-386c-474b-b54f-c778e44e1934
  | (TrainTrainable pid=29396) The actor is dead because because all references to the actor were removed.

```

Hmmm, test failed... very wired...

**Comment by iycheng** [comment]
Ok, this one https://github.com/ray-project/ray/pull/24330/commits/99f624416c3efb6babde981d3d06a9f9d19a5d8b fixed the test failure (GPU train). I think there is a race condition here which got triggered with backoff setup.

I'll first finish this PR and then double-check it. If it's true, I'll create an issue to track it.
