### PR TITLE
Fix memory leak in lineage cache

### LINKED ISSUE #3360: Lineage cache doesn't clean up a local data structure
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: all
- **Ray installed from (source or binary)**: source
- **Ray version**: master
- **Python version**: all

### Describe the problem
The lineage cache keeps track of "parents" of each task in the lineage, or the tasks that each task in the lineage depends on, so that it can keep track of which tasks can be evicted safely. This is done in `children_`, which is currently not cleaned up properly. When a task is [added](https://github.com/ray-project/ray/blob/master/src/ray/raylet/lineage_cache.cc#L166), different entries get added than when the task is [removed](https://github.com/ray-project/ray/blob/master/src/ray/raylet/lineage_cache.cc#L385). This results in an ever-increasing `children_` map for workloads on a cluster.

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

The lineage cache has to keep track of dependencies between tasks in the cache, but this map was not getting cleaned up before. This refactors the lineage cache to make sure that the dependencies are cleaned up properly when tasks are removed from the lineage cache.

## Related issue number

Closes #3360.

### CODE REVIEW

**Comment by richardliaw** [comment]
Is there a corresponding test to check this?

File: src/ray/raylet/lineage_cache.cc [hunk 1]
```diff
@@ -92,27 +92,49 @@ boost::optional<LineageEntry &> Lineage::GetEntryMutable(const TaskID &task_id)
...
-  if (current_entry) {
-    if (current_entry->SetStatus(status)) {
+  auto it = entries_.find(task_id);
+  bool updated = false;
+  if (it != entries_.end()) {
+    if (it->second.SetStatus(status)) {
+      // The task's spec may have changed, so remove its old dependencies.
+      // TODO(swang): This could be inefficient for tasks that have lots of
+      // dependencies and/or large specs. A flag could be passed in for tasks
+      // wohse data has not changed.
```
Comment (ericl) [inline src/ray/raylet/lineage_cache.cc]: whose

File: src/ray/raylet/lineage_cache.cc [hunk 2]
```diff
@@ -92,27 +92,49 @@ boost::optional<LineageEntry &> Lineage::GetEntryMutable(const TaskID &task_id)
...
-  auto current_entry = GetEntryMutable(task_id);
-  if (current_entry) {
-    if (current_entry->SetStatus(status)) {
+  auto it = entries_.find(task_id);
+  bool updated = false;
+  if (it != entries_.end()) {
+    if (it->second.SetStatus(status)) {
+      // The task's spec may have changed, so remove its old dependencies.
+      // TODO(swang): This could be inefficient for tasks that have lots of
+      // dependencies and/or large specs. A flag could be passed in for tasks
```
Comment (robertnishihara) [inline src/ray/raylet/lineage_cache.cc]: Why is it an issue if the task spec is large?

Comment (stephanie-wang) [reply src/ray/raylet/lineage_cache.cc]: Just that you have to copy the task spec over when updating the task entry. Updating the dependencies is probably going to be worse in most cases. I made this slightly better in the last commit.

**Comment by stephanie-wang** [comment]
@richardliaw, I added some statements to the unit tests, which uncovered a bug in the PR :)

File: src/ray/raylet/lineage_cache_test.cc [hunk 3]
```diff
@@ -558,16 +565,34 @@ TEST_F(LineageCacheTest, TestEvictionUncommittedChildren) {
...
-  auto it = tasks.rbegin();
-  RAY_CHECK_OK(mock_gcs_.RemoteAdd(it->GetTaskSpecification().TaskId(), task_data));
-  // We expect the task that was added remotely to be flushed.
-  num_tasks_flushed++;
-  // Check that once the last task in the forwarded chain is flushed, all local
-  // tasks are flushed, since all of their dependencies have been evicted and
-  // are therefore committed in the GCS.
-  mock_gcs_.Flush();
-  ASSERT_EQ(mock_gcs_.TaskTable().size(), num_tasks_flushed);
+  // auto task_data = std::make_shared<protocol::TaskT>();
```
Comment (richardliaw) [inline src/ray/raylet/lineage_cache_test.cc]: hey are you planning to keep this here?

File: src/ray/raylet/lineage_cache.cc [hunk 4]
```diff
@@ -438,7 +458,7 @@ bool LineageCache::ContainsTask(const TaskID &task_id) const {
   return it != entries.end();
 }
 
-size_t LineageCache::NumEntries() const { return lineage_.GetEntries().size(); }
```
Comment (richardliaw) [inline src/ray/raylet/lineage_cache.cc]: why not keep this?

Comment (richardliaw) [reply src/ray/raylet/lineage_cache.cc]: (or give a method to `Lineage` that provides size?)

File: src/ray/raylet/lineage_cache_test.cc (hunk 3 above)
Comment (stephanie-wang) [reply src/ray/raylet/lineage_cache_test.cc]: Oops thanks, removed.

File: src/ray/raylet/lineage_cache.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/raylet/lineage_cache.cc]: I added the `GetLineage()` method, and you can get the size using `Lineage::GetEntries().size()`.

**Review by richardliaw — APPROVED** [review]

**Comment by stephanie-wang** [comment]
I believe the test failures are from previous commits.
