### PR TITLE
[core] Avoid ObjectID collisions for re-executed tasks

### LINKED ISSUE #20713: [Bug][core] Task re-execution doesn't work if the owner of a created object has changed
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Core

### What happened + What you expected to happen

A task can fail at any time, leaving a partial state if it creates some objects before it fails. #20447 addresses the problem by having a re-executed task pin the created object if a copy already exists. But this itself can be problematic if the previous copy of the object is inconsistent with the re-executed task.

This also doesn't work in cases where the object ID stays the same, but the owner address changes, which can happen with nested tasks. For example:
1. Worker W1 executing task A calls `ray.put` on object X. W1 is then the owner of X.
2. X gets copied to somewhere else in the cluster.
3. W crashes.
4. A's owner resubmits A. If it executes on W2, then it will call `X = ray.put()` again, but this time W2 will be the owner of X.

There's a couple problems with this scenario: (1) we could have different versions of X if A is nondeterministic, (2) the owner is responsible for keeping metadata (e.g., ref counts) about the object, but the new owner will not have all the metadata that the previous owner held.

### Versions / Dependencies

2.0dev

### Reproduction script

```python
import os
import signal
import sys
import time

import numpy as np
import pytest

import ray
from ray._private.test_utils import (
    wait_for_condition,
    wait_for_pid_to_exit,
    SignalActor,
)

SIGKILL = signal.SIGKILL if sys.platform != "win32" else signal.SIGTERM

@pytest.mark.parametrize("reconstruction_enabled", [false, true])
def test_nested(ray_start_cluster, reconstruction_enabled):
    config = {
        "num_heartbeats_timeout": 10,
        "raylet_heartbeat_period_milliseconds": 100,
        "object_timeout_milliseconds": 200,
        "fetch_fail_timeout_milliseconds": 10_000,
    }
    # workaround to reset the config to the default value.
    if not reconstruction_enabled:
        config["lineage_pinning_enabled"] = false

    cluster = ray_start_cluster
    # head node with no resources.
    cluster.add_node(
        num_cpus=0,
        _system_config=config,
        enable_object_reconstruction=reconstruction_enabled)
    ray.init(address=cluster.address)
    done_signal = signalactor.remote()
    exit_signal = signalactor.remote()
    ray.get(done_signal.wait.remote(should_wait=false))
    ray.get(exit_signal.wait.remote(should_wait=false))

    # Node to place the initial object.
    node_to_kill = cluster.add_node(num_cpus=1, object_store_memory=10**8)
    cluster.wait_for_nodes()

    @ray.remote
    def dependent_task(x):
        return

    @ray.remote
    def large_object():
        return np.zeros(10**7, dtype=np.uint8)

    @ray.remote
    def nested(done_signal, exit_signal):
        ref = ray.put(np.zeros(10**7, dtype=np.uint8))
        # Flush object store.
        for _ in range(20):
            ray.put(np.zeros(10**7, dtype=np.uint8))
        dep = dependent_task.options(resources={"node": 1}).remote(ref)
        ray.get(done_signal.send.remote(clear=True))
        ray.get(dep)
        return ray.get(ref)

    ref = nested.remote(done_signal, exit_signal)
    # Wait for task to get scheduled on the node to kill.
    ray.get(done_signal.wait.remote())
    # Wait for ray.put object to get transferred to the other node.
    cluster.add_node(
        num_cpus=2, resources={"node": 10}, object_store_memory=10**8)
    ray.get(dependent_task.remote(ref))

    # Destroy the task's output.
    cluster.remove_node(node_to_kill, allow_graceful=False)
    wait_for_condition(
        lambda: not all(node["Alive"] for node in ray.nodes()), timeout=10)

    if reconstruction_enabled:
        # NOTE(swang): This is supposed to work because nested doesn't actually
        # return any ObjectRefs. However, currently the ray.put in `nested`
        # fails because the object already exists with a different owner.
        try:
            ray.get(ref, timeout=60)
        except ray.exceptions.RayTaskError as e:
            assert isinstance(e.cause, ray.exceptions.ObjectFetchTimedOutError)
    else:
        with pytest.raises(ray.exceptions.ObjectLostError):
            ray.get(ref, timeout=60)


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main(["-v", __file__]))

```

### Anything else

Ideally, we should treat the second version of X as a completely different object X2. That way, we can avoid any inconsistencies (e.g., ref holders for X do not count as ref holders for X2). I think the simplest way to do this for now is to make task/put IDs nondeterministic. This might make reconstruction for ray.put() refs more complicated, but it will make sure we don't have any issues from partial state after failures.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

If a task is re-executed on failure, it will deterministically generate the same IDs for any ray.put or .remote task calls because it uses its own task ID as a seed. This can cause problems if those objects conflict with previous versions that still exist in the cluster.

This PR adds the execution attempt number to the current task ID seed. This avoids collisions with any ObjectIDs generated by the previous execution attempt of the task.

## Related issue number

Closes #20713.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/context.cc [hunk 1]
```diff
@@ -86,6 +90,10 @@ struct WorkerThreadContext {
   /// The task ID for current task.
   TaskID current_task_id_;
 
+  /// Unique bytes to use for any ObjectIDs generated by the
+  /// current task (via ray.put or .remote calls).
+  TaskID current_task_unique_bytes_;
```
Comment (jjyao) [inline src/ray/core_worker/context.cc:95]: nit: It's a bit weird that it's called unique_bytes but the type is TaskID. What about current_task_internal_id?

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -810,7 +810,7 @@ void CoreWorker::RegisterOwnershipInfoAndResolveFuture(
 Status CoreWorker::Put(const RayObject &object,
                        const std::vector<ObjectID> &contained_object_ids,
                        ObjectID *object_id) {
-  *object_id = ObjectID::FromIndex(worker_context_.GetCurrentTaskID(),
+  *object_id = ObjectID::FromIndex(worker_context_.GetCurrentTaskUniqueBytes(),
```
Comment (jjyao) [inline src/ray/core_worker/core_worker.cc:813]: A random thought: what if we change the index to contain the run number of this task. This way each re-run of the same task generates deterministic but yet unique IDs. E.g. `ObjectID::FromIndex(GetCurrentTaskID(), GetRunNumber(), GetNextPutIndex())`

Comment (ericl) [reply src/ray/core_worker/core_worker.cc:813]: +1

Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:813]: You mean to include the run number in the hash? That sounds good to me. But I don't think we should include it in the actual ID since we'd have to increase the number of bits too.

File: src/ray/common/id.h [hunk 3]
```diff
@@ -224,6 +224,15 @@ class TaskID : public BaseID<TaskID> {
   static TaskID ForNormalTask(const JobID &job_id, const TaskID &parent_task_id,
                               size_t parent_task_counter);
 
+  /// Given a base task ID, create a task ID that reprents the n-th execution
+  /// of that task. This task ID should be used to seed any TaskIDs or
+  /// ObjectIDs created during that task.
+  /// See https://github.com/ray-project/ray/issues/20713.
+  ///
+  /// \param task_id The task ID generated by the task's parent.
```
Comment (clarkzinzow) [inline src/ray/common/id.h:232]: Add a `\param` line for `execution_counter`.

File: src/ray/protobuf/common.proto [hunk 4]
```diff
@@ -256,6 +256,9 @@ message TaskSpec {
   int64 depth = 26;
   // Strategy about how to schedule this task.
   SchedulingStrategy scheduling_strategy = 27;
+  // A count of the number of times this task has executed so
+  // far. 0 means this is the first execution.
+  int64 execution_counter = 28;
```
Comment (clarkzinzow) [inline src/ray/protobuf/common.proto:261]: Nit: The semantics of this counter weren't obvious to me at first, since I first assumed that this was incremented at submission time ("number of executions, including the current one in progress"), but it actually isn't incremented until an execution run has finished (and failed). Would a better name for this be `num_past_executions` or something like that, so these semantics are more easily conveyed?

I'm also not super sure about this one, `execution_counter` is already a pretty good name for "number of executions that have already happened", so feel free to disregard if you think `execution_counter` is good enough.

File: src/ray/common/id.cc [hunk 5]
```diff
@@ -194,6 +194,14 @@ TaskID TaskID::ForNormalTask(const JobID &job_id, const TaskID &parent_task_id,
   return TaskID::FromBinary(data);
 }
 
+TaskID TaskID::ForExecution(const TaskID &task_id, int64_t execution_counter) {
+  std::string data_str;
+  std::copy_n(task_id.Data(), TaskID::kLength, std::back_inserter(data_str));
+  auto data = reinterpret_cast<uint8_t *>(data_str.data());
+  data[TaskID::kLength - 1] += execution_counter;
```
[the remark this answers is not in the document]
Comment (ericl) [reply src/ray/common/id.cc:201]: How about we reinterpret_cast<uint64_t> instead to avoid this?

Btw, it would be great to initialize the last byte of task_id to zero by default, so that the counter is more readable.

File: src/ray/protobuf/common.proto (hunk 4 above)
Comment (ericl) [inline src/ray/protobuf/common.proto:261]: `num_attempts`?

Comment (stephanie-wang) [reply src/ray/protobuf/common.proto]: Hmm yeah not sure about it either, but I decided to just follow the naming convention we're already using for `parent_task_counter`.

File: src/ray/common/id.cc [hunk 6]
```diff
@@ -194,6 +194,18 @@ TaskID TaskID::ForNormalTask(const JobID &job_id, const TaskID &parent_task_id,
...
 
+TaskID TaskID::ForExecution(const TaskID &task_id, uint64_t execution_counter) {
+  std::string data_str;
+  std::copy_n(task_id.Data(), TaskID::kLength, std::back_inserter(data_str));
+  static_assert(TaskID::kUniqueBytesLength >= 8, "TaskID must have at least 64 bits");
+  auto data = reinterpret_cast<uint64_t *>(data_str.data());
+  // Zero out the low byte for readability.
+  (*reinterpret_cast<uint8_t *>(data)) = 0;
+  // Add execution_counter to the task ID unique bytes.
+  (*data) += execution_counter;
```
Comment (jjyao) [inline src/ray/common/id.cc:205]: Do we need to consider endianness here?

Comment (stephanie-wang) [reply src/ray/common/id.cc:205]: The correctness should be fine because casting to `uint8_t` will truncate the higher-order bits. But the endianness affects which bytes get zero-ed out (on my laptop the first two bytes of the .hex() representation are zeroed).

**Review by ericl — COMMENTED** [review]
Can we rename execution_counter to attempt_number? That's the more common terminology for retried tasks.

File: src/ray/common/id.cc (hunk 6 above)
Comment (jjyao) [reply src/ray/common/id.cc]: I think I'm worried about the ` (*data) += execution_counter;` like are we always adding the counter to the bytes that are zero-ed out.

Comment (stephanie-wang) [reply src/ray/common/id.cc]: I'm not sure if I understand - the intention is to add the counter to the zeroed out bytes.

Comment (jjyao) [reply src/ray/common/id.cc]:
```
#include <stdio.h>
#include <stdint.h>
int main() {
  uint16_t bytes = 1;
  if (*((uint8_t*) &bytes) == 1) {
    printf("Detected Host Little Endian.\n");
  } else {
    printf("Detected Host Big Endian.\n");
  }
  uint8_t data[4];
  int i = 0;
  for (i = 0; i < 4; ++i) {
    data[i] = 1;
  }
  uint32_t *ptr = (uint32_t *)data;
  (*(uint8_t *)(ptr)) = 0;
  (*ptr) += 1;
  for (i = 0; i < 4; ++i) {
    printf("%d\n", data[i]);
  }
}
```

```
root@f2c9044927aa:/# ./a.out 
Detected Host Big Endian.
0
1
1
2
```

```
(ray) jjyao@Jiajuns-MacBook-Pro:~/Workspace/ray1 jjyao/parallelism$ ./a.out 
Detected Host Little Endian.
1
1
1
1
```

Comment (stephanie-wang) [reply src/ray/common/id.cc]: Ah I see ,my bad! I'm just going to change this to use an extra uint8_t field for the counter for simplicity/portability.

File: src/ray/common/id.cc [hunk 7]
```diff
@@ -180,18 +188,36 @@ TaskID TaskID::ForActorTask(const JobID &job_id, const TaskID &parent_task_id,
...
+  std::memcpy(task_id.id_ + TaskID::kUniqueBytesLength, dummy_actor_id.Data(),
+              ActorID::kLength);
+  // Zero out the task attempt number.
+  task_id.id_[TaskID::kUniqueBytesLength + ActorID::kLength] = 0;
+  return task_id;
+}
+
+TaskID TaskID::ForExecutionAttempt(const TaskID &task_id, uint64_t attempt_number) {
+  TaskID task_id_copy = task_id;
+  if (attempt_number >= std::numeric_limits<uint8_t>::max()) {
```
Comment (ericl) [inline src/ray/common/id.cc:213]: Why not use int64_t* and allow it to overflow into the unique bits as before?

Comment (stephanie-wang) [reply src/ray/common/id.cc:213]: It turns out to be tricky because of endianness (see above conversation with @jjyao). If you have an idea of how to do it in a portable/simple way, let me know.

Comment (ericl) [reply src/ray/common/id.cc:213]: Can't we just assume little endian? There's no real architecture that's big endian.

Comment (stephanie-wang) [reply src/ray/common/id.cc:213]: Hmm I think this is a little sketchy... it appears that some architectures default to little endian but do allow you to switch.

I could also just change this back to overflowing into the unique bits and statically detect the endianness. What do you think?

Comment (scv119) [reply src/ray/common/id.cc:213]: If we want to assume little endian, one thing we could do is crash the program if it's not using https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/endian.h

Comment (jjyao) [reply src/ray/common/id.cc:213]: Yea, I think we need to make the assumption explicit.

Comment (stephanie-wang) [reply src/ray/common/id.cc:213]: Thanks for the tip, I'll try that!

File: src/ray/common/id.cc (hunk 6 above)
Comment (jjyao) [reply src/ray/common/id.cc]: Actually just think of a portable way, instead of `(*reinterpret_cast<uint8_t *>(data)) = 0;` we can do `*data & 0xFFFFFF...0`

Comment (stephanie-wang) [reply src/ray/common/id.cc]: Ah good idea, thanks!

File: src/ray/common/id.h [hunk 8]
```diff
@@ -176,6 +177,9 @@ class TaskID : public BaseID<TaskID> {
   static constexpr size_t kUniqueBytesLength = 8;
 
  public:
+  static_assert(absl::little_endian::IsLittleEndian(),
```
Comment (clarkzinzow) [inline src/ray/common/id.h:180]: Question: This is a compilation check, so if the binary is compiled under little-endian byte order and run under big-endian byte order, this assertion won't fail. I think that this would be an issue for dynamically switching byte orders e.g. on ARM.

I _think_ that cross-compilation would be fine given that this static assertion consults the compiler for endianness, and this should be set to the target platform's endianness if the world is sensible?

Anyways, static check should be fine for us I think. 😄

File: src/ray/common/id.cc [hunk 9]
```diff
@@ -194,6 +194,19 @@ TaskID TaskID::ForNormalTask(const JobID &job_id, const TaskID &parent_task_id,
...
 }
 
+TaskID TaskID::ForExecutionAttempt(const TaskID &task_id, uint64_t attempt_number) {
+  std::string data_str;
+  std::copy_n(task_id.Data(), TaskID::kLength, std::back_inserter(data_str));
+  static_assert(TaskID::kUniqueBytesLength >= 8, "TaskID must have at least 64 bits");
+  auto data = reinterpret_cast<uint64_t *>(data_str.data());
+  // Zero out the low byte for readability.
+  uint64_t mask = 0xFFFFFFFFFFFFFF00;
+  data[0] = data[0] & mask;
```
Comment (clarkzinzow) [inline src/ray/common/id.cc:204]: Supernit:
```suggestion
  data[0] &= mask;
```

File: src/ray/common/id_test.cc [hunk 10]
```diff
@@ -69,6 +69,21 @@ TEST(TaskIDTest, TestTaskID) {
...
+  ASSERT_NE(task_id, TaskID::ForExecutionAttempt(task_id, 1));
+  ASSERT_NE(TaskID::ForExecutionAttempt(task_id, 0),
+            TaskID::ForExecutionAttempt(task_id, 1));
+  ASSERT_EQ(TaskID::ForExecutionAttempt(task_id, 0),
+            TaskID::ForExecutionAttempt(task_id, 0));
+  ASSERT_EQ(TaskID::ForExecutionAttempt(task_id, 1),
+            TaskID::ForExecutionAttempt(task_id, 1));
+  // Check for overflow.
+  ASSERT_NE(TaskID::ForExecutionAttempt(task_id, 0),
+            TaskID::ForExecutionAttempt(task_id, 256));
```
Comment (ericl) [inline src/ray/common/id_test.cc:84]: Can check higher ranges now too.

**Review by ericl — APPROVED** [review]

File: src/ray/design_docs/id_specification.md [hunk 11]
```diff
@@ -54,3 +54,6 @@ An `ObjectID` contains 2 parts:
   1 <= idx <= num_return_objects is reserved for the task's return objects, while
   idx > num_return_objects is available for the task's put objects.
 - `TaskID`: 24 bytes to indicate the ID of the task to which this object belongs.
+  Note: For `ray.put()` IDs only, the first byte of the `TaskID` is zeroed out
```
Comment (ericl) [inline src/ray/design_docs/id_specification.md:57]: To clarify, does this also apply to the return ids? Per the description of the PR: `deterministically generate the same IDs for any ray.put or .remote task calls`

**Comment by kfstorm** [comment]
Seems to me the new mechanism is still not **randomized**. Am I missing something?

File: src/ray/design_docs/id_specification.md (hunk 11 above)
Comment (stephanie-wang) [reply src/ray/design_docs/id_specification.md:57]: Ah I'll clarify this. It does not apply to return IDs, but all child task IDs are now seeded with the execution number of the parent task ID, so this will prevent collisions for the return IDs.

**Comment by stephanie-wang** [comment]
> Seems to me the new mechanism is still not **randomized**. Am I missing something?

Yes, that's right, the new mechanism will still generate the IDs deterministically but in a way that avoids collisions for re-executed tasks. Let me update the PR description to reflect that.
