### PR TITLE
Fix local scheduler crash when driver creates actor and exits.

### LINKED ISSUE #1462: local scheduler crashes
### System information
- **OS Platform and Distribution**: Linux Ubuntu 16.04
- **Ray installed from (source or binary)**: source
- **Ray version**: f130329
- **Python version**: 2.7.14
- **Exact command to reproduce**:

Start ray on one machine:
```
ray start --head --redis-port=6379
```

And running the following code on the same machine results in a core dump:

```python
class Foo(object):
    def __init__(self):
        pass

    def act(self):
        pass

ray.init(redis_address="xx.xx.xxx.xx:6379")
wks = [ray.remote(Foo).remote() for i in range(2)]
```
The issue won't happen though if we add one more line in the end
```python 
[ray.get(wk.act.remote()) for wk in wks]
```

### PR DESCRIPTION
**Pull request by robertnishihara**
This should fix #1462.

The problem was that if a driver created an actor and then immediately exited, the local scheduler would call `task_table_update` to "finish" the actor's `__init__` task before ever calling `task_table_add_task` for that task, which is illegal.

The bug fix is just the one line change to the local scheduler. The rest is just some small improvements and adding a test.

### CODE REVIEW

File: src/local_scheduler/local_scheduler_algorithm.cc [hunk 1]
```diff
@@ -407,7 +407,11 @@ void finish_killed_task(LocalSchedulerState *state,
   if (state->db != NULL) {
     Task *task = Task_alloc(execution_spec, TASK_STATUS_DONE,
                             get_db_client_id(state->db));
-    task_table_update(state->db, task, NULL, NULL, NULL);
+    // In most cases, task_table_update would be appropriate, however, it is
+    // possible in some cases that the task has not yet been added to the task
+    // table (e.g., if it is an actor task that is queued locally because the
+    // actor has not been created yet).
+    task_table_add_task(state->db, task, NULL, NULL, NULL);
```
Comment (robertnishihara) [inline src/local_scheduler/local_scheduler_algorithm.cc]: this is the bug fix

**Review by stephanie-wang — APPROVED** [review]
Looks good! Just to make sure, does the test you added fail deterministically without the fix?

**Comment by robertnishihara** [comment]
I don't know about "deterministically", but it failed something like 4 out of 4 times that I tried it locally.
