### PR TITLE
[gcs ft] Mark old head node as dead after pod restart

### LINKED ISSUE #39122: [Core][GCS FT] Two alive head nodes will be present after the original head node recovers from a failure
### What happened + What you expected to happen

KubeRay has several tests for GCS fault tolerance, and I observed that there will be 2 alive head Pods for ~10 seconds in the Ray cluster after the head node recovers from a failure. Therefore, using `ray list nodes` might show more than 1 "ALIVE" head nodes in the cluster temporarily. This may lead to an issue where the Serve controller believes it hasn't been scheduled to the head node, and as a result, it raises an [exception](https://sourcegraph.com/github.com/ray-project/ray@2f12a4b9845244d6043d3615ed4863456dae02a1/-/blob/python/ray/serve/controller.py?L119). To avoid this issue, I added a workaround retry logic in `test_ray_serve_1` to wait until only 1 head node is alive.

Screen Shot 2023-08-30 at 11 57 17 AM

### Versions / Dependencies

2.6.3 & nightly

I believe this is not a new behavior.

### Reproduction script

See https://github.com/ray-project/kuberay/pull/1364 for more details.

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by jonathan-anyscale**
## Why are these changes needed?
Ensure only 1 head node is alive at a time, by marking existing alive head node as dead when we register a new head node

## Related issue number

Closes #39122

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 1]
```diff
@@ -59,6 +59,17 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
     RAY_LOG(INFO) << "Finished registering node info, node id = " << node_id
                   << ", address = " << request.node_info().node_manager_address()
                   << ", node name = " << request.node_info().node_name();
+    if (request.node_info().is_head_node()) {
+      // mark the old head node as dead
+      auto head_node_it =
+          std::find_if(alive_nodes_.begin(), alive_nodes_.end(), [](const auto &node) {
+            return node.second->is_head_node();
+          });
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:67]: Since here we add the new head and then remove the old one. If we crash in between, we will have two heads after restarts so we need to mark all head nodes as dead.

Alternatively, we can mark the old one as dead before adding a new one. This guarantees that there can only be one alive head node in redis at any given point of time.

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 2]
```diff
@@ -59,6 +59,17 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
     RAY_LOG(INFO) << "Finished registering node info, node id = " << node_id
                   << ", address = " << request.node_info().node_manager_address()
                   << ", node name = " << request.node_info().node_name();
+    if (request.node_info().is_head_node()) {
+      // mark the old head node as dead
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:63]:
```suggestion
      // mark the old head node as dead if exists
```

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:63]: Also comment when this happens 

```
1. should never happen when HA is not used
2. happens when a new GCS is started
```

**Review by rkooo567 — COMMENTED** [review]
Hmm wonder instead of we iterate all nodes every time we register a new node (which is N^2) why don't we just have a separate map we record head nodes? 

1. When a new head id registered we add it to this node
2. We kill all items in this data structure when a new head is coming in

File: src/ray/gcs/gcs_server/gcs_node_manager.cc (hunk 1 above)
Comment (jonathan-anyscale) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:67]: we do this before add node in line 74 which adding the head node to alive_nodes.
can move this before `put_node` to table storage too

Comment (jjyao) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc]: What matters is the order in terms of redis.

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 3]
```diff
@@ -53,6 +53,17 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
...
                 << ", node name = " << request.node_info().node_name();
+  if (request.node_info().is_head_node()) {
+    // mark the old head node as dead
+    auto head_node_it =
+        std::find_if(alive_nodes_.begin(), alive_nodes_.end(), [](const auto &node) {
+          return node.second->is_head_node();
+        });
+    if (head_node_it != alive_nodes_.end()) {
+      NodeID old_head_node_id = head_node_it->first;
+      OnNodeFailure(old_head_node_id);
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:64]: OnNodeFailure is async: we need to make sure the old is marked as dead in redis before we add a new one.

File: src/ray/gcs/gcs_server/gcs_node_manager.cc (hunk 2 above)
Comment (jonathan-anyscale) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc]: I think the time complexity will not change to O(N^2) since we only iterate through all node when we add head node which only happens once per gcs server creation (since if a head node dead, then gcs_server also dead?), so same frequency as num calls of `Initialize` which also iterate through all alive nodes.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc]: ah yeah. I missed that part. sgtm then. 

For finding a head node, is it possible to find "all" nodes with head = true? I think it is safer to not assume there's only 1 additional head node (although in reality it could be true)

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 4]
```diff
@@ -64,22 +64,31 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
     GCS_RPC_SEND_REPLY(send_reply_callback, reply, status);
   };
   if (request.node_info().is_head_node()) {
-    // mark the old head node as dead if exists:
+    // mark the all old head nodes as dead if exists:
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:67]:
```suggestion
    // mark all old head nodes as dead if exists:
```

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 5]
```diff
@@ -261,10 +290,12 @@ void GcsNodeManager::OnNodeFailure(const NodeID &node_id) {
...
     node_info_delta->set_end_time_ms(node->end_time_ms());
 
-    auto on_done = [this, node_id, node_info_delta](const Status &status) {
-      RAY_CHECK_OK(gcs_publisher_->PublishNodeInfo(node_id, *node_info_delta, nullptr));
+    auto on_done = [this, node_id, callback, node_info_delta](const Status &status) {
+      RAY_CHECK_OK(gcs_publisher_->PublishNodeInfo(node_id, *node_info_delta, callback));
     };
     RAY_CHECK_OK(gcs_table_storage_->NodeTable().Put(node_id, *node, on_done));
+  } else {
+    callback(Status::OK());
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:298]: callback can be nullptr

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 6]
```diff
@@ -261,10 +290,12 @@ void GcsNodeManager::OnNodeFailure(const NodeID &node_id) {
     node_info_delta->set_state(node->state());
     node_info_delta->set_end_time_ms(node->end_time_ms());
 
-    auto on_done = [this, node_id, node_info_delta](const Status &status) {
-      RAY_CHECK_OK(gcs_publisher_->PublishNodeInfo(node_id, *node_info_delta, nullptr));
+    auto on_done = [this, node_id, callback, node_info_delta](const Status &status) {
+      RAY_CHECK_OK(gcs_publisher_->PublishNodeInfo(node_id, *node_info_delta, callback));
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc]: We don't need to do the callback after `PublishNodeInfo` is done. I think there is no ordering requirement here. We can just invoke the callback directly in `on_done`.

File: src/ray/gcs/gcs_server/gcs_node_manager.h [hunk 7]
```diff
@@ -82,7 +82,7 @@ class GcsNodeManager : public rpc::NodeInfoHandler {
                         rpc::CheckAliveReply *reply,
                         rpc::SendReplyCallback send_reply_callback) override;
 
-  void OnNodeFailure(const NodeID &node_id);
+  void OnNodeFailure(const NodeID &node_id, const StatusCallback &callback);
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.h:85]: Could you add docstring for this method and its parameters. 

Also `callback` as variable name is not that meaningful, maybe `node_table_updated_callback`?

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 8]
```diff
@@ -63,8 +63,36 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
     AddNode(std::make_shared<rpc::GcsNodeInfo>(request.node_info()));
     GCS_RPC_SEND_REPLY(send_reply_callback, reply, status);
   };
-  RAY_CHECK_OK(
-      gcs_table_storage_->NodeTable().Put(node_id, request.node_info(), on_done));
+  if (request.node_info().is_head_node()) {
+    // mark all old head nodes as dead if exists:
+    // 1. should never happen when HA is not used
+    // 2. happens when a new GCS is started
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:69]:
```suggestion
    // 2. happens when a new head node is started
```

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 9]
```diff
@@ -63,8 +63,36 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
...
+
+    std::vector<NodeID> head_nodes;
+    for (auto &node : alive_nodes_) {
+      if (node.second->is_head_node()) {
+        head_nodes.push_back(node.first);
+      }
+    }
```
Comment (jjyao) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:76]: After a second thought, I'd prefer to have a RAY_CHECK to make sure there is at most one alive head node. I think this is guaranteed now since we always mark the old one as dead before adding the new head.

I think this guarantee makes reasoning the code easier.

Thoughts @rkooo567 @jonathan-anyscale ?

File: python/ray/tests/test_gcs_ha_e2e.py [hunk 10]
```diff
@@ -12,16 +12,19 @@ def test_ray_nodes_liveness(docker_cluster):
...
-        text = output.output.decode().strip().split("\n")[-1]
-        print("Output: ", output.output.decode().strip().split("\n"))
+        output_msg = output.output.decode().strip().split("\n")
+        print("Output: ", output_msg)
         assert output.exit_code == 0
-        return n == int(text)
+        for msg in output_msg:
+            if "Num Alive Nodes" in msg:
+                return n == int(msg.split()[-1])
+        return False
```
[the remark this answers is not in the document]
Comment (jonathan-anyscale) [reply python/ray/tests/test_gcs_ha_e2e.py:27]: To ensure that as long as num alive head nodes message is printed since `text` can return error message from kiled head node. This was fine with wait condition, but now since we removed it, previous `check_alive` can fail despite num alive head nodes are correct.

File: src/ray/gcs/gcs_server/gcs_node_manager.cc (hunk 9 above)
Comment (jonathan-anyscale) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:76]: I can agree with this, so we can emphasize the reason we added this code

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:76]: yeah that sounds good to me

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 11]
```diff
@@ -63,8 +63,36 @@ void GcsNodeManager::HandleRegisterNode(rpc::RegisterNodeRequest request,
...
+    std::function<void(int)> kill_node_chain_callback =
+        [this, &kill_node_chain_callback, head_nodes, on_done, request, node_id](
+            const auto &node_idx) {
+          if (node_idx < static_cast<int>(head_nodes.size())) {
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:80]: hmm this recursion logic seems unnecessary. can you just iterate head_nodes instead? I don't think the callback is also necessary? 

```
assert len(head_nodes) == 1
OnNodeFailure(head_nodes[0])
Put(new_head)
```

File: src/ray/gcs/gcs_server/gcs_node_manager.cc [hunk 12]
```diff
@@ -261,10 +290,16 @@ void GcsNodeManager::OnNodeFailure(const NodeID &node_id) {
     node_info_delta->set_state(node->state());
     node_info_delta->set_end_time_ms(node->end_time_ms());
 
-    auto on_done = [this, node_id, node_info_delta](const Status &status) {
+    auto on_done = [this, node_id, node_table_updated_callback, node_info_delta](
+                       const Status &status) {
+      if (node_table_updated_callback != nullptr) {
+        node_table_updated_callback(Status::OK());
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_node_manager.cc:296]: remove a callback!

**Review by rkooo567 — CHANGES_REQUESTED** [review]

File: src/ray/gcs/gcs_server/gcs_node_manager.cc (hunk 11 above)
Comment (jonathan-anyscale) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:80]: we do callback since `OnNodeFailure` is async (has KV put as well). So we want to ensure that `OnNodeFailure` finish before putting the new head node by make it sync

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_node_manager.cc:80]: it will be marked as dead as the source of truth is in memory (alive_nodes_). 

We don't need to worry about ordering as redis update ordering is guaranteed. So failure update will happen before new node update happens to Redis (meaning we don't need to worry about GCS failure case). 

cc @jjyao

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
I like the new logic after we add head_node == 1 assertion!
