### PR TITLE
Fix pull manager deadlock due to object reconstruction

### LINKED ISSUE #13689: [core] Lineage reconstruction fails due to deadlock in object pulling
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 1.2dev

Object reconstruction can fail to a deadlock introduced in #13514. The problem is that failed objects may not have a size, and so tasks that depend on a failed object may block later tasks that need to execute in order to recreate the object.

### Reproduction (REQUIRED)

Skipped tests in `test_reconstruction.py`.

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
When an object is under reconstruction, pull manager keeps the bundle request active with no timeout, which may block the next bundle request that's needed for the object reconstruction. As a result,  we have deadlock.

For example, task 1 takes object A as argument and returns object B, task 2 takes object B as argument. When we run task 2, pull manager will add B to the queue and then B is lost. In this case, task 1 is re-submitted and A is added the the pull manager queue after B (assuming both tasks are scheduled to the same node). Due to limited available object store memory, A cannot be activated until B is pulled but B cannot be pulled until A is pulled and B is reconstructed.

The solution is that if an active pull request has pending-creation objects, pull manager will deactivates it until creation is done. This way, we will free object store memory occupied by the current active pull request so that next requests can proceed and potentially unblock the object creation.

## Related issue number
Closes #13689

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by stephanie-wang — COMMENTED** [review]
I like the high-level change! One thing I'm not sure about is if it will matter that we're no longer preserving order between requests as they go between active and inactive. To be safe, I think we should use map instead of set to store active/inactive requests. One scenario where it could matter, for example, is if we have a large request that has been active for a long time, and we end up deactivating that over another later request.

**Comment by stephanie-wang** [comment]
^ Ignore that, I forgot std::set is ordered :)

File: src/ray/object_manager/pull_manager.cc [hunk 1]
```diff
@@ -182,70 +166,53 @@ bool PullManager::ActivateNextPullBundleRequest(const Queue &bundles,
...
   num_active_bundles_ += 1;
   return true;
 }
 
-void PullManager::DeactivatePullBundleRequest(
-    const Queue &bundles,
-    const Queue::iterator &request_it,
-    uint64_t *highest_req_id_being_pulled,
+void PullManager::DeactivateBundlePullRequest(
+    BundlePullRequests *bundles,
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.cc:176]:
```suggestion
    BundlePullRequests &bundles,
```

(per [style guide](https://google.github.io/styleguide/cppguide.html#Inputs_and_Outputs))

File: src/ray/object_manager/pull_manager.h [hunk 2]
```diff
@@ -196,26 +191,94 @@ class PullManager {
...
-      RAY_CHECK(num_object_sizes_missing > 0);
-      num_object_sizes_missing--;
-      num_bytes_needed += object_size;
+  /// A helper structure for tracking information about each ongoing bundle pull request.
+  struct BundlePullRequest {
+    BundlePullRequest(std::vector<ObjectID> requested_objects,
+                      BundlePriority bundle_priority)
+        : objects(std::move(requested_objects)), priority(bundle_priority) {}
+    const std::vector<ObjectID> objects;
+    const BundlePriority priority;
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.h:204]: Is this field used? Wondering why we need it now but didn't previously.

File: src/ray/object_manager/pull_manager.cc [hunk 3]
```diff
@@ -431,6 +374,8 @@ void PullManager::OnLocationChange(const ObjectID &object_id,
   if (it == object_pull_requests_.end()) {
     return;
   }
+
+  const bool is_pullable_before = it->second.IsPullable();
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.cc:378]:
```suggestion
  const bool was_pullable_before = it->second.IsPullable();
```

File: src/ray/object_manager/pull_manager.h [hunk 4]
```diff
@@ -196,26 +191,94 @@ class PullManager {
...
+
+    void MarkBundleAsPullable(uint64_t request_id) {
+      RAY_CHECK(map_find_or_die(requests, request_id).IsPullable());
+      RAY_CHECK_EQ(active_requests.count(request_id), 0u);
+      inactive_requests.emplace(request_id);
+    }
+
+    void MarkBundleAsUnpullable(uint64_t request_id) {
+      RAY_CHECK(!map_find_or_die(requests, request_id).IsPullable());
+      RAY_CHECK_EQ(active_requests.count(request_id), 0u);
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.h:261]: Oh I see from the .cc file why we can't do this. Can you specify in the docstring that the request must be inactive?

**Review by stephanie-wang — CHANGES_REQUESTED** [review]

File: src/ray/object_manager/pull_manager.h (hunk 2 above)
Comment (jjyao) [reply src/ray/object_manager/pull_manager.h:204]: oops, it's a left over from my previous implementation.

File: python/ray/tests/test_object_manager.py [hunk 5]
```diff
@@ -563,6 +564,62 @@ def ready(self):
...
+    @ray.remote(
+        scheduling_strategy=NodeAffinitySchedulingStrategy(worker_node_2_id, soft=False)
+    )
+    def task_b_to_c(b):
+        return "c"
+
+    object_c = task_b_to_c.remote(object_b)
+    # task_a_to_b will be re-executed on worker_node_2 so pull manager there will
+    # have object_a pull request after the existing object_b pull request.
+    # Make sure object_b pull request won't block the object_a pull request.
```
[the remark this answers is not in the document]
Comment (jjyao) [reply python/ray/tests/test_object_manager.py:618]: It's not guaranteed and I don't know what's a good way to guarantee that. I think I'm more relying on it being non-flaky. Although I did reproduce it on my laptop consistently.

File: src/ray/object_manager/pull_manager.h [hunk 6]
```diff
@@ -141,19 +139,16 @@ class PullManager {
   void ResetRetryTimer(const ObjectID &object_id);
 
   /// The number of ongoing object pulls.
-  int NumActiveRequests() const;
+  int NumObjectPullRequests() const;
```
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/object_manager/pull_manager.h:142]: Yes, just a bad naming.  We are counting `object_pull_reqeusts_` not `active_object_pull_requests_`

File: src/ray/object_manager/pull_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/object_manager/pull_manager.cc:176]: oh, apparently I'm still remembering the old style guide: https://github.com/google/styleguide/commit/7a7a2f510efe7d7fc :)

File: python/ray/tests/test_object_manager.py (hunk 5 above)
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply python/ray/tests/test_object_manager.py:619]: Okay got it! Yeah, I was curious if it would fail on laptop/CI.

File: src/ray/object_manager/pull_manager.cc [hunk 7]
```diff
@@ -450,37 +395,58 @@ void PullManager::OnLocationChange(const ObjectID &object_id,
...
+      if (bundle_it != get_request_bundles_.requests.end()) {
+        bundles = &get_request_bundles_;
+      } else if (bundle_it = wait_request_bundles_.requests.find(bundle_request_id);
+                 bundle_it != wait_request_bundles_.requests.end()) {
+        bundles = &wait_request_bundles_;
+      } else {
+        bundle_it = task_argument_bundles_.requests.find(bundle_request_id);
+        RAY_CHECK(bundle_it != task_argument_bundles_.requests.end());
+        bundles = &task_argument_bundles_;
+      }
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.cc:423]: Suggest defining a helper function to find the right queue for readability.

File: src/ray/object_manager/pull_manager.cc [hunk 8]
```diff
@@ -683,98 +641,79 @@ void PullManager::UnpinObject(const ObjectID &object_id) {
...
+    RAY_CHECK(task_argument_bundles_.requests.contains(request_id));
+    bundles = &task_argument_bundles_;
   }
 
-  if (request_id <= *highest_req_id_being_pulled) {
-    // This request is in the prefix of the queue that is being pulled.
-    return true;
-  }
-  return bundle_it->second.num_object_sizes_missing > 0;
+  return bundles->inactive_requests.count(request_id) == 0;
```
Comment (stephanie-wang) [inline src/ray/object_manager/pull_manager.cc:662]: Can you add a comment here? Took me a minute to understand why this works.

**Review by stephanie-wang — APPROVED** [review]
Nice, this is great! Let's also check if it's working on the chaos test in parallel?
