### PR TITLE
[Doc] Fix heading issue which broke AI assistant

### LINKED ISSUE #42461: [docs] [AI Assistant] Clicking on the Ask AI button to submit a query doesn't work
### Description

When I type a query and hit the Ask AI button, it doesn't submit the query. With the last PR, I also expected that hitting return at the end of the query string, would be equivalent to hitting the Ask AI button. Instead, a carriage return appears in the input box and the dialog box scrolls down. 

BTW, could we change the copyright message to say `2024` instead of `2023`?

cc: @chris-ray-zhang 

### Link

https://docs.ray.io/en/master/

### PR DESCRIPTION
**Pull request by peytondmurray**
## Why are these changes needed?

This PR fixes an issue where right headers were not being included in `index.html`, breaking the AI assistant.

In overriding the template for `index.html`, the relevant headers must be included, just as they are in `layout.html`. To do this, I moved the headers into their own `extrahead.html` template, which gets included in both `layout.html` and `index.html` (since we override `layout.html` for that page.)

I also updated the copyright displayed for the AI assistant to 2024, as per the original issue.

## Related issue number

Closes https://github.com/ray-project/ray/issues/42461.

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by chris-ray-zhang** [comment]
Loom video to confirm expected behavior: https://www.loom.com/share/7983065f1fbf4cbcbce5697d3770b6d5

**Review by chris-ray-zhang — APPROVED** [review]
lgtm thanks

File: doc/source/_static/js/assistant.js [hunk 1]
```diff
@@ -1,15 +1,15 @@
 // Create chat-widget div
-var chatWidgetDiv = document.createElement("div");
-chatWidgetDiv.className = "chat-widget";
+var chatWidgetDiv = document.createElement('div');
+chatWidgetDiv.className = 'chat-widget';
```
Comment (aslonnie) [inline doc/source/_static/js/assistant.js:3]: what are these styling changes? is is related to AI assistant breaking?

File: doc/source/_static/js/assistant.js [hunk 2]
```diff
@@ -30,150 +30,153 @@ chatPopupDiv.innerHTML = `
     </div>
   </div>
   <div class="chatFooter text-right p-2">
-    © Copyright 2023, The Ray Team.
+    © Copyright 2024, The Ray Team.
```
Comment (aslonnie) [inline doc/source/_static/js/assistant.js:33]: is this year change related to AI assistant breaking?

File: doc/source/_static/js/assistant.js [hunk 3]
```diff
@@ -30,150 +30,153 @@ chatPopupDiv.innerHTML = `
...
+          {
+            method: 'POST',
+            headers: {
+              'Content-Type': 'application/json',
+              Accept: 'application/json',
+            },
+            body: JSON.stringify({query: searchTerm}),
+          },
         );
+        const reader = response.body.getReader();
```
Comment (aslonnie) [inline doc/source/_static/js/assistant.js:150]: I suppose something inside here changed? but it is hard to tell what it is.

File: doc/source/_templates/extrahead.html [hunk 4]
```diff
@@ -0,0 +1,71 @@
+<!-- Extra header to include at the top of each template.
```
Comment (aslonnie) [inline doc/source/_templates/extrahead.html:1]: is this file a pure moving?

File: doc/source/_static/js/assistant.js (hunk 2 above)
Comment (chris-ray-zhang) [reply doc/source/_static/js/assistant.js:33]: a request from @angelinalg per https://github.com/ray-project/ray/issues/42461

Comment (peytondmurray) [reply doc/source/_static/js/assistant.js:33]: Usually I do one issue -> one PR. I'll make a separate issue for this if that's preferred.

File: doc/source/_static/js/assistant.js (hunk 1 above)
Comment (peytondmurray) [reply doc/source/_static/js/assistant.js:3]: Ugh, no. This is caused by the fact that I'm running pre-commit, but it hasn't yet been run on anything in `doc/`. I'm opening up an issue and a PR to do this now so we don't have to keep worrying about this. See https://github.com/ray-project/ray/pull/42589.

File: doc/source/_templates/extrahead.html (hunk 4 above)
Comment (peytondmurray) [reply doc/source/_templates/extrahead.html:1]: No, it's a brand new file. Since we now need this heading in two separate templates (`index.html` and `layout.html`), I'm breaking this into its own file so that we can easily include it in both without repeating ourselves.

File: doc/source/_static/js/assistant.js (hunk 3 above)
Comment (peytondmurray) [reply doc/source/_static/js/assistant.js:150]: Yep, it was just the 2023->2024 change. Since we're doing that elsewhere anyway, I'll get rid of this.

**Review by aslonnie — APPROVED** [review]

**Review by angelinalg — APPROVED** [review]
