### PR TITLE
Split profile table among many keys in the GCS.

### LINKED ISSUE #3306: Uncontrolled profiling table
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **Ray installed from (source or binary)**:
- **Ray version**:
- **Python version**:
- **Exact command to reproduce**:

### Describe the problem

For a long running job, this profiling table will grow very big.
We can provide an option for users to choose open this profiler or not.

### PR DESCRIPTION
**Pull request by robertnishihara**
This fixes #3306 by sharding the profile table over a number of keys in the GCS.
- Each key now corresponds to one batch of profiling info (e.g., one second of data) as opposed to all events from a given process.
- I removed `--collect-profiling-data`.
- I verified that the profile table gets flushed via GCS LRU eviction.
- I checked that the timeline visualization works properly (including when GCS eviction is happening).

### CODE REVIEW

File: src/ray/gcs/tables.h [hunk 1]
```diff
@@ -501,23 +501,6 @@ class ProfileTable : private Log<UniqueID, ProfileTableData> {
...
-  /// \param component_type The type of the component that the event came from.
-  /// \param component_id An identifier for the component that generated the event.
-  /// \param node_ip_address The IP address of the node that generated the event.
-  /// \param start_time The timestamp of the event start, this should be in seconds since
-  /// the Unix epoch.
-  /// \param end_time The timestamp of the event end, this should be in seconds since
-  /// the Unix epoch. If the event is a point event, this should be equal to start_time.
-  /// \param extra_data Additional data to associate with the event.
-  /// \return Status.
-  Status AddProfileEvent(const std::string &event_type, const std::string &component_type,
```
Comment (robertnishihara) [inline src/ray/gcs/tables.h]: This was unused.

File: python/ray/workers/default_worker.py [hunk 2]
```diff
@@ -51,11 +51,6 @@
     type=str,
     default=ray_constants.LOGGER_FORMAT,
     help=ray_constants.LOGGER_FORMAT_HELP)
-parser.add_argument(
-    "--collect-profiling-data",
-    type=int,  # int since argparse can't handle bool values
-    default=1,
-    help="Whether to collect profiling data from workers.")
```
Comment (robertnishihara) [inline python/ray/workers/default_worker.py]: Now that we flush the GCS (including the profiling table), we no longer need this.

**Review by ericl — APPROVED** [review]

**Comment by robertnishihara** [comment]
Thanks @ericl, I removed the reference. I'll remove the entire page when we turn on flushing by default.
