### PR TITLE
[Dashboard] Fix GPU resource rendering issue

### LINKED ISSUE #13265: [dashboard] Frequently getting `Cannot read property 'usedResources' of undefined` and blank screen
### What is the problem?
Dashboard gets blank with Error:
image
image

Complete log: 
[172.31.1.103-1610037078818.log](https://github.com/ray-project/ray/files/5782810/172.31.1.103-1610037078818.log)

#### System
* ray: 1.2.0.dev0
* python3.7
* NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0 GeForce GTX 1070
* ubuntu 18.04
* Chromium: Version 87.0.4280.66 (Official Build) Built on Ubuntu

### Reproduction (REQUIRED)
I am not yet able to reproduce this issue as it comes and goes, but it is kind of anoying, because you never know whan it comes back. I am actually not sure if it is a real severe issue -> I dont know that much about how the dashboard works internally but at least that case should be possible to prevent with adding ? behind `coreWorkerStats[0]`, however not sure if that causes another error than at some other place...

```
const WorkerGPU: WorkerFeatureRenderFn = ({ worker }) => {
const workerRes = worker.coreWorkerStats[0].usedResources;
const workerUsedGPUResources = workerRes?.["GPU"];
```

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I also saw this error before in a clean environment, but right now it happens on our test cluster
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

@mfitton

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
In `GPU.tsx`, this line can fail 
```
worker.coreWorkerStats[0].usedResources;
```
because coreWorkerStats can be empty array as @TanjaBayer reported. (thx!)

img

## Related issue number
Closes #13265

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: dashboard/client/src/pages/dashboard/node-info/features/GPU.tsx [hunk 1]
```diff
@@ -133,7 +133,7 @@ const WorkerGPUEntry: React.FC<WorkerGPUEntryProps> = ({ resourceSlot }) => {
 };
 
 const WorkerGPU: WorkerFeatureRenderFn = ({ worker }) => {
-  const workerRes = worker.coreWorkerStats[0].usedResources;
+  const workerRes = worker.coreWorkerStats[0]?.usedResources;
```
Comment (simon-mo) [inline dashboard/client/src/pages/dashboard/node-info/features/GPU.tsx:136]: the `?` propagate the `undefined` value so if `coreWorkerStats` is empty, `workerRes` will be `undefined` as well.

**Review by edoakes — APPROVED** [review]
