### PR TITLE
[Fix][Core] Close unused pipe file descriptor of child processes of Raylet

### LINKED ISSUE #52385: [Core] Agent process does not die after raylet dies in a special setup
### What happened + What you expected to happen

Follow-up for #52336. The root cause for the side effect is that in the special setup of `test_job_head_choose_job_agent_E2E`, after `kill_raylet` is called, normally the corresponding agent process should also die. But sometimes the agent process still alive.

https://github.com/ray-project/ray/blob/0a0aad6b00dabc25134d75d7cbdc34ebc3ecd8c1/python/ray/dashboard/modules/job/tests/test_sdk.py#L289

### Versions / Dependencies

master branch

### Reproduction script

https://github.com/ray-project/ray/blob/0a0aad6b00dabc25134d75d7cbdc34ebc3ecd8c1/python/ray/dashboard/modules/job/tests/test_sdk.py#L289

### Issue Severity

None

### PR DESCRIPTION
**Pull request by MortalHappiness**
### Root cause

- We rely on a pipe-based mechanism to monitor the parent process (raylet)'s health:  
  https://github.com/ray-project/ray/blob/07a00f20bb830c61ccf8fb2fddcfae8fa4c418dd/python/ray/_private/process_watcher.py#L127-L149  
  - Ideally, when raylet dies, the OS will close all its file descriptors. With no process holding the write end of the pipe, so the `readline()` in https://github.com/ray-project/ray/blob/07a00f20bb830c61ccf8fb2fddcfae8fa4c418dd/python/ray/_private/process_watcher.py#L138 will return an empty string, indicating that the raylet has exited.
  - However, this only works if *no other process* holds the pipe's write end.
- Raylet launches several child processes via `fork + exec`. For example, `DashboardAgent` and `RuntimeEnvAgent`:  
  https://github.com/ray-project/ray/blob/c2a6de384217e5db6f055d0607ca3e531deed56c/src/ray/raylet/node_manager.cc#L392-L393  
  - These child processes are spawned using `ProcessFD::spawnvpe`:  
    https://github.com/ray-project/ray/blob/a80f02f2c1c53d79eb94ecafaf59ae51f87d0734/src/ray/util/process.cc#L130  
    This function sets up a pipe and closes unused ends in both parent and child:  
    https://github.com/ray-project/ray/blob/6ca0da17300e6087ae6bc9cb9faaa7e9a071b33e/src/ray/util/process.cc#L178-L226
  - Raylet (parent process) creates `DashboardAgent` first, holding the write end (`parent_lifetime_pipe[1]`, say fd 40), and closes the read end.
  - The dashboard agent (child process 1) holds the read end (`parent_lifetime_pipe[0]`, say fd 39), and closes the write end.
  - When raylet later forks `RuntimeEnvAgent` (child process 2), all open fds (including fd 40) are inherited by the new child process.
  - As a result, even if raylet dies, `RuntimeEnvAgent` still holds fd 40 (write end), preventing `DashboardAgent` from detecting raylet's death.
- Therefore, `readline()` in the dashboard agent hangs forever instead of returning an empty string.

**Solution:** Ensure unused pipe write ends are closed on `exec` by setting `FD_CLOEXEC`.

### Changes in this PR

- Revert the changes in https://github.com/ray-project/ray/pull/52388 because it is only a hotfix.
- Move `SetFdCloseOnExec` to `process.h` and `process.cc` and make it a public util function.
- Call `SetFdCloseOnExec` in the parent process to make sure the pipe fd is closed in subsequent `exec`.

### Testing

Tested manually. Before this PR, in about 20% of the runs the agent process did not exit after the raylet died. After this PR, I ran it 20 times consecutively and the agent process successfully exited in all runs.

## Related issue number

Closes: ray-project/ray#52385

## Checks

- [x] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
@israbbani you should review it :)

File: src/ray/common/client_connection.cc [hunk 1]
```diff
@@ -54,26 +55,6 @@ void SetFdCloseOnExec(const NativeHandleType &handle) {
   // https://learn.microsoft.com/en-us/windows/win32/sysinfo/handle-inheritance
   return;
 }
-#else
```
Comment (edoakes) [inline src/ray/common/client_connection.cc:57]: let's keep the linux & windows implementations of `SetFdCloseOnExec` in the same place, so also move the `#if defined(_WIN32)` branch

File: src/ray/common/client_connection.cc [hunk 2]
```diff
@@ -30,6 +30,7 @@
 
 #include "ray/common/event_stats.h"
 #include "ray/common/ray_config.h"
+#include "ray/util/process.h"
```
Comment (edoakes) [inline src/ray/common/client_connection.cc:33]: this is a little bit of an odd dependency to introduce -- IMO instead let's split `SetFdCloseOnExec` out into a utility that is depended on by both this and `process.cc`

File: src/ray/util/process.h [hunk 3]
```diff
@@ -40,6 +40,18 @@ enum { PID_MAX_LIMIT = 1 << 22 };
 
 namespace ray {
 
+#if !defined(_WIN32)
+/// Sets the flag FD_CLOEXEC to a file descriptor.
+/// This means when the process is forked, this fd would be closed in the child process
+/// side. Raylet forks to create core workers and we don't want the Unix Socket FDs to be
+/// inherited by the core workers. Leaking these FDs would have performance implications.
+///
+/// Idempotent. Calling twice == calling once.
```
Comment (edoakes) [inline src/ray/util/process.h:49]:
```suggestion
/// Idempotent.
```

File: src/ray/util/process.h [hunk 4]
```diff
@@ -40,6 +40,18 @@ enum { PID_MAX_LIMIT = 1 << 22 };
 
 namespace ray {
 
+#if !defined(_WIN32)
+/// Sets the flag FD_CLOEXEC to a file descriptor.
```
Comment (edoakes) [inline src/ray/util/process.h:44]:
```suggestion
/// Sets the FD_CLOEXEC flag on a file descriptor.
```

File: src/ray/util/process.cc [hunk 5]
```diff
@@ -202,6 +216,7 @@ class ProcessFD {
     if (pid != 0 && pipefds[1] != -1) {
       close(pipefds[1]);  // not the child, so close the write end of the pipe
       pipefds[1] = -1;
+      SetFdCloseOnExec(pipefds[0]);
```
Comment (edoakes) [inline src/ray/util/process.cc:219]: drop a comment for the purpose of this

Comment (edoakes) [reply src/ray/util/process.cc:219]: any reason we shouldn't also set `FD_CLOEXEC` on the write end of the pipe inside the child? that'd prevent FD leaks if users fork processes for any reason

File: src/ray/util/process.h [hunk 6]
```diff
@@ -40,6 +40,18 @@ enum { PID_MAX_LIMIT = 1 << 22 };
...
+/// This means when the process is forked, this fd would be closed in the child process
+/// side. Raylet forks to create core workers and we don't want the Unix Socket FDs to be
+/// inherited by the core workers. Leaking these FDs would have performance implications.
```
Comment (edoakes) [inline src/ray/util/process.h:47]: this section of the comment is an abstraction leak, should be put at the callsite to close those FDs instead

File: python/ray/dashboard/consts.py [hunk 7]
```diff
@@ -87,7 +87,7 @@
     METRICS_INPUT_ROOT, "prometheus", "prometheus.yml"
 )
 PARENT_HEALTH_CHECK_BY_PIPE = env_bool(
-    "RAY_enable_pipe_based_agent_to_parent_health_check", False
+    "RAY_enable_pipe_based_agent_to_parent_health_check", True
```
Comment (edoakes) [inline python/ray/dashboard/consts.py:90]: is there any reason this wasn't on by default previously? would look at git history to sanity check

**Review by edoakes — COMMENTED** [review]
Great work @MortalHappiness!

Most of the comments are stylistic improvements to leave the code better than we found it.

File: src/ray/common/client_connection.cc (hunk 1 above)
Comment (MortalHappiness) [reply src/ray/common/client_connection.cc:57]: I removed the entire implementation of the Windows version of `SetFdCloseOnExec` and instead used macros to conditionally call it inside `client_connection.cc`. Since it does nothing and simply returns, and Windows does not use "file descriptors", I felt it was odd to keep it as a utility function.

File: src/ray/common/client_connection.cc (hunk 2 above)
Comment (MortalHappiness) [reply src/ray/common/client_connection.cc:33]: Where do you think is a better place to put this utility function? I originally wanted to put it in `src/ray/util/util.h`, but I found that `src/ray/util/util.cc` includes `"ray/util/process.h"`, so this creates a circular dependency between `process.h` and `util.h`.

Comment (MortalHappiness) [reply src/ray/common/client_connection.cc:33]: I'm not very familiar with Bazel. Do we perhaps have a way to handle circular dependencies in Bazel?

File: src/ray/util/process.cc (hunk 5 above)
Comment (MortalHappiness) [reply src/ray/util/process.cc:220]: Because the child process has closed `pipefds[0]` above.

File: python/ray/dashboard/consts.py (hunk 7 above)
Comment (MortalHappiness) [reply python/ray/dashboard/consts.py:90]: I found a comment here https://github.com/ray-project/ray/pull/41935#discussion_r1428162075. In fact, the default value on the Python side is not used at all.

**Review by israbbani — COMMENTED** [review]
Good investigation and thank you for the writeup! 

The fix looks correct to me. I left a few small comments.

File: src/ray/util/process.cc (hunk 5 above)
Comment (edoakes) [reply src/ray/util/process.cc:220]: ah yeah but in that codepath, shouldn't we also do:
`SetFdCloseOnExec(pipefds[1])`?

File: src/ray/common/client_connection.cc (hunk 2 above)
Comment (edoakes) [reply src/ray/common/client_connection.cc:33]: I see... wouldn't expect that `util.h` requires `process.h`. Do you know what it's including from there?

File: src/ray/util/process.cc (hunk 5 above)
Comment (MortalHappiness) [reply src/ray/util/process.cc:220]: No we cannot call `SetFdCloseOnExec(pipefds[1])` because `pipefds[1]` is needed for the child process. It should still be opened after fork.

Comment (MortalHappiness) [reply src/ray/util/process.cc:220]: There is no flag like "close on second exec". It's hard to prevent a file descriptor from being inherited by the grandchild process because the child process is a Python process and we don't explicitly pass the file descriptor number to it.

Comment (MortalHappiness) [reply src/ray/util/process.cc:220]: If we want to handle this, we need to pass file descriptor numbers that we don't want to propagate as arguments to child process.

Comment (MortalHappiness) [reply src/ray/util/process.cc:220]: We can also try `posix_spawn` as specified in the TODO comment here. I haven't looked into it in depth yet though.

https://github.com/ray-project/ray/blob/f2aa9505f9bf3931155a8b00ffd5394ee254ac7c/src/ray/util/process.cc#L192-L193

File: src/ray/common/client_connection.cc (hunk 2 above)
Comment (MortalHappiness) [reply src/ray/common/client_connection.cc:33]: https://github.com/ray-project/ray/blob/8f7e30a2beb3003d09392b2f89a6d1a99b7ac338/src/ray/util/util.cc#L201

`IsProcessAlive` and `IsParentProcessAlive`

File: src/ray/common/client_connection.cc [hunk 8]
```diff
@@ -42,48 +43,16 @@
...
-  RAY_CHECK_NE(flags, -1) << "fcntl error: errno = " << errno << ", fd = " << fd;
-  const int ret = fcntl(fd, F_SETFD, flags | FD_CLOEXEC);
-  RAY_CHECK_NE(ret, -1) << "fcntl error: errno = " << errno << ", fd = " << fd;
-  RAY_LOG(DEBUG) << "set FD_CLOEXEC to fd " << fd;
-}
-#endif
-
-}  // namespace
-
 void SetCloseOnExec(local_stream_socket &socket) {
```
[the remark this answers is not in the document]
Comment (MortalHappiness) [reply src/ray/common/client_connection.cc:46]: Is is also used in https://github.com/ray-project/ray/blob/52899a8679651f14c21a88a8c7270697a52065fb/src/ray/object_manager/plasma/store.cc#L113 and https://github.com/ray-project/ray/blob/51d1af96579bb19071d95e2b57a7f7a36b04d581/src/ray/raylet/raylet.cc#L86.

Do you think it's better to also replace them with

```
#if !defined(_WIN32)
  SetFdCloseOnExec(acceptor.native_handle());
#endif
```

File: python/ray/dashboard/consts.py (hunk 7 above)
Comment (MortalHappiness) [reply python/ray/dashboard/consts.py]: Make sense. Reverted. Thanks.

File: src/ray/util/process.cc (hunk 5 above)
Comment (edoakes) [reply src/ray/util/process.cc:220]: In the branch here once we're inside the child process after fork, we already have the FD in the child. Why can't we call `FD_CLOEXEC` there

Comment (MortalHappiness) [reply src/ray/util/process.cc:220]: Let me correct my statement. We cannot call `SetFdCloseOnExec(pipefds[1])` because `pipefds[1]` is the write end of the pipe for the child process (`agent.py`), and the parent process (`raylet`) uses `pipefds[0]` to detect the child's health. Note that this line is executed after `fork` but before `exec` for `agent.py` (`exec` happens here: [https://github.com/ray-project/ray/blob/f2aa9505f9bf3931155a8b00ffd5394ee254ac7c/src/ray/util/process.cc#L263-L264](https://github.com/ray-project/ray/blob/f2aa9505f9bf3931155a8b00ffd5394ee254ac7c/src/ray/util/process.cc#L263-L264)). If we call `SetFdCloseOnExec(pipefds[1])`, it will be closed when `exec` is executed, and `agent.py` will no longer hold the write end of the pipe. As a result, `raylet` will treat `agent.py` as dead and terminate.

On the other hand, we *can* call `SetFdCloseOnExec(parent_lifetime_pipe[0])` in the child process because `parent_lifetime_pipe[0]` is the read end of the pipe, and more importantly, it is redirected to `stdin` via `dup2` here: [https://github.com/ray-project/ray/blob/f2aa9505f9bf3931155a8b00ffd5394ee254ac7c/src/ray/util/process.cc#L257](https://github.com/ray-project/ray/blob/f2aa9505f9bf3931155a8b00ffd5394ee254ac7c/src/ray/util/process.cc#L257). So even if it is closed, `stdin` still holds the read end of the pipe, so it still works.

I've called `SetFdCloseOnExec(parent_lifetime_pipe[0])` in my latest commit.

File: src/ray/common/client_connection.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (israbbani) [reply src/ray/common/client_connection.cc:46]: Can we call 

`ray::SetFdCloseOnExec(socket.native_handle());`

in both store.cc and raylet.cc?

And, can the implementation of `SetFdCloseOnExec(..)` handle the OS checking (so we remove the ifdef from client_connection.cc). 

The implementation in can be in `process.cc` and it can look like

```C++
// ...
void SetFdCloseOnExec(int fd) {
#ifdef !(_WIN32)
  if (fd < 0) {
    return;
  }
  int flags = fcntl(fd, F_GETFD, 0);
  RAY_CHECK_NE(flags, -1) << "fcntl error: errno = " << errno << ", fd = " << fd;
  const int ret = fcntl(fd, F_SETFD, flags | FD_CLOEXEC);
  RAY_CHECK_NE(ret, -1) << "fcntl error: errno = " << errno << ", fd = " << fd;
  RAY_LOG(DEBUG) << "set FD_CLOEXEC to fd " << fd;
#endif
}

[the remark this answers is not in the document]
Comment (MortalHappiness) [reply src/ray/common/client_connection.cc:46]: I don't think it is good to do this for two reasons:

* The input argument for `SetFdCloseOnExec` is `int fd`, which is of type `int` and different from the `native_handle` type.
* The concept of `native_handle` only exists in the Boost socket library. But `SetFdCloseOnExec` should work on any Unix file descriptor, not necessarily a socket file descriptor.

But thanks for your proposal. I also think it would be good if we can remove the intermediate function `SetCloseOnExec`. Further proposals are welcome!

**Review by edoakes — APPROVED** [review]

File: src/ray/common/client_connection.cc (hunk 8 above)
[the remark this answers is not in the document]
Comment (israbbani) [reply src/ray/common/client_connection.cc:46]: Makes sense. My only real concern with this is having the OS checking code inside `client_connection.cc`. We can revisit it later separately.

**Review by israbbani — APPROVED** [review]
🚢 Thanks for the very thorough explanation!
