### PR TITLE
Fix log losses

### LINKED ISSUE #9555: [core] Driver log file lost after multiple `ray.init`s in the same process
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 0.9dev

The driver logs to a `python-core-driver-*` file correctly during the first `ray.init()`, but then a subsequent `ray.shutdown()` and `ray.init()` does not produce a second file in the session logs. This is probably only relevant for pytests that run multiple ray sessions in the same process.

### Reproduction (REQUIRED)

Any checked in pytest. For example, `pytest python/ray/tests/test_basic.py`.

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by mehrdadn**
## Why are these changes needed?

Some logging is lost due to the `std::ofstream` not being closed after log shutdown, which caused the subsequent `open` of the same `std::ofstream` object to fail.

Also disables buffering of the sink to avoid log message loss.

## Related issue number

Closes #9555

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested (please justify below)

### CODE REVIEW

File: src/ray/util/logging.cc [hunk 1]
```diff
@@ -200,6 +200,7 @@ void RayLog::StartRayLog(const std::string &app_name, RayLogLevel severity_thres
     strftime(buffer, sizeof(buffer), "%Y%m%d-%H%M%S", localtime(&rawtime));
     std::string path = dir_ends_with_slash + app_name_without_path + "." + buffer + "." +
                        std::to_string(pid) + ".log";
+    stream_logger_singleton.out_.rdbuf()->pubsetbuf(0, 0);
```
Comment (stephanie-wang) [inline src/ray/util/logging.cc:203]: Does this have any performance implications?

**Review by stephanie-wang — APPROVED** [review]

File: src/ray/util/logging.cc (hunk 1 above)
Comment (mehrdadn) [reply src/ray/util/logging.cc:203]: I don't know, but hopefully not significant ones. Though I think buffering isn't really appropriate in this layer regardless, since it can result in random log truncation. The kernel should already buffer sequential writes (which won't result in truncation), and [glog also has buffering support](/google/glog/blob/28321d8959574a8268de3ebe41d40cf65415fc9b/src/logging.cc#L145), so I think it's better to delegate to those.
