### PR TITLE
[Core] RetryObjectInPlasmaErrors tries to fetch all objects, not just ready ones.

### LINKED ISSUE #30375: [Core] ray.wait(fetch_local=True) does not prefetch more than num_returns objects
## What happened + What you expected to happen

When you specify `ray.wait(objs, fetch_local=True, num_returns=N)`, the expected behavior is that we send a fetch request for `len(objs)` objects to the raylet. Internally, the raylet persists these fetch requests until the current task finishes or the worker is killed. This enables users to use `ray.wait` repeatedly in a loop to prefetch objects.

However, there is a bug where instead of issuing `len(objs)` fetch requests, we issue `N` requests. This is due to a logic error in `core_worker.cc` that incorrectly skips over objects not in the ready set. The following patch fixes the issue:

```
--- a/src/ray/core_worker/core_worker.cc
+++ b/src/ray/core_worker/core_worker.cc
@@ -1260,20 +1260,11 @@ void RetryObjectInPlasmaErrors(std::shared_ptr<CoreWorkerMemoryStore> &memory_st
   for (auto iter = memory_object_ids.begin(); iter != memory_object_ids.end();) {
     auto current = iter++;
     const auto &mem_id = *current;
-    auto ready_iter = ready.find(mem_id);
-    if (ready_iter != ready.end()) {
-      std::vector<std::shared_ptr<RayObject>> found;
-      RAY_CHECK_OK(memory_store->Get({mem_id},
-                                     /*num_objects=*/1,
-                                     /*timeout=*/0,
-                                     worker_context,
-                                     /*remote_after_get=*/false,
-                                     &found));
-      if (found.size() == 1 && found[0]->IsInPlasmaError()) {
-        plasma_object_ids.insert(mem_id);
-        ready.erase(ready_iter);
-        memory_object_ids.erase(current);
-      }
+    auto found = memory_store->GetIfExists(mem_id);
+    if (found != nullptr && found->IsInPlasmaError()) {
+      plasma_object_ids.insert(mem_id);
+      ready.erase(mem_id);
+      memory_object_ids.erase(current);
     }
   }
 }
```

This is the root cause of https://github.com/ray-project/ray/issues/23983

## Benchmarks

After applying this patch, the wait based prefetch time improved considerably (about on par with the actor prefetcher):

```
Actor prefetcher
------------------
Runs: 15.7s, 14.2s, 17.2s, 10.2s ~= 14.3 seconds mean

Wait prefetcher (old)
------------------
Runs: 23.4s, 18.3s, 19.5s, 19.8s ~= 20.2 seconds mean

Wait prefetcher (after this PR)
------------------
Runs: 11.2s, 12.7s, 17.1s, 12.8s ~= 13.4 seconds mean
```

The script I used was this (run on a two-node cluster):

```
import ray
import time
import numpy as np

# 15GB
ds = ray.data.range_tensor(100000, shape=(80, 80, 3), parallelism=200)
print(ds.size_bytes() / 1e9, "GB")

context = ray.data.context.DatasetContext.get_current()
context.actor_prefetcher_enabled = False

start = time.time()
latencies = []
for _ in ds.iter_batches(batch_size=None, prefetch_blocks=5):
    latencies.append(time.time() - start)
    start = time.time()
    if len(latencies) % 10 == 0:
            print("Latencies (mean/50/90)", np.mean(latencies), np.median(latencies), np.quantile(latencies, 0.9))

print(ds.stats())
```

### PR DESCRIPTION
**Pull request by cadedaniel**
Eric root-caused a bug in Datasets prefetching that was impacting performance. The TL;DR is that a bug in core_worker.cc was causing `ray.wait(objrefs, num_returns=N, fetch_local=True)` to only fetch N objects locally, instead of `len(objrefs)`.

Eric's patch fixes this by having core_worker.cc fetch `len(objrefs)` objects locally. In the case where `len(objrefs)` > N, there should now be more prefetching 🎉 .

Closes https://github.com/ray-project/ray/issues/30375.

### Testing
Steps followed:
1. Create Workspace with two nodes.
2. Start Ray on latest on each node, each with 20GB object store size.
3. Run a modified version of Eric's script (see below) that creates a 15GB dataset on the worker node, and streams it to the head node using `prefetch_blocks=10`.
4. Compile Ray with latest + this PR / start Ray on each node
5. Run the same script

#### Results
`after` indicates a test run including this change, `before` indicates a test run without this change.
```
$ grep 'In ray.wait' *prefetch*
after_prefetch10_1:* In ray.wait(): 138.7ms
after_prefetch10_2:* In ray.wait(): 400.36ms
after_prefetch10_3:* In ray.wait(): 54.53ms
after_prefetch10_4:* In ray.wait(): 350.69ms
before_prefetch_10_1:* In ray.wait(): 2.44s
before_prefetch_10_2:* In ray.wait(): 1.57s
before_prefetch_10_3:* In ray.wait(): 1.6s
before_prefetch_10_4:* In ray.wait(): 1.34s
```

#### Test script
```python3
#!/usr/bin/env python3

import ray
import time
import numpy as np


@ray.remote
def create_ds():
    # 15 GB
    ds = ray.data.range_tensor(100000, shape=(80, 80, 3), parallelism=200)

    return ray.put(ds)

# Create ds on worker node
ref = ray.get(create_ds.options(resources={'node:172.31.181.44': 0.001}).remote())
ds = ray.get(ref)
print(ds.size_bytes() / 1e9, "GB")

context = ray.data.context.DatasetContext.get_current()
context.actor_prefetcher_enabled = False

start = time.time()
latencies = []
for _ in ds.iter_batches(batch_size=None, prefetch_blocks=10):
    latencies.append(time.time() - start)
    start = time.time()
    if len(latencies) % 10 == 0:
            print("Latencies (mean/50/90)", np.mean(latencies), np.median(latencies), np.quantile(latencies, 0.9))

print(ds.stats())
```

### CODE REVIEW

**Review by clarkzinzow — APPROVED** [review]
Awesome! I traced through the rest of the wait protocol through the Plasma store provider and the raylet, and it looks like this gives us the desired prefetching semantics. Super great that the fix ended up being so small!

As a follow-up, we should change the Datasets-level default prefetcher to use `ray.wait()` by default rather than the dummy prefetching actor:
- https://github.com/ray-project/ray/blob/47f8faa0f2389e6995b3cda6834adbbdac71316e/python/ray/data/_internal/block_batching.py#L113-L120
- https://github.com/ray-project/ray/blob/47f8faa0f2389e6995b3cda6834adbbdac71316e/python/ray/data/context.py#L56

**Comment by cadedaniel** [comment]
> As a follow-up, we should change the Datasets-level default prefetcher to use ray.wait() by default rather than the dummy prefetching actor:

Are you thinking by 2.2?

**Comment by cadedaniel** [comment]
Oh, is it literally just this line?

https://github.com/ray-project/ray/blob/47f8faa0f2389e6995b3cda6834adbbdac71316e/python/ray/data/context.py#L56

**Comment by clarkzinzow** [comment]
@cadedaniel I don't think that change needs to be cherry-picked for 2.2 since the actor prefetcher isn't a P0 source of instability or performance issues.

>Oh, is it literally just this line?

Yep, that's it!

**Comment by cadedaniel** [comment]
PTAL https://github.com/ray-project/ray/pull/30739

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -1260,20 +1260,11 @@ void RetryObjectInPlasmaErrors(std::shared_ptr<CoreWorkerMemoryStore> &memory_st
...
-      if (found.size() == 1 && found[0]->IsInPlasmaError()) {
-        plasma_object_ids.insert(mem_id);
-        ready.erase(ready_iter);
-        memory_object_ids.erase(current);
-      }
+    auto found = memory_store->GetIfExists(mem_id);
+    if (found != nullptr && found->IsInPlasmaError()) {
+      plasma_object_ids.insert(mem_id);
+      ready.erase(mem_id);
+      memory_object_ids.erase(current);
```
Comment (ericl) [inline src/ray/core_worker/core_worker.cc:1267]: It's unfortunate this is in core_worker.cc so we can't easily unit test it--- could be worth thinking a bit harder on how to test without an e2e test.

Shall we at least add a Python/integration test that covers this case somehow?

**Review by ericl — APPROVED** [review]
I'm ok with merging this if we cannot figure out a good non-e2e test.

**Comment by cadedaniel** [comment]
Ok, let's merge for now? We have EOD deadline to get cherry picks in.

I think for this particular change a C++ unit test can be written since the function appears pure. But it will take me longer than today to mock out the `CoreWorkerMemoryStore`.

**Comment by cadedaniel** [comment]
Also, if our goal towards Ray 3.0 is to have no regressions in code coverage %, then we'll need to meaningfully prioritize paying off tech debt to make code like this readably testable.

**Comment by clarkzinzow** [comment]
@cadedaniel Strongly agreed on the core worker needing to be made more unit-testable! I opened a somewhat out-of-date issue for this nearly 2 years ago, would love to see it happen: https://github.com/ray-project/ray/issues/13268

**Comment by cadedaniel** [comment]
@scv119 do we have a backlog I can use for ^? or some way to keep track of actionable tech debt reductions
