### PR TITLE
[xray] Try to flush children of a task that is evicted from the lineage cache

### LINKED ISSUE #2519: Lineage cache bug: uncommitted_ready_children_.count(task_id) == 0.
The bug occurs when using x-ray (e.g., starting Python with `RAY_USE_XRAY=1 ipython`) and running the following.

```python
import ray

@ray.remote
class Actor(object):
    def __init__(self):
        pass
    def step(self):
        return

@ray.remote
def foo(x):
    return

if __name__ == '__main__':
    ray.worker._init(use_raylet=True, num_local_schedulers=2, start_ray_local=True, redirect_output=False)

    actors = [Actor.remote() for _ in range(10)]
    for _ in range(10):
        for _ in range(100):
            for actor in actors:
                foo.remote(actor.step.remote())
```

This fails with

```
/home/ubuntu/ray/src/ray/raylet/lineage_cache.cc:380 Check failed: uncommitted_ready_children_.count(task_id) == 0
```

The check is too strong. Basically, when evicting a remote task from the lineage cache, it may still have "uncommitted ready" children (if those children have additional parents), so when we evict a task, we should see if that enables us to begin flushing any of its children.

cc @ujvl @ericl @stephanie-wang

### PR DESCRIPTION
**Pull request by stephanie-wang**
## What do these changes do?

This fixes a bug in the lineage cache where we assumed that evicted tasks did not have any children (i.e. dependent tasks) that could be flushed. This PR factors out the common code for evicting a task, which includes attempting to flush any children of the evicted task.

## Related issue number

Fixes #2519.

### CODE REVIEW

File: src/ray/raylet/lineage_cache.cc [hunk 1]
```diff
@@ -365,31 +365,57 @@ bool LineageCache::UnsubscribeTask(const UniqueID &task_id) {
...
+  auto children_entry = uncommitted_ready_children_.find(task_id);
+  if (children_entry != uncommitted_ready_children_.end()) {
+    // Get the children of the committed task that are uncommitted but ready.
+    auto children = std::move(children_entry->second);
+    uncommitted_ready_children_.erase(children_entry);
+
+    // Try to flush the children.  If all of the child's parents are committed,
+    // then the child will be flushed here.
+    for (const auto &child_id : children) {
+      bool flushed = FlushTask(child_id);
```
Comment (robertnishihara) [inline src/ray/raylet/lineage_cache.cc]: If `FlushTask` returns true, that means that we've begun the process of committing `child_id`, but it hasn't been successfully committed yet. So isn't it premature to remove `child_id` from `uncommitted_ready_tasks_`, since `uncommitted_ready_tasks_` is a mapping from all "tasks that haven't been committed yet", and `child_id` still isn't committed?

If not, then maybe the documentation for `uncommitted_ready_tasks_` and `FlushTask` should be clarified.

**Comment by shaneknapp** [comment]
test this please

File: src/ray/raylet/lineage_cache.cc (hunk 1 above)
Comment (robertnishihara) [reply src/ray/raylet/lineage_cache.cc]: I'd expect the erase to happen in `HandleEntryCommitted`

Comment (robertnishihara) [reply src/ray/raylet/lineage_cache.cc]: Ok I think I confused it with `uncommitted_ready_children_`

**Review by robertnishihara — APPROVED** [review]
