### PR TITLE
[core][gpu-objects] Fix the performance regression by clearing `object_ref` for small and non-GPU objects

### LINKED ISSUE #53623: [core][gpu-objects] Performance regression caused by transferring object references for small objects
### What happened + What you expected to happen

The GPU objects POC PR (https://github.com/ray-project/ray/pull/52938) causes a performance degradation because it passes ObjectRef for small objects.

* Before GPU objects POC PR, `mutable_arg->clear_object_ref();` will be called. After GPU objects POC PR, the whole object ref will be transferred which slow down a very niche [test stage2 in test_many_tasks.py](https://github.com/ray-project/ray/blob/0e53e1ddc84662adbffbddcb7e3ff5d845747838/release/nightly_tests/stress_tests/test_many_tasks.py#L77). (See https://github.com/ray-project/ray/pull/53575 for more details)
  * Before GPU objects POC PR: stage_2_time 168.2283821105957 seconds
  * After GPU objects POC PR: stage_2_time 287.988343000412 seconds

* Clear owner_address (https://github.com/ray-project/ray/pull/53590) to reduce the size of data transfer because we only need object id. 
  * `stage_2_time` = 198.5783519744873
 
Solution is to clear object ref if the object ref is not a GPU object ref.

### Versions / Dependencies

nightly

### Reproduction script

Trigger release tests with `name:stress_test_many_tasks.aws`

### Issue Severity

None

### PR DESCRIPTION
**Pull request by kevin85421**
## Why are these changes needed?

This PR is based on https://github.com/ray-project/ray/pull/53630.

See #53623 for the issue. In this PR, we clear the object ref when the arg's tensor transport is not OBJECT_STORE.

## Related issue number

Closes #53623 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
The regression was fixed.

https://buildkite.com/ray-project/release/builds/45142#019758ea-6d72-4590-a80c-d43a2ecaf2f2

```
success = 1
--
  | stage_0_time = 7.095437526702881
  | stage_1_time = 125.6585624217987
  | stage_1_avg_iteration_time = 12.565850567817687
  | stage_1_max_iteration_time = 12.910065412521362
  | stage_1_min_iteration_time = 11.427676439285278
  | stage_2_time = 168.93659591674805
  | stage_2_avg_iteration_time = 33.787201929092404
  | stage_2_max_iteration_time = 34.26388764381409
  | stage_2_min_iteration_time = 33.193145990371704
  | stage_3_creation_time = 1.903125524520874
  | stage_3_time = 1813.0130867958069
  | stage_4_spread = 0.7813597517227632
```

File: src/ray/core_worker/test/dependency_resolver_test.cc [hunk 1]
```diff
@@ -461,6 +488,56 @@ TEST(LocalDependencyResolverTest, TestDependenciesAlreadyLocal) {
   ASSERT_EQ(resolver.NumPendingTasks(), 0);
 }
 
+TEST(LocalDependencyResolverTest, TestMixedTensorTransport) {
```
Comment (kevin85421) [inline src/ray/core_worker/test/dependency_resolver_test.cc:491]: unit test for this PR

Comment (stephanie-wang) [reply src/ray/core_worker/test/dependency_resolver_test.cc:491]: Nice, thanks for adding this.

File: src/ray/core_worker/transport/dependency_resolver.cc [hunk 2]
```diff
@@ -39,7 +40,18 @@ void InlineDependencies(
         auto *mutable_arg = msg.mutable_args(i);
         if (!it->second->IsInPlasmaError()) {
           // The object has not been promoted to plasma. Inline the object by
-          // clearing the reference and replacing it with the raw value.
+          // replacing it with the raw value.
+          if (tensor_transport_getter(id) == rpc::TensorTransport::OBJECT_STORE) {
+            // Clear the object reference if the object is transferred via the object
+            // store. If we don't clear the object reference, it will have performance
+            // degradation in some edge cases.
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/dependency_resolver.cc]:
```suggestion
            // store. If we don't clear the object reference, tasks with a large number of arguments will experience performance
            // degradation due to higher serialization overhead.
```

Comment (stephanie-wang) [reply src/ray/core_worker/transport/dependency_resolver.cc]: (more specific)

**Review by stephanie-wang — APPROVED** [review]
