### PR TITLE
[Core] Fix the race condition where grpc requests are handled while core worker not yet initialized

### LINKED ISSUE #36829: [release-test] `placement_group_performance_test.aws` failed
https://console.anyscale-staging.com/o/anyscale-internal/jobs/prodjob_gnvzua6c5abyhb4q4cabeyl4v6

```
[INFO 2023-06-25 23:58:59,221] anyscale_job_wrapper.py: 175  Starting process 2179.
+ python placement_group_tests/placement_group_performance_test.py
2023-06-25 23:58:59,720 INFO worker.py:1309 -- Using address 10.0.36.202:6379 set in the environment variable RAY_ADDRESS
2023-06-25 23:58:59,720 INFO worker.py:1427 -- Connecting to existing Ray cluster at address: 10.0.36.202:6379...
2023-06-25 23:58:59,768 INFO worker.py:1608 -- Connected to Ray cluster. View the dashboard at https://session-8rinvlkmlvbd2zljycszbb2vfq.i.anyscaleuserdata-staging.com 
*** SIGSEGV received at time=1687762739 on cpu 13 ***
PC: @     0x7f90056875d0  (unknown)  absl::lts_20220623::Mutex::Lock()
    @     0x7f9006448420       3376  (unknown)
    @     0x7f9004e48bba        192  ray::core::CoreWorker::HandleNumPendingTasks()
    @     0x7f9004df6bd5        144  ray::rpc::ServerCallImpl<>::HandleRequestImpl()
    @     0x7f900511f4f6         80  EventTracker::RecordExecution()
    @     0x7f90050bc79e         48  std::_Function_handler<>::_M_invoke()
    @     0x7f90050bccf6        112  boost::asio::detail::completion_handler<>::do_complete()
    @     0x7f9005670d7b        128  boost::asio::detail::scheduler::do_run_one()
    @     0x7f9005672849        288  boost::asio::detail::scheduler::run()
    @     0x7f9005672d02         96  boost::asio::io_context::run()
    @     0x7f9004e48e2d        240  ray::core::CoreWorker::RunIOService()
    @     0x7f90056a3800  (unknown)  execute_native_thread_routine
    @          0x1b96fb0   69494744  (unknown)
    @     0x7f9004d86cb0  (unknown)  (unknown)
    @ 0x900091cb71e90789  (unknown)  (unknown)
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361: *** SIGSEGV received at time=1687762739 on cpu 13 ***
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361: PC: @     0x7f90056875d0  (unknown)  absl::lts_20220623::Mutex::Lock()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9006448420       3376  (unknown)
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9004e48bba        192  ray::core::CoreWorker::HandleNumPendingTasks()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9004df6bd5        144  ray::rpc::ServerCallImpl<>::HandleRequestImpl()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f900511f4f6         80  EventTracker::RecordExecution()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f90050bc79e         48  std::_Function_handler<>::_M_invoke()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f90050bccf6        112  boost::asio::detail::completion_handler<>::do_complete()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9005670d7b        128  boost::asio::detail::scheduler::do_run_one()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9005672849        288  boost::asio::detail::scheduler::run()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9005672d02         96  boost::asio::io_context::run()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f9004e48e2d        240  ray::core::CoreWorker::RunIOService()
[2023-06-25 23:58:59,845 E 2181 2228] logging.cc:361:     @     0x7f90056a3800  (unknown)  execute_native_thread_routine
[2023-06-25 23:58:59,846 E 2181 2228] logging.cc:361:     @          0x1b96fb0   69494744  (unknown)
[2023-06-25 23:58:59,850 E 2181 2228] logging.cc:361:     @     0x7f9004d86cb0  (unknown)  (unknown)
[2023-06-25 23:58:59,851 E 2181 2228] logging.cc:361:     @ 0x900091cb71e90789  (unknown)  (unknown)
Fatal Python error: Segmentation fault

/tmp/ray/session_2023-06-25_23-58-17_716277_50/runtime_resources/working_dir_files/s3_ray-release-automation-results_working_dirs_placement_group_performance_test_aws_bamaxwxxhc__anyscale_pkg_a3ae00d02caf5513b000a94bcaf7edec/workload.sh: line 1:  2181 Segmentation fault      (core dumped) python placement_group_tests/placement_group_performance_test.py
Subprocess return code: 139
```

It segment.

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

there is a race condition where grpc server start handling requests before the core worker is initialized. This PR fixes by waiting for initialization before handling any grpc request.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -611,6 +611,13 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
   // Verify driver and worker are never mixed in the same process.
   RAY_CHECK_EQ(options_.worker_type != WorkerType::DRIVER, niced);
 #endif
+
+  // Notify that core worker is initialized.
+  {
```
Comment (jjyao) [inline src/ray/core_worker/core_worker.cc:616]: Can we change the initialization order instead: only start grpc server or register grpc services until initialization is done, this way we don't need to add `WaitUntilInitialized` to each HandleXXX

Comment (scv119) [reply src/ray/core_worker/core_worker.cc:616]: tried to do that and turns out too hard, as we need to refactor a huge amount of initialization code. this mainly because that certains components need to get rpc_server's port address to start with, so we need to start rpc_server first.

Comment (jjyao) [reply src/ray/core_worker/core_worker.cc:616]: Do you know which part of the initialization needs to happen before handling grpc requests?

Comment (jjyao) [reply src/ray/core_worker/core_worker.cc:616]: Also do you know which rpc request is handled while core worker is not initialized? Ideally core worker shouldn't receive any requests until `local_raylet_client_->AnnounceWorkerPort(core_worker_server_->GetPort()));`, is it possible that we announce worker port too soon?

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -2867,6 +2874,7 @@ void CoreWorker::HandleReportGeneratorItemReturns(
     rpc::ReportGeneratorItemReturnsRequest request,
     rpc::ReportGeneratorItemReturnsReply *reply,
     rpc::SendReplyCallback send_reply_callback) {
+  WaitUntilInitialized();
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:2877]: Is there any way to modify a macro instead here? core_worker_server.h. Seems to be prone to error...

File: src/ray/core_worker/core_worker.cc [hunk 3]
```diff
@@ -611,6 +611,13 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
   // Verify driver and worker are never mixed in the same process.
   RAY_CHECK_EQ(options_.worker_type != WorkerType::DRIVER, niced);
 #endif
+
+  // Notify that core worker is initialized.
+  {
+    absl::MutexLock lock(&initialize_mutex_);
+    initialized_ = true;
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:618]: Should we have some timeout here to avoid infinite hang? Maybe sth like 30 seconds? (and we can probably check fail if it is not done on time?)

File: src/ray/core_worker/core_worker.cc (hunk 1 above)
Comment (rkooo567) [reply src/ray/core_worker/core_worker.cc:616]: I think the RPC comes from GCS. So we should defer `RegisterToGcs`

**Review by rkooo567 — COMMENTED** [review]
I think it'd be the best if we can fix by changing the initialization order as @jjyao said. But if not, I have comments for existing logics;

**Comment by scv119** [comment]
yes it's from GCS, let me defer that instead.

File: src/ray/core_worker/core_worker.cc (hunk 3 above)
Comment (scv119) [reply src/ray/core_worker/core_worker.cc]: moved this to a scope_guard to ensure it will eventually be called.

**Comment by scv119** [comment]
huh none of them seems easy. we should process with this.

**Comment by iycheng** [comment]
I'm OK with the solution but preferred with the other way like fixing the initialization. I'll leave it to @jjyao @rkooo567

**Review by rkooo567 — APPROVED** [review]
Looks great to me!

File: src/ray/rpc/server_call.h [hunk 4]
```diff
@@ -196,6 +209,9 @@ class ServerCallImpl : public ServerCall {
   }
 
   void HandleRequestImpl() {
+    if constexpr (std::is_base_of_v<DelayedServiceHandler, ServiceHandler>) {
```
Comment (scv119) [inline src/ray/rpc/server_call.h:212]: C++ is amazing
