### PR TITLE
Use subreaper to kill unowned subprocesses in raylet.

### LINKED ISSUE #42861: [core] subprocess leaks if Ray worker crashes
### What happened + What you expected to happen

If a Ray Worker process spawns another subprocess, then the worker dies, it tries to kill those subprocesses on graceful exit process. However if the worker is sigkill'd it does not have a chance to clean up and the subprocess leaks.

### Versions / Dependencies

master

### Reproduction script

```py
import ray

ray.init()


import multiprocessing
import time
import psutil
from pprint import pprint
import os

def sleep_forever():
    while True:
        time.sleep(10000)

def get_process_info(pid):
    try:
        process = psutil.Process(pid)
        return {
            "PID": process.pid,
            "Name": process.name(),
            "Status": process.status(),
            "CPU Times": process.cpu_times(),
            "Memory Info": process.memory_info(),
        }
    except psutil.NoSuchProcess:
        return f"No process found with PID: {pid}"
    except Exception as e:
        return f"Error: {e}"

@ray.remote
class BedMaker:
    def make_sleeper(self):
        p = multiprocessing.Process(target=sleep_forever)
        p.start()
        return p.pid
    def my_pid(self):
        return os.getpid()


def demo1():
    print("----------- demo1: ray.kill can kill subprocesses. ----------")
    b = BedMaker.remote()
    pid = ray.get(b.make_sleeper.remote())

    # ray.kill can kill subprocesses.
    pprint(get_process_info(pid)) # shows the process
    ray.kill(b)
    time.sleep(1)
    pprint(get_process_info(pid)) # shows not found

def demo2():
    print("----------- demo2: sigkill'd actor can't kill subprocesses. ----------")
    # sigkill'd actor can't kill subprocesses
    b = BedMaker.remote()
    pid = ray.get(b.make_sleeper.remote())
    actor_pid = ray.get( b.my_pid.remote())

    pprint(get_process_info(pid)) # shows the process
    psutil.Process(actor_pid).kill() # sigkill
    time.sleep(1)
    pprint(get_process_info(pid)) # shows the process

demo1()
demo2()
```
result:
```
----------- demo1: ray.kill can kill subprocesses. ----------
{'CPU Times': pcputimes(user=0.0, system=0.0, children_user=0.0, children_system=0.0, iowait=0.0),
 'Memory Info': pmem(rss=44326912, vms=42548969472, shared=2883584, text=2043904, lib=0, data=509145088, dirty=0),
 'Name': 'ray::BedMaker.make_sleeper',
 'PID': 7576,
 'Status': 'sleeping'}
'No process found with PID: 7576'
----------- demo2: sigkill'd actor can't kill subprocesses. ----------
{'CPU Times': pcputimes(user=0.0, system=0.0, children_user=0.0, children_system=0.0, iowait=0.0),
 'Memory Info': pmem(rss=44318720, vms=42548936704, shared=2883584, text=2043904, lib=0, data=509112320, dirty=0),
 'Name': 'ray::BedMaker.make_sleeper',
 'PID': 7685,
 'Status': 'sleeping'}
{'CPU Times': pcputimes(user=0.0, system=0.0, children_user=0.0, children_system=0.0, iowait=0.0),
 'Memory Info': pmem(rss=44318720, vms=42548936704, shared=2883584, text=2043904, lib=0, data=509112320, dirty=0),
 'Name': 'ray::BedMaker.make_sleeper',
 'PID': 7685,
 'Status': 'sleeping'}
```

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by rynewang**
Currently when user code spawns subprocess (from core worker), we don't have a good way to track them. We do best effort to kill direct child procs on core worker exit (#33976), but if a worker crashed (e.g. sigkill'd), or there are grandchild processes those processes leak. They may still hold valuable resources e.g. GPU memory.

This patches adds a feature to kill any recursive children from a core worker on its death. It's gated by a flag `RAY_kill_child_processes_on_worker_exit_with_raylet_subreaper` default disabled.

Once enabled:

- raylet as Linux subreaper.
- raylet tracks "known subprocesses" it spawned.
- raylet auto-kills unknown children every 10s.
- core worker as Linux subreaper, no auto-kills.

so that

- if a core worker is running, a (grand)child dies -> all other (grand)children keeps running
- if a core worker dies -> all (grand)children killed by raylet.

To avoid zombies, sets core worker to auto reap zombies by ignoring SIGCHLD. The raylet already reaps zombies, but now it also removes the dead children in the "known subprocesses".

Added a linux only unit test, and a doc page.

Fixes #42861, #26118

### CODE REVIEW

**Comment by rynewang** [comment]
removeOwnedChild needs a redo. Now we call it in ProcessFD dtor. However there are times we deallocate ProcessFD and does not track the process anymore, yet we don't want to kill it immediately either, e.g. when you spawn a one time util script. So we really need to track exit of those processes, i.e. in sigchld handler.

```
while (waitpid(&pid)) {
if pid in children {
    children.remove(pid)
  }
}
```

File: src/ray/util/process.cc [hunk 1]
```diff
@@ -242,21 +358,14 @@ class ProcessFD {
...
-      }
-    }
+    // Parent process case
     // Use pipe to track process lifetime. (The pipe closes when process terminates.)
     fd = pipefds[0];
     if (pid == -1) {
       ec = std::error_code(errno, std::system_category());
     }
 #endif
+    addOwnedChild(pid);
```
Comment (cadedaniel) [inline src/ray/util/process.cc:368]: You need a signal block between process creation and adding it to the owned set. Otherwise there is a race where the process dies before it is added to the owned set. I'll leave to you whether this is something that should be fixed now or not.

File: src/ray/util/process.cc [hunk 2]
```diff
@@ -242,21 +358,14 @@ class ProcessFD {
...
     return ProcessFD(pid, fd);
```
Comment (cadedaniel) [inline src/ray/util/process.cc:369]: seems the constructor is public, what happens if someone creates a process using another mechanism? tricky

File: src/ray/util/process.cc (hunk 1 above)
Comment (cadedaniel) [reply src/ray/util/process.cc:368]: (maybe boost magic solves this for you)

File: src/ray/util/process.cc [hunk 3]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+    int status;
+    pid_t pid;
+    while ((pid = waitpid(-1, &status, WNOHANG)) > 0) {
+      if (WIFEXITED(status)) {
+        RAY_LOG(INFO) << "Child process " << pid << " exited with status "
+                      << WEXITSTATUS(status);
+      } else if (WIFSIGNALED(status)) {
+        RAY_LOG(INFO) << "Child process " << pid << " exited from signal "
+                      << WTERMSIG(status);
+      }
```
Comment (cadedaniel) [inline src/ray/util/process.cc:117]: why do we need the notion of ownership at all? seems this will only run for dead child procs which need to be reaped anyways

**Comment by rkooo567** [comment]
I will review this by today!

**Review by rkooo567 — COMMENTED** [review]
Current status: it is not working yet. Waiting for it to work

**Comment by rynewang** [comment]
Updated, now the subreaper test works. i.e. if the worker is dead, its subprocesses are sigkilled.

**Comment by rynewang** [comment]
Note: 

1. we may not want a hard sigkill at first. We can do something like "sigterm, after 5s then sigkill".
2. I am wondering how waterproof is this approach. If we spawn a one time command (`bash start_something.sh`) which spawns a tool, will it be killed? Maybe we can bring back the "decouple" arg and only care about the "coupled" processes, i.e. workers.

File: src/ray/util/process.cc [hunk 4]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+// Only tracked in linux.
+//
+// A pid is added when a spawn is called and removed when the ProcessFD is closed (i.e.
+// it's in dtor and we no longer want to track it).
+std::mutex m;
+absl::flat_hash_set<pid_t> owned_children;
+
+void addOwnedChild(pid_t pid) {
+#ifdef __linux__
+  std::lock_guard<std::mutex> guard(m);
```
Comment (rkooo567) [inline src/ray/util/process.cc:82]: nit, but just use absl::MutexLock lock(&mutex_);? (we use this for locks)

File: src/ray/util/process.cc [hunk 5]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+                       << error->message();
+      }
+    }
+  }
+}
+
+// Set this process as a subreaper.
+void SetThisProcessAsSubreaper() {
+  if (prctl(PR_SET_CHILD_SUBREAPER, 1) == -1) {
+    perror("prctl");
```
Comment (rkooo567) [inline src/ray/util/process.cc:160]: Consider RAY_LOG(FATAL) here?

File: src/ray/util/process.cc [hunk 6]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+        RAY_LOG(ERROR) << "Failed to kill leaked child process " << pid << " with error "
+                       << error->message();
+      }
+    }
+  }
+}
+
+// Set this process as a subreaper.
+void SetThisProcessAsSubreaper() {
+  if (prctl(PR_SET_CHILD_SUBREAPER, 1) == -1) {
```
Comment (rkooo567) [inline src/ray/util/process.cc:159]: it is only available after linux 3.4. Do you know how old is this version? If it is not supported, does it mean it will just crash raylet?

File: src/ray/util/process.cc [hunk 7]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+
+// Register a signal handler for the given signal.
+// The handler will be called with the signal_set and the error code.
+// After the handler is called, the signal will be re-registered.
+void RegisterSignalHandlerLoop(boost::asio::signal_set &signals,
+                               void (*handler)(const boost::system::error_code &, int)) {
+  signals.async_wait(
+      [&signals, handler](const boost::system::error_code &error, int signal_number) {
+        handler(error, signal_number);
+        RegisterSignalHandlerLoop(signals, handler);
```
Comment (rkooo567) [inline src/ray/util/process.cc:102]: is it a normal practice? Is there other way to just register handler once that's called?

File: src/ray/util/process.cc [hunk 8]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+      });
+}
+
+void SigchldHandlerPlain(const boost::system::error_code &error, int signal_number) {
+  if (!error) {
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/util/process.cc:107]: +1. Can you comment here? Also it is no-op if it is an error. Is this the legit behavior?

File: src/ray/util/process.cc [hunk 9]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+    int status;
+    pid_t pid;
+    while ((pid = waitpid(-1, &status, WNOHANG)) > 0) {
```
Comment (rkooo567) [inline src/ray/util/process.cc:110]: this is blocking. Do we assume it is non-blocking because it is already dead when we get this signal? if so can you comment it here?

File: src/ray/util/process.cc [hunk 10]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+void RegisterSignalHandlerLoop(boost::asio::signal_set &signals,
+                               void (*handler)(const boost::system::error_code &, int)) {
+  signals.async_wait(
+      [&signals, handler](const boost::system::error_code &error, int signal_number) {
+        handler(error, signal_number);
+        RegisterSignalHandlerLoop(signals, handler);
+      });
+}
+
+void SigchldHandlerPlain(const boost::system::error_code &error, int signal_number) {
```
Comment (rkooo567) [inline src/ray/util/process.cc:106]: Is it possible for owned children (the workers), we just handle it in the same way as before? I think it is probably unnecessary change for this PR?

File: src/ray/util/process.cc [hunk 11]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+      }
+      removeOwnedChild(pid);
+    }
+  }
+}
+
+#ifdef __linux__
+
+void KillUnownedChildren() {
+  auto maybe_child_procs = GetAllProcsWithPpid(GetPID());
```
Comment (rkooo567) [inline src/ray/util/process.cc:126]: how slow is this?

File: src/ray/util/process.cc [hunk 12]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+
+  // Enumerating child procs is not supported on this platform.
+  if (!maybe_child_procs) {
+    RAY_LOG(WARNING)
```
Comment (rkooo567) [inline src/ray/util/process.cc:130]: maybe this should just exit here and we shouldn't even start this function if it is not linux

File: src/ray/util/process.cc [hunk 13]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+        << "Killing leaked procs not supported on this platform. Only supports Linux";
+    return;
+  }
+
+  std::vector<pid_t> to_kill;
+  to_kill.reserve(maybe_child_procs->size());
+  {
+    std::lock_guard<std::mutex> guard(m);
```
Comment (rkooo567) [inline src/ray/util/process.cc:138]: why do we need a lock btw? is it happening in a different thread?

File: src/ray/util/process.cc [hunk 14]
```diff
@@ -63,6 +68,123 @@ int execvpe(const char *program, char *const argv[], char *const envp[]) {
...
+        to_kill.push_back(pid);
+      }
+    }
+  }
+  for (auto pid : to_kill) {
+    if (owned_children.count(pid) == 0) {
+      RAY_LOG(INFO) << "Killing leaked child process " << pid;
+      auto error = KillProc(pid);
+      if (error) {
+        RAY_LOG(ERROR) << "Failed to kill leaked child process " << pid << " with error "
```
Comment (rkooo567) [inline src/ray/util/process.cc:150]: Use WARNING here. ERROR will be printed to the user driver.

**Review by rkooo567 — COMMENTED** [review]
In general, it lgtm. But I feel like we don't need SigchldHandlerPlain for this PR? I think it is the best we only handle killing unowned children in this PR, and replace stdin read -> wait on child procs in another PR. wait on child procs will also improve observabiilty.

> we may not want a hard sigkill at first. We can do something like "sigterm, after 5s then sigkill".

SGTM

> I am wondering how waterproof is this approach. If we spawn a one time command (bash start_something.sh) which spawns a tool, will it be killed? Maybe we can bring back the "decouple" arg and only care about the "coupled" processes, i.e. workers.

Do we ever do this from raylet though? Besides, agreed to keep decouple here.

**Comment by rkooo567** [comment]
Btw, can we accelerate the progress of this PR as the branch cut is coming? We'd like to merge this by this week to meet 2/29

File: src/ray/util/process.cc (hunk 6 above)
Comment (rynewang) [reply src/ray/util/process.cc:150]: Linux 3.4 is released in 2012. As a comparison: ubuntu 18.04 is on linux 5.4. So we should be safe.

File: src/ray/util/process.cc (hunk 11 above)
Comment (rynewang) [reply src/ray/util/process.cc:116]: 1 file read per process in the current linux. so not very fast. Fortunately we are not blocking anything here.

File: src/ray/util/process.cc (hunk 13 above)
Comment (rynewang) [reply src/ray/util/process.cc:128]: if 1 thread is spawning a child process, while another thread is gathering this owned children list.

**Comment by rkooo567** [comment]
Q: all comments ^ are addressed? Also, there seems to be some premerge failures

**Comment by rynewang** [comment]
# addressed 

> decouple

Intention of the decouple was to make the spawned process be reparented to 1 (init), however if we have subreaper the double forked subprocess will be reparented to raylet so it won't work.

> how we track child process' health

Yes I'm keeping it

> Only handle sigchld for unowned children

sigchld actually is triggered from the direct children death and we need to take care of all children deaths, which we do via `waitpid`. For the killing, yes we kill onowned children only.

> We can remove owned children pid when a worker is killed (there must be some sort of hook here)

Right, we remove owned children in `waitpid` where Linux tells us the child is gone.

> Make sure things are logged properly with pid with INFO.

Yes we have the logs on child exited and child killed.


> Probably we can remove parent core worker killing child workers and convert it to this mechanism?

Maybe. but let's at least keep it in this PR.

# Not addressed 

> The behavior should be clearly specified from core doc.

ok, will write doc in this PR

> premerge

It's strange, can't repro on my linux devbox. will fix

File: src/ray/raylet/worker_pool.cc [hunk 15]
```diff
@@ -113,11 +113,7 @@ WorkerPool::WorkerPool(instrumented_io_context &io_service,
   stats::NumCachedWorkersSkippedJobMismatch.Record(0);
   stats::NumCachedWorkersSkippedDynamicOptionsMismatch.Record(0);
   stats::NumCachedWorkersSkippedRuntimeEnvironmentMismatch.Record(0);
-#ifndef _WIN32
-  // Ignore SIGCHLD signals. If we don't do this, then worker processes will
-  // become zombies instead of dying gracefully.
-  signal(SIGCHLD, SIG_IGN);
-#endif
+  // No need to treat SIGCHLD as it's handled in raylet main.cc.
```
[the remark this answers is not in the document]
Comment (rynewang) [reply src/ray/raylet/worker_pool.cc:116]: we added it in subreaper.cc when the flag was disabled https://github.com/ray-project/ray/pull/42992/files#diff-b0a94cc61107f7633adfcda0a86e9472617b35b4931b182fab82785e0d4a81ebR138

File: doc/source/ray-core/user-spawn-processes.rst [hunk 16]
```diff
@@ -0,0 +1,118 @@
+Lifetimes of a User-Spawn Process
+=================================
+
+This document describes the lifecycle of a user-spawned process in Ray. A user-spawned process is a process that is started by a user and not by Ray.
+
+On Linux by default (controlled by the environment variable `RAY_kill_child_processes_on_worker_exit`), the lifetime of a user-spawned process is tied to the lifetime of the parent Ray worker process. When the parent Ray worker process dies, that is, after a task finishes or an actor is killed, all of its child processes are killed as well.
```
[the remark this answers is not in the document]
Comment (rkooo567) [reply doc/source/ray-core/user-spawn-processes.rst:6]: I think it is killed only when worker is killed.

File: doc/source/ray-core/user-spawn-processes.rst [hunk 17]
```diff
@@ -0,0 +1,118 @@
...
+
+The feature is supported on Linux 3.4 or newer. On other platforms, the flag is ignored, and the user is responsible for managing the lifetime of the child processes. If the parent Ray worker process dies, the child processes will continue to run, as if the flag is always disabled.
+
+If user uses Linux < 3.4, the flag is not present and the Raylet crashes. The user can upgrade the kernel to use this feature, or disable the feature by setting the environment variable ``RAY_kill_child_processes_on_worker_exit`` to ``false``.
+
+
+⚠️ CAVEAT: daemon user processes may be killed
+---------------------------------------------
+
+Note that, if a user process exits, all its subprocess are killed immediately. For example if user spawns a "launcher" process which spawns a "daemon" process, and then the launcher exits, the daemon is killed immediately, even if the **Ray task or actor is still alive**.
```
Comment (rkooo567) [inline doc/source/ray-core/user-spawn-processes.rst:67]: Hmm this is trickyl... is it because daemon is reparented?

File: src/ray/util/subreaper.cc [hunk 18]
```diff
@@ -0,0 +1,235 @@
...
+// T=0: raylet -> child -> grandchild
+// T=1: child receives SIGKILL. grandchild becomes an orphan and is reparented.
+// T=2: raylet -> child (zombie); raylet -> grandchild
+// T=3: raylet receives SIGCHLD for child
+// T=4: raylet reaps child, and finds grandchild is unowned child, killing it.
+//
+// CAVEAT: We may accidentally kill innocent subprocesses, if the direct child process
+// proposefully creates a grandchild process and exits. We need good test and audit to
+// make sure this doesn't happen.
+void SigchldHandlerKillOrphanSubprocesses(const boost::system::error_code &error,
```
Comment (rkooo567) [inline src/ray/util/subreaper.cc:104]: should we do this in sigchld? I feel like it is more robust & simple to just do it in a timer? (basically keep checking all unowned children and kill it?)

**Review by rkooo567 — COMMENTED** [review]
We should make sure to run MacOS test before merging.

Also, it is probably better making it "off by default" for 2.10 since it can have some regressions. 

Regarding implementation;
I feel like it is much simpler we just use timer-based approach? Basically,
1. add pid when a new proc starts
2. remove pid when it dies 
3. have a loop that checks all children every 10 seconds

IIUC, the current approach can have leak in the following scenario as well?

raylet -> child -> grandchild
T1: child dies
T2: sigchild received
T3: grandchild reparented to raylet

This will leak until a new proc starts and be killed?

File: doc/source/ray-core/user-spawn-processes.rst (hunk 16 above)
[the remark this answers is not in the document]
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:6]: yeah it's not "task finishes" but the core worker exited. Rewording

**Comment by rkooo567** [comment]
Lmk when it is ready again. Per private discussion
- we will make both raylet and worker subreaper
- this means granchildren can be zomebie in some circumstances. we should document this well
- off by default
- timer based approach

**Comment by rynewang** [comment]
In spirit of not breaking anything, set the flag to default=false and added back `decouple`.

**Comment by rkooo567** [comment]
please remove the label when it is ready to review again! I will take a look asap

**Comment by rynewang** [comment]
Only failure is a linkcheck which is in rllib, not relevant. Should be ok now.

File: doc/source/ray-core/user-spawn-processes.rst [hunk 19]
```diff
@@ -0,0 +1,106 @@
...
+
+- ``RAY_kill_child_processes_on_worker_exit_with_raylet_subreaper`` (default ``false``): Only works on Linux greater than or equal to 3.4. If true, Raylet kills any subprocesses that were spawned by the core worker after the core worker exits. This works even if the core worker crashed or was killed by a signal. Even if a process is created as a daemon, e.g. double forked, it will still be killed by this mechanism. The killing happens within 10 seconds after the core worker death.
+
+Both killings happen recursively, meaning if the core worker spawns user process A, then user process A spawns user process B, on core worker exit (or crash) both A and B are killed.
+
+On non-Linux platforms, user-spawned process is not controlled by Ray. The user is responsible for managing the lifetime of the child processes. If the parent Ray worker process dies, the child processes will continue to run.
+
+
```
Comment (jjyao) [inline doc/source/ray-core/user-spawn-processes.rst:16]: What we provide is more like a last resort. We should mention that ideally child processes should catch the death of the parent and self-exit so this feature doesn't need to be turned on.

File: doc/source/ray-core/user-spawn-processes.rst [hunk 20]
```diff
@@ -0,0 +1,106 @@
+Lifetimes of a User-Spawn Process
+=================================
+
+To avoid leaking user-spawned processes, Ray provides mechanisms to kill all user-spawned processes when a worker that starts it exits. This feature prevents GPU memory leaks from child processes (e.g., torch).
+
+We have 2 environment variables to handle subprocess killing on core worker exit:
+
+- ``RAY_kill_child_processes_on_worker_exit`` (default ``true``): Only works on Linux. If true, core worker kills all subprocesses on exit. This won't work if the core worker crashed or was killed by a signal. If a process is created as a daemon, e.g. double forked, it will not be killed by this mechanism.
+
+- ``RAY_kill_child_processes_on_worker_exit_with_raylet_subreaper`` (default ``false``): Only works on Linux greater than or equal to 3.4. If true, Raylet kills any subprocesses that were spawned by the core worker after the core worker exits. This works even if the core worker crashed or was killed by a signal. Even if a process is created as a daemon, e.g. double forked, it will still be killed by this mechanism. The killing happens within 10 seconds after the core worker death.
```
Comment (jjyao) [inline doc/source/ray-core/user-spawn-processes.rst:10]: What's the plan to turn this on by default and remove the other one?

File: doc/source/ray-core/user-spawn-processes.rst [hunk 21]
```diff
@@ -0,0 +1,106 @@
...
+  RAY_kill_child_processes_on_worker_exit_with_raylet_subreaper=true ray start --head
+
+Another way is to enable it during ``ray.init()`` by adding a ``_system_config`` like this:
+
+.. code-block::
+
+  ray.init(_system_config={"kill_child_processes_on_worker_exit_with_raylet_subreaper":True})
+
+
+⚠️ Caution: Core worker needs to reap zombies
```
Comment (jjyao) [inline doc/source/ray-core/user-spawn-processes.rst:76]: Is it more of an issue if the core work is long live since otherwise they will be killed by raylet.

Comment (rkooo567) [reply doc/source/ray-core/user-spawn-processes.rst:76]: yes, long running driver for example

File: doc/source/ray-core/user-spawn-processes.rst [hunk 22]
```diff
@@ -0,0 +1,106 @@
+Lifetimes of a User-Spawn Process
+=================================
+
+To avoid leaking user-spawned processes, Ray provides mechanisms to kill all user-spawned processes when a worker that starts it exits. This feature prevents GPU memory leaks from child processes (e.g., torch).
+
+We have 2 environment variables to handle subprocess killing on core worker exit:
+
+- ``RAY_kill_child_processes_on_worker_exit`` (default ``true``): Only works on Linux. If true, core worker kills all subprocesses on exit. This won't work if the core worker crashed or was killed by a signal. If a process is created as a daemon, e.g. double forked, it will not be killed by this mechanism.
```
Comment (rkooo567) [inline doc/source/ray-core/user-spawn-processes.rst:8]: > e.g. double forked, it will not be killed by this mechanism.

I don't think people can understand this. Either remove it or add more details?

File: doc/source/ray-core/user-spawn-processes.rst [hunk 23]
```diff
@@ -0,0 +1,106 @@
+Lifetimes of a User-Spawn Process
+=================================
+
+To avoid leaking user-spawned processes, Ray provides mechanisms to kill all user-spawned processes when a worker that starts it exits. This feature prevents GPU memory leaks from child processes (e.g., torch).
```
Comment (rkooo567) [inline doc/source/ray-core/user-spawn-processes.rst:4]: Let's improve this a bit. 

When you spawns child processes from Ray workers, you are responsible for managing the lifetime of child processes. However, it is not always possible, especially when worker crashes and child processes are spawned from libraries (torch dataloader).

To avoid leak...

File: doc/source/ray-core/user-spawn-processes.rst [hunk 24]
```diff
@@ -0,0 +1,106 @@
...
+
+  ray.init(_system_config={"kill_child_processes_on_worker_exit_with_raylet_subreaper":True})
+
+
+⚠️ Caution: Core worker needs to reap zombies
+----------------------------------------------
+
+When the feature is enabled, the core worker process becomes a subreaper (see the next section), meaning there can be some grandchildren processes that are reparented to the core worker process. If these processes exit, core worker needs to reap them to avoid zombies, even though they are not spawn by core worker. If core worker does not reap them, the zombies will accumulate and eventually cause the system to run out of resources like memory.
+
+You can add this code to the Ray Actors or Tasks to reap zombies, if you choose to enable the feature:
```
Comment (rkooo567) [inline doc/source/ray-core/user-spawn-processes.rst:81]: is this tested? can you add a test?

File: doc/source/ray-core/user-spawn-processes.rst [hunk 25]
```diff
@@ -0,0 +1,106 @@
...
+
+.. code-block::
+
+  ray.init(_system_config={"kill_child_processes_on_worker_exit_with_raylet_subreaper":True})
+
+
+⚠️ Caution: Core worker needs to reap zombies
+----------------------------------------------
+
+When the feature is enabled, the core worker process becomes a subreaper (see the next section), meaning there can be some grandchildren processes that are reparented to the core worker process. If these processes exit, core worker needs to reap them to avoid zombies, even though they are not spawn by core worker. If core worker does not reap them, the zombies will accumulate and eventually cause the system to run out of resources like memory.
```
Comment (rkooo567) [inline doc/source/ray-core/user-spawn-processes.rst:79]: We should not mention "core worker". It should be just "worker"

File: python/ray/tests/test_kill_subprocesses.py [hunk 26]
```diff
@@ -0,0 +1,122 @@
...
+    time.sleep(11)  # unowned processes are killed every 10s.
+    with pytest.raises(psutil.NoSuchProcess):
+        logger.info(get_process_info(pid))  # subprocess killed
+
+
+@pytest.mark.skipif(
+    sys.platform != "linux",
+    reason="Orphan process killing only works on Linux.",
+)
+def test_daemon_processes_not_killed_until_actor_dead(enable_subreaper, shutdown_only):
```
Comment (rkooo567) [inline python/ray/tests/test_kill_subprocesses.py:103]: Can you add a test where adding signal can reap grandchildren?

File: src/ray/util/subreaper.h [hunk 27]
```diff
@@ -0,0 +1,126 @@
...
+#endif
+
+namespace ray {
+
+#ifdef __linux__
+// Utility functions to enable subreaper functionality in Linux.
+//
+// In Ray, raylet creates core_worker processes, which may create grandchild processes.
+// If core_worker exits normally it tries to kill all its children recursively. However
+// if core_worker is killed by a signal, its children leak and still occupy resources.
```
Comment (rkooo567) [inline src/ray/util/subreaper.h:36]:
```suggestion
// if core_worker is crashed unexpectedly, its children leak and still occupy resources.
```

If signal is sigterm, it doesn't leak

File: src/ray/util/subreaper.h [hunk 28]
```diff
@@ -0,0 +1,126 @@
...
+// raylet (subreaper, killing unknown children)
+//  -> core_worker (subreaper, don't kill children until exiting)
+//  -> user process
+//  -> grandchild process
+//
+// If core_worker is alive and user process exited, grandchild is reparented to
+// core_worker. In this case core_worker will do nothing, because the grandchild may be
+// a daemon process.
+//
+// If core_worker crashed, user process is reparented to raylet. Raylet kills all unknown
```
Comment (rkooo567) [inline src/ray/util/subreaper.h:59]: nice description!

File: src/ray/util/subreaper.h [hunk 29]
```diff
@@ -0,0 +1,126 @@
...
+// Kill all unknown children. Lists all processes with pid = this process, and filters
+// out the known children, that is, processes created via `Process::spawnvpe`.
+//
+// Should be called by raylet only.
+//
+// Note: this function is one-time. Raylet should call it periodically.
+void KillUnknownChildren();
+
+// Thread-safe tracker for owned children. Provides transactional interfaces for creating
+// children and listing children. Only works in Linux.
```
Comment (rkooo567) [inline src/ray/util/subreaper.h:77]: nit; but we don't need to mention it only works on linux (it is already inside linux def)

File: src/ray/util/subreaper.h [hunk 30]
```diff
@@ -0,0 +1,126 @@
...
+// enabled, it's not tracking anything and is a no-op for each method.
+class KnownChildrenTracker {
+ public:
+  static KnownChildrenTracker &instance() {
+    static KnownChildrenTracker instance;
+    return instance;
+  }
+
+  // Used in initialization to enable the tracker. NOT thread safe.
+  void Enable() { enabled_ = true; }
```
Comment (rkooo567) [inline src/ray/util/subreaper.h:88]: Q: do we need enable? isn't this something we can always use?

File: src/ray/util/subreaper.cc [hunk 31]
```diff
@@ -0,0 +1,177 @@
...
+// Linux implementation.
+
+namespace {
+
+using SignalHandlerFn = void (*)(const boost::system::error_code &, int);
+// Register a signal handler for the given signal.
+// The handler will be called with the signal_set and the error code.
+// After the handler is called, the signal will be re-registered.
+// The callback keeps a reference of the shared ptr to make sure it's not destroyed.
+void RegisterSignalHandlerLoop(std::shared_ptr<boost::asio::signal_set> signals,
```
Comment (rkooo567) [inline src/ray/util/subreaper.cc:45]: is this necessary? no better API from asio that does this automatically?

File: src/ray/util/subreaper.cc [hunk 32]
```diff
@@ -0,0 +1,177 @@
...
+void SigchldHandlerReapZombieAndRemoveKnownChildren(
+    const boost::system::error_code &error, int signal_number) {
+  if (error) {
+    RAY_LOG(WARNING) << "Error in SIGCHLD handler: " << error.message();
+  }
+  int status;
+  pid_t pid;
+  // Reaps any children that have exited. WNOHANG makes waitpid non-blocking and returns
+  // 0 if there's no zombie children.
+  while ((pid = waitpid(-1, &status, WNOHANG)) > 0) {
```
Comment (rkooo567) [inline src/ray/util/subreaper.cc:63]: this should be non-blocking right? (since proc should have already dead)

File: src/ray/util/subreaper.cc [hunk 33]
```diff
@@ -0,0 +1,177 @@
...
+      [signals, handler](const boost::system::error_code &error, int signal_number) {
+        handler(error, signal_number);
+        RegisterSignalHandlerLoop(signals, handler);
+      });
+}
+
+void SigchldHandlerReapZombieAndRemoveKnownChildren(
+    const boost::system::error_code &error, int signal_number) {
+  if (error) {
+    RAY_LOG(WARNING) << "Error in SIGCHLD handler: " << error.message();
```
Comment (rkooo567) [inline src/ray/util/subreaper.cc:57]: should we just return here? what kind of error can happen?

File: src/ray/util/subreaper.cc [hunk 34]
```diff
@@ -0,0 +1,177 @@
...
+}
+
+// Kill all child processes that are not owned by this process.
+// It's done by checking the list of child processes and killing the ones that are not
+// created via Process::spawnvpe.
+//
+// TODO: Checking PIDs is not 100% reliable because of PID recycling. If we find issues
+// later due to this, we can use pidfd.
+void KillUnknownChildren() {
+  auto to_kill =
```
Comment (rkooo567) [inline src/ray/util/subreaper.cc:104]: Q: Is this automatically optimized by compiler?

File: src/ray/util/subreaper.cc [hunk 35]
```diff
@@ -0,0 +1,177 @@
...
+    }
+  }
+}
+
+void KnownChildrenTracker::AddKnownChild(std::function<pid_t()> create_child_fn) {
+  if (!enabled_) {
+    create_child_fn();
+    return;
+  }
+  absl::MutexLock lock(&m_);
```
Comment (rkooo567) [inline src/ray/util/subreaper.cc:129]: we don't need a lock when we create a child proc? 

```
pid_t pid = create_child_fn();
absl::MutexLock lock(&m_);
children_.insert(pid);
```

**Review by rkooo567 — COMMENTED** [review]
Generally LGTM! 

PR description still relevant? can you update it?

File: doc/source/ray-core/user-spawn-processes.rst (hunk 21 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:76]: I can reverse the default on core worker: it defaults to reap all zombies, and if users want to call `waitpid` they can set the signal handler to default (no waiting).

File: src/ray/util/subreaper.cc (hunk 32 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:63]: Non-blocking, yes. It's controlled by the WNOHANG. If there's no child dead already, it returns -1

File: src/ray/util/subreaper.cc (hunk 33 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:57]: The only error is "signal set cancelled" as `boost::asio::error::operation_aborted` but we won't ever cancel it.

https://www.boost.org/doc/libs/1_84_0/doc/html/boost_asio/reference/basic_signal_set/async_wait.html

It does not hurt to waitpid anyway.

File: src/ray/util/subreaper.cc (hunk 35 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:129]: We don't want the creation of a pid (in procfs) happen when we are reading the procfs for pids, I assume

File: src/ray/util/subreaper.h (hunk 30 above)
Comment (rynewang) [reply src/ray/util/subreaper.h:88]: this is used to allow we don't do anything if the flag is not turned on. i.e. with enabled_ = false we don't track the pids, nor do we lock.

File: src/ray/util/subreaper.h (hunk 29 above)
Comment (rynewang) [reply src/ray/util/subreaper.h:77]: done

File: src/ray/util/subreaper.cc (hunk 34 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:104]: I think it can do guaranteed copy elision but not 100% sure

File: doc/source/ray-core/user-spawn-processes.rst (hunk 23 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:4]: done

File: doc/source/ray-core/user-spawn-processes.rst (hunk 22 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:8]: changed to "grandchild processes" which should be more understandable.

File: doc/source/ray-core/user-spawn-processes.rst (hunk 19 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:16]: Since I reversed the default sigchld handler in core worker to reap-all-dead, users need to toggle it back to really do the signal handling. See the new `⚠️ Caution` section.

File: python/ray/tests/test_kill_subprocesses.py (hunk 26 above)
Comment (rynewang) [reply python/ray/tests/test_kill_subprocesses.py:103]: no need, reversed to core worker to default-reap all children.

File: doc/source/ray-core/user-spawn-processes.rst (hunk 25 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:79]: renamed all `core worker` to `the worker`

File: src/ray/core_worker/core_worker.cc [hunk 36]
```diff
@@ -131,6 +132,24 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
...
   RAY_LOG(DEBUG) << "Constructing CoreWorker, worker_id: " << worker_id;
 
+  if (RayConfig::instance().kill_child_processes_on_worker_exit_with_raylet_subreaper()) {
+#ifdef __linux__
+    // Not setting sigchld = ignore: user may want to do waitpid on their own.
+    // If user's bad code causes a zombie process, it will hang their in zombie status
+    // until this worker exits and raylet reaps it.
+    if (SetThisProcessAsSubreaper()) {
+      RAY_LOG(INFO) << "Set this core_worker process as subreaper: " << getpid();
+    } else {
```
Comment (fishbone) [inline src/ray/core_worker/core_worker.cc:142]: When `kill_child_processes_on_worker_exit_with_raylet_subreaper` is set, why do we still need to set the core worker ? The raylet should just work as the reaper I think?

File: doc/source/ray-core/user-spawn-processes.rst (hunk 24 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:81]: added.

File: src/ray/core_worker/core_worker.cc (hunk 36 above)
Comment (rynewang) [reply src/ray/core_worker/core_worker.cc:143]: See https://github.com/ray-project/ray/pull/42992/files#diff-f6c49babcc6278c29b15f311f28011254c7e7d20a0ff06b03a1ac17a6fe352bbR103

tldr: if a child of core worker spawns a grandchild and dies, the grandchild is reparented to the nearest subreaper. But we don't want it to be killed (since the core worker is still alive), so we set the core worker as a subreaper as well to avoid it be noticed and killed by raylet.

File: src/ray/util/subreaper.cc (hunk 35 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:129]: e.g. if 2 racing threads:

1. create process
    a. then add pid to the known list
3. kill unknown children

If the order is `1 -> 3 -> a`, the new process is killed which is not what we want. We have to make `1` and `a` be atomic on the list.

File: src/ray/util/subreaper.cc [hunk 37]
```diff
@@ -0,0 +1,177 @@
...
+
+// Kill all child processes that are not owned by this process.
+// It's done by checking the list of child processes and killing the ones that are not
+// created via Process::spawnvpe.
+//
+// TODO: Checking PIDs is not 100% reliable because of PID recycling. If we find issues
+// later due to this, we can use pidfd.
+void KillUnknownChildren() {
+  auto to_kill =
+      KnownChildrenTracker::instance().ListUnknownChildren([]() -> std::vector<pid_t> {
```
Comment (fishbone) [inline src/ray/util/subreaper.cc:105]: Why do we pass the lambda to the function instead of just move the lambda to the function body?

File: src/ray/raylet/main.cc [hunk 38]
```diff
@@ -193,13 +195,51 @@ int main(int argc, char *argv[]) {
   RAY_CHECK_OK(gcs_client->Connect(main_service, cluster_id));
   std::unique_ptr<ray::raylet::Raylet> raylet;
 
+  // Enable subreaper. This is called in `AsyncGetInternalConfig` below, but MSVC does
+  // not allow a macro invocation (#ifdef) in another macro invocation (RAY_CHECK_OK),
+  // so we have to put it here.
+  auto enable_subreaper = [&]() {
+#ifdef __linux__
```
Comment (fishbone) [inline src/ray/raylet/main.cc:202]: This probably is not an issue. Maybe we can put the __linux__ into the SetThisProcessAsSubreaper. 

For the platform specific code, the lower level we put it, the better.

**Review by fishbone — COMMENTED** [review]
Overall it looks good. 

Question is that, should we just turn it on by default? At least let raylet be the reaper?

The lifecycle of subprocess now becomes complicated, in different cases, the behavior is different.

IMO, if we just turned it on by default for most cases, and let the user know this might be better. Some special flag in remote options to turn it off for corner cases.

**Comment by rkooo567** [comment]
@fishbone we will turn it on by default. It is off because it is merged in the last minute and a bit of breaking change.

File: src/ray/util/subreaper.cc (hunk 33 above)
Comment (rkooo567) [reply src/ray/util/subreaper.cc:57]: Hmm I think the problem is waitpid is blocking, so if the operation is cancelled (I believe which means it can be called when a child is not dead yet), it can block raylet thread?

Comment (rkooo567) [reply src/ray/util/subreaper.cc:57]: can you comment in code? Also comment in the waitpid that it is non blocking (so although it is due to abort, it is okay)

File: src/ray/util/subreaper.h (hunk 30 above)
Comment (rkooo567) [reply src/ray/util/subreaper.h:87]: I feel like we can just always track here, but it is simple anyway. Will leave it up to you

File: python/ray/tests/test_kill_subprocesses.py (hunk 26 above)
Comment (rkooo567) [reply python/ray/tests/test_kill_subprocesses.py:102]: got it! please make sure you added a test case for reap. (and document how to diable automatic reap)

File: doc/source/ray-core/user-spawn-processes.rst (hunk 24 above)
Comment (rkooo567) [reply doc/source/ray-core/user-spawn-processes.rst]: so it is the default behavior now right? Can you add info here?

**Review by rkooo567 — APPROVED** [review]
LGTM if tests pass. Let's make sure the core worker reaping grand children is the default behavior

**Comment by rkooo567** [comment]
also before merge, let's make sure to run mac test/window test/release test

File: doc/source/ray-core/user-spawn-processes.rst (hunk 19 above)
Comment (jjyao) [reply doc/source/ray-core/user-spawn-processes.rst:17]: Oh, I mean not the signal handle on the parent side but on the child side: https://stackoverflow.com/questions/284325/how-to-make-child-process-die-after-parent-exits.

File: doc/source/ray-core/user-spawn-processes.rst (hunk 20 above)
Comment (jjyao) [reply doc/source/ray-core/user-spawn-processes.rst]: I mean removing the other `RAY_kill_child_processes_on_worker_exit` flag and the related code since we don't need two cleanup mechanisms.

File: src/ray/util/subreaper.cc (hunk 33 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:57]: added comments for the error and WNOHANG.

File: src/ray/util/subreaper.cc (hunk 35 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:129]: see the race condition I gave: if a killing happens between `create()` and `addknownchild` it may kill the newborn child process.

File: src/ray/util/subreaper.cc (hunk 37 above)
Comment (rynewang) [reply src/ray/util/subreaper.cc:105]: This is to ensure the `KnownChildrenTracker` only cares about the lock on the hash set, and it separates from the children finding code.

File: doc/source/ray-core/user-spawn-processes.rst (hunk 19 above)
Comment (rynewang) [reply doc/source/ray-core/user-spawn-processes.rst:17]: Understood. Added Note in the last section in the intro.

File: src/ray/core_worker/core_worker.cc (hunk 36 above)
Comment (fishbone) [reply src/ray/core_worker/core_worker.cc:143]: Hmm, let me know if I understand it correctly:

- if the core worker is dead => the grand child reparented to the raylet
- if the raylet is dead => the core worker is still alive => later it'll kill itself => before it exits, it'll kill all the children?

File: src/ray/util/subreaper.cc (hunk 37 above)
Comment (fishbone) [reply src/ray/util/subreaper.cc:105]: Hmm, I doubt the separation making things simpler, but I'm fine with it.

File: src/ray/core_worker/core_worker.cc (hunk 36 above)
Comment (rynewang) [reply src/ray/core_worker/core_worker.cc:143]: it handles this case:

raylet -> core worker -> A -> B

then

A exited, we don't want to kill B.

Now, B is reparented to core worker who does NOT kill B, so it's good. If we don't do that, B'd be reparented to raylet and be killed, which is what we don't want

Comment (fishbone) [reply src/ray/core_worker/core_worker.cc:143]: Thanks!

**Review by fishbone — APPROVED** [review]

**Review by matthewdeng — APPROVED** [review]

**Comment by jjyao** [comment]
I'll merge this for now. @angelinalg could you still review the doc related changes and we will address comments in the follow up PR.

File: src/ray/core_worker/core_worker.cc [hunk 39]
```diff
@@ -131,6 +132,25 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
...
   RAY_LOG(DEBUG) << "Constructing CoreWorker, worker_id: " << worker_id;
 
+  if (RayConfig::instance().kill_child_processes_on_worker_exit_with_raylet_subreaper()) {
+#ifdef __linux__
+    // Not setting sigchld = ignore: user may want to do waitpid on their own.
+    // If user's bad code causes a zombie process, it will hang their in zombie status
+    // until this worker exits and raylet reaps it.
+    if (SetThisProcessAsSubreaper()) {
+      RAY_LOG(INFO) << "Set this core_worker process as subreaper: " << getpid();
+      SetSigchldIgnore();
```
Comment (haohualipony) [inline src/ray/core_worker/core_worker.cc:142]: @rynewang curious why do you set sigchld ignore here? according to your comment in line 137, it should not be set?
