### PR TITLE
[core] Raylet adds job to GCS after the driver port announced.

### LINKED ISSUE #44459: GetAllJobInfo `is_running_tasks` is not returning the correct value when driver starts ray
### What happened + What you expected to happen

The `is_running_tasks` attribute on `GetAllJobInfo` is not returning the expected value (True) when no ray cluster is started, but it returns the correct value when a cluster is already started.

e.g.

```
import ray

@ray.remote
def f(x):
    import time
    time.sleep(5)
    return 0

ray.get([f.remote(i) for i in range(4)])

```

to reproduce:
1. Run `ray stop -f`
2. Run the script above and query the job API

Actual: while the task are in progress, the `is_running_tasks` flag should be True but it is False.
Expected: It should be True. If you repeat the steps above after pre-starting ray with `ray start --head`. The expected value is returned.

### Versions / Dependencies

2.10

### Reproduction script

import ray

@ray.remote
def f(x):
    import time
    time.sleep(5)
    return 0

ray.get([f.remote(i) for i in range(4)])

### Issue Severity

Medium: It is a significant difficulty but I can work around it.

### PR DESCRIPTION
**Pull request by rynewang**
GCS Client API `GetAllJobInfo` makes 1 RPC to each driver process for some up-to-date info. To make the call, GCS uses the driver core worker's IP and port address from the Raylet calling `ray::gcs::JobInfoAccessor::AsyncAdd` method. However Raylet may give a `port = 0` in the call, causing GCS not able to access the driver's core worker.

Here is a time order in core worker init:

1. core worker starts
2. core worker -> raylet `RegisterClientRequest`
3. raylet -> GCS `AddJob`
4. core worker -> raylet `AnnounceWorkerPort`.

Note step 3 should actually happen after step 4, because at step 3, raylet does not yet know the core worker's real port. This can happen when the raylet has `NodeManagerConfig::min_worker_port` set to 0, allowing the core worker to pick a port on its own.

This PR moves the step 3 (raylet -> GCS `AddJob`) to the raylet function that handles incoming `AnnounceWorkerPort` message, and instead of the `assigned_port`, now we give GCS the real port.

One catch is that, previously `AnnounceWorkerPort` is one-way, core worker does not wait for the reply and continues to the user code immediately. However we do want it to wait until the GCS received the newly added job. We don't want to always add an RTT to all worker inits either, so we only add the reply message when the worker is a driver. Luckily, both sides knows the worker type.

Fixes #44459.

### CODE REVIEW

**Comment by rynewang** [comment]
Note: I expect this PR to not have any performance regressions. The driver needs to wait for the raylet -> GCS RPC to finish anyways in both before & after this PR.

File: src/ray/raylet/node_manager.cc [hunk 1]
```diff
@@ -1292,33 +1292,20 @@ void NodeManager::ProcessRegisterClientRequestMessage(
...
+    // Assume raylet ID is the same as the node ID.
+    driver_address.set_raylet_id(self_node_id_.Binary());
+    driver_address.set_ip_address(worker_ip_address);
+    // driver_address.port is not set! It will be set in ProcessAnnounceWorkerPortMessage
+    driver_address.set_worker_id(worker_id.Binary());
+    auto job_data_ptr = gcs::CreateJobTableData(
+        job_id, /*is_dead=*/false, driver_address, pid, entrypoint, job_config);
+    worker->SetDriverJobTableData(job_data_ptr);
+
+    RAY_UNUSED(worker_pool_.RegisterDriver(worker, job_config, send_reply_callback));
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1308]: I think we can just construct JobTableData inside AnnouncePort, whatever information you need, you can include in the AnnouncePortRequest (e.g. worker_ip_address).

File: src/ray/raylet/node_manager.cc [hunk 2]
```diff
@@ -1335,10 +1322,34 @@ void NodeManager::ProcessAnnounceWorkerPortMessage(
 
   auto message = flatbuffers::GetRoot<protocol::AnnounceWorkerPort>(message_data);
   int port = message->port();
+  RAY_LOG(ERROR) << "NodeManager::ProcessAnnounceWorkerPortMessage " << port
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1325]: Why error?

File: src/ray/raylet/node_manager.cc [hunk 3]
```diff
@@ -1335,10 +1322,34 @@ void NodeManager::ProcessAnnounceWorkerPortMessage(
...
     worker_pool_.OnWorkerStarted(worker);
     HandleWorkerAvailable(worker);
+  } else {
+    auto job_data_ptr = worker->GetDriverJobTableData();
+    job_data_ptr->mutable_driver_address()->set_port(port);
+    RAY_CHECK_OK(gcs_client_->Jobs().AsyncAdd(job_data_ptr, [client](Status status) {
+      if (!status.ok()) {
+        RAY_LOG(ERROR) << "Failed to add job to GCS: " << status.ToString();
+        return;
+      }
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1338]: This is not the current behavior I think. The new code means we will never reply back to the driver if adding job fails?

File: src/ray/raylet_client/raylet_client.h [hunk 4]
```diff
@@ -298,9 +298,10 @@ class RayletClient : public RayletClientInterface {
 
   /// Tell the raylet which port this worker's gRPC server is listening on.
   ///
-  /// \param The port.
+  /// \param port The port.
+  /// \param wait_for_reply Whether to wait for the reply before returning.
   /// \return ray::Status.
-  Status AnnounceWorkerPort(int port);
+  Status AnnounceWorkerPort(int port, bool wait_for_reply);
```
Comment (jjyao) [inline src/ray/raylet_client/raylet_client.h:304]: `has_reply` is more accurate

File: python/ray/tests/test_state_api.py [hunk 5]
```diff
@@ -3559,6 +3559,28 @@ def test_core_state_api_usage_tags(shutdown_only):
...
+    tasks = [f.remote() for i in range(4)]
+
+    client = ray.worker.global_worker.gcs_client
+    job_id = ray.worker.global_worker.current_job_id.binary()
+    all_job_info = client.get_all_job_info()
+    assert len(all_job_info) == 1
+    assert job_id in all_job_info
+    assert client.get_all_job_info()[job_id].is_running_tasks is True
+    for o in tasks:
+        ray.cancel(o)
```
Comment (jjyao) [inline python/ray/tests/test_state_api.py:3581]: Do you need these, the cluster is terminating anyway

File: python/ray/tests/test_state_api.py [hunk 6]
```diff
@@ -3559,6 +3559,28 @@ def test_core_state_api_usage_tags(shutdown_only):
     )
 
 
+def test_job_info_is_running_task(shutdown_only):
```
Comment (jjyao) [inline python/ray/tests/test_state_api.py:3562]: This should be consistently failing before this PR right

**Review by jjyao — COMMENTED** [review]
lg

**Comment by jjyao** [comment]
Many test failures.

File: src/ray/raylet/node_manager.cc (hunk 2 above)
Comment (rynewang) [reply src/ray/raylet/node_manager.cc:1325]: debug leftover. removed

File: src/ray/raylet/node_manager.cc (hunk 1 above)
Comment (rynewang) [reply src/ray/raylet/node_manager.cc:1308]: The problem is `entrypoint` which is passed from core_worker to raylet in `RegisterClientRequest`. It's not making the most sense to pass in `AnnouncePortRequest`.

File: src/ray/raylet/node_manager.cc (hunk 3 above)
Comment (rynewang) [reply src/ray/raylet/node_manager.cc:1338]: not sure what we need to do if gcs add failed. Maybe we should just check fail. But yeah I will warn-and-continue for now

File: python/ray/tests/test_state_api.py (hunk 5 above)
Comment (rynewang) [reply python/ray/tests/test_state_api.py:3581]: if we don't use `tasks`, the linter complains. I changed the cancel to a print to mitigate.

Comment (rynewang) [reply python/ray/tests/test_state_api.py:3581]: In second thought, I can add a noqa lint directive for the unused variables

File: src/ray/raylet/node_manager.cc (hunk 3 above)
Comment (jjyao) [reply src/ray/raylet/node_manager.cc]: Let's just keep the old behavior (no regression) in this PR. We can think about what the better behavior is in follow-ups.

File: src/ray/raylet/node_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/raylet/node_manager.cc:1308]: I guess this is just because the current rpc is named `AnnouncePort`? If it's named something like `AnnounceReady`, it makes sense?

I just felt that we now store something permanently for something that's only needed locally.

Comment (rynewang) [reply src/ray/raylet/node_manager.cc:1308]: It's not only the problem of naming. the field `entrypoint` is passed in `RegisterClientRequest` so we need to keep it until we got the AnnouncePort. I can free the memory after it's used in AnnouncePort. Does that sound good?

Comment (rynewang) [reply src/ray/raylet/node_manager.cc:1308]: OK now I understand you want to put the `entrypoint` in AnnouncePortRequest. Ok will do that. Was misreading your comments lol

**Comment by rynewang** [comment]
@jjyao ready to merge

File: python/ray/tests/test_advanced_9.py [hunk 7]
```diff
@@ -264,6 +264,11 @@ def test_gcs_connection_no_leak(ray_start_cluster):
 
     ray.init(cluster.address)
 
+    # When we create a new node, the new raylet invokes RegisterGcs -> AsyncSubscribeAll
+    # -> AsyncGetAll -> GetAllJobInfo which makes the GCS to make a connection to each
+    # drivers. To make the connections consistent, pre-create the connection here.
+    ray._private.worker.global_worker.gcs_client.get_all_job_info()
+
```
Comment (jjyao) [inline python/ray/tests/test_advanced_9.py:271]: I still don't understand why we need to do this here?

File: python/ray/tests/test_state_api.py [hunk 8]
```diff
@@ -3559,6 +3559,28 @@ def test_core_state_api_usage_tags(shutdown_only):
...
+
+    @ray.remote
+    def f():
+        import time
+
+        while True:
+            time.sleep(10000)
+
+    # Create some long running tasks, no need to wait.
+    tasks = [f.remote() for i in range(4)]  # noqa: F841
```
Comment (jjyao) [inline python/ray/tests/test_state_api.py:3574]: any reason why we need 4 tasks here instead of 1?

File: src/ray/raylet/node_manager.cc [hunk 9]
```diff
@@ -1339,6 +1311,45 @@ void NodeManager::ProcessAnnounceWorkerPortMessage(
...
+                                /*is_dead=*/false,
+                                driver_address,
+                                worker->GetProcess().GetId(),
+                                string_from_flatbuf(*message->entrypoint()),
+                                *job_config);
+
+    RAY_CHECK_OK(gcs_client_->Jobs().AsyncAdd(job_data_ptr, [client](Status status) {
+      if (!status.ok()) {
+        RAY_LOG(ERROR) << "Failed to add job to GCS: " << status.ToString();
+      }
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1338]: In the original code, if this fails, `RegisterClientReply` will have 

```
// Whether the registration succeeded.
  success: bool;
  // The reason of registration failure.
  failure_reason: string;
```

set. We should do the same thing for AnnounceWorkerPortReply?

File: src/ray/raylet/node_manager.cc [hunk 10]
```diff
@@ -1339,6 +1311,45 @@ void NodeManager::ProcessAnnounceWorkerPortMessage(
...
+      // Write the reply back.
+      flatbuffers::FlatBufferBuilder fbb;
+      auto message = protocol::CreateAnnounceWorkerPortReply(fbb);
+      fbb.Finish(message);
+
+      auto reply_status = client->WriteMessage(
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:1344]: Why don't we call `WriteMessageAsync` here following

```
auto reply =
        ray::protocol::CreateRegisterClientReply(fbb,
                                                 status.ok(),
                                                 fbb.CreateString(status.ToString()),
                                                 to_flatbuf(fbb, self_node_id_),
                                                 assigned_port);
    fbb.Finish(reply);
    client->WriteMessageAsync(
        static_cast<int64_t>(protocol::MessageType::RegisterClientReply),
        fbb.GetSize(),
        fbb.GetBufferPointer(),
        [this, client](const ray::Status &status) {
          if (!status.ok()) {
            DisconnectClient(client,
                             rpc::WorkerExitType::SYSTEM_ERROR,
                             "Worker is failed because the raylet couldn't reply the "
                             "registration request.");
          }
        });
```

File: python/ray/tests/test_advanced_9.py (hunk 7 above)
Comment (rynewang) [reply python/ray/tests/test_advanced_9.py:271]: So I found after this PR, we got 1 more connection created in the test add node, and is not closed in test remove node. Then I found creating a node triggers gcs to connect with driver core workers, and that connection is persisted in core_worker_connection_pool in an LRU policy. Previously we did not have that because gcs had no way to connect to the driver (port is 0) which is exactly what we are fixing in this PR. So I pre-trigger the gcs->driver core worker connection to make it count in the initial list, so after the add node and remove node, the conn count is stable.

File: src/ray/raylet/node_manager.cc (hunk 9 above)
Comment (rynewang) [reply src/ray/raylet/node_manager.cc]: ok, added reply status. But at the terminal we check-fail it, since the cython binding `notify_raylet` returns void. Do we want to also change that to a raise exception?

File: src/ray/raylet/node_manager.cc (hunk 10 above)
Comment (rynewang) [reply src/ray/raylet/node_manager.cc]: makes sense. updated

File: python/ray/tests/test_state_api.py (hunk 8 above)
Comment (rynewang) [reply python/ray/tests/test_state_api.py:3574]: TODO: make it a signal actor enabling task

File: src/ray/core_worker/core_worker.cc [hunk 11]
```diff
@@ -736,12 +734,22 @@ void CoreWorker::Shutdown() {
...
-void CoreWorker::ConnectToRaylet() {
-  RAY_CHECK(!options_.connect_on_start);
+void CoreWorker::ConnectToRayletInternal() {
   // Tell the raylet the port that we are listening on.
   // NOTE: This also marks the worker as available in Raylet. We do this at the
   // very end in case there is a problem during construction.
-  RAY_CHECK_OK(local_raylet_client_->AnnounceWorkerPort(core_worker_server_->GetPort()));
+  if (options_.worker_type == WorkerType::DRIVER) {
+    RAY_CHECK_OK(local_raylet_client_->AnnounceWorkerPortForDriver(
+        core_worker_server_->GetPort(), options_.entrypoint));
```
Comment (rynewang) [inline src/ray/core_worker/core_worker.cc:743]: todo: add a msg to check

File: python/ray/tests/test_advanced_9.py [hunk 12]
```diff
@@ -262,32 +262,32 @@ def test_gcs_connection_no_leak(ray_start_cluster):
...
-    print(ray.get([t.ready.remote() for t in actors]))
-
-    # Kill the actors
-    del actors
+    with ray.init(cluster.address):
+        # Wait for everything to be ready.
+        time.sleep(10)
+        # Note: `fds_without_workers` need to be recorded *after* a ray start, because
+        # a prestarted worker is started on the first driver init. This worker keeps 1
+        # connection to the GCS, and it stays alive even after the driver exits. If
```
Comment (jjyao) [inline python/ray/tests/test_advanced_9.py:281]: do you know why the connection stays alive even after the driver exits?

**Review by jjyao — APPROVED** [review]

File: python/ray/tests/test_advanced_9.py (hunk 12 above)
Comment (rynewang) [reply python/ray/tests/test_advanced_9.py:281]: The prestarted worker is not specifically for job 01000000; it's for job = nil (ffffffff): [code](https://github.com/ray-project/ray/blob/27b6c12e85833ebcd6a640805802868654b29284/src/ray/raylet/worker_pool.cc#L1544). Frankly I don't know what it does - the worker can't be used by any jobs right?

Comment (jjyao) [reply python/ray/tests/test_advanced_9.py:281]: Yea, initially the prestarted worker is not tied to a job but I thought later on when we start the actor, it will late bind to job 0100000

Comment (jjyao) [reply python/ray/tests/test_advanced_9.py:281]: Oh, those prestarted workers cannot be used for actors

```
void WorkerPool::PrestartDefaultCpuWorkers(ray::Language language, int64_t num_needed) {
  // default workers uses 1 cpu and doesn't support actor.
  static const WorkerCacheKey kDefaultCpuWorkerCacheKey{/*serialized_runtime_env*/ "",
                                                        {{"CPU", 1}},
                                                        /*is_actor*/ false,
                                                        /*is_gpu*/ false};
```
