### PR TITLE
[Xlang][Java] Fix Java overrided `default` method cannot be invoked.

### LINKED ISSUE #21477: [Bug] [Xlang] Overloaded Java Class can't be called via xlang
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Others

### What happened + What you expected to happen

Given the following Java interface and class
```java
public interface ExampleInterface {
  default String echo(String inp) {
    return inp;
  }
}
```

```java
public class ExampleImpl implements ExampleInterface {
  @Override
  public String echo(String inp) {
    return inp + " echo";
  }
}
```

and calling it via Python (use own package of course):
```python
import ray
ray.init(job_config=ray.job_config.JobConfig(code_search_path=["."]))
cls = ray.java_actor_class("io.ray.serve.util.ExampleImpl")
handle = cls.remote()
print(ray.get(handle.echo.remote("hi")))
```

I get the following error:
```
In [6]: ray.get(handle.echo.remote("hi"))                                                                    
---------------------------------------------------------------------------
CrossLanguageError                        Traceback (most recent call last)
<ipython-input-6-eb72b94dc879> in <module>
----> 1 ray.get(handle.echo.remote("hi"))

~/Desktop/ray/ray/python/ray/_private/client_mode_hook.py in wrapper(*args, **kwargs)
    103             if func.__name__ != "init" or is_client_mode_enabled_by_default:
    104                 return getattr(ray, func.__name__)(*args, **kwargs)
--> 105         return func(*args, **kwargs)
    106 
    107     return wrapper

~/Desktop/ray/ray/python/ray/worker.py in get(object_refs, timeout)
   1742                     raise value.as_instanceof_cause()
   1743                 else:
-> 1744                     raise value
   1745 
   1746         if is_individual_id:

CrossLanguageError: An exception raised from JAVA:
io.ray.runtime.exception.RayTaskException: (pid=68724, ip=192.168.1.69) Error executing task 63964fa4841d4a2eeb3d013876f4f3c8c527dbba01000000
        at io.ray.runtime.task.TaskExecutor.execute(TaskExecutor.java:188)
        at io.ray.runtime.RayNativeRuntime.nativeRunTaskExecutor(Native Method)
        at io.ray.runtime.RayNativeRuntime.run(RayNativeRuntime.java:251)
        at io.ray.runtime.runner.worker.DefaultWorker.main(DefaultWorker.java:15)
Caused by: java.lang.RuntimeException: RayFunction io.ray.serve.util.ExampleImpl.echo is overloaded, the signature can't be empty.
        at io.ray.runtime.functionmanager.FunctionManager$JobFunctionTable.getFunction(FunctionManager.java:183)
        at io.ray.runtime.functionmanager.FunctionManager.getFunction(FunctionManager.java:108)
        at io.ray.runtime.task.TaskExecutor.getRayFunction(TaskExecutor.java:69)
        at io.ray.runtime.task.TaskExecutor.execute(TaskExecutor.java:121)
        ... 3 more
```

Note that if I can make the method not overloaded, then it's passes. 
```
  default String echo(String inp) {
```
to
```
  String echo(String inp);
```

### Versions / Dependencies

master

### Reproduction script

see above

### Anything else

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by jovany-wang**
## Why are these changes needed?
In Xlang(Python call Java), a Java method which overrides a `default` method of the super class is not able to be invoked successfully, due to we treat it as overloaded method instead of overrided method. This PR correctly handle it at the case it overrides a `default` method.

Before this PR, the following usage is not able to be invoked from Python -> Java.
```Java
public interface ExampleInterface {
  default String echo(String inp) {
    return inp;
  }
}
public class ExampleImpl implements ExampleInterface {
  @Override
  public String echo(String inp) {
    return inp + " echo";
  }
}
```
```python
/// Invoke it in Python.
cls = ray.java_actor_class("io.ray.serve.util.ExampleImpl")
handle = cls.remote()
print(ray.get(handle.echo.remote("hi")))
```

## Related issue number
Fix #21477

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java [hunk 1]
```diff
@@ -192,9 +193,11 @@ RayFunction getFunction(JavaFunctionDescriptor descriptor) {
     }
 
     /** Load all functions from a class. */
-    Map<Pair<String, String>, RayFunction> loadFunctionsForClass(String className) {
+    Map<Pair<String, String>, Pair<RayFunction, Boolean>> loadFunctionsForClass(String className) {
       // If RayFunction is null, the function is overloaded.
-      Map<Pair<String, String>, RayFunction> map = new HashMap<>();
+      // The value of this map is a pair of <rayFunction, isDefault>.
+      // The `isDefault` is used to mark if the method is a marked as default keyword.
+      Map<Pair<String, String>, Pair<RayFunction, Boolean>> map = new HashMap<>();
```
Comment (chaokunyang) [inline java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java:200]: Not necessary to add a default field using `Pair`, just check whether the method is default when needed?

Comment (jovany-wang) [reply java/runtime/src/main/java/io/ray/runtime/functionmanager/FunctionManager.java:200]: `isDefault` is not used for the overrided method in child class in Java. It's not able to check it when we need it.

**Review by chaokunyang — APPROVED** [review]
LGTM
