### PR TITLE
[core] Periodically GC metadata for streaming generators

### LINKED ISSUE #39151: [Core][Streaming Generator] Lineage reconstruction is not working if generator ref is GC'ed.
### What happened + What you expected to happen

Currently, if the generator ref is GC'ed, all the result report will be ignored. 

This means if the user GC the generator ref after their work is done, and if lineage reconstruction is triggered, the result is ignored, and the ray.get will hang (because the result will never be rewritten).

We can fix this by keep the generator ref alive until the lineage for the task is released. 

### Versions / Dependencies

master

### Reproduction script

See unit tests https://github.com/ray-project/ray/pull/38982

### Issue Severity

None

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Less invasive fix than #43584. Changes:
- When generator goes out of scope, add it to a list of streaming generator tasks that we scan periodically
- For each generator task, check if the task and streaming metadata can be removed. It can be removed if the generator task and all generated return refs have gone out of scope.
- Fixes an existing potential leak where task completes after the generator ref and returned refs have gone out of scope, by deleting the task metadata with the stream metadata.

#43584 is probably better long-term as it refactors stream metadata to be GCed through the normal ref counting path, and lineage can be GCed eagerly. However, this fix is safer.

## Related issue number

Closes #39151.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/task_manager.cc [hunk 1]
```diff
@@ -238,7 +238,7 @@ std::vector<rpc::ObjectReference> TaskManager::AddPendingTask(
   // The language frontend is responsible for calling DeleteObjectRefStream.
   if (spec.IsStreamingGenerator()) {
     const auto generator_id = spec.ReturnId(0);
-    RAY_LOG(DEBUG) << "Create an object ref stream of an id " << generator_id;
+    RAY_LOG(INFO) << "Create an object ref stream of an id " << generator_id;
```
Comment (rkooo567) [inline src/ray/core_worker/task_manager.cc]: is this debug -> info intended? we should revert?

File: src/ray/core_worker/task_manager.h [hunk 2]
```diff
@@ -410,7 +423,9 @@ class TaskManager : public TaskFinisherInterface, public TaskResubmissionInterfa
       ABSL_LOCKS_EXCLUDED(mu_);
 
   /// Return True if there's no more object to read. False otherwise.
-  bool IsFinished(const ObjectID &generator_id) const ABSL_LOCKS_EXCLUDED(mu_);
+  bool StreamingGeneratorIsFinished(const ObjectID &generator_id,
```
Comment (rkooo567) [inline src/ray/core_worker/task_manager.h:426]: Can you add docstring for num_objects_generated?

File: src/ray/core_worker/reference_count.cc [hunk 3]
```diff
@@ -273,6 +273,26 @@ void ReferenceCounter::OwnDynamicStreamingTaskReturnRef(const ObjectID &object_i
...
+  absl::MutexLock lock(&mutex_);
+  if (object_id_refs_.count(generator_id)) {
+    return false;
+  }
+
+  auto task_id = generator_id.TaskId();
+  for (int64_t i = 0; i < num_objects_generated; i++) {
+    // Add 2 because task returns start from index 1 and the
+    // first return object is the generator ID.
+    const auto return_id = ObjectID::FromIndex(task_id, i + 2);
```
Comment (rkooo567) [inline src/ray/core_worker/reference_count.cc:287]: hmm maybe this logic needs to be abstracted somewhere. but we don't have to do this in this PR

File: src/ray/core_worker/task_manager.cc [hunk 4]
```diff
@@ -792,11 +814,19 @@ void TaskManager::CompletePendingTask(const TaskID &task_id,
...
           spec.SetNumStreamingGeneratorReturns(num_streaming_generator_returns);
-          RAY_LOG(DEBUG) << "Completed streaming generator task " << spec.TaskId()
-                         << " has " << spec.NumStreamingGeneratorReturns()
-                         << " return objects.";
+          RAY_LOG(INFO) << "Completed streaming generator task " << spec.TaskId()
+                        << " has " << spec.NumStreamingGeneratorReturns()
+                        << " return objects.";
           for (const auto &return_id_info : reply.streaming_generator_return_ids()) {
             if (return_id_info.is_plasma_object()) {
+              // NOTE(swang): It is possible that the dynamically returned refs
```
Comment (rkooo567) [inline src/ray/core_worker/task_manager.cc:822]: is this a separate issue?

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -2963,8 +2968,33 @@ Status CoreWorker::SealReturnObject(const ObjectID &return_id,
...
+       it++) {
+    const auto &generator_id = *it;
+    RAY_LOG(DEBUG) << "Try DelObjectRefStream " << generator_id;
+    int64_t num_objects_generated = 0;
+    if (!task_manager_->StreamingGeneratorIsFinished(generator_id,
+                                                     &num_objects_generated)) {
+      continue;
+    }
+
+    bool can_gc = reference_counter_->CheckGeneratorRefsOutOfScope(generator_id,
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:2988]: can we remove all unconsumed objects here (and add a test)? This seems like a regression (where unconsumed objects are not deleted if lineage is alive). 

E.g., when delete hapapens, all unconsumed objects are deleted (same behavior as now). And only the stream metadata is cleaned up after a delay.

File: src/ray/core_worker/task_manager.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/core_worker/task_manager.cc]: Yes, it has been reverted.

File: src/ray/core_worker/task_manager.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/core_worker/task_manager.cc:822]: Existing issue that I added a fix for in this PR.

File: src/ray/core_worker/core_worker.cc [hunk 6]
```diff
@@ -2963,8 +2968,29 @@ Status CoreWorker::SealReturnObject(const ObjectID &return_id,
...
+
+void CoreWorker::TryDeleteObjectRefStreams() {
+  std::vector<ObjectID> out_of_scope_generator_ids;
+  for (auto it = deleted_generator_ids_.begin(); it != deleted_generator_ids_.end();
+       it++) {
+    const auto &generator_id = *it;
+    RAY_LOG(DEBUG) << "TryDelObjectRefStream " << generator_id;
+    if (task_manager_->TryDelObjectRefStream(generator_id)) {
+      out_of_scope_generator_ids.push_back(generator_id);
+      continue;
```
Comment (rkooo567) [inline src/ray/core_worker/core_worker.cc:2987]: continue seems unnecessary (since we do it++)?

**Review by rkooo567 — APPROVED** [review]
LGTM!

File: src/ray/core_worker/core_worker.cc [hunk 7]
```diff
@@ -641,6 +641,11 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
       RayConfig::instance().metrics_report_interval_ms() / 2,
       "CoreWorker.RecordMetrics");
 
+  periodical_runner_.RunFnPeriodically(
+      [this] { TryDeleteObjectRefStreams(); },
+      RayConfig::instance().local_gc_min_interval_s() * 1000,
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/core_worker/core_worker.cc:646]: It's to convert to ms?

Should be fine because we trigger it once immediately now.

File: src/ray/core_worker/task_manager.cc [hunk 8]
```diff
@@ -57,6 +57,38 @@ absl::flat_hash_set<ObjectID> ObjectRefStream::GetItemsUnconsumed() const {
   return result;
 }
 
+std::vector<ObjectID> ObjectRefStream::PopUnconsumedItems() {
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/core_worker/task_manager.cc:60]: This method pops the items, not just get.
