### PR TITLE
[core] Fix bug in task dependency management for duplicate args

### LINKED ISSUE #16556: [core] Tasks with duplicate args sometimes don't get scheduled
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 1.4 and earlier

The raylet overestimates the number of missing args for tasks that have duplicate args. This can lead to the task never being scheduled.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

```python
def test_many_args(ray_start_cluster):
    # This test ensures that a task will run where its task dependencies are
    # located, even when those objects are borrowed.
    cluster = ray_start_cluster
    object_size = int(1e6)

    # Disable worker caching so worker leases are not reused, and disable
    # inlining of return objects so return objects are always put into Plasma.
    for _ in range(4):
        cluster.add_node(
            num_cpus=1, object_store_memory=(4 * object_size * 25))
    ray.init(address=cluster.address)

    @ray.remote
    def f(i, *args):
        print(i)
        return

    @ray.remote
    def put():
        return np.zeros(object_size, dtype=np.uint8)

    xs = [put.remote() for _ in range(100)]
    ray.wait(xs, num_returns=len(xs), fetch_local=False)
    tasks = []
    for i in range(100):
        args = [np.random.choice(xs) for _ in range(25)]
        tasks.append(f.remote(i, *args))
    ray.get(tasks)
```

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

We overestimated the number of missing args for tasks that have duplicate args. This can lead to the task never being scheduled.

Closes #16556.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Review by ericl — APPROVED** [review]
Interesting. In pullmanager this is solved by de-duping the args, but guess the problem also occurs at a higher level.

File: src/ray/raylet/dependency_manager.h [hunk 1]
```diff
@@ -192,10 +192,10 @@ class DependencyManager : public TaskDependencyManagerInterface {
 
   /// A struct to represent the object dependencies of a task.
   struct TaskDependencies {
-    TaskDependencies(const std::vector<rpc::ObjectReference> &deps)
-        : num_missing_dependencies(deps.size()) {
+    TaskDependencies(const std::vector<rpc::ObjectReference> &deps) {
```
Comment (ericl) [inline src/ray/raylet/dependency_manager.h:195]: Consider changing this to absl::flat_hash_set<ObjectReference> so that duplicate edge cases can't happen by construction.

**Comment by ericl** [comment]
Rerunning tests:
[windows]
//python/ray/tests:test_scheduling                                       FAILED in 3 out of 3 in 96.6s

File: python/ray/tests/test_scheduling.py [hunk 2]
```diff
@@ -455,6 +455,37 @@ def f(x):
     assert len(ray.state.objects()) == 0, ray.state.objects()
 
 
+def test_many_args(ray_start_cluster):
```
Comment (ericl) [inline python/ray/tests/test_scheduling.py:458]: ::test_lease_request_leak SKIPPED                                        [ 92%]
::test_many_args Windows fatal exception: access violation

This seems to generate a memory access violation on Windows--- is it possible this is actually a real memory corruption bug?

File: src/ray/raylet/dependency_manager.h [hunk 3]
```diff
@@ -192,11 +192,8 @@ class DependencyManager : public TaskDependencyManagerInterface {
 
   /// A struct to represent the object dependencies of a task.
   struct TaskDependencies {
-    TaskDependencies(const std::vector<rpc::ObjectReference> &deps)
-        : num_missing_dependencies(deps.size()) {
-      const auto dep_ids = ObjectRefsToIds(deps);
-      dependencies.insert(dep_ids.begin(), dep_ids.end());
-    }
+    TaskDependencies(absl::flat_hash_set<ObjectID> &&deps)
```
Comment (ericl) [inline src/ray/raylet/dependency_manager.h:195]: R-value ref along with the move above is a bit suspicious, may explain the windows segfault.

**Comment by AmeerHajAli** [comment]
Can you please open an issue for this and label it 1.4.1 to make sure it is in the branch cut?

**Comment by stephanie-wang** [comment]
Yeah sorry for the delay too, I don't know what's up with the memory corruption issue...

**Comment by ericl** [comment]
Could try to "bisect" the changes to see what causes the memory issue.

**Comment by ericl** [comment]
@stephanie-wang per https://github.com/ray-project/ray/pull/16566 the test is crashing even sans the c++ change, seems some serializer memory safety issue. How about skipping it on windows to unblock the fix? We can separately try to figure out why this test causes this.

**Comment by stephanie-wang** [comment]
> @stephanie-wang per #16566 the test is crashing even sans the c++ change, seems some serializer memory safety issue. How about skipping it on windows to unblock the fix? We can separately try to figure out why this test causes this.

Oh thanks, was just trying this too. Yeah, sounds good.

**Comment by DmitriGekhtman** [comment]
cpp tests are unhappy

**Comment by stephanie-wang** [comment]
Hmm I'm having trouble reproducing the C++ failure locally, which is weird (these are usually pretty reliable). I just merged, let's see what happens.

**Comment by DmitriGekhtman** [comment]
I wonder what this means:
https://travis-ci.com/github/ray-project/ray/builds/230265115#L37906

**Comment by stephanie-wang** [comment]
> I wonder what this means:
> https://travis-ci.com/github/ray-project/ray/builds/230265115#L37906

This issue seems to be in master too, I don't think it's related to this PR.

**Comment by stephanie-wang** [comment]
test_multi_node_3 looks unrelated.
