### PR TITLE
[core][gcs] Fix task events profile events per task leak

### LINKED ISSUE #42144: [Serve] Memory leak after upgrading from 2.8.1 to 2.9.0
### What happened + What you expected to happen

After upgrading Ray version from 2.8.1 to 2.9.0 we noticed a memory leak `ray_node_mem_used`  on the head node. image

### Versions / Dependencies

2.9.0 

### Reproduction script
Load is 200 QPS

```python
import logging

from fastapi import FastAPI, Request
from fastapi.encoders import jsonable_encoder
from ray import serve
from starlette.responses import JSONResponse

logger = logging.getLogger("ray.serve")

app = FastAPI()


@serve.deployment
@serve.ingress(app)
class ModelServer:

    def __init__(self):
        logger.info("Initialized")


    @app.post("/inference")
    def inference(self, request: Request) -> JSONResponse:

        response = {
            "result": "OK"
        }

        return JSONResponse(content=jsonable_encoder(response))

esp_model_app = ModelServer.bind()
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by rickyyx**
## Why are these changes needed?

When a long running task keeps submitting tasks (e.g. driver task, actor task), it generates many profile events as part of task submission. 

While we already cap the number of profile events in a task at the core worker (where task events are produced and reported), we are not doing that on GCS (the sink), so it's possible when new task events merged to existing ones, it goes unbounded. 

Closes https://github.com/ray-project/ray/issues/42144

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rickyyx** [comment]
As a follow-up, I think we should add explicit memory consumption to GCS and other components for our long running tests. https://github.com/ray-project/ray/issues/42250

File: src/ray/gcs/gcs_server/gcs_task_manager.cc [hunk 1]
```diff
@@ -149,6 +149,20 @@ void GcsTaskManager::GcsTaskManagerStorage::UpdateExistingTaskAttempt(
   // Update the task event.
   existing_task.MergeFrom(task_events);
 
+  // Truncate the profile events if needed.
+  auto max_num_profile_events_per_task =
+      RayConfig::instance().task_events_max_num_profile_events_per_task();
+  if (existing_task.profile_events().events_size() > max_num_profile_events_per_task) {
+    auto to_drop =
+        existing_task.profile_events().events_size() - max_num_profile_events_per_task;
+    existing_task.mutable_profile_events()->mutable_events()->DeleteSubrange(0, to_drop);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_task_manager.cc:158]: if to_drop is negative, it will be noop?

**Review by rkooo567 — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_task_manager.cc (hunk 1 above)
Comment (rickyyx) [reply src/ray/gcs/gcs_server/gcs_task_manager.cc:158]: it will not enter the if clause in this case.
