### PR TITLE
[GCS Actor Management] Fix a dashboard doesn't show the correct actor state.

### LINKED ISSUE #9203: [GCS Actor Management] Dashboard still renders ALIVE state when actors are DEAD
### What is the problem?

It happens only when gcs actor management is on.

1. When actors are killed, the dashboard doesn't update the actor state to DEAD.

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

This is just for tracking. I will work on this issue.

### PR DESCRIPTION
**Pull request by rkooo567**
## Why are these changes needed?

Currently, GCS cleans up the actor address before it publishes. As a result, the published messages doesn't contain the proper address / port information of killed actors. This breaks the dashboard.

## Related issue number

Resolves https://github.com/ray-project/ray/issues/9203

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/latest/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failure rates at https://ray-travis-tracker.herokuapp.com/.
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [x] This PR is not tested (please justify below)
Manually tested.

### CODE REVIEW

**Review by stephanie-wang — APPROVED** [review]

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 1]
```diff
@@ -534,18 +534,18 @@ void GcsActorManager::DestroyActor(const ActorID &actor_id) {
...
       std::make_shared<rpc::ActorTableData>(*mutable_actor_table_data);
   // The backend storage is reliable in the future, so the status must be ok.
   RAY_CHECK_OK(gcs_table_storage_->ActorTable().Put(
       actor->GetActorID(), *actor_table_data,
-      [this, actor_id, actor_table_data](Status status) {
+      [this, actor, actor_id, actor_table_data](Status status) {
         RAY_CHECK_OK(gcs_pub_sub_->Publish(ACTOR_CHANNEL, actor_id.Hex(),
                                            actor_table_data->SerializeAsString(),
                                            nullptr));
+        actor->UpdateAddress(rpc::Address());
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:548]: We remove it directly, because actor is dead.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 2]
```diff
@@ -655,6 +654,8 @@ void GcsActorManager::ReconstructActor(const ActorID &actor_id, bool need_resche
               ACTOR_CHANNEL, actor_id.Hex(),
               mutable_actor_table_data->SerializeAsString(), nullptr));
         }));
+    // Empty address so that we can avoid scheduler schedules at the same address.
+    actor->UpdateAddress(rpc::Address());
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:658]: I think we need to update the address before writing to the storage. Otherwise, after the GCS server restarts, it will mistakenly think that the actor has succeeded in the lease worker.

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 3]
```diff
@@ -677,6 +678,7 @@ void GcsActorManager::ReconstructActor(const ActorID &actor_id, bool need_resche
           RAY_CHECK_OK(gcs_pub_sub_->Publish(
               ACTOR_CHANNEL, actor_id.Hex(),
               mutable_actor_table_data->SerializeAsString(), nullptr));
+          actor->UpdateAddress(rpc::Address());
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:681]: We can remove it directly, because actor is dead.

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:681]: will do!

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 2 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:658]: I see. So are you suggesting 
```
copy actor table data
update the mutable data
publish the copied data
``` ?

Does it make sense?

Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc]: @ffbin I copied the actor table data before updating some other states. Can you review one more time?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 4]
```diff
@@ -647,15 +645,20 @@ void GcsActorManager::ReconstructActor(const ActorID &actor_id, bool need_resche
...
-        [this, actor_id, mutable_actor_table_data](Status status) {
-          RAY_CHECK_OK(gcs_pub_sub_->Publish(
-              ACTOR_CHANNEL, actor_id.Hex(),
-              mutable_actor_table_data->SerializeAsString(), nullptr));
+        [this, actor_id, actor_table_data](Status status) {
+          RAY_CHECK_OK(gcs_pub_sub_->Publish(ACTOR_CHANNEL, actor_id.Hex(),
+                                             actor_table_data.SerializeAsString(),
+                                             nullptr));
         }));
+    // Empty address so that we can avoid scheduler schedules at the same address.
```
Comment (ffbin) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:661]: Does this comment match the code?

**Review by ffbin — APPROVED** [review]
LGTM

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 4 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:661]: Removed
