### PR TITLE
No spreading if a node is selected for lease request due to locality

### LINKED ISSUE #18581: [core][scheduler] Data locality scheduling doesn't always work with distributed scheduler policy
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* Ray 2.0dev

Locality aware leasing works by choosing a node that has the most arguments local for a task. However, this can interact poorly with the scheduler spreading threshold, which forces tasks to other nodes if the local resource utilization is higher than a certain threshold. So we can end up in a situation like this:

1. Object A created on node N, which puts node N's object store memory usage over the threshold (default 50%).
2. Driver submits task T that depends on A, sends to node N because A is local there.
3. Node N sees that head node has CPU and object store memory available, so it sends it back to the head node.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

TODO: Add example.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?
1. If the node is selected based on locality, we always run the task on the node selected by locality if the node is available.
2. For spread scheduling strategy, we always select the local node as the first raylet to request lease, no locality involved.

## Related issue number
Closes #18581

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by jjyao** [comment]
I need to add tests, etc but I'd like to request an early review to make sure the overall approach is good.

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 1]
```diff
@@ -329,14 +329,27 @@ void CoreWorkerDirectTaskSubmitter::RequestNewWorkerIfNeeded(
...
-  const TaskSpecification resource_spec = TaskSpecification(resource_spec_msg);
+  TaskSpecification resource_spec = TaskSpecification(resource_spec_msg);
   rpc::Address best_node_address;
   const bool is_spillback = (raylet_address != nullptr);
+  float scheduler_spread_threshold = RayConfig::instance().scheduler_spread_threshold();
   if (raylet_address == nullptr) {
+    bool is_selected_based_on_locality;
     // If no raylet address is given, find the best worker for our next lease request.
-    best_node_address = lease_policy_->GetBestNodeForTask(resource_spec);
+    std::tie(best_node_address, is_selected_based_on_locality) =
```
Comment (ericl) [inline src/ray/core_worker/transport/direct_task_transport.cc:339]: Shouldn't we only run this logic if the scheduling strategy is DEFAULT?

**Review by ericl — COMMENTED** [review]
To make sure, the desired precedence is:
1. SPREAD strategy => always spread, ignore locality complete
2. DEFAULT / locality present => set spread threshold to 1.0 (no spreading at all)
3. DEFAULT / no-locality => default spread threshold

Is this right?

**Comment by jjyao** [comment]
> To make sure, the desired precedence is:
> 
> 1. SPREAD strategy => always spread, ignore locality complete
> 
> 2. DEFAULT / locality present => set spread threshold to 1.0 (no spreading at all)
> 
> 3. DEFAULT / no-locality => default spread threshold
> 
> 
> 
> Is this right?

That's right.

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.cc:339]: Currently that check is inside lease_policy: it checks the scheduling strategy and decide if it needs to run locality logic.

File: src/ray/core_worker/transport/direct_task_transport.cc [hunk 2]
```diff
@@ -329,14 +329,27 @@ void CoreWorkerDirectTaskSubmitter::RequestNewWorkerIfNeeded(
...
+        lease_policy_->GetBestNodeForTask(resource_spec);
+    if (is_selected_based_on_locality) {
+      scheduler_spread_threshold = 1.0;
+    }
     raylet_address = &best_node_address;
   }
+  if (resource_spec.GetMessage().scheduling_strategy().scheduling_strategy_case() ==
+      rpc::SchedulingStrategy::SchedulingStrategyCase::kDefaultSchedulingStrategy) {
```
Comment (clarkzinzow) [inline src/ray/core_worker/transport/direct_task_transport.cc:347]: What about the placement group case?

File: src/ray/protobuf/common.proto [hunk 3]
```diff
@@ -58,7 +58,12 @@ message PlacementGroupSchedulingStrategy {
   bool placement_group_capture_child_tasks = 3;
 }
 
-message DefaultSchedulingStrategy {}
+message DefaultSchedulingStrategy {
+  // This config is not set by the user
+  // but rather determinted by the system based on
```
Comment (clarkzinzow) [inline src/ray/protobuf/common.proto:63]:
```suggestion
  // but rather determined by the system based on
```

**Comment by stephanie-wang** [comment]
Is there a way we can set the spread threshold only on the owner side? So that way the scheduler just takes the spread threshold directly from the TaskSpec?

**Comment by jjyao** [comment]
> Is there a way we can set the spread threshold only on the owner side? So that way the scheduler just takes the spread threshold directly from the TaskSpec?

Yes, this PR already set the spread threshold only on the owner side for tasks, what's left is doing the same thing for actors. Also I'm purposely associating spread threshold to scheduling strategy to make it clear that it only applies to certain scheduling strategy not all (e.g. LOCAL_NODE_ONLY).

**Comment by jjyao** [comment]
@ericl @stephanie-wang Updated, now only scheduler decides spread threshold.

File: src/ray/raylet/scheduling/cluster_task_manager.cc [hunk 4]
```diff
@@ -1558,7 +1558,8 @@ std::string ClusterTaskManager::GetBestSchedulableNode(const internal::Work &wor
                                                        bool *is_infeasible) {
   // If the local node is available, we should directly return it instead of
   // going through the full hybrid policy since we don't want spillback.
-  if (work.grant_or_reject && !force_spillback && IsLocallySchedulable(work.task)) {
+  if ((work.grant_or_reject || work.is_selected_based_on_locality) && !force_spillback &&
```
Comment (ericl) [inline src/ray/raylet/scheduling/cluster_task_manager.cc:1561]: Would it make sense to unify grant_or_reject and is_selected_based_on_locality?

Comment (jjyao) [reply src/ray/raylet/scheduling/cluster_task_manager.cc:1561]: They are the same if the node is available. But if the node is not available, their behavior is different, one is spill, the other is reject. I think it might be clearer to separate them.

File: src/ray/core_worker/transport/direct_task_transport.cc (hunk 2 above)
Comment (jjyao) [reply src/ray/core_worker/transport/direct_task_transport.cc]: update: I changed the PR so placement group case also runs the locality logic as before.

**Comment by jjyao** [comment]
This improves the locality aware scheduling but doesn't fix the fundamental problem: resource view and object view are separated in two places (owner core worker and raylet). Without having these information in a single place, we have the following issues:
1. Spillback is not locality aware: ideally if the best locality node is not available, we may want to spill back to the second best locality node.
2. It's possible that best locality node doesn't have the resources needed by the task (e.g. task needs custom resource A but best locality node doesn't have it), however core worker will still request the lease from that node.
3. Actor scheduling is not locality aware.

It's possible those issues won't cause much problem in real workload and this PR is enough but just something to keep in mind when we refactor scheduler. cc @scv119

**Comment by jjyao** [comment]
Don't merge it yet since I want to run nightly tests.

**Comment by clarkzinzow** [comment]
FYI @jjyao for (1), we have an [open issue](https://github.com/ray-project/ray/issues/12815) for it from the original locality-aware scheduling work and a [basic implementation idea](https://docs.google.com/document/d/1-V1hMYijBAXtciDOdHVjZZlb-GRjNZNK20EiSqfYLyg/edit#heading=h.j0a135tt2i1v) (on spillback, raylet returns **all** available nodes and the core worker chooses the best locality node from that set) but it has never been prioritized since we haven't created a test workload that demonstrates the need for it. It also predates the hybrid scheduling policy and wouldn't work very well with it (breaks under-threshold round-robin packing), so implementing a locality-aware spillback policy within the hybrid scheduling policy would probably yield much better results.

(2) is a great point that's always bothered me about this design, and we've heard (3) requested from users before. Really looking forward to addressing all of these with the redesign!

**Review by clarkzinzow — APPROVED** [review]
LGTM, great tests!

File: python/ray/tests/test_scheduling.py [hunk 5]
```diff
@@ -275,13 +305,21 @@ def test_locality_aware_leasing(ray_start_cluster):
...
+    non_local_node = cluster.add_node(num_cpus=2, resources={"pin": 2})
+    cluster.wait_for_nodes()
+
+    @ray.remote(num_cpus=1, resources={"pin": 1})
+    class Actor:
+        def ping(self):
+            pass
+
+    actor = Actor.remote()
+    ray.get(actor.ping.remote())
```
[the remark this answers is not in the document]
Comment (jjyao) [reply python/ray/tests/test_scheduling.py:322]: This makes sure that the best locality node has higher critical resource utilization and we don't spill back.

[the remark this answers is not in the document]
Comment (clarkzinzow) [reply python/ray/tests/test_scheduling.py:322]: Ah that makes sense, thanks!

**Comment by ericl** [comment]
Ah... I didn't see the label, sorry! Hopefully it works with the nightly tests.

**Comment by jjyao** [comment]
Nightly tests are broken now. Hopefully this works otherwise we can revert it. I'll keep an eye on the nightly tests once it's recovered.
