### PR TITLE
[core] Fix bugs in worker cleanup on driver exit

### LINKED ISSUE #16951: [Core] ObjectLostError related to ownership and named detached actor
### What is the problem?

Kill the driver while the detached named actor holds the ownership will result in `ray.exceptions.ObjectLostError: Object 7ff8ed146320e218ffffffffffffffffffffffff0100000001000000 is lost due to node failure`. This happens when the driver is been terminated, not exiting normally (however for other examples not shown here, exit the driver normally raises the same issue).

### Reproduction (REQUIRED)

```python
def test_ownership():
    subprocess.run(["ray start --head"], shell=True)
    time.sleep(1)
    script = os.path.join(
        os.path.abspath(os.path.dirname(__file__)), "detached.py")
    proc = subprocess.Popen([sys.executable, script])
    time.sleep(10)
    proc.kill()
    time.sleep(1)
    # connect to the cluster
    ray.init(address="auto", namespace="workflow")
    actor = ray.get_actor("holder")
    x = actor.get.remote()
    while isinstance(x, ray.ObjectRef):
        x = ray.get(x)
    assert x == 42
    ray.shutdown()
    subprocess.run(["ray stop"], shell=True)
    time.sleep(1)
```

the simplest `detached.py`:

```python
import ray


@ray.remote
def foo(x):
    return ray.put(42)


@ray.remote
class Actor:
    def __init__(self):
        self.ref = None

    def invoke(self):
        self.ref = foo.remote(0)

    def get(self):
        return self.ref


if __name__ == "__main__":
    ray.init(address="auto", namespace="workflow")
    a = Actor.options(name="holder", lifetime="detached").remote()
    a.invoke.remote()

    import time
    time.sleep(100)
```

a more complicated `detached.py`:

```python
import ray


@ray.remote
def foo(x):
    print("Executing", x)
    import time
    time.sleep(1)
    if x < 42:
        return foo.remote(x + 1)
    else:
        return 42


@ray.remote
class Actor:
    def __init__(self):
        self.ref = None

    def invoke(self):
        self.ref = foo.remote(0)
        return self.ref

    def get(self):
        return self.ref


if __name__ == "__main__":
    ray.init(address="auto", namespace="workflow")
    a = Actor.options(name="holder", lifetime="detached").remote()
    x = a.invoke.remote()

   # use time.sleep(100) here also causes error. but if the driver exits, no errors occur
    while isinstance(x, ray.ObjectRef):
        x = ray.get(x)
    assert x == 42
```

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

The raylet force-kills workers if their driver exits, but this can cause issues if the worker owns objects that are referenced by a detached actor (which lives past the driver). It's also buggy because workers can get started for the driver after the driver has already exited, e.g., if the driver submitted a task without waiting for its return value.

This PR removes this codepath and instead guarantees that all workers for that job will be killed eventually using the same codepath as for idle workers. This codepath already waits for the workers ObjectRefs to drain before killing the process.

## Related issue number

Closes #16951.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/raylet/worker_pool.cc [hunk 1]
```diff
@@ -715,11 +716,13 @@ void WorkerPool::TryKillingIdleWorkers() {
   running_size -= pending_exit_idle_workers_.size();
   // Kill idle workers in FIFO order.
   for (const auto &idle_pair : idle_of_all_languages_) {
-    if (running_size <= static_cast<size_t>(num_workers_soft_limit_)) {
+    const auto &idle_worker = idle_pair.first;
+    const auto &job_id = idle_worker->GetAssignedJobId();
+    if (running_size <= static_cast<size_t>(num_workers_soft_limit_) &&
+        !finished_jobs_.count(job_id)) {
```
Comment (iycheng) [inline src/ray/raylet/worker_pool.cc:722]: Does this mean that even the job has a lot of idle workers, if the job hasn't finished, we'll never kill any idle work?

Comment (stephanie-wang) [reply src/ray/raylet/worker_pool.cc:722]: I think this is right? It should be:
few workers && job not finished -> don't kill
lots of workers -> kill
job finished -> kill

Comment (iycheng) [reply src/ray/raylet/worker_pool.cc:722]: Sorry, my bad. You're right.

Comment (iycheng) [reply src/ray/raylet/worker_pool.cc:722]: I still feel some confusion here. Let me know if I'm wrong. If we got this code path, it means the workers will drain all the references before exiting right. Is it necessary to check whether the job finished or not?

Think about this case, there is another job running with a lot of workers, for the current job, although it hasn't finished, we still kill the worker which is the same as before?

Comment (stephanie-wang) [reply src/ray/raylet/worker_pool.cc:722]: Hmm yeah I added this to take care of the case where a job has finished but its workers are still around. Assuming no other workers will get started, the finished job's workers won't get killed because they're still under the soft limit.

It's not really necessary if the cluster is actively used, though, since another job will start more workers and then we should enter the idle-killing cleanup.

Comment (stephanie-wang) [reply src/ray/raylet/worker_pool.cc:722]: Maybe I should just add a comment here to explain why we have the finished check?

Comment (iycheng) [reply src/ray/raylet/worker_pool.cc:722]: Ah, got it. It makes sense! I think I went to the wrong direction ~~(we don't want to kill idle workers when the job is active)~~

**Review by fishbone — APPROVED** [review]
LGTM and thanks for the helping here!

File: src/ray/raylet/worker_pool.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/raylet/worker_pool.cc]: Okay! Yeah, this bit of logic is confusing. I added a comment, BTW!

**Review by rkooo567 — APPROVED** [review]
Do we already have tests that check if workers are killed when the job is done? (if not, can we write one?)

**Comment by stephanie-wang** [comment]
> Do we already have tests that check if workers are killed when the job is done? (if not, can we write one?)

I think test_multi_tenancy might check this but it's flaky. I added one in test_multi_node.

**Review by suquark — APPROVED** [review]

**Comment by stephanie-wang** [comment]
//python/ray/tests:test_runtime_env_complicated is flaky.

**Comment by suquark** [comment]
let me try if this works for my concrete workflow test
