### PR TITLE
Fix for incorrect channel read behavior after accelerated DAG teardown

### LINKED ISSUE #46284: [core][experimental] Calling ray.get() on CompiledDAGRef after dag.teardown() or actor failure hangs
### What happened + What you expected to happen

We should throw an error if `ray.get()` is called on a CompiledDAGRef after the DAG has already been torn down. Instead, it seems that `ray.get()` returns an infinite string of 0s and hangs.

### Versions / Dependencies

3.0dev

### Reproduction script

```python
import ray
from ray.dag import InputNode

@ray.remote
class Actor:
    def foo(self, arg):
        return arg
        
a = Actor.remote()
with InputNode() as inp:
    dag = a.foo.bind(inp)
    
dag = dag.experimental_compile()
x = dag.execute(1)
ray.kill(a)
# This hangs and returns infinite string of 0s.
ray.get(x)
```

### Issue Severity

None

### PR DESCRIPTION
**Pull request by jackhumphries**
## Why are these changes needed?

Prior to this PR (described in #46284), calling `ray.get()` on a `CompiledDAGRef` (i.e., a channel) after DAG teardown would return a large series of zeroes. This issue could be reproduced with this script:
```
import ray
from ray.dag import InputNode

@ray.remote
class Actor:
    def foo(self, arg):
        return arg
        
a = Actor.remote()
with InputNode() as inp:
    dag = a.foo.bind(inp)
    
dag = dag.experimental_compile()
x = dag.execute(1)
dag.teardown()
# `ray.get(x)` returns a large series of zeroes.
print(ray.get(x))
```

This issue happened because the channel was unregistered with the mutable object manager on DAG teardown, and thus on a subsequent access to the channel, the core worker thought the channel reference was for a normal immutable Ray object rather than for a channel mutable object. Thus, the core worker was returning the raw underlying memory for the mutable object, and the memory buffers were sized equal to the total size of the underlying memory, not the amount of data in the mutable object.

This PR fixes this issue by properly checking that a channel is either currently registered or previously registered, rather than just checking only that the channel is currently registered.

## Related issue number

Closes #46284

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by kevin85421** [comment]
> This issue happened because the channel was unregistered with the mutable object manager on DAG teardown

Where does `unregister` happen? Are you referring to [SetErrorInternal](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/experimental_mutable_object_manager.cc#L409-L410)?

> the core worker thought the channel reference was for a normal immutable Ray object rather than for a channel mutable object. Thus, the core worker was returning the raw underlying memory for the mutable object

Are you suggesting that we should use `GetExperimentalMutableObjects` to read the object for the correct result, but due to the channel being unregistered, `GetObjects` was used instead?

**Comment by jackhumphries** [comment]
> > This issue happened because the channel was unregistered with the mutable object manager on DAG teardown
> 
> Where does `unregister` happen? Are you referring to [SetErrorInternal](https://github.com/ray-project/ray/blob/master/src/ray/core_worker/experimental_mutable_object_manager.cc#L409-L410)?
> 
> > the core worker thought the channel reference was for a normal immutable Ray object rather than for a channel mutable object. Thus, the core worker was returning the raw underlying memory for the mutable object
> 
> Are you suggesting that we should use `GetExperimentalMutableObjects` to read the object for the correct result, but due to the channel being unregistered, `GetObjects` was used instead?

When I said "unregistered", I meant that `SetErrorInternal()` was called on the channel, as you said. This method then sets `reader_registered` to `false` for the channel.

For the second question, what you said is correct.

File: src/ray/core_worker/core_worker.cc [hunk 1]
```diff
@@ -1556,6 +1556,14 @@ Status CoreWorker::Get(const std::vector<ObjectID> &ids,
   for (const ObjectID &id : ids) {
     if (experimental_mutable_object_provider_->ReaderChannelRegistered(id)) {
       is_experimental_channel = true;
+      continue;
+    }
+
+    Status error_set = experimental_mutable_object_provider_->IsErrorSet(id);
+    if (error_set.IsChannelError()) {
```
Comment (ruisearch42) [inline src/ray/core_worker/core_worker.cc:1563]: I feel this experimental_mutable_object_provider_ API is a bit confusing to use.

experimental_mutable_object_provider_ can probably expose a more user-friendly API, something like `bool isChannelClosed()`, and internally you can implement it with `CheckHasError()`

File: src/ray/core_worker/core_worker.cc [hunk 2]
```diff
@@ -1556,6 +1556,14 @@ Status CoreWorker::Get(const std::vector<ObjectID> &ids,
...
+      // The channel is not registered but the error bit is set (likely because the
+      // channel was previously open and then was closed), so we should return an error.
+      return error_set;
```
Comment (ruisearch42) [inline src/ray/core_worker/core_worker.cc:1566]: Can you add a test to validate the fix?

**Review by ruisearch42 — COMMENTED** [review]
Great findings!

**Review by kevin85421 — COMMENTED** [review]
The PR description makes sense to me, but I have a question:

Based on my observation at https://github.com/ray-project/ray/issues/46284#issuecomment-2196354261, the actor method can get an error message like `(Actor pid=2054169) check_status: Channel closed. False True`. This means that:

* Shared memory channel calls `close()`, and writes error into `has_error` successfully. This also implies that the channels are unregistered.
* However, it can still get the error which means it calls `CheckHasError` which seems only be called in `ReadAcquire`. If it is unregistered, it should not call `ReadAcquire`. There might be some time difference between setting `has_error` and unregistration. However, the actor always prints the log.

File: src/ray/core_worker/core_worker.cc [hunk 3]
```diff
@@ -1556,6 +1556,14 @@ Status CoreWorker::Get(const std::vector<ObjectID> &ids,
   for (const ObjectID &id : ids) {
```
[the remark this answers is not in the document]
Comment (jackhumphries) [reply src/ray/core_worker/core_worker.cc:1556]: Done, though I pass a single object ID rather than a vector. The loop has logic that is specific to CoreWorker (all objects must be experimental or all objects must not be), so I thought it was best to leave it in CoreWorker.

File: src/ray/core_worker/core_worker.cc (hunk 2 above)
Comment (jackhumphries) [reply src/ray/core_worker/core_worker.cc]: Done.

**Comment by jackhumphries** [comment]
> The PR description makes sense to me, but I have a question:
> 
> Based on my observation at [#46284 (comment)](https://github.com/ray-project/ray/issues/46284#issuecomment-2196354261), the actor method can get an error message like `(Actor pid=2054169) check_status: Channel closed. False True`. This means that:
> 
> * Shared memory channel calls `close()`, and writes error into `has_error` successfully. This also implies that the channels are unregistered.
> * However, it can still get the error which means it calls `CheckHasError` which seems only be called in `ReadAcquire`. If it is unregistered, it should not call `ReadAcquire`. There might be some time difference between setting `has_error` and unregistration. However, the actor always prints the log.

I think what's happening is the actor is calling `WriteAcquire()` on the same channel, which does not call `WriterChannelRegistered()` to check if the channel is registered. Currently, `CoreWorker::Get()` does check `ReaderChannelRegistered()`, which is why the behavior is different.

After this PR is merged, can you add a check for `WriteChannelRegistered()`? I think this could be a good way to get more familiar with the C++ codebase. Thanks!

**Review by kevin85421 — APPROVED** [review]
Nice!

File: python/ray/dag/tests/experimental/test_accelerated_dag.py [hunk 4]
```diff
@@ -998,6 +998,26 @@ def test_composite_channel_multi_output(self, ray_start_regular_shared):
         compiled_dag.teardown()
 
 
+def test_channel_access_after_close(ray_start_regular):
```
Comment (kevin85421) [inline python/ray/dag/tests/experimental/test_accelerated_dag.py:1001]: Use `ray_start_regular_shared` instead? It may be able to fix the CI error.

**Comment by kevin85421** [comment]
> After this PR is merged, can you add a check for WriterChannelRegistered()? I think this could be a good way to get more familiar with the C++ codebase. Thanks!

Sounds good. Thanks!

File: python/ray/dag/tests/experimental/test_accelerated_dag.py (hunk 4 above)
Comment (jackhumphries) [reply python/ray/dag/tests/experimental/test_accelerated_dag.py]: Done, thanks!

File: src/ray/core_worker/core_worker.cc [hunk 5]
```diff
@@ -1554,8 +1554,16 @@ Status CoreWorker::Get(const std::vector<ObjectID> &ids,
   // Check whether these are experimental.Channel objects.
   bool is_experimental_channel = false;
   for (const ObjectID &id : ids) {
-    if (experimental_mutable_object_provider_->ReaderChannelRegistered(id)) {
+    Status ret = experimental_mutable_object_provider_->IsExperimentalChannel(id);
```
Comment (ruisearch42) [inline src/ray/core_worker/core_worker.cc:1557]: nit: let's call it status

File: python/ray/dag/tests/experimental/test_accelerated_dag.py [hunk 6]
```diff
@@ -998,6 +998,26 @@ def test_composite_channel_multi_output(self, ray_start_regular_shared):
...
+    class Actor:
+        def foo(self, arg):
+            return arg
+
+    a = Actor.remote()
+    with InputNode() as inp:
+        dag = a.foo.bind(inp)
+
+    dag = dag.experimental_compile()
+    x = dag.execute(1)
```
Comment (ruisearch42) [inline python/ray/dag/tests/experimental/test_accelerated_dag.py:1014]: call it ref to be consistent

File: src/ray/core_worker/experimental_mutable_object_provider.h [hunk 7]
```diff
@@ -131,6 +131,22 @@ class MutableObjectProvider {
   /// \param[in] object_id The ID of the object.
   Status SetError(const ObjectID &object_id);
 
+  /// Checks if the channel is closed.
+  ///
+  /// \param[in] object_id The ID of the object.
+  /// \return Status indicating whether the object (if a channel for it exists) has its
+  ///         error bit set (i.e., the channel is closed).
+  Status IsChannelClosed(const ObjectID &object_id);
```
Comment (ruisearch42) [inline src/ray/core_worker/experimental_mutable_object_provider.h:139]: `IsChannelClosed()` does not quite match the return type (Status), can we change it to `CheckChannelStatus()` across the board? With it, you may not need `IsExperimentalChannel()`.

**Review by ruisearch42 — COMMENTED** [review]
Looks good to approve. Still wondering if the API can be improved.

**Comment by stephanie-wang** [comment]
Should we just not reset reader_registered and writer_registered to false for now? That seems like a simpler fix.

File: src/ray/core_worker/core_worker.cc (hunk 5 above)
Comment (jackhumphries) [reply src/ray/core_worker/core_worker.cc:1557]: Done.

File: src/ray/core_worker/experimental_mutable_object_provider.h (hunk 7 above)
Comment (jackhumphries) [reply src/ray/core_worker/experimental_mutable_object_provider.h]: Done. I removed `IsExperimentalChannel()` from `MutableObjectProvider`.

File: python/ray/dag/tests/experimental/test_accelerated_dag.py (hunk 6 above)
Comment (jackhumphries) [reply python/ray/dag/tests/experimental/test_accelerated_dag.py]: Done.

**Comment by jackhumphries** [comment]
> Should we just not reset reader_registered and writer_registered to false for now? That seems like a simpler fix.

I'd prefer to keep this as is, if that's alright. When I do the channel garbage collection work, I would imagine I'm going to need to implement what is currently in this PR if we don't keep it.

**Review by kevin85421 — APPROVED** [review]
