### PR TITLE
[core] Trigger global gc when plasma store is under pressure.

### LINKED ISSUE #15550: [core] Objects are spilled before `gc.collect()` finishes
### What is the problem?

*Ray version and other system information (Python version, TensorFlow version, OS):* 1.3/2.0dev

Ubuntu 18.04, 8 cores.

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

```python
import dask
import dask.dataframe as dd
import json
import pandas as pd
import numpy as np
import os.path
import csv

from dask.distributed import Client
from dask.distributed import wait

import time


@dask.delayed
def generate(num_bytes):
    nrows = int(num_bytes // 8)
    array = np.random.randint(0, 100, size=(nrows, ), dtype=np.int64)
    return array


@dask.delayed
def select(array):
    return np.random.choice(array)


def run(nbytes, num_consumers):
    times = []
    start = time.time()
    for i in range(20):

        trial_start = time.time()

        array = generate(nbytes)
        futures = []
        for _ in range(num_consumers):
            futures.append(select(array))
        print(dask.compute(*futures)[:10])

        trial_end = time.time()
        duration = trial_end - trial_start
        times.append(duration)
        print("Trial {} done after {}".format(i, duration))

        del futures
        del array
        #import gc
        #gc.collect()

        if time.time() - start > 60:
            break
    return times


if __name__ == '__main__':
    import ray
    from ray.util.dask import ray_dask_get

    ray.init(object_store_memory=4e9)
    dask.config.set(scheduler=ray_dask_get)

    run(1_000_000_000, 4)
```

This script repeatedly generates a large array. With the `gc.collect()` lines commented out, most trials on my laptop complete in about 1.4s, but occasionally one trial takes ~4s. I confirmed that this is because an ObjectRef from a previous round is not getting freed at the end of the loop, and it ends up getting spilled when the next object needs to be stored.

With the `gc.collect()` lines commented in, each trial finishes consistently in 1.4s.

There are two problems here:
1. Dask-on-Ray is probably creating a cyclic reference that's keeping ObjectRefs in scope.
2. Although the raylet triggers `gc.collect()` on the workers once out of memory, it's not giving the workers enough time to complete this before triggering spilling. So we end up spilling objects that would've been collected anyway.

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [x] I have verified my script runs in a clean environment and reproduces the issue.
- [x] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

To avoid object spilling when the object is full, we trigger the global gc earlier to release memory.
## Related issue number
Closes #15550

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by rkooo567** [comment]
Why don't we implement this in `Status CreateRequestQueue::ProcessRequests()`?

File: src/ray/object_manager/object_manager.h [hunk 1]
```diff
@@ -313,6 +313,10 @@ class ObjectManager : public ObjectManagerInterface,
 
   int64_t GetMemoryCapacity() const { return config_.object_store_memory; }
 
+  double GetUsedMemoryPercentage() const {
```
Comment (stephanie-wang) [inline src/ray/object_manager/object_manager.h:316]: I think that we already have something like this in the resource manager that you could reuse.

File: src/ray/raylet/node_manager.cc [hunk 2]
```diff
@@ -519,20 +519,27 @@ void NodeManager::FillResourceReport(rpc::ResourcesData &resources_data) {
   cluster_resource_scheduler_->FillResourceUsage(resources_data);
   cluster_task_manager_->FillResourceUsage(resources_data);
 
+  // If plasma store is under high pressure, we should try to schedule a global gc.
+  bool plasma_high_pressure =
+      object_manager_.GetUsedMemoryPercentage() > high_plasma_storage_usage_;
```
Comment (stephanie-wang) [inline src/ray/raylet/node_manager.cc:524]: Should we adjust the interval based on the current memory usage instead of using a static threshold/interval?

Also, what are the guarantees for when this method gets called? Is it on a timer?

Comment (iycheng) [reply src/ray/raylet/node_manager.cc:524]: Ah, I've talked with @ericl about this, the conclusion is that the 30s probably should be the minimum duration to avoid overhead to the cluster. The default GC on the local node is 10min here. And here it's to issue a global gc which is different from that one.

Besides, we think maybe the global GC should be sent from GCS since that's the place that can have better global control. For example, if all nodes are at a similar usage of memory, global GC will be triggered at the same time, and it's N*N message passing which is not necessary. Although it goes with the heartbeat, the heartbeat will be forced to be broadcasted if global_gc bit is set to be true.

This goes with report, it's run periodically ([code](https://github.com/ray-project/ray/blob/master/src/ray/raylet/node_manager.cc#L421-L423))

**Comment by iycheng** [comment]
> Why don't we implement this in `Status CreateRequestQueue::ProcessRequests()`? (It's the code that handles proper actions for different memory usage)

This is more like a higher-level logic I think. It's a little bit strange to put global GC logic into plasma store which is a single node in-memory storage. I actually prefer moving that triggering gc out from the store.

Another reason is that the ProcessRequests are something processing plasma query, and if there is no query, it won't trigger it (I guess :p). Think about this case, the plasma store is under high pressure and all things are being used. GC got triggered, and it doesn't help. After this, some resources released in the app layer, before app gc's scheduling, there is no traffic running to plasma store which will keep the store under high memory pressure. So I think this is the better place for it.

File: src/ray/raylet/node_manager.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/raylet/node_manager.cc:524]: Ah I see, thanks for explaining!

Yeah for the report, I was just worried we might miss the GC call because this handler doesn't get called soon enough. This seems fine, though.

**Comment by stephanie-wang** [comment]
Also, is it possible to write a Python test for this?

File: src/ray/raylet/node_manager.cc (hunk 2 above)
Comment (rkooo567) [reply src/ray/raylet/node_manager.cc:524]: I like the gcs based report idea. Can you create a enhancement issue? Would there be any issue with that approach?

Comment (iycheng) [reply src/ray/raylet/node_manager.cc:524]: > Ah I see, thanks for explaining!
> 
> Yeah for the report, I was just worried we might miss the GC call because this handler doesn't get called soon enough. This seems fine, though.

I agree with you. I think here if memory usage is close to 100%, we probably can do nothing. It'll help if it bump to 90% suddenly and increase slowly. That's why even with this, it won't help fix the issue.

**Comment by iycheng** [comment]
> Also, is it possible to write a Python test for this?

Sure. I actually was thinking about how to add a unit test and then realized it's not that easy to do. python e2e test totally makes sense.

File: src/ray/object_manager/object_manager.h (hunk 1 above)
Comment (iycheng) [reply src/ray/object_manager/object_manager.h:316]: @stephanie-wang I only see resource manager in gcs, which probably doesn't fit here. Is this the one you mentioned?

File: src/ray/raylet/node_manager.cc [hunk 3]
```diff
@@ -519,20 +519,27 @@ void NodeManager::FillResourceReport(rpc::ResourcesData &resources_data) {
...
     should_global_gc_ = false;
+    global_gc_throttler_.RunNow();
   }
 
   // Trigger local GC if needed. This throttles the frequency of local GC calls
   // to at most once per heartbeat interval.
-  auto now = absl::GetCurrentTimeNanos();
-  if ((should_local_gc_ || now - last_local_gc_ns_ > local_gc_interval_ns_) &&
-      now - last_local_gc_ns_ > local_gc_min_interval_ns_) {
+  if ((should_local_gc_ || (absl::GetCurrentTimeNanos() -
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:538]: Do we need `absl::GetCurrentTimeNanos() - local_gc_throttler_.LastRunTime()` here? Doesn't AbleToRun have the same logic in it?

File: src/ray/util/throttler_test.cc [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+// limitations under the License.
+
+#include "gtest/gtest.h"
+
+#include <cstdlib>
+#include <thread>
+
+#include "ray/util/throttler.h"
+
+TEST(ThrottlerTest, BasicTest) {
```
Comment (rkooo567) [inline src/ray/util/throttler_test.cc:22]: This means the test takes 20 seconds right? Can we just use the logical timer like `PullManager`'s `get_time`?

**Review by rkooo567 — APPROVED** [review]

File: src/ray/object_manager/object_manager.h (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/object_manager/object_manager.h:316]: I was thinking of the [ClusterResourceScheduler](https://github.com/ray-project/ray/blob/master/src/ray/raylet/scheduling/cluster_resource_scheduler.h), although I'm not totally sure it's there. @ericl should know since I think he added the memory availability reporting for the autoscaler.

File: src/ray/util/throttler.h [hunk 5]
```diff
@@ -0,0 +1,44 @@
...
+#pragma once
+
+#include "absl/time/clock.h"
+
+namespace ray {
+
+class Throttler {
+ public:
+  explicit Throttler(uint64_t interval_ns)
+      : last_run_ns_(absl::GetCurrentTimeNanos()), interval_ns_(interval_ns) {}
```
Comment (ericl) [inline src/ray/util/throttler.h:24]: Can we set last_run_ns_ to zero by default?

File: src/ray/util/throttler_test.cc (hunk 4 above)
Comment (ericl) [reply src/ray/util/throttler_test.cc:22]: +1

File: src/ray/util/throttler.h (hunk 5 above)
Comment (ericl) [reply src/ray/util/throttler.h:24]: (This allows the first trigger to happen immediately)

File: src/ray/raylet/node_manager.cc (hunk 3 above)
Comment (iycheng) [reply src/ray/raylet/node_manager.cc:538]: There are two things here: 1) prevent it from running if it run too frequently. 2) force it to run if it hasn't run for a while. AbleToRun cover 1), 2) is not covered.

File: src/ray/util/throttler_test.cc (hunk 4 above)
Comment (iycheng) [reply src/ray/util/throttler_test.cc:22]: Let me check it

**Comment by ericl** [comment]
Can you rebase to fix the CI issues?

**Comment by rkooo567** [comment]
(07:04:40) ERROR: BUILD.bazel:969:8: Couldn't build file _objs/throttler_test/throttler_test.obj: C++ compilation of rule '//:throttler_test' failed (Exit 2): cl.exe failed: error executing command 


Failing with Windows build with this error

**Comment by iycheng** [comment]
> (07:04:40) ERROR: BUILD.bazel:969:8: Couldn't build file _objs/throttler_test/throttler_test.obj: C++ compilation of rule '//:throttler_test' failed (Exit 2): cl.exe failed: error executing command
> 
> Failing with Windows build with this error

Thanks for the reminder! Sorry too busy with other things and totally forgot this :(

I checked the failure of the window and I think it's an important check and I'm surprised that Linux doesn't give such an error.

**Comment by rkooo567** [comment]
`tests:test_global_gc ` fails on both Linux & OSX (in flaky builds). I think it should be related to this PR
