### PR TITLE
[Core][pubsub] handle failures when publish failed.

### LINKED ISSUE #32046: [Core] ObjectStore fail to pull object, possibly because node info is missing
### What happened + What you expected to happen

As mentioned here: https://discuss.ray.io/t/raylet-object-manager-cc-couldnt-send-pull-request-from/9027, we meet problems about pulling remote object in our production environment.

> (raylet, ip=[fdbd:dc01:16:165:ad00::48]) [2023-01-30 14:47:12,412 E 27 27] (raylet) [object_manager.cc:293](http://object_manager.cc:293/): Couldn't send pull request from d9969738fb6ac4cb998e1b12a4d8acfea969cd2ab45a7cc6c7fda954 to fd54f76b74986c8e913dbab01a94b9c13881e98981bf0f417a3a62d3 of object 00d31a2771aa3d2fd74413d0eaf37ce41b9135450800000003000000 , setup rpc connection failed.

**Our production ray cluster:** 240 work nodes and 1400 actors totally, ray version 2.0.0

**NOTE**: In order to describe the problem conveniently, the following use nodeA to represent `d9969738fb6ac4cb998e1b12a4d8acfea969cd2ab45a7cc6c7fda954`, and nodeB to represent `fd54f76b74986c8e913dbab01a94b9c13881e98981bf0f417a3a62d3`.

After diving into some code(raylet and gcs) and log, we found that it is possible that the gcs pub node info message is missing.

https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/src/ray/object_manager/object_manager.cc#L293
The `Couldn't send pull request from` log means that the rpc client from nodeA to nodeB is null.
https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/src/ray/object_manager/object_manager.cc#L704
It seems that nodeA cannot get connection info of nodeB.
go on
https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/src/ray/object_manager/ownership_based_object_directory.cc#L451
https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/src/ray/gcs/gcs_client/accessor.cc#L536

The nodeB does not exists in the local node cache.

Then, check raylet.out of nodeA, there is not log like `Received notification for node id` for nodeB.
https://github.com/ray-project/ray/blob/2947e2360676b2034163282f7426d979849fa79a/src/ray/gcs/gcs_client/accessor.cc#L608

From gcs log, nodeB should be registered normally.

>[2023-01-30 11:25:03,809 I 12 12] (gcs_server) gcs_node_manager.cc:42: Registering node info, node id = fd54f76b74986c8e913dbab01a94b9c13881e98981bf0f417a3a62d3, address = [fdbd:dc01:28:311:a200::53], node name = [fdbd:dc01:28:311:a200::53][2023-01-30 11:25:03,809 I 12 12] (gcs_server) gcs_node_manager.cc:48: Finished registering node info, node id = fd54f76b74986c8e913dbab01a94b9c13881e98981bf0f417a3a62d3, address = [fdbd:dc01:28:311:a200::53], node name = [fdbd:dc01:28:311:a200::53]

So obviously, nodeA didn't receive node info of nodeB from gcs. Meanwhile, we check other nodes, such as nodeC, node info of nodeB is received.

> [2023-01-30 11:25:03,811 I 27 27] (raylet) accessor.cc:608: Received notification for node id = fd54f76b74986c8e913dbab01a94b9c13881e98981bf0f417a3a62d3, IsAlive = 1

### Versions / Dependencies

**Version**: ray 2.0.0

### Reproduction script

None

### Issue Severity

None

### PR DESCRIPTION
**Pull request by scv119**
## Why are these changes needed?

https://github.com/ray-project/ray/issues/32046 indicating that the pubsub might lose data, especially when the subscriber is under load. After examine the protocol it seems one bug is that the publisher fails to handle publish failures. i.e. when we push message in mailbox, we will delete the message being sent regardless of RPC failures.

This PR tries to address the problem by adding monotonically increasing sequence_id to each message, and only delete messages when the subscriber acknowledged a message has been received.
 
The sequence_id sequences is also generated per publisher, regardless of channels. This means if there exists multiple channels for the same publisher, each channel might not see contiguous sequences. This also assumes the invariant that  a subscriber object will only subscribe to one publisher.

We also relies on the pubsub protocol that at most one going push request will be inflight. 

This also handles the case gcs failover. We do so by track the publisher_id between both publisher and subscriber. When gcs failover, the publisher_id will be different, thus both the publisher and subscriber will forget the information about previous state.

   - [x] Unit tests
   - [x]  Integration tests

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/pubsub/publisher.h [hunk 1]
```diff
@@ -457,6 +458,13 @@ class Publisher : public PublisherInterface {
   int publish_batch_size_;
 
   absl::flat_hash_map<rpc::ChannelType, uint64_t> cum_pub_message_cnt_ GUARDED_BY(mutex_);
+
+  /// The monotonically increasings sequence_id for this publishter.
```
Comment (MissiontoMars) [inline src/ray/pubsub/publisher.h:462]: typo, increasings and publishter

File: python/ray/_private/gcs_pubsub.py [hunk 2]
```diff
@@ -271,6 +273,10 @@ def _poll_locked(self, timeout=None) -> None:
             if fut.done():
                 self._last_batch_size = len(fut.result().pub_messages)
                 for msg in fut.result().pub_messages:
+                    if msg.sequence_id <= self._max_processed_sequence_id:
```
Comment (jjyao) [inline python/ray/_private/gcs_pubsub.py:276]: what if msg.seq_id > max_processed + 1?

File: src/ray/pubsub/publisher.cc [hunk 3]
```diff
@@ -359,13 +372,15 @@ bool Publisher::RegisterSubscription(const rpc::ChannelType channel_type,
   return subscription_index_it->second.AddEntry(key_id.value_or(""), subscriber);
 }
 
-void Publisher::Publish(const rpc::PubMessage &pub_message) {
+void Publisher::Publish(rpc::PubMessage pub_message) {
+  RAY_CHECK(pub_message.sequence_id() == 0) << "sequence_id should not be set;";
```
Comment (jjyao) [inline src/ray/pubsub/publisher.cc:376]: use RAY_CHECK_EQ so that it prints out `pub_message.sequence_id()` when the check fails

File: src/ray/pubsub/subscriber.cc [hunk 4]
```diff
@@ -381,6 +381,16 @@ void Subscriber::HandleLongPollingResponse(const rpc::Address &publisher_address
       const auto &msg = reply.pub_messages(i);
       const auto channel_type = msg.channel_type();
       const auto &key_id = msg.key_id();
+      RAY_CHECK(msg.sequence_id() > 0)
```
Comment (jjyao) [inline src/ray/pubsub/subscriber.cc:384]: RAY_CHECK_GT

**Review by clarng — COMMENTED** [review]
Nice

File: python/ray/_private/gcs_pubsub.py [hunk 5]
```diff
@@ -90,7 +91,8 @@ def _subscribe_request(self, channel):
 
     def _poll_request(self):
         return gcs_service_pb2.GcsSubscriberPollRequest(
-            subscriber_id=self._subscriber_id
+            subscriber_id=self._subscriber_id,
+            max_processed_sequence_id=self._max_processed_sequence_id,
```
Comment (rkooo567) [inline python/ray/_private/gcs_pubsub.py:95]: Isn't it supposed to be _max_processed_sequence_id + 1?

File: src/ray/pubsub/publisher.cc [hunk 6]
```diff
@@ -278,28 +286,33 @@ bool SubscriberState::PublishIfPossible(bool force_noop) {
...
   // Clean up & update metadata.
   long_polling_connection_.reset();
+  // Clean up & update metadata.
   last_connection_update_time_ms_ = get_time_ms_();
   return true;
 }
 
 bool SubscriberState::CheckNoLeaks() const {
   // If all message in the mailbox has been replied, consider there is no leak.
-  return !long_polling_connection_ && mailbox_.empty();
```
Comment (rkooo567) [inline src/ray/pubsub/publisher.cc:302]: Why do we remove this?

**Review by rkooo567 — COMMENTED** [review]
Generally, lgtm

Did I understand the high level behavior change correctly?

1. We now guarantee at least once semantics
2. The subscribe side processing is idempotent (same as status quo)

Also some of tests seem fail (maybe we have a bug somewhere).

Lastly, this should work only when we do "resubscribe". When I wrote code last time, I didn't add resubscribe mechanism to the module (but @mwtian  probably added this mechanism to the high lever layer?). At that time, if the publish failed (meaning long polling failed), the publisher is considered as dead. Do you happen to know if we do resubscription in this scenario? I am 100% sure we don't do resubscription for non-GCS channels, but I am not sure about GCS

File: src/ray/pubsub/publisher.cc [hunk 7]
```diff
@@ -262,7 +269,8 @@ void SubscriberState::ConnectToSubscriber(const rpc::PubsubLongPollingRequest &r
 
 void SubscriberState::QueueMessage(const std::shared_ptr<rpc::PubMessage> &pub_message,
                                    bool try_publish) {
-  mailbox_.push(pub_message);
+  RAY_LOG(DEBUG) << "enqueue: " << pub_message->sequence_id();
```
[the remark this answers is not in the document]
Comment (scv119) [reply src/ray/pubsub/publisher.cc:272]: I assume we do not care too much about spamminess of debug log, since it's not supposed to turn on by default.

File: src/ray/pubsub/publisher.cc (hunk 6 above)
Comment (scv119) [reply src/ray/pubsub/publisher.cc:302]: - this is only used for testing, and there is already another helper function `ConnectionExists` does't connection check.
- we also changed test code to call `ConnectionExists` accordingly.

**Comment by scv119** [comment]
> Did I understand the high level behavior change correctly?
> 
> We now guarantee at least once semantics
> The subscribe side processing is idempotent (same as status quo)

It's almost correct. We guarantee the subscribe will receive all the published message at least once after subscribe succeeded, on those non-lossy channels (i.e. there a channels capped by mailbox queue size). we also guarantee that exact once semantics if only network error happens (no application error).  


> Lastly, this should work only when we do "resubscribe". When I wrote code last time, I didn't add resubscribe mechanism to the module (but @mwtian probably added this mechanism to the high lever layer?). At that time, if the publish failed (meaning long polling failed), the publisher is considered as dead. Do you happen to know if we do resubscription in this scenario? I am 100% sure we don't do resubscription for non-GCS channels, but I am not sure about GCS

**Review by rkooo567 — APPROVED** [review]

**Comment by scv119** [comment]
synced with Sang, i'll add integration tests to verify it works e2e.

**Review by rkooo567 — CHANGES_REQUESTED** [review]
I will review ti today

File: src/ray/pubsub/publisher.cc [hunk 8]
```diff
@@ -246,6 +243,22 @@ std::unique_ptr<EntityState> SubscriptionIndex::CreateEntityState() {
...
+  if (request.publisher_id().empty() ||
+      publisher_id_ != PublisherID::FromBinary(request.publisher_id())) {
+    // in case the publisher_id mismatches, we should ignore the
+    // max_processed_sequence_id.
+    max_processed_sequence_id = 0;
+  }
+
+  // clean up messages that have already been processed.
+  while (!mailbox_.empty() &&
+         mailbox_.front()->sequence_id() <= max_processed_sequence_id) {
```
Comment (rkooo567) [inline src/ray/pubsub/publisher.cc:256]: I might be missing something, but isn't it going to cause issues if this happens?

1. New GCS starts. It sent messages to other nodes (so the global seq_no > 0)
2. publisher finds the subscriber doesn't match. Set max_processed_sequence_id for this subscriber == 0
2. `Publish` is called to this subscriber. Since seq_no > 0, it will never be sent (because max_processed_sequence_id == 0)?

**Review by rkooo567 — COMMENTED** [review]
LGTM, but I have one last question... I might be missing some invariants you assumed here though.

File: src/ray/pubsub/publisher.cc (hunk 8 above)
Comment (scv119) [reply src/ray/pubsub/publisher.cc:256]: hmm

> Publish is called to this subscriber. Since seq_no > 0, it will never be sent (because max_processed_sequence_id == 0)?

on sender:  max_processed_sequence_id is only used for garbage collection, not preventing messaging being sent
on receiver: max_processed_sequence_id will also be reset to 0 so if any message sequence_id > 0, it will be received.

**Review by rkooo567 — APPROVED** [review]

**Comment by rkooo567** [comment]
Hmm not sure lint failure is related. can you merge the latest master?
