### PR TITLE
[core] Mark raylet unhealthy if GCS can't recognize it.

### LINKED ISSUE #33854: [Core] Raylet becomes zomebie when the HA GCS restarts and the external storage loses the data
### What happened + What you expected to happen

When the external storage loses the data, all the raylet becomes the zombie raylet (it is alive, but it cannot connect to GCS and lives). The main root cause is that the GCS health check from raylet will succeed (because channel is healthy as GCS is alive), but GCS doesn't have the membership information of the raylet, so it won't communicate to it. All the health check of resource broadcasting won't be communicated to this node because the node is dead.

Since GCS HA assumes the backing storage won't lose the data, there's no "fix" we can do in this problem. However, we should fail more loudly in this scenario. More specifically, we need to do the following action items; 

- Fix the behavior so the raylet won’t become a zombie if it connects to a GCS that it isn’t actually registered to
- Improve the logging across the board to make it easier to debug these things

cc @iycheng 

### Versions / Dependencies

master

### Reproduction script

remove data from redis and restart GCS. Worker node raylet should be killed. 

### Issue Severity

Low: It annoys or frustrates me.

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?
When GCS can't recognize the raylet, Raylet will just hang there and never exits. There is also no way to tell whether this raylet is healthy or not.

This could happen when some incorrect setup. For example, data is lost in the DB. When Raylet detect the issue, it should just exit itself or mark itself as unhealthy.

This PR will mark raylet mark itself unhealthy and the upper layer can choose what to do for this case. This is useful for Serve HA's usecase because as long as the raylet is alive, the actors will be still able to serve traffic and the upper layer can do more operations, like starting a new cluster and shutdown the current one later.

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a 
           method in Tune, I've added it in `doc/source/tune/api/` under the 
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/common/ray_syncer/ray_syncer-inl.h [hunk 1]
```diff
@@ -229,7 +229,7 @@ class RaySyncerBidiReactorBase : public RaySyncerBidiReactor, public T {
       node_versions[message->message_type()] = message->version();
       message_processor_(message);
     } else {
-      RAY_LOG_EVERY_N(WARNING, 100)
+      RAY_LOG_EVERY_MS(WARNING, 1000)
```
Comment (iycheng) [inline src/ray/common/ray_syncer/ray_syncer-inl.h:232]: This is just to reduce the log numbers outputted.

File: python/ray/tests/test_gcs_fault_tolerance.py [hunk 2]
```diff
@@ -765,6 +765,65 @@ def f():
...
+    ray.get(create_actor.remote())
+
+    ray._private.worker._global_node.kill_gcs_server()
+    # Delete redis
+    redis_addr = os.environ.get("RAY_REDIS_ADDRESS")
+    import redis
+
+    ip, port = redis_addr.split(":")
+    cli = redis.Redis(ip, port)
+    cli.flushall()
```
Comment (rkooo567) [inline python/ray/tests/test_gcs_fault_tolerance.py:800]: this test is amazing!

File: src/ray/gcs/gcs_client/accessor.cc [hunk 3]
```diff
@@ -470,6 +470,25 @@ Status NodeInfoAccessor::AsyncRegister(const rpc::GcsNodeInfo &node_info,
   return Status::OK();
 }
 
+Status NodeInfoAccessor::AsyncCheckSelfAlive(
+    const std::function<void(Status, bool)> &callback) {
+  rpc::CheckAliveRequest request;
+  auto node_addr = local_node_info_.node_manager_address() + ":" +
+                   std::to_string(local_node_info_.node_manager_port());
+  RAY_CHECK(callback != nullptr);
+  request.add_raylet_address(node_addr);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_client/accessor.cc:479]: Maybe it doesn't need to be done here, but we probably should check the node id instead of address?

File: src/ray/raylet/node_manager.cc [hunk 4]
```diff
@@ -541,6 +541,35 @@ ray::Status NodeManager::RegisterGcs() {
...
   }
+  // Raylet periodically check whether it's alive in GCS.
+  // For failure cases, GCS might think this raylet dead, but this
+  // failure still think it's alive.
+  periodical_runner_.RunFnPeriodically(
+      [this] {
+        // Flag to see whether a request is running.
+        static bool checking = false;
+        if (checking) {
+          return;
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:552]: does it mean it is not replied within 60 seconds? Should we have a timeout to the request?

File: src/ray/raylet/node_manager.cc [hunk 5]
```diff
@@ -541,6 +541,35 @@ ray::Status NodeManager::RegisterGcs() {
...
+        }
+        checking = true;
+        RAY_CHECK_OK(gcs_client_->Nodes().AsyncCheckSelfAlive([this](auto status,
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:555]: maybe we need some timeout for health checking RPC?

File: src/ray/raylet/node_manager.cc [hunk 6]
```diff
@@ -541,6 +541,35 @@ ray::Status NodeManager::RegisterGcs() {
...
+              // GCS think this raylet is dead. Set the raylet unhealthy.
+              RAY_LOG(WARNING)
+                  << "GCS consider this node to be dead. Set the status to be unhealthy";
+              node_manager_server_.GetServer().GetHealthCheckService()->SetServingStatus(
+                  self_node_id_.Hex(), false);
+              node_manager_server_.GetServer().GetHealthCheckService()->SetServingStatus(
+                  false);
+            }
+            checking = false;
+          }
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:568]: what if status is not okay? We just retry forever?

File: src/ray/raylet/node_manager.cc [hunk 7]
```diff
@@ -541,6 +541,35 @@ ray::Status NodeManager::RegisterGcs() {
...
+        RAY_CHECK_OK(gcs_client_->Nodes().AsyncCheckSelfAlive([this](auto status,
+                                                                     auto alive) mutable {
+          if (status.ok()) {
+            if (!alive) {
+              // GCS think this raylet is dead. Set the raylet unhealthy.
+              RAY_LOG(WARNING)
+                  << "GCS consider this node to be dead. Set the status to be unhealthy";
+              node_manager_server_.GetServer().GetHealthCheckService()->SetServingStatus(
+                  self_node_id_.Hex(), false);
+              node_manager_server_.GetServer().GetHealthCheckService()->SetServingStatus(
```
Comment (rkooo567) [inline src/ray/raylet/node_manager.cc:564]: what's the consequence of this btw? Is this terminating raylet eventually? 

Wonder if we should just RAY_LOG(FATAL) here?

**Review by rkooo567 — COMMENTED** [review]
Some questions around retry protocol!

File: src/ray/raylet/node_manager.cc [hunk 8]
```diff
@@ -541,6 +541,35 @@ ray::Status NodeManager::RegisterGcs() {
         RayConfig::instance().raylet_check_gc_period_milliseconds(),
         "NodeManager.CheckGC");
   }
+  // Raylet periodically check whether it's alive in GCS.
+  // For failure cases, GCS might think this raylet dead, but this
+  // failure still think it's alive.
```
Comment (jjyao) [inline src/ray/raylet/node_manager.cc:546]:
```suggestion
  // raylet still think it's alive.
```

**Review by jjyao — COMMENTED** [review]
Could you given a concrete example when this can happen in the PR description?

File: src/ray/gcs/gcs_client/accessor.cc (hunk 3 above)
Comment (iycheng) [reply src/ray/gcs/gcs_client/accessor.cc:479]: I agree, but the existing code path only accept the address. I think it still should work because no two raylets can start on the same addresses. (port conflict?)

File: src/ray/raylet/node_manager.cc (hunk 6 above)
Comment (iycheng) [reply src/ray/raylet/node_manager.cc:568]: Yes, if GCS is down for a long time, raylet will crash. 
Status not ok => GCS not reachable => Raylet crash eventually

File: src/ray/raylet/node_manager.cc (hunk 7 above)
Comment (iycheng) [reply src/ray/raylet/node_manager.cc:564]: No, we just make it unhealthy so that the management system will take care of the failure. Blindly kill the raylet will make it lose all the tasks and actors. For Serve HA workloads, this is bad.

File: src/ray/gcs/gcs_client/accessor.cc (hunk 3 above)
Comment (jjyao) [reply src/ray/gcs/gcs_client/accessor.cc:479]: When you restart the raylet, node id is guaranteed to be different but ip+port can be reused, not sure if it will cause issues.

(Not this PR) I think we should change the existing code path to also use node id?

**Review by rkooo567 — APPROVED** [review]

File: src/ray/gcs/gcs_client/accessor.cc (hunk 3 above)
Comment (iycheng) [reply src/ray/gcs/gcs_client/accessor.cc:479]: > When you restart the raylet, node id is guaranteed to be different but ip+port can be reused, not sure if it will cause issues.

I don't think it'll cause issue for this PR. Then this node is alive and GCS will report it's alive.


> (Not this PR) I think we should change the existing code path to also use node id?

I think it depends on the actual use case. Node id and ip+port both have useful cases. When you know a node has ip+port and you want to check whether the node is alive, just use ip+port.

node id is more internal concept for ray which might be more useful.

File: src/ray/raylet/node_manager.cc (hunk 7 above)
Comment (rkooo567) [reply src/ray/raylet/node_manager.cc]: Btw, I still don't know what's going to happen if we set this unhealthy. When you say "management systems", you meant kuberay? What's going to happen if this happens in VM autoscaler?

I think this implied behavior needs to be documented to be maintainable.

**Comment by iycheng** [comment]
Discussed with @rkooo567 offline and I'll change it to kill given that:

- This case shouldn't happen frequently since the assumption is that DB is HA.
- For the rest cases, it's the setup issue, for example, the user restart a GCS which doesn't have a DB at the back.

Killing makes things simple and reduce the dependence of external system. Change it to kill for now and we'll change it back if needed.
