### PR TITLE
[core] Fix autoscaler RAY_CHECK when GcsAutoscalerStateManager is out of sync with NodeManager

### LINKED ISSUE #56995: [Core] check failure in gcs autoscaler
### What happened + What you expected to happen

While trying to debug another check_failure in the pubsub, I created a dummy pr #56970 to introduce additional RAY_CHECKs in the core worker code to confirm my guess on why it was happening. This actually result in a different check failure happening in the GCS here: https://github.com/ray-project/ray/blob/bc27a3293d4eb9dad842743dd533246c7c195565/src/ray/gcs/gcs_autoscaler_state_manager.cc#L377 hence there was probably a change that was picked up in between 2.49 and this dummy pr that is causing this issue. 

### Versions / Dependencies

python 3.12, after ray 2.49

### Reproduction script

git clone git@github.com:anyscale/examples.git
cd examples
git checkout dedup
cd deduplication
anyscale login
anyscale job submit -f job.yaml

make sure to modify the Dockerfile to contain the lines:
RUN pip uninstall -y ray && pip install https://ray-ci-artifact-pr-public.s3.us-west-2.amazonaws.com/782d0ff5dca242f56e8128d761c8ff387fdee4f9/tmp/artifacts/.whl/.whl/ray-3.0.0.dev0-cp312-cp312-manylinux2014_x86_64.whl

### Issue Severity

None

### PR DESCRIPTION
**Pull request by ZacAttack**
## Why are these changes needed?

This is a fix for #56995 which was a regression introduced by change #56351 .  This change rendered it so that listener callbacks were no longer triggered synchronously with node updates.  This means there exists a period of time where node resource information is out of sync with node entries in the GcsNodeManager.  This change introduces an auto repair attempt prior to triggering the ray check.

## Related issue number

Closes #56995 

## Checks

- [ ] I've signed off every commit(by using the -s flag, i.e., `git commit -s`) in this PR.
- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
    - [ ] I've added any new APIs to the API Reference. For example, if I added a
           method in Tune, I've added it in `doc/source/tune/api/` under the
           corresponding `.rst` file.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

---

> [!NOTE]
> Handle out-of-order node additions by populating missing resource state on-the-fly and skip duplicate OnNodeAdd; add test for GetClusterStatus with out-of-order node add.
> 
> - **Autoscaler (GCS)**:
>   - Auto-repair in `GetNodeStates`: if `node_resource_info_` lacks an alive `node`, call `OnNodeAdd` to populate before proceeding.
>   - Prevent duplicate processing in `OnNodeAdd` by early-return when `node_resource_info_` already contains the `node_id`.
> - **Tests**:
>   - Add `AddNodeToNodeManagerOnly` helper and `TestHandleGetClusterStatusWithOutOfOrderNodeAdd` to validate cluster status when node add/order is out-of-sync.
> - **Misc**:
>   - Minor comment cleanup in `gcs_server.cc`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit eef8ad2088ca9fe64d06ff621a45e8307747660b. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: src/ray/gcs/gcs_autoscaler_state_manager.cc [hunk 1]
```diff
@@ -268,8 +268,11 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
 }
 
 void GcsAutoscalerStateManager::OnNodeAdd(const rpc::GcsNodeInfo &node) {
-  RAY_CHECK(thread_checker_.IsOnSameThread());
```
Comment (jjyao) [inline src/ray/gcs/gcs_autoscaler_state_manager.cc:271]: Why removing this? I think GcsAutoscalerStateManager is not thread safe?

Comment (jjyao) [inline src/ray/gcs/gcs_autoscaler_state_manager.cc:271]: Why removing this check?

File: src/ray/gcs/gcs_autoscaler_state_manager.cc [hunk 2]
```diff
@@ -268,8 +268,11 @@ void GcsAutoscalerStateManager::GetClusterResourceConstraints(
...
   NodeID node_id = NodeID::FromBinary(node.node_id());
+  if (node_resource_info_.contains(node_id)) {
+    // early termination as we already know about this node
```
Comment (jjyao) [inline src/ray/gcs/gcs_autoscaler_state_manager.cc:274]: Can you comment on when this can happen

File: src/ray/gcs/gcs_autoscaler_state_manager.cc [hunk 3]
```diff
@@ -372,8 +375,18 @@ void GcsAutoscalerStateManager::GetNodeStates(
 
     auto const node_id = NodeID::FromBinary(node_state_proto->node_id());
     // The node is alive. We need to check if the node is idle.
-    auto const node_resource_iter = node_resource_info_.find(node_id);
-
+    auto node_resource_iter = node_resource_info_.find(node_id);
+
```
Comment (jjyao) [inline src/ray/gcs/gcs_autoscaler_state_manager.cc:380]: Hmm, seems there is another bug: we never remove dead node from `node_resource_info_`

**Review by jjyao — COMMENTED** [review]
Have we checked all other listeners and see if similar problems exist.

**Review by edoakes — COMMENTED** [review]
This one definitely needs a unit test for autoscaler state manager.

Also, for posterity, I was auditing other interactions between autoscaling manager & node manager. The only other place where autoscaling manager calls into node manager is in [HandleDrainNode](https://github.com/ray-project/ray/blob/4865a2b40753ce94fb40741461941ae8c26bff01/src/ray/gcs/gcs_autoscaler_state_manager.cc#L476).

At first glance it looks like there might be the potential for a race condition where `gcs_autoscaler_manager_->HandleDrainNode` is invoked concurrently with `gcs_node_manager_->HandleRegisterNode`. If that happened, autoscaler manager might mistakenly mark the node as drained without actually pinging the Raylet to initiate draining. However, this could only happen if the client attempts to drain the node before receiving the response to `HandleRegisterNode`. So we rely on client-side serialization to avoid this one. I'm not actually sure if that is guaranteed to never happen though; it could be that we provide the user with the node ID prior to getting the `RegisterNode` response.

File: src/ray/gcs/gcs_autoscaler_state_manager.cc (hunk 1 above)
Comment (ZacAttack) [reply src/ray/gcs/gcs_autoscaler_state_manager.cc:271]: This check is honestly kind of a bad check.  It doesn't make sense to enforce the same thread on a callback.

File: src/ray/gcs/gcs_autoscaler_state_manager.cc (hunk 2 above)
Comment (ZacAttack) [reply src/ray/gcs/gcs_autoscaler_state_manager.cc:274]: This happens exactly in this change.  Essentially the bug is that the callback is scheduled on the io_context AFTER the call which throws the check.  So we add an auto repair.  So that call to AddNode can come in before the callback is triggered.

File: src/ray/gcs/gcs_autoscaler_state_manager.cc (hunk 3 above)
Comment (ZacAttack) [reply src/ray/gcs/gcs_autoscaler_state_manager.cc:380]: No we do.  It's in the base class header implementation (but I had the same impression as you initially).

**Comment by ZacAttack** [comment]
> This one definitely needs a unit test for autoscaler state manager.
> 
> Also, for posterity, I was auditing other interactions between autoscaling manager & node manager. The only other place where autoscaling manager calls into node manager is in [HandleDrainNode](https://github.com/ray-project/ray/blob/4865a2b40753ce94fb40741461941ae8c26bff01/src/ray/gcs/gcs_autoscaler_state_manager.cc#L476).
> 
> At first glance it looks like there might be the potential for a race condition where `gcs_autoscaler_manager_->HandleDrainNode` is invoked concurrently with `gcs_node_manager_->HandleRegisterNode`. If that happened, autoscaler manager might mistakenly mark the node as drained without actually pinging the Raylet to initiate draining. However, this could only happen if the client attempts to drain the node before receiving the response to `HandleRegisterNode`. So we rely on client-side serialization to avoid this one. I'm not actually sure if that is guaranteed to never happen though; it could be that we provide the user with the node ID prior to getting the `RegisterNode` response.

@edoakes  I think your scenario could technically happen if the client came to know about the newly RegisteredNode via pubsub?

**EDIT:** nevermind, we publish to pubsub AFTER updating metadata.  So seems unlikely unless they were getting it out of the raylet itself somehow.

File: src/ray/gcs/gcs_autoscaler_state_manager.cc (hunk 1 above)
Comment (jjyao) [reply src/ray/gcs/gcs_autoscaler_state_manager.cc:271]: If the GcsAutoscalerStateManager is not thread safe yet then it's better to have that check explicitly and we can remove it after we make the class thread safe.

Comment (ZacAttack) [reply src/ray/gcs/gcs_autoscaler_state_manager.cc:271]: I honestly don't know if I agree.  Is this kind of protection really worth the availability of the cluster?

**Review by jjyao — APPROVED** [review]
LGTM as a patch fix

File: src/ray/gcs/gcs_autoscaler_state_manager.cc (hunk 2 above)
Comment (jjyao) [reply src/ray/gcs/gcs_autoscaler_state_manager.cc:274]: Yea, adding this as a comment is still useful for future readers to understand the motivation.
