### PR TITLE
[Core] fix idle_time_ms resetting for nodes not running tasks

### LINKED ISSUE #54372: [Core|Autoscaler|Kuberay] Cannot parallelize tasks across multiple nodes that depend on a large input arrow table
### What happened + What you expected to happen

We have come across a behavior on a Ray + KubeRay cluster where Ray schedules a remote function call, with a reference to a sizeable object as an argument, one task at a time while other tasks are waiting for scheduling even though worker nodes have already been allocated. The tasks are set up to consume most of the resources of each node, so that running multiple tasks in parallel would necessitate running across several nodes. We expect Ray to transfer the object to the other nodes and schedule the tasks there, but it seems data locality is taking precedence.

More specifically:
- Pulling a 25GB polars df from s3 and storing the ref
- Passing the ref to `[myfunc_w_ref.options(num_cpus=100).remote(ref) for _ in range(10)]` (purposely setting hints high to force 1 task per worker)
- Ray only schedules 1 `myfunc_w_ref task` at a time while the remaining 9 are waiting for scheduling even though worker nodes have already been allocated
If we do the same thing but call some `myfunc_simple` that doesn't take ref to the object then all 10 tasks get scheduled right away. 

Code to reproduce (further below) for the following steps:
1. Setting up
2. Generate and write a large dataframe to S3
3. Get reference to dataframe in objectstore
4. Attempt to process remote file in parallel with 10 tasks
Expected: All 10 tasks should be scheduled in parallel across available workers
Actual: Only 1 task runs at a time, with the remaining 9 waiting for scheduling

### Versions / Dependencies

Ray 2.43.0
KubeRay v0.6.0

### Reproduction script

1. Setting up
```
import os
import numpy as np
import polars as pl
import ray
import time
RAY_ADDRESS = "ray://******:80"
AUTH_TOKEN = "******"
ray_config = {
    'address'         : f"{RAY_ADDRESS}",
    '_metadata'       : [("authorization", f"Basic {AUTH_TOKEN}")],
    'runtime_env'     : {
        "env_vars": {
            "AWS_PROFILE": "s3_user",
            "BUCKET_NAME": "some-bucket-name",
            "AWS_CONFIG_FILE": "./aws_credentials.ini",
            "AWS_SHARED_CREDENTIALS_FILE": "./aws_credentials.ini",
        },
    }
}
# Initialize Ray.
ray_context = ray.init(**ray_config)
```
2. Generate and write a large dataframe to S3
```
@ray.remote
def gen_large_df():
    LENGTH = 35_000_000
    df_tmp = pl.DataFrame(np.random.randn(10_000, 100)).lazy()
    table = pl.concat((df_tmp,)* (LENGTH // 10_000)).collect()
    size = table.estimated_size("gb")
    print("Estimated size of the DataFrame:", size)
    return table.to_arrow()

@ray.remote
def polars_write_to_object_store(df, key):
    bucket = os.environ['BUCKET_NAME']
    s3_path = f"s3://{bucket}/{key}"
    df = pl.from_arrow(df)
    df.write_parquet(s3_path)
    print(f"DataFrame written to {s3_path}")
    return s3_path

# create large dummy df
table = gen_large_df.remote()
# upload to s3/object store as parquet file
my_file_path = ray.get(polars_write_to_object_store.remote(table,"foo_large.pq"))
```
3. Get reference to dataframe in objectstore
```
@ray.remote
def read_pl_df_from_object_store(s3_path):
    df = pl.read_parquet(s3_path)
    print(f"DataFrame read from {s3_path}, shape: {df.shape}")
    return df.to_arrow()
# download from s3/object store
reference = read_pl_df_from_object_store.remote(my_file_path)
```
4. Attempt to process remote file in parallel (only 1 task runs at a time)
```
@ray.remote
def remote_call(table):
    print("Starting remote call...Running long computation")
    print(type(table))
    print(table)
    time.sleep(2.5 * 60)  # Simulate a long computation
    np.random.randn(1_000_000, 100) # doing something to ensure some computation is done
    table = pl.from_arrow(table).head().with_columns(hello=pl.lit("hello"))
    size = table.estimated_size("gb")
    print("updated DataFrame size:", size)
    return table

# process the downloaded file in parallel
result = [remote_call.options(num_cpus= 100, memory=1024**3 * 100).remote(reference) for _ in range(10)]
result = [ray.get(r) for r in result]
```
We have the following autoscaler settings:
```
 enableInTreeAutoscaling: true
  autoscalerOptions:
    env:
    - name: TZ
      value: America/New_York
    # autoscale 1 container first, then autoscale the rest of the containers, per multi-tenancy
    upscalingMode: Conservative
    # idleTimeoutSeconds: 60
    # autoscaler sidecar image, that matches the ray head image ray version, and ray autoscaler
    image: "{{ artifactory }}/rayproject/ray:{{ ray_version }}-py39-gpu"
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "500m"
        memory: "512Mi"
      requests:
        cpu: "500m"
        memory: "512Mi"
```

### Issue Severity

None

### LINKED ISSUE #60546: [Core]  Nodes fail to scale down due to idle_time_ms resetting
### What happened + What you expected to happen

After upgrading from Ray 2.47.1 (autoscaler v1) to 2.53.0 (autoscaler v2), we're seeing the cluster fail to properly scale down idle nodes. `ray status -v` shows idle_time_ms on idle nodes resetting to 0 every few seconds, despite no new tasks being scheduled on those nodes. This reset appears to be correlated with the addition of new tasks "Waiting for scheduling." This prevents proper scale-down since idle nodes never reach the idle_timeout_s threshold during periods of heavy load. 

**Expected**: idle_time_ms should monotonically increase on a node unless a new task is actually scheduled on that node.
**Actual**: idle_time_ms resets with the addition of new tasks, even if those tasks are not scheduled on that node

[raylet.txt](https://github.com/user-attachments/files/24894990/raylet.txt)
[gcs.txt](https://github.com/user-attachments/files/24894991/gcs.txt)

### Versions / Dependencies

- python 3.12.9
- ray 2.53.0
- cluster: AWS, docker containerized, heterogenous 

### Reproduction script

```
import time
import ray
ray.init()

@ray.remote(num_cpus=0, resources={"custom_resource": 1})
def prior_task():
    time.sleep(10)

@ray.remote(num_cpus=0.1)
def leaf(duration: float) -> None:
    time.sleep(duration)

@ray.remote(num_cpus=0.1)
def parent() -> None:
    ray.get([leaf.remote(5) for _ in range(5)])

@ray.remote(num_cpus=0.1)
def grandparent() -> None:
    while True:
        ray.get([parent.remote() for _ in range(5)])

if __name__ == "__main__":
    # simulate scaling up cluster, cpu=0 + custom resource chosen
    # to eliminate rescheduling
    ray.get([prior_task.remote() for _ in range(2)])
    # will see nodes from prior tasks idle duration fresh as new tasks are
    # waiting for scheduling
    ray.get([grandparent.remote() for _ in range(10)])
```

### Issue Severity

High: It blocks me from completing my task.

### PR DESCRIPTION
**Pull request by sampan-s-nayak**
## Description
In autoscaler v2, idle nodes fail to scale down because `idle_time_ms` resets to 0 every few seconds (in environments submitting a large number of tasks). The root cause is that when a task enters the scheduling queue on one node, the `PULLING_TASK_ARGUMENTS` footprint is marked busy on the node where the lease request arrives. If the task gets spilled to another node, calling `MarkFootprintAsIdle()` resets the idle time to `Now()` instead of preserving the original idle duration.

This happens because:

`MarkFootprintAsBusy(PULLING_TASK_ARGUMENTS)` is called eagerly even before the task is fully committed to run on the node (this was done to fix: https://github.com/ray-project/ray/issues/54372 pr: https://github.com/ray-project/ray/pull/57928) The task may be spilled to a different node before running to completion, When this happens (and when the queue is empty)  `MarkFootprintAsIdle(PULLING_TASK_ARGUMENTS)` is called which sets idle time to `Now()`. The node's idle counter effectively resets even though no actual work was performed. in high task submission environments, repeatedly resetting idle time can lead to slow node scale downs.

The fix:
introduced `MaybeMarkFootprintAsBusy()` for speculative/eager busy marking that saves the previous idle time. When `MarkFootprintAsIdle()` is called later:

If no actual work happened (task was spilled), the saved idle time is restored
If actual work happened (`NODE_WORKERS` was marked busy), the saved time is cleared and idle time resets to `Now() `as expected

## Related issues
Fixes #60546

### CODE REVIEW

**Comment by edoakes** [comment]
@rueian PTAL

File: src/ray/raylet/scheduling/local_resource_manager.h [hunk 1]
```diff
@@ -224,6 +231,11 @@ class LocalResourceManager : public syncer::ReporterInterface {
 
   /// A map storing when the resource was last idle.
   absl::flat_hash_map<WorkArtifact, std::optional<absl::Time>> last_idle_times_;
+  /// Saved idle times for footprints marked busy via MaybeMarkFootprintAsBusy().
+  /// Used to restore idle time when the speculative busy state is cleared.
+  absl::flat_hash_map<WorkFootprint, absl::Time> saved_footprint_idle_times_;
```
Comment (rueian) [inline src/ray/raylet/scheduling/local_resource_manager.h]: Is it possible that we merge the 2 maps? I think this should save us some lookup costs.

```c
struct FootprintIdleTimes {
  std::optional<absl::Time> idle_ts;
  std::optional<absl::Time> saved_ts;
};

absl::flat_hash_map<WorkArtifact, IdleTimes> last_idle_times_;
```

**Comment by sampan-s-nayak** [comment]
@rueian addressed comment, PTAL

File: src/ray/raylet/scheduling/local_resource_manager.cc [hunk 2]
```diff
@@ -124,19 +126,69 @@ void LocalResourceManager::FreeTaskResourceInstances(
...
+
+  // If the footprint is already busy, do nothing.
+  if (it != idle_time_states_.end() && !it->second.current.has_value()) {
+    return;
+  }
+
+  // If the footprint was idle, save its idle time.
+  if (it != idle_time_states_.end()) {
+    // It must have a value because we checked for the busy case above.
+    it->second.saved = it->second.current.value();
```
Comment (rueian) [inline src/ray/raylet/scheduling/local_resource_manager.cc:157]: Hi @sampan-s-nayak, do we need to save the speculative timestamp for WorkFootprint::NODE_WORKERS? Won't this cause the old idle time to be restored when calling MarkFootprintAsIdle on an actual work?

Comment (rueian) [reply src/ray/raylet/scheduling/local_resource_manager.cc:157]: I think we'd better add a check here to only save the speculative timestamp for `PULLING_TASK_ARGUMENTS`, even if we call MaybeMarkFootprintAsBusy only on `PULLING_TASK_ARGUMENTS`, otherwise the `item == WorkFootprint::NODE_WORKERS` check in MarkFootprintAsBusy looks weird. Or should we combine MaybeMarkFootprintAsBusy and MarkFootprintAsBusy to avoid confusion?

Comment (sampan-s-nayak) [reply src/ray/raylet/scheduling/local_resource_manager.cc:157]: >do we need to save the speculative timestamp for WorkFootprint::NODE_WORKERS

currently we dont, and we probably wont need to do it in the future either

>otherwise the item == WorkFootprint::NODE_WORKERS check in MarkFootprintAsBusy looks weird

I can remove this check, and clear all saved idle times (regardless of footprint). I had added this check just to ensure tighter controls but it is really not needed. I feel we should keep `MaybeMarkFootprintAsBusy()` generic and not restricted to just `PULLING_TASK_ARGUMENTS`.

Ill make this change and add a comment around this block.

> should we combine MaybeMarkFootprintAsBusy and MarkFootprintAsBusy to avoid confusion?

I kept them separate to avoid confusion.

**Review by rueian — APPROVED** [review]

File: src/ray/raylet/scheduling/local_resource_manager.cc (hunk 2 above)
Comment (rueian) [reply src/ray/raylet/scheduling/local_resource_manager.cc:157]: Thanks, LGTM! cc @edoakes for merging!
