### PR TITLE
[Core]Fix ray.kill doesn't cancel pending actor bug

### LINKED ISSUE #13214: [core] ray.kill pending actor doesn't cancel the actor creation task
### What is the problem?

Currently, `ray.kill` will silently fail if the actor has not already been started. This appears to be because we try to kill actors directly (via direct actor transport), but now GCS is responsible for scheduling/creating actors, so the actor's owner can't easily cancel the pending lease request. 

Here's a simple reproduction which shows the lease request is still infeasible in a raylet.

```
import ray
from ray._raylet import GlobalStateAccessor
import time

cluster = ray.init()

global_state_accessor = GlobalStateAccessor(
    cluster["redis_address"], ray.ray_constants.REDIS_DEFAULT_PASSWORD)
global_state_accessor.connect()


@ray.remote(resources={"WORKER": 1.0})
class ActorA:
    pass

a = ActorA.remote()
ray.kill(a) # do not wait until it starts

while True:
    message = global_state_accessor.get_all_resource_usage()
    if message is not None:
        resource_usage = ray.gcs_utils.ResourceUsageBatchData.FromString(
            message)
        print(resource_usage)
    else:
        print(message)
    time.sleep(1)
```

cc @ericl 

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
Please provide a short code snippet (less than 50 lines if possible) that can be copy-pasted to reproduce the issue. The snippet should have **no external library dependencies** (i.e., use fake or mock data / environments):

If the code snippet cannot be run by itself, the issue will be closed with "needs-repro-script".

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by ffbin**
## Why are these changes needed?
Currently, ray.kill doesn't cancel pending actor creation request in raylet. So we add `DestroyActor` api in gcs and call `lease_client->CancelWorkerLease` in gcs actor scheduler to cancel actor creation request.

## Related issue number
https://github.com/ray-project/ray/issues/13214#issuecomment-755018369

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 1]
```diff
@@ -127,13 +127,26 @@ std::vector<ActorID> GcsActorScheduler::CancelOnNode(const NodeID &node_id) {
...
+  const auto &iter = alive_nodes.find(node_id);
+  if (iter != alive_nodes.end()) {
+    const auto &node_info = iter->second;
+    rpc::Address address;
+    address.set_raylet_id(node_info->node_id());
+    address.set_ip_address(node_info->node_manager_address());
+    address.set_port(node_info->node_manager_port());
+    auto lease_client = GetOrConnectLeaseClient(address);
+    lease_client->CancelWorkerLease(
+        task_id, [](const Status &status, const rpc::CancelWorkerLeaseReply &reply) {});
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:148]: Is every other change necessary other than this part? I thought this would be sufficient?

Comment (ffbin) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:148]: Other changes is necessary, otherwise GCS will not cancel the actor, because it will not cancel the worker until the actor is successfully created.

**Review by wuisawesome — APPROVED** [review]
Looks reasonable to me, but I'll defer to @rkooo567 since he knows more about the actor lifecycle code

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 1 above)
Comment (rkooo567) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:148]: I am confused. The CancelLeasingRequest is invoked by pubsub anyway right? And the current solution will still not cancel the entry in the raylet if no_restart is True.

**Review by rkooo567 — COMMENTED** [review]
@ffbin I am still confused why we need to distinguish no_restart=True/False. In both cases, we still should cancel queued entry from the raylet because GCS will send a new lease request even when it restart?

**Comment by ffbin** [comment]
> I am still confused why we need to distinguish no_restart=True/False. In both cases, we still should cancel queued entry from the raylet because GCS will send a new lease request even when it restart?

If no_restart=True, we  just need to destroy the actor. If no_restart=False, there are two situations. One is that an actor can be scheduled. At present, raylet will trigger a kill worker to restart the actor after the actor is created. Another case is that the actor resource is not satisfied and cannot be scheduled temporarily. When raylet finds that there are nodes in the cluster that can schedule actors, it will return the corresponding node information to GCS, so we don't need to go to cancal leasing request.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 1 above)
Comment (ffbin) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:148]: If no_restart is True, the current solution will cancel the entry in the raylet. The CancelLeasingRequest is invoked only by rpc.

**Comment by rkooo567** [comment]
We should just make sure both `infeasible_requests_queue` and  `len(resource_demand)` are 0 regardless of no_restart after we run Alex's script (hence the test cases you wrote seems to be wrong). I really think no_restart is unrelated to this problem. Restart is just handled by the GCS server, and the only problem is the task entry is not removed in a queue when the actor is killed.

**Comment by rkooo567** [comment]
Lmk if I am missing something!

**Comment by ffbin** [comment]
> We should just make sure both `infeasible_requests_queue` and `len(resource_demand)` are 0 regardless of no_restart after we run Alex's script (hence the test cases you wrote seems to be wrong). I really think no_restart is unrelated to this problem. Restart is just handled by the GCS server, and the only problem is the task entry is not removed in a queue when the actor is killed.

@rkooo567 If no_restart=False, `infeasible_requests_queue` should be 1. Because the actor needs to be scheduled, but the cluster resource cannot meet the requirement.

**Comment by rkooo567** [comment]
In that case, GCS will reschedule actors right? If so, the infeasible queue should be 0.

**Comment by rkooo567** [comment]
Or does GCS remember it already sent a lease request and resume from there?

**Comment by rkooo567** [comment]
I think we can verify what's the right behavior with this type of test case;

- Start an actor with max_restarts = 10
- Make it fail 11 times.
- Make sure the infeasible task queue length is 0 after

**Comment by ffbin** [comment]
> In that case, GCS will reschedule actors right? If so, the infeasible queue should be 0.

I don't understand why the infeasible queue should be 0.

**Comment by rkooo567** [comment]
Can you verify it with this test case? https://github.com/ray-project/ray/pull/13254#issuecomment-762059988

**Comment by ffbin** [comment]
> Can you verify it with this test case? [#13254 (comment)](https://github.com/ray-project/ray/pull/13254#issuecomment-762059988)

Ok, i will add a testcase, thx

**Comment by rkooo567** [comment]
Btw, I understood what you meant now. But I think it is anyway good to have that test case.

Can I also ask you one favor? Do you mind removing this, 
```
  if (no_restart) {
    RAY_CHECK_OK(gcs_client_->Actors().AsyncDestroyActor(actor_id, nullptr));
  } else {
    direct_actor_submitter_->KillActor(actor_id, force_kill, no_restart);
  }
```

and just use `direct_actor_submitter_->KillActor(actor_id, force_kill, no_restart);` and see if it will pass or fail test cases?

**Comment by ffbin** [comment]
> Btw, I understood what you meant now (you are right it should be 1 after that because the GCS rescheduled an actor). But I think it is anyway good to have that test case.
> 
> Can I also ask you one favor? Do you mind removing this,
> 
> ```
>   if (no_restart) {
>     RAY_CHECK_OK(gcs_client_->Actors().AsyncDestroyActor(actor_id, nullptr));
>   } else {
>     direct_actor_submitter_->KillActor(actor_id, force_kill, no_restart);
>   }
> ```
> 
> and just use `direct_actor_submitter_->KillActor(actor_id, force_kill, no_restart);` and see if it will pass or fail test cases?

If we call `direct_actor_submitter_->KillActor(actor_id, force_kill, no_restart);` , it will kill the worker of actor after receiving the  subscription message (actor is created).

**Comment by rkooo567** [comment]
Discussed offline; The conclusion is we need to handle the edge case where num_retires > max_retries. Destroy actor should go to GCS if we don't need to restart because ray.kill will never be invoked until actor is created.

File: src/ray/protobuf/gcs_service.proto [hunk 2]
```diff
@@ -92,6 +92,19 @@ message GetAllActorInfoReply {
   repeated ActorTableData actor_table_data = 2;
 }
 
+message KillActorViaGcsRequest {
```
Comment (ffbin) [inline src/ray/protobuf/gcs_service.proto:95]: core_worker.proto has `message KillActorRequest`. To avoid duplicate names, we name it `KillActorViaGcsRequest`. Let me know if you have a better name.

**Comment by ffbin** [comment]
Hey @rkooo567 This PR can be reviewed, pls help take a look, thanks.

**Comment by ffbin** [comment]
Java testcase has bug, i will fix it.

**Comment by rkooo567** [comment]
@ffbin Can you remove the tag after fixing the issue?

**Comment by ffbin** [comment]
> @ffbin Can you remove the tag after fixing the issue?

Yeah, thanks.

File: src/ray/protobuf/gcs_service.proto (hunk 2 above)
Comment (rkooo567) [reply src/ray/protobuf/gcs_service.proto:95]: Can you add a comment in this message what's the difference from a regular killActor?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc [hunk 3]
```diff
@@ -932,15 +929,47 @@ void GcsActorManager::RemoveActorFromOwner(const std::shared_ptr<GcsActor> &acto
...
+  const auto &worker_id = actor->GetWorkerID();
+  auto node_it = created_actors_.find(node_id);
+  if (node_it != created_actors_.end() && node_it->second.count(worker_id)) {
+    // The actor has already been created. Destroy the process by force-killing
+    // it.
+    NotifyCoreWorkerToKillActor(actor, force_kill, no_restart);
+  } else {
+    const auto &task_id = actor->GetCreationTaskSpecification().TaskId();
+    CancelActorInScheduling(actor, task_id);
+    ReconstructActor(actor_id, /*need_reschedule=*/true);
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_manager.cc:969]: Do we need this? Isn't it automatically triggered by worker failure listener?

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc [hunk 4]
```diff
@@ -238,6 +252,16 @@ void GcsActorScheduler::LeaseWorkerFromNode(std::shared_ptr<GcsActor> actor,
           }
 
           if (status.ok()) {
+            if (reply.worker_address().raylet_id().empty() &&
```
Comment (rkooo567) [inline src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:255]: I don't see any code that add this logic. Did it exist from before? How did you find this issue?

File: src/ray/gcs/gcs_server/gcs_actor_manager.cc (hunk 3 above)
Comment (ffbin) [reply src/ray/gcs/gcs_server/gcs_actor_manager.cc:969]: Yeah ,we need this, because the task is not successfully scheduled, there will be no worker failure.

File: src/ray/gcs/gcs_server/gcs_actor_scheduler.cc (hunk 4 above)
Comment (ffbin) [reply src/ray/gcs/gcs_server/gcs_actor_scheduler.cc:255]: We cancel the actor creation request, so the raylet id of the returned reply is empty. There was no cancel logic before.

File: src/ray/protobuf/gcs_service.proto (hunk 2 above)
Comment (ffbin) [reply src/ray/protobuf/gcs_service.proto:95]: Ok, thanks.

**Review by rkooo567 — APPROVED** [review]
Feel free to merge it once tests pass!

**Comment by ffbin** [comment]
Hey @rkooo567 , pls help double check whether the failed ci job is related, thx :)

**Comment by rkooo567** [comment]
The serve failures might be related. I cannot find the failure from the flaky dashboard, and it happens on both Mac & Linux builds. Can you merge the latest master?

**Comment by ffbin** [comment]
> The serve failures might be related. I cannot find the failure from the flaky dashboard, and it happens on both Mac & Linux builds. Can you merge the latest master?

I will take a look, thanks.

**Comment by wuisawesome** [comment]
Looks like this broke test_placement_group

**Comment by ffbin** [comment]
> Looks like this broke test_placement_group

Yeah, i will fix it. I'm still fixing the problem of `test_queue.py`.

**Comment by ffbin** [comment]
> Looks like this broke test_placement_group

@rkooo567 @wuisawesome It seems that the failure of `test_queue.py` and `test_failure.py` is not related to this pr.

**Comment by rkooo567** [comment]
Ping me if it is ready!

**Comment by ffbin** [comment]
> Ping me if it is ready!

Hey @rkooo567 I think it is ready, pls help take a look, thx

**Comment by rkooo567** [comment]
@ffbin ASAN build failing

**Comment by ffbin** [comment]
> @ffbin ASAN build failing

@rkooo567 ASAN build is ok now.

**Comment by ffbin** [comment]
@rkooo567 I will merge this PR, if you have any questions, please let me know, thx :)
