### PR TITLE
[core] Admission control for pulling objects to the local node

### LINKED ISSUE #12663: [Object Spilling] Thrashing when there are large number of dependencies for many tasks
### What is the problem?

Discovered from the shuffling workload: https://gist.github.com/ericl/d419c6373928b4b7c8739738262da287

When there are many tasks with a large number of dependencies, tasks are not properly scheduled because they are waiting for dependencies to be local, but some of the dependencies are evicted (to make space) before every dependency becomes local. These dependencies are restored again, but after that, it is re-evicted. This leads all of the tasks to be in the waiting state and not executed forever (which causes the hanging). 

There might be many solutions, but one of them is to temporarily pin the restored objects until it is used by tasks. Indeed, this sort of thrashing behavior can happen even for non-object spilling scenarios (pull->evicted->pull->evicted), so this can help to optimize the object pulling in general. 

### Reproduction (REQUIRED)
Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/master/installation.html).

### PR DESCRIPTION
**Pull request by stephanie-wang**
## Why are these changes needed?

Previously, we would fetch all requested objects simultaneously, including queued tasks' arguments and `ray.get` or `ray.wait` requests from local workers. If the total size was greater than the node's capacity, this could result in starvation.

This adds admission control when choosing which objects to fetch to the local node. This makes a couple changes:
1. Pull requests are served in FIFO order.
2. The total size of objects actively fetched is kept under the node's current capacity (defined as the object store's total capacity - size of pinned objects).
3. We do not start pulling an object until its size is known. This is to prevent flooding the object manager with incoming objects when many requests are made simultaneously for different objects.

The algorithm is implemented by finding the longest contiguous prefix of the current request queue whose total size is known and under the current capacity. Object size is now attached to all object table replies. The total set of objects needed by the chosen requests will be actively pulled or restored. The current capacity is dynamically and asynchronously updated at every ObjectManager tick.

## Related issue number

Closes #12663.

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

To test this, the Python tests submit tasks with several arguments, and there is only enough memory to run one task at a time. On master, this timed out, but the test would finish in ~5s if the Python code is modified to manually submit and get one task at a time. With this PR, the run time now matches the version with manual admission control.

### CODE REVIEW

File: src/ray/object_manager/pull_manager.cc [hunk 1]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+  // should not activate the bundle, since it may put us over the available
+  // capacity.
+  for (const auto &ref : next_request_it->second) {
+    auto obj_id = ObjectRefToId(ref);
+    const auto it = object_pull_requests_.find(obj_id);
+    RAY_CHECK(it != object_pull_requests_.end());
+    if (!it->second.object_size_set) {
+      RAY_LOG(DEBUG) << "No size for " << obj_id << ", canceling activation for pull "
+                     << next_request_it->first;
+      return false;
```
Comment (rkooo567) [inline src/ray/object_manager/pull_manager.cc:65]: Did I understand correctly that this means if the size of the head of the queue is not known, we don't pull objects anymore?

File: src/ray/object_manager/pull_manager.cc [hunk 2]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+  // Activate the bundle.
+  for (const auto &ref : next_request_it->second) {
+    auto obj_id = ObjectRefToId(ref);
+    bool start_pull = active_object_pull_requests_.count(obj_id) == 0;
+    active_object_pull_requests_[obj_id].insert(next_request_it->first);
+    if (start_pull) {
+      RAY_LOG(DEBUG) << "Activating pull for object " << obj_id;
+      // This is the first bundle request in the queue to require this object.
+      // Add the size to the number of bytes being pulled.
+      // NOTE(swang): The size could be 0 if we haven't received size
```
Comment (rkooo567) [inline src/ray/object_manager/pull_manager.cc:78]: If size is not known (0), is it not reaching this line due to 63? Is there anything I am missing?

File: src/ray/object_manager/pull_manager.cc [hunk 3]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+  for (const auto &ref : request_it->second) {
+    auto obj_id = ObjectRefToId(ref);
+    RAY_CHECK(active_object_pull_requests_[obj_id].erase(request_it->first));
+    if (active_object_pull_requests_[obj_id].empty()) {
+      RAY_LOG(DEBUG) << "Deactivating pull for object " << obj_id;
+      auto it = object_pull_requests_.find(obj_id);
+      RAY_CHECK(it != object_pull_requests_.end());
+      num_bytes_being_pulled_ -= it->second.object_size;
+      active_object_pull_requests_.erase(obj_id);
+      if (object_ids_to_cancel) {
```
Comment (rkooo567) [inline src/ray/object_manager/pull_manager.cc:107]: Why not just `RAY_CHECK(object_ids_to_cancell != nullptr)`?

File: src/ray/object_manager/pull_manager.cc [hunk 4]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+    }
+  }
+
+  // If this was the last active request, update the pointer to its
+  // predecessor, if one exists.
+  if (highest_req_id_being_pulled_ == request_it->first) {
+    if (request_it == pull_request_bundles_.begin()) {
+      highest_req_id_being_pulled_ = 0;
+    } else {
+      highest_req_id_being_pulled_ = std::prev(request_it)->first;
```
Comment (rkooo567) [inline src/ray/object_manager/pull_manager.cc:119]: Q: Is the map ordered?

File: src/ray/object_manager/pull_manager.cc [hunk 5]
```diff
@@ -1,20 +1,23 @@
 #include "ray/object_manager/pull_manager.h"
 
 #include "ray/common/common_protocol.h"
+#include "ray/object_manager/plasma/plasma_allocator.h"
```
Comment (rkooo567) [inline src/ray/object_manager/pull_manager.cc:4]: This doesn't seem to be used IIUC?

File: src/ray/object_manager/test/pull_manager_test.cc [hunk 6]
```diff
@@ -295,38 +322,193 @@ TEST_F(PullManagerTest, TestDeduplicateBundles) {
...
+    // The total requests that are active is under the specified capacity.
+    ASSERT_TRUE(
+        IsUnderCapacity(num_requests_expected * num_oids_per_request * object_size));
+    // This is the maximum number of requests that can be served at once that
+    // is under the capacity.
+    if (num_requests_expected < num_requests) {
+      ASSERT_FALSE(IsUnderCapacity((num_requests_expected + 1) * num_oids_per_request *
+                                   object_size));
+    }
+  }
```
Comment (rkooo567) [inline src/ray/object_manager/test/pull_manager_test.cc:445]: Can you also test the case where the whole pull requests are digested and new pull requests are queued to test this part? 
``` cpp
if (highest_req_id_being_pulled_ == request_it->first) {
    if (request_it == pull_request_bundles_.begin()) {
      highest_req_id_being_pulled_ = 0;
    } else {
      highest_req_id_being_pulled_ = std::prev(request_it)->first;
```

File: python/ray/tests/test_object_manager.py [hunk 7]
```diff
@@ -296,6 +296,83 @@ def driver():
     ray.get(driver.remote())
 
 
+@pytest.mark.timeout(30)
+def test_pull_bundles_admission_control(shutdown_only):
+    cluster = Cluster()
+    object_size = int(1e7)
+    num_objects = 10
+    num_tasks = 10
+    # Head node can fit all of the objects at once.
```
Comment (rkooo567) [inline python/ray/tests/test_object_manager.py:305]: Why is that? If we'd like to test the feature, aren't we supposed to make only 1 task to fit at a time at all nodes?

File: python/ray/tests/test_object_manager.py [hunk 8]
```diff
@@ -296,6 +296,83 @@ def driver():
...
+        ]
+        args.append(task_args)
+
+    tasks = [foo.remote(*task_args) for task_args in args]
+    ray.get(tasks)
+
+
+@pytest.mark.timeout(30)
+def test_pull_bundles_admission_control_dynamic(shutdown_only):
+    # This test is the same as test_pull_bundles_admission_control, except that
```
Comment (rkooo567) [inline python/ray/tests/test_object_manager.py:335]: This is a nice test!

**Review by rkooo567 — COMMENTED** [review]
IIRC, ray.get and ray.wait are prioritized over fetching task dependencies. (Lmk if I am wrong?) Should we add test cases for this?

File: src/ray/object_manager/pull_manager.cc [hunk 9]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+  // TODO(swang): We could return an error for requests whose total size is
+  // larger than the capacity of the memory store. This would hang right now.
+
+  if (num_bytes_available_ != num_bytes_available) {
+    RAY_LOG(DEBUG) << "Updating pulls based on available memory: " << num_bytes_available;
+  }
+  num_bytes_available_ = num_bytes_available;
+
+  std::unordered_set<ObjectID> object_ids_to_pull;
+  // While there is available capacity, activate the next pull request.
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:134]: Should we always pull at least the first bundle in the queue? Otherwise I can see the workload stalling when it is possible we can make space via object spilling.

File: src/ray/object_manager/pull_manager.cc [hunk 10]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+      // size information. Wait until we have object size information before
+      // activating this pull bundle.
+      break;
+    }
+  }
+
+  std::unordered_set<ObjectID> object_ids_to_cancel;
+  // While the total bytes requested is over the available capacity, deactivate
+  // the last pull request, ordered by request ID.
+  while (num_bytes_being_pulled_ > num_bytes_available_) {
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:167]: Nice.

File: src/ray/object_manager/pull_manager.cc [hunk 11]
```diff
@@ -39,33 +42,183 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+    DeactivatePullBundleRequest(last_request_it, &object_ids_to_cancel);
+  }
+
+  for (auto &obj_id : object_ids_to_pull) {
+    if (object_ids_to_cancel.count(obj_id) == 0) {
+      // We should begin pulling this object.
+      // NOTE(swang): We could also just wait for the next tick to pull the
+      // objects, but this would add a delay of up to one tick for any bundles
+      // of multiple objects, even when we are not under memory pressure.
+      TryToMakeObjectLocal(obj_id);
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:182]: Could we instead trigger the tick?

**Review by ericl — COMMENTED** [review]
Looks good at a high level--- some questions about the corner case handling when under memory pressure.

File: python/ray/tests/test_object_manager.py [hunk 12]
```diff
@@ -296,6 +296,83 @@ def driver():
     ray.get(driver.remote())
 
 
+@pytest.mark.timeout(30)
+def test_pull_bundles_admission_control(shutdown_only):
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply python/ray/tests/test_object_manager.py:300]: I was too lazy to figure out how to parametrize it properly :D Also, I was running into trouble where the non-head node would connect first, so the rest of the test wouldn't run properly.

File: src/ray/core_worker/reference_count.cc [hunk 13]
```diff
@@ -948,6 +948,15 @@ absl::optional<absl::flat_hash_set<NodeID>> ReferenceCounter::GetObjectLocations
   return it->second.locations;
 }
 
+size_t ReferenceCounter::GetObjectSize(const ObjectID &object_id) const {
+  absl::MutexLock lock(&mutex_);
+  auto it = object_id_refs_.find(object_id);
+  if (it == object_id_refs_.end()) {
+    return 0;
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/core_worker/reference_count.cc:955]: We should return 0 in case the object has gone out of scope, which is a valid scenario.

File: src/ray/object_manager/object_directory.cc [hunk 14]
```diff
@@ -31,13 +31,17 @@ using ray::rpc::ObjectTableData;
...
-                           std::unordered_set<NodeID> *node_ids,
-                           std::string *spilled_url) {
+                           std::unordered_set<NodeID> *node_ids, std::string *spilled_url,
+                           size_t *object_size) {
   // location_updates contains the updates of locations of the object.
   // with GcsChangeMode, we can determine whether the update mode is
   // addition or deletion.
   bool isUpdated = false;
   for (const auto &update : location_updates) {
+    if (update.size() > 0) {
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/object_manager/object_directory.cc:41]: I think it's 0 for deletion. We can add a flag instead if there are cases where the object size really is 0.

File: src/ray/object_manager/object_manager.cc [hunk 15]
```diff
@@ -203,8 +208,9 @@ uint64_t ObjectManager::Pull(const std::vector<rpc::ObjectReference> &object_ref
 
   const auto &callback = [this](const ObjectID &object_id,
                                 const std::unordered_set<NodeID> &client_ids,
-                                const std::string &spilled_url) {
-    pull_manager_->OnLocationChange(object_id, client_ids, spilled_url);
+                                const std::string &spilled_url, size_t object_size) {
+    // TODO
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/object_manager/object_manager.cc:212]: Oops, removed!

File: src/ray/object_manager/object_manager.cc [hunk 16]
```diff
@@ -819,6 +825,14 @@ void ObjectManager::Tick(const boost::system::error_code &e) {
                 << ". Please file a bug report on here: "
                    "https://github.com/ray-project/ray/issues";
 
+  // Request the current available memory from the object
+  // store.
+  plasma::plasma_store_runner->GetAvailableMemoryAsync([this](size_t available_memory) {
```
[the remark this answers is not in the document]
Comment (stephanie-wang) [reply src/ray/object_manager/object_manager.cc:830]: Yes, I don't think we currently report the available memory metric that I'm using (but maybe we should!).

File: src/ray/object_manager/pull_manager.cc (hunk 1 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:65]: Yes!

File: src/ray/object_manager/pull_manager.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:78]: Ah oops, this comment was for the other block of code. Will move it.

File: src/ray/object_manager/pull_manager.cc (hunk 3 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:107]: We don't always need to know. I only use it to prevent unnecessary object pulls when updating, since sometimes this will activate then deactivate a request that is right at the boundary of the current capacity.

File: src/ray/object_manager/pull_manager.cc (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:119]: Yes.

File: src/ray/object_manager/pull_manager.cc (hunk 5 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:4]: Yes, you're right, will remove.

File: src/ray/object_manager/test/pull_manager_test.cc (hunk 6 above)
Comment (stephanie-wang) [reply src/ray/object_manager/test/pull_manager_test.cc:445]: Hmm I think this will get covered by the cancellation tests, but let me know if there is something else you're looking for.

File: python/ray/tests/test_object_manager.py (hunk 7 above)
Comment (stephanie-wang) [reply python/ray/tests/test_object_manager.py:305]: We need to create all the objects somewhere, so we make the head node big. The worker node will try to fetch objects from the head node, but it can only fit one task at a time.

File: src/ray/object_manager/pull_manager.cc (hunk 9 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:134]: Hmm that's a good point, I'll change that and see if I can write a regression test for it.

File: src/ray/object_manager/pull_manager.cc (hunk 11 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:182]: Ah, good idea!

File: src/ray/object_manager/test/pull_manager_test.cc (hunk 6 above)
Comment (rkooo567) [reply src/ray/object_manager/test/pull_manager_test.cc:445]: Ah, if it is convered by that test, it is fine. (It was a bit hard to understand if this was tested).

File: src/ray/object_manager/pull_manager.cc (hunk 9 above)
Comment (stephanie-wang) [reply src/ray/object_manager/pull_manager.cc:126]: Actually, it turns out this doesn't work because the object store just keeps evicting other objects needed by the first bundle, so it never triggers the OOM handling. So I'm going to change this to directly trigger OOM instead.

File: python/ray/tests/test_object_manager.py (hunk 12 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply python/ray/tests/test_object_manager.py:300]: oh lol. I think you can just do like

```python3
cluster = ray_start_cluster
cluster.add_node()
cluster.wait_for_nodes()
ray.init(address=cluster.address)
cluster.add_node...
```

File: python/ray/tests/test_object_manager.py (hunk 7 above)
Comment (rkooo567) [reply python/ray/tests/test_object_manager.py:305]: Ah, I misunderstood the comment. It makes sense!

File: src/ray/core_worker/reference_count.h [hunk 17]
```diff
@@ -397,6 +397,8 @@ class ReferenceCounter : public ReferenceCounterInterface,
   absl::optional<absl::flat_hash_set<NodeID>> GetObjectLocations(
       const ObjectID &object_id) LOCKS_EXCLUDED(mutex_);
 
+  size_t GetObjectSize(const ObjectID &object_id) const;
```
Comment (rkooo567) [inline src/ray/core_worker/reference_count.h:400]: Can you write a comment? (and explain when 0 is returned?)

File: src/ray/object_manager/object_directory.cc (hunk 14 above)
[the remark this answers is not in the document]
Comment (rkooo567) [reply src/ray/object_manager/object_directory.cc:41]: Do you mind writing a comment here?

File: src/ray/object_manager/pull_manager.cc (hunk 1 above)
Comment (rkooo567) [reply src/ray/object_manager/pull_manager.cc:68]: Isn't it something we should improve in the future? (Like re-queue until sizes are known or something)?

**Review by rkooo567 — APPROVED** [review]
LGTM. A few follow up comments, but they are minor.

File: src/ray/object_manager/pull_manager.cc [hunk 18]
```diff
@@ -39,33 +42,224 @@ uint64_t PullManager::Pull(const std::vector<rpc::ObjectReference> &object_ref_b
...
+    }
+    num_bytes_needed += it->second.object_size;
+  }
+
+  // The first request in the queue is not being pulled due to lack of space.
+  // Trigger out-of-memory handling to try to make room.
+  // TODO(swang): This can hang if no room can be made. We should return an
+  // error for requests whose total size is larger than the capacity of the
+  // memory store.
+  if (get_time_() - last_oom_reported_ms_ > 1000) {
```
Comment (ericl) [inline src/ray/object_manager/pull_manager.cc:213]:
```suggestion
  if (get_time_() - last_oom_reported_ms_ > 30000) {
```

**Review by ericl — APPROVED** [review]

**Comment by stephanie-wang** [comment]
@ericl, @rkooo567, FYI:

I had to change a couple things to get the tests working:
- removed the tests under "run_object_manager_tests.sh". These tests have been useless for a while, and now we have python and unit tests that cover the code better anyway.
- disabled //:core_worker_test since it relies on the legacy plasma store and I couldn't figure out how to disable that. This test is also pretty useless since the Python tests are a superset.
- disabled the new object spilling test added in this PR. It also hangs on master, so I don't think this is a big deal.

It turns out there is a race condition causing the new object spilling test to fail that I think is non-trivial to fix. Here is the issue:
1. Task 1 requires A, task 2 requires B. We only have room for 1 object.
2. We pull A and lease the worker for task 1. At this point, we cancel the pull request for A and start the pull request for B.
3. We pull B, which evicts A. The worker executing task 1 now requests A again. We hang because we're trying to pull B first.

To break the deadlock, we need to prioritize running workers' dependencies over queued task dependencies (as @rkooo567 mentioned above). Unfortunately, this won't fix the problem of evicting A before the worker gets it. To fix that, we'd need wait to to cancel the pull manager request for A until after we were sure the worker got a ref to A, which seems pretty complicated to do right now.

So for now, I can open a second PR to break the deadlock and at least report some metrics on how often such thrashing is happening.

**Comment by ericl** [comment]
Could we pin the object A in memory until the task 1 has finished
execution? When the task 1 finishes it could do a double decrement of the
refcount to release the object.

**Comment by ericl** [comment]
Btw by pin I mean hard pin (unevictable).

**Comment by stephanie-wang** [comment]
> Could we pin the object A in memory until the task 1 has finished execution? When the task 1 finishes it could do a double decrement of the refcount to release the object.

I think that is the right approach long-term, but it's pretty complicated to do right now. The problem is that we're calculating the PullManager's available memory based on total_capacity - pinned_objects_size. If we pin pulled objects, we'll have to make sure to account for that in the available memory. Plus the available memory is reported asynchronously right now, since the object store is running in a different thread.

It seems like we need a larger refactor to really fix this problem properly.

**Comment by ericl** [comment]
Hmm wouldn't incrementing the pinned memory count and letting it get
asynchronously updated as well suffice?

I also think it's fine to let it just get asynchronously updated, the worst
that can happen is a few spurious pull failures.

**Comment by stephanie-wang** [comment]
After some offline discussion, the decision is to merge this and fix the deadlock problem by pinning pulled objects until they're no longer needed. We'll account for the pinned memory by asking for the current availability synchronously and subtracting the size of the objects pinned by the PullManager.
