### PR TITLE
Retry application-level errors

### LINKED ISSUE #17452: Support retry_exceptions option in Ray tasks
In workflows and other use cases, it is desirable to support retrying application-level exceptions.

Retry API:
```
@ray.remote(retry_exceptions=True, max_retries=3)
def f():
   raise ValueError()   # retried up to 3 times
```

Note that this is expanding the scope of the existing `max_retries` to also retry application-level exceptions.

Implementation:
We already have retry logic implemented in the owner of the task. We need to propagate an "exception" bit so that we can also retry application-level errors.

### PR DESCRIPTION
**Pull request by jjyao**
## Why are these changes needed?

Add a new option called retry_exceptions that triggers the retry of application-level errors if it's true.
## Related issue number
Closes #17452

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: cpp/src/ray/runtime/task/task_executor.cc [hunk 1]
```diff
@@ -126,7 +126,8 @@ Status TaskExecutor::ExecuteTask(
     const std::vector<ObjectID> &arg_reference_ids,
     const std::vector<ObjectID> &return_ids, const std::string &debugger_breakpoint,
     std::vector<std::shared_ptr<ray::RayObject>> *results,
-    std::shared_ptr<ray::LocalMemoryBuffer> &creation_task_exception_pb_bytes) {
+    std::shared_ptr<ray::LocalMemoryBuffer> &creation_task_exception_pb_bytes,
+    bool *application_level_error_thrown) {
```
Comment (ericl) [inline cpp/src/ray/runtime/task/task_executor.cc:130]:
```suggestion
    bool *application_level_error) {
```

(technically you "raise" in python and not throw, maybe let's avoid the term altogether)

File: python/ray/worker.py [hunk 2]
```diff
@@ -1962,12 +1963,16 @@ def decorator(function_or_class):
...
+                num_returns, max_calls, max_retries, runtime_env,
+                retry_exceptions)
 
         if inspect.isclass(function_or_class):
             if num_returns is not None:
                 raise TypeError("The keyword 'num_returns' is not "
                                 "allowed for actors.")
+            if max_retries is not None:
+                raise TypeError("The keyword 'max_retries' is not "
+                                "allowed for actor.")
```
Comment (ericl) [inline python/ray/worker.py:1975]:
```suggestion
                                "allowed for actors.")
```

File: src/ray/protobuf/common.proto [hunk 3]
```diff
@@ -213,6 +213,8 @@ message TaskSpec {
   string serialized_runtime_env = 24;
   // The concurrency group name in which this task will be performed.
   string concurrency_group_name = 25;
+  // Should we retry application-level errors as well
```
Comment (ericl) [inline src/ray/protobuf/common.proto:216]:
```suggestion
  // Whether application-level errors should be retried.
```

File: src/ray/protobuf/core_worker.proto [hunk 4]
```diff
@@ -124,6 +124,8 @@ message PushTaskReply {
   // may now be borrowing. The reference counts also include any new borrowers
   // that the worker created by passing a borrowed ID into a nested task.
   repeated ObjectReferenceCount borrowed_refs = 4;
+  // Set to true if the task ends in an error
+  bool application_level_error_thrown = 5;
```
Comment (ericl) [inline src/ray/protobuf/core_worker.proto:128]:
```suggestion
  bool application_level_error = 5;
```

File: src/ray/protobuf/core_worker.proto [hunk 5]
```diff
@@ -124,6 +124,8 @@ message PushTaskReply {
   // may now be borrowing. The reference counts also include any new borrowers
   // that the worker created by passing a borrowed ID into a nested task.
   repeated ObjectReferenceCount borrowed_refs = 4;
+  // Set to true if the task ends in an error
```
Comment (ericl) [inline src/ray/protobuf/core_worker.proto:127]:
```suggestion
  // Whether the result contains an application level error (exception).
```

**Review by ericl — COMMENTED** [review]
Can you add python unit tests (and add one for direct_actor_tranport_test if possible)?

File: cpp/src/ray/runtime/task/task_executor.cc (hunk 1 above)
Comment (jjyao) [reply cpp/src/ray/runtime/task/task_executor.cc:130]: Sure. Do we have any coding style about the naming? To me, `application_level_error` variable intuitively holds some error object instead of bool. Maybe `is_application_level_error`?

Comment (ericl) [reply cpp/src/ray/runtime/task/task_executor.cc:130]: is_application_level_error SGTM!

File: python/ray/remote_function.py [hunk 6]
```diff
@@ -100,6 +101,9 @@ def __init__(self, language, function, function_descriptor, num_cpus,
                            if max_calls is None else max_calls)
         self._max_retries = (DEFAULT_REMOTE_FUNCTION_NUM_TASK_RETRIES
                              if max_retries is None else max_retries)
+        self._retry_exceptions = (DEFAULT_REMOTE_FUNCTION_RETRY_EXCEPTIONS
```
Comment (wuisawesome) [inline python/ray/remote_function.py:104]: Can you update the doc string for the class, and the one for @ray.remote in `worker.py`?

**Review by ericl — CHANGES_REQUESTED** [review]
@jjyao code looks good, but one issue I noticed is that we don't log anything when retrying these exceptions (you at least get some warning for retried system-level errors).

How about adding a message that we're retrying with `CoreWorker::PushError`?

(btw, this is kind of related to a tech debt item where RAY_LOG(ERROR) doesn't show in console for core worker logs, but that's a bit bigger to fix: https://github.com/ray-project/ray/issues/12893)

**Review by ericl — APPROVED** [review]
Tried out locally, LGTM. One followup issue we might want to address is the exception isn't logged at all anywhere (not even in core worker logs), until retries are exhausted; however I think this shouldn't block merging.

**Review by wuisawesome — APPROVED** [review]
