### PR TITLE
[gcs] Fix resource updating incorrectly

### LINKED ISSUE #22122: [Bug] Resource demand backlog caps out at 10+ in multi-node K8s cluster
### Search before asking

- [X] I searched the [issues](https://github.com/ray-project/ray/issues) and found no similar issues.

### Ray Component

Ray Clusters

### What happened + What you expected to happen

My Setup:

I have deployed a Ray Cluster on Kubernetes with EKS. The cluster has a worker type with 15 CPUs that is always on (min_workers: 1). Other worker types include 7 CPUs, 15 CPUs, 30 CPUs.

I've also configured: `upscaling_speed=9999`, `AUTOSCALER_MAX_LAUNCH_BATCH=9999`, `AUTOSCALER_MAX_CONCURRENT_LAUNCHES=9999` as recommended here: https://github.com/ray-project/ray/issues/21683#issuecomment-1018015823

**Main Issue**:

Whenever I launch 200 tasks, the autoscaler only launches a single 7-cpu worker. After that worker is ready, it launches another single 7-cpu worker. I expect it to launch at least enough workers for 185 CPUs in the first iteration.

In the Ray Operator Pod Logs, I see `{'CPU': 1.0}: 1+ pending tasks/actors`. I imagine this should be something like "185+ pending tasks/actors"?

However, I can successfully use `ray.autoscaler.sdk.request_resources` to request 200 cpus all at once. 

---

Ray Operator Pod Logs:
`kubectl logs -f po/ray-operator-987dc99b9-47v92 | grep Resources -A 10`
```
Resources
---------------------------------------------------------------
Usage:
 0.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 (no resource demands)
py38-cu112,karpenter:2022-02-04 10:47:45,337    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.6050498485565186, '10.16.126.217': 0.6049869060516357}\n - NodeIdleSeconds: Min=0 Mean=38219 Max=76437\n - ResourceUsage: 0.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:47:45,338    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 4.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
py38-cu112,karpenter:2022-02-04 10:47:51,278    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.5087563991546631, '10.16.126.217': 0.5086848735809326}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 4.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:47:51,289    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 10.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
py38-cu112,karpenter:2022-02-04 10:47:57,323    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.4549856185913086, '10.16.126.217': 0.4549136161804199}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 10.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:47:57,324    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 15.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
py38-cu112,karpenter:2022-02-04 10:48:03,348    DEBUG gcs_utils.py:245 -- internal_kv_put b'__autoscaling_status_legacy' b"Cluster status: 1 nodes\n - MostDelayedHeartbeats: {'10.16.115.16': 0.54921555519104, '10.16.126.217': 0.5491447448730469}\n - NodeIdleSeconds: Min=0 Mean=0 Max=0\n - ResourceUsage: 15.0/15.0 CPU, 0.0 GiB/25.9 GiB memory, 0.0 GiB/10.25 GiB object_store_memory\n - TimeSinceLastHeartbeat: Min=0 Mean=0 Max=0\nWorker node types:\n - wkr-15cpu30g-ondemand: 1" True None
py38-cu112,karpenter:2022-02-04 10:48:03,350    DEBUG legacy_info_string.py:26 -- Cluster status: 1 nodes
--
Resources
---------------------------------------------------------------
Usage:
 15.0/15.0 CPU
 0.00/25.900 GiB memory
 0.00/10.249 GiB object_store_memory

Demands:
 {'CPU': 1.0}: 1+ pending tasks/actors
```

Ray Pod Description:
```
Name:         ray-operator-987dc99b9-47v92
Namespace:    karpenter
Priority:     0
Node:         ip-10-16-65-175.us-west-2.compute.internal/10.16.65.175
Start Time:   Thu, 03 Feb 2022 13:05:01 -0600
Labels:       cluster.ray.io/component=operator
              pod-template-hash=987dc99b9
Annotations:  kubernetes.io/psp: eks.privileged
Status:       Running
IP:           10.16.68.93
IPs:
  IP:           10.16.68.93
Controlled By:  ReplicaSet/ray-operator-987dc99b9
Containers:
  ray:
    Container ID:  docker://f78dc8efee6c1f8483438e325c275a281c310341a1f304f4811aa8c80d263903
    Image:         rayproject/ray:bbc64e
    Image ID:      docker-pullable://rayproject/ray@sha256:6a0520c449555a31418ed79188827553e43276db6abc1bc4341edd16dd832eb3
    Port:          <none>
    Host Port:     <none>
    Command:
      ray-operator
    State:          Running
      Started:      Thu, 03 Feb 2022 13:05:03 -0600
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  2Gi
    Requests:
      cpu:                1
      ephemeral-storage:  1Gi
      memory:             1Gi
    Environment:
      AUTOSCALER_MAX_NUM_FAILURES:         inf
      AUTOSCALER_MAX_LAUNCH_BATCH:         9999
      AUTOSCALER_MAX_CONCURRENT_LAUNCHES:  9999
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wq2kl (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  kube-api-access-wq2kl:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

### Versions / Dependencies

Ray Operator Image: rayproject/ray:bbc64e
Ray Client Version: 1.9.2
Python 3.8
Kubernetes Version: 1.21 with EKS

### Reproduction script

```python3
from pprint import pprint

import ray
ray.init("ray://mycluster.internal:10001")

@ray.remote
def task():
    import time
    time.sleep(30)

pprint(ray.cluster_resources())
results = ray.get([task.remote() for _ in range(200)])
```

### Anything else

This issue occurs every time.

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by fishbone**
## Why are these changes needed?

When there is no scheduling task of scheduling class in local raylet, the backlog resource will not be reported. It usually will happen when core worker try to schedule the task on other node and report backlog to local node.

This will lead to the wrong demands.

## Related issue number
Closes https://github.com/ray-project/ray/issues/22122

## Checks

- [ ] I've run `scripts/format.sh` to lint the changes in this PR.
- [ ] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [ ] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [ ] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

**Comment by iycheng** [comment]
Hmmm, the fix is not correct... :(

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 1]
```diff
@@ -64,103 +67,62 @@ void SchedulerResourceReporter::FillResourceUsage(
...
-      // Add to `resource_loads`.
-      const auto &label = resource.first;
-      const auto &quantity = resource.second;
-      (*resource_loads)[label] += quantity * count;
-
-      // Add to `resource_load_by_shape`.
-      (*by_shape_entry->mutable_shape())[label] = quantity;
-    }
+  absl::flat_hash_set<SchedulingClass> visited;
+  auto transform_func = [](auto &pair) {
```
Comment (jjyao) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:71]: nit: const auto&

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 2]
```diff
@@ -64,103 +67,62 @@ void SchedulerResourceReporter::FillResourceUsage(
...
+    return std::make_pair(pair.first, pair.second.size());
+  };
+  auto fill_resource_usage_helper = [&](auto &range, bool is_infeasible) mutable {
```
Comment (jjyao) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:74]: const auto&?

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 3]
```diff
@@ -64,103 +67,62 @@ void SchedulerResourceReporter::FillResourceUsage(
...
+      const auto &resources =
+          TaskSpecification::GetSchedulingClassDescriptor(scheduling_class)
+              .resource_set.GetResourceMap();
+      auto by_shape_entry = resource_load_by_shape->Add();
+
+      for (const auto &resource : resources) {
+        // Add to `resource_loads`.
+        const auto &label = resource.first;
+        const auto &quantity = resource.second;
+        (*resource_loads)[label] += quantity * count;
```
Comment (jjyao) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:97]: `quantity * count` only makes sense for tasks_to_schedule_, tasks_to_dispatch_, infeasible_tasks_. backlog_tracker_ doesn't add to resource_loads.

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 4]
```diff
@@ -64,103 +67,66 @@ void SchedulerResourceReporter::FillResourceUsage(
...
-      const auto &label = resource.first;
-      const auto &quantity = resource.second;
-      (*resource_loads)[label] += quantity * count;
-
-      // Add to `resource_load_by_shape`.
-      (*by_shape_entry->mutable_shape())[label] = quantity;
-    }
+      if (visited.count(scheduling_class) != 0) {
+        continue;
+      }
```
Comment (jjyao) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:83]: Actually we can have the same scheduling class in both tasks_to_schedule_ and tasks_to_dispatch_, won't we miss counting resource_loads if we early return here?

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 5]
```diff
@@ -64,103 +67,66 @@ void SchedulerResourceReporter::FillResourceUsage(
...
+          (*by_shape_entry->mutable_shape())[label] = quantity;
+        }
+      }
+
+      if (is_infeasible) {
+        by_shape_entry->set_num_infeasible_requests_queued(count);
+      } else {
+        by_shape_entry->set_num_ready_requests_queued(count);
+      }
+      by_shape_entry->set_backlog_size(TotalBacklogSize(scheduling_class));
```
Comment (jjyao) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:107]: Now I'm wondering if the existing code is wrong: for the same scheduling_class, we may create multiple by_shape_entry since the same scheduling_class can appear in multiple task queues, and each sets backlog size to the same. Won't autoscaler get wrong result if it sums them up?

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 6]
```diff
@@ -64,103 +67,66 @@ void SchedulerResourceReporter::FillResourceUsage(
...
-      // Add to `resource_loads`.
-      const auto &label = resource.first;
-      const auto &quantity = resource.second;
-      (*resource_loads)[label] += quantity * count;
-
-      // Add to `resource_load_by_shape`.
-      (*by_shape_entry->mutable_shape())[label] = quantity;
-    }
+      if (visited.count(scheduling_class) != 0) {
+        continue;
```
Comment (wuisawesome) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:82]: what's this for? it feels like this will make us skip separate scheduling classes with the same shape?

File: python/ray/tests/test_scheduling_2.py [hunk 7]
```diff
@@ -304,6 +306,51 @@ def task2():
         assert set(ray.get(locations)) == worker_node_ids
 
 
+def test_demand_report_when_scale_up(shutdown_only):
```
Comment (ericl) [inline python/ray/tests/test_scheduling_2.py:309]: Does this test fail before the fix?

File: python/ray/tests/test_scheduling_2.py [hunk 8]
```diff
@@ -304,6 +306,51 @@ def task2():
...
+    global_state_accessor = make_global_state_accessor(info)
+
+    def get_backlog_size():
+        message = global_state_accessor.get_all_resource_usage()
+        if message is None:
+            return 0
+
+        resource_usage = gcs_utils.ResourceUsageBatchData.FromString(message)
+        aggregate_resource_load = resource_usage.resource_load_by_shape.resource_demands
+        if len(aggregate_resource_load) == 1:
```
Comment (wuisawesome) [inline python/ray/tests/test_scheduling_2.py:347]: can you assert that the shape is right here too? like it should have `{"CPU": 1}`.

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 9]
```diff
@@ -64,103 +67,66 @@ void SchedulerResourceReporter::FillResourceUsage(
...
+
+      if (count != 0) {
+        for (const auto &resource : resources) {
+          // Add to `resource_loads`.
+          const auto &label = resource.first;
+          const auto &quantity = resource.second;
+          (*resource_loads)[label] += quantity * count;
+
+          // Add to `resource_load_by_shape`.
+          (*by_shape_entry->mutable_shape())[label] = quantity;
```
[the remark this answers is not in the document]
Comment (wuisawesome) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:98]: i think this is fine? num_cpus=0 can show up as an empty resource set.

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc (hunk 5 above)
Comment (wuisawesome) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:107]: I think it works out because the `resource_load_by_shape` will just look like `[{shape={"CPU":1}, num_queued=2}, {shape={"CPU":1}, num_queued=3}]` And the autoscaler won't care and will just expand it out to be 5 * {CPU: 1} demands.

**Review by wuisawesome — CHANGES_REQUESTED** [review]
I think you have 2 bugs that cancelled out in test cases here. I think some test like 

```
@ray.remote
def f():
 sleep(10000)

@ray.remote
def g():
 ray.get(h.remote())

@ray.remote
def h():
 sleep(10000)

ray.get([f.remote() for _ in range(10000)].extend([g.remote() for _ in range(1000)]))
```

will fail (note that the nested task is just one way of causing 2 tasks to have the same resource shape but separate scheduling classes. (it may not hurt to also have a test case with 2 tasks of the same resource shape but different scheduling classes, but i leave that up to you).

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc (hunk 9 above)
[the remark this answers is not in the document]
Comment (jjyao) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:98]: oh, count here is not num_cpus

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc (hunk 5 above)
Comment (jjyao) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:107]: Yea, `num_queued` is fine since autoscaler should just add them up. I'm worried about `backlog_size` since it sets to the same total for same shape: `[{shape={"CPU":1}, num_queued=2, backlog_size=100}, {shape={"CPU":1}, num_queued=3, backlog_size=100}]`, total backlog_size should be 100 not 200? I need to read autoscaler code to see how backlog_size is used.

Comment (wuisawesome) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:107]: oh you're right that's a bug in the existing code (assuming we're parallelizing lease requests, which tbh i don't remember if that's on by default 😅)

Comment (jjyao) [reply src/ray/raylet/scheduling/scheduler_resource_reporter.cc:107]: Yea it's on by default with parallelism 10 (even if it's off we still have the same issue I think since we can still have multiple by_shape_entry with the same shape caused by lease requests from different workers).

File: python/ray/tests/test_scheduling_2.py (hunk 7 above)
Comment (iycheng) [reply python/ray/tests/test_scheduling_2.py:309]: Yes because the demand will always be 10.

**Comment by iycheng** [comment]
@wuisawesome  thanks for catch up the issue. I think I lack some knowledge about schedule cls here.

I've updated the code and also use your test case in the code.

I'm thinking about the bug @jjyao  mentioned. I think this code should have already fixed that. I plan to add a test case for this as well. But is there some suggestion about how to construct that?

File: src/ray/raylet/scheduling/scheduler_resource_reporter.cc [hunk 10]
```diff
@@ -64,103 +68,67 @@ void SchedulerResourceReporter::FillResourceUsage(
...
+        (*by_shape_entry->mutable_shape())[label] = quantity;
+      }
+
+      if (is_infeasible) {
+        by_shape_entry->set_num_infeasible_requests_queued(count);
+      } else {
+        by_shape_entry->set_num_ready_requests_queued(count);
+      }
+
+      // Backlog has already been set
```
Comment (jjyao) [inline src/ray/raylet/scheduling/scheduler_resource_reporter.cc:105]: Nice.

**Review by jjyao — APPROVED** [review]
Let's get an approval from @wuisawesome as well before merging.

**Review by wuisawesome — APPROVED** [review]
lgtm now. 

re: your point on @jjyao 's edge case, I think the main 2 ways to force a task to be stuck on the dispatch queue is to either use a runtime env that takes a long time to set up, or to use nested tasks to trigger rate limiting of worker startup.

**Comment by iycheng** [comment]
@wuisawesome  it seems that's not working :( I use a long-running runtime env, it seems not triggering the bug. I'll leave it there for now since this is a P0 issue.
