### PR TITLE
[Core] Actor Retries Out of Order Tasks on Restart

### LINKED ISSUE #11683: [core] Async Actor Task fails when `max_retries=-1`
### What is the problem?
An actor task fails when the actor dies, _despite_ having `max_retries=-1` & `max_restart=-1`

*Ray version and other system information (Python version, TensorFlow version, OS):*

### Reproduction (REQUIRED)
The easiest way to test this is with Serve
1. Add the following method to `python/ray/serve/controller.py::ServeController`
```
    def _test_crash(self):
        os._exit(0)
```
2. Add the following between L44 & L45 (the assert) in `python/ray/serve/tests/test_standalone.py`:
```
    with pytest.raises(ray.exceptions.RayActorError):
        ray.get(client._controller._test_crash.remote())
```
3. Run `python -m pytest -sv python/ray/serve/tests/test_standalone.py::test_detached_deployment`

Please provide a script that can be run to reproduce the issue. The script should have **no external library dependencies** (i.e., use fake or mock data / environments):

If we cannot run your script, we cannot fix your issue.

- [ ] I have verified my script runs in a clean environment and reproduces the issue.
- [ ] I have verified the issue also occurs with the [latest wheels](https://docs.ray.io/en/latest/installation.html).

### PR DESCRIPTION
**Pull request by simon-mo**
## Why are these changes needed?
This PR fixes #11683. The solution I settled on was:
- Submitter keep tracks of all the tasks that were completed out of order.
- On actor restart, submitter will submit all these tasks once, with a flag `skip_execution=true`.
- The receiver will simple just record these tasks for ordering purpose and directly return status::Ok() without execution.
 

## Checks

- [x] I've run `scripts/format.sh` to lint the changes in this PR.
- [x] I've included any doc changes needed for https://docs.ray.io/en/master/.
- [x] I've made sure the tests are passing. Note that there might be a few flaky tests, see the recent failures at https://flakey-tests.ray.io/
- Testing Strategy
   - [x] Unit tests
   - [ ] Release tests
   - [ ] This PR is not tested :(

### CODE REVIEW

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 1]
```diff
@@ -217,36 +218,57 @@ void CoreWorkerDirectActorTaskSubmitter::DisconnectActor(const ActorID &actor_id
...
-    RAY_CHECK(!it->second.worker_id.empty());
-    PushActorTask(it->second, task_spec, skip_queue);
-    it->second.next_send_position++;
+    RAY_CHECK(!client_queue.worker_id.empty());
+    PushActorTask(client_queue, task_spec, skip_queue);
+    client_queue.next_send_position++;
+  }
+
+  // Send all out of order compeleted tasks to the actor.
+  if (send_out_of_order_tasks) {
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:257]: Since we're only doing this upon the initial connection, I think it is clearer to move this code into `ConnectActor` instead of doing it under the if-check (maybe as a separate helper function).

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 2]
```diff
@@ -266,30 +288,54 @@ void CoreWorkerDirectActorTaskSubmitter::PushActorTask(const ClientQueue &queue,
 
   const auto task_id = task_spec.TaskId();
   const auto actor_id = task_spec.ActorId();
-  const auto counter = task_spec.ActorCounter();
+  const auto actor_counter = task_spec.ActorCounter();
+  const auto task_skipped = task_spec.GetMessage().skip_execution();
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:292]: What do you think about not having the task_skipped flag and letting the actor re-execute the out-of-order tasks? I could see use cases for both, so I'd prefer to start with no flag.

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 3]
```diff
@@ -266,30 +288,54 @@ void CoreWorkerDirectActorTaskSubmitter::PushActorTask(const ClientQueue &queue,
...
           absl::MutexLock lock(&mu_);
-          auto queue = client_queues_.find(actor_id);
-          RAY_CHECK(queue != client_queues_.end());
-          queue->second.num_completed_tasks++;
+          auto queue_pair = client_queues_.find(actor_id);
+          RAY_CHECK(queue_pair != client_queues_.end());
+          auto &queue = queue_pair->second;
+
+          // Keep increment queue.num_completed_tasks for the contintoues block
+          // of completed task counters.
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:320]: Could you expand the comment to explain what other state gets updated?

File: src/ray/core_worker/transport/direct_actor_transport.h [hunk 4]
```diff
@@ -184,6 +186,14 @@ class CoreWorkerDirectActorTaskSubmitter
     /// actor failure.
     uint64_t num_completed_tasks = 0;
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.h:187]: Can you update the doc for this member to explain that it only tracks consecutive tasks? Maybe we should call this something different to indicate that it's the next task counter that we're expecting.

**Review by stephanie-wang — CHANGES_REQUESTED** [review]

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 2 above)
Comment (simon-mo) [reply src/ray/core_worker/transport/direct_actor_transport.cc:292]: The out of order tasks can be potentially very expensive to execute and mutate the state in undesirable way. Two examples in Serve:

## Serve Controller
1. `__init__` # reconstruct the state from internal kv upon restart
2. `start_control_loop()` # long running
3. `create_backend()` # state mutating and starting new actors, but we checkpoint the state to internal kv
4. `create_endpoint()` # state mutating but the state is checkpointed to internal kv.

After restart, we don't want to re-run task 3 and 4 because the state is already reconstructed. 

## Serve Replica (e.g. running ML models)
1. `__init__`
2. `handle_request` # takes longer to run
3. `handle_request` # finished
4. ...

After restart, we don't want to rerun the computation for task 3 but we do want to retry task 2. Additionally, re-running task 3 will slow down the replica and do unnecessary compute work. 

## Sidenote
I understand the library can adopt to any ray core semantic changes. but it does seem like completed actor task won't be executed is a good semantic guarantee.

File: src/ray/protobuf/common.proto [hunk 5]
```diff
@@ -196,6 +196,9 @@ message TaskSpec {
   bool placement_group_capture_child_tasks = 20;
   // Environment variables to override for this task
   map<string, string> override_environment_variables = 21;
+  // Whether or not to skip the execution of this task and only use this task for
+  // task ordering purpose.
```
Comment (stephanie-wang) [inline src/ray/protobuf/common.proto:200]: Can you include more context in this comment? It's hard to understand what "task ordering purpose" means.

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 6]
```diff
@@ -266,30 +288,54 @@ void CoreWorkerDirectActorTaskSubmitter::PushActorTask(const ClientQueue &queue,
...
   rpc::Address addr(queue.rpc_client->Addr());
   queue.rpc_client->PushActorTask(
       std::move(request), skip_queue,
-      [this, addr, task_id, actor_id](Status status, const rpc::PushTaskReply &reply) {
+      [this, addr, task_id, actor_id, actor_counter, task_spec, task_skipped](
+          Status status, const rpc::PushTaskReply &reply) {
         bool increment_completed_tasks = true;
+
         if (!status.ok()) {
           bool will_retry = task_finisher_->PendingTaskFailed(
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:304]: What happens if `!status.ok() && task_skipped`? I'm not sure if it's okay to mark an already completed task as failed.

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 7]
```diff
@@ -406,6 +452,9 @@ void CoreWorkerDirectTaskReceiver::HandleTask(
   auto reject_callback = [send_reply_callback]() {
     send_reply_callback(Status::Invalid("client cancelled stale rpc"), nullptr, nullptr);
   };
+  auto skip_callback = [send_reply_callback]() {
+    send_reply_callback(Status::OK(), nullptr, nullptr);
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:456]: Could we just put this logic into the normal accept callback instead of passing a separate skip callback?

**Review by stephanie-wang — COMMENTED** [review]
Can you also add unit tests to `src/ray/core_worker/test/direct_actor_transport_test.cc`?

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 2 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_actor_transport.cc:292]: I see. I think there are still use cases for re-executing the out-of-order tasks, but I guess we can try this first.

Actually, I don't really understand the serve controller use case. Why would 3 and 4 get re-executed?

Can you also update the docs here to explain what the guarantees are for async actors? https://docs.ray.io/en/master/fault-tolerance.html#actors

File: src/ray/core_worker/transport/direct_actor_transport.h (hunk 4 above)
Comment (simon-mo) [reply src/ray/core_worker/transport/direct_actor_transport.h:188]: Added some comments but can't really think of a better name

File: doc/source/fault-tolerance.rst [hunk 8]
```diff
@@ -163,6 +163,12 @@ semantics. If the actor’s exact state at the time of failure is needed, the
 application is responsible for resubmitting all tasks since the last
 checkpoint.
 
+.. note::
+    For :ref:`async actor or threaded actors <async-actors>`, the tasks might
```
Comment (edoakes) [inline doc/source/fault-tolerance.rst:167]:
```suggestion
    For :ref:`async or threaded actors <async-actors>`, the tasks might
```

File: python/ray/serve/tests/test_long_poll.py [hunk 9]
```diff
@@ -38,34 +39,41 @@ def test_host_standalone(serve_instance):
...
 
     on_going_ref = host.listen_for_change.remote({"timer": timer.snapshot_id})
-    host.exit.remote()
-    on_going_ref = host.listen_for_change.remote({"timer": timer.snapshot_id})
+    ray.get(host.set_exit.remote())
+    # This task should trigger the actor to exit.
+    # But the retried task will not because self.should_exit is false.
+    host.exit_if_set.remote()
+
+    # on_going_ref should return succesfully with a differnt value.
```
Comment (edoakes) [inline python/ray/serve/tests/test_long_poll.py:76]:
```suggestion
    # on_going_ref should return successfully with a different value.
```

File: src/ray/core_worker/core_worker.cc [hunk 10]
```diff
@@ -436,6 +436,7 @@ CoreWorker::CoreWorker(const CoreWorkerOptions &options, const WorkerID &worker_
   };
   task_manager_.reset(new TaskManager(
       memory_store_, reference_counter_,
+      /*retry_task_callback*/
       [this](TaskSpecification &spec, bool delay) {
```
Comment (edoakes) [inline src/ray/core_worker/core_worker.cc:440]:
```suggestion
      /* retry_task_callback= */[this](TaskSpecification &spec, bool delay) {
```

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 11]
```diff
@@ -223,33 +225,59 @@ void CoreWorkerDirectActorTaskSubmitter::SendPendingTasks(const ActorID &actor_i
...
+void CoreWorkerDirectActorTaskSubmitter::ResendOutOfOrderTasks(const ActorID &actor_id) {
+  auto it = client_queues_.find(actor_id);
+  RAY_CHECK(it != client_queues_.end());
+  if (!it->second.rpc_client) {
+    return;
+  }
+  auto &client_queue = it->second;
+
+  for (const auto &completed_task : client_queue.out_of_order_completed_tasks) {
+    // Making an copy here because we are flipping a flag and the original value is
```
Comment (edoakes) [inline src/ray/core_worker/transport/direct_actor_transport.cc:266]:
```suggestion
    // Making a copy here because we are flipping a flag and the original value is
```

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 12]
```diff
@@ -223,33 +225,59 @@ void CoreWorkerDirectActorTaskSubmitter::SendPendingTasks(const ActorID &actor_i
...
+    // const.
+    TaskSpecification task_spec = completed_task.second;
+    // Calling SubmitTask in event loop to avoid deadlock condition. SubmitTask holds
+    // the mu_ and calls this method, we can't call SubmitTask recursively.
+    io_service_.post([this, task_spec]() mutable {
```
Comment (edoakes) [inline src/ray/core_worker/transport/direct_actor_transport.cc:271]: Unless I'm mistaken, I believe this is making two copies -> one when you do the assignment operator and then a second when you capture it in the `io_service_.post` call. We should only make the second copy.

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 13]
```diff
@@ -166,7 +166,9 @@ void CoreWorkerDirectActorTaskSubmitter::ConnectActor(const ActorID &actor_id,
                 << queue->second.caller_starts_at << " to "
                 << queue->second.num_completed_tasks;
   queue->second.caller_starts_at = queue->second.num_completed_tasks;
+
   SendPendingTasks(actor_id);
+  ResendOutOfOrderTasks(actor_id);
```
Comment (edoakes) [inline src/ray/core_worker/transport/direct_actor_transport.cc:171]: To make sure I'm understanding correctly: the sequence numbers of these may not be in order (e.g., we send some earlier tasks in the `ResendOutOfOrderTasks` than we do in `SendPendingTasks`, but that's ok because we're relying on the receiver-side ordering, right?

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 2 above)
Comment (edoakes) [reply src/ray/core_worker/transport/direct_actor_transport.cc:298]: Not sure the controller case is relevant. Those methods are effectively synchronous anyways because they hold a lock during execution so they won't happen out of order.

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 6 above)
Comment (edoakes) [reply src/ray/core_worker/transport/direct_actor_transport.cc:314]: We wouldn't mark it as failed in this case because we check the task_skipped condition first, right? Maybe this comment was on outdated code

File: doc/source/fault-tolerance.rst [hunk 14]
```diff
@@ -163,6 +163,12 @@ semantics. If the actor’s exact state at the time of failure is needed, the
...
+    be completed out of order. Upon actor restarts, the system will only retry
+    incomplete tasks in their initial submission order. This prevent unnecessary
+    re-execution of previous completed tasks.
```
Comment (stephanie-wang) [inline doc/source/fault-tolerance.rst:170]:
```suggestion
    be completed out of order. Upon actor restart, the system will only retry
    *incomplete* tasks, in their initial submission order. Previously completed
    tasks will not be re-executed.
```

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 13 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_actor_transport.cc:171]: Maybe we should call this `ResendIncompleteTasks` instead? Also, does it make sense to do this before `SendPendingTasks` (not sure if it makes a difference, but it seems more intuitive)?

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 15]
```diff
@@ -223,33 +225,59 @@ void CoreWorkerDirectActorTaskSubmitter::SendPendingTasks(const ActorID &actor_i
...
+    // Making an copy here because we are flipping a flag and the original value is
+    // const.
+    TaskSpecification task_spec = completed_task.second;
+    // Calling SubmitTask in event loop to avoid deadlock condition. SubmitTask holds
+    // the mu_ and calls this method, we can't call SubmitTask recursively.
+    io_service_.post([this, task_spec]() mutable {
+      task_spec.GetMutableMessage().set_skip_execution(true);
+      // Call SubmitTask instead of PushActorTask here because we need to re-add the
+      // task to the task queue.
+      RAY_CHECK_OK(SubmitTask(task_spec));
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:275]: Actually, could we just push the task onto the queue directly? I'm not sure if we need to go through `SubmitTask` again. Then we don't need to re-acquire the lock, plus we can just send all the incomplete tasks immediately during the following `SendPendingTasks` call.

File: src/ray/core_worker/transport/direct_actor_transport.cc [hunk 16]
```diff
@@ -266,16 +294,23 @@ void CoreWorkerDirectActorTaskSubmitter::PushActorTask(const ClientQueue &queue,
...
   queue.rpc_client->PushActorTask(
       std::move(request), skip_queue,
-      [this, addr, task_id, actor_id](Status status, const rpc::PushTaskReply &reply) {
+      [this, addr, task_id, actor_id, actor_counter, task_spec, task_skipped](
+          Status status, const rpc::PushTaskReply &reply) {
         bool increment_completed_tasks = true;
-        if (!status.ok()) {
+
+        if (task_skipped) {
+          // Increment the task counter regardless of the status this is the reply for
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.cc:310]:
```suggestion
          // Increment the task counter regardless of the status because this is the reply for
```

File: src/ray/core_worker/transport/direct_actor_transport.h (hunk 4 above)
Comment (stephanie-wang) [reply src/ray/core_worker/transport/direct_actor_transport.h:188]: How about `next_task_reply_position_`?

File: src/ray/core_worker/transport/direct_actor_transport.h [hunk 17]
```diff
@@ -209,6 +221,15 @@ class CoreWorkerDirectActorTaskSubmitter
   /// \return Void.
   void SendPendingTasks(const ActorID &actor_id) EXCLUSIVE_LOCKS_REQUIRED(mu_);
 
+  /// Resend all previously-received, out-of-order, received tasks for an actor.
+  /// When sending these tasks, the tasks will have the flag skip_execution=true.
+  /// Note that this function doesn't take lock, the caller is expected to hold
```
Comment (stephanie-wang) [inline src/ray/core_worker/transport/direct_actor_transport.h:226]: Not really necessary, the thread annotations are enough to guard against this.

File: src/ray/core_worker/test/direct_actor_transport_test.cc [hunk 18]
```diff
@@ -106,13 +106,14 @@ class DirectActorSubmitterTest : public ::testing::Test {
...
             }),
-            store_, task_finisher_) {}
+            store_, task_finisher_, io_service_) {}
 
   int num_clients_connected_ = 0;
   std::shared_ptr<MockWorkerClient> worker_client_;
   std::shared_ptr<CoreWorkerMemoryStore> store_;
   std::shared_ptr<MockTaskFinisher> task_finisher_;
   CoreWorkerDirectActorTaskSubmitter submitter_;
+  boost::asio::io_service io_service_;
```
Comment (stephanie-wang) [inline src/ray/core_worker/test/direct_actor_transport_test.cc:116]: Can you a unit test for out-of-order task completion and resending? You can use the same scenarios that you have in Python, but it's good to have the C++ tests.

File: src/ray/core_worker/core_worker.cc (hunk 10 above)
Comment (simon-mo) [reply src/ray/core_worker/core_worker.cc:440]: clang-format just won't put them on the same line lol

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 13 above)
Comment (simon-mo) [reply src/ray/core_worker/transport/direct_actor_transport.cc:171]: @edoakes your understanding is correct, i'll add a comment.
@stephanie-wang i'm confused. `ResendOutofOrderTasks` are resending tasks that were completed before again just so the receiver can keep track of all of seqnos. It really isn't `ResendIncompleteTasks`?

File: src/ray/core_worker/transport/direct_actor_transport.cc (hunk 12 above)
Comment (simon-mo) [reply src/ray/core_worker/transport/direct_actor_transport.cc:271]: Tried but turns out we can't do it in C++11 https://stackoverflow.com/questions/24221061/lambda-capture-list-capturing-objects-member-field-by-value-not-possible-witho

This is because if we just pass the first task_spec without copying, compiler complains because it's const (yes even when it's mutable), so we have to copy it to de-const it.

**Review by stephanie-wang — APPROVED** [review]
Thanks, looks great!
